<!--
                 This page has been created by Renaissance IT
   Renaissance Internet Technologies Copyright (c) 1999 All Rights Reserved.

             for more info on our products, please visit :
                        http://www.renaissance.nl/

	This script has been written by Roy Boverhof <rboverhof@renaissance.nl>
	
        Pagename                : current_jewelry.html
        Last Updated    		: 31-01-2000
-->

<HTML>
<HEAD>
	<TITLE>the Seekers of Lore : Current Jewelry Chart</TITLE>
</HEAD>

<BODY BGCOLOR="#000000" TEXT="#000000" LINK="#000000" VLINK="#000000" ALINK="#000000">
<DIV ALIGN="CENTER">
<BR>
<!-- FGN Banner Code -->
<script language="JavaScript">
	<!-- Hide from old browsers
	var random = new Number(Math.floor(9999999 * Math.random())+1);

	// Modify to reflect site specifics
	page = "eqlore.com/";
	target = "@Top1,x02,x05,x08!Top1";

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript1.1" SRC="http://oascentral.cybereps.com/RealMedia/ads/adstream_jx.ads/' + page + 1 + random + target + '">');
	document.write('</SCR');
	document.write('IPT>');

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript">');
	document.write('_version=10; //-->');
	document.write('</SCR');
	document.write('IPT>');

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript1.1">');
	document.write('_version=11; //-->');
	document.write('</SCR');
	document.write('IPT>');

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript">');

	if (navigator.appVersion.indexOf('MSIE 3') != -1){
	document.write('<IFRAME MARGINWIDTH=0 MARGINHEIGHT=0 HSPACE=0 VSPACE=0 FRAMEBORDER=0 SCROLLING=no BORDERCOLOR="#000000" SRC="oascentral.cybereps.com/RealMedia/ads/adstream_sx.ads/' + page + random + target + '"></IFRAME>');
	  }
	else if (_version < 11) {
	document.write ('<A HREF="http://oascentral.cybereps.com/RealMedia/ads/click_nx.ads/' + page + random + target + '"><IMG SRC="http://oascentral.cybereps.com/RealMedia/ads/adstream_nx.ads/' + page + random + target + '"></a>');
	  }

	document.write('</SCR');
	document.write('IPT>');

	// End Hide -->
</script>
<!-- END FGN Banner Code --><BR>
<TABLE CELLSPACING = 0 CELLPADDING = 0 BORDER = 0>
<TR>
	<TD width="63"><IMG SRC = "http://www.loreseekers.com/graphics/topc000.jpg" WIDTH = 63 HEIGHT = 87></TD>
	<TD width="473"><IMG SRC = "http://www.loreseekers.com/graphics/topc001.jpg" WIDTH = 473 HEIGHT = 87></TD>
	<TD width="64"><IMG SRC = "http://www.loreseekers.com/graphics/topc002.jpg" WIDTH = 64 HEIGHT = 87></TD>
</TR>
	<TD width="63"></TD>
	<TD BGCOLOR="#BEA279" width="460">
	<DIV ALIGN="CENTER">
	<TABLE>
	<TR>
	<TD BGCOLOR="#BEA279" width="450">

<P ALIGN="left"><FONT SIZE="4" face="helvetica"><STRONG>A. Current Jewelry</STRONG></FONT></A></P>


<!-- START OF CURRENT JEWELRY -->
<!-- ------------------------- -->
<Table border BGCOLOR="#BEA279">
<TR VALIGN="bottom">
<TD BGCOLOR=#800000 ALIGN="center"><FONT FACE="Verdana" SIZE="1" COLOR=#FFFFFF><B>
Item</B></FONT></TD>
<TD BGCOLOR=#800000 ALIGN="center"><FONT FACE="Verdana" SIZE="1" COLOR=#FFFFFF><B>
Gem</B></FONT></TD>
<TD BGCOLOR=#800000 ALIGN="center"><FONT FACE="Verdana" SIZE="1" COLOR=#FFFFFF><B>
Metal</B></FONT></TD>
<TD BGCOLOR=#800000 ALIGN="center"><FONT FACE="Verdana" SIZE="1" COLOR=#FFFFFF><B>
Cost (cp)</B></FONT></TD>
<TD ALIGN="right"><FONT FACE="Verdana" SIZE="1">
&nbsp;</FONT></TD>
<TD ALIGN="right"><FONT FACE="Verdana" SIZE="1">
&nbsp;</FONT></TD>
<TD ALIGN="right"><FONT FACE="Verdana" SIZE="1">
&nbsp;</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD BGCOLOR=#C0C0C0 ALIGN="center"><FONT FACE="Verdana" SIZE="1" COLOR=#000000><B>
Ring</B></FONT></TD>
<TD BGCOLOR=#FFFFCC ALIGN="center"><FONT FACE="Verdana" SIZE="1" COLOR=#000000><B>
Merchant</B></FONT></TD>
<TD BGCOLOR=#C0C0C0 ALIGN="center"><FONT FACE="Verdana" SIZE="1">
Silver</FONT></TD>
<TD BGCOLOR=#C0C0C0 ALIGN="center"><FONT FACE="Verdana" SIZE="1">
525</FONT></TD>
<TD ALIGN="right"><FONT FACE="Verdana" SIZE="1">
&nbsp;</FONT></TD>
<TD ALIGN="right"><FONT FACE="Verdana" SIZE="1">
&nbsp;</FONT></TD>
<TD ALIGN="right"><FONT FACE="Verdana" SIZE="1">
&nbsp;</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD BGCOLOR=#00FF00 ALIGN="center"><FONT FACE="Verdana" SIZE="1" COLOR=#000000><B>
Necklace</B></FONT></TD>
<TD BGCOLOR=#FF9900 ALIGN="center"><FONT FACE="Verdana" SIZE="1" COLOR=#000000><B>
Monster Loot</B></FONT></TD>
<TD BGCOLOR=#C0C0C0 ALIGN="center"><FONT FACE="Verdana" SIZE="1">
Electrum</FONT></TD>
<TD BGCOLOR=#C0C0C0 ALIGN="center"><FONT FACE="Verdana" SIZE="1">
2625</FONT></TD>
<TD ALIGN="right"><FONT FACE="Verdana" SIZE="1">
&nbsp;</FONT></TD>
<TD ALIGN="right"><FONT FACE="Verdana" SIZE="1">
&nbsp;</FONT></TD>
<TD ALIGN="right"><FONT FACE="Verdana" SIZE="1">
&nbsp;</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD BGCOLOR=#FFCC00 ALIGN="center"><FONT FACE="Verdana" SIZE="1" COLOR=#000000><B>
Earring</B></FONT></TD>
<TD ALIGN="right"><FONT FACE="Verdana" SIZE="1">
&nbsp;</FONT></TD>
<TD BGCOLOR=#C0C0C0 ALIGN="center"><FONT FACE="Verdana" SIZE="1">
Gold</FONT></TD>
<TD BGCOLOR=#C0C0C0 ALIGN="center"><FONT FACE="Verdana" SIZE="1">
10500</FONT></TD>
<TD ALIGN="right"><FONT FACE="Verdana" SIZE="1">
&nbsp;</FONT></TD>
<TD ALIGN="right"><FONT FACE="Verdana" SIZE="1">
&nbsp;</FONT></TD>
<TD ALIGN="right"><FONT FACE="Verdana" SIZE="1">
&nbsp;</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD BGCOLOR=#FF00FF ALIGN="center"><FONT FACE="Verdana" SIZE="1" COLOR=#000000><B>
Face</B></FONT></TD>
<TD ALIGN="right"><FONT FACE="Verdana" SIZE="1">
&nbsp;</FONT></TD>
<TD BGCOLOR=#C0C0C0 ALIGN="center"><FONT FACE="Verdana" SIZE="1">
Platinum</FONT></TD>
<TD BGCOLOR=#C0C0C0 ALIGN="center"><FONT FACE="Verdana" SIZE="1">
105000</FONT></TD>
<TD ALIGN="right"><FONT FACE="Verdana" SIZE="1">
&nbsp;</FONT></TD>
<TD ALIGN="right"><FONT FACE="Verdana" SIZE="1">
&nbsp;</FONT></TD>
<TD ALIGN="right"><FONT FACE="Verdana" SIZE="1">
&nbsp;</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD BGCOLOR=#33CCCC ALIGN="center"><FONT FACE="Verdana" SIZE="1" COLOR=#000000><B>
Bracelet</B></FONT></TD>
<TD ALIGN="right"><FONT FACE="Verdana" SIZE="1">
&nbsp;</FONT></TD>
<TD ALIGN="right"><FONT FACE="Verdana" SIZE="1">
&nbsp;</FONT></TD>
<TD ALIGN="right"><FONT FACE="Verdana" SIZE="1">
&nbsp;</FONT></TD>
<TD ALIGN="right"><FONT FACE="Verdana" SIZE="1">
&nbsp;</FONT></TD>
<TD ALIGN="right"><FONT FACE="Verdana" SIZE="1">
&nbsp;</FONT></TD>
<TD ALIGN="right"><FONT FACE="Verdana" SIZE="1">
&nbsp;</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="right"><FONT FACE="Verdana" SIZE="1">
&nbsp;</FONT></TD>
<TD ALIGN="right"><FONT FACE="Verdana" SIZE="1">
&nbsp;</FONT></TD>
<TD ALIGN="right"><FONT FACE="Verdana" SIZE="1">
&nbsp;</FONT></TD>
<TD ALIGN="right"><FONT FACE="Verdana" SIZE="1">
&nbsp;</FONT></TD>
<TD ALIGN="right"><FONT FACE="Verdana" SIZE="1">
&nbsp;</FONT></TD>
<TD ALIGN="right"><FONT FACE="Verdana" SIZE="1">
&nbsp;</FONT></TD>
<TD ALIGN="right"><FONT FACE="Verdana" SIZE="1">
&nbsp;</FONT></TD>
</TR>
<TR ALIGN="center" VALIGN="bottom">
<TD COLSPAN=7><FONT FACE="Verdana" SIZE="1" COLOR=#800000><B>
CURRENT JEWELERY</B></FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="right"><FONT FACE="Verdana" SIZE="1">
&nbsp;</FONT></TD>
<TD ALIGN="right"><FONT FACE="Verdana" SIZE="1">
&nbsp;</FONT></TD>
<TD ALIGN="right"><FONT FACE="Verdana" SIZE="1">
&nbsp;</FONT></TD>
<TD ALIGN="right"><FONT FACE="Verdana" SIZE="1">
&nbsp;</FONT></TD>
<TD ALIGN="right"><FONT FACE="Verdana" SIZE="1">
&nbsp;</FONT></TD>
<TD ALIGN="right"><FONT FACE="Verdana" SIZE="1">
&nbsp;</FONT></TD>
<TD ALIGN="right"><FONT FACE="Verdana" SIZE="1">
&nbsp;</FONT></TD>
</TR>
<TR ALIGN="center" VALIGN="bottom">
<TD BGCOLOR=#800000><FONT FACE="Verdana" SIZE="1" COLOR=#FFFFFF><B>
Stone</B></FONT></TD>
<TD BGCOLOR=#800000><FONT FACE="Verdana" SIZE="1" COLOR=#FFFFFF><B>
Property</B></FONT></TD>
<TD BGCOLOR=#800000><FONT FACE="Verdana" SIZE="1" COLOR=#FFFFFF><B>
Cost (cp)</B></FONT></TD>
<TD BGCOLOR=#800000><FONT FACE="Verdana" SIZE="1" COLOR=#FFFFFF><B>
Ench Silver</B></FONT></TD>
<TD BGCOLOR=#800000><FONT FACE="Verdana" SIZE="1" COLOR=#FFFFFF><B>
Ench Elect</B></FONT></TD>
<TD BGCOLOR=#800000><FONT FACE="Verdana" SIZE="1" COLOR=#FFFFFF><B>
Ench Gold</B></FONT></TD>
<TD BGCOLOR=#800000><FONT FACE="Verdana" SIZE="1" COLOR=#FFFFFF><B>
Ench Plat</B></FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD BGCOLOR=#FFFFCC ALIGN="left"><FONT FACE="Verdana" SIZE="1">
Malachite</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
Vs Pois</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
52</FONT></TD>
<TD BGCOLOR=#C0C0C0 ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
 +2</FONT></TD>
<TD BGCOLOR=#33CCCC ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
 +3</FONT></TD>
<TD BGCOLOR=#33CCCC ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
 +5</FONT></TD>
<TD BGCOLOR=#C0C0C0 ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
 +7</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD BGCOLOR=#FFFFCC ALIGN="left"><FONT FACE="Verdana" SIZE="1">
Lapis Lazuli</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
Vs Dis</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
94</FONT></TD>
<TD BGCOLOR=#00FF00 ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
 +2</FONT></TD>
<TD BGCOLOR=#FFCC00 ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
 +3</FONT></TD>
<TD BGCOLOR=#FFCC00 ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
 +5</FONT></TD>
<TD BGCOLOR=#00FF00 ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
 +7</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD BGCOLOR=#FFFFCC ALIGN="left"><FONT FACE="Verdana" SIZE="1">
Turquiose</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
Vs Cold</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
115</FONT></TD>
<TD BGCOLOR=#33CCCC ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1">
 +2</FONT></TD>
<TD BGCOLOR=#C0C0C0 ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
 +3</FONT></TD>
<TD BGCOLOR=#C0C0C0 ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
 +5</FONT></TD>
<TD BGCOLOR=#33CCCC ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
 +7</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD BGCOLOR=#FFFFCC ALIGN="left"><FONT FACE="Verdana" SIZE="1">
Hematite</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
Vs Fire</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
157</FONT></TD>
<TD BGCOLOR=#C0C0C0 ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
 +2</FONT></TD>
<TD BGCOLOR=#00FF00 ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
 +4</FONT></TD>
<TD BGCOLOR=#00FF00 ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
 +7</FONT></TD>
<TD BGCOLOR=#C0C0C0 ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
 +7</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD BGCOLOR=#FFFFCC ALIGN="left"><FONT FACE="Verdana" SIZE="1">
Wolf's Eye Agate</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
Vs Magic</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
160</FONT></TD>
<TD BGCOLOR=#00FF00 ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
 +4</FONT></TD>
<TD BGCOLOR=#33CCCC ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
 +4</FONT></TD>
<TD BGCOLOR=#33CCCC ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
 +7</FONT></TD>
<TD BGCOLOR=#00FF00 ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
 +9</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD BGCOLOR=#FFFFCC ALIGN="left"><FONT FACE="Verdana" SIZE="1">
Cat's Eye Agate</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
CHR</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
210</FONT></TD>
<TD BGCOLOR=#00FF00 ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
 +3</FONT></TD>
<TD BGCOLOR=#33CCCC ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
 +4</FONT></TD>
<TD BGCOLOR=#33CCCC ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
 +7</FONT></TD>
<TD BGCOLOR=#00FF00 ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
 +9</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD BGCOLOR=#FFFFCC ALIGN="left"><FONT FACE="Verdana" SIZE="1">
Bloodstone</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
STA</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
525</FONT></TD>
<TD BGCOLOR=#FFCC00 ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
 +2</FONT></TD>
<TD BGCOLOR=#00FF00 ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
 +3</FONT></TD>
<TD BGCOLOR=#00FF00 ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
 +5</FONT></TD>
<TD BGCOLOR=#FFCC00 ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
 +6</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD BGCOLOR=#FFFFCC ALIGN="left"><FONT FACE="Verdana" SIZE="1">
Onyx</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
DEX</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
652</FONT></TD>
<TD BGCOLOR=#33CCCC ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
 +2</FONT></TD>
<TD BGCOLOR=#00FF00 ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
 +3</FONT></TD>
<TD BGCOLOR=#00FF00 ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
 +5</FONT></TD>
<TD BGCOLOR=#33CCCC ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
 +6</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD BGCOLOR=#FFFFCC ALIGN="left"><FONT FACE="Verdana" SIZE="1">
Jasper</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
WIS</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
787</FONT></TD>
<TD BGCOLOR=#C0C0C0 ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
 +2</FONT></TD>
<TD BGCOLOR=#FFCC00 ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
 +2</FONT></TD>
<TD BGCOLOR=#FFCC00 ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
 +3</FONT></TD>
<TD BGCOLOR=#C0C0C0 ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
 +6</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD BGCOLOR=#FFFFCC ALIGN="left"><FONT FACE="Verdana" SIZE="1">
Carnelian</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
AGI</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
892</FONT></TD>
<TD BGCOLOR=#C0C0C0 ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
 +2</FONT></TD>
<TD BGCOLOR=#C0C0C0 ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
 +3</FONT></TD>
<TD BGCOLOR=#C0C0C0 ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
 +5</FONT></TD>
<TD BGCOLOR=#C0C0C0 ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
 +7</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD BGCOLOR=#FFFFCC ALIGN="left"><FONT FACE="Verdana" SIZE="1">
Star Rose Quartz</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
INT</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
1050</FONT></TD>
<TD BGCOLOR=#C0C0C0 ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
 +2</FONT></TD>
<TD BGCOLOR=#00FF00 ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
 +2</FONT></TD>
<TD BGCOLOR=#00FF00 ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
 +4</FONT></TD>
<TD BGCOLOR=#C0C0C0 ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
 +4</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD BGCOLOR=#FFFFCC ALIGN="left"><FONT FACE="Verdana" SIZE="1">
Amber</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
STR</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
2625</FONT></TD>
<TD BGCOLOR=#C0C0C0 ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
 +2</FONT></TD>
<TD BGCOLOR=#FFCC00 ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
 +1</FONT></TD>
<TD BGCOLOR=#FFCC00 ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
 +3</FONT></TD>
<TD BGCOLOR=#C0C0C0 ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
 +4</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD BGCOLOR=#FFFFCC ALIGN="left"><FONT FACE="Verdana" SIZE="1">
Jade</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
Mana / HP / AC</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
3675</FONT></TD>
<TD BGCOLOR=#C0C0C0 ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
 +5/ +5/ +1</FONT></TD>
<TD BGCOLOR=#33CCCC ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
+10/ +10/ +2</FONT></TD>
<TD BGCOLOR=#33CCCC ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
+15/ +15/ +2</FONT></TD>
<TD BGCOLOR=#C0C0C0 ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
+20/ +20/ +4</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD BGCOLOR=#FFFFCC ALIGN="left"><FONT FACE="Verdana" SIZE="1">
Pearl</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
Vs Pois / AC</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
4725</FONT></TD>
<TD BGCOLOR=#C0C0C0 ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
+4/ +2</FONT></TD>
<TD BGCOLOR=#00FF00 ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
+6/ +3</FONT></TD>
<TD BGCOLOR=#00FF00 ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
+9/ +5</FONT></TD>
<TD BGCOLOR=#C0C0C0 ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
+10/ +4</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD BGCOLOR=#FFFFCC ALIGN="left"><FONT FACE="Verdana" SIZE="1">
Topaz</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
Vs   Dis / AC</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
5250</FONT></TD>
<TD BGCOLOR=#00FF00 ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
+5/ +3</FONT></TD>
<TD BGCOLOR=#FFCC00 ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
 +5/ +2</FONT></TD>
<TD BGCOLOR=#FFCC00 ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
 +8/ +3</FONT></TD>
<TD BGCOLOR=#00FF00 ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
 +13/ +5</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD BGCOLOR=#FFFFCC ALIGN="left"><FONT FACE="Verdana" SIZE="1">
Peridot</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
Vs Cold / AC</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
10500</FONT></TD>
<TD BGCOLOR=#C0C0C0 ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
 +5/ +2</FONT></TD>
<TD BGCOLOR=#33CCCC ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
 +4/ +3</FONT></TD>
<TD BGCOLOR=#33CCCC ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
 +6/ +3</FONT></TD>
<TD BGCOLOR=#C0C0C0 ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
 +10/ +4</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD BGCOLOR=#FFFFCC ALIGN="left"><FONT FACE="Verdana" SIZE="1">
Emerald</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
Vs   Fire / AC</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
13650</FONT></TD>
<TD BGCOLOR=#C0C0C0 ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
 +5/ +2</FONT></TD>
<TD BGCOLOR=#33CCCC ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
 +4/ +3</FONT></TD>
<TD BGCOLOR=#33CCCC ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
 +6/ +3</FONT></TD>
<TD BGCOLOR=#C0C0C0 ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
 +10/ +4</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD BGCOLOR=#FF9900 ALIGN="left"><FONT FACE="Verdana" SIZE="1">
Jacinth</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
Vs Magic / AC</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
13655</FONT></TD>
<TD BGCOLOR=#808080 ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
?</FONT></TD>
<TD BGCOLOR=#C0C0C0 ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
?</FONT></TD>
<TD BGCOLOR=#C0C0C0 ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
 +3/ +7</FONT></TD>
<TD BGCOLOR=#C0C0C0 ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
 +13/ +0</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD BGCOLOR=#FFFFCC ALIGN="left"><FONT FACE="Verdana" SIZE="1">
Opal</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
Sta / Agi</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
17850</FONT></TD>
<TD BGCOLOR=#C0C0C0 ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
 +3/ +2</FONT></TD>
<TD BGCOLOR=#00FF00 ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
 +4/ +3</FONT></TD>
<TD BGCOLOR=#00FF00 ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
 +9/ +6</FONT></TD>
<TD BGCOLOR=#C0C0C0 ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
 +7/ +5</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD BGCOLOR=#FF9900 ALIGN="left"><FONT FACE="Verdana" SIZE="1">
Black Pearl</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
Dex / Agi</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
21000</FONT></TD>
<TD BGCOLOR=#C0C0C0 ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
 +3/ +3</FONT></TD>
<TD BGCOLOR=#00FF00 ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
 +4/ +4</FONT></TD>
<TD BGCOLOR=#00FF00 ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
 +7/ +7</FONT></TD>
<TD BGCOLOR=#C0C0C0 ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
 +6/ +6</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD BGCOLOR=#FF9900 ALIGN="left"><FONT FACE="Verdana" SIZE="1">
Fire Opal</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
HP/ AC</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
52500</FONT></TD>
<TD BGCOLOR=#C0C0C0 ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
 +30/ +2</FONT></TD>
<TD BGCOLOR=#C0C0C0 ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
 +35/ +3</FONT></TD>
<TD BGCOLOR=#C0C0C0 ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
 +45/ +4</FONT></TD>
<TD BGCOLOR=#C0C0C0 ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
 +55/ +5</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD BGCOLOR=#FFFFCC ALIGN="left"><FONT FACE="Verdana" SIZE="1">
Star Ruby</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
Dex / Chr</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
68250</FONT></TD>
<TD BGCOLOR=#FF00FF ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
 +5/ +5</FONT></TD>
<TD BGCOLOR=#C0C0C0 ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
 +5/ +7</FONT></TD>
<TD BGCOLOR=#C0C0C0 ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
 +7/ +5</FONT></TD>
<TD BGCOLOR=#FF00FF ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
 +9/ +9</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD BGCOLOR=#FFFFCC ALIGN="left"><FONT FACE="Verdana" SIZE="1">
Fire Emerald</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
Str / Dex</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
89250</FONT></TD>
<TD BGCOLOR=#C0C0C0 ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
 +3/ +3</FONT></TD>
<TD BGCOLOR=#33CCCC ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
 +3/ +5</FONT></TD>
<TD BGCOLOR=#33CCCC ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
 +5/ +3</FONT></TD>
<TD BGCOLOR=#C0C0C0 ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1">
 +5/ +5</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD BGCOLOR=#FFFFCC ALIGN="left"><FONT FACE="Verdana" SIZE="1">
Sapphire</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
Str / Int</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
105000</FONT></TD>
<TD BGCOLOR=#00FF00 ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
 +4/ +4</FONT></TD>
<TD BGCOLOR=#FFCC00 ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
 +4/ +2</FONT></TD>
<TD BGCOLOR=#FFCC00 ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
 +2/ +4</FONT></TD>
<TD BGCOLOR=#00FF00 ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
 +7/ +7</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD BGCOLOR=#FFFFCC ALIGN="left"><FONT FACE="Verdana" SIZE="1">
Ruby</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
Str / Wis</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
131000</FONT></TD>
<TD BGCOLOR=#FF00FF ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
 +4/ +4</FONT></TD>
<TD BGCOLOR=#C0C0C0 ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
 +4/ +2</FONT></TD>
<TD BGCOLOR=#C0C0C0 ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
 +2/ +4</FONT></TD>
<TD BGCOLOR=#FF00FF ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
 +7/ +7</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD BGCOLOR=#FF9900 ALIGN="left"><FONT FACE="Verdana" SIZE="1">
Black Sapphire</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
HP / Mana</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
250000</FONT></TD>
<TD BGCOLOR=#00FF00 ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
?</FONT></TD>
<TD BGCOLOR=#FFCC00 ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
 +35/ +25</FONT></TD>
<TD BGCOLOR=#FFCC00 ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
 +25/ +35</FONT></TD>
<TD BGCOLOR=#00FF00 ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
 +55/ +55</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD BGCOLOR=#FF9900 ALIGN="left"><FONT FACE="Verdana" SIZE="1">
Diamond</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
Vs Fire / Dis / Cold / Poi / Mag</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
250000</FONT></TD>
<TD BGCOLOR=#C0C0C0 ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
 +3/ +3/ +3/ +3/ +3</FONT></TD>
<TD BGCOLOR=#FF00FF ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
?</FONT></TD>
<TD BGCOLOR=#FF00FF ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
 +10/ +5/ +10/ +5/ +3</FONT></TD>
<TD BGCOLOR=#C0C0C0 ALIGN="justify" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
 +7/ +7/ +7/ +7/ +7</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="right"><FONT FACE="Verdana" SIZE="1">
&nbsp;</FONT></TD>
<TD ALIGN="right"><FONT FACE="Verdana" SIZE="1">
&nbsp;</FONT></TD>
<TD ALIGN="right"><FONT FACE="Verdana" SIZE="1">
&nbsp;</FONT></TD>
<TD ALIGN="right"><FONT FACE="Verdana" SIZE="1">
&nbsp;</FONT></TD>
<TD ALIGN="right"><FONT FACE="Verdana" SIZE="1">
&nbsp;</FONT></TD>
<TD ALIGN="right"><FONT FACE="Verdana" SIZE="1">
&nbsp;</FONT></TD>
<TD ALIGN="right"><FONT FACE="Verdana" SIZE="1">
&nbsp;</FONT></TD>
</TR>
<TR ALIGN="center" VALIGN="bottom">
<TD COLSPAN=4><FONT FACE="Verdana" SIZE="1">
Note: Prices on Monster Loot Gems are only estimates</FONT></TD>
<TD COLSPAN=3><FONT FACE="Verdana" SIZE="1">
Information from Casters Realm</FONT></TD>
</TR>
<TR ALIGN="center" VALIGN="bottom">
<TD COLSPAN=4><FONT FACE="Verdana" SIZE="1">
with the exception of fire opal.</FONT></TD>
<TD COLSPAN=3><FONT FACE="Verdana" SIZE="1">
http://eq.castersrealm.com</FONT></TD>
</TR>
</Table>
<!-- ------------------------- -->
<!-- END OF CURRENT JEWELRY -->
<!-- ------------------------- -->


<BR><BR><DIV ALIGN="center"><A HREF="new_jewelry_guide.phtml" TARGET="_self"><IMG SRC="back_button.jpg" WIDTH=200 HEIGHT=50 BORDER=0 ALIGN="MIDDLE" ALT="Back to the Guide"></A></DIV><BR><BR>



</TR>
</TABLE>
	<TD width="64"></TD>
<TR>
	<TD><IMG SRC = "http://www.loreseekers.com/graphics/botc000.jpg" WIDTH = 63 HEIGHT = 87></TD>
	<TD><IMG SRC = "http://www.loreseekers.com/graphics/botc001.jpg" WIDTH = 473 HEIGHT = 87></TD>
	<TD><IMG SRC = "http://www.loreseekers.com/graphics/botc002.jpg" WIDTH = 64 HEIGHT = 87></TD>
</TR>
</TABLE>
<BR>
<IMG SRC="http://service.bfast.com/bfast/serve?bfmid=1375281&siteid=40292692&bfpage=pc" BORDER="0" WIDTH="1" HEIGHT="1" NOSAVE ><A HREF="http://service.bfast.com/bfast/click?bfmid=1375281&siteid=40292692&bfpage=pc" TARGET="_new"><IMG SRC="http://affiliate.gamestop.com/affIMG/pc_120x60.gif" BORDER="0" WIDTH="120" HEIGHT="60" ALT="PC Games at GameStop.com"></A>
<BR>
<BR>
</DIV>
</BODY>
</HTML>


