<!--
                 This page has been created by Renaissance IT
   Renaissance Internet Technologies Copyright (c) 1999 All Rights Reserved.
             for more info on our products, please visit :
                        http://www.renaissance.nl/

	This script has been written by Roy Boverhof <rboverhof@renaissance.nl>

        Pagename                : links.html
        Last Updated    		: 10-24-2000

-->


<HTML>
<HEAD>
	<TITLE>the Seekers of Lore : Suggested Links</TITLE>
</HEAD>

<BODY BGCOLOR="#000000" TEXT="#000000" LINK="#000000" VLINK="#000000" ALINK="#000000">
<DIV ALIGN="CENTER">
<BR>
<!-- FGB Banner Code -->
<SCRIPT LANGUAGE="JavaScript">
<!-- Hide from old browsers
now = new Date();
random = now.getTime();

// Modify to reflect site specifics
site = "http://ds.cybereps.com";
target = "/SITE=FGN/AREA=EQLORE/AAMSZ=BANNER";

document.write('<IFRAME SRC="' + site + '/hserver/acc_random=' + random + target + '"');
document.write(' NORESIZE SCROLLING=NO HSPACE=0 VSPACE=0 FRAMEBORDER=0 MARGINHEIGHT=0 MARGINWIDTH=0 WIDTH=468 HEIGHT=60>');

document.write('<SCR');
document.write('IPT SRC="' + site + '/jnserver/acc_random=' + random + target + '">');
document.write('</SCR');
document.write('IPT>');

document.write('</IFRAME>');
// End Hide -->
</SCRIPT>

<NOSCRIPT><A HREF="http://ds.cybereps.com/accipiter/adclick/SITE=FGN/AREA=EQLORE/AAMSZ=BANNER"><IMG SRC="http://ds.cybereps.com/accipiter/nserver/SITE=FGN/AREA=EQLORE/AAMSZ=BANNER" border="0"></A></NOSCRIPT>
<!-- END FGB Banner Code --><BR>
<TABLE CELLSPACING = 0 CELLPADDING = 0 BORDER = 0>
<TR>
	<TD width="63"><IMG SRC = "graphics/topc000.jpg" WIDTH = 63 HEIGHT = 87></TD>
	<TD width="473"><IMG SRC = "graphics/topc001.jpg" WIDTH = 473 HEIGHT = 87></TD>
	<TD width="64"><IMG SRC = "graphics/topc002.jpg" WIDTH = 64 HEIGHT = 87></TD>
</TR>
<TR>
	<TD width="63"></TD>
	<TD BGCOLOR="#BEA279" width="460">
	<DIV ALIGN="CENTER">
	<IMG SRC="graphics/linkheader.jpg" WIDTH ="200" HEIGHT ="75">
	<TABLE WIDTH="460">
	<TR>
		<TD>
		<TABLE BGCOLOR="#BEA279" width="420" CELLPADDING="5" CELLSPACING="5">
		<TR>
		<TD BGCOLOR="#BEA279" width="20"></TD>
		<TD GCOLOR="#BEA279" width="380">
		<HR>
		<FONT FACE="Verdana" SIZE="-1"><B>1. <A HREF="links1.phtml">General</A></B></FONT><BR>&nbsp;&nbsp;&nbsp; - <FONT SIZE="-1">General information sites</FONT><BR><BR>
		<FONT FACE="Verdana" SIZE="-1"><B>2. <A HREF="links4.phtml">Specialized</A></FONT></B><BR>&nbsp;&nbsp;&nbsp; - <FONT SIZE="-1">Sites with specific information</FONT><BR><BR>
		<FONT FACE="Verdana" SIZE="-1"><B>3. <A HREF="links2.phtml">Class Specific</A><FONT COLOR="#FF0000"> - Updated!</FONT></B></FONT><BR>&nbsp;&nbsp;&nbsp; - <FONT SIZE="-1">Sites focusing on a certain class</FONT><BR><BR>
		<FONT FACE="Verdana" SIZE="-1"><B>4. <A HREF="links3.phtml">Forums</A><FONT COLOR="#FF0000"> - Updated!</FONT></B></FONT><BR>&nbsp;&nbsp;&nbsp; - Various discussion forums</FONT><BR>
		</FONT>
		<HR>
		</TD>
		<TD BGCOLOR="#BEA279" width="20"></TD>
		</TR>
		</TABLE>

		<CENTER>
			<P>
			<BR>
			<BR>
			<B><FONT SIZE="+1">I</FONT>f you have a nice EQ site, feel free to link us.</B><BR><BR>
			<A HREF="http://www.loreseekers.com"><IMG SRC="http://www.loreseekers.com/graphics/seekers_link.jpg" WIDTH=220 HEIGHT=75 ALT="the Seekers of Lore" BORDER="0"><BR></A>
			<BR>
			<B><FONT SIZE="+1">T</FONT>his is the HTML Code (ready for copying / pasting) :</B><BR>
			<FORM><TEXTAREA wrap=physical rows="5" cols="50">
			<A HREF="http://www.loreseekers.com"><IMG SRC="http://www.loreseekers.com/graphics/seekers_link.jpg" WIDTH=220 HEIGHT=75 ALT="the Seekers of Lore" BORDER="0"><BR></A>
			</TEXTAREA></FORM>
			<BR>
			<CENTER>
			<FONT SIZE="2">Buy EverQuest now!</FONT><BR>
			<A HREF="http://www.dragon.ca/cgi-bin/affiliate.cgi?affid=LoreSeekersRB&id=EVERRUI" TARGET="_new"><IMG SRC="graphics/orderfrom.gif" ALIGN="Center" WIDTH ="120" HEIGHT ="26" ALT="Buy EverQuest Now!" BORDER="0"></A>
			</CENTER>
			</CENTER>
			</P>
		</TD>
	</TR>
	</TABLE>

	<TD width="64"></TD>
<TR>
	<TD><IMG SRC = "graphics/botc000.jpg" WIDTH = 63 HEIGHT = 87></TD>
	<TD><IMG SRC = "graphics/botc001.jpg" WIDTH = 473 HEIGHT = 87></TD>
	<TD><IMG SRC = "graphics/botc002.jpg" WIDTH = 64 HEIGHT = 87></TD>
</TR>
</TABLE>

<BR>
<SCRIPT LANGUAGE="JavaScript">
<!-- Hide from old browsers
now = new Date();
random = now.getTime();

// Modify to reflect site specifics
site = "http://ds.cybereps.com";
target = "/SITE=FGN/AREA=EQLORE/AAMSZ=BUTTON1";

document.write('<IFRAME SRC="' + site + '/hserver/acc_random=' + random + target + '"');
document.write(' NORESIZE SCROLLING=NO HSPACE=0 VSPACE=0 FRAMEBORDER=0 MARGINHEIGHT=0 MARGINWIDTH=0 WIDTH=120 HEIGHT=90>');

document.write('<SCR');
document.write('IPT SRC="' + site + '/jnserver/acc_random=' + random + target + '">');
document.write('</SCR');
document.write('IPT>');

document.write('</IFRAME>');
// End Hide -->
</SCRIPT>
<NOSCRIPT> <A HREF="http://ds.cybereps.com/accipiter/adclick/SITE=FGN/AREA=EQLORE/AAMSZ=BUTTON1">
<IMG SRC="http://ds.cybereps.com/accipiter/nserver/SITE=FGN/AREA=EQLORE/AAMSZ=BUTTON1" border="0"></A>
</NOSCRIPT>
<BR>
<BR>
</DIV>
</BODY>
</HTML>
