<!--
                 This page has been created by Renaissance IT
   Renaissance Internet Technologies Copyright (c) 1999 All Rights Reserved.

             for more info on our products, please visit :
                        http://www.renaissance.nl/

	This script has been written by Roy Boverhof <rboverhof@renaissance.nl>
	
        Pagename                : xegony_shots.html
        Last Updated    		: 05-15-2000
-->

<HTML>
<HEAD>
	<TITLE>the Seekers of Lore : Xegony Server Screenshots</TITLE>
</HEAD>

<BODY BGCOLOR="#000000" TEXT="#000000" LINK="#000000" VLINK="#000000" ALINK="#000000">
<DIV ALIGN="CENTER">
<BR>
<script type="text/javascript"><!--
google_ad_client = "pub-0988179937943699";
google_ad_width = 468;
google_ad_height = 60;
google_ad_format = "468x60_as";
google_ad_channel ="7352298734";
google_page_url = document.location;
google_color_border = "FFFFFF";
google_color_bg = "00001F";
google_color_link = "FFFFFF";
google_color_url = "FFF000";
google_color_text = "0000FF";
//--></script>
<script type="text/javascript"
  src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
</script><BR>	
<TABLE CELLSPACING = 0 CELLPADDING = 0 BORDER = 0>
<TR>
	<TD width="63"><IMG SRC = "graphics/topc000.jpg" WIDTH = 63 HEIGHT = 87></TD>
	<TD width="473"><IMG SRC = "graphics/topc001.jpg" WIDTH = 473 HEIGHT = 87></TD>
	<TD width="64"><IMG SRC = "graphics/topc002.jpg" WIDTH = 64 HEIGHT = 87></TD>
</TR>
	<TD width="63"></TD>
	<TD BGCOLOR="#BEA279" width="460">
	<DIV ALIGN="CENTER">
	<A HREF="http://www.loreseekers.com/screenshots.phtml"><IMG SRC="graphics/screencap_header.gif" WIDTH ="200" HEIGHT ="75" BORDER="0"></A>
	<TABLE WIDTH="460">
	<TR><TD>
	<CENTER>
<TABLE BORDER="0">
<TR>
<TD><BR><FONT SIZE="4" FACE="Ariel"><CENTER>Screenshots from our Xegony members</CENTER></FONT><BR></TD>
</TR>
</TABLE>

<TABLE BORDER="0" WIDTH="440">
<TR> 
	<TD><A HREF="screenshots/05052000_xegony.jpg" TARGET="_new"><IMG SRC="screenshots/tn_05052000_xegony.jpg" WIDTH ="200" HEIGHT ="150" BORDER=0 ALT="Click to view image full size"></A></TD>
	<TD><A HREF="screenshots/05052000_xegony2.jpg" TARGET="_new"><IMG SRC="screenshots/tn_05052000_xegony2.jpg" WIDTH ="200" HEIGHT ="150" BORDER=0 ALT="Click to view image full size"></A></TD>
</TR>
<TR>
<TD><FONT SIZE="2" FACE="ariel"><DIV ALIGN="center">800 x 600<BR>Participants in the Newbie race from Freeport to Befallen. Submitted by Clalron.</DIV></FONT></TD>
<TD><FONT SIZE="2" FACE="ariel"><DIV ALIGN="center">800 x 600<BR>Seekers of Lore raid on Befallen.</DIV></FONT></TD>
</TR>
</TABLE>

	</CENTER>
	<P>
	<BR>
	<BR>
	</P>
	</TD></TR>
	</TABLE>
	<TD width="64"></TD>
<TR>
	<TD><IMG SRC = "graphics/botc000.jpg" WIDTH = 63 HEIGHT = 87></TD>
	<TD><IMG SRC = "graphics/botc001.jpg" WIDTH = 473 HEIGHT = 87></TD>
	<TD><IMG SRC = "graphics/botc002.jpg" WIDTH = 64 HEIGHT = 87></TD>
</TR>
</TABLE>
<BR>
<a href="http://wetrack.it/guidefox/a/16/b/20/e/2" TARGET="_new"><img src="http://guidefox.com/resources/atn/135x48_ani_eq2_1.gif" border="0"></a><BR>
<BR>
</DIV>
</BODY>
</HTML>