<!--
                 This page has been created by Renaissance IT
   Renaissance Internet Technologies Copyright (c) 1999 All Rights Reserved.

             for more info on our products, please visit :
                        http://www.renaissance.nl/

	This page has been made by Roy Boverhof <rboverhof@renaissance.nl>
	
        Pagename                : faq.html
        Last Updated    		: 11-7-1999
-->
<HTML>
<HEAD>
	<TITLE>Seekers of Lore F.A.Q.</TITLE>
</HEAD>
<BODY bgcolor="#000000" TEXT="#000000">
<DIV ALIGN="CENTER">
<BR>
<script type="text/javascript"><!--
google_ad_client = "pub-0988179937943699";
google_ad_width = 468;
google_ad_height = 60;
google_ad_format = "468x60_as";
google_ad_channel ="7352298734";
google_page_url = document.location;
google_color_border = "FFFFFF";
google_color_bg = "00001F";
google_color_link = "FFFFFF";
google_color_url = "FFF000";
google_color_text = "0000FF";
//--></script>
<script type="text/javascript"
  src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
</script><BR>
<TABLE CELLSPACING = 0 CELLPADDING = 0 BORDER = 0>
<TR>
	<TD width="63"><IMG SRC = "graphics/topc000.jpg" WIDTH = 63 HEIGHT = 87></TD>
	<TD width="473"><IMG SRC = "graphics/topc001.jpg" WIDTH = 473 HEIGHT = 87></TD>
	<TD width="64"><IMG SRC = "graphics/topc002.jpg" WIDTH = 64 HEIGHT = 87></TD>
</TR>
	<TD width="63"></TD>
	<TD BGCOLOR="#BEA279" width="460">
	<DIV ALIGN="CENTER">
	<IMG SRC="graphics/faq.jpg">
	<TABLE WIDTH="460">
	<TR>
		<TD>
		<table  width="98%" cellpadding="0" cellspacing="0">
		<TR>
		<TD>
		<br>
		    <p align="left">
			<font size="5" face="helvetica"><strong>Table of contents: </strong></font></p>
		    <p align="left">
			<a href="#1.0 General questions."><font size="2" face="helvetica">1.0 General questions.</font></a><BR>
			<a href="#2.0 Guild questions."><font size="2" face="helvetica">2.0 Guild questions.</font></a><BR>
			
			<p align="left"><a name="1"><font size="5" face="helvetica"><strong>1.0 General questions.</strong></font></a></p>
	        <p align="left"><font size="2" face="helvetica"><b>1.1 What is a FAQ?</b></font></p>
	        <p align="left"><font size="2" face="helvetica">
			FAQ stands for Frequently Asked
	        Questions. FAQs are designed to cover the most common
	        questions and answers regarding a product.
			</font></p>
	        <p align="left"><font size="2" face="helvetica"><b>1.2 What is EverQuest?</b></font></p>
	        <p align="left"><font size="2" face="helvetica">
			EverQuest is a real 3D massively
	        multiplayer online RPG. Another equally accurate way of
	        describing EverQuest is to call it a graphical MUD.
			</font></p>
	        
			<p align="left"><a name="2"><font size="5" face="helvetica"><strong>2.0 Guild questions.</strong></font></a></p>
	        <p align="left"><font size="2" face="helvetica"><b>2.1 What is a Guild?</b></font></p>
	        <p align="left"><font size="2" face="helvetica">
			Guild stand for a group of players who are "Bound" together with a purpose, this is usually a group of friends who enjoy playing together, or people who have a common goal
			</font></p>
	        <p align="left"><font size="2" face="helvetica"><b>2.2 How can I join ?</b></font></p>
	        <p align="left"><font size="2" face="helvetica">
			This used to be very easy, but because of some bad experiences with members misbehaving, we have raised the standards !<BR>
			When you are serious about becoming a member, make sure you have do the following things :<BR>
			<OL>
			<LI>Read our <A HREF="charter.phtml">Charter</A> and make sure you fully agree with it.
			<LI>Find one (or more) of our members and group with them.
			<LI>If you enjoy yourself, and our member thinks you will make a nice addition to our guild ask if you can be recommended.
			<LI>If that member allows you to be recommended by him / her go to our <A HREF="apply.phtml">application page</A> and fill out the form.
			<LI>You will be contacted by one of our officers or the leader of that branch.
			<LI>Once you are inducted, you are a probationary member.
			<LI>When you have spent enough time online, and we feel you really fit in our guild you will become a full member. (time varies on each branch)<BR>
			You will be inaugurated by an Officer or the leader.
			</OL>
			<SUP>*</SUP>Some of our branches have special guild quests, to become a member you will be appointed a quest that suits your level by the local "quest officer".
			This quest has to be completed to prove yourself worthy of bearing our name.
			</font></p>		
			<p align="left"><font size="2" face="helvetica"><b>2.3 What's inside the "members only" area ?</b></font></p>
	        <p align="left"><font size="2" face="helvetica">
			All members have access to this restricted area, here we have a discussion board where our members can talk about various topics.
			We also have a mailing list where members can subscribe to.
			</font></p>
			<p align="left"><font size="2" face="helvetica"><b>2.4 what are chapters ?</b></font></p>
	        <p align="left"><font size="2" face="helvetica">
			Every server has its own leader, this leader is fully responsable for the members on that server.<BR>
			A leader may create new rules for the server he administers, but the the basic rules as listed in rules / charter allways apply !<BR>
			</font></p>	
			<p align="left"><font size="2" face="helvetica"><b>2.5 I have lost my password !</b></font></p>
	        <p align="left"><font size="2" face="helvetica">
			If you have lost your password / username, simply go to <A HREF="http://www.loreseekers.com/lostpasswd.php3">this</A> page to get it sent to you.<BR>
			</font></p>
		</TD>
		</TR>
		</TABLE>
	</div>
	</TD>
	</TR>
	</TABLE>
	<TD width="64"></TD>
<TR>
	<TD><IMG SRC = "graphics/botc000.jpg" WIDTH = 63 HEIGHT = 87></TD>
	<TD><IMG SRC = "graphics/botc001.jpg" WIDTH = 473 HEIGHT = 87></TD>
	<TD><IMG SRC = "graphics/botc002.jpg" WIDTH = 64 HEIGHT = 87></TD>
</TR>
</TABLE>
<script type="text/javascript"><!--
google_ad_client = "pub-0988179937943699";
google_ad_width = 180;
google_ad_height = 60;
google_ad_format = "180x60_as_rimg";
google_cpa_choice = "CAAQ56j8zwEaCHvU9tBAqJJaKMu293M";
//--></script>
<script type="text/javascript" src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
</script>
<BR>
<BR>
<BR>
</DIV>
</BODY>
</HTML>

