<HTML>
<HEAD>
<TITLE>Welcome to Media and Games Online Network - MGON</TITLE>
<META name="description" content="MGON - The Gamer's Choice for gaming news. Get the hottest info from the gaming industry.
.">
<META name="keywords" content="MGON, MGO, Interviews, Game previews, Game downloads, Gaming Network, Articles, Gaming News, News, Multiplayer, Games, PC Games, Console Games, Reviews, Forum, MGON International AB, Action, Strategy, Simulation, Roleplay, Racing">
<META name="robots" content="index,follow">
<LINK rel="stylesheet" href="/pagestyle2.css">
<STYLE type="text/css">
<!--
-->
</STYLE>
<script language="JavaScript" type="text/javascript">
<!--
function go(where) {
  if(where != "void" && where!="") location.href = where;
}

function reply(tid,pid,cid,lang) {

  url = "/reply.phtml?tid=" + tid + "&pid=" + pid + "&id=" + cid + "&language=" + lang + '&ref=%2Fnews.phtml';
  ipwindow = open("","prewindow","scrollbars=yes,toolbar=no,height=400,width=400");
  ipwindow.location.href = url;
        
}

function rateit(id,vote) {
    if(vote != "") {
		document.rate.content_id.value = id;
		document.rate.vote.value = vote;
		document.rate.submit();
	}
}

function screenshot(cid,pid) {

  url = "/screenshot.phtml?cid=" + cid + "&pid=" + pid;
  ipwindow = open("","prewindow","scrollbars=yes,toolbar=no,height=630,width=710");
  ipwindow.location.href = url;
        
}

function relatedmedia(url) {

  ipwindow = open("","prewindow","scrollbars=yes,toolbar=no,height=300,width=300");
  ipwindow.location.href = url;
        
}
//-->
</script> 
</HEAD>

<BODY bgcolor="#FFFFFF" text="#000000" link="#000000" vlink="#000000" alink="#000000" leftmargin="0" topmargin="0" marginwidth="0" marginheight="0" background="/images2/backgrounds/resize.gif">
<TABLE width="750" border="0" cellspacing="0" cellpadding="0">
  <TR> 
    <TD><!-- Webserver: w14 --><script language="JavaScript">
<!--
function MM_openBrWindow(theURL,winName,features) { //v2.0
  window.open(theURL,winName,features);  
}
function login() {
  window.open('/common/loginNew.phtml', 'Login', 'width=250,height=250,scrollbars=yes'); 
}
function member() {
  window.open('/common/members.phtml', 'Member', 'width=500,height=600,scrollbars=yes'); 
}
//-->
</script>
<table width="100%" border="0" cellspacing="0" cellpadding="0" background="/common/images/topplate/resize.gif">
  <tr> 
    <td> 
      <table width="488" border="0" cellspacing="0" cellpadding="0" background="/common/images/topplate/resize.gif">
        <tr> 
          <td><img src="/common/images/topplate/metalcorner.gif" width="5" height="20"></td>
          <td><a href="javascript:login();"><img src="/common/images/topplate/memberlogin.gif" width="80" height="20" border="0"></a></td>
          <td><img src="/common/images/topplate/arrow.gif" width="10" height="20"></td>
          <td><img src="/common/images/topplate/metalcolumn.gif" width="3" height="20"></td>
          <td><a href="javascript:;" onClick="MM_openBrWindow('/common/sitemap.html','navigation','width=540,height=420')"><img src="/common/images/topplate/pc.gif" width="23" height="20" border="0"></a></td>
          <td><img src="/common/images/topplate/metalcolumn.gif" width="3" height="20"></td>
          <td><a href="javascript:;" onClick="MM_openBrWindow('/common/sitemap.html','navigation','width=540,height=420')"><img src="/common/images/topplate/action.gif" width="47" height="20" border="0"></a></td>
          <td><img src="/common/images/topplate/metalcolumn.gif" width="3" height="20"></td>
          <td><a href="javascript:;" onClick="MM_openBrWindow('/common/sitemap.html','navigation','width=540,height=420')"><img src="/common/images/topplate/roleplay.gif" width="62" height="20" border="0"></a></td>
          <td><img src="/common/images/topplate/metalcolumn.gif" width="3" height="20"></td>
          <td><a href="javascript:;" onClick="MM_openBrWindow('/common/sitemap.html','navigation','width=540,height=420')"><img src="/common/images/topplate/simulation.gif" width="70" height="20" border="0"></a></td>
          <td><img src="/common/images/topplate/metalcolumn.gif" width="3" height="20"></td>
          <td><a href="javascript:;" onClick="MM_openBrWindow('/common/sitemap.html','navigation','width=540,height=420')"><img src="/common/images/topplate/console.gif" width="56" height="20" border="0"></a></td>
          <td><img src="/common/images/topplate/metalcolumn.gif" width="3" height="20"></td>
          <td><a href="javascript:;" onClick="MM_openBrWindow('/common/sitemap.html','navigation','width=540,height=420')"><img src="/common/images/topplate/strategy.gif" width="64" height="20" border="0"></a></td>
          <td><img src="/common/images/topplate/metalcolumn.gif" width="3" height="20"></td>
          <td><a href="javascript:;" onClick="MM_openBrWindow('/common/sitemap.html','navigation','width=540,height=420')"><img src="/common/images/topplate/racing.gif" width="47" height="20" border="0"></a></td>
          <td><img src="/common/images/topplate/metalcolumn.gif" width="3" height="20"></td>
        </tr>
      </table>
    </td>
    <td background="/common/images/topplate/resize.gif" width="100%"><img src="/common/images/topplate/resize.gif" width="100%" height="20"></td>
    <td>
      <table width="88" border="0" cellspacing="0" cellpadding="0" background="/common/images/topplate/resize.gif">
        <tr>
          <td><img src="/common/images/topplate/metalcolumn.gif" width="3" height="20"></td>
          <td><a href="javascript:;" onClick="MM_openBrWindow('/common/sitemap.html','navigation','width=540,height=420')"><img src="/common/images/topplate/mgonetwork.gif" width="82" height="20" border="0"></a></td>
          <td><img src="/common/images/topplate/metalcorner.gif" width="5" height="20"></td>
        </tr>
      </table>
    </td>
  </tr>
</table>
<table width="100%" border="0" cellspacing="0" cellpadding="0" bgcolor="#000000">
  <tr> 
    <td><img src="/images/misc/1pix.gif" width="1" height="1"></td>
  </tr>
</table><script language="javascript">
var compname='Ad/mgon';
</script>
<script language="javascript" src="http://www.rankyou.com/cpt_transfers/single_month_enter.js">
</script></TD>
  </TR>
</TABLE>


<TABLE width="750" border="0" cellspacing="0" cellpadding="0">

  <TR> 

    <TD><IMG src="/images2/top/topleft.gif" width="592" height="81" border="0" usemap="#Map"><MAP name="Map"><AREA shape="rect" coords="13,36,138,76" href="http://www.mgon.com" alt="MGON Home" title="MGON Home"></MAP></TD>

    <TD width="100%" background="/images2/top/resize.gif"><IMG src="/images2/top/resize.gif" width="1" height="81"></TD>

    <TD><IMG src="/images2/top/emgeo.gif" width="157" height="81"></TD>

  </TR>

</TABLE>


<TABLE width="750" border="0" cellspacing="0" cellpadding="0" bgcolor="#000000">
	<TR> 
		<TD align="center" width="130"> 
			<TABLE width="100%" border="0" cellspacing="0" cellpadding="0">
				<TR> 
					<TD align="center" background="/images2/top/channelresize.gif"><OBJECT classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=4,0,2,0" width="120" height="60">
							<PARAM name=movie value="http://www.mgon.com/flashmovies/mgochannel2.swf">
							<PARAM name=quality value=high>
							<PARAM name="menu" value="false">
							<EMBED src="http://www.mgon.com/flashmovies/mgochannel2.swf" quality=high pluginspage="http://www.macromedia.com/shockwave/download/index.cgi?P1_Prod_Version=ShockwaveFlash" 
type="application/x-shockwave-flash" menu="false" width="120" height="60">
							</EMBED> 
						</OBJECT></TD>
				</TR>
				<TR> 
					<TD><IMG src="/images/top/channelbottom.gif" width="130" height="13"></TD>
				</TR>
			</TABLE>
		</TD>
		
    <TD align="center" width="490" valign="top"> 
      <span class="smalltext"><NOLAYER><IFRAME SRC="http://ad.se.doubleclick.net/adi/mgon.com/;sz=468x60;ord=984099114?" bgcolor="#000000" width="468" height="60" frameborder="no" border="0" MARGINWIDTH="0" MARGINHEIGHT="0" SCROLLING="no"><A HREF="http://ad.se.doubleclick.net/jump/mgon.com/;abr=!ie;sz=468x60;ord=984099114?"><IMG SRC="http://ad.se.doubleclick.net/ad/mgon.com/;abr=!ie;sz=468x60;ord=984099114?" border="0" height="60" width="468"></A></IFRAME></NOLAYER><ILAYER id="layer1" visibility="hidden" width="468" height="60" align="center"></ILAYER></span>    </TD>
		
    <TD width="130" align="center" valign="top"><IMG
SRC="http://service.bfast.com/bfast/serve?bfmid=1375281&siteid=34593362&bfpa
ge=pc" BORDER="0" WIDTH="1" HEIGHT="1" NOSAVE > <A
HREF="http://service.bfast.com/bfast/click?bfmid=1375281&siteid=34593362&bfp
age=pc" TARGET="_top"><IMG
SRC="http://affiliate.gamestop.com/affimg/120_pc3_gs.gif" BORDER="0"
WIDTH="120" HEIGHT="60" ALT="PC titles from Gamestop.com"></A></TD>
	</TR>
</TABLE>
 
<TABLE width="750" border="0" cellspacing="0" cellpadding="0">
  <TR> 
    <TD valign="top" width="130" align="center"> 
       
<TABLE width="130" border="0" cellspacing="0" cellpadding="0">
  <TR> 
    <TD><IMG src="/images2/buttons/sitecontent.gif" width="130" height="25"></TD>
  </TR>
</TABLE>
<table width="124" border="0" cellspacing="0" cellpadding="0" bgcolor="#000000">
  <tr bgcolor="#000000"> 
    <td> 
      <table width="100%" border=0 cellpadding=0 cellspacing=1>
        <tr bgcolor="#10243F"> 
          <td style="border='1 #10243F'" onMouseOver="style.backgroundColor='#809ECB'; style.cursor='hand'; style.border='1 #10243F'" onMouseOut="style.backgroundColor='#10243F'; style.border='1 #10243F';" height="21"> 
            <table width="100%" border="0" cellspacing="0" cellpadding="2">
              <tr> 
                <td bgcolor="#10243F" height="21" width="100%"><a href="/" class="navlinks" style="margin:0;"> 
                  <div><img src="/images2/misc/1pix.gif" width="1" height="1" border="0">&nbsp;<span class="navlinks">Home</span></div>
                  </a></td>
                <td class="Bolded"><font size="2" face="Verdana, Arial, Helvetica, sans-serif" color="#10243F">&laquo;</font></td>
              </tr>
            </table>
          </td>
        </tr>
        <tr bgcolor="#10243F"> 
          <td style="border='1 #10243F'" onMouseOver="style.backgroundColor='#809ECB'; style.cursor='hand'; style.border='1 #10243F'" onMouseOut="style.backgroundColor='#10243F'; style.border='1 #10243F';" height="21"> 
            <table width="100%" border="0" cellspacing="0" cellpadding="2">
              <tr> 
                <td bgcolor="#10243F" height="21" width="100%"><a href="/news.phtml" class="navlinks" style="margin:0;"> 
                  <div><img src="/images2/misc/1pix.gif" width="1" height="1" border="0">&nbsp;<span class="navlinks">News</span></div>
                  </a></td>
                <td class="Bolded"><font size="2" face="Verdana, Arial, Helvetica, sans-serif" color="#10243F">&laquo;</font></td>
              </tr>
            </table>
          </td>
        </tr>
        <tr bgcolor="#10243F"> 
          <td style="border='1 #10243F'" onMouseOver="style.backgroundColor='#809ECB'; style.cursor='hand'; style.border='1 #10243F'" onMouseOut="style.backgroundColor='#10243F'; style.border='1 #10243F';" height="21"> 
            <table width="100%" border="0" cellspacing="0" cellpadding="2">
              <tr> 
                <td bgcolor="#10243F" height="21" width="100%"><a href="/reviewindex.phtml" class="navlinks" style="margin:0;"> 
                  <div><img src="/images2/misc/1pix.gif" width="1" height="1" border="0">&nbsp;<span class="navlinks">Reviews</span></div>
                  </a></td>
                <td class="Bolded"><font size="2" face="Verdana, Arial, Helvetica, sans-serif" color="#10243F">&laquo;</font></td>
              </tr>
            </table>
          </td>
        </tr>
        <tr bgcolor="#10243F"> 
          <td style="border='1 #10243F'" onMouseOver="style.backgroundColor='#809ECB'; style.cursor='hand'; style.border='1 #10243F'" onMouseOut="style.backgroundColor='#10243F'; style.border='1 #10243F';" height="21"> 
            <table width="100%" border="0" cellspacing="0" cellpadding="2">
              <tr> 
                <td bgcolor="#10243F" height="21" width="100%"><a href="/previewindex.phtml" class="navlinks" style="margin:0;"> 
                  <div><img src="/images2/misc/1pix.gif" width="1" height="1" border="0">&nbsp;<span class="navlinks">Previews</span></div>
                  </a></td>
                <td class="Bolded"><font size="2" face="Verdana, Arial, Helvetica, sans-serif" color="#10243F">&laquo;</font></td>
              </tr>
            </table>
          </td>
        </tr>
        <tr bgcolor="#10243F"> 
          <td style="border='1 #10243F'" onMouseOver="style.backgroundColor='#809ECB'; style.cursor='hand'; style.border='1 #10243F'" onMouseOut="style.backgroundColor='#10243F'; style.border='1 #10243F';" height="21"> 
            <table width="100%" border="0" cellspacing="0" cellpadding="2">
              <tr> 
                <td bgcolor="#10243F" height="21" width="100%"><a href="/interviewindex.phtml" class="navlinks" style="margin:0;"> 
                  <div><img src="/images2/misc/1pix.gif" width="1" height="1" border="0">&nbsp;<span class="navlinks">Interviews</span></div>
                  </a></td>
                <td class="Bolded"><font size="2" face="Verdana, Arial, Helvetica, sans-serif" color="#10243F">&laquo;</font></td>
              </tr>
            </table>
          </td>
        </tr>

        <tr bgcolor="#10243F"> 
          <td style="border='1 #10243F'" onMouseOver="style.backgroundColor='#809ECB'; style.cursor='hand'; style.border='1 #10243F'" onMouseOut="style.backgroundColor='#10243F'; style.border='1 #10243F';" height="21"> 
            <table width="100%" border="0" cellspacing="0" cellpadding="2">
              <tr> 
                <td bgcolor="#10243F" height="21" width="100%"><a href="/articleindex.phtml" class="navlinks" style="margin:0;"> 
                  <div><img src="/images2/misc/1pix.gif" width="1" height="1" border="0">&nbsp;<span class="navlinks">Articles</span></div>
                  </a></td>
                <td class="Bolded"><font size="2" face="Verdana, Arial, Helvetica, sans-serif" color="#10243F">&laquo;</font></td>
              </tr>
            </table>
          </td>
        </tr>
        <tr bgcolor="#10243F"> 
          <td style="border='1 #10243F'" onMouseOver="style.backgroundColor='#809ECB'; style.cursor='hand'; style.border='1 #10243F'" onMouseOut="style.backgroundColor='#10243F'; style.border='1 #10243F';" height="21"> 
            <table width="100%" border="0" cellspacing="0" cellpadding="2">
              <tr> 
                <td bgcolor="#10243F" height="21" width="100%"><a href="/fileindex.phtml" class="navlinks" style="margin:0;"> 
                  <div><img src="/images2/misc/1pix.gif" width="1" height="1" border="0">&nbsp;<span class="navlinks">Downloads</span></div>
                  </a></td>
                <td class="Bolded"><font size="2" face="Verdana, Arial, Helvetica, sans-serif" color="#10243F">&laquo;</font></td>
              </tr>
            </table>
          </td>
        </tr>
        <tr bgcolor="#10243F"> 
          <td style="border='1 #10243F'" onMouseOver="style.backgroundColor='#809ECB'; style.cursor='hand'; style.border='1 #10243F'" onMouseOut="style.backgroundColor='#10243F'; style.border='1 #10243F';" height="21"> 
            <table width="100%" border="0" cellspacing="0" cellpadding="2">
              <tr> 
                <td bgcolor="#10243F" height="21" width="100%"><a href="http://www.mgoforum.com/" class="navlinks" style="margin:0;"> 
                  <div><img src="/images2/misc/1pix.gif" width="1" height="1" border="0">&nbsp;<span class="navlinks">MGON 
                    Forum</span></div>
                  </a></td>
                <td class="Bolded"><font size="2" face="Verdana, Arial, Helvetica, sans-serif" color="#10243F">&laquo;</font></td>
              </tr>
            </table>
          </td>
        </tr>
      </table>
    </td>
  </tr>
</table>
<TABLE width="130" border="0" cellspacing="0" cellpadding="0">
  <TR> 
    <TD><IMG src="/images2/buttons/siteinfo.gif" width="130" height="25"></TD>
  </TR>
</TABLE>
<table width="124" border="0" cellspacing="0" cellpadding="0" bgcolor="#000000">
  <tr bgcolor="#000000"> 
    <td> 
      <table width="100%" border=0 cellpadding=0 cellspacing=1>
        <tr bgcolor="#10243F"> 
          <td style="border='1 #10243F'" onMouseOver="style.backgroundColor='#809ECB'; style.cursor='hand'; style.border='1 #10243F'" onMouseOut="style.backgroundColor='#10243F'; style.border='1 #10243F';" height="21"> 
            <table width="100%" border="0" cellspacing="0" cellpadding="2">
              <tr> 
                <td bgcolor="#10243F" height="21" width="100%"><a href="/company/" class="navlinks" style="margin:0;"> 
                  <div><img src="/images2/misc/1pix.gif" width="1" height="1" border="0">&nbsp;<span class="navlinks">The 
                    Company</span></div>
                  </a></td>
                <td class="Bolded"><font size="2" face="Verdana, Arial, Helvetica, sans-serif" color="#10243F">&laquo;</font></td>
              </tr>
            </table>
          </td>
        </tr>
        <tr bgcolor="#10243F"> 
          <td style="border='1 #10243F'" onMouseOver="style.backgroundColor='#809ECB'; style.cursor='hand'; style.border='1 #10243F'" onMouseOut="style.backgroundColor='#10243F'; style.border='1 #10243F';" height="21"> 
            <table width="100%" border="0" cellspacing="0" cellpadding="2">
              <tr> 
                <td bgcolor="#10243F" height="21" width="100%"><a href="/mediakit/" class="navlinks" style="margin:0;"> 
                  <div><img src="/images2/misc/1pix.gif" width="1" height="1" border="0">&nbsp;<span class="navlinks">Our 
                    Mediakit</span></div>
                  </a></td>
                <td class="Bolded"><font size="2" face="Verdana, Arial, Helvetica, sans-serif" color="#10243F">&laquo;</font></td>
              </tr>
            </table>
          </td>
        </tr>
        <tr bgcolor="#10243F"> 
          <td style="border='1 #10243F'" onMouseOver="style.backgroundColor='#809ECB'; style.cursor='hand'; style.border='1 #10243F'" onMouseOut="style.backgroundColor='#10243F'; style.border='1 #10243F';" height="21"> 
            <table width="100%" border="0" cellspacing="0" cellpadding="2">
              <tr> 
                <td bgcolor="#10243F" height="21" width="100%"><a href="/press.phtml" class="navlinks" style="margin:0;"> 
                  <div><img src="/images2/misc/1pix.gif" width="1" height="1" border="0">&nbsp;<span class="navlinks">Press 
                    Material</span></div>
                  </a></td>
                <td class="Bolded"><font size="2" face="Verdana, Arial, Helvetica, sans-serif" color="#10243F">&laquo;</font></td>
              </tr>
            </table>
          </td>
        </tr>
        <tr bgcolor="#10243F"> 
          <td style="border='1 #10243F'" onMouseOver="style.backgroundColor='#809ECB'; style.cursor='hand'; style.border='1 #10243F'" onMouseOut="style.backgroundColor='#10243F'; style.border='1 #10243F';" height="21"> 
            <table width="100%" border="0" cellspacing="0" cellpadding="2">
              <tr> 
                <td bgcolor="#10243F" height="21" width="100%"><a href="/contactus/" class="navlinks" style="margin:0;"> 
                  <div><img src="/images2/misc/1pix.gif" width="1" height="1" border="0">&nbsp;<span class="navlinks">Contact 
                    Us</span></div>
                  </a></td>
                <td class="Bolded"><font size="2" face="Verdana, Arial, Helvetica, sans-serif" color="#10243F">&laquo;</font></td>
              </tr>
            </table>
          </td>
        </tr>
      </table>
    </td>
  </tr>
</table>    
<TABLE width="124" border="0" cellspacing="0" cellpadding="1" bgcolor="#000000" background="/images/misc/50x50pix.gif">
  <TR align="center"> 
          <TD><IMG SRC="http://service.bfast.com/bfast/serve?bfmid=1307357&siteid=36766142&bfpage=1" BORDER="0" WIDTH="0" HEIGHT="0" NOSAVE >
<A HREF="http://service.bfast.com/bfast/click?bfmid=1307357&siteid=36766142&bfpage=1" TARGET="_top"><IMG SRC="http://www.gator.com/images/banners/gator_laughform_120x90.gif" BORDER="0" WIDTH="120" HEIGHT="90" ALT="Fills out forms, remembers passwords. Grab Gator!"></A><!--index: 1 num: 15 --></TD>
        </TR>
      </TABLE>
    </TD>
    <TD width="620" valign="top">  
      <TABLE width="100%" border="0" cellspacing="0" cellpadding="0" background="/images2/sections/resize.gif">
        <TR> 
          <TD><IMG src="/images2/misc/1pixblack.gif" width="1" height="63"></TD>
          <TD width="100%" valign="bottom"> 
            <TABLE width="100%" border="0" cellspacing="0" cellpadding="0" background="/images2/misc/50x50pix.gif">
              <TR> 
                <TD height="28"><SPAN class="Bolded"><IMG src="/images2/misc/1pix.gif" width="11" height="1">Page:</SPAN> 
									<SPAN class="bluebolded"> &nbsp;1&nbsp;of&nbsp;80</SPAN></TD>
              </TR>
            </TABLE>
          </TD>
          <TD align="right"><IMG src="/images2/sections/newsarchive.gif" width="275" height="63"></TD>
        </TR>
      </TABLE>
      <TABLE width="100%" border="0" cellspacing="0" cellpadding="0">
				<TR> 
					<TD valign="top" width="100%" align="center"> 
						<TABLE width="100%" border="0" cellspacing="0" cellpadding="0" background="/images2/buttons/resize.gif">
							<TR> 
								<TD><IMG src="/images2/buttons/archive.gif" width="130" height="25"></TD>
							</TR>
						</TABLE>
						<TABLE width="100%" border="0" cellspacing="1" cellpadding="0">
							<FORM method="post" action="/news.phtml">
								<TR> 
									<TD height="40"><IMG src="/images2/misc/1pix.gif" width="10" height="8"></TD>
									<TD height="40" width="100%" nowrap><SPAN class="Bolded"><SPAN class="bluebolded">Search 
										News:&nbsp;</SPAN></SPAN>&nbsp; 
										<INPUT type="text" name="search" class="formbody" size="14" maxlength="50" value="">
										&nbsp; 
										<SELECT name="rel_category" class="formbody">
											<option selected value="0">All</option>
<option  value="1">Action</option>
<option  value="15">Adventure</option>
<option  value="3">Hardware</option>
<option  value="16">Other</option>
<option  value="14">Peripherals</option>
<option  value="17">Puzzle</option>
<option  value="12">Racing</option>
<option  value="11">RPG</option>
<option  value="2">Simulation</option>
<option  value="4">Software</option>
<option  value="8">Sport</option>
<option  value="9">Strategy</option>
 
										</SELECT>
										&nbsp; &nbsp; 
										<INPUT type="image" border="0" name="imageField2" src="/images2/buttons/search_go.gif" width="24" height="22" align="top">
									</TD>
									<TD height="40" class="Bolded" align="right" nowrap> <!--Offset: 0 -->
1&nbsp;|&nbsp;<a href="?page=1&search=&cnt=79&rel_category=&sortby=">2</a>&nbsp;|&nbsp;<a href="?page=2&search=&cnt=79&rel_category=&sortby=">3</a>&nbsp;|&nbsp;<a href="?page=3&search=&cnt=79&rel_category=&sortby=">4</a>&nbsp;|&nbsp;<a href="?page=4&search=&cnt=79&rel_category=&sortby=">5</a>&nbsp;|&nbsp;<a href="?page=5&search=&cnt=79&rel_category=&sortby=">6</a>&nbsp;|&nbsp;<a href="?page=6&search=&cnt=79&rel_category=&sortby=">7</a>&nbsp;|&nbsp;<a href="?page=10&search=&cnt=79&rel_category=&sortby=">&gt;&gt;</a>
 &nbsp;&nbsp; <IMG src="/images2/misc/1pix.gif" width="10" height="1"></TD>
								</TR>
							</FORM>
						</TABLE>
							
<TABLE width="100%" border="0" cellspacing="0" cellpadding="0">
<TR>
<TD nowrap class="Bluebolded" background="/images2/buttons/resize.gif" height="25"><IMG src="/images2/misc/1pix.gif" width="11" height="1">Thursday, March 8</TD>
<TD width="100%" background="/images2/buttons/resize.gif" height="25" align="right" nowrap><A href="mailto:news@mgon.com">Report news</A>&nbsp;&nbsp;|&nbsp;&nbsp;<A href="/news.phtml">Archive</A>&nbsp;&nbsp;|&nbsp;&nbsp;<A href="#top">Top</A>&nbsp;&nbsp;&nbsp;</TD>
</TR>
</TABLE><TABLE width="100%" border="0" cellspacing="0" cellpadding="11"><TR><TD width="100%"><P><SPAN class="Headline">Quickfire News</SPAN> 
<TABLE width="100%" border="0" cellspacing="1" cellpadding="0">
<TR bgcolor="#335F5F"> 
<TD colspan="2" nowrap><IMG src="/images2/misc/1pix.gif" width="1" height="1"></TD>
</TR>
<TR>
<TD height="20" width="100%" nowrap><SPAN class="Bolded">Reported by: </SPAN><A href="javascript:Profile=open('/common/showprofile.phtml?id=', 'Profile','width=480,height=480,scrollbars=no,toolbar=no');Profile.focus();" >Dale</A>&nbsp;&nbsp;|&nbsp;&nbsp;<SPAN class="Bolded">Source: </SPAN> </TD>
<TD align="right" bgcolor="#335F5F" nowrap>&nbsp;&nbsp;<A href="/news.phtml?id=59876&language=en&action=comments">0 Comments</A> | <A href="/news.phtml?id=59876&language=en&action=comments#addcomment">Add</A>&nbsp;&nbsp;</TD>
</TR>
</TABLE>
<P><SPAN class="normal"><IMG src="/icons/0.gif" width="65" height="65" hspace="10" align="left" vspace="5" border="0">Sony's PlayStation 2 console has notched up an impressive 366,000 sales in the UK in just 101 days it emerged this week - with over one million software units having been sold in the same period.<br>
<br>
Despite the news this week of impressive PS2 figures, Derby's Core Design has decided to hold back the release of Project: Eden and Herdy Gerdy because of a perceived lack of installed base of the Sony machine.<br>
<br>
A comprehensive marketing and PR campaign is backing this Friday's (March 9) release of Acclaim's long-awaited drive 'em up Vanishing Point.<br>
<br>
With many publishers complaining about the high price of DVD duplication, Infodisc Technology is pledging to resolve such problems with competitively priced replication facilities.<br>
<br>
Titus Interactive has sealed a deal with Criterion Software licensing its multi-platform game development toolkit RenderWare 3 for a number of forthcoming titles produced by its studios across the world.<br>
<br>
Thanks goes out the the <a href='http://www.ctw.co.uk/' target="_blank"> Creative News Digest</a> for this information.<BR><!--No link--></SPAN></TD></TR></TABLE><TABLE width="100%" border="0" cellspacing="0" cellpadding="11"><TR><TD width="100%"><P><SPAN class="Headline">Fallout Tactics Gold</SPAN> 
<TABLE width="100%" border="0" cellspacing="1" cellpadding="0">
<TR bgcolor="#335F5F"> 
<TD colspan="2" nowrap><IMG src="/images2/misc/1pix.gif" width="1" height="1"></TD>
</TR>
<TR>
<TD height="20" width="100%" nowrap><SPAN class="Bolded">Reported by: </SPAN><A href="javascript:Profile=open('/common/showprofile.phtml?id=', 'Profile','width=480,height=480,scrollbars=no,toolbar=no');Profile.focus();" >Dale</A>&nbsp;&nbsp;|&nbsp;&nbsp;<SPAN class="Bolded">Source: </SPAN> </TD>
<TD align="right" bgcolor="#335F5F" nowrap>&nbsp;&nbsp;<A href="/news.phtml?id=59872&language=en&action=comments">0 Comments</A> | <A href="/news.phtml?id=59872&language=en&action=comments#addcomment">Add</A>&nbsp;&nbsp;</TD>
</TR>
</TABLE>
<P><SPAN class="normal"><IMG src="/icons/0.gif" width="65" height="65" hspace="10" align="left" vspace="5" border="0">Interplay has just sent word that the much anticipated Fallout Tactics has gone gold. You can now expect this very promising title to be on shelves in a store near you very soon.<br>
<br>
<i>14 Degrees East, a division of Interplay Entertainment Corp., proudly announced today that the highly anticipated game, Fallout Tactics: Brotherhood of Steel, has GONE GOLD!   Fallout Tactics: Brotherhood of Steel will be available at retail stores nationwide soon!</a><BR><P>[&nbsp;<a href="/news.phtml?id=59872&language=en">Read More...</a>&nbsp;]</SPAN></TD></TR></TABLE><TABLE width="100%" border="0" cellspacing="0" cellpadding="11"><TR><TD width="100%"><P><SPAN class="Headline">Microsoft Adds More Talent to Xbox</SPAN> 
<TABLE width="100%" border="0" cellspacing="1" cellpadding="0">
<TR bgcolor="#335F5F"> 
<TD colspan="2" nowrap><IMG src="/images2/misc/1pix.gif" width="1" height="1"></TD>
</TR>
<TR>
<TD height="20" width="100%" nowrap><SPAN class="Bolded">Reported by: </SPAN><A href="javascript:Profile=open('/common/showprofile.phtml?id=', 'Profile','width=480,height=480,scrollbars=no,toolbar=no');Profile.focus();" >Dale</A>&nbsp;&nbsp;|&nbsp;&nbsp;<SPAN class="Bolded">Source: </SPAN> </TD>
<TD align="right" bgcolor="#335F5F" nowrap>&nbsp;&nbsp;<A href="/news.phtml?id=59869&language=en&action=comments">0 Comments</A> | <A href="/news.phtml?id=59869&language=en&action=comments#addcomment">Add</A>&nbsp;&nbsp;</TD>
</TR>
</TABLE>
<P><SPAN class="normal"><IMG src="/icons/0.gif" width="65" height="65" hspace="10" align="left" vspace="5" border="0">Microsoft is adding more to what is going to be a very impressive development pool. With the Xbox providing a code base that most game developers are already familliar with I can see it quickly gaining on PS2 once released. After all the PS2 does not seem to have lived up to its promise far.<br>
<br>
<i>REDMOND, Wash. - March 8, 2001 - Microsoft Corp. today announced that six world-class design studios plan to create exclusive games for the XboxT video game system, all of which will be published under the Microsoft® label. The game companies, which join 18 other studios that are creating first-party games for Microsoft, are Blitz Games Ltd., Curly Monsters Ltd., Double Fine Productions Inc., Radical Entertainment Inc., Vision Scape Interactive Inc. and Yeti Interactive. These alliances further demonstrate the game community's confidence in Xbox and in Microsoft's commitment to becoming a leading video game publisher.</I><BR><P>[&nbsp;<a href="/news.phtml?id=59869&language=en">Read More...</a>&nbsp;]</SPAN></TD></TR></TABLE><TABLE width="100%" border="0" cellspacing="0" cellpadding="11"><TR><TD width="100%"><P><SPAN class="Headline">Severance Review</SPAN> 
<TABLE width="100%" border="0" cellspacing="1" cellpadding="0">
<TR bgcolor="#335F5F"> 
<TD colspan="2" nowrap><IMG src="/images2/misc/1pix.gif" width="1" height="1"></TD>
</TR>
<TR>
<TD height="20" width="100%" nowrap><SPAN class="Bolded">Reported by: </SPAN><A href="javascript:Profile=open('/common/showprofile.phtml?id=', 'Profile','width=480,height=480,scrollbars=no,toolbar=no');Profile.focus();" >Dale</A>&nbsp;&nbsp;|&nbsp;&nbsp;<SPAN class="Bolded">Source: </SPAN> </TD>
<TD align="right" bgcolor="#335F5F" nowrap>&nbsp;&nbsp;<A href="/news.phtml?id=59867&language=en&action=comments">0 Comments</A> | <A href="/news.phtml?id=59867&language=en&action=comments#addcomment">Add</A>&nbsp;&nbsp;</TD>
</TR>
</TABLE>
<P><SPAN class="normal"><IMG src="/icons/0.gif" width="65" height="65" hspace="10" align="left" vspace="5" border="0">Uros over at Actiontrip has sent a quick shout on their latest review.<br>
<br>
<i>Riddle me this, will ya? Why in the hell is Conan break dancing? Maybe they should've sharpened this Blade some more... <br>
<br>
Check out the review <a href='http://www.actiontrip.com/reviews/severancebladeofdarkness.phtml' target="_blank">right here</a>.</I><BR><!--No link--></SPAN></TD></TR></TABLE>
<TABLE width="100%" border="0" cellspacing="0" cellpadding="0">
<TR>
<TD nowrap class="Bluebolded" background="/images2/buttons/resize.gif" height="25"><IMG src="/images2/misc/1pix.gif" width="11" height="1">Wednesday, March 7</TD>
<TD width="100%" background="/images2/buttons/resize.gif" height="25" align="right" nowrap><A href="mailto:news@mgon.com">Report news</A>&nbsp;&nbsp;|&nbsp;&nbsp;<A href="/news.phtml">Archive</A>&nbsp;&nbsp;|&nbsp;&nbsp;<A href="#top">Top</A>&nbsp;&nbsp;&nbsp;</TD>
</TR>
</TABLE><TABLE width="100%" border="0" cellspacing="0" cellpadding="11"><TR><TD width="100%"><P><SPAN class="Headline">CPL Pacific</SPAN> 
<TABLE width="100%" border="0" cellspacing="1" cellpadding="0">
<TR bgcolor="#335F5F"> 
<TD colspan="2" nowrap><IMG src="/images2/misc/1pix.gif" width="1" height="1"></TD>
</TR>
<TR>
<TD height="20" width="100%" nowrap><SPAN class="Bolded">Reported by: </SPAN><A href="javascript:Profile=open('/common/showprofile.phtml?id=', 'Profile','width=480,height=480,scrollbars=no,toolbar=no');Profile.focus();" >Morten</A>&nbsp;&nbsp;|&nbsp;&nbsp;<SPAN class="Bolded">Source: </SPAN> </TD>
<TD align="right" bgcolor="#335F5F" nowrap>&nbsp;&nbsp;<A href="/news.phtml?id=59479&language=en&action=comments">0 Comments</A> | <A href="/news.phtml?id=59479&language=en&action=comments#addcomment">Add</A>&nbsp;&nbsp;</TD>
</TR>
</TABLE>
<P><SPAN class="normal"><IMG src="/icons/0.gif" width="65" height="65" hspace="10" align="left" vspace="5" border="0">In case the CPL Amateur's League isn't enough for you, the upcoming CPL Pacific event should be enough to give you some good competition. This is the info the CPL Press Center has announced so far:<br>
<br>
<b>CPL Pacific</b> - <a href="http://www.cplpacific.com">www.cplpacific.com</A> <br>
<b>Location:</b> Melbourne, Australia <br>
Flemington Racecourse ( <a href="http://www.cplpacific.com/images/hall_from_media_area.jpg">picture</A> ) <br>
<b>Dates: </b>March 31 - April 1, 2001 <br>
<b>Tournament Games: </b>Quake 3 and Counter-Strike <br>
<B>BYOC Capacity: </b>500 Computers <br>
<b>Cash Prizes: </b>$ 15,000 <br>
<b>Floor plan: </b><a href="http://www.cplpacific.com/images/floorplan33.gif">http://www.cplpacific.com/images/floorplan33.gif</A><br>
<b>Qualifiers: </b><a href="http://www.cplpacific.com/?agn=qualifiers">http://www.cplpacific.com/?agn=qualifiers</A><BR><!--No link--></SPAN></TD></TR></TABLE><TABLE width="100%" border="0" cellspacing="0" cellpadding="11"><TR><TD width="100%"><P><SPAN class="Headline">Medal of Honor Returns</SPAN> 
<TABLE width="100%" border="0" cellspacing="1" cellpadding="0">
<TR bgcolor="#335F5F"> 
<TD colspan="2" nowrap><IMG src="/images2/misc/1pix.gif" width="1" height="1"></TD>
</TR>
<TR>
<TD height="20" width="100%" nowrap><SPAN class="Bolded">Reported by: </SPAN><A href="javascript:Profile=open('/common/showprofile.phtml?id=', 'Profile','width=480,height=480,scrollbars=no,toolbar=no');Profile.focus();" >Warren</A>&nbsp;&nbsp;|&nbsp;&nbsp;<SPAN class="Bolded">Source: </SPAN> </TD>
<TD align="right" bgcolor="#335F5F" nowrap>&nbsp;&nbsp;<A href="/news.phtml?id=59406&language=en&action=comments">0 Comments</A> | <A href="/news.phtml?id=59406&language=en&action=comments#addcomment">Add</A>&nbsp;&nbsp;</TD>
</TR>
</TABLE>
<P><SPAN class="normal"><IMG src="/icons/13.gif" width="65" height="65" hspace="10" align="left" vspace="5" border="0">At an Electronic Arts press event earlier, the company revealed two new titles in the highly successful Medal of Honor series, both currently in development for the PlayStation 2.<br>
<br>
Of the titles, Medal of Honour: Frontline, is a mission based first person shooter, while Medal of Honor: Fighter Command, is a mission based air combat simulation.<br>
<br>
Head over to <A HREF="http://www.playstationcenter.com">PlayStationCenter </A> for first impressions and screenshots.<br><BR><!--No link--></SPAN></TD></TR></TABLE>
<TABLE width="100%" border="0" cellspacing="0" cellpadding="0">
<TR>
<TD nowrap class="Bluebolded" background="/images2/buttons/resize.gif" height="25"><IMG src="/images2/misc/1pix.gif" width="11" height="1">Tuesday, March 6</TD>
<TD width="100%" background="/images2/buttons/resize.gif" height="25" align="right" nowrap><A href="mailto:news@mgon.com">Report news</A>&nbsp;&nbsp;|&nbsp;&nbsp;<A href="/news.phtml">Archive</A>&nbsp;&nbsp;|&nbsp;&nbsp;<A href="#top">Top</A>&nbsp;&nbsp;&nbsp;</TD>
</TR>
</TABLE><TABLE width="100%" border="0" cellspacing="0" cellpadding="11"><TR><TD width="100%"><P><SPAN class="Headline">STAR TREK® BORG ASSIMILATOR</SPAN> 
<TABLE width="100%" border="0" cellspacing="1" cellpadding="0">
<TR bgcolor="#335F5F"> 
<TD colspan="2" nowrap><IMG src="/images2/misc/1pix.gif" width="1" height="1"></TD>
</TR>
<TR>
<TD height="20" width="100%" nowrap><SPAN class="Bolded">Reported by: </SPAN><A href="javascript:Profile=open('/common/showprofile.phtml?id=', 'Profile','width=480,height=480,scrollbars=no,toolbar=no');Profile.focus();" >Dale</A>&nbsp;&nbsp;|&nbsp;&nbsp;<SPAN class="Bolded">Source: </SPAN> </TD>
<TD align="right" bgcolor="#335F5F" nowrap>&nbsp;&nbsp;<A href="/news.phtml?id=59344&language=en&action=comments">0 Comments</A> | <A href="/news.phtml?id=59344&language=en&action=comments#addcomment">Add</A>&nbsp;&nbsp;</TD>
</TR>
</TABLE>
<P><SPAN class="normal"><IMG src="/icons/0.gif" width="65" height="65" hspace="10" align="left" vspace="5" border="0">Here is another game that has been hinted at a few times but no one was willing to come right out and confirm it. Well, here it is for all the Star Trek fans out there. <br>
<br>
<i>Santa Monica, CA &#8212; March 6, 2001 &#8212;Activision, Inc. (Nasdaq: ATVI) imposes order on the universe with the announcement of Star Trek® Borg Assimilator, the first world building sim set in the Star Trek universe.  The game is being developed by Cyberlore Studios, the team responsible for the highly acclaimed Majesty and the Warcraft II mission pack Beyond the Dark Portal, and will be available in the winter of 2001 for the PC.</I><BR><P>[&nbsp;<a href="/news.phtml?id=59344&language=en">Read More...</a>&nbsp;]</SPAN></TD></TR></TABLE><TABLE width="100%" border="0" cellspacing="0" cellpadding="11"><TR><TD width="100%"><P><SPAN class="Headline">Eternal Team Arena 1.0beta</SPAN> 
<TABLE width="100%" border="0" cellspacing="1" cellpadding="0">
<TR bgcolor="#335F5F"> 
<TD colspan="2" nowrap><IMG src="/images2/misc/1pix.gif" width="1" height="1"></TD>
</TR>
<TR>
<TD height="20" width="100%" nowrap><SPAN class="Bolded">Reported by: </SPAN><A href="javascript:Profile=open('/common/showprofile.phtml?id=', 'Profile','width=480,height=480,scrollbars=no,toolbar=no');Profile.focus();" >Corven</A>&nbsp;&nbsp;|&nbsp;&nbsp;<SPAN class="Bolded">Source: </SPAN> </TD>
<TD align="right" bgcolor="#335F5F" nowrap>&nbsp;&nbsp;<A href="/news.phtml?id=59301&language=en&action=comments">0 Comments</A> | <A href="/news.phtml?id=59301&language=en&action=comments#addcomment">Add</A>&nbsp;&nbsp;</TD>
</TR>
</TABLE>
<P><SPAN class="normal"><IMG src="/icons/0.gif" width="65" height="65" hspace="10" align="left" vspace="5" border="0">what? all the eternal features in team arena too? somebody spank me! <br>
<br>
That's right folks, all the original Eternal Arena Q3 <A HREF="http://www.q3center.com/ea/etafeatures.phtml" target="_blank">features </A> have now been coded into Eternal Team Arena. So if you've ever wanted to play TA with offhand grapple, bloodtrails, weapon dropping, player cloaking and fully configurable weapons and items, plus all the gamemodes like instagib rails, pain factor, hunted or rocket duel, then you better grab <A HREF="http://www.q3center.com/eadownloadsindex.phtml?id=59288&language=en" target="_blank">ETA v1.0beta</A> right now!... and bring a spare pair of pants.<BR><!--No link--></SPAN></TD></TR></TABLE><TABLE width="100%" border="0" cellspacing="0" cellpadding="11"><TR><TD width="100%"><P><SPAN class="Headline">Serious Sam Juice</SPAN> 
<TABLE width="100%" border="0" cellspacing="1" cellpadding="0">
<TR bgcolor="#335F5F"> 
<TD colspan="2" nowrap><IMG src="/images2/misc/1pix.gif" width="1" height="1"></TD>
</TR>
<TR>
<TD height="20" width="100%" nowrap><SPAN class="Bolded">Reported by: </SPAN><A href="javascript:Profile=open('/common/showprofile.phtml?id=', 'Profile','width=480,height=480,scrollbars=no,toolbar=no');Profile.focus();" >Dale</A>&nbsp;&nbsp;|&nbsp;&nbsp;<SPAN class="Bolded">Source: </SPAN> </TD>
<TD align="right" bgcolor="#335F5F" nowrap>&nbsp;&nbsp;<A href="/news.phtml?id=59209&language=en&action=comments">0 Comments</A> | <A href="/news.phtml?id=59209&language=en&action=comments#addcomment">Add</A>&nbsp;&nbsp;</TD>
</TR>
</TABLE>
<P><SPAN class="normal"><IMG src="/icons/0.gif" width="65" height="65" hspace="10" align="left" vspace="5" border="0">Our Aussie connection comes through with some Info on the upcoming Serious Sam. A title that has garnered a fair amount interest that you can guarantee will be reviewed here pretty shortly.<br>
<br>
<i>Jack of All Games, Sydney, Australia is ecstatic to announce the release of one of this year's high-action, highly anticipated games on PC CD -Serious Sam. Serious Sam is a high-adrenaline arcade-action shooter heavily focused on frantic arcade-style single player action. In a world where cyberpunk meets fantasy-fiction and advanced technology is mixed with black magic and psycho-powers, Sam travels through the beautiful world of ancient Egypt and several diverse planets, confronting countless Mental's minions on his way to the Mental's base.</i><br>
<BR><P>[&nbsp;<a href="/news.phtml?id=59209&language=en">Read More...</a>&nbsp;]</SPAN></TD></TR></TABLE><TABLE width="100%" border="0" cellspacing="0" cellpadding="11"><TR><TD width="100%"><P><SPAN class="Headline">Lara Movie Poster Revealed</SPAN> 
<TABLE width="100%" border="0" cellspacing="1" cellpadding="0">
<TR bgcolor="#335F5F"> 
<TD colspan="2" nowrap><IMG src="/images2/misc/1pix.gif" width="1" height="1"></TD>
</TR>
<TR>
<TD height="20" width="100%" nowrap><SPAN class="Bolded">Reported by: </SPAN><A href="javascript:Profile=open('/common/showprofile.phtml?id=', 'Profile','width=480,height=480,scrollbars=no,toolbar=no');Profile.focus();" >Warren</A>&nbsp;&nbsp;|&nbsp;&nbsp;<SPAN class="Bolded">Source: </SPAN> </TD>
<TD align="right" bgcolor="#335F5F" nowrap>&nbsp;&nbsp;<A href="/news.phtml?id=59202&language=en&action=comments">1 Comments</A> | <A href="/news.phtml?id=59202&language=en&action=comments#addcomment">Add</A>&nbsp;&nbsp;</TD>
</TR>
</TABLE>
<P><SPAN class="normal"><IMG src="/icons/165.gif" width="65" height="65" hspace="10" align="left" vspace="5" border="0">Angelina Jolie as Lara Croft. Mmmmmm. Those five words combined are enough to make any red blooded gamer drool. But, better still, the official movie poster has been revealed to the world, and you can now check her out in detail like never before.  Head over to <A HREF="http://www.playstationcenter.com/news.phtml?id=59192&language=en">PlaystationCenter</A> to take a closer look.<br>
<br>
What are you waiting for?<br> <BR><!--No link--></SPAN></TD></TR></TABLE><TABLE width="100%" border="0" cellspacing="0" cellpadding="11"><TR><TD width="100%"><P><SPAN class="Headline">Xbox Delayed in Japan?</SPAN> 
<TABLE width="100%" border="0" cellspacing="1" cellpadding="0">
<TR bgcolor="#335F5F"> 
<TD colspan="2" nowrap><IMG src="/images2/misc/1pix.gif" width="1" height="1"></TD>
</TR>
<TR>
<TD height="20" width="100%" nowrap><SPAN class="Bolded">Reported by: </SPAN><A href="javascript:Profile=open('/common/showprofile.phtml?id=', 'Profile','width=480,height=480,scrollbars=no,toolbar=no');Profile.focus();" >Warren</A>&nbsp;&nbsp;|&nbsp;&nbsp;<SPAN class="Bolded">Source: </SPAN> </TD>
<TD align="right" bgcolor="#335F5F" nowrap>&nbsp;&nbsp;<A href="/news.phtml?id=59201&language=en&action=comments">0 Comments</A> | <A href="/news.phtml?id=59201&language=en&action=comments#addcomment">Add</A>&nbsp;&nbsp;</TD>
</TR>
</TABLE>
<P><SPAN class="normal"><IMG src="/icons/30.gif" width="65" height="65" hspace="10" align="left" vspace="5" border="0">The latest reports from Japan suggest that the Xbox launch in Japan, may be delayed as Japanese gamers and gaming companies have been less than enthusiastic about the console.<br>
<br>
While the machine is slated for a late 2001 release in both the US and Japan, reports suggest that Microsoft may move the Japanese date in line with the March 2002 European date, to give consumers, retailers and developers time to grow accustomed to the console.<br>
<br>
While this is bad news for Microsoft, Nintendo executives will be delighted with the news, as they may now receive the head start they have so desired, to keep ahead in the console race for the region.<BR><!--No link--></SPAN></TD></TR></TABLE><TABLE width="100%" border="0" cellspacing="0" cellpadding="11"><TR><TD width="100%"><P><SPAN class="Headline">Dreamcast Sales Soar</SPAN> 
<TABLE width="100%" border="0" cellspacing="1" cellpadding="0">
<TR bgcolor="#335F5F"> 
<TD colspan="2" nowrap><IMG src="/images2/misc/1pix.gif" width="1" height="1"></TD>
</TR>
<TR>
<TD height="20" width="100%" nowrap><SPAN class="Bolded">Reported by: </SPAN><A href="javascript:Profile=open('/common/showprofile.phtml?id=', 'Profile','width=480,height=480,scrollbars=no,toolbar=no');Profile.focus();" >Warren</A>&nbsp;&nbsp;|&nbsp;&nbsp;<SPAN class="Bolded">Source: </SPAN> </TD>
<TD align="right" bgcolor="#335F5F" nowrap>&nbsp;&nbsp;<A href="/news.phtml?id=59200&language=en&action=comments">0 Comments</A> | <A href="/news.phtml?id=59200&language=en&action=comments#addcomment">Add</A>&nbsp;&nbsp;</TD>
</TR>
</TABLE>
<P><SPAN class="normal"><IMG src="/icons/2.gif" width="65" height="65" hspace="10" align="left" vspace="5" border="0">Sega's Dreamcast console may be dead and buried, but this hasn't stopped Japanese gamers from wanting a piece of the console pie.<br>
<br>
Statistics in from Japan suggest that Dreamcast hardware sales have increased by up to 400% since the console's demise was announced, and industry analysts are left baffled as to why Sega could not achieve such favourable results before now.  C'est la vie, Sega!<BR><!--No link--></SPAN></TD></TR></TABLE>  
						</TABLE>
					</TD>
				</TR>
			</TABLE>
			<P> </TR>
			</TABLE>
    </TD>
  </TR>
</TABLE>
 
<TABLE width="750" border="0" cellspacing="0" cellpadding="0">
  <TR> 
    <TD><IMG src="/images2/bottom/copyright.gif" width="340" height="30" border="0"><A href="/privacy.phtml"><IMG src="/images2/bottom/privacy.gif" width="101" height="30" border="0"></A></TD>
    <TD><IMG src="/images2/bottom/bottomplate.gif" width="177" height="30"></TD>
    <TD><A href="#top"><IMG src="/images2/bottom/top.gif" width="68" height="30" border="0"></A></TD>
    <TD><A href="/index.phtml"><IMG src="/images2/bottom/home.gif" width="64" height="30" border="0"></A></TD>
  </TR>
</TABLE>
<TABLE width="750" border="0" cellspacing="0" cellpadding="0" height="90" background="/images2/misc/50x50pix.gif">
  <TR bgcolor="#000000" align="center"> 
    <TD class="smalltext">
      <SCRIPT language="JavaScript"
src="http://adtegrity.spinbox.net/?DC=Mgon+Bottom&JS=Y&TARGET=_new">
</SCRIPT>
      <NOSCRIPT><A href="http://adtegrity.spinbox.net/?SHT=Mgon+Bottom" target="_new"
height="468" width="60"><IMG src="http://adtegrity.spinbox.net/?SIT=Mgon+Bottom" border="0"></A></NOSCRIPT></TD>
  </TR>
</TABLE>
  
<!--Bottom Layer-->
<LAYER SRC="http://ad.se.doubleclick.net/adl/mgon.com/;sz=468x60;ord=984099114?" bgcolor="#000000" width="468" height="60" visibility="hidden" onLoad="moveToAbsolute(layer1.pageX,layer1.pageY);clip.height=60;clip.width=468; visibility='show';"></LAYER><!--End Bottom Layer--></BODY>

</HTML>


