<!doctype html public "-//w3c//dtd html 4.0 transitional//en"><html><head><meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"><meta name="GENERATOR" content="Mozilla/4.7 [en] (Win98; I) [Netscape]"><meta name="Author" content="Jeff Moyer"><meta name="Description" content="Read and discuss strategies for playing particular classes, races, zones and trade skills."><meta name="KeyWords" content="everquest, Everquest, class, race, zone, guide, strategy, spoiler, Norrath, Antonica, Kunark"><title>AllaKhazam's Links Resource</title><!-- Changed by: , 17-Aug-2000 --><LINK REL=STYLESHEET TYPE="text/css" HREF="/style.css"></head><body><layer id=one top=0 left=0><LINK REL=STYLESHEET TYPE="text/css" HREF="/style.css"><table  width=100% cellpadding=0 cellspacing=0 border=0><tr><td abgcolor=#B49871  rowspan=2></td><td align=center><img SRC="http://everquest.allakhazam.com/strategy/realm8.gif" NATURALSIZEFLAG="0" height=50 width=302 align=BOTTOM vspace=10 alt="Allakhazam's Magic Realm"><img src="http://eqdb.allakhazam.com/eqc.gif"></td></tr><tr><td align=center><div align="center"><iframe src="http://www.allakhazam.com/counter-bin/stcode.php?"
WIDTH=468 HEIGHT=60 MARGINWIDTH=0 MARGINHEIGHT=0 HSPACE=0
VSPACE=0 FRAMEBORDER=0 SCROLLING=no BORDERCOLOR="#000000"></iframe></div></td></tr><tr><td bgcolor="#CC0000" height=2 colspan=2><spacer type=block width=1 height=1></td></tr></table><table width="100%" cellspacing=0 cellpadding=0 border=0><tr><td height=10 align="center">&nbsp;</td></tr></table><table width="100%" cellpadding=0 cellspacing=0 border=0><tr><td bgcolor="#666666" height=2><spacer type=block width=1 height=1></td></tr><tr><td><table width="100%" cellpadding=4 cellspacing=0 border=0><tr><td><b><font face="Arial,Helvetica">Search Options</font></b></td></tr></table></td></tr><tr><td bgcolor="#666666" height=2><spacer type=block width=1 height=1></td></tr></table><table width="100%" cellpadding=2 cellspacing=0 border=0><tr><td>&nbsp;</td></tr></table><table width="75%" cellspacing=0 cellpadding=0 border=0><tr valign="top"><td bgcolor="#B1A67E"><font face="Arial,Helvetica" size=-1>&nbsp;</font></td></tr><tr><td height=4><spacer type="block" width=1 height=1></td></tr></table><form action="http://links.allakhazam.com/cgi-bin/search.cgi" method="GET"><div class="margin"><table border="0" cellpadding="0" cellspacing="0"><tr><td>Search: <input type="TEXT" name="query" size="30"> <input type="Submit" value="Search"></td></tr><tr><td>Number of Results: <SELECT name="mh"><OPTION>10<OPTION selected>25<OPTION>50<OPTION>100</SELECT></td></tr><tr><td>AND connector: <input type="RADIO" name="bool" value="and" checked> OR connector: <input type="RADIO" name="bool" value="or"></td></tr><tr><td>Substring: <input type="RADIO" name="substring" value="1"> Exact Word: <input type="RADIO" name="substring" value=0 checked></td></tr></table></div></form><p>&nbsp;</p><p><table bgcolor="#CCCCCC" width="100%" cellspacing=0 cellpadding=4 border=0><tr><td>&nbsp;</td></tr></table><table width="100%" cellspacing=0 cellpadding=0 border=0><tr><td bgcolor="#666666" height=2 colspan=3><spacer type=block width=1 height=1></td></tr><tr><td width="14%" rowspan=3><table width="100%" border="0" cellpadding="0" cellspacing="1"><tr bgcolor="#CC0000"><td><small class="menu"><img src="/images/templates/snap/pseudosnap_small.gif" height="25" width="103"></small></td></tr></table></td><td width="84%" align=center height=27><small class="menu">| <a class="menulink" href="http://links.allakhazam.com/pages">Home</a>
 | <a class="menulink" href="http://links.allakhazam.com/cgi-bin/add.cgi">Add a Site</a>
 | <a class="menulink" href="http://links.allakhazam.com/cgi-bin/modify.cgi">Modify a Site</a>
 | <a class="menulink" href="http://links.allakhazam.com/pages/New">What's
 New</a> |</small></td><td width="2%">&nbsp;</td></tr><tr><td bgcolor="#CC0000" height=2 colspan=2><spacer type=block width=1 height=1></td></tr><tr><td align=center height=25 width="84%"><small class="menu"> | <a class="menulink" href="http://links.allakhazam.com/pages/Cool">What's
 Cool</a> | <a class="menulink" href="http://links.allakhazam.com/pages/Ratings">Top
 Rated</a> | <a class="menulink" href="http://links.allakhazam.com/cgi-bin/jump.cgi?ID=random">Random
 Link</a> | <a class="menulink" href="http://links.allakhazam.com/cgi-bin/search.cgi">Search</a>
 | </small></td><td width="2%"><spacer type=block width=1 height=1></td></tr></table><p><small class="update">Pages Updated On: 2001-04-07 - 21:03:31<br></small></p><p class="grandtotal">&nbsp;</p></p></body></html>
