<!--
                 This page has been created by Renaissance IT
   Renaissance Internet Technologies Copyright (c) 1999 All Rights Reserved.

             for more info on our products, please visit :
                        http://www.renaissance.nl/

	This script has been written by Roy Boverhof <rboverhof@renaissance.nl>
	
        Pagename                : fear.phtml
        Last Updated    		: 08-29-2000
-->

<HTML>
<HEAD>
	<TITLE>the Seekers of Lore : Fear</TITLE>
</HEAD>

<BODY BGCOLOR="#000000" TEXT="#000000" LINK="#000000" VLINK="#000000" ALINK="#000000">
<DIV ALIGN="CENTER">
<BR>
<!-- FGN Banner Code -->
<script language="JavaScript">
	<!-- Hide from old browsers
	var random = new Number(Math.floor(9999999 * Math.random())+1);

	// Modify to reflect site specifics
	page = "eqlore.com/";
	target = "@Top1,x02,x05,x08!Top1";

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript1.1" SRC="http://oascentral.cybereps.com/RealMedia/ads/adstream_jx.ads/' + page + 1 + random + target + '">');
	document.write('</SCR');
	document.write('IPT>');

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript">');
	document.write('_version=10; //-->');
	document.write('</SCR');
	document.write('IPT>');

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript1.1">');
	document.write('_version=11; //-->');
	document.write('</SCR');
	document.write('IPT>');

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript">');

	if (navigator.appVersion.indexOf('MSIE 3') != -1){
	document.write('<IFRAME MARGINWIDTH=0 MARGINHEIGHT=0 HSPACE=0 VSPACE=0 FRAMEBORDER=0 SCROLLING=no BORDERCOLOR="#000000" SRC="oascentral.cybereps.com/RealMedia/ads/adstream_sx.ads/' + page + random + target + '"></IFRAME>');
	  }
	else if (_version < 11) {
	document.write ('<A HREF="http://oascentral.cybereps.com/RealMedia/ads/click_nx.ads/' + page + random + target + '"><IMG SRC="http://oascentral.cybereps.com/RealMedia/ads/adstream_nx.ads/' + page + random + target + '"></a>');
	  }

	document.write('</SCR');
	document.write('IPT>');

	// End Hide -->
</script>
<!-- END FGN Banner Code --><BR>
<TABLE CELLSPACING = 0 CELLPADDING = 0 BORDER = 0>
<TR>
	<TD width="63"><IMG SRC = "../graphics/topc000.jpg" WIDTH = 63 HEIGHT = 87></TD>
	<TD width="473"><IMG SRC = "../graphics/topc001.jpg" WIDTH = 473 HEIGHT = 87></TD>
	<TD width="64"><IMG SRC = "../graphics/topc002.jpg" WIDTH = 64 HEIGHT = 87></TD>
</TR>
	<TD width="63"></TD>
	<TD BGCOLOR="#BEA279" width="460">
	<DIV ALIGN="CENTER">
	<TABLE>
	<TR>

	<TD BGCOLOR="#BEA279" width="400">

	
	<P><BR><CENTER><FONT SIZE="+2"><B><I>Fear</I></B></FONT><BR>By Foladen Moonsong of The Rathe<BR></CENTER>

	<FONT SIZE="-1">
	
<P>&nbsp;&nbsp;&nbsp;&nbsp;<FONT SIZE="+1"><B>A</B></FONT> slow hot breeze wafted by the bard. he reveled in what little comfort it gave him. To Hades with this blasted place and this wall of fire thought Foladen. Grimly he returned to sharpening his swords. His concentration was broken by a bellowing yell.

<P>"<I>Myron!!!!!</I>"

<P>&nbsp;&nbsp;&nbsp;&nbsp;<FONT SIZE="+1"><B>H</B></FONT>e grimaced as his friend fell dead to the infernal touch of the god Cazic Thule. He moved away as another cleric rushed to their fallen comrades side in order to restore life to his broken body. A blue glow enveloped Myron and gingerly he rose to his feet, weakened but once again amongst the living.

<P>&nbsp;&nbsp;&nbsp;&nbsp;<FONT SIZE="+1"><B>T</B></FONT>he time had come. Foladen strode forward and turned to the ranks behind him.

<P>"<I>I have had enough of this crap. We came here for a reason, to kill that beast that calls itself immortal and end its reign of terror. Instead, it taunts us and strikes us down at will. WELL NO MORE! Its time to end this farce. Prepare ranks!</I>"

<P>&nbsp;&nbsp;&nbsp;&nbsp;<FONT SIZE="+1"><B>Q</B></FONT>uickly the alliance formed into well formed ranks. Foladen saluted the brave druid who ran forth to taunt Cazic Thule into their trap, therefore nobly giving his life. The sound of booming footsteps closing in, followed by a short anguished scream told him that the trap had worked.Without a single hesitation he gave the command, "<I>ATTACK!</I>" With a wave of his sword, the onslaught began.

<P>&nbsp;&nbsp;&nbsp;&nbsp;<FONT SIZE="+1"><B>T</B></FONT>he battle raged for 2 days and each time the noble warriors came near the foul beast it called upon its hordes to defend it and struck from afar. Not once were they able to reach the cowardly creature. The hordes of demons were cut down like stalks of wheat. Yet time and time again did Cazic Thule strike them down, yet they did not give up. Again and again they charged and attacked the pit of evil.

<P>&nbsp;&nbsp;&nbsp;&nbsp;<FONT SIZE="+1"><B>I</B></FONT>n the end, Foladen fell to his knees. Breathing heavily from exhaustion. He had lost feeling in his sword arm hours ago and his armor bore the marks of claws and teeth. HE leaned heavily on his gore covered blades. Grimly he rose to his feet and called for them to leave. Enough was enough, there was nothing more to be gained here this day. He signaled to his officers to gather the treasures they had earned and to take them with him. "<I>At least</I>" he thought, "<I>I can suffer the anguish of knowing his minions are dead and we walk out of here with his most treasured gifts.</I>"

<P>"<I>CAZIC</I>" he shouted, "<I>This is not over with. Next time you will not hide from us. Hear me well and hear this oath. If it takes until the day I die I will carry your wretched head home as a trophy. WE WILL RETURN!</I>" And with a command they left.<BR><BR>

<B>August 25th & 26th, 2000</B><BR><BR>


<B>Day 1 Loot:</B>
<HR SIZE=2>
Miri - <I>Thorny Vine Boots</I> <BR>
Nibian - <I>Umbral Boots and Helm</I> <BR>
Beguilaen - <I>Wand of Lava</I> <BR>
Fladar - <I>Wand of Allure</I> <BR>
Silia - <I>Carmine Pants</I> <BR>
Wildinar - <I>Vermiculated BP</I> <BR>
Nekkon - <I>Vermiculated BP</I> <BR>
Typfon - <I>Vermiculated BP</I> <BR>
Etrigan - <I>Amyygdalan Tendril</I> <BR>
Lylani - <I>Vermiculated Arms</I> <BR>
Hrvatsko - <I>Valorium Vambraces</I> <BR>
Nalonius - <I>Cryoslik Pants ( i think)</I><BR><BR>

<B>Day 2 Loot:</B>
<HR SIZE=2>
Bakun - <I>Cryosilk Veil</I> <BR>
Clou - <I>Shiveback Legs </I><BR>
Nibian - <I>Umbral Pants (the boy is now full planes gear wtg man!!!)</I><BR>
Saorn - <I>Valorium Boots</I> <BR>
Roothless - <I>Valorium Vambraces</I> <BR>
Etrigan -  <I>Nautilus Shield</I> <BR>
Aesthir - <I>Flayed Turmoil Skin Belt</I> <BR>
Gmish - <I>Wand of Lava</I><BR><BR>
</FONT>

	</TD>
	</TR>
	</TABLE>
<TABLE>
<TR>
<TD><A HREF="http://www.loreseekers.com/tales.phtml"><IMG SRC="http://www.loreseekers.com/graphics/tales_return_link.jpg" WIDTH=200 HEIGHT=75 ALT="Read some other stories by our members!" BORDER="0"></A></TD>
</TR>
</TABLE>

	<TD width="64"></TD>
<TR>
	<TD><IMG SRC = "../graphics/botc000.jpg" WIDTH = 63 HEIGHT = 87></TD>
	<TD><IMG SRC = "../graphics/botc001.jpg" WIDTH = 473 HEIGHT = 87></TD>
	<TD><IMG SRC = "../graphics/botc002.jpg" WIDTH = 64 HEIGHT = 87></TD>
</TR>
</TABLE>
<BR>
<IMG SRC="http://service.bfast.com/bfast/serve?bfmid=1375281&siteid=40292692&bfpage=pc" BORDER="0" WIDTH="1" HEIGHT="1" NOSAVE ><A HREF="http://service.bfast.com/bfast/click?bfmid=1375281&siteid=40292692&bfpage=pc" TARGET="_new"><IMG SRC="http://affiliate.gamestop.com/affIMG/pc_120x60.gif" BORDER="0" WIDTH="120" HEIGHT="60" ALT="PC Games at GameStop.com"></A>
<BR>
<BR>
</DIV>
</BODY>
</HTML>