<!--
                 This page has been created by Renaissance IT
   Renaissance Internet Technologies Copyright (c) 1999 All Rights Reserved.
             for more info on our products, please visit :
                        http://www.renaissance.nl/

	This script has been written by Roy Boverhof <rboverhof@renaissance.nl>

        Pagename                : links1.html
        Last Updated    		: 09-27-2000
-->


<HTML>
<HEAD>
	<TITLE>the Seekers of Lore : General EQ Links</TITLE>
</HEAD>

<BODY BGCOLOR="#000000" TEXT="#000000" LINK="#BEA279" VLINK="#BEA279">
<DIV ALIGN="CENTER">
<BR>
<!-- FGB Banner Code -->
<SCRIPT LANGUAGE="JavaScript">
<!-- Hide from old browsers
now = new Date();
random = now.getTime();

// Modify to reflect site specifics
site = "http://ds.cybereps.com";
target = "/SITE=FGN/AREA=EQLORE/AAMSZ=BANNER";

document.write('<IFRAME SRC="' + site + '/hserver/acc_random=' + random + target + '"');
document.write(' NORESIZE SCROLLING=NO HSPACE=0 VSPACE=0 FRAMEBORDER=0 MARGINHEIGHT=0 MARGINWIDTH=0 WIDTH=468 HEIGHT=60>');

document.write('<SCR');
document.write('IPT SRC="' + site + '/jnserver/acc_random=' + random + target + '">');
document.write('</SCR');
document.write('IPT>');

document.write('</IFRAME>');
// End Hide -->
</SCRIPT>

<NOSCRIPT><A HREF="http://ds.cybereps.com/accipiter/adclick/SITE=FGN/AREA=EQLORE/AAMSZ=BANNER"><IMG SRC="http://ds.cybereps.com/accipiter/nserver/SITE=FGN/AREA=EQLORE/AAMSZ=BANNER" border="0"></A></NOSCRIPT>
<!-- END FGB Banner Code -->
<BR>
<TABLE CELLSPACING = 0 CELLPADDING = 0 BORDER = 0>
<TR>
	<TD width="63"><IMG SRC = "graphics/topc000.jpg" WIDTH = 63 HEIGHT = 87></TD>
	<TD width="473"><IMG SRC = "graphics/topc001.jpg" WIDTH = 473 HEIGHT = 87></TD>
	<TD width="64"><IMG SRC = "graphics/topc002.jpg" WIDTH = 64 HEIGHT = 87></TD>
</TR>
<TR>
	<TD width="63"></TD>
	<TD BGCOLOR="#BEA279" width="460">
	<DIV ALIGN="CENTER">
	<A HREF="links.phtml"><IMG SRC="graphics/linkheader.jpg" WIDTH ="200" HEIGHT ="75" ALT="Back to Links Index"></A>
	<TABLE WIDTH=440 ALIGN="center">
	<TR><TD></TD></TR>
	<TR>
		<TD>
		<A HREF="https://www.station.sony.com/store/" TARGET="_new"><IMG SRC="graphics/sony_store_link.jpg" WIDTH ="220" HEIGHT ="75" ></A>
		</TD>
		<TD><FONT FACE="Verdana" SIZE="-2" COLOR="#FF0000">New! - </FONT><FONT FACE="Verdana" SIZE="-2">Sony's Official Online Store. You may purchase the seperate Kunark Upgrade here finally.</FONT></TD>
	</TR>
	<TR>
	<TR>
		<TD>
		<A HREF="http://everquest.station.sony.com/velious/index.html" TARGET="_new"><IMG SRC="graphics/velious_link.jpg" WIDTH ="220" HEIGHT ="75" ></A>
		</TD>
		<TD><FONT FACE="Verdana" SIZE="-2">Sony's Official <I>Scars of Velious</I>™ website. The new expansion due out at the end of 2000.</FONT></TD>
	</TR>
	<TR>
		<TD>
		<A HREF="http://www.everquest.com/" TARGET="_new"><IMG SRC="graphics/everquest_link.jpg" WIDTH ="220" HEIGHT ="75" ></A>
		</TD>
		<TD><FONT FACE="Verdana" SIZE="-2">Sony's Official <I>EverQuest</I>™ Homepage</FONT></TD>
	</TR>
	<TR>
		<TD>
		<A HREF="http://everquest.station.sony.com/kunark/index.html" TARGET="_new"><IMG SRC="graphics/kunark_link.jpg" WIDTH ="220" HEIGHT ="75" ></A>
		</TD>
		<TD><FONT FACE="Verdana" SIZE="-2">Sony's official <I>Ruins of Kunark</I>™ website..</FONT></TD>
	</TR>
	<TR>
		<TD>
		<A HREF="http://www.verant.com/" TARGET="_new"><IMG SRC="graphics/verant_link.jpg" WIDTH ="220" HEIGHT ="75" ></A>
		</TD>
		<TD><FONT FACE="Verdana" SIZE="-2">Verant Interactive. Producers of EverQuest.</FONT></TD>
	</TR>
	<TR>
		<TD>
		<A HREF="http://eqvault.ign.com/" TARGET="_new"><IMG SRC="graphics/eqvault_link.jpg" WIDTH ="220" HEIGHT ="75" ></A>
		</TD>
		<TD><FONT FACE="Verdana" SIZE="-2">One of the oldest and most popular EQ sites on the net.</FONT></TD>
	</TR>
	<TR>
		<TD>
		<A HREF="http://everquest.allakhazam.com/" TARGET="_new"><IMG SRC="graphics/allakhazam_link.jpg" WIDTH ="220" HEIGHT ="75" ></A>
		</TD>
		<TD><FONT FACE="Verdana" SIZE="-2">The most complete and up to date information on EQ available! ***New URL***</FONT></TD>
	</TR>
	<TR>
		<TD>
		<A HREF="http://eq.stratics.com/" TARGET="_new"><IMG SRC="graphics/eqss_link.jpg" WIDTH ="220" HEIGHT ="75" ></A>
		</TD>
		<TD><FONT FACE="Verdana" SIZE="-2">EverQuest Stratics - another excellant site. Very well laid out and informative forums.</FONT></TD>
	</TR>
	<TR>
		<TD>
		<A HREF="http://www.gameznet.com/eq/index.shtml" TARGET="_new"><IMG SRC="graphics/eqlizer_link.jpg" WIDTH ="220" HEIGHT ="75" ></A>
		</TD>
		<TD><FONT FACE="Verdana" SIZE="-2">Quality information site with many higher level items and information.</FONT></TD>
	</TR>
	<TR>
		<TD>
		<A HREF="http://www.everlore.com/" TARGET="_new"><IMG SRC="graphics/everlore_link.jpg" WIDTH ="220" HEIGHT ="75" ></A>
		</TD>
		<TD><FONT FACE="Verdana" SIZE="-2">Another quality site with especially good spell information.</FONT></TD>
	</TR>
	<TR>
		<TD>
		<A HREF="http://members.home.net/casinobound/" TARGET="_new"><IMG SRC="graphics/sand_link.jpg" WIDTH ="220" HEIGHT ="75" ></A>
		</TD>
		<TD><FONT FACE="Verdana" SIZE="-2">Sanderson's Quest - A new source of EQ and RoK information.</FONT></TD>
	</TR>
	<TR>
		<TD>
		<A HREF="http://onlinegames.pagina.nl/" TARGET="_new"><IMG SRC="graphics/startpagina_link.jpg" WIDTH ="220" HEIGHT ="75" ></A>
		</TD>
		<TD><FONT FACE="Verdana" SIZE="-2"><FONT FACE="Verdana" SIZE="-2" COLOR="#FF0000">New! - </FONT>Online Games @ Startpagina - A great source of links to just about every good site on the net for our Dutch visitors. (Dutch Language Site)</FONT></TD>
	</TR>

	<TR>
		<TD>
		<A HREF="mailto:webmaster@loreseekers.com?subject=links"><IMG SRC="graphics/submit_link.jpg" WIDTH ="220" HEIGHT ="75" ></A>
		</TD>
		<TD><I>Do you know a quality EverQuest site? Email us your link!</I></TD>
	</TR>
	</TABLE>
	<TD width="64"></TD>
<TR>
	<TD><IMG SRC = "graphics/botc000.jpg" WIDTH = 63 HEIGHT = 87></TD>
	<TD><IMG SRC = "graphics/botc001.jpg" WIDTH = 473 HEIGHT = 87></TD>
	<TD><IMG SRC = "graphics/botc002.jpg" WIDTH = 64 HEIGHT = 87></TD>
</TR>
</TABLE>
<BR>
<SCRIPT LANGUAGE="JavaScript">
<!-- Hide from old browsers
now = new Date();
random = now.getTime();

// Modify to reflect site specifics
site = "http://ds.cybereps.com";
target = "/SITE=FGN/AREA=EQLORE/AAMSZ=BUTTON1";

document.write('<IFRAME SRC="' + site + '/hserver/acc_random=' + random + target + '"');
document.write(' NORESIZE SCROLLING=NO HSPACE=0 VSPACE=0 FRAMEBORDER=0 MARGINHEIGHT=0 MARGINWIDTH=0 WIDTH=120 HEIGHT=90>');

document.write('<SCR');
document.write('IPT SRC="' + site + '/jnserver/acc_random=' + random + target + '">');
document.write('</SCR');
document.write('IPT>');

document.write('</IFRAME>');
// End Hide -->
</SCRIPT>
<NOSCRIPT> <A HREF="http://ds.cybereps.com/accipiter/adclick/SITE=FGN/AREA=EQLORE/AAMSZ=BUTTON1">
<IMG SRC="http://ds.cybereps.com/accipiter/nserver/SITE=FGN/AREA=EQLORE/AAMSZ=BUTTON1" border="0"></A>
</NOSCRIPT>
<BR>
<BR>
</DIV>
</BODY>
</HTML>
