<!--
                 This page has been created by Renaissance IT
   Renaissance Internet Technologies Copyright (c) 1999 All Rights Reserved.

             for more info on our products, please visit :
                        http://www.renaissance.nl/

	This script has been written by Roy Boverhof <rboverhof@renaissance.nl>
	
        Pagename                : roleplaying.html
        Last Updated    		: 13-6-1999
-->

<HTML>
<HEAD>
	<TITLE>the Seekers of Lore : Roleplaying</TITLE>
</HEAD>

<BODY BGCOLOR="#000000" TEXT="#FFFFFF" LINK="#FFFFFF">
<DIV ALIGN="CENTER">
<BR>
<!-- FGB Banner Code -->
<SCRIPT LANGUAGE="JavaScript">
<!-- Hide from old browsers
now = new Date();
random = now.getTime();

// Modify to reflect site specifics
site = "http://ds.cybereps.com";
target = "/SITE=FGN/AREA=EQLORE/AAMSZ=BANNER";

document.write('<IFRAME SRC="' + site + '/hserver/acc_random=' + random + target + '"');
document.write(' NORESIZE SCROLLING=NO HSPACE=0 VSPACE=0 FRAMEBORDER=0 MARGINHEIGHT=0 MARGINWIDTH=0 WIDTH=468 HEIGHT=60>');

document.write('<SCR');
document.write('IPT SRC="' + site + '/jnserver/acc_random=' + random + target + '">');
document.write('</SCR');
document.write('IPT>');

document.write('</IFRAME>');
// End Hide -->
</SCRIPT>

<NOSCRIPT><A HREF="http://ds.cybereps.com/accipiter/adclick/SITE=FGN/AREA=EQLORE/AAMSZ=BANNER"><IMG SRC="http://ds.cybereps.com/accipiter/nserver/SITE=FGN/AREA=EQLORE/AAMSZ=BANNER" border="0"></A></NOSCRIPT>
<!-- END FGB Banner Code --><BR>	
<TABLE CELLSPACING = 0 CELLPADDING = 0 BORDER = 0>
<TR>
	<TD width="63"><IMG SRC = "graphics/topc000.jpg" WIDTH = 63 HEIGHT = 87></TD>
	<TD width="473"><IMG SRC = "graphics/topc001.jpg" WIDTH = 473 HEIGHT = 87></TD>
	<TD width="64"><IMG SRC = "graphics/topc002.jpg" WIDTH = 64 HEIGHT = 87></TD>
</TR>
	<TD width="63"></TD>
	<TD BGCOLOR="#BEA279" width="460">
	<DIV ALIGN="CENTER">
	<IMG SRC="graphics/roleplay.jpg" WIDTH=199 HEIGHT=43 BORDER=0 ALT="">
	<BR>
	<TABLE WIDTH="460">
	<TR>
		<TD>
		<FONT COLOR="#000000">
		
		<CENTER>
		<B><FONT SIZE=4><P>Playing a Role</P></B></FONT>
		<FONT SIZE=+1><P><B>By <A HREF="mailto:icewolf@tampabay.rr.com">Mardyrn</A> of Tarew Marr</B></P></FONT>
		</CENTER>
		<BR>
		<FONT SIZE="+1"><B>Overview</B></FONT>
		<BR>
		<P><FONT SIZE="+1">T</FONT>his document is a not-so brief treatise on exactly what role-playing is and how to do it. To play "in character" consistently requires both intelligence and imagination, not to mention a certain amount of humor and patience. Not everyone likes to role-play. Role-playing as a genre was born out of TSR's Dungeons and Dragons game in the 70's. As far as I know, D&D was the first of the games where one generated a character, and took on that character's role in life - hence, role-playing.
		
		<P><FONT SIZE="+1">T</FONT>hink of role-playing as acting. That is what it comes down to. And if you think of it in that way, it is a lot harder to be offended when that Dark-elf Cleric decides he's not going to help you just because you're a High Elf. One may argue that the player has more control over his character than does an actor in a movie. I say, "Pfui!". Think about the relative roles in Norrath of the Tier'dal and the Fier'dal. Consider their histories, as laid out by Verant. In the world of Everquest, Verant is the director and we are all actors on the stage of the Internet.</P>
		
		<P><FONT SIZE="+1">M</FONT>any of the notes and comments below are my personal opinion, and do not reflect the opinions of Verant, Sony, or even the Seekers of Lore as an organization.
		<BR><BR>
		<FONT SIZE="+1"><B>General Role-playing</B></FONT>
		<BR>
		<P><FONT SIZE="+1">H</FONT>ow do you role-play? In general, consider the type of character you have chosen. Male or female? Human, Elf, or something else? What class are you? Dig into the history of your race and class, which all good games should provide (Everquest gives you just enough to leave you wanting more). Draw from historical mythos and other fantasy classics. Read J. R.R. Tolkien's "Lord of the Rings" for a great look at racial interactions - specifically between Legolas and Gimli.
		
		<P><FONT SIZE="+1">O</FONT>utside the strictures of the game, it is perfectly possible to give your character a personality quirk or two that make him or her into a person rather than a cardboard cutout. Try being an astrophobe who turns and runs for the nearest inn whenever it starts to rain. Or develop a pathological hatred for orange, and refuse to have anything to do with anyone who wears bronze. Or (this mostly applies to bards) begin making up limericks about people you group with (or your guild, should you be so fortunate as to join one).
		
		<P><FONT SIZE="+1">D</FONT>eveloping a character can take time. If you're new to the idea, model your character on yourself. Can't stand spiders? Make your character an arachnophobe. As you play your character, you'll begin to develop a personality. When you gain experience in role-playing, you can decide what you want your character to be like while you're setting him up. "I'm going to set up a half-elf bard, based in Qeynos, who is determined to learn every language in the game." Or, "I am going to set up a dark-elf cleric who is a renegade among his own kind and prefers to deal with the good races." This latter isn't one I've personally tried, but it sounds rather difficult within the framework of EQ.
		<BR><BR>
		<FONT SIZE="+1"><B>A few Everquest specifics</B></FONT>
		<BR>
		<P><FONT SIZE="+1">R</FONT>ole-playing in EQ, at its simplest, is avoiding references to real life except when absolutely necessary - and should probably be limited to /oocs. The so-called "doodspeak" is anathema to role-players and should be avoided like plague at all times. Sprinkling your speech with "thee"s and "thou"s, is a nice touch if done properly and not carried to extremes. Ditto for the old English verb forms such as "dost" and "shalt". References to "zoning", "trains", "MOBs", and other game jargon should be restricted to /shouts and /tells. Use the /auction channel for buying and selling goods. Now admittedly, one has to strike a balance between role-playing and keeping the game playable. It's a lot easier to type "TRAIN TO ZONE!" than "A vast number of most foul gnolls are chasing me out of Blackburrow!" especially when running for one's life. I would also suggest turning on the /roleplay flag.
		
		<P><FONT SIZE="+1">O</FONT>n the subject of speech, swearing is a two-edged sword. It can be argued that it is "in character" for a warrior to spout four-letter words every other sentence. But swearing for the sake of swearing is offensive to many people, and doesn't really add anything to the game. Try emoting something like "Soandso calls Whosis every filthy name in the book." Or "Soandso spits out a stream of invective." I personally think that continual foul language is a sign of immaturity, and I tend to avoid characters who engage in that practice. 
		
		<P><FONT SIZE="+1">T</FONT>he races in EQ are apparently divided into two groups: good and evil (for lack of better descriptors). High Elves, Dwarves, Gnomes, Halflings, Wood Elves, Humans, Erudites, Barbarians, and Half-Elves are good, and Trolls, Ogres, and Dark Elves are evil. There is some inherent bias towards "good" races in this game; it is much easier for a good character to get around. Bearing in mind that "good" and "evil" don't mix well with each other, the following can be used as a rough guide to role-playing.

		<P><FONT SIZE="+1">R</FONT>ole-playing takes a liberal application of imagination. Anyone can go out and hack things up or toss spells. How do you make yourself stand out? Again, this is where developing a personality comes into play. Just won a big duel? Emote cutting an ear off your opponent, and stringing it on a cord. If you like to duel, collect an entire string of ears. When someone challenges you, make a comment about "one more for the string." Then explain. Play a warrior, and put some of your extra ability points into Intelligence - then become a polyglot on the side. Sure, you won't be as strong or tough as John Doe over there, but you'll be more three-dimensional.
		
		<P><FONT SIZE="+1">S</FONT>pend time learning trade skills and hawking your goods rather than simply leveling. Learn languages, and use them. Offer to teach languages if you're short on cash. Run mini-quests for newbie characters. Sponsor a foot-race from the West Gate of Freeport to the far side of East Commons, with a prize for whoever gets there first.
		
		<P><FONT SIZE="+1">T</FONT>reat others of your race with respect and dignity (and sometimes discounts on goods and services), and be a little standoffish with others until you get to know them. Now this does NOT apply if you are grouped with them. In that case, you should pitch in and do your best for the group. Otherwise you'll develop a reputation as a coward and whiner and no one will group with you.
		
		<P><FONT SIZE="+1">C</FONT>lerics, Shamen, Shadowknights and Paladins have a spiritual side to consider and flesh out. Charging into battle shouting , "Mithaniel, deliver us!" is kind of cool. Help out a newbie who's in trouble, and give them a lecture on the glories of your particular deity. This is a VERY overlooked facet to Everquest. Think about the nature of your god - Veeshan is a dragon, so when you attack an orc, say something like "Feel Veeshan's claws, foul beast!"  If you're in a group and someone gets killed, emote chanting a prayer for the dead over their corpse.
		
		<P><FONT SIZE="+1">I</FONT>n short, role-playing is doing lots of little things that may not get you levels, but add an entire new dimension to the game.
		<BR>
		<BR>
		<FONT SIZE="+1">M</FONT>ay Veeshan's wings cover you,
		<BR><BR>
		<B>Mardyrn of Tarew Marr</B><BR>
		</FONT>
		</TD>
	</TR>
	</TABLE>	
	</DIV>
	</TD>
	<TD width="64"></TD>
<TR>
	<TD><IMG SRC = "graphics/botc000.jpg" WIDTH = 63 HEIGHT = 87></TD>
	<TD><IMG SRC = "graphics/botc001.jpg" WIDTH = 473 HEIGHT = 87></TD>
	<TD><IMG SRC = "graphics/botc002.jpg" WIDTH = 64 HEIGHT = 87></TD>
</TR>
</TABLE>
<BR>
<SCRIPT LANGUAGE="JavaScript">
<!-- Hide from old browsers
now = new Date();
random = now.getTime();

// Modify to reflect site specifics
site = "http://ds.cybereps.com";
target = "/SITE=FGN/AREA=EQLORE/AAMSZ=BUTTON1";

document.write('<IFRAME SRC="' + site + '/hserver/acc_random=' + random + target + '"');
document.write(' NORESIZE SCROLLING=NO HSPACE=0 VSPACE=0 FRAMEBORDER=0 MARGINHEIGHT=0 MARGINWIDTH=0 WIDTH=120 HEIGHT=90>');

document.write('<SCR');
document.write('IPT SRC="' + site + '/jnserver/acc_random=' + random + target + '">');
document.write('</SCR');
document.write('IPT>');

document.write('</IFRAME>');
// End Hide -->
</SCRIPT>
<NOSCRIPT> <A HREF="http://ds.cybereps.com/accipiter/adclick/SITE=FGN/AREA=EQLORE/AAMSZ=BUTTON1">
<IMG SRC="http://ds.cybereps.com/accipiter/nserver/SITE=FGN/AREA=EQLORE/AAMSZ=BUTTON1" border="0"></A>
</NOSCRIPT>
<BR>
<BR>
</DIV>
</BODY>
</HTML>
