<!--
                 This page has been created by Renaissance IT
   Renaissance Internet Technologies Copyright (c) 1999 All Rights Reserved.

             for more info on our products, please visit :
                        http://www.renaissance.nl/

	This script has been written by Roy Boverhof <rboverhof@renaissance.nl>
	
        Pagename                : caves.html
        Last Updated    		: 17-03-2000
-->

<HTML>
<HEAD>
	<TITLE>the Seekers of Lore : Caves of Peril!</TITLE>
</HEAD>

<BODY BGCOLOR="#000000" TEXT="#000000" LINK="#000000" VLINK="#000000" ALINK="#000000">
<DIV ALIGN="CENTER">
<BR>
<!-- FGN Banner Code -->
<script language="JavaScript">
	<!-- Hide from old browsers
	var random = new Number(Math.floor(9999999 * Math.random())+1);

	// Modify to reflect site specifics
	page = "eqlore.com/";
	target = "@Top1,x02,x05,x08!Top1";

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript1.1" SRC="http://oascentral.cybereps.com/RealMedia/ads/adstream_jx.ads/' + page + 1 + random + target + '">');
	document.write('</SCR');
	document.write('IPT>');

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript">');
	document.write('_version=10; //-->');
	document.write('</SCR');
	document.write('IPT>');

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript1.1">');
	document.write('_version=11; //-->');
	document.write('</SCR');
	document.write('IPT>');

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript">');

	if (navigator.appVersion.indexOf('MSIE 3') != -1){
	document.write('<IFRAME MARGINWIDTH=0 MARGINHEIGHT=0 HSPACE=0 VSPACE=0 FRAMEBORDER=0 SCROLLING=no BORDERCOLOR="#000000" SRC="oascentral.cybereps.com/RealMedia/ads/adstream_sx.ads/' + page + random + target + '"></IFRAME>');
	  }
	else if (_version < 11) {
	document.write ('<A HREF="http://oascentral.cybereps.com/RealMedia/ads/click_nx.ads/' + page + random + target + '"><IMG SRC="http://oascentral.cybereps.com/RealMedia/ads/adstream_nx.ads/' + page + random + target + '"></a>');
	  }

	document.write('</SCR');
	document.write('IPT>');

	// End Hide -->
</script>
<!-- END FGN Banner Code --><BR>
<TABLE CELLSPACING = 0 CELLPADDING = 0 BORDER = 0>
<TR>
	<TD width="63"><IMG SRC = "../graphics/topc000.jpg" WIDTH = 63 HEIGHT = 87></TD>
	<TD width="473"><IMG SRC = "../graphics/topc001.jpg" WIDTH = 473 HEIGHT = 87></TD>
	<TD width="64"><IMG SRC = "../graphics/topc002.jpg" WIDTH = 64 HEIGHT = 87></TD>
</TR>
	<TD width="63"></TD>
	<TD BGCOLOR="#BEA279" width="460">
	<DIV ALIGN="CENTER">
	<TABLE>
	<TR>

	<TD BGCOLOR="#BEA279" width="400">

	<FONT FACE="Times New Roman" SIZE="+2">
	<P><BR><CENTER><B><I>Caves of Peril!</I></B></CENTER></FONT>

	<FONT SIZE="-1">

<P><FONT SIZE="+1"><B>F</B></FONT>ar to the east on the continent of Faydwer, lies a range known as the Steamfont Mountains.  It is called this due to the vast amount of steam geysers that exist in and amongst the crags and valleys.  Here also lies the great city of Ak'anon, home to the tinkering gnomes.  They have used their knowledge to harness the power of steam and wind to provide arguably the most advanced city in Norrath.  The mountains can be some of the most beautiful and amazing sites to traverse, but as in all places, there are also dangers.  Kobolds roam the foothills, plague rats are common siting, but both of these threats are negligible.  The true terror lies in the northeastern valley, past the great windmills.  Here roam earth elementals and ebon drakes, rogue clockworks and foul harpies.

<P><FONT SIZE="+1"><B>I</B></FONT>t was this valley that two Seekers, Chyrsan and Rathbane, had come to look over now.  The two rangers had come here as an advanced scouting party, but not to wage battles on the many beasts that made the valley home.  It was the caves at the northern end that drew their attention.  The infamous Minotaur slavers dwelled there, and more importantly, the nefarious Meldrath the Malignant called the caves his home.  Seekers had fallen here just a few months ago, attacked and slain by the evil necromancer and his Minotaur minions.

<P><FONT SIZE="+1"><B><I>"R</I></B></FONT><I>ath, take the point,"</I> Chyrsan said.  <I>"I must send the others the summons."</I>  She reached inside her ivy-colored tunic, and pulled forth a small medallion with the symbol of Tunare.  Clasping the symbol between her hands, she began a prayer.  Rathbane drew forth her bow, and notched an arrow.  The Minos were rarely seen this far south, but she would take no chances.

<P><FONT SIZE="+1"><B>S</B></FONT>uddenly the air seemed charged with electricity, and a silvery blue slash appeared off to one side.  Quickly, the two stepped back, weapons drawn just in case someone other than a Seeker opened this magical portal.  The portal expanded to become wide enough to allow an Ogre through with ease, and from it strode Sir Xereos, mighty paladin of Brell, wielder of the famed sword Ghoulbane and leader of the Seekers.  To his left was Felenya, a druid of incredible power, and Xereos' wife.  To his right came the blue robed wizard Shahk and his wife, fair Lady Khathryne, a high priestess of Tunare.  Most would wonder at the power that these four individuals could wield by themselves, but this was no ordinary foe they came to fight, as a general call had been answered by all but a few Seekers.  Those who did not come had stayed behind to guard the respective holdings of the Seekers from other dangers.

<P><FONT SIZE="+1"><B>N</B></FONT>ext came the rest of the Seekers.  High Cleric Grundrikt, Sir Kakanar the paladin, and Sir Bombpur, a warrior of great might.  Accompanying them was the High Elf Vrondi, an enchanter and Half-elven bard Kervan, Jessy, a towering shaman beauty capable of crushing many men's hearts, figuratively and literally, and the rogue Mordier, a man of the shadows.  The two dark elves bringing up the rear were capable of putting fear in the hearts of entire cities.  Many still shivered every time these two showed up.  The black robed, scythe wielding Soulree, and the shadow knight Nalfein, black runeblade in hand.  The very shadows seemed to move to cloak them.

<P><FONT SIZE="+1"><B>S</B></FONT>hahk let the portal disperse the moment everyone was through, and the plan that had been discussed was set into action.  The rangers had already found a clear path along the mountains edge to the opening to the mines.  Cloaked in magical invisibility, they made the hour-long journey easily, arriving at the caves mid-morning.  <I>"Ready Mordier?"</I> Xereos asked. <I>"When aren't I,"</I> the rogue quipped.  Donning his magical mask to give him ultravision, he vanished into the shadows to scout them out.

<P><FONT SIZE="+1"><B>H</B></FONT>ugging the walls to add the extra bit of stealth, he easily slipped past the slavers just inside the entrance.  Man those cows smell, he thought to himself.  He walked forward a ways, until he came to a three way split. Hmm, which one to take…well the right one seemed the one with the most light, so he headed down that one first.  Slave cages were all he found, full of sullen, beaten slaves.  Mordier made a note to himself to come back and free these souls once their captors were vanquished.  After some further scouting, he was able to determine that the minotaurs made the left tunnel their home, which meant Meldrath would be down there as well.

<P><FONT SIZE="+1"><B>H</B></FONT>e started out the tunnel to head back outside, when he felt a blast of hot breath across his neck.  Instinct saved Mordier, as he dove and rolled to the left, barely avoiding a killing blow.  He turned to see a creature rivaled only in size by the sand giants in far off Ro.  This must be the dreaded Minotaur Hero, one so massive that he crushed warrior with his bare hands.  Throwing one of his daggers at the beast, more as a distraction than anything else, the nimble rogue abandoned stealth for out right speed, and ran for the cave mouth.

<P><FONT SIZE="+1"><B><I>"C</I></B></FONT><I>oming out!"</I> he yelled as he shot past the slavers and into the clearing.  He ran straight out to bring the unsuspecting beasts into the trap that had been prepared for just this possibility.  The slavers came first, but they made it no more than three step outside before Chyrsan and Rathbane's deadly rain of arrows had felled them.  Hero came storming out, with more slavers in tow.  The battle had begun.

<P><FONT SIZE="+1"><B>K</B></FONT>akanar and Bombpur fell in behind the beast, with the intent to hamstring the foul creature.  Xereos charged in from the left and Nalfein moved in from the right.  Rathbane continued the barrage of arrows, while Chyrsan left her bow fall to the ground and drew her dual swords and began the dance of blades.

<P><FONT SIZE="+1"><B>B</B></FONT>low after blow landed on the creature, yet they seemed only to glance off it, never landing true.  The battle was not going well.  Several Seekers were down, and those left were beginning to tire.  It was the mighty Shahk who would fell this beast.  Chanting his spells, he dispelled the enchantments that aided this beast, and then blasted him with several white-hot bolts of lightning.  The beast staggered, stunned by the sudden onslaught. <I>"Hah!"</I> Bombpur shouted, <I>"We have him now!"</I> Painbringer swung true, cutting the beast behind the left knee, limiting its movement capabilities. That was the break Chyrsan needed, and she deftly avoided a poorly aimed axe to deliver two fatal wounds.

<P><FONT SIZE="+1"><B><I>"M</I></B></FONT><I>eldrath save me!"</I> the beast howled as it collapsed to the ground.  The battle had been won, but not without a cost.  Nalfein stood clutching his side, blood seeping through his fingers, and Kervan lay up against a tree, where he had landed after a vicious backslap had knocked him off his feet.  Alas the worst off was Grundrikt.  The battle hardened dwarf had taken a blow from the butt of the axe on his helmet.  He lay motionless on the ground.  <I>"Felenya, tend to the others,"</I> Khathryne shouted, as she dropped to Grundrikt's side.  Laying her hands upon his chest, she began to chant. 

<P><FONT SIZE="+1"><B><I>"T</I></B></FONT><I>unare, mother of all, aid me now in our time of need."</I>  Her hands began to glow, blue energy of life pulsing from her hands and into the dwarf.  <I>"I am not done with you overgrown bovine!"</I> Grundrikt suddenly shouted, looking as if the combat had never stopped.  <I>"Grund, this be no time for lying around on your bum"</I>, Kakanar joked, pulling his dear friend to his feet.  Everyone laughed, a moment of tension gone.  Kervan looked no worse for wear, using his ability to turn song into magic to heal himself.  Nalfein rubbed his newly healed side, still a bit tender, but he would live.  

<P><FONT SIZE="+1"><B>X</B></FONT>ereos surveyed the group, assessing their battle readiness.  A rest was needed, but could not be afforded.  Surely Meldrath and his minions were aware of the presence of intruders.  No time could be wasted.  Now came the time to forge in towards Meldrath's haven.  Without a word, he hefted Ghoulbane, picked up his shield and turned to the entrance, and the rest fell in behind.  Felenya had assumed the form of a wolf, to better scout out possible ambushes.  Soulree had reached into the netherworld and brought forth one of his dreaded skeletal knights to do his bidding, and Nalfein's hands glowed with an unholy aura as Dark Reaver gave forth a dull hum, as if in anticipation of what was to come.  The priests cast their own magical barriers, and Jessy used her powers of spirit to strengthen the group.  The battle to come had no sure outcome, and they were all aware.

<P><FONT SIZE="+1"><B>T</B></FONT>he group split into two.  Rathbane, Kervan and Vrondi, would take out the slavers down the right hall, free the slaves, and see them to safety, then come back to join the others.  The main force headed down the left tunnel.  Mordier in the lead, scouting out the tunnel for traps and such.  It almost seemed to easy, as they came to the lighted opening that marked the sanctum of their enemy.  Xereos turned to see if all were ready, and raised his hand in a silent signal to the rest to indicate that the rogue spied 2 massive minotaur guards, and behind them, their target, Meldrath the Malignant.

<P><FONT SIZE="+1"><B>W</B></FONT>ithout further delay, combat was initiated by Khathryne and Grundrikt casting spells of force to stun the guards, upon which Kakanar, Nalfein and Bombpur, attacked them, backed up by Grundrikt, and Jessy, and with Mordier dancing in out, stabbing with his daggers.  While stronger than the biggest ogre, they did not stand a chance against the skills of these six heroes. Meldrath stood behind, sending forth waves of fear to impair the onslaught, but to no avail, Xereos, Chyrsan and Soulree's skeletal companion charged past the guards to engage the vile little man, while Shahk, and Soulree assailed Meldrath with all the arcane power they could muster.

<P><FONT SIZE="+1"><B>W</B></FONT>hat transpired next will go down in one of the most awesome display of force ever but for by such a small band.  The very halls of Ak'anon shook with the force of the battle, and it seemed that the very mountain above the mines might explode under the strain.  The gods themselves are said to have taken notice.

<P><FONT SIZE="+1"><B>I</B></FONT>n the end, a proud and weary group of heroes stood at the cave mouth, the Skull of Meldrath in hand to be added to the hall of trophies.  Once again, the world of Norrath would sing the praises of...

<P><CENTER><FONT SIZE="+2"><B><I>The Seekers of Lore!</I></B></FONT></CENTER>

	<P><FONT SIZE="+1"><I>Nalfein T'sarran, House Auvryndar</I></FONT><BR><FONT SIZE="2" FACE="ariel">Bertoxxulous Server</FONT><BR><BR>

	</FONT>

	</TD>
	</TR>
	</TABLE>
<TABLE>
<TR>
<TD><A HREF="http://www.loreseekers.com/tales.phtml"><IMG SRC="http://www.loreseekers.com/graphics/tales_return_link.jpg" WIDTH=200 HEIGHT=75 ALT="Read some other stories by our members!" BORDER="0"></A></TD>
</TR>
</TABLE>

	<TD width="64"></TD>
<TR>
	<TD><IMG SRC = "../graphics/botc000.jpg" WIDTH = 63 HEIGHT = 87></TD>
	<TD><IMG SRC = "../graphics/botc001.jpg" WIDTH = 473 HEIGHT = 87></TD>
	<TD><IMG SRC = "../graphics/botc002.jpg" WIDTH = 64 HEIGHT = 87></TD>
</TR>
</TABLE>
<BR>

<script language="JavaScript">
	<!-- Hide from old browsers
	var random = new Number(Math.floor(9999999 * Math.random())+1);

	// Modify to reflect site specifics
	page = "eqlore.com/";
	target = "@Top1,x02,x05,x08!x02";

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript1.1" SRC="http://oascentral.cybereps.com/RealMedia/ads/adstream_jx.ads/' + page + 1 + random + target + '">');
	document.write('</SCR');
	document.write('IPT>');

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript">');
	document.write('_version=10; //-->');
	document.write('</SCR');
	document.write('IPT>');

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript1.1">');
	document.write('_version=11; //-->');
	document.write('</SCR');
	document.write('IPT>');

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript">');

	if (navigator.appVersion.indexOf('MSIE 3') != -1){
	document.write('<IFRAME MARGINWIDTH=0 MARGINHEIGHT=0 HSPACE=0 VSPACE=0 FRAMEBORDER=0 SCROLLING=no BORDERCOLOR="#000000" SRC="oascentral.cybereps.com/RealMedia/ads/adstream_sx.ads/' + page + random + target + '"></IFRAME>');
	  }
	else if (_version < 11) {
	document.write ('<A HREF="http://oascentral.cybereps.com/RealMedia/ads/click_nx.ads/' + page + random + target + '"><IMG SRC="http://oascentral.cybereps.com/RealMedia/ads/adstream_nx.ads/' + page + random + target + '"></a>');
	  }

	document.write('</SCR');
	document.write('IPT>');

	// End Hide -->
</script><BR>
<BR>
</DIV>
</BODY>
</HTML>