<!--
                 This page has been created by Renaissance IT
   Renaissance Internet Technologies Copyright (c) 1999 All Rights Reserved.

             for more info on our products, please visit :
                        http://www.renaissance.nl/

	This script has been written by Roy Boverhof <rboverhof@renaissance.nl>
	
        Pagename                : rok_shots_new.html
        Last Updated    		: 04-05-2000
-->

<HTML>
<HEAD>
	<TITLE>the Seekers of Lore : RoK™ New Screenshots</TITLE>
</HEAD>

<BODY BGCOLOR="#000000" TEXT="#000000" LINK="#000000" VLINK="#000000" ALINK="#000000">
<DIV ALIGN="CENTER">
<BR>
<!-- FGB Banner Code -->
<SCRIPT LANGUAGE="JavaScript">
   <!-- Hide from old browsers
   now = new Date();
   random = now.getTime();
     
   // Modify to reflect site specifics
   site = "http://ds.cybereps.com";
   target = "/SITE=FGN/AREA=EQLORE/AAMSZ=BANNER";
   
   document.write('<IFRAME SRC="' + site + '/hserver/acc_random=' + random + target + '"');
   document.write(' NORESIZE SCROLLING=NO HSPACE=0 VSPACE=0 FRAMEBORDER=0 MARGINHEIGHT=0 MARGINWIDTH=0 WIDTH=468 HEIGHT=60>');
   
   document.write('<SCR');
   document.write('IPT SRC="' + site + '/jnserver/acc_random=' + random + target + '">');
   document.write('</SCR');
   document.write('IPT>');
   
   document.write('</IFRAME>');
   // End Hide -->
 </SCRIPT>
 <NOSCRIPT> 
   <A HREF="http://ds.cybereps.com/accipiter/adclick/SITE=FGN/AREA=EQLORE/AAMSZ=BANNER">
   <IMG SRC="http://ds.cybereps.com/accipiter/nserver/SITE=FGN/AREA=EQLORE/AAMSZ=BANNER" border="0"></A>
 </NOSCRIPT>
<!-- END FGB Banner Code --><BR>	
<TABLE CELLSPACING = 0 CELLPADDING = 0 BORDER = 0>
<TR>
	<TD width="63"><IMG SRC = "graphics/topc000.jpg" WIDTH = 63 HEIGHT = 87></TD>
	<TD width="473"><IMG SRC = "graphics/topc001.jpg" WIDTH = 473 HEIGHT = 87></TD>
	<TD width="64"><IMG SRC = "graphics/topc002.jpg" WIDTH = 64 HEIGHT = 87></TD>
</TR>
	<TD width="63"></TD>
	<TD BGCOLOR="#BEA279" width="460">
	<DIV ALIGN="CENTER">
		<A HREF="http://www.loreseekers.com/screenshots.phtml"><IMG SRC="graphics/screencap_header.gif" WIDTH ="200" HEIGHT ="75" BORDER="0"></A>
	<TABLE WIDTH="460">
	<TR><TD>
	<CENTER>
<TABLE BORDER="0">
<TR>
<TD><BR><FONT SIZE="4" FACE="Ariel"><CENTER>Newest <A HREF="http://everquest.station.sony.com/kunark/index.html" TARGET="_new">Ruins of Kunark™</A> screenshots</CENTER></FONT><BR></TD>
</TR>
</TABLE>
<TABLE BORDER="0">
<TR> 
	<TD><A HREF="http://www.loreseekers.com/screenshots/newexclusive1.jpg" TARGET="_new"><IMG SRC="http://www.loreseekers.com/screenshots/tn_newexclusive1.jpg" WIDTH ="200" HEIGHT ="150" ALT="Click to view image full size"></A></TD>
	<TD><A HREF="http://www.loreseekers.com/screenshots/newexclusive2.jpg" TARGET="_new"><IMG SRC="http://www.loreseekers.com/screenshots/tn_newexclusive2.jpg" WIDTH ="200" HEIGHT ="150" ALT="Click to view image full size"></A></TD>
</TR>
<TR> 
	<TD><A HREF="http://www.loreseekers.com/screenshots/newexclusive3.jpg" TARGET="_new"><IMG SRC="http://www.loreseekers.com/screenshots/tn_newexclusive3.jpg" WIDTH ="200" HEIGHT ="150" ALT="Click to view image full size"></A></TD>
	<TD><A HREF="http://www.loreseekers.com/screenshots/newexclusive4.jpg" TARGET="_new"><IMG SRC="http://www.loreseekers.com/screenshots/tn_newexclusive4.jpg" WIDTH ="200" HEIGHT ="150" ALT="Click to view image full size"></A></TD>
</TR>
<TR> 
	<TD><A HREF="http://www.loreseekers.com/screenshots/eq000026.jpg" TARGET="_new"><IMG SRC="http://www.loreseekers.com/screenshots/tn_eq000026.jpg" WIDTH ="200" HEIGHT ="150" ALT="Click to view image full size"></A></TD>
	<TD><A HREF="http://www.loreseekers.com/screenshots/eq000029.jpg" TARGET="_new"><IMG SRC="http://www.loreseekers.com/screenshots/tn_eq000029.jpg" WIDTH ="200" HEIGHT ="150" ALT="Click to view image full size"></A></TD>
</TR>
<TR>
	<TD><FONT SIZE="2" FACE="ARIEL"><CENTER>1024 X 768</CENTER></FONT></TD>
	<TD><FONT SIZE="2" FACE="ARIEL"><CENTER>1024 X 768</CENTER></FONT></TD>
</TR>
<TR> 
	<TD><A HREF="http://www.loreseekers.com/screenshots/eq000032.jpg" TARGET="_new"><IMG SRC="http://www.loreseekers.com/screenshots/tn_eq000032.jpg" WIDTH ="200" HEIGHT ="150" ALT="Click to view image full size"></A></TD>
	<TD><A HREF="http://www.loreseekers.com/screenshots/eq000036.jpg" TARGET="_new"><IMG SRC="http://www.loreseekers.com/screenshots/tn_eq000036.jpg" WIDTH ="200" HEIGHT ="150" ALT="Click to view image full size"></A></TD>
</TR>
<TR>
	<TD><FONT SIZE="2" FACE="ARIEL"><CENTER>1024 X 768</CENTER></FONT></TD>
	<TD><FONT SIZE="2" FACE="ARIEL"><CENTER>1024 X 768</CENTER></FONT></TD>
</TR>
<TR> 
	<TD><A HREF="http://www.loreseekers.com/screenshots/eq000037.jpg" TARGET="_new"><IMG SRC="http://www.loreseekers.com/screenshots/tn_eq000037.jpg" WIDTH ="200" HEIGHT ="150" ALT="Click to view image full size"></A></TD>
	<TD><A HREF="http://www.loreseekers.com/screenshots/eq000043.jpg" TARGET="_new"><IMG SRC="http://www.loreseekers.com/screenshots/tn_eq000043.jpg" WIDTH ="200" HEIGHT ="150" ALT="Click to view image full size"></A></TD>
</TR>
<TR>
	<TD><FONT SIZE="2" FACE="ARIEL"><CENTER>1024 X 768</CENTER></FONT></TD>
	<TD><FONT SIZE="2" FACE="ARIEL"><CENTER>1024 X 768</CENTER></FONT></TD>
</TR>
<TR> 
	<TD><A HREF="http://www.loreseekers.com/screenshots/eq000047.jpg" TARGET="_new"><IMG SRC="http://www.loreseekers.com/screenshots/tn_eq000047.jpg" WIDTH ="200" HEIGHT ="150" ALT="Click to view image full size"></A></TD>
	<TD><A HREF="http://www.loreseekers.com/screenshots/eq000063.jpg" TARGET="_new"><IMG SRC="http://www.loreseekers.com/screenshots/tn_eq000063.jpg" WIDTH ="200" HEIGHT ="150" ALT="Click to view image full size"></A></TD>
</TR>
<TR>
	<TD><FONT SIZE="2" FACE="ARIEL"><CENTER>1024 X 768</CENTER></FONT></TD>
	<TD><FONT SIZE="2" FACE="ARIEL"><CENTER>1024 X 768</CENTER></FONT></TD>
</TR>
<TR> 
	<TD><A HREF="http://www.loreseekers.com/screenshots/eq000065.jpg" TARGET="_new"><IMG SRC="http://www.loreseekers.com/screenshots/tn_eq000065.jpg" WIDTH ="200" HEIGHT ="150" ALT="Click to view image full size"></A></TD>
	<TD><A HREF="http://www.loreseekers.com/screenshots/eq000069.jpg" TARGET="_new"><IMG SRC="http://www.loreseekers.com/screenshots/tn_eq000069.jpg" WIDTH ="200" HEIGHT ="150" ALT="Click to view image full size"></A></TD>
</TR>
<TR>
	<TD><FONT SIZE="2" FACE="ARIEL"><CENTER>1024 X 768</CENTER></FONT></TD>
	<TD><FONT SIZE="2" FACE="ARIEL"><CENTER>1024 X 768</CENTER></FONT></TD>
</TR>
</TABLE>

	</CENTER>
	<P>
	<BR>
	<BR>
	</P>
	</TD></TR>
	</TABLE>
	<TD width="64"></TD>
<TR>
	<TD><IMG SRC = "graphics/botc000.jpg" WIDTH = 63 HEIGHT = 87></TD>
	<TD><IMG SRC = "graphics/botc001.jpg" WIDTH = 473 HEIGHT = 87></TD>
	<TD><IMG SRC = "graphics/botc002.jpg" WIDTH = 64 HEIGHT = 87></TD>
</TR>
</TABLE>
<BR>
 <SCRIPT LANGUAGE="JavaScript">
   <!-- Hide from old browsers
   now = new Date();
   random = now.getTime();
   
   // Modify to reflect site specifics
   site = "http://ds.cybereps.com";
   target = "/SITE=FGN/AREA=EQLORE/AAMSZ=BOX";
   
   document.write('<IFRAME SRC="' + site + '/hserver/acc_random=' + random + target + '"');
   document.write(' NORESIZE SCROLLING=NO HSPACE=0 VSPACE=0 FRAMEBORDER=0 MARGINHEIGHT=0 MARGINWIDTH=0 WIDTH=125 HEIGHT=125>');
      
   document.write('<SCR');
   document.write('IPT SRC="' + site + '/jnserver/acc_random=' + random + target + '">');
   document.write('</SCR');
   document.write('IPT>');
   
   document.write('</IFRAME>');
   // End Hide -->
 </SCRIPT>
 <NOSCRIPT> 
   <A HREF="http://ds.cybereps.com/accipiter/adclick/SITE=FGN/AREA=EQLORE/AAMSZ=BOX">
   <IMG SRC="http://ds.cybereps.com/accipiter/nserver/SITE=FGN/AREA=EQLORE/AAMSZ=BOX" border="0"></A>
 </NOSCRIPT>
<BR>
<BR>
</DIV>
</BODY>
</HTML>


