<HTML>
<HEAD>
<TITLE>Welcome to Media and Games Online Network - MGON</TITLE>
<META name="description" content="MGON - The Gamer's Choice for gaming news. Get the hottest info from the gaming industry.
.">
<META name="keywords" content="MGON, MGO, Interviews, Game previews, Game downloads, Gaming Network, Articles, Gaming News, News, Multiplayer, Games, PC Games, Console Games, Reviews, Forum, MGON International AB, Action, Strategy, Simulation, Roleplay, Racing">
<META name="robots" content="index,follow">
<LINK rel="stylesheet" href="/pagestyle2.css">
<STYLE type="text/css">
<!--
-->
</STYLE>
<script language="JavaScript" type="text/javascript">
<!--
function go(where) {
  if(where != "void" && where!="") location.href = where;
}

function reply(tid,pid,cid,lang) {

  url = "/reply.phtml?tid=" + tid + "&pid=" + pid + "&id=" + cid + "&language=" + lang + '&ref=%2Fmgonews.phtml';
  ipwindow = open("","prewindow","scrollbars=yes,toolbar=no,height=330,width=400");
  ipwindow.location.href = url;
        
}

function rateit(id,vote) {
    if(vote != "") {
		document.rate.content_id.value = id;
		document.rate.vote.value = vote;
		document.rate.submit();
	}
}

function screenshot(cid,pid) {

  url = "/screenshot.phtml?cid=" + cid + "&pid=" + pid;
  ipwindow = open("","prewindow","scrollbars=yes,toolbar=no,height=630,width=710");
  ipwindow.location.href = url;
        
}

function relatedmedia(url) {

  ipwindow = open("","prewindow","scrollbars=yes,toolbar=no,height=300,width=300");
  ipwindow.location.href = url;
        
}
//-->
</script></HEAD>

<BODY bgcolor="#FFFFFF" text="#000000" link="#000000" vlink="#000000" alink="#000000" leftmargin="0" topmargin="0" marginwidth="0" marginheight="0" background="/images2/backgrounds/resize.gif">
<TABLE width="750" border="0" cellspacing="0" cellpadding="0"><TR><TD><!-- Webserver: w17 --><!-- loginUrl: http://everquest.mgon.com/common/loginNew.phtml?ref=www.mgon.com&page=/mgonews.phtml !--><!-- loginUrl: http://everquest.mgon.com/common/members.phtml?ref=www.mgon.com&page=/mgonews.phtml !--><script language="JavaScript">
<!--
function MM_openBrWindow(theURL,winName,features) { //v2.0
  window.open(theURL,winName,features);  
}
function login() {
  window.open('http://everquest.mgon.com/common/loginNew.phtml?ref=www.mgon.com&page=/mgonews.phtml', 'Login', 'width=250,height=250,scrollbars=yes'); 
}
function member() {
  window.open('http://everquest.mgon.com/common/members.phtml?ref=www.mgon.com&page=/mgonews.phtml', 'Member', 'width=500,height=600,scrollbars=yes'); 
}
//-->
</script>
<table width="100%" border="0" cellspacing="0" cellpadding="0" background="/common/images/topplate/resize.gif">
  <tr> 
    <td> 
      <table width="488" border="0" cellspacing="0" cellpadding="0" background="/common/images/topplate/resize.gif">
        <tr> 
          <td><img src="/common/images/topplate/metalcorner.gif" width="5" height="20"></td>
          <td><a href="javascript:login();"><img src="/common/images/topplate/memberlogin.gif" width="80" height="20" border="0"></a></td>
          <td><img src="/common/images/topplate/arrow.gif" width="10" height="20"></td>
          <td><img src="/common/images/topplate/metalcolumn.gif" width="3" height="20"></td>
          <td><a href="javascript:;" onClick="MM_openBrWindow('/common/sitemap.html','navigation','width=540,height=420')"><img src="/common/images/topplate/pc.gif" width="23" height="20" border="0"></a></td>
          <td><img src="/common/images/topplate/metalcolumn.gif" width="3" height="20"></td>
          <td><a href="javascript:;" onClick="MM_openBrWindow('/common/sitemap.html','navigation','width=540,height=420')"><img src="/common/images/topplate/action.gif" width="47" height="20" border="0"></a></td>
          <td><img src="/common/images/topplate/metalcolumn.gif" width="3" height="20"></td>
          <td><a href="javascript:;" onClick="MM_openBrWindow('/common/sitemap.html','navigation','width=540,height=420')"><img src="/common/images/topplate/roleplay.gif" width="62" height="20" border="0"></a></td>
          <td><img src="/common/images/topplate/metalcolumn.gif" width="3" height="20"></td>
          <td><a href="javascript:;" onClick="MM_openBrWindow('/common/sitemap.html','navigation','width=540,height=420')"><img src="/common/images/topplate/simulation.gif" width="70" height="20" border="0"></a></td>
          <td><img src="/common/images/topplate/metalcolumn.gif" width="3" height="20"></td>
          <td><a href="javascript:;" onClick="MM_openBrWindow('/common/sitemap.html','navigation','width=540,height=420')"><img src="/common/images/topplate/console.gif" width="56" height="20" border="0"></a></td>
          <td><img src="/common/images/topplate/metalcolumn.gif" width="3" height="20"></td>
          <td><a href="javascript:;" onClick="MM_openBrWindow('/common/sitemap.html','navigation','width=540,height=420')"><img src="/common/images/topplate/strategy.gif" width="64" height="20" border="0"></a></td>
          <td><img src="/common/images/topplate/metalcolumn.gif" width="3" height="20"></td>
          <td><a href="javascript:;" onClick="MM_openBrWindow('/common/sitemap.html','navigation','width=540,height=420')"><img src="/common/images/topplate/racing.gif" width="47" height="20" border="0"></a></td>
          <td><img src="/common/images/topplate/metalcolumn.gif" width="3" height="20"></td>
        </tr>
      </table>
    </td>
    <td background="/common/images/topplate/resize.gif" width="100%"><img src="/common/images/topplate/resize.gif" width="100%" height="20"></td>
    <td>
      <table width="88" border="0" cellspacing="0" cellpadding="0" background="/common/images/topplate/resize.gif">
        <tr>
          <td><img src="/common/images/topplate/metalcolumn.gif" width="3" height="20"></td>
          <td><a href="javascript:;" onClick="MM_openBrWindow('/common/sitemap.html','navigation','width=540,height=420')"><img src="/common/images/topplate/mgonetwork.gif" width="82" height="20" border="0"></a></td>
          <td><img src="/common/images/topplate/metalcorner.gif" width="5" height="20"></td>
        </tr>
      </table>
    </td>
  </tr>
</table>
<table width="100%" border="0" cellspacing="0" cellpadding="0" bgcolor="#000000">
  <tr> 
    <td><img src="/images/misc/1pix.gif" width="1" height="1"></td>
  </tr>
</table><script language="javascript">
var compname='Ad/mgon';
</script>
<script language="javascript" src="http://www.rankyou.com/cpt_transfers/single_month_enter.js">
</script></TD></TR></TABLE>

<TABLE width="750" border="0" cellspacing="0" cellpadding="0">

  <TR> 

    <TD><IMG src="/images2/top/topleft.gif" width="592" height="81" border="0" usemap="#Map"><MAP name="Map"><AREA shape="rect" coords="13,36,138,76" href="http://www.mgon.com" alt="MGON Home" title="MGON Home"></MAP></TD>

    <TD width="100%" background="/images2/top/resize.gif"><IMG src="/images2/top/resize.gif" width="1" height="81"></TD>

    <TD><IMG src="/images2/top/emgeo.gif" width="157" height="81"></TD>

  </TR>

</TABLE>


<TABLE width="750" border="0" cellspacing="0" cellpadding="0" bgcolor="#000000">
	<TR> 
		<TD align="center" width="130"> 
			<TABLE width="100%" border="0" cellspacing="0" cellpadding="0">
				<TR> 
					<TD align="center" background="/images2/top/channelresize.gif"><OBJECT classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=4,0,2,0" width="120" height="60">
							<PARAM name=movie value="http://www.mgon.com/flashmovies/mgochannel2.swf">
							<PARAM name=quality value=high>
							<PARAM name="menu" value="false">
							<EMBED src="http://www.mgon.com/flashmovies/mgochannel2.swf" quality=high pluginspage="http://www.macromedia.com/shockwave/download/index.cgi?P1_Prod_Version=ShockwaveFlash" 
type="application/x-shockwave-flash" menu="false" width="120" height="60">
							</EMBED> 
						</OBJECT></TD>
				</TR>
				<TR> 
					<TD><IMG src="/images/top/channelbottom.gif" width="130" height="13"></TD>
				</TR>
			</TABLE>
		</TD>
		
    <TD align="center" width="490" valign="top"> 
      <span class="smalltext"><NOLAYER><IFRAME SRC="http://ad.se.doubleclick.net/adi/mgon.com/;sz=468x60;ord=984139370?" bgcolor="#000000" width="468" height="60" frameborder="no" border="0" MARGINWIDTH="0" MARGINHEIGHT="0" SCROLLING="no"><A HREF="http://ad.se.doubleclick.net/jump/mgon.com/;abr=!ie;sz=468x60;ord=984139370?"><IMG SRC="http://ad.se.doubleclick.net/ad/mgon.com/;abr=!ie;sz=468x60;ord=984139370?" border="0" height="60" width="468"></A></IFRAME></NOLAYER><ILAYER id="layer1" visibility="hidden" width="468" height="60" align="center"></ILAYER></span>    </TD>
		
    <TD width="130" align="center" valign="top"><IMG
SRC="http://service.bfast.com/bfast/serve?bfmid=1375281&siteid=34593362&bfpa
ge=pc" BORDER="0" WIDTH="1" HEIGHT="1" NOSAVE > <A
HREF="http://service.bfast.com/bfast/click?bfmid=1375281&siteid=34593362&bfp
age=pc" TARGET="_top"><IMG
SRC="http://affiliate.gamestop.com/affimg/120_pc3_gs.gif" BORDER="0"
WIDTH="120" HEIGHT="60" ALT="PC titles from Gamestop.com"></A></TD>
	</TR>
</TABLE>
 
<TABLE width="750" border="0" cellspacing="0" cellpadding="0">
  <TR> 
    <TD valign="top" width="130"> 
<TABLE width="130" border="0" cellspacing="0" cellpadding="0">
  <TR> 
    <TD><IMG src="/images2/buttons/sitecontent.gif" width="130" height="25"></TD>
  </TR>
</TABLE>
<table width="130" border="0" cellspacing="0" cellpadding="0">
  <tr bgcolor="#000E24"> 
    <td> 
      <table width="100%" border=0 cellpadding=0 cellspacing=1>
        <tr bgcolor="#000E24"> 
          <td style="border='1 solid #809ECB'" onMouseOver="style.backgroundColor='#809ECB'; style.cursor='hand'; style.border='1 solid #809ECB'" onMouseOut="style.backgroundColor='#000E24'; style.border='1 solid #809ECB';" height="21"> 
            <table width="100%" border="0" cellspacing="0" cellpadding="2">
              <tr> 
                <td bgcolor="#000E24" height="21" width="100%"><a href="/" class="navlinks" style="margin:0;"> 
                  <div><img src="/images2/misc/1pix.gif" width="1" height="1" border="0">&nbsp;<span class="navlinks">Home</span></div>
                  </a></td>
                <td class="Bolded"><font size="2" face="Verdana, Arial, Helvetica, sans-serif" color="#000E24">&laquo;</font></td>
              </tr>
            </table>
          </td>
        </tr>
        <tr bgcolor="#000E24"> 
          <td style="border='1 solid #809ECB'" onMouseOver="style.backgroundColor='#809ECB'; style.cursor='hand'; style.border='1 solid #809ECB'" onMouseOut="style.backgroundColor='#000E24'; style.border='1 solid #809ECB';" height="21"> 
            <table width="100%" border="0" cellspacing="0" cellpadding="2">
              <tr> 
                <td bgcolor="#000E24" height="21" width="100%"><a href="/news.phtml" class="navlinks" style="margin:0;"> 
                  <div><img src="/images2/misc/1pix.gif" width="1" height="1" border="0">&nbsp;<span class="navlinks">News</span></div>
                  </a></td>
                <td class="Bolded"><font size="2" face="Verdana, Arial, Helvetica, sans-serif" color="#000E24">&laquo;</font></td>
              </tr>
            </table>
          </td>
        </tr>
        <tr bgcolor="#000E24"> 
          <td style="border='1 solid #809ECB'" onMouseOver="style.backgroundColor='#809ECB'; style.cursor='hand'; style.border='1 solid #809ECB'" onMouseOut="style.backgroundColor='#000E24'; style.border='1 solid #809ECB';" height="21"> 
            <table width="100%" border="0" cellspacing="0" cellpadding="2">
              <tr> 
                <td bgcolor="#000E24" height="21" width="100%"><a href="/mgonews.phtml" class="navlinks" style="margin:0;"> 
                  <div><img src="/images2/misc/1pix.gif" width="1" height="1" border="0">&nbsp;<span class="navlinks">MGONews</span></div>
                  </a></td>
                <td class="Bolded"><font size="2" face="Verdana, Arial, Helvetica, sans-serif" color="#000E24">&laquo;</font></td>
              </tr>
            </table>
          </td>
        </tr>
        <tr bgcolor="#000E24"> 
          <td style="border='1 solid #809ECB'" onMouseOver="style.backgroundColor='#809ECB'; style.cursor='hand'; style.border='1 solid #809ECB'" onMouseOut="style.backgroundColor='#000E24'; style.border='1 solid #809ECB';" height="21"> 
            <table width="100%" border="0" cellspacing="0" cellpadding="2">
              <tr> 
                <td bgcolor="#000E24" height="21" width="100%"><a href="/reviewindex.phtml" class="navlinks" style="margin:0;"> 
                  <div><img src="/images2/misc/1pix.gif" width="1" height="1" border="0">&nbsp;<span class="navlinks">Reviews</span></div>
                  </a></td>
                <td class="Bolded"><font size="2" face="Verdana, Arial, Helvetica, sans-serif" color="#000E24">&laquo;</font></td>
              </tr>
            </table>
          </td>
        </tr>
        <tr bgcolor="#000E24"> 
          <td style="border='1 solid #809ECB'" onMouseOver="style.backgroundColor='#809ECB'; style.cursor='hand'; style.border='1 solid #809ECB'" onMouseOut="style.backgroundColor='#000E24'; style.border='1 solid #809ECB';" height="21"> 
            <table width="100%" border="0" cellspacing="0" cellpadding="2">
              <tr> 
                <td bgcolor="#000E24" height="21" width="100%"><a href="/previewindex.phtml" class="navlinks" style="margin:0;"> 
                  <div><img src="/images2/misc/1pix.gif" width="1" height="1" border="0">&nbsp;<span class="navlinks">Previews</span></div>
                  </a></td>
                <td class="Bolded"><font size="2" face="Verdana, Arial, Helvetica, sans-serif" color="#000E24">&laquo;</font></td>
              </tr>
            </table>
          </td>
        </tr>
        <tr bgcolor="#000E24"> 
          <td style="border='1 solid #809ECB'" onMouseOver="style.backgroundColor='#809ECB'; style.cursor='hand'; style.border='1 solid #809ECB'" onMouseOut="style.backgroundColor='#000E24'; style.border='1 solid #809ECB';" height="21"> 
            <table width="100%" border="0" cellspacing="0" cellpadding="2">
              <tr> 
                <td bgcolor="#000E24" height="21" width="100%"><a href="/interviewindex.phtml" class="navlinks" style="margin:0;"> 
                  <div><img src="/images2/misc/1pix.gif" width="1" height="1" border="0">&nbsp;<span class="navlinks">Interviews</span></div>
                  </a></td>
                <td class="Bolded"><font size="2" face="Verdana, Arial, Helvetica, sans-serif" color="#000E24">&laquo;</font></td>
              </tr>
            </table>
          </td>
        </tr>
        <tr bgcolor="#000E24"> 
          <td style="border='1 solid #809ECB'" onMouseOver="style.backgroundColor='#809ECB'; style.cursor='hand'; style.border='1 solid #809ECB'" onMouseOut="style.backgroundColor='#000E24'; style.border='1 solid #809ECB';" height="21"> 
            <table width="100%" border="0" cellspacing="0" cellpadding="2">
              <tr> 
                <td bgcolor="#000E24" height="21" width="100%"><a href="/articleindex.phtml" class="navlinks" style="margin:0;"> 
                  <div><img src="/images2/misc/1pix.gif" width="1" height="1" border="0">&nbsp;<span class="navlinks">Articles</span></div>
                  </a></td>
                <td class="Bolded"><font size="2" face="Verdana, Arial, Helvetica, sans-serif" color="#000E24">&laquo;</font></td>
              </tr>
            </table>
          </td>
        </tr>
        <tr bgcolor="#000E24"> 
          <td style="border='1 solid #809ECB'" onMouseOver="style.backgroundColor='#809ECB'; style.cursor='hand'; style.border='1 solid #809ECB'" onMouseOut="style.backgroundColor='#000E24'; style.border='1 solid #809ECB';" height="21"> 
            <table width="100%" border="0" cellspacing="0" cellpadding="2">
              <tr> 
                <td bgcolor="#000E24" height="21" width="100%"><a href="http://www.mgoforum.com/" class="navlinks" style="margin:0;"> 
                  <div><img src="/images2/misc/1pix.gif" width="1" height="1" border="0">&nbsp;<span class="navlinks">MGON 
                    Forum</span></div>
                  </a></td>
                <td class="Bolded"><font size="2" face="Verdana, Arial, Helvetica, sans-serif" color="#000E24">&laquo;</font></td>
              </tr>
            </table>
          </td>
        </tr>
      </table>
    </td>
  </tr>
</table>
<TABLE width="130" border="0" cellspacing="0" cellpadding="0">
  <TR> 
    <TD><IMG src="/images2/buttons/siteinfo.gif" width="130" height="25"></TD>
  </TR>
</TABLE>
<table width="130" border="0" cellspacing="0" cellpadding="0">
  <tr bgcolor="#000E24"> 
    <td> 
      <table width="100%" border=0 cellpadding=0 cellspacing=1>
        <tr bgcolor="#000E24"> 
          <td style="border='1 solid #809ECB'" onMouseOver="style.backgroundColor='#809ECB'; style.cursor='hand'; style.border='1 solid #809ECB'" onMouseOut="style.backgroundColor='#000E24'; style.border='1 solid #809ECB';" height="21"> 
            <table width="100%" border="0" cellspacing="0" cellpadding="2">
              <tr> 
                <td bgcolor="#000E24" height="21" width="100%"><a href="/company/" class="navlinks" style="margin:0;"> 
                  <div><img src="/images2/misc/1pix.gif" width="1" height="1" border="0">&nbsp;<span class="navlinks">The 
                    Company</span></div>
                  </a></td>
                <td class="Bolded"><font size="2" face="Verdana, Arial, Helvetica, sans-serif" color="#000E24">&laquo;</font></td>
              </tr>
            </table>
          </td>
        </tr>
        <tr bgcolor="#000E24"> 
          <td style="border='1 solid #809ECB'" onMouseOver="style.backgroundColor='#809ECB'; style.cursor='hand'; style.border='1 solid #809ECB'" onMouseOut="style.backgroundColor='#000E24'; style.border='1 solid #809ECB';" height="21"> 
            <table width="100%" border="0" cellspacing="0" cellpadding="2">
              <tr> 
                <td bgcolor="#000E24" height="21" width="100%"><a href="/jobs/" class="navlinks" style="margin:0;"> 
                  <div><img src="/images2/misc/1pix.gif" width="1" height="1" border="0">&nbsp;<span class="navlinks">MGON 
                    Jobs</span></div>
                  </a></td>
                <td class="Bolded"><font size="2" face="Verdana, Arial, Helvetica, sans-serif" color="#000E24">&laquo;</font></td>
              </tr>
            </table>
          </td>
        </tr>
        <tr bgcolor="#000E24"> 
          <td style="border='1 solid #809ECB'" onMouseOver="style.backgroundColor='#809ECB'; style.cursor='hand'; style.border='1 solid #809ECB'" onMouseOut="style.backgroundColor='#000E24'; style.border='1 solid #809ECB';" height="21"> 
            <table width="100%" border="0" cellspacing="0" cellpadding="2">
              <tr> 
                <td bgcolor="#000E24" height="21" width="100%"><a href="/partnerships/" class="navlinks" style="margin:0;"> 
                  <div><img src="/images2/misc/1pix.gif" width="1" height="1" border="0">&nbsp;<span class="navlinks">Our 
                    Partners</span></div>
                  </a></td>
                <td class="Bolded"><font size="2" face="Verdana, Arial, Helvetica, sans-serif" color="#000E24">&laquo;</font></td>
              </tr>
            </table>
          </td>
        </tr>
        <tr bgcolor="#000E24"> 
          <td style="border='1 solid #809ECB'" onMouseOver="style.backgroundColor='#809ECB'; style.cursor='hand'; style.border='1 solid #809ECB'" onMouseOut="style.backgroundColor='#000E24'; style.border='1 solid #809ECB';" height="21"> 
            <table width="100%" border="0" cellspacing="0" cellpadding="2">
              <tr> 
                <td bgcolor="#000E24" height="21" width="100%"><a href="/mediakit/" class="navlinks" style="margin:0;"> 
                  <div><img src="/images2/misc/1pix.gif" width="1" height="1" border="0">&nbsp;<span class="navlinks">Our 
                    Mediakit</span></div>
                  </a></td>
                <td class="Bolded"><font size="2" face="Verdana, Arial, Helvetica, sans-serif" color="#000E24">&laquo;</font></td>
              </tr>
            </table>
          </td>
        </tr>
        <tr bgcolor="#000E24"> 
          <td style="border='1 solid #809ECB'" onMouseOver="style.backgroundColor='#809ECB'; style.cursor='hand'; style.border='1 solid #809ECB'" onMouseOut="style.backgroundColor='#000E24'; style.border='1 solid #809ECB';" height="21"> 
            <table width="100%" border="0" cellspacing="0" cellpadding="2">
              <tr> 
                <td bgcolor="#000E24" height="21" width="100%"><a href="/press.phtml" class="navlinks" style="margin:0;"> 
                  <div><img src="/images2/misc/1pix.gif" width="1" height="1" border="0">&nbsp;<span class="navlinks">Press 
                    Material</span></div>
                  </a></td>
                <td class="Bolded"><font size="2" face="Verdana, Arial, Helvetica, sans-serif" color="#000E24">&laquo;</font></td>
              </tr>
            </table>
          </td>
        </tr>
        <tr bgcolor="#000E24"> 
          <td style="border='1 solid #809ECB'" onMouseOver="style.backgroundColor='#809ECB'; style.cursor='hand'; style.border='1 solid #809ECB'" onMouseOut="style.backgroundColor='#000E24'; style.border='1 solid #809ECB';" height="21"> 
            <table width="100%" border="0" cellspacing="0" cellpadding="2">
              <tr> 
                <td bgcolor="#000E24" height="21" width="100%"><a href="/contactus/" class="navlinks" style="margin:0;"> 
                  <div><img src="/images2/misc/1pix.gif" width="1" height="1" border="0">&nbsp;<span class="navlinks">Contact 
                    Us</span></div>
                  </a></td>
                <td class="Bolded"><font size="2" face="Verdana, Arial, Helvetica, sans-serif" color="#000E24">&laquo;</font></td>
              </tr>
            </table>
          </td>
        </tr>
<tr bgcolor="#000E24"> 
          <td style="border='1 solid #809ECB'" onMouseOver="style.backgroundColor='#809ECB'; style.cursor='hand'; style.border='1 solid #809ECB'" onMouseOut="style.backgroundColor='#000E24'; style.border='1 solid #809ECB';" height="21"> 
            <table width="100%" border="0" cellspacing="0" cellpadding="0">
              <tr> 
                <td bgcolor="#000E24" height="21" width="100%" align="center"><a href="/contactus/" class="navlinks" style="margin:0;"> 
                  <div></div>
                  </a><a href="mailto:advertise@mgon.com"><img src="/ads/120x240.gif" width="120" height="240" border="0" alt="Ad Space"></a></td>
              </tr>
            </table>
          </table>
    </td>
  </tr>
</table>
</TD>
    <TD width="620" valign="top"> 
      <TABLE width="100%" border="0" cellspacing="0" cellpadding="0" background="/images2/sections/resize.gif">
        <TR> 
          <TD><IMG src="/images2/misc/1pixblack.gif" width="1" height="63"></TD>
          <TD width="100%" valign="bottom"> 
            <TABLE width="100%" border="0" cellspacing="0" cellpadding="0" background="/images2/misc/50x50pix.gif">
              <TR> 
                <TD height="28"><SPAN class="Bolded"><IMG src="/images2/misc/1pix.gif" width="11" height="1"></SPAN></TD>
              </TR>
            </TABLE>
          </TD>
          <TD align="right"><IMG src="/images2/sections/mgonews.gif" width="275" height="63"></TD>
        </TR>
      </TABLE>
      <table width="100%" border="0" cellspacing="0" cellpadding="0" background="/images2/buttons/resize.gif">
        <tr> 
          <td height="25"><img src="/images2/misc/1pixblack.gif" width="1" height="25"></td>
        </tr>
      </table>
      <TABLE width="100%" border="0" cellspacing="0" cellpadding="0">
        <TR> 
          <TD width="100%"> 
<TABLE width="100%" border="0" cellspacing="0" cellpadding="11">
        <TR>
          <TD width="100%"> 
            <P><SPAN class="Headline">Are you good with money?</SPAN><BR><SPAN class="Bolded">Reported by: </SPAN><A name="31357" href="mailto:sands@mgon.com">sands</A>&nbsp;&nbsp;&nbsp;<SPAN class="Bolded">Date:</SPAN> August, 30
			<P><SPAN class="normal"><IMG src="/icons/1.gif" width="65" height="65" hspace="10" align="left" vspace="5" border="0">We are looking for a Financial Manager! Have you got what it takes? Take a look in the MGON Jobs section for more information.<BR><!--No link--></SPAN>
            <P>
</TD></TR></TABLE>
            <TABLE width="100%" border="0" cellspacing="1" cellpadding="0">
              <TR> 
                <TD height="20" bgcolor="#001F39" width="100%">&nbsp;&nbsp;<A href="#top">Top of page</A> | <A href="mailto:news@mgon.com?Subject=News">Report news</A> | <A href="/mgonews.phtml">News Archive</A></TD>
                <TD align="right" bgcolor="#001F39" nowrap>&nbsp;&nbsp;<A href="/mgonews.phtml?id=31357&language=en#comments">&nbsp;0 Comments</A> | <A href="/mgonews.phtml?id=31357&language=en#addcomment">Add</A>&nbsp;&nbsp;</TD>
              </TR>
            </TABLE>
<TABLE width="100%" border="0" cellspacing="0" cellpadding="11">
        <TR>
          <TD width="100%"> 
            <P><SPAN class="Headline">Join my launch competition!</SPAN><BR><SPAN class="Bolded">Reported by: </SPAN><A name="28304" href="mailto:thomas@oddjob.se">Thomas I</A>&nbsp;&nbsp;&nbsp;<SPAN class="Bolded">Date:</SPAN> August, 25
			<P><SPAN class="normal"><IMG src="/icons/1.gif" width="65" height="65" hspace="10" align="left" vspace="5" border="0">Help! I was just moving in when I somehow lost a couple of my review scores. They are now scattered throughout the site! I need to know what the total sum is when you add the scores together. There are 5 scores on the loose somewhere on this site, find them, add them together and mail <A href="mailto:emgeo@mgon.com?subject=Competition1">emgeo@mgon.com</A> with the total score! During September I will announce the lucky winner and send out the prize described below!<BR><!--No link--></SPAN>
            <P>
</TD></TR></TABLE>
            <TABLE width="100%" border="0" cellspacing="1" cellpadding="0">
              <TR> 
                <TD height="20" bgcolor="#001F39" width="100%">&nbsp;&nbsp;<A href="#top">Top of page</A> | <A href="mailto:news@mgon.com?Subject=News">Report news</A> | <A href="/mgonews.phtml">News Archive</A></TD>
                <TD align="right" bgcolor="#001F39" nowrap>&nbsp;&nbsp;<A href="/mgonews.phtml?id=28304&language=en#comments">&nbsp;0 Comments</A> | <A href="/mgonews.phtml?id=28304&language=en#addcomment">Add</A>&nbsp;&nbsp;</TD>
              </TR>
            </TABLE>
<TABLE width="100%" border="0" cellspacing="0" cellpadding="11">
        <TR>
          <TD width="100%"> 
            <P><SPAN class="Headline">Hi I'm Emgeo, welcome home!</SPAN><BR><SPAN class="Bolded">Reported by: </SPAN><A name="28163" href="mailto:">CJNE</A>&nbsp;&nbsp;&nbsp;<SPAN class="Bolded">Date:</SPAN> August, 25
			<P><SPAN class="normal"><IMG src="/icons/1.gif" width="65" height="65" hspace="10" align="left" vspace="5" border="0">My name is Emgeo and I am your host at the newly launched www.mgon.com website. I speak several languages already and I learn new ones constantly. Now I invite you all to take the tour through this site and learn what we're doing here!<br>
<br>
Please keep in mind that we only just opened this site and there are plenty of new sections coming up as we progress with development. We have hosting programs, technical support, guides of all sorts and much more waiting to go in during the coming weeks. Once again <SPAN class="Bolded">Welcome!</SPAN><BR><!--No link--></SPAN>
            <P>
</TD></TR></TABLE>
            <TABLE width="100%" border="0" cellspacing="1" cellpadding="0">
              <TR> 
                <TD height="20" bgcolor="#001F39" width="100%">&nbsp;&nbsp;<A href="#top">Top of page</A> | <A href="mailto:news@mgon.com?Subject=News">Report news</A> | <A href="/mgonews.phtml">News Archive</A></TD>
                <TD align="right" bgcolor="#001F39" nowrap>&nbsp;&nbsp;<A href="/mgonews.phtml?id=28163&language=en#comments">&nbsp;0 Comments</A> | <A href="/mgonews.phtml?id=28163&language=en#addcomment">Add</A>&nbsp;&nbsp;</TD>
              </TR>
            </TABLE>

          <p>&nbsp;</p></TD>
        </TR>
      </TABLE>
    </TD>
  </TR>
</TABLE>
 
<TABLE width="750" border="0" cellspacing="0" cellpadding="0">
  <TR> 
    <TD><IMG src="/images2/bottom/copyright.gif" width="340" height="30" border="0"><A href="/privacy.phtml"><IMG src="/images2/bottom/privacy.gif" width="101" height="30" border="0"></A></TD>
    <TD><IMG src="/images2/bottom/bottomplate.gif" width="177" height="30"></TD>
    <TD><A href="#top"><IMG src="/images2/bottom/top.gif" width="68" height="30" border="0"></A></TD>
    <TD><A href="/index.phtml"><IMG src="/images2/bottom/home.gif" width="64" height="30" border="0"></A></TD>
  </TR>
</TABLE>
<TABLE width="750" border="0" cellspacing="0" cellpadding="0" height="90" background="/images2/misc/50x50pix.gif">
  <TR bgcolor="#000000" align="center"> 
    <TD class="smalltext">
      <SCRIPT language="JavaScript"
src="http://adtegrity.spinbox.net/?DC=Mgon+Bottom&JS=Y&TARGET=_new">
</SCRIPT>
      <NOSCRIPT><A href="http://adtegrity.spinbox.net/?SHT=Mgon+Bottom" target="_new"
height="468" width="60"><IMG src="http://adtegrity.spinbox.net/?SIT=Mgon+Bottom" border="0"></A></NOSCRIPT></TD>
  </TR>
</TABLE>
<!--Bottom Layer-->
<LAYER SRC="http://ad.se.doubleclick.net/adl/mgon.com/;sz=468x60;ord=984139370?" bgcolor="#000000" width="468" height="60" visibility="hidden" onLoad="moveToAbsolute(layer1.pageX,layer1.pageY);clip.height=60;clip.width=468; visibility='show';"></LAYER><!--End Bottom Layer--></BODY>

</HTML>


