<!--
                 This page has been created by Renaissance IT
   Renaissance Internet Technologies Copyright (c) 1999 All Rights Reserved.

             for more info on our products, please visit :
                        http://www.renaissance.nl/

	This script has been written by Roy Boverhof <rboverhof@renaissance.nl>
	
        Pagename                : armor.html
        Last Updated    		: 27-7-1999
-->

<HTML>
<HEAD>
	<TITLE>Armor</TITLE>
</HEAD>

<body BGCOLOR="#000000" TEXT="#000000">
<DIV ALIGN="CENTER">
<BR>
<script type="text/javascript"><!--
google_ad_client = "pub-0988179937943699";
google_ad_width = 468;
google_ad_height = 60;
google_ad_format = "468x60_as";
google_ad_channel ="7352298734";
google_page_url = document.location;
google_color_border = "FFFFFF";
google_color_bg = "00001F";
google_color_link = "FFFFFF";
google_color_url = "FFF000";
google_color_text = "0000FF";
//--></script>
<script type="text/javascript"
  src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
</script><BR>
<TABLE CELLSPACING = 0 CELLPADDING = 0 BORDER = 0>
<TR>
	<TD width="63"><IMG SRC = "graphics/topc000.jpg" WIDTH = 63 HEIGHT = 87></TD>
	<TD width="473"><IMG SRC = "graphics/topc001.jpg" WIDTH = 473 HEIGHT = 87></TD>
	<TD width="64"><IMG SRC = "graphics/topc002.jpg" WIDTH = 64 HEIGHT = 87></TD>
</TR>
	<TD width="63"></TD>
	<TD BGCOLOR="#BEA279" width="460">
	<DIV ALIGN="CENTER">
	<IMG SRC="graphics/armorheader.jpg" WIDTH=200 HEIGHT=75 ALT="" BORDER="0">
	<TABLE WIDTH="460">
	<TR>
		<TD>
		<DIV ALIGN="CENTER">
		<FONT COLOR="#000000">
		<BR>
		<BR>
		Just fill in the name of an Item to search our database.

		<TABLE border="0" cellpadding="3" cellspacing="3">
		<TR>
			<TD>Name : </TD>
			<TD><FORM ACTION="armor_search.php3" METHOD="POST"><INPUT TYPE="Hidden" NAME="action" VALUE="namesearch"><INPUT TYPE="text" NAME="name" SIZE="20"></TD>
			<TD>
			<TABLE><TR><TD height=14></TD></TR><TR><TD><INPUT TYPE="Submit" VALUE="Search"></FORM></TD></TR></TABLE>
			</TD>
		</TR>
		<TR>
			<TD>Select your class : </TD>
			<TD>
			<FORM ACTION="armor_search.php3" METHOD="POST"> 
			<INPUT TYPE="Hidden" NAME="action" VALUE="classsearch">
			<SELECT NAME="class">
			<OPTION SELECTED>Bard</OPTION>
			<OPTION>Cleric</OPTION>
			<OPTION>Druid</OPTION>
			<OPTION>Enchanter</OPTION>
			<OPTION>Magician</OPTION>
			<OPTION>Monk</OPTION>
			<OPTION>Necromancer</OPTION>
			<OPTION>Paladin</OPTION>
			<OPTION>Ranger</OPTION>
			<OPTION>Rogue</OPTION>
			<OPTION>Shadowknight</OPTION>
			<OPTION>Shaman</OPTION>
			<OPTION>Warrior</OPTION>
			<OPTION>Wizard</OPTION>
			</SELECT>
			</TD>
			<TD>
			<TABLE><TR><TD height=14></TD></TR><TR><TD><INPUT TYPE="submit" VALUE="Search"></FORM></TD></TR></TABLE>
			</TD>
		</TR>
		<TR>
			<TD>Type : </TD>
			<TD>
			<FORM ACTION="armor_search.php3" METHOD="POST"> 
			<INPUT TYPE="Hidden" NAME="action" VALUE="typesearch">
			<SELECT NAME="type">
			<OPTION VALUE="Arm">Arm</OPTION>
			<OPTION VALUE="Back">Back</OPTION>
			<OPTION VALUE="Chest">Chest</OPTION>
			<OPTION VALUE="Ear">Ear</OPTION>
			<OPTION VALUE="Face">Face</OPTION>
			<OPTION VALUE="Feet">Feet</OPTION>
			<OPTION VALUE="Finger">Finger</OPTION>
			<OPTION VALUE="Hand">Hand</OPTION>
			<OPTION VALUE="Head">Head</OPTION>
			<OPTION VALUE="Leg">Leg</OPTION>
			<OPTION VALUE="Neck">Neck</OPTION>
			<OPTION VALUE="Shield">Shield</OPTION>
			<OPTION VALUE="Shoulder">Shoulder</OPTION>
			<OPTION VALUE="Waist">Waist</OPTION>
			<OPTION VALUE="Wrist">Wrist</OPTION>
			</SELECT>
			</TD>
			<TD>
			<TABLE><TR><TD height=14></TD></TR><TR><TD><INPUT TYPE="submit" VALUE="Search"></FORM></TD></TR></TABLE>
			</TD>
		</TR>
		</TABLE>
		
		</FONT>
		</DIV>
		</TD>
	</TR>
	</TABLE>
	<TD width="64"></TD>
<TR>
	<TD><IMG SRC = "graphics/botc000.jpg" WIDTH = 63 HEIGHT = 87></TD>
	<TD><IMG SRC = "graphics/botc001.jpg" WIDTH = 473 HEIGHT = 87></TD>
	<TD><IMG SRC = "graphics/botc002.jpg" WIDTH = 64 HEIGHT = 87></TD>
</TR>
</TABLE>
<BR>
<IMG SRC="http://service.bfast.com/bfast/serve?bfmid=1375281&siteid=40292692&bfpage=pc" BORDER="0" WIDTH="1" HEIGHT="1" NOSAVE ><A HREF="http://service.bfast.com/bfast/click?bfmid=1375281&siteid=40292692&bfpage=pc" TARGET="_new"><IMG SRC="http://affiliate.gamestop.com/affIMG/pc_120x60.gif" BORDER="0" WIDTH="120" HEIGHT="60" ALT="PC Games at GameStop.com"></A>
<BR>
<BR>
</DIV>
</BODY>
</HTML>