#!/usr/local/bin/php


<h3>Select an administrative function...</h3><br><br>

<ul>
<li><a href="addCalendar.phtml">Add an item to the calendar</a></li>
<li><a href="update.phtml">Update an item on the calendar</a></li>
<li><a href="delete.phtml">Delete an item from the calendar</a></li>
<li><a href="expire.phtml">Expire a month</a></li>
<li><a href="../simple.phtml">View the simple calendar (database-less)</a></li>
</ul>

            <!--  End  Body  -->
<CENTER>
<br><hr width='70%'><br><font face='Arial'>
| <a href="../index.phtml">View Calendar</a> |
 <a href="./admin.phtml">Admin Page</a> |
<br>
</font>
</CENTER>
</BODY>
</HTML>
