<!--
                 This page has been created by Renaissance IT
   Renaissance Internet Technologies Copyright (c) 1999 All Rights Reserved.

             for more info on our products, please visit :
                        http://www.renaissance.nl/

	This script has been written by Roy Boverhof <rboverhof@renaissance.nl>
	
        Pagename                : files.html
        Last Updated    		: 08-12-2000
-->

<HTML>
<HEAD>
	<TITLE>the Seekers of Lore : File Library</TITLE>
</HEAD>

<BODY BGCOLOR="#000000" TEXT="#000000" LINK="#000000" VLINK="#000000" ALINK="#000000">
<DIV ALIGN="CENTER">
<BR>
<!-- FGN Banner Code -->
<script language="JavaScript">
	<!-- Hide from old browsers
	var random = new Number(Math.floor(9999999 * Math.random())+1);

	// Modify to reflect site specifics
	page = "eqlore.com/";
	target = "@Top1,x02,x05,x08!Top1";

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript1.1" SRC="http://oascentral.cybereps.com/RealMedia/ads/adstream_jx.ads/' + page + 1 + random + target + '">');
	document.write('</SCR');
	document.write('IPT>');

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript">');
	document.write('_version=10; //-->');
	document.write('</SCR');
	document.write('IPT>');

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript1.1">');
	document.write('_version=11; //-->');
	document.write('</SCR');
	document.write('IPT>');

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript">');

	if (navigator.appVersion.indexOf('MSIE 3') != -1){
	document.write('<IFRAME MARGINWIDTH=0 MARGINHEIGHT=0 HSPACE=0 VSPACE=0 FRAMEBORDER=0 SCROLLING=no BORDERCOLOR="#000000" SRC="oascentral.cybereps.com/RealMedia/ads/adstream_sx.ads/' + page + random + target + '"></IFRAME>');
	  }
	else if (_version < 11) {
	document.write ('<A HREF="http://oascentral.cybereps.com/RealMedia/ads/click_nx.ads/' + page + random + target + '"><IMG SRC="http://oascentral.cybereps.com/RealMedia/ads/adstream_nx.ads/' + page + random + target + '"></a>');
	  }

	document.write('</SCR');
	document.write('IPT>');

	// End Hide -->
</script>
<!-- END FGN Banner Code --><BR>
<TABLE CELLSPACING=0 CELLPADDING=0 BORDER=0>
<TR>
	<TD width=63><IMG SRC="graphics/topc000.jpg" WIDTH=63 HEIGHT=87></TD>
	<TD width=473><IMG SRC="graphics/topc001.jpg" WIDTH=473 HEIGHT=87></TD>
	<TD width=64><IMG SRC="graphics/topc002.jpg" WIDTH=64 HEIGHT=87></TD>
</TR>
	<TD width=63></TD>
	<TD BGCOLOR="#BEA279" width=460>
	<DIV ALIGN="CENTER">
	<IMG SRC="graphics/fileheader.jpg" WIDTH=200 HEIGHT=75>
	<TABLE WIDTH=460>
	<TR><TD>
	
	<TABLE BGCOLOR="#BEA279" WIDTH=430 ALIGN="center" CELLPADDING=5 CELLSPACING=5>
	<TR>
	<TD BGCOLOR="#BEA279" WIDTH=15></TD>
	<TD GCOLOR="#BEA279" WIDTH=400>
	<FONT FACE="Verdana" SIZE=2>
	<HR SIZE=2>
	
	<B>1. <A HREF="http://www.xs4all.nl/~fury/EQClient.zip">EQ Client INI writer</A></B><FONT COLOR="#FF0000" SIZE="-2"> - <B>New!</B></FONT><BR>&nbsp;&nbsp;&nbsp; - <FONT SIZE="-1">by <A HREF="mailto:enoch100@hotmail.com?subject=EQClient">Gresham Dagor</A>, Seekers of Lore - Veeshan</FONT><BR><BR>
	
	<B>2. <A HREF="http://www.electricfunstuff.com/songs/EFS_Has_Anybody_Here_Seen_My_Corpse_(original).mp3">"Has Anybody Seen my Corpse?"</A></B><BR>&nbsp;&nbsp;&nbsp; - <FONT SIZE="-1">Very popular EQ song recently remixed<BR>&nbsp;&nbsp;&nbsp; - <FONT SIZE="-1">by <A HREF="http://www.electricfunstuff.com/efs_band.html" TARGET="_new">Electric Funstuff</A></FONT><BR><BR>
	
	<B>3. <A HREF="http://www.electricfunstuff.com/songs/EFS_Has_Anybody_Here_Seen_My_Corpse.mp3">"Has Anybody Seen my Corpse?"</A></B><FONT COLOR="#FF0000" SIZE="-2"> - <B>Original</B></FONT><BR>&nbsp;&nbsp;&nbsp; - <FONT SIZE="-1">The original version because some people prefer it!<BR>&nbsp;&nbsp;&nbsp; - <FONT SIZE="-1">by <A HREF="http://www.electricfunstuff.com/efs_band.html" TARGET="_new">Electric Funstuff</A></FONT><BR><BR>
	
	<B>4. <A HREF="http://www.visi.com/~abc/eqmapper.exe">EQMapper Ver. 2</A></B><BR>&nbsp;&nbsp;&nbsp; - <FONT SIZE="-1">by Jebo<BR>&nbsp;&nbsp;&nbsp; - <A HREF="http://www.visi.com/~abc/" TARGET="_new">EQMapper Homepage</A></FONT><BR><BR>
	
	<B>5. <A HREF="http://www.duke.nu/EQSSnSetup185.exe">EQ ServerScan 1.8.5</A></B><BR>&nbsp;&nbsp;&nbsp; - <FONT SIZE="-1">by Erik Elamson, aka Duke Elam of Tarew Marr<BR>&nbsp;&nbsp;&nbsp; - <A HREF="http://www.duke.nu/eqserverscan.html">EQServerScan Homepage</A></FONT><BR><BR>
	
	<B>6. <A HREF="http://www.xs4all.nl/~fury/eq_armor_jan14.zip">All Armor</A></B><BR>&nbsp;&nbsp;&nbsp; - <FONT SIZE="-1">Excel Sheet - Updated January 14th 2000</FONT><BR><BR>
	
	<B>7. <A HREF="http://www.xs4all.nl/~fury/eq_weapons_mar05.zip">All Weapons</A></B><BR>&nbsp;&nbsp;&nbsp; - <FONT SIZE="-1">Excel Sheet - Updated March 05th 2000</FONT><BR><BR>
	
	<B>8. <A HREF="http://www.xs4all.nl/~fury/eq_npcs_mar05.zip">All NPC's</A></B><BR>&nbsp;&nbsp;&nbsp; - <FONT SIZE="-1">Excel Sheet - Updated March 05th 2000</FONT><BR><BR>
	
	<B>9. <A HREF="http://www.xs4all.nl/~fury/EQParse213.zip">EQ Log Parser ver. 2.13</A></B><BR>&nbsp;&nbsp;&nbsp; - <A HREF="http://kqp.mpog.com/EQParse/">EQ Log Parser Homepage</A><BR>&nbsp;&nbsp;&nbsp; - <FONT SIZE="-1">A handy utility</FONT><BR><BR>
	
	<B>10. <A HREF="http://www.xs4all.nl/~fury/eqtheme.zip">EQ Desktop Theme Pack</A></B><BR>&nbsp;&nbsp;&nbsp; - <FONT SIZE="-1">Eq based desktop themes for Windows</FONT><BR><BR>
	
	<B>11. <A HREF="http://www.xs4all.nl/~fury/eq_music.zip">EQ Music Files</A></B><BR>&nbsp;&nbsp;&nbsp; - <FONT SIZE="-1">All the MIDI music files from the game.</FONT><BR><BR>
	
	<B>12. <A HREF="http://www.xs4all.nl/~fury/mwdc3_8full.zip">EQ Mana & Weapon Damage Calc. v3.8</A></B><BR>&nbsp;&nbsp;&nbsp; - <FONT SIZE="-1">A handy utility</FONT><BR><BR>
	<HR SIZE=2>
	</FONT>
	</TD>
	<TD BGCOLOR="#BEA279" width=15></TD>
	</TR>
	</TABLE>

	</TD></TR>
	</TABLE>
	<TD width="64"></TD>
<TR>
	<TD><IMG SRC = "graphics/botc000.jpg" WIDTH = 63 HEIGHT = 87></TD>
	<TD><IMG SRC = "graphics/botc001.jpg" WIDTH = 473 HEIGHT = 87></TD>
	<TD><IMG SRC = "graphics/botc002.jpg" WIDTH = 64 HEIGHT = 87></TD>
</TR>
</TABLE>
<BR>
<IMG SRC="http://service.bfast.com/bfast/serve?bfmid=1375281&siteid=40292692&bfpage=pc" BORDER="0" WIDTH="1" HEIGHT="1" NOSAVE ><A HREF="http://service.bfast.com/bfast/click?bfmid=1375281&siteid=40292692&bfpage=pc" TARGET="_new"><IMG SRC="http://affiliate.gamestop.com/affIMG/pc_120x60.gif" BORDER="0" WIDTH="120" HEIGHT="60" ALT="PC Games at GameStop.com"></A>
<BR>
<BR>
</DIV>
</BODY>
</HTML>

