<!-- WARNING!  DO NOT EDIT THIS FILE BY HAND OR USING AN HTML EDITOR! -->
<HTML>
<HEAD>
<TITLE>Contact Moderators</TITLE>
<SCRIPT LANGUAGE="JavaScript">
<!-- ;
function setStatus(msg) {
  window.status = msg;
  return true;
}
function initpage () {
  window.defaultStatus = ""
  if (document.userpass) {
    if (document.userpass.username) {
      if (document.userpass.username.value == "") {
        document.userpass.username.value = readcookie("user")
      }
    }
    if (document.userpass.passwd) {
      if (document.userpass.passwd.value == "") {
        document.userpass.passwd.value = readcookie("rpwd")
      }
    }
  }
}function readcookie(name) {
  var i = 0; var lookfor = name + "="
  while (i < document.cookie.length) {
    var j = i + lookfor.length
    if (document.cookie.substring(i,j) == lookfor) {
      var endstr = document.cookie.indexOf(";", j)
      if (endstr == -1) {
        endstr = document.cookie.length
      }
      return unescape(document.cookie.substring(j, endstr))
    }
    i = document.cookie.indexOf(" ", i) + 1
    if (i == 0) {
      break
    }
  }
  return ""
}
// end hide -->
</SCRIPT>
</HEAD>
<BODY BGCOLOR="#eeeeee" TEXT="#000000" LINK="#0000ff" VLINK="#800080" ALINK="#ff0000" BACKGROUND="http://www.eq-continuum.com/images/lebkgnd.jpg" onLoad="initpage()">
<BASEFONT SIZE="2"><FONT FACE="Verdana,Arial,Helvetica">
<A NAME="">
<a name=MT>
<CENTER><FONT SIZE=+1><B>Contact Moderators</B></FONT></CENTER>
<HR>
<FONT SIZE=1><B></B></FONT>
<P>Moderators:<P><UL>
<LI>admin</A></LI>
<LI><A HREF="mailto:adammair_1@yahoo.com">Adammair</A></LI>
<LI><A HREF="mailto:sbp99@hotmail.com">Arameus</A></LI>
</UL><P>
<P>Please address general questions and concerns to <A HREF="mailto:sbp99@hotmail.com">Guildleader</A>.<P>
<HR><CENTER><BR>
<A HREF="javascript:history.back()">Back to previous page</A>
</CENTER>
</FONT>
<P>
<P>
</BODY>
</HTML>
