<!--
                 This page has been created by Renaissance IT
   Renaissance Internet Technologies Copyright (c) 1999 All Rights Reserved.

             for more info on our products, please visit :
                        http://www.renaissance.nl/

	This script has been written by Roy Boverhof <rboverhof@renaissance.nl>
	
        Pagename                : trivial_chart.html
        Last Updated    		: 31-01-2000
-->

<HTML>
<HEAD>
	<TITLE>the Seekers of Lore : Trivial Chart</TITLE>
</HEAD>

<BODY BGCOLOR="#000000" TEXT="#000000" LINK="#000000" VLINK="#000000" ALINK="#000000">
<DIV ALIGN="CENTER">
<BR>
<!-- FGN Banner Code -->
<script language="JavaScript">
	<!-- Hide from old browsers
	var random = new Number(Math.floor(9999999 * Math.random())+1);

	// Modify to reflect site specifics
	page = "eqlore.com/";
	target = "@Top1,x02,x05,x08!Top1";

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript1.1" SRC="http://oascentral.cybereps.com/RealMedia/ads/adstream_jx.ads/' + page + 1 + random + target + '">');
	document.write('</SCR');
	document.write('IPT>');

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript">');
	document.write('_version=10; //-->');
	document.write('</SCR');
	document.write('IPT>');

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript1.1">');
	document.write('_version=11; //-->');
	document.write('</SCR');
	document.write('IPT>');

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript">');

	if (navigator.appVersion.indexOf('MSIE 3') != -1){
	document.write('<IFRAME MARGINWIDTH=0 MARGINHEIGHT=0 HSPACE=0 VSPACE=0 FRAMEBORDER=0 SCROLLING=no BORDERCOLOR="#000000" SRC="oascentral.cybereps.com/RealMedia/ads/adstream_sx.ads/' + page + random + target + '"></IFRAME>');
	  }
	else if (_version < 11) {
	document.write ('<A HREF="http://oascentral.cybereps.com/RealMedia/ads/click_nx.ads/' + page + random + target + '"><IMG SRC="http://oascentral.cybereps.com/RealMedia/ads/adstream_nx.ads/' + page + random + target + '"></a>');
	  }

	document.write('</SCR');
	document.write('IPT>');

	// End Hide -->
</script>
<!-- END FGN Banner Code --><BR>
<TABLE CELLSPACING = 0 CELLPADDING = 0 BORDER = 0>
<TR>
	<TD width="63"><IMG SRC = "http://www.loreseekers.com/graphics/topc000.jpg" WIDTH = 63 HEIGHT = 87></TD>
	<TD width="473"><IMG SRC = "http://www.loreseekers.com/graphics/topc001.jpg" WIDTH = 473 HEIGHT = 87></TD>
	<TD width="64"><IMG SRC = "http://www.loreseekers.com/graphics/topc002.jpg" WIDTH = 64 HEIGHT = 87></TD>
</TR>
	<TD width="63"></TD>
	<TD BGCOLOR="#BEA279" width="460">
	<DIV ALIGN="CENTER">
	<TABLE>
	<TR>
	<TD BGCOLOR="#BEA279" width="450">
	
<P ALIGN="left"><FONT SIZE="4" face="helvetica"><STRONG>G. Trivial Chart</STRONG></FONT></A></P>


<!-- START OF CONVERTED OUTPUT -->
<!-- ------------------------- -->
<Table border>
<TR ALIGN="center" VALIGN="bottom">
<TD BGCOLOR=#FFFFCC COLSPAN=5><FONT FACE="Verdana" SIZE="2" COLOR=#800000><B>
Trivial Chart</B></FONT></TD>
</TR>
<TR ALIGN="center" VALIGN="bottom">
<TD COLSPAN=5><FONT FACE="Verdana" SIZE="1" COLOR=#800000>
<B>Note:</B> Values with an asterisk after them denote bugged items that have no trivial in their *enchanted* form only, the mundane metal and gem combinations will go trivial correctly at the given value</FONT></TD>
</TR>
<TR ALIGN="center" VALIGN="bottom">
<TD BGCOLOR=#800000><FONT FACE="Verdana" SIZE="1" COLOR=#FFFFFF><B>
Stone</B></FONT></TD>
<TD BGCOLOR=#800000><FONT FACE="Verdana" SIZE="1" COLOR=#FFFFFF><B>
Ench Silver</B></FONT></TD>
<TD BGCOLOR=#800000><FONT FACE="Verdana" SIZE="1" COLOR=#FFFFFF><B>
Ench Elect</B></FONT></TD>
<TD BGCOLOR=#800000><FONT FACE="Verdana" SIZE="1" COLOR=#FFFFFF><B>
Ench Gold</B></FONT></TD>
<TD BGCOLOR=#800000><FONT FACE="Verdana" SIZE="1" COLOR=#FFFFFF><B>
Ench Plat</B></FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD BGCOLOR=#FFFFCC ALIGN="left"><FONT FACE="Verdana" SIZE="1">
Malachite</FONT></TD>
<TD ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
???</FONT></TD>
<TD ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
74</FONT></TD>
<TD ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
146</FONT></TD>
<TD ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
???</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD BGCOLOR=#FFFFCC ALIGN="left"><FONT FACE="Verdana" SIZE="1">
Lapis Lazuli</FONT></TD>
<TD ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
???</FONT></TD>
<TD ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
76</FONT></TD>
<TD ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
148</FONT></TD>
<TD ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
???</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD BGCOLOR=#FFFFCC ALIGN="left"><FONT FACE="Verdana" SIZE="1">
Turquiose</FONT></TD>
<TD ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
???</FONT></TD>
<TD ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
79</FONT></TD>
<TD ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
151</FONT></TD>
<TD ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
???</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD BGCOLOR=#FFFFCC ALIGN="left"><FONT FACE="Verdana" SIZE="1">
Hematite</FONT></TD>
<TD ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
???</FONT></TD>
<TD ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
82</FONT></TD>
<TD ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
154</FONT></TD>
<TD ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
???</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD BGCOLOR=#FFFFCC ALIGN="left"><FONT FACE="Verdana" SIZE="1">
Wolf's Eye Agate</FONT></TD>
<TD ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
???</FONT></TD>
<TD ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
???</FONT></TD>
<TD ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
???</FONT></TD>
<TD ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
???</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD BGCOLOR=#FFFFCC ALIGN="left"><FONT FACE="Verdana" SIZE="1">
Cat's Eye Agate</FONT></TD>
<TD ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
22</FONT></TD>
<TD ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
84</FONT></TD>
<TD ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
156</FONT></TD>
<TD ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
???</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD BGCOLOR=#FFFFCC ALIGN="left"><FONT FACE="Verdana" SIZE="1">
Bloodstone</FONT></TD>
<TD ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
26</FONT></TD>
<TD ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
87</FONT></TD>
<TD ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
159</FONT></TD>
<TD ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
???</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD BGCOLOR=#FFFFCC ALIGN="left"><FONT FACE="Verdana" SIZE="1">
Onyx</FONT></TD>
<TD ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
28</FONT></TD>
<TD ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
90</FONT></TD>
<TD ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
162</FONT></TD>
<TD ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
???</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD BGCOLOR=#FFFFCC ALIGN="left"><FONT FACE="Verdana" SIZE="1">
Jasper</FONT></TD>
<TD ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
30</FONT></TD>
<TD ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
92</FONT></TD>
<TD ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
164</FONT></TD>
<TD ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
???</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD BGCOLOR=#FFFFCC ALIGN="left"><FONT FACE="Verdana" SIZE="1">
Carnelian</FONT></TD>
<TD ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
32</FONT></TD>
<TD ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
95</FONT></TD>
<TD ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
167</FONT></TD>
<TD ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
???</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD BGCOLOR=#FFFFCC ALIGN="left"><FONT FACE="Verdana" SIZE="1">
Star Rose Quartz</FONT></TD>
<TD ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
34</FONT></TD>
<TD ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
98</FONT></TD>
<TD ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
170*</FONT></TD>
<TD ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
???</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD BGCOLOR=#FFFFCC ALIGN="left"><FONT FACE="Verdana" SIZE="1">
Amber</FONT></TD>
<TD ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
36</FONT></TD>
<TD ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
100</FONT></TD>
<TD ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
172</FONT></TD>
<TD ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
???</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD BGCOLOR=#FFFFCC ALIGN="left"><FONT FACE="Verdana" SIZE="1">
Jade</FONT></TD>
<TD ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
40</FONT></TD>
<TD ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
106</FONT></TD>
<TD ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
178</FONT></TD>
<TD ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
???</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD BGCOLOR=#FFFFCC ALIGN="left"><FONT FACE="Verdana" SIZE="1">
Pearl</FONT></TD>
<TD ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
42</FONT></TD>
<TD ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
108</FONT></TD>
<TD ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
180</FONT></TD>
<TD ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
???</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD BGCOLOR=#FFFFCC ALIGN="left"><FONT FACE="Verdana" SIZE="1">
Topaz</FONT></TD>
<TD ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
44</FONT></TD>
<TD ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
111</FONT></TD>
<TD ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
???</FONT></TD>
<TD ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
???</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD BGCOLOR=#FFFFCC ALIGN="left"><FONT FACE="Verdana" SIZE="1">
Peridot</FONT></TD>
<TD ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
46</FONT></TD>
<TD ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
113</FONT></TD>
<TD ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
186</FONT></TD>
<TD ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
???</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD BGCOLOR=#FFFFCC ALIGN="left"><FONT FACE="Verdana" SIZE="1">
Emerald</FONT></TD>
<TD ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
48</FONT></TD>
<TD ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
116</FONT></TD>
<TD ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
188</FONT></TD>
<TD ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
???</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD BGCOLOR=#FFFFCC ALIGN="left"><FONT FACE="Verdana" SIZE="1">
Opal</FONT></TD>
<TD ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
50</FONT></TD>
<TD ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
119</FONT></TD>
<TD ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
191</FONT></TD>
<TD ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
???</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD BGCOLOR=#FFFFCC ALIGN="left"><FONT FACE="Verdana" SIZE="1">
Star Ruby</FONT></TD>
<TD ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
??</FONT></TD>
<TD ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
127</FONT></TD>
<TD ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
???</FONT></TD>
<TD ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
???</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD BGCOLOR=#FFFFCC ALIGN="left"><FONT FACE="Verdana" SIZE="1">
Fire Emerald</FONT></TD>
<TD ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
??</FONT></TD>
<TD ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
130</FONT></TD>
<TD ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
???</FONT></TD>
<TD ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
???</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD BGCOLOR=#FFFFCC ALIGN="left"><FONT FACE="Verdana" SIZE="1">
Sapphire</FONT></TD>
<TD ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
??</FONT></TD>
<TD ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
???</FONT></TD>
<TD ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
???</FONT></TD>
<TD ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
???</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD BGCOLOR=#FFFFCC ALIGN="left"><FONT FACE="Verdana" SIZE="1">
Ruby</FONT></TD>
<TD ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
75</FONT></TD>
<TD ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
???*</FONT></TD>
<TD ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
???</FONT></TD>
<TD ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
???</FONT></TD>
</TR>
<TR ALIGN="center" VALIGN="bottom">
<TD BGCOLOR=#800000 COLSPAN=5><FONT FACE="Verdana" SIZE="1" COLOR=#FFFFFF><B>
Rare Stones</B></FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD BGCOLOR=#FF9900 ALIGN="left"><FONT FACE="Verdana" SIZE="1">
Black Pearl</FONT></TD>
<TD ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
???</FONT></TD>
<TD ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
???</FONT></TD>
<TD ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
???</FONT></TD>
<TD ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
???</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD BGCOLOR=#FF9900 ALIGN="left"><FONT FACE="Verdana" SIZE="1">
Fire Opal</FONT></TD>
<TD ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
???</FONT></TD>
<TD ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
???</FONT></TD>
<TD ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
???</FONT></TD>
<TD ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
???</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD BGCOLOR=#FF9900 ALIGN="left"><FONT FACE="Verdana" SIZE="1">
Jacinth</FONT></TD>
<TD ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
???</FONT></TD>
<TD ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
???</FONT></TD>
<TD ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
???</FONT></TD>
<TD ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
???</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD BGCOLOR=#FF9900 ALIGN="left"><FONT FACE="Verdana" SIZE="1">
Black Sapphire</FONT></TD>
<TD ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
???</FONT></TD>
<TD ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
???</FONT></TD>
<TD ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
???</FONT></TD>
<TD ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
???</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD BGCOLOR=#FF9900 ALIGN="left"><FONT FACE="Verdana" SIZE="1">
Diamond</FONT></TD>
<TD ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
???</FONT></TD>
<TD ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
???</FONT></TD>
<TD ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
???</FONT></TD>
<TD ALIGN="center" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#000000>
???</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD BGCOLOR=#FFFFCC COLSPAN=5><FONT FACE="Verdana" SIZE="2" COLOR=#800000>&nbsp;</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="right"><FONT FACE="Verdana" SIZE="1">
&nbsp;</FONT></TD>
<TD ALIGN="right"><FONT FACE="Verdana" SIZE="1">
&nbsp;</FONT></TD>
<TD COLSPAN=3 ALIGN="center"><FONT FACE="Verdana" SIZE="1">
Send all updated information to:</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="right"><FONT FACE="Verdana" SIZE="1">
&nbsp;</FONT></TD>
<TD ALIGN="right"><FONT FACE="Verdana" SIZE="1">
&nbsp;</FONT></TD>
<TD COLSPAN=3 ALIGN="center"><A HREF="mailto:adroken@swbell.net"><FONT FACE="Arial" COLOR=#0000FF><U>
adroken@swbell.net</U></FONT></A></TD>
</TR>
</Table>
<!-- ------------------------- -->
<!-- END OF CONVERTED OUTPUT -->

<BR><BR><DIV ALIGN="center"><A HREF="new_jewelry_guide.phtml" TARGET="_self"><IMG SRC="back_button.jpg" WIDTH=200 HEIGHT=50 BORDER=0 ALIGN="MIDDLE" ALT="Back to the Guide"></A></DIV><BR><BR>

</TR>
</TABLE>
	<TD width="64"></TD>
<TR>
	<TD><IMG SRC = "http://www.loreseekers.com/graphics/botc000.jpg" WIDTH = 63 HEIGHT = 87></TD>
	<TD><IMG SRC = "http://www.loreseekers.com/graphics/botc001.jpg" WIDTH = 473 HEIGHT = 87></TD>
	<TD><IMG SRC = "http://www.loreseekers.com/graphics/botc002.jpg" WIDTH = 64 HEIGHT = 87></TD>
</TR>
</TABLE>
<BR>

<script language="JavaScript">
	<!-- Hide from old browsers
	var random = new Number(Math.floor(9999999 * Math.random())+1);

	// Modify to reflect site specifics
	page = "eqlore.com/";
	target = "@Top1,x02,x05,x08!x02";

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript1.1" SRC="http://oascentral.cybereps.com/RealMedia/ads/adstream_jx.ads/' + page + 1 + random + target + '">');
	document.write('</SCR');
	document.write('IPT>');

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript">');
	document.write('_version=10; //-->');
	document.write('</SCR');
	document.write('IPT>');

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript1.1">');
	document.write('_version=11; //-->');
	document.write('</SCR');
	document.write('IPT>');

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript">');

	if (navigator.appVersion.indexOf('MSIE 3') != -1){
	document.write('<IFRAME MARGINWIDTH=0 MARGINHEIGHT=0 HSPACE=0 VSPACE=0 FRAMEBORDER=0 SCROLLING=no BORDERCOLOR="#000000" SRC="oascentral.cybereps.com/RealMedia/ads/adstream_sx.ads/' + page + random + target + '"></IFRAME>');
	  }
	else if (_version < 11) {
	document.write ('<A HREF="http://oascentral.cybereps.com/RealMedia/ads/click_nx.ads/' + page + random + target + '"><IMG SRC="http://oascentral.cybereps.com/RealMedia/ads/adstream_nx.ads/' + page + random + target + '"></a>');
	  }

	document.write('</SCR');
	document.write('IPT>');

	// End Hide -->
</script><BR>
<BR>
</DIV>
</BODY>
</HTML>