<!--
                 This page has been created by Renaissance IT
   Renaissance Internet Technologies Copyright (c) 1999 All Rights Reserved.

             for more info on our products, please visit :
                        http://www.renaissance.nl/

	This script has been written by Roy Boverhof <rboverhof@renaissance.nl>
	
        Pagename                : jewelcraft.html
        Last Updated    		: 28-7-1999
-->

<HTML>
<HEAD>
	<TITLE>the Seekers of Lore : Alchemys Magicians Guide to Soloing</TITLE>
</HEAD>

<BODY BGCOLOR="#000000" TEXT="#000000" LINK="#FFF000">
<DIV ALIGN="CENTER">
<BR>
<!-- FGN Banner Code -->
<script language="JavaScript">
	<!-- Hide from old browsers
	var random = new Number(Math.floor(9999999 * Math.random())+1);

	// Modify to reflect site specifics
	page = "eqlore.com/";
	target = "@Top1,x02,x05,x08!Top1";

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript1.1" SRC="http://oascentral.cybereps.com/RealMedia/ads/adstream_jx.ads/' + page + 1 + random + target + '">');
	document.write('</SCR');
	document.write('IPT>');

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript">');
	document.write('_version=10; //-->');
	document.write('</SCR');
	document.write('IPT>');

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript1.1">');
	document.write('_version=11; //-->');
	document.write('</SCR');
	document.write('IPT>');

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript">');

	if (navigator.appVersion.indexOf('MSIE 3') != -1){
	document.write('<IFRAME MARGINWIDTH=0 MARGINHEIGHT=0 HSPACE=0 VSPACE=0 FRAMEBORDER=0 SCROLLING=no BORDERCOLOR="#000000" SRC="oascentral.cybereps.com/RealMedia/ads/adstream_sx.ads/' + page + random + target + '"></IFRAME>');
	  }
	else if (_version < 11) {
	document.write ('<A HREF="http://oascentral.cybereps.com/RealMedia/ads/click_nx.ads/' + page + random + target + '"><IMG SRC="http://oascentral.cybereps.com/RealMedia/ads/adstream_nx.ads/' + page + random + target + '"></a>');
	  }

	document.write('</SCR');
	document.write('IPT>');

	// End Hide -->
</script>
<!-- END FGN Banner Code --><BR>
<TABLE CELLSPACING = 0 CELLPADDING = 0 BORDER = 0>
<TR>
	<TD width="63"><IMG SRC = "../graphics/topc000.jpg" WIDTH = 63 HEIGHT = 87></TD>
	<TD width="473"><IMG SRC = "../graphics/topc001.jpg" WIDTH = 473 HEIGHT = 87></TD>
	<TD width="64"><IMG SRC = "../graphics/topc002.jpg" WIDTH = 64 HEIGHT = 87></TD>
</TR>
	<TD width="63"></TD>
	<TD BGCOLOR="#BEA279" width="460">
	<TABLE WIDTH="460">
	<TR>
		<TD>		

			<P><CENTER><FONT face=Arial size=2>
			
			<FONT size=4><B>Alchemys</B> Magicians Guide to Soloing (L1 - L18)</FONT><BR><EM>
			
			by Alchemys &lt;Seekers Of Lore&gt;<BR></EM><FONT 
			
			face=Arial size=2>
			
			Level 18 High Elf Magician, Tunare<BR></FONT>
			
			<P></P></CENTER>
			
			<P>
			
			I will preface this guide with the following disclaimer: Most of the tips I have
			
			here are from my own experience. However, some of it I have adopted from other
			
			guides and suggestions. Drue's guide is still the best comprehensive one as far
			
			as I have seen (can be found at <a href="http://eq.stratics.com/classes_mag_ad.shtml">EQ Stratics Advance Magician Guide</a>).
			
			He has also played longer than I.  I am only Level 18 and can not say if these
			
			techniques transfer well to higher levels. Also, I have included some notes that 
			
			apply to grouping as well.  Mostly in describing the use of spells.  Some of the
			
			Magician spells are better suited to a group environment, and I make note of 
			
			those.
			
			</P>
			
			<P>
			
			As a Magician I have spent most of my advancement solo.  This is mostly due to
			
			my limited contiguous play time.  I usually can get in an hour or two straight
			
			with rare stints of 2+ hours.
			
			</P>
			
			<P>
			
			If you are starting off now (as of 20 July 1999), pets are even better than when
			
			I started.  They get Kick, Bash, and Spells. Makes them much more formidable in
			
			a fight, especially against other spell casting MOBS.
			
			</P>
			
			<P>
			
			Also, I will make spell "buy" suggestions, but these are only my opinions.  Also
			
			some of the available spells may have changed.  Look to <a href="http://eq.stratics.com">EQ Stratics</a>
			
			for a good spell guide.  There are many other sites out there too that may have
			
			more accurate information, or at least may fill in more info, but this site
			
			seems to have the best info over all.   I also recommend that you subscribe to
			
			the EQMagicians@onelist.com forum (subscribe at <a href="http://www.onelist.com">One List</a>).   There are
			
			a bunch of experienced mages in this group that answer questions fairly quickly
			
			and *usually* with direct and accurate information from experience.
			
			</P>
			
			<P>
			
			I will first give you my general play style guide that I am using to very good
			
			effect at level 18.  This is for outdoor soloing.  Dungeons are special, so
			
			refer to my <A href="#DungeonGuide" >Dungeon Guide</A> below for that style.
			
			</P>
			
			<P>
			
			Typically this is how a round goes:
			
			</P>
			
			<P>
			
			<OL>
			
			<LI>Park Pet (/pet sit down, NOT /pet Guard Here) 
			
			<LI>Cast Fire Shield on it. 
			
			<LI>Find suitable target. 
			
			<LI>Burn with Shock of Blades or other quick cast spell 
			
			<LI>Run back to pet. 
			
			<LI>Sick pet on target if it has not hit me 
			
			<LI>Burn 2 more times 
			
			<LI>Meditate (BLUES ONLY) 
			
			<LI>[Burn again if pet is below 50%]</LI>       
			
			</OL>
			
			<P>
			
			Now this is where things are interesting.  If the pet is blue and my pet is blue
			
			or better, I will sit and meditate at this time.  Yes that is right.  I have the
			
			MOB targeted and I keep a running tab on my pet with /pet report health.  If it
			
			drops below 50% and the MOB is not near death, I will stand up and burn it once
			
			more, or twice if it is stubborn or resisted my spell slightly.  I try to stay
			
			just in the /pet report range but far enough from the mob that it is not tempted
			
			to attack me.  Some MOBS are DETERMINED to get me and my pet has to keep
			
			taunting it back.  Sometimes the MOB will make it and strike me.  That also is a
			
			good time to just plaster it.  I have found that this really reduces my down
			
			time with blues by about 50%.  I use the water pet without Burnout and it
			
			usually is healed up just as I have meditated up to full mana.  I find if I 
			
			reduce the burn I can let my pet soak all the damage and finish it off, and be
			
			back out searching for another real quick.
			
			</P>
			
			<P>
			
			HOWEVER, if the MOB is a very tough blue, or a white or yellow, I stay and burn,
			
			heavily and even tank for my pet after the second burn.  Even if you take some
			
			damage, you tanking for the pet a bit keeps it alive long enough to finish off
			
			the MOB.  ESPECIALLY if it is a Yellow or Low Red.
			
			</P>
			
			<P>
			
			Keep in mind these are for certain White / Yellow and SOME Reds. I have noticed
			
			that some MOBS are tougher than others at the same "level".  Some I will have to
			
			burn more and tank more while there are others my pet can finish off themselves.
			
			As a mater of fact, my water pet at my level has finished off a low blue and one
			
			green mob, completely solo, while I was running for my life with another blue on
			
			my tail.  I did eventually finish off the one blue on me, but was near death and
			
			was being attacked by a stray green MOB I was near so had to zone.  When I got
			
			back to the scene of the battle I had discovered my pet had finished off both
			
			the mobs without me and the corpses were waiting (even though I had killed my
			
			poor pet by zoning).. Pretty satisfying.  Talk about an effective, mana
			
			efficient DOT spell!!!  If you look at pets that way, we Magicians have by far
			
			the best DOT spells around.
			
			</P>
			
			<P>
			
			Another tip.  YOUR PETS ARE EXPENDABLE!!!.  I have learned this the hard way.
			
			If there is the slightest doubt of survival.  Don't think, RUN for the zone, if
			
			guards are not handy.  I have died way too many times trying to "save my pet"
			
			don't bother.  It ain't worth the experience loss.  They are CHEAP in
			
			comparison.  We have a great advantage in that if the scene looks grim, we have
			
			a sacrificial tank.  USE IT.
			
			</P>
			
			<P>
			
			When soloing Fire Shield is your friend.  That is why I avoid Fire Elementals as
			
			my pet, I can turn my Water, Earth or Air into a much better Fire Elemental with
			
			Fire Shield.  The fire shield lasts for about 3 minutes at my level.  Enough for
			
			one and possibly two fights.  If you use it on yourself, you are wasting mana,
			
			because it does not last and you should not be tanking that much anyway.  Fire
			
			shield is also great if you are grouped with one PC tank. Fire Shield the PC tank,
			
			because chances are the MOB will ignore your pet in favor of the PC tank.
			
			</P>
			
			<BR></FONT>
			
			<H3>SPECIFIC INFO BROKEN DOWN BY RANK: </H3>
			
			<H4>RANK 1, Levels 1-3</H4><FONT face=Arial size=2>
			
			<P>
			
			This is the time when you are petless and have to burn everything.  Your melee
			
			skills are lame and you end up running for your life as much as you do killing
			
			anything.  The fortunate thing is that you will advance pretty quick.  Attack
			
			whites only when you are level 1.  From level 2 you need to seriously consider
			
			any target you attack.  Even some blues will give you troubles, and without
			
			meditate, you have a slow mana recovery.  But stick with it, level 4 is when you
			
			really begin to shine.  If you can get in a group that is great, but you will
			
			advance much quicker on your own.  I found that getting my Magician to level 4
			
			was about twice as fast as getting my Ranger character to level 4. I think they
			
			do this on purpose, since as a caster, not having meditate or a pet, you are
			
			really weak.   I did not even use many of my training points during this time.
			
			Just a few to give me a boost in my piercing skill so I was not completely lame
			
			at level 1.  Save them for later levels (16+) with research.  Pick a race that
			
			has pretty good intelligence.  I picked a High Elf for a good balance, plus
			
			the Infra vision. Erudinites have the best native intelligence.  But in the long
			
			run, it all boils down to personal preference and what you want to role play as.
			
			Any minor differences between races will be compensated for in some way.  Also
			
			save all your pennies.  You will need them for your Rank 2 spells.  Buy only
			
			what you need for level 1.
			
			</P>
						
			<P>
			
			Here is a list of level 1 - 4 spells, and some attributes.  I pulled this info
			
			straight from the http://eq.stratics.com site, however I have ranked them with
			
			my buy order (top to bottom).
			
			</P>
			
			<P>
			
			Note: "CT" indicates a spell's base casting time, in seconds
			
			</P>
			
			<P>

			<TABLE BORDER CELLSPACING=1 BORDERCOLOR="#000000" CELLPADDING=7 WIDTH=460>
			
			<TR>
			
			   <TD WIDTH="21%" VALIGN="TOP" BGCOLOR="#006600"><B><FONT SIZE=2 COLOR="#ffff00">Spell</B></FONT></TD>
			
			   <TD WIDTH="12%" VALIGN="TOP" BGCOLOR="#006600"><B><FONT SIZE=2 COLOR="#ffff00">Who</B></FONT></TD>
			
			   <TD WIDTH="43%" VALIGN="TOP" BGCOLOR="#006600"><B><FONT SIZE=2 COLOR="#ffff00">Description</B></FONT></TD>
			
			   <TD WIDTH="10%" VALIGN="TOP" BGCOLOR="#006600"><B><FONT SIZE=2 COLOR="#ffff00"><CENTER>Skill<CENTER></B></FONT></TD>
			
			   <TD WIDTH="5%"  VALIGN="TOP" BGCOLOR="#006600"><B><FONT SIZE=2 COLOR="#ffff00"><CENTER>CT<CENTER></B></FONT></TD>
			
			   <TD WIDTH="9%"  VALIGN="TOP" BGCOLOR="#006600"><B><FONT SIZE=2 COLOR="#ffff00"><CENTER>Mana<CENTER></B></FONT></TD>
			
			</TR>
			
			<TR>
			
			   <TD WIDTH="21%" VALIGN="TOP" BGCOLOR="#FFFFCC"><B><FONT SIZE=2 COLOR="#000000">Burst of Flame</B></FONT></TD>
			
			   <TD WIDTH="12%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000">Target:</B></FONT></TD>
			
			   <TD WIDTH="43%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000">1-6 HP Direct Damage</B></FONT></TD>
			
			   <TD WIDTH="10%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>Evo.<CENTER></B></FONT></TD>
			
			   <TD WIDTH="5%"  VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>1</CENTER></FONT></TD>
			
			   <TD WIDTH="9%"  VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>7</CENTER></B></FONT></TD>
			
			</TR>
			
			<TR>
			
			   <TD WIDTH="21%" VALIGN="TOP" BGCOLOR="#FFFFCC"><B><FONT SIZE=2 COLOR="#000000">Minor Shielding</B></FONT></TD>
			
			   <TD WIDTH="12%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000">Self:</B></FONT></TD>
			
			   <TD WIDTH="43%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000">+AC &amp; Max HP</B></FONT></TD>
			
			   <TD WIDTH="10%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>Abj.<CENTER></B></FONT></TD>
			
			   <TD WIDTH="5%"  VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>2</CENTER></FONT></TD>
			
			   <TD WIDTH="9%"  VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>10</CENTER></B></FONT></TD>
			
			</TR>
			
			<TR>
			
			   <TD WIDTH="21%" VALIGN="TOP" BGCOLOR="#FFFFCC"><B><FONT SIZE=2 COLOR="#000000">Summon Dagger</B></FONT></TD>
			
			   <TD WIDTH="12%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000">Self:</B></FONT></TD>
			
			   <TD WIDTH="43%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000">Summons a Normal dagger<br>(damage 3, delay 21, dissappears on logout)</B></FONT></TD>
			
			   <TD WIDTH="10%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>Con.<CENTER></B></FONT></TD>
			
			   <TD WIDTH="5%"  VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>2</CENTER></FONT></TD>
			
			   <TD WIDTH="9%"  VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>10</CENTER></B></FONT></TD>
			
			</TR>
			
			<TR>
			
			   <TD WIDTH="21%" VALIGN="TOP" BGCOLOR="#FFFFCC"><B><FONT SIZE=2 COLOR="#000000">Summon Drink</B></FONT></TD>
			
			   <TD WIDTH="12%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000">Self:</B></FONT></TD>
			
			   <TD WIDTH="43%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000">Summons a Normal drink<br>(dissappears on logout)</B></FONT></TD>
			
			   <TD WIDTH="10%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>Con<CENTER></B></FONT></TD>
			
			   <TD WIDTH="5%"  VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>2</CENTER></FONT></TD>
			
			   <TD WIDTH="9%"  VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>10</CENTER></B></FONT></TD>
			
			</TR>
			
			<TR>
			
			   <TD WIDTH="21%" VALIGN="TOP" BGCOLOR="#FFFFCC"><B><FONT SIZE=2 COLOR="#000000">Summon Drink</B></FONT></TD>
			
			   <TD WIDTH="12%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000">Self:</B></FONT></TD>
			
			   <TD WIDTH="43%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000">Summons Normal food<br>(dissappears on logout)</B></FONT></TD>
			
			   <TD WIDTH="10%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>Con<CENTER></B></FONT></TD>
			
			   <TD WIDTH="5%"  VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>2</CENTER></FONT></TD>
			
			   <TD WIDTH="9%"  VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>10</CENTER></B></FONT></TD>
			
			</TR>
			
			<TR>
			
			   <TD WIDTH="21%" VALIGN="TOP" BGCOLOR="#FFFFCC"><B><FONT SIZE=2 COLOR="#000000">Reclaim Energy</B></FONT></TD>
			
			   <TD WIDTH="12%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000">Target:</B></FONT></TD>
			
			   <TD WIDTH="43%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000">Unsummon pet for mana</B></FONT></TD>
			
			   <TD WIDTH="10%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>Con<CENTER></B></FONT></TD>
			
			   <TD WIDTH="5%"  VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>1</CENTER></FONT></TD>
			
			   <TD WIDTH="9%"  VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>5</CENTER></B></FONT></TD>
			
			</TR>
			
			<TR>
			
			   <TD WIDTH="21%" VALIGN="TOP" BGCOLOR="#FFFFCC"><B><FONT SIZE=2 COLOR="#000000">Flare</B></FONT></TD>
			
			   <TD WIDTH="12%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000">Effect:</B></FONT></TD>
			
			   <TD WIDTH="43%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000">Shoots a flare in the direction you are facing</B></FONT></TD>
			
			   <TD WIDTH="10%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>Evo.<CENTER></B></FONT></TD>
			
			   <TD WIDTH="5%"  VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>2</CENTER></FONT></TD>
			
			   <TD WIDTH="9%"  VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>3</CENTER></B></FONT></TD>
			
			</TR>
			
			<TR>
			
			   <TD WIDTH="21%" VALIGN="TOP" BGCOLOR="#FFFFCC"><B><FONT SIZE=2 COLOR="#000000">Sense Majic</B></FONT></TD>
			
			   <TD WIDTH="12%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000">Target:</B></FONT></TD>
			
			   <TD WIDTH="43%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000">Sense magic on item you are holding (only works if you are self targeted)</B></FONT></TD>
			
			   <TD WIDTH="10%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>Div.<CENTER></B></FONT></TD>
			
			   <TD WIDTH="5%"  VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>2</CENTER></FONT></TD>
			
			   <TD WIDTH="9%"  VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>5</CENTER></B></FONT></TD>
			
			</TR>
			
			</TABLE>   		
					
			</P>
			
			<P>
			
			<B>Spell Notes:</B><BR>
			
			I believe (can't remember, it was so long ago) you start with your Burst of
			
			Flame and Minor Shielding spells.  Regardless, they are the most important in
			
			my mind to have first.
			
			</P>
			
			<P>
			
			So far I have found <STRONG>sense magic </STRONG> to be virtually useless.  Same is true for
			
			the Identify spell.  All items have all the information about them visible. I
			
			have never heard of the condition where items that are magic don't already tell
			
			you.  The only thing it <i><b>does</b></i> is enable you to practice your Divination skill,
			
			which helps when you get your Cast Invisible spell but has no utility value.
			
			Perhaps Verant plans on "hiding" object's abilities later on.
			
			</P></FONT>
			
			<H4>RANK 2, Levels 4-7</H4><FONT face=Arial size=2>
			
			<P>
			
			Whoo Hoo!  You can meditate AND you get pets.  Choose your pet wisely based upon
			
			your style of play.  There are tons of general guides on what the stats of each
			
			pet are, so I won't really go into that part.  I will provide suggestions based
			
			upon MY personal experience and style of play (mostly solo):  See my General Pet
			
			guide below.
			
			</P>
			
			<P>
			
			My suggestion for soloing would be either Earth or Water.
			
			</P>
			
			<P>
			
			At this point you also need to start looking out for buying your cloth armor.
			
			Fill up those slots as fast as you can.  Kill Orcs or skeletons that carry cloth
			
			armor.  Beg borrow or buy it.  It does make a difference.  Eventually you will
			
			graduate to more expensive robes and Woven or Netted Magic armor (that still
			
			looks like cloth, but is better).  But for now you want every last bit of AC you
			
			can get.  It is cheap, so buy it when you can..  Kill green mobs for cash if
			
			necessary.
			
			</P>
			
			<P>
			
			Spell Suggestions: (Pets are ranked separately, your pet spell is always first
			
			in the buy order :P ).  It usually is more cost effective to pick the type of
			
			pet you will use the most and buy that one and stick to it.  Early on, money is
			
			tight and even later on you usually don't want to expend a bunch of cash on a
			
			pet that you use rarely.  It really becomes moot after 16 anyway, because you
			
			have to research all of your pets except for one.   I will deviate from the one
			
			available only when it does not suit me (like when the Fire Elemental is the
			
			only one you can buy, I will go to the ends of the earth to research Earth or
			
			Water).
			
			</P>
			
			<P>
		
			<TABLE BORDER CELLSPACING=1 BORDERCOLOR="#000000" CELLPADDING=7 WIDTH=460>
			
			<TR>
			
			   <TD WIDTH="25%" VALIGN="TOP" BGCOLOR="#006600"><B><FONT SIZE=2 COLOR="#ffff00">Spell</B></FONT></TD>
			
			   <TD WIDTH="12%" VALIGN="TOP" BGCOLOR="#006600"><B><FONT SIZE=2 COLOR="#ffff00">Who</B></FONT></TD>
			
			   <TD WIDTH="39%" VALIGN="TOP" BGCOLOR="#006600"><B><FONT SIZE=2 COLOR="#ffff00">Description</B></FONT></TD>
			
			   <TD WIDTH="10%" VALIGN="TOP" BGCOLOR="#006600"><B><FONT SIZE=2 COLOR="#ffff00"><CENTER>Skill<CENTER></B></FONT></TD>
			
			   <TD WIDTH="5%"  VALIGN="TOP" BGCOLOR="#006600"><B><FONT SIZE=2 COLOR="#ffff00"><CENTER>CT<CENTER></B></FONT></TD>
			
			   <TD WIDTH="9%"  VALIGN="TOP" BGCOLOR="#006600"><B><FONT SIZE=2 COLOR="#ffff00"><CENTER>Mana<CENTER></B></FONT></TD>
			
			</TR>
			
			<TR>
			
			   <TD WIDTH="25%" VALIGN="TOP" BGCOLOR="#FFFFCC"><B><FONT SIZE=2 COLOR="#000000">Elementalkin Water</B></FONT></TD>
			
			   <TD WIDTH="12%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000">Self:</B></FONT></TD>
			
			   <TD WIDTH="39%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000">Summons Pet (Needs Malachite)</B></FONT></TD>
			
			   <TD WIDTH="10%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>Con.<CENTER></B></FONT></TD>
			
			   <TD WIDTH="5%"  VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>4</CENTER></FONT></TD>
			
			   <TD WIDTH="9%"  VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>40</CENTER></B></FONT></TD>
			
			</TR>
			
			<TR>
			
			   <TD WIDTH="25%" VALIGN="TOP" BGCOLOR="#FFFFCC"><B><FONT SIZE=2 COLOR="#000000">Elementalkin Earth</B></FONT></TD>
			
			   <TD WIDTH="12%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000">Self:</B></FONT></TD>
			
			   <TD WIDTH="39%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000">Summons Pet (Needs Malachite)</B></FONT></TD>
			
			   <TD WIDTH="10%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>Con.<CENTER></B></FONT></TD>
			
			   <TD WIDTH="5%"  VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>4</CENTER></FONT></TD>
			
			   <TD WIDTH="9%"  VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>40</CENTER></B></FONT></TD>
			
			</TR>
			
			<TR>
			
			   <TD WIDTH="25%" VALIGN="TOP" BGCOLOR="#FFFFCC"><B><FONT SIZE=2 COLOR="#000000">Elementalkin Air</B></FONT></TD>
			
			   <TD WIDTH="12%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000">Self:</B></FONT></TD>
			
			   <TD WIDTH="39%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000">Summons Pet (Needs Malachite)</B></FONT></TD>
			
			   <TD WIDTH="10%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>Con.<CENTER></B></FONT></TD>
			
			   <TD WIDTH="5%"  VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>4</CENTER></FONT></TD>
			
			   <TD WIDTH="9%"  VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>40</CENTER></B></FONT></TD>
			
			</TR>
			
			<TR>
			
			   <TD WIDTH="25%" VALIGN="TOP" BGCOLOR="#FFFFCC"><B><FONT SIZE=2 COLOR="#000000">Elementalkin Fire</B></FONT></TD>
			
			   <TD WIDTH="12%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000">Self:</B></FONT></TD>
			
			   <TD WIDTH="39%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000">Summons Pet (Needs Malachite)</B></FONT></TD>
			
			   <TD WIDTH="10%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>Con.<CENTER></B></FONT></TD>
			
			   <TD WIDTH="5%"  VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>4</CENTER></FONT></TD>
			
			   <TD WIDTH="9%"  VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>40</CENTER></B></FONT></TD>
			
			</TR>
			
			<TR>
			
			   <TD WIDTH="100%" VALIGN="TOP" COLSPAN=6 BGCOLOR="#CCCC99"><B><FONT SIZE=1><P>*Pick one pet spell and buy the others if you want later</B></FONT></TD>
			
			</TR>
			
			<TR>
			
			   <TD WIDTH="25%" VALIGN="TOP" BGCOLOR="#FFFFCC"><B><FONT SIZE=2 COLOR="#000000">Burn</B></FONT></TD>
			
			   <TD WIDTH="12%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000">Target:</B></FONT></TD>
			
			   <TD WIDTH="39%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000">2-12 HP Direct Damage</B></FONT></TD>
			
			   <TD WIDTH="10%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>Evo.<CENTER></B></FONT></TD>
			
			   <TD WIDTH="5%"  VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>1</CENTER></FONT></TD>
			
			   <TD WIDTH="9%"  VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>15</CENTER></B></FONT></TD>
			
			</TR>
			
			<TR>
			
			   <TD WIDTH="25%" VALIGN="TOP" BGCOLOR="#FFFFCC"><B><FONT SIZE=2 COLOR="#000000">Gate</B></FONT></TD>
			
			   <TD WIDTH="12%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000">Self:</B></FONT></TD>
			
			   <TD WIDTH="39%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000">Teleport to home point</B></FONT></TD>
			
			   <TD WIDTH="10%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>Alt.<CENTER></B></FONT></TD>
			
			   <TD WIDTH="5%"  VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>5</CENTER></FONT></TD>
			
			   <TD WIDTH="9%"  VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>70</CENTER></B></FONT></TD>
			
			</TR>
			
			<TR>
			
			   <TD WIDTH="25%" VALIGN="TOP" BGCOLOR="#FFFFCC"><B><FONT SIZE=2 COLOR="#000000">Summon Bandages</B></FONT></TD>
			
			   <TD WIDTH="12%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000">Self:</B></FONT></TD>
			
			   <TD WIDTH="39%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000">Summons level / 2 number of bandages (round down)</B></FONT></TD>
			
			   <TD WIDTH="10%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>Con<CENTER></B></FONT></TD>
			
			   <TD WIDTH="5%"  VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>3</CENTER></FONT></TD>
			
			   <TD WIDTH="9%"  VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>15</CENTER></B></FONT></TD>
			
			</TR>
			
			<TR>
			
			   <TD WIDTH="25%" VALIGN="TOP" BGCOLOR="#FFFFCC"><B><FONT SIZE=2 COLOR="#000000">Summon Wisp</B></FONT></TD>
			
			   <TD WIDTH="12%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000">Self:</B></FONT></TD>
			
			   <TD WIDTH="39%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000">Summons Light (Fixed)<br>(must be in main inventory slot, dissapears on logout)</B></FONT></TD>
			
			   <TD WIDTH="10%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>Con<CENTER></B></FONT></TD>
			
			   <TD WIDTH="5%"  VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>3</CENTER></FONT></TD>
			
			   <TD WIDTH="9%"  VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>30</CENTER></B></FONT></TD>
			
			</TR>
			
			<TR>
			
			   <TD WIDTH="25%" VALIGN="TOP" BGCOLOR="#FFFFCC"><B><FONT SIZE=2 COLOR="#000000">Fire Flux</B></FONT></TD>
			
			   <TD WIDTH="12%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000">Self:</B></FONT></TD>
			
			   <TD WIDTH="39%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000">AE 2-12 HP Radius Damage</B></FONT></TD>
			
			   <TD WIDTH="10%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>Evo.<CENTER></B></FONT></TD>
			
			   <TD WIDTH="5%"  VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>2</CENTER></FONT></TD>
			
			   <TD WIDTH="9%"  VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>23</CENTER></B></FONT></TD>
			
			</TR>
			
			<TR>
			
			   <TD WIDTH="25%" VALIGN="TOP" BGCOLOR="#FFFFCC"><B><FONT SIZE=2 COLOR="#000000">Sense Summoned</B></FONT></TD>
			
			   <TD WIDTH="12%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000">Self:</B></FONT></TD>
			
			   <TD WIDTH="39%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000">Point toward nearest summoned creature</B></FONT></TD>
			
			   <TD WIDTH="10%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>Div.<CENTER></B></FONT></TD>
			
			   <TD WIDTH="5%"  VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>3</CENTER></FONT></TD>
			
			   <TD WIDTH="9%"  VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>5</CENTER></B></FONT></TD>
			
			</TR>
			
			</TABLE>   
								
			</P>
			
			<P>
			
			<B>Spell Notes:</b><BR>
			
			Gate.  Well you will wonder what you ever did with out this.  Especially when
			
			you hit 12 and get Bind Affinity.  I use it to teleport away from a bad scene if
			
			it looks like my pet won't make it and I am really near death, or to save time
			
			when in zone.  It is an instant teleport when you are in the zone you are bound
			
			too.  Like from the entrance to Crushbone to the entrance to Felwith in a
			
			second. :)
			
			</P>
			
			<P>
			
			<B>Summon Bandages</B>:  Now this is very useful.  Get this one as early as you can
			
			afford it (after your primary spells).  Practice bind wound often.  Bandage
			
			other players that have gotten below 50% health (works only to 50% health if
			
			you did not already know that), even if you are not in a group.  Magicians are
			
			the only class that Bind Wound is even an option for.  Bandages are just too
			
			expensive to buy and practice.  I wish I had started practicing with bind wound
			
			much sooner.  I am currently at only 59 at level 18 and could have been in the
			
			high 60's.  It really is helpful when you get near death, and you want to get up
			
			to a point where you move faster than a crawl fast and there aren't any healers
			
			around.  Currently I can heal from 9 hp to 155+ with 6 to 7 bandages in a very
			
			short time (when my current max HP was at 319, too new to 18 and have not had to
			
			try it yet!).  That means I am doing about 22-25 hp per bandage.  It should be
			
			in the 30 to 40 hp or higher range when I am in the high 90's (I am speculating
			
			here).  Pretty good use of stored mana, if you ask me.  This is also good when
			
			you are in a group and you want to conserve the Healer's mana.  Heal up the tank
			
			to 50% and let the Cleric / Ranger / Druid etc bring them to 90%.  (A grouping
			
			side note , good healers know that they don't need to "top off" a tank, and
			
			should just get them up to a safe level that they can heal on their own, while
			
			the healer meditates.  This increases the groups effectiveness and minimizes
			
			their down time).
			
			</P>
			
			<P>
			
			<B>Summon Wisp</B> is ok if you don't have Infra Vision or Ultra Vision.  It is like a
			
			permanent torch and will hold you until you get your "glowing" weapon spells.
			
			The Staff of Tracing and Staff of Warding weapons cast light and remove the need
			
			for the Wisp Light source, unless you choose to use your Dagger or Fang or other
			
			non glowing or piercing weapons.  I actually have a Magic Torch that is AC 3, +7
			
			Charisma that I carry around I got off a named MOB in Lavastorm.  Others carry
			
			the Skull of Jhen'Tra (sp?) which gives good stats, an you may want the wisp then
			
			too.
			
			</P>
			
			<P>
			
			<B>Fire Flux</B> I found to be of limited use.  If I remember correctly it is a PBAE
			
			(Point Blank Area Effect), centered on YOU not your target.   Which means that
			
			the only MOBS affected are those that are attacking you directly..  Not great
			
			since you may not even get a shot off because two mobs are hitting you, not to
			
			mention the chance of fizzles.  The Rain of xxxx spells are Target centered AE
			
			spells, that make much better sense for a mage.  I used my Fire Flux spell maybe
			
			twice.
			
			</P>
			
			<P>
			
			<B>Sense Summoned</B>.  Hmmm, another in the set of useless mage spells.  It basically
			
			points you in the direction of the NEAREST summoned creature, be it yours,
			
			another mage's or a summoned MOB.  Not very useful.  Another one that clutters
			
			up my spell book that I used once or twice before I found out how useless it
			
			was.
			
			</P></FONT>
			
			<H4>
			
			<BR>
			
			RANK 3, Levels 8-11</H4><FONT face=Arial size=2>
			
			<P>
			
			Well nothing really new here, just better spells! This is the level that you
			
			start to get the really useful spells that will be useful for a long time.
			
			</P>
			
			<P>
			
			<TABLE BORDER CELLSPACING=1 BORDERCOLOR="#000000" CELLPADDING=7 WIDTH=460>
			
			<TR>
			
			   <TD WIDTH="25%" VALIGN="TOP" BGCOLOR="#006600"><B><FONT SIZE=2 COLOR="#ffff00">Spell</B></FONT></TD>
			
			   <TD WIDTH="12%" VALIGN="TOP" BGCOLOR="#006600"><B><FONT SIZE=2 COLOR="#ffff00">Who</B></FONT></TD>
			
			   <TD WIDTH="39%" VALIGN="TOP" BGCOLOR="#006600"><B><FONT SIZE=2 COLOR="#ffff00">Description</B></FONT></TD>
			
			   <TD WIDTH="10%" VALIGN="TOP" BGCOLOR="#006600"><B><FONT SIZE=2 COLOR="#ffff00"><CENTER>Skill<CENTER></B></FONT></TD>
			
			   <TD WIDTH="5%"  VALIGN="TOP" BGCOLOR="#006600"><B><FONT SIZE=2 COLOR="#ffff00"><CENTER>CT<CENTER></B></FONT></TD>
			
			   <TD WIDTH="9%"  VALIGN="TOP" BGCOLOR="#006600"><B><FONT SIZE=2 COLOR="#ffff00"><CENTER>Mana<CENTER></B></FONT></TD>
			
			</TR>
			
			<TR>
			
			   <TD WIDTH="25%" VALIGN="TOP" BGCOLOR="#FFFFCC"><B><FONT SIZE=2 COLOR="#000000">Elementaling Water</B></FONT></TD>
			
			   <TD WIDTH="12%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000">Self:</B></FONT></TD>
			
			   <TD WIDTH="39%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000">Summons Pet (Needs Malachite)</B></FONT></TD>
			
			   <TD WIDTH="10%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>Con.<CENTER></B></FONT></TD>
			
			   <TD WIDTH="5%"  VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>5</CENTER></FONT></TD>
			
			   <TD WIDTH="9%"  VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>80</CENTER></B></FONT></TD>
			
			</TR>
			
			<TR>
			
			   <TD WIDTH="25%" VALIGN="TOP" BGCOLOR="#FFFFCC"><B><FONT SIZE=2 COLOR="#000000">Elementaling Earth</B></FONT></TD>
			
			   <TD WIDTH="12%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000">Self:</B></FONT></TD>
			
			   <TD WIDTH="39%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000">Summons Pet (Needs Malachite)</B></FONT></TD>
			
			   <TD WIDTH="10%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>Con.<CENTER></B></FONT></TD>
			
			   <TD WIDTH="5%"  VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>5</CENTER></FONT></TD>
			
			   <TD WIDTH="9%"  VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>80</CENTER></B></FONT></TD>
			
			</TR>
			
			<TR>
			
			   <TD WIDTH="25%" VALIGN="TOP" BGCOLOR="#FFFFCC"><B><FONT SIZE=2 COLOR="#000000">Elementaling Air</B></FONT></TD>
			
			   <TD WIDTH="12%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000">Self:</B></FONT></TD>
			
			   <TD WIDTH="39%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000">Summons Pet (Needs Malachite)</B></FONT></TD>
			
			   <TD WIDTH="10%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>Con.<CENTER></B></FONT></TD>
			
			   <TD WIDTH="5%"  VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>5</CENTER></FONT></TD>
			
			   <TD WIDTH="9%"  VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>80</CENTER></B></FONT></TD>
			
			</TR>
			
			<TR>
			
			   <TD WIDTH="25%" VALIGN="TOP" BGCOLOR="#FFFFCC"><B><FONT SIZE=2 COLOR="#000000">Elementaling Fire</B></FONT></TD>
			
			   <TD WIDTH="12%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000">Self:</B></FONT></TD>
			
			   <TD WIDTH="39%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000">Summons Pet (Needs Malachite)</B></FONT></TD>
			
			   <TD WIDTH="10%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>Con.<CENTER></B></FONT></TD>
			
			   <TD WIDTH="5%"  VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>5</CENTER></FONT></TD>
			
			   <TD WIDTH="9%"  VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>80</CENTER></B></FONT></TD>
			
			</TR>
			
			<TR>
			
			   <TD WIDTH="100%" VALIGN="TOP" COLSPAN=6 BGCOLOR="#CCCC99"><B><FONT SIZE=1><P>*Pick one pet spell and buy the others if you want later</B></FONT></TD>
			
			</TR>
			
			<TR>
			
			   <TD WIDTH="25%" VALIGN="TOP" BGCOLOR="#FFFFCC"><B><FONT SIZE=2 COLOR="#000000">Shock of Blades</B></FONT></TD>
			
			   <TD WIDTH="12%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000">Target:</B></FONT></TD>
			
			   <TD WIDTH="39%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000">23 + 1/level HP Direct Damage</B></FONT></TD>
			
			   <TD WIDTH="10%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>Con.<CENTER></B></FONT></TD>
			
			   <TD WIDTH="5%"  VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>2</CENTER></FONT></TD>
			
			   <TD WIDTH="9%"  VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>30</CENTER></B></FONT></TD>
			
			</TR>
			
			<TR>
			
			   <TD WIDTH="25%" VALIGN="TOP" BGCOLOR="#FFFFCC"><B><FONT SIZE=2 COLOR="#000000">Lesser Shielding</B></FONT></TD>
			
			   <TD WIDTH="12%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000">Self:</B></FONT></TD>
			
			   <TD WIDTH="39%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000">+AC &amp; Max HP &amp; MR</B></FONT></TD>
			
			   <TD WIDTH="10%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>Abj.<CENTER></B></FONT></TD>
			
			   <TD WIDTH="5%"  VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>3</CENTER></FONT></TD>
			
			   <TD WIDTH="9%"  VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>25</CENTER></B></FONT></TD>
			
			</TR>
			
			<TR>
			
			   <TD WIDTH="25%" VALIGN="TOP" BGCOLOR="#FFFFCC"><B><FONT SIZE=2 COLOR="#000000">Invisibility</B></FONT></TD>
			
			   <TD WIDTH="12%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000">Target:</B></FONT></TD>
			
			   <TD WIDTH="39%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000">Turn Target Invisible</B></FONT></TD>
			
			   <TD WIDTH="10%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>Div.<CENTER></B></FONT></TD>
			
			   <TD WIDTH="5%"  VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>3</CENTER></FONT></TD>
			
			   <TD WIDTH="9%"  VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>30</CENTER></B></FONT></TD>
			
			</TR>
			
			<TR>
			
			   <TD WIDTH="25%" VALIGN="TOP" BGCOLOR="#FFFFCC"><B><FONT SIZE=2 COLOR="#000000">Shield of Fire</B></FONT></TD>
			
			   <TD WIDTH="12%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000">Target:</B></FONT></TD>
			
			   <TD WIDTH="39%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000">5-8 HP Damage Shield</B></FONT></TD>
			
			   <TD WIDTH="10%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>Abj.<CENTER></B></FONT></TD>
			
			   <TD WIDTH="5%"  VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>4</CENTER></FONT></TD>
			
			   <TD WIDTH="9%"  VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>40</CENTER></B></FONT></TD>
			
			</TR>
			
			<TR>
			
			   <TD WIDTH="25%" VALIGN="TOP" BGCOLOR="#FFFFCC"><B><FONT SIZE=2 COLOR="#000000">Dimensional Pocket</B></FONT></TD>
			
			   <TD WIDTH="12%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000">Self:</B></FONT></TD>
			
			   <TD WIDTH="39%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000">Summon 4 Slot Bag</B></FONT></TD>
			
			   <TD WIDTH="10%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>Con.<CENTER></B></FONT></TD>
			
			   <TD WIDTH="5%"  VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>4</CENTER></FONT></TD>
			
			   <TD WIDTH="9%"  VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>40</CENTER></B></FONT></TD>
			
			</TR>
			
			<TR>
			
			   <TD WIDTH="25%" VALIGN="TOP" BGCOLOR="#FFFFCC"><B><FONT SIZE=2 COLOR="#000000">Flame Bolt</B></FONT></TD>
			
			   <TD WIDTH="12%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000">Target:</B></FONT></TD>
			
			   <TD WIDTH="39%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000">Direct Damage Bolt</B></FONT></TD>
			
			   <TD WIDTH="10%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>Evo.<CENTER></B></FONT></TD>
			
			   <TD WIDTH="5%"  VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>2</CENTER></FONT></TD>
			
			   <TD WIDTH="9%"  VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>40</CENTER></B></FONT></TD>
			
			</TR>
			
			<TR>
			
			   <TD WIDTH="25%" VALIGN="TOP" BGCOLOR="#FFFFCC"><B><FONT SIZE=2 COLOR="#000000">Eye of Zomm</B></FONT></TD>
			
			   <TD WIDTH="12%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000">Self:</B></FONT></TD>
			
			   <TD WIDTH="39%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000">Moveable see through eye</B></FONT></TD>
			
			   <TD WIDTH="10%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>Con.<CENTER></B></FONT></TD>
			
			   <TD WIDTH="5%"  VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>3</CENTER></FONT></TD>
			
			   <TD WIDTH="9%"  VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>30</CENTER></B></FONT></TD>
			
			</TR>
			
			</TABLE>		
			
			</P>
			
			
			
			<P>
			
			<B>Shock of Blades</B> will be your primary burn for a long time.  Even at my level
			
			(since I have spent most of my time in Lavastorm, it is my main "attention
			
			getter").  It is rarely resisted, and if it is, it still does damage.  The "blade"
			
			spells are by far the most versatile DD spells in the Magician's bag of tricks, 
			
			as they are much harder to resist (conjuration spells not evocation).
			
			</P>
			
			<P>
			
			<B>Invisibility</B> is a god send for exploration.  It is a requirement for me to get
			
			to Lavastorm (I am a High Elf, and Lavastorm is on the north side of the
			
			Nektlos Forest, where the Guards will KOS me) I have used this to explore most
			
			of Norrath.  I have been to almost every zone, and the majority of dungeons with
			
			this one.  Most of level 17 was spent exploring Antontica.  I did not visit
			
			every zone, but I would say that I covered about 89% of them.  The dungeons I
			
			visited were: Permafrost Dungeon, Blackburrow (couldn't avoid that when getting
			
			to Everfrost Peaks and Permafrost :), Infected Paw, Upper Guk, Soluseks Eye (A
			
			and B), Nagena, Beholder's Maze, Befallen. I also visited Crush Bone (level 8),
			
			Dagnor's Cauldron and Unrest (level 11). So you can see that Invisible is really
			
			useful for exploration.
			
			</P>
			
			<P>
			
			<B>Shield of fire</B> is a must.  Especially solo.  I refer to it in other sections of
			
			this guide, so won't go into it much here.
			
			</P>
			
			<P>
			
			<B>Dimensional Pocket</B>.  This summons a 4 slot bag that disappears when you log out.
			
			It has a very cool property though.  Anything placed in this bag becomes
			
			effectively weightless.  Great when you get chunks, or blocks of ore, or heavy
			
			weapons or armor.  Just be careful.  Don't expect anything to be in your
			
			inventory that was in the pocket if you go link dead or log out.  But it is
			
			great if you are encumbered and want to move out and sell the stuff.  Stuff that
			
			normally would be left can now go with you.  I usually put my summoned food and
			
			bandages in here, so no loss there.  If I need to reduce weight, I plop just
			
			enough in there to un-encumber myself.  This spell is hard to find.  As far as I
			
			know it is only in Erudin, Ak'Anon and Neriak.  But they, without notice, change
			
			spell locations for uncommon and rare items, so this may not be true TODAY.   I
			
			had a dark elf buy me mine from Neriak.
			
			</P>
			
			<P>
			
			<B>Flame Bolt</B>.  Well, hmm.  Never used it.  I really don't care for the bolt
			
			spells.  I may later on. I accidentally bough my Level 20-23 Bolt of Flame
			
			spell. One of those I *thought* I clicked the right spell when I bought it.
			
			Anyway, They are line of sight and can miss.  They also consume lots of mana to
			
			throw away if you miss.  However, they are great when they DO hit, or so I hear.
			
			<BR>
			
			Update: One fellow Mage, that read this guide mentioned that this is really good long distance "fetching spell".  If the terrain permitts, you can hit a target from a long way off and cast another dd spell as it is running towards you.  Now that really seems cool.  I can't wait to try this tactic in the karanas somewhere! :P
			
			</P>
			
			<P>
			
			<B>Eye of Zomm</B> is really fun to use.  You can explore areas that you normally would
			
			have to do invisible, or can't go (like past zone boundaries. heh heh).  You can
			
			also cast "through" the eye, but unless they fixed this recently, you can only
			
			cast against things that are within range of your real body, so is limited in
			
			this capacity..  However if you are in range, but around a corner, this is good.
			
			The disadvantage is that you CANNOT cast this spell while you have a pet.  It
			
			did not used to be this way, but recently (about a month and a 1/2 ago) they
			
			introduced this.  Really reduced the effectiveness of this spell to near zero.
			
			Humph.
			
			</P></FONT>
			
			<H4>
			
			<BR>
			
			RANK 4, Levels 12-15</H4><FONT face=Arial size=2>
			
			
			
			<P>
			
			<TABLE BORDER CELLSPACING=1 BORDERCOLOR="#000000" CELLPADDING=7 WIDTH=460>
			
			<TR>
			
			   <TD WIDTH="25%" VALIGN="TOP" BGCOLOR="#006600"><B><FONT SIZE=2 COLOR="#ffff00">Spell</B></FONT></TD>
			
			   <TD WIDTH="12%" VALIGN="TOP" BGCOLOR="#006600"><B><FONT SIZE=2 COLOR="#ffff00">Who</B></FONT></TD>
			
			   <TD WIDTH="39%" VALIGN="TOP" BGCOLOR="#006600"><B><FONT SIZE=2 COLOR="#ffff00">Description</B></FONT></TD>
			
			   <TD WIDTH="10%" VALIGN="TOP" BGCOLOR="#006600"><B><FONT SIZE=2 COLOR="#ffff00"><CENTER>Skill<CENTER></B></FONT></TD>
			
			   <TD WIDTH="5%"  VALIGN="TOP" BGCOLOR="#006600"><B><FONT SIZE=2 COLOR="#ffff00"><CENTER>CT<CENTER></B></FONT></TD>
			
			   <TD WIDTH="9%"  VALIGN="TOP" BGCOLOR="#006600"><B><FONT SIZE=2 COLOR="#ffff00"><CENTER>Mana<CENTER></B></FONT></TD>
			
			</TR>
			
			<TR>
			
			   <TD WIDTH="25%" VALIGN="TOP" BGCOLOR="#FFFFCC"><B><FONT SIZE=2 COLOR="#000000">Elemental Water</B></FONT></TD>
			
			   <TD WIDTH="12%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000">Self:</B></FONT></TD>
			
			   <TD WIDTH="39%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000">Summons Pet (lapis lazuli)</B></FONT></TD>
			
			   <TD WIDTH="10%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>Con.<CENTER></B></FONT></TD>
			
			   <TD WIDTH="5%"  VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>6</CENTER></FONT></TD>
			
			   <TD WIDTH="9%"  VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>120</CENTER></B></FONT></TD>
			
			</TR>
			
			<TR>
			
			   <TD WIDTH="25%" VALIGN="TOP" BGCOLOR="#FFFFCC"><B><FONT SIZE=2 COLOR="#000000">Elemental Earth</B></FONT></TD>
			
			   <TD WIDTH="12%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000">Self:</B></FONT></TD>
			
			   <TD WIDTH="39%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000">Summons Pet (lapis lazuli)</B></FONT></TD>
			
			   <TD WIDTH="10%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>Con.<CENTER></B></FONT></TD>
			
			   <TD WIDTH="5%"  VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>6</CENTER></FONT></TD>
			
			   <TD WIDTH="9%"  VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>120</CENTER></B></FONT></TD>
			
			</TR>
			
			<TR>
			
			   <TD WIDTH="25%" VALIGN="TOP" BGCOLOR="#FFFFCC"><B><FONT SIZE=2 COLOR="#000000">Elemental Air</B></FONT></TD>
			
			   <TD WIDTH="12%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000">Self:</B></FONT></TD>
			
			   <TD WIDTH="39%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000">Summons Pet (lapis lazuli)</B></FONT></TD>
			
			   <TD WIDTH="10%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>Con.<CENTER></B></FONT></TD>
			
			   <TD WIDTH="5%"  VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>6</CENTER></FONT></TD>
			
			   <TD WIDTH="9%"  VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>120</CENTER></B></FONT></TD>
			
			</TR>
			
			<TR>
			
			   <TD WIDTH="25%" VALIGN="TOP" BGCOLOR="#FFFFCC"><B><FONT SIZE=2 COLOR="#000000">Elemental Fire</B></FONT></TD>
			
			   <TD WIDTH="12%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000">Self:</B></FONT></TD>
			
			   <TD WIDTH="39%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000">Summons Pet (lapis lazuli)</B></FONT></TD>
			
			   <TD WIDTH="10%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>Con.<CENTER></B></FONT></TD>
			
			   <TD WIDTH="5%"  VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>6</CENTER></FONT></TD>
			
			   <TD WIDTH="9%"  VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>120</CENTER></B></FONT></TD>
			
			</TR>
			
			<TR>
			
			   <TD WIDTH="100%" VALIGN="TOP" COLSPAN=6 BGCOLOR="#CCCC99"><B><FONT SIZE=1><P>*Pick one pet spell and buy the others if you want later</B></FONT></TD>
			
			</TR>
			
			<TR>
			
			   <TD WIDTH="25%" VALIGN="TOP" BGCOLOR="#FFFFCC"><B><FONT SIZE=2 COLOR="#000000">Bind Affinity</B></FONT></TD>
			
			   <TD WIDTH="12%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000">Target:</B></FONT></TD>
			
			   <TD WIDTH="39%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000">Set home point location (target must be in your group)</B></FONT></TD>
			
			   <TD WIDTH="10%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>Alt.<CENTER></B></FONT></TD>
			
			   <TD WIDTH="5%"  VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>6</CENTER></FONT></TD>
			
			   <TD WIDTH="9%"  VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>100</CENTER></B></FONT></TD>
			
			</TR>
			
			<TR>
			
			   <TD WIDTH="25%" VALIGN="TOP" BGCOLOR="#FFFFCC"><B><FONT SIZE=2 COLOR="#000000">Summon Fang</B></FONT></TD>
			
			   <TD WIDTH="12%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000">Self:</B></FONT></TD>
			
			   <TD WIDTH="39%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000">Summon Weapon (damage 5/delay 26)<BR>(disappears at logout, was Summon Blade)</B></FONT></TD>
			
			   <TD WIDTH="10%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>Con.<CENTER></B></FONT></TD>
			
			   <TD WIDTH="5%"  VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>4</CENTER></FONT></TD>
			
			   <TD WIDTH="9%"  VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>40</CENTER></B></FONT></TD>
			
			</TR>
			
			<TR>
			
			   <TD WIDTH="25%" VALIGN="TOP" BGCOLOR="#FFFFCC"><B><FONT SIZE=2 COLOR="#000000">Burnout</B></FONT></TD>
			
			   <TD WIDTH="12%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000">Pet:</B></FONT></TD>
			
			   <TD WIDTH="39%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000">Inc Pet's HP, AC, &amp; STR (Lowers HP regen)</B></FONT></TD>
			
			   <TD WIDTH="10%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>Alt.<CENTER></B></FONT></TD>
			
			   <TD WIDTH="5%"  VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>2</CENTER></FONT></TD>
			
			   <TD WIDTH="9%"  VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>30</CENTER></B></FONT></TD>
			
			</TR>
			
			<TR>
			
			   <TD WIDTH="25%" VALIGN="TOP" BGCOLOR="#FFFFCC"><B><FONT SIZE=2 COLOR="#000000">Cancel Magic</B></FONT></TD>
			
			   <TD WIDTH="12%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000">Target:</B></FONT></TD>
			
			   <TD WIDTH="39%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000">Remove magic effect</B></FONT></TD>
			
			   <TD WIDTH="10%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>Abj.<CENTER></B></FONT></TD>
			
			   <TD WIDTH="5%"  VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>2</CENTER></FONT></TD>
			
			   <TD WIDTH="9%"  VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>30</CENTER></B></FONT></TD>
			
			</TR>
			
			<TR>
			
			   <TD WIDTH="25%" VALIGN="TOP" BGCOLOR="#FFFFCC"><B><FONT SIZE=2 COLOR="#000000">Ward Summoned</B></FONT></TD>
			
			   <TD WIDTH="12%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000">Target:</B></FONT></TD>
			
			   <TD WIDTH="39%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000">30-42 HP Damage<BR>(Summoned Creatures Only)</B></FONT></TD>
			
			   <TD WIDTH="10%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>Evo.<CENTER></B></FONT></TD>
			
			   <TD WIDTH="5%"  VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>3</CENTER></FONT></TD>
			
			   <TD WIDTH="9%"  VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>30</CENTER></B></FONT></TD>
			
			</TR>
			
			<TR>
			
			   <TD WIDTH="25%" VALIGN="TOP" BGCOLOR="#FFFFCC"><B><FONT SIZE=2 COLOR="#000000">Rain of Blades</B></FONT></TD>
			
			   <TD WIDTH="12%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000">Target:</B></FONT></TD>
			
			   <TD WIDTH="39%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000">20-26 HP AE Radius Damage</B></FONT></TD>
			
			   <TD WIDTH="10%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>Evo.<CENTER></B></FONT></TD>
			
			   <TD WIDTH="5%"  VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>4</CENTER></FONT></TD>
			
			   <TD WIDTH="9%"  VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>62</CENTER></B></FONT></TD>
			
			</TR>
			
			<TR>
			
			   <TD WIDTH="25%" VALIGN="TOP" BGCOLOR="#FFFFCC"><B><FONT SIZE=2 COLOR="#000000">Column of Fire</B></FONT></TD>
			
			   <TD WIDTH="12%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000">Target:</B></FONT></TD>
			
			   <TD WIDTH="39%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000">AE Radius Damage</B></FONT></TD>
			
			   <TD WIDTH="10%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>Evo.<CENTER></B></FONT></TD>
			
			   <TD WIDTH="5%"  VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>3</CENTER></FONT></TD>
			
			   <TD WIDTH="9%"  VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>65</CENTER></B></FONT></TD>
			
			</TR>
			
			</TABLE>
						
			</P>
			
			<P>
			
			<B>Bind Affinity</B>.  Do I really need to detail this? :)
			
			</P>
			
			<P>
			
			<B>Summon Fang</B>.  This is hard to find.  You need to go to Ak'Anon or Erudin for
			
			this weapon spell.  It may be in Neriak, but I don't know.  I got mine in
			
			Erudin.  Ask about, because, as I have said earlier, Verant moves spells or
			
			entire vendors without notice.
			
			</P>
			
			<P>
			
			<B>Cancel Magic</B> is great when you get some nasty caster casting spells on YOU. You
			
			can remove the affect from you or a fellow group member.  Also good for removing
			
			the burnout spell from your pet (burnout is a permanent spell on your pet until
			
			it dies or you remove it).  Another great trick is one I adopted in Lavastorm.
			
			I am fighting a Fire Elemental, so what I do to get it's attention (instead of a
			
			burn spell) is cast Cancel Magic to remove it's fire shield, then sick my pet
			
			which has fire shield already cast upon it.  I have just turned the tables on
			
			the fire elemental.  My pet hits it, does not get burned, fire elemental hits my
			
			pet and gets burned!  Great fun.
			
			</P>
			
			<P>
			
			<B>Ward Summoned</B> will only work against summoned creatures (elementals, lava
			
			crawlers, Fire Imps etc).  I have only seen Earth elementals in the open in
			
			Steamfont.  Fire Elementals, Lava Crawlers and Fire Imps are in Lavastorm.  It
			
			is a great one for these guys.  However the Expulse summoned that the Druids get
			
			at level 14 is even better.  Does 90+ damage.  We get that only at level 20.
			
			</P>
			
			<P>
			
			<B>Rain of Blades</B> I prefer over the Column of Fire.  The effect is supposed to be 2
			
			or three rounds of 20-26 damage.  I have only ever seen one round.  It is better
			
			than the Flux range of spells as it is an AE with the target as the center, so
			
			if your and your pet are getting hammered, stand on top of your pet and cast
			
			this one on your target...  Again any of the AE spells are not really useful
			
			except when grouping and your tank is being attacked by multiple targets.  Your
			
			pet can't "peg" multiple targets like PC tanks can, so is pretty useless to
			
			Magicians.
			
			</P>
			
			<P>
			
			<B>Column of Fire</B>.  See Rain of Blades. Never have used it much...  Waste of money
			
			for me.
			
			</P></FONT>
			
			<H4>
			
			<BR>
			
			RANK 5, Levels 16-19 (ok I am guessing on the L19 
			
			parts :)</H4><FONT face=Arial size=2>
			
			
			
			<P>
			
			<TABLE BORDER CELLSPACING=1 BORDERCOLOR="#000000" CELLPADDING=7 WIDTH=460>
			
			<TR>
			
			   <TD WIDTH="28%" VALIGN="TOP" BGCOLOR="#006600"><B><FONT SIZE=2 COLOR="#ffff00">Spell</B></FONT></TD>
			
			   <TD WIDTH="12%" VALIGN="TOP" BGCOLOR="#006600"><B><FONT SIZE=2 COLOR="#ffff00">Who</B></FONT></TD>
			
			   <TD WIDTH="34%" VALIGN="TOP" BGCOLOR="#006600"><B><FONT SIZE=2 COLOR="#ffff00">Description</B></FONT></TD>
			
			   <TD WIDTH="10%" VALIGN="TOP" BGCOLOR="#006600"><B><FONT SIZE=2 COLOR="#ffff00"><CENTER>Skill<CENTER></B></FONT></TD>
			
			   <TD WIDTH="5%"  VALIGN="TOP" BGCOLOR="#006600"><B><FONT SIZE=2 COLOR="#ffff00"><CENTER>CT<CENTER></B></FONT></TD>
			
			   <TD WIDTH="9%"  VALIGN="TOP" BGCOLOR="#006600"><B><FONT SIZE=2 COLOR="#ffff00"><CENTER>Mana<CENTER></B></FONT></TD>
			
			</TR>
			
			<TR>
			
			   <TD WIDTH="28%" VALIGN="TOP" BGCOLOR="#FFFFCC"><B><FONT SIZE=2 COLOR="#000000">Minor Summoning Water</B></FONT></TD>
			
			   <TD WIDTH="12%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000">Self:</B></FONT></TD>
			
			   <TD WIDTH="34%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000">Summons Pet (lapis lazuli)</B></FONT></TD>
			
			   <TD WIDTH="10%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>Con.<CENTER></B></FONT></TD>
			
			   <TD WIDTH="5%"  VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>6</CENTER></FONT></TD>
			
			   <TD WIDTH="9%"  VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>160</CENTER></B></FONT></TD>
			
			</TR>
			
			<TR>
			
			   <TD WIDTH="28%" VALIGN="TOP" BGCOLOR="#FFFFCC"><B><FONT SIZE=2 COLOR="#000000">Minor Summoning Earth</B></FONT></TD>
			
			   <TD WIDTH="12%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000">Self:</B></FONT></TD>
			
			   <TD WIDTH="34%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000">Summons Pet (lapis lazuli)</B></FONT></TD>
			
			   <TD WIDTH="10%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>Con.<CENTER></B></FONT></TD>
			
			   <TD WIDTH="5%"  VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>6</CENTER></FONT></TD>
			
			   <TD WIDTH="9%"  VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>160</CENTER></B></FONT></TD>
			
			</TR>
			
			<TR>
			
			   <TD WIDTH="28%" VALIGN="TOP" BGCOLOR="#FFFFCC"><B><FONT SIZE=2 COLOR="#000000">Minor Summoning Air</B></FONT></TD>
			
			   <TD WIDTH="12%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000">Self:</B></FONT></TD>
			
			   <TD WIDTH="34%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000">Summons Pet (lapis lazuli)</B></FONT></TD>
			
			   <TD WIDTH="10%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>Con.<CENTER></B></FONT></TD>
			
			   <TD WIDTH="5%"  VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>6</CENTER></FONT></TD>
			
			   <TD WIDTH="9%"  VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>160</CENTER></B></FONT></TD>
			
			</TR>
			
			<TR>
			
			   <TD WIDTH="28%" VALIGN="TOP" BGCOLOR="#FFFFCC"><B><FONT SIZE=2 COLOR="#000000">Minor Summoning Fire</B></FONT></TD>
			
			   <TD WIDTH="12%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000">Self:</B></FONT></TD>
			
			   <TD WIDTH="34%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000">Summons Pet (lapis lazuli)</B></FONT></TD>
			
			   <TD WIDTH="10%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>Con.<CENTER></B></FONT></TD>
			
			   <TD WIDTH="5%"  VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>6</CENTER></FONT></TD>
			
			   <TD WIDTH="9%"  VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>160</CENTER></B></FONT></TD>
			
			</TR>
			
			<TR>
			
			   <TD WIDTH="100%" VALIGN="TOP" COLSPAN=6 BGCOLOR="#CCCC99"><B><FONT SIZE=1><P>*Pick one pet spell and buy the others if you want later</B></FONT></TD>
			
			</TR>
			
			<TR>
			
			   <TD WIDTH="28%" VALIGN="TOP" BGCOLOR="#FFFFCC"><B><FONT SIZE=2 COLOR="#000000">Shielding</B></FONT></TD>
			
			   <TD WIDTH="12%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000">Self:</B></FONT></TD>
			
			   <TD WIDTH="34%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000">+AC, + Max HP, &amp; +MR</B></FONT></TD>
			
			   <TD WIDTH="10%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>Abj.<CENTER></B></FONT></TD>
			
			   <TD WIDTH="5%"  VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>4</CENTER></FONT></TD>
			
			   <TD WIDTH="9%"  VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>50</CENTER></B></FONT></TD>
			
			</TR>
			
			<TR>
			
			   <TD WIDTH="28%" VALIGN="TOP" BGCOLOR="#FFFFCC"><B><FONT SIZE=2 COLOR="#000000">Shock of Flame</B></FONT></TD>
			
			   <TD WIDTH="12%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000">Target:</B></FONT></TD>
			
			   <TD WIDTH="34%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000">75 + 1/level HP Direct Damage</B></FONT></TD>
			
			   <TD WIDTH="10%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>Evo.<CENTER></B></FONT></TD>
			
			   <TD WIDTH="5%"  VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>3</CENTER></FONT></TD>
			
			   <TD WIDTH="9%"  VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>70</CENTER></B></FONT></TD>
			
			</TR>
			
			<TR>
			
			   <TD WIDTH="28%" VALIGN="TOP" BGCOLOR="#FFFFCC"><B><FONT SIZE=2 COLOR="#000000">See Invisible</B></FONT></TD>
			
			   <TD WIDTH="12%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000">Self:</B></FONT></TD>
			
			   <TD WIDTH="34%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000">See Invisible creatures</B></FONT></TD>
			
			   <TD WIDTH="10%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>Div.<CENTER></B></FONT></TD>
			
			   <TD WIDTH="5%"  VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>3</CENTER></FONT></TD>
			
			   <TD WIDTH="9%"  VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>25</CENTER></B></FONT></TD>
			
			</TR>
			
			<TR>
			
			   <TD WIDTH="28%" VALIGN="TOP" BGCOLOR="#FFFFCC"><B><FONT SIZE=2 COLOR="#000000">Phantom Leather</B></FONT></TD>
			
			   <TD WIDTH="12%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000">Self:</B></FONT></TD>
			
			   <TD WIDTH="34%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000">Add to AC stackable with shield<BR>(Needs Cat's Eye Agate)</B></FONT></TD>
			
			   <TD WIDTH="10%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>Abj.<CENTER></B></FONT></TD>
			
			   <TD WIDTH="5%"  VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>4</CENTER></FONT></TD>
			
			   <TD WIDTH="9%"  VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>60</CENTER></B></FONT></TD>
			
			</TR>
			
			<TR>
			
			   <TD WIDTH="28%" VALIGN="TOP" BGCOLOR="#FFFFCC"><B><FONT SIZE=2 COLOR="#000000">Summon Heatstone</B></FONT></TD>
			
			   <TD WIDTH="12%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000">Self:</B></FONT></TD>
			
			   <TD WIDTH="34%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000">Summon Infra Vision Stone</B></FONT></TD>
			
			   <TD WIDTH="10%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>Con.<CENTER></B></FONT></TD>
			
			   <TD WIDTH="5%"  VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>5</CENTER></FONT></TD>
			
			   <TD WIDTH="9%"  VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>40</CENTER></B></FONT></TD>
			
			</TR>
			
			<TR>
			
			   <TD WIDTH="28%" VALIGN="TOP" BGCOLOR="#FFFFCC"><B><FONT SIZE=2 COLOR="#000000">Summon Throwing Dagger</B></FONT></TD>
			
			   <TD WIDTH="12%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000">Self:</B></FONT></TD>
			
			   <TD WIDTH="34%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000">Summon Range Weapon (20) (disappears on logout)</B></FONT></TD>
			
			   <TD WIDTH="10%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>Con.<CENTER></B></FONT></TD>
			
			   <TD WIDTH="5%"  VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>4</CENTER></FONT></TD>
			
			   <TD WIDTH="9%"  VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>20</CENTER></B></FONT></TD>
			
			</TR>
			
			<TR>
			
			   <TD WIDTH="28%" VALIGN="TOP" BGCOLOR="#FFFFCC"><B><FONT SIZE=2 COLOR="#000000">Identify</B></FONT></TD>
			
			   <TD WIDTH="12%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000">Target:</B></FONT></TD>
			
			   <TD WIDTH="34%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000">Identify Object</B></FONT></TD>
			
			   <TD WIDTH="10%" VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>Div.<CENTER></B></FONT></TD>
			
			   <TD WIDTH="5%"  VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>4</CENTER></FONT></TD>
			
			   <TD WIDTH="9%"  VALIGN="TOP" BGCOLOR="#CCCC99"><B><FONT SIZE=2 COLOR="#000000"><CENTER>50</CENTER></B></FONT></TD>
			
			</TR>
			
			</TABLE>   
			
			</P>
			
			<P><STRONG>Shielding</STRONG>
			
			.  Finally, your next level of Shielding!  Makes a huge difference.
			
			</P>
			
			<P><STRONG>Shock of Flame</STRONG>
			
			  ,   At level 17 this spell was doing 92 Points of damage. Have not
			
			tried it again at 18, as I am in Lavastorm and most creatures resist it anyway.
			
			Great burn spell.  Nice to be able to hit for some serious hp damage.  Also a
			
			fairly reasonable cast time.  Not as good as Shock of blades, but it does almost
			
			3 times the damage, if it is not resisted at all.
			
			</P>
			
			<P><STRONG>See Invisible</STRONG>
			
			 .  This is of limited (but in its limitation is great) use.  You
			
			have no indication of which objects would normally be "invisible" when you use
			
			this, because they just are visible.  So far in my travels I have never been
			
			attacked by something that was "invisible". I have been attacked by things while
			
			I was in a building and it was outside.  Very strange when you can't attack it
			
			directly but it can see and hit you. Humph.  This spell is *great* when you are
			
			in a group that is traveling invisible.  No more running "blind" with your group.
			
			So I do recommend you pick this one up, because when you do need it, it is
			
			invaluable.<BR>
			
			Update: Madwand has informed me that Shamans in Blackburrow *do* cast invisible on some Gnolls and they hit you while invisible. I will have to visit there and check this out.  I want to see if they stay invisible, or it is mandatory that you have this spell to attack them. :)
			
			
			
			</P>
			
			<P><STRONG>Phantom Leather</STRONG>
			
			 .  I personally did not buy this spell yet. I figured it is
			
			pretty expensive to cast when you should not be tanking that much anyway.  I
			
			suppose I will eventually get it and see how it works out, but my initial
			
			thought was that it would be a waste of money  (requires Cat's Eye Agate each
			
			cast) and mana.  I do well to stay out of the melee when soloing, so extra HP is
			
			not THAT much of a deal.  I have some extra money now from Lavastorm (have you
			
			gotten the impression that is a great place yet??) I may try it out.<BR>
			
			Update: I was thinking about this, and it may be that this is unlike the shielding spells in that it probably stays around as long as you are logged in?  I need to confirm this, but that would make it more worth while, in my mind.
			
			</P>
			
			<P><STRONG>Summon Heatstone. </STRONG>
			
			   Useless for me.  I have Infra Vision already, but if you want
			
			to be nice to the blinder races, you can summon these for them.  Coldstone will
			
			be the one *I* get (Ultra Vision).
			
			</P>
			
			<P><STRONG>Summon Throwing Dagger. </STRONG>
			
			    Well I got this one for the novelty of it.  Cool to
			
			have a "plinking" weapon.  Does not do much damage, but you can "pull" with it
			
			or be a tiny bit helpful if in a group and are OOM but do not want to Melee the
			
			MOB.   Good for other players that like throwing daggers.  Also I have heard of
			
			people that use it to "twink" their faction.  Walk up to a group that is attacking 
			
			a MOB that would give you a desired faction hit, and toss a dagger at it.  When
			
			the MOB dies, you share the faction hit.  Just be careful the group is able to 
			
			finish it off, or else that same mob will be after YOU. (_8(|) DOH!
			
			</P></FONT>
			
			<H4>Identify. See Sense Magic. Useless (except for practicing Divination) spell.. </H4>
			
			<H4>
			
			<BR><a name=PetGuide>General Pet Guide (Remember, this is my opinion and low on exact stats info).</a></H4><FONT 
			
			face=Arial size=2>
			
			<P>
			
			<B>Earth:</B>
			
			I was exclusive with earth until I reached 16 when water was my only immediate
			
			choice.  It was at that point that I was converted.   Earth pets are Tough and
			
			Strong.  They have the best strength and probably the most HP.  They need it
			
			though.  Their Agility really sucks, which means they get hit.  A lot.  They
			
			also have poor regeneration speed.  I figure theirs is the worst.  But they make
			
			great tanks.  They take a bunch of beatings and are great taunters.  When you
			
			hit 8 and get fire shield they really become amazing tanks.
			
			</P>
			
			<P>
			
			<B>Water:</B>
			
			Probably the best middle of the road pet.  They are tough, reasonable strength
			
			and awesome regen speed.  They are more agile than earth, but not by much.  They
			
			still get hit a lot.  The second side benefit of water is their near immunity to
			
			poison and disease.  I believe they are more dexterous, but I am not really
			
			certain on this.  My experience is that they hit as often if not more often than
			
			Earth.   The real selling point of Water though, is it's fast regeneration
			
			speed.  It actually can recover during a fight.  I can't tell you how many times
			
			I have done "/pet report health" at the end of a battle and gotten back 90+ or
			
			100.  Pretty awesome.  Especially when you get burnout (Level 12, I believe).
			
			Burnout makes them hit harder, at the expense of regeneration speed, so you get
			
			a strong pet that regens at about the same rate as earth for a while.  I have
			
			noticed however, that after a battle, if your pet sits long enough it regains
			
			it's original regeneration rate.  So if it was down to 10%, by the time it is up
			
			to 40% it starts healing at it's original rate.  Pretty cool.
			
			</P>
			
			<P>
			
			<B>My thoughts on Air and Fire:</B>
			
			I tried both, and determined that Fire and Air were too weak for effective solo.
			
			Even though fire has a damage shield, I did not find that to be much difference,
			
			even at lower levels.  Their agility, while better than earth does not
			
			compensate for their over all low hit points.  Fire shield is great if two MOBS
			
			are attacking your pet, but it does not really stay alive long enough to do much
			
			damage.  Even more so now that all the pets get offensive DD spells.  Air's
			
			agility is the highest, but its HP and AC the lowest, so while they don't get
			
			hit as often, when they get hit, it does a significant amount of damage,
			
			percentage wise.  I will say Air is IDEAL for dungeons and groups (see my
			
			dungeon guide below). Basically I feel these guys are not suited for Solo play.
			
			They are more useful in group situations, or for operations in dungeons.
			
			</P></FONT>
			
			<H4>
			
			<BR><a name=DungeonGuide>General Dungeon Guide (no not where they are, but how to survive in dungeons)</a>: 
			
			</H4><FONT face=Arial size=2>
			
			<P>
			
			First off, I will say that I have not played in dungeon areas much.  For two
			
			reasons:<BR>
			
			1) MOB trains<BR>
			
			2) Pet related woes.<BR>
			
			</P>
			
			<P>
			
			When I get to the higher levels where I will spend more time in dungeons, I will
			
			buy or research Air, just for those areas.  Air casts invisible on itself, so
			
			when it is not fighting, it does not attract stray MOBS. Most groups in dungeons
			
			don't like Mages because their pets wander off and drag in nasties when the
			
			group is healing.  Air reduces this.
			
			</P>
			
			<P>
			
			Another tip to making you a friendly Mage in dungeons is PARK YOUR PET.  We now
			
			have a great means of parking your pet, so that it does not chase after any mob
			
			that comes near.  "/pet sit down".  Learn it. Use it. Love it.  That command is
			
			a staple for me.  It has two benefits, one it keeps your pet out of trouble, and
			
			two, it enables it to heal faster.  Don't worry, if you are in trouble and you
			
			get near your pet, it will come running.  However (as my experience has shown me
			
			in LavaStorm),  you have to be in "hailing' distance of the pet (which is a
			
			radius from the pet of about 10 meters).  There is nothing more frustrating
			
			than being stunned by a lava bask, who is munching on you and your pet sits
			
			there watching, until you get close.  The only good thing is that, (assuming you
			
			have full health) you can survive enough to get to your pet.  You also have a
			
			(for my char at least) a 2 out of 3 chance of resisting the Stone Breath spell
			
			the Lava Bask casts, especially when you get to the point that all basks are
			
			blue to you.  I digress.
			
			</P>
			
			<P>
			
			Your best bet in a dungeon is to stay as close to a zone as possible. If not you
			
			should join a group (I know this is a SOLO guide, but dungeons are really built
			
			for GROUPS).  However, if your are DETERMINED to solo in dungeons, try following
			
			these tips.
			
			</P>
			
			<P>
			
			1) I reiterate the Park Your Pet directive.  Go fishing for your target and
			
			bring it back to your pet, if the dungeon layout supports this means of hunting.
			
			Many don't, so you just park it when you are medding and letting your pet heal
			
			up.
			
			</P>
			
			<P>
			
			2) Try to get SOW from someone without making a pain of yourself.  Offer money
			
			or trade for some summoned magic weapon or something.  Remember all your
			
			summoned weapons will hit MOBS that require magic weapons! That little boost
			
			of speed may save you when you start the inevitable train.
			
			</P>
			
			<P>
			
			3) find an area in the dungeon that is low traffic and has no MOBS about that
			
			will attack you (some dungeons, especially at higher levels, have green mobs
			
			that will ignore you).
			
			</P>
			
			<P>
			
			4) KNOW THE DUNGEON LAYOUT.  This may seem like common sense, but trust me, when
			
			you are being chased, you will quickly get confused if you are new to the
			
			dungeon.  Nothing is worse than getting stunned, doing the slow spin while you
			
			are waiting to get un-stunned, and shooting off in the wrong direction, falling
			
			in a pit (like in Black Burrow) or running into a bunch more nasties.
			
			</P>
			
			<P>
			
			Hunting dungeons is much tricker than hunting in the open.  I usually
			
			tour the dungeon invisible (If you are below Level 8 when you get the invisible
			
			spell, you probably should not really be there, or exploring deep.).  Crush
			
			Bone, or the open area of Black Burrow may be the exceptions  in this case.
			
			They have "open" areas that are more forgiving to the explorer, Crush Bone more
			
			so than Black Burrow.  You can find out what level all the MOBS are, and where
			
			they hang out long before you start "hunting".
			
			</P>
			
			<P>
			
			5) Stay alert, always.  You never know when someone will tromp through your
			
			little area with 10 Orcs on their tail when they forgot directive number 4.
			
			</P>
			
			<P>
			
			6) Let your pet take as much damage as you can.  You never know when you will
			
			need that little bit extra health or mana to escape the dungeon.  Try keeping
			
			your health and mana up as much as possible.  While this is true while in the
			
			open, in dungeons it is CUBED.
			
			</P>
			
			<P>
			
			7) If your pet starts chasing after a runner (a MOB who after getting damaged
			
			beyond a certain point starts running), burn it (the MOB) QUICK!  Runners in a
			
			dungeon are BAD NEWS.  They will bring back others or your pet will after it
			
			kills the runner. If you are low on mana, you may consider dispelling your pet
			
			and fighting it yourself or just running towards the zone and hang out near
			
			there until you see the faction / experience gain notice. It all depends on the
			
			area and your health etc.  This usually happens when you are fighting some MOB
			
			and a green MOB decides to join the fray and your pet starts beating it down
			
			until it runs.
			
			</P>
			
			<P>
			
			That is all I really have to offer for soloing in dungeons.  It really is
			
			different and you will have to find your own style that works well here.
			
			</P>
			
			<P>
			<CENTER>
			<IMG  src="http://www.kdi.com/~jeffj/images/Alchemys_sig.jpg" height=79 width=200>
			</CENTER>
			</P></FONT>
		</TD>
	</TR>
	</TABLE>	
	</TD>
	<TD width="64"></TD>
<TR>
	<TD><IMG SRC = "../graphics/botc000.jpg" WIDTH = 63 HEIGHT = 87></TD>
	<TD><IMG SRC = "../graphics/botc001.jpg" WIDTH = 473 HEIGHT = 87></TD>
	<TD><IMG SRC = "../graphics/botc002.jpg" WIDTH = 64 HEIGHT = 87></TD>
</TR>
</TABLE>
<BR>

<script language="JavaScript">
	<!-- Hide from old browsers
	var random = new Number(Math.floor(9999999 * Math.random())+1);

	// Modify to reflect site specifics
	page = "eqlore.com/";
	target = "@Top1,x02,x05,x08!x02";

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript1.1" SRC="http://oascentral.cybereps.com/RealMedia/ads/adstream_jx.ads/' + page + 1 + random + target + '">');
	document.write('</SCR');
	document.write('IPT>');

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript">');
	document.write('_version=10; //-->');
	document.write('</SCR');
	document.write('IPT>');

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript1.1">');
	document.write('_version=11; //-->');
	document.write('</SCR');
	document.write('IPT>');

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript">');

	if (navigator.appVersion.indexOf('MSIE 3') != -1){
	document.write('<IFRAME MARGINWIDTH=0 MARGINHEIGHT=0 HSPACE=0 VSPACE=0 FRAMEBORDER=0 SCROLLING=no BORDERCOLOR="#000000" SRC="oascentral.cybereps.com/RealMedia/ads/adstream_sx.ads/' + page + random + target + '"></IFRAME>');
	  }
	else if (_version < 11) {
	document.write ('<A HREF="http://oascentral.cybereps.com/RealMedia/ads/click_nx.ads/' + page + random + target + '"><IMG SRC="http://oascentral.cybereps.com/RealMedia/ads/adstream_nx.ads/' + page + random + target + '"></a>');
	  }

	document.write('</SCR');
	document.write('IPT>');

	// End Hide -->
</script><BR>
<BR>
</DIV>
</BODY>
</HTML>
