<!--
                 This page has been created by Renaissance IT
   Renaissance Internet Technologies Copyright (c) 1999 All Rights Reserved.

             for more info on our products, please visit :
                        http://www.renaissance.nl/

	This script has been written by Roy Boverhof <rboverhof@renaissance.nl>
	
        Pagename                : neriak_zones.html
        Last Updated    		: 05-02-2000
-->

<HTML>
<HEAD>
	<TITLE>the Seekers of Lore : Neriak Region</TITLE>
</HEAD>

<BODY BGCOLOR="#000000" TEXT="#000000" LINK="#000000" VLINK="#000000" ALINK="#000000">
<DIV ALIGN="CENTER">
<BR>
<script type="text/javascript"><!--
google_ad_client = "pub-0988179937943699";
google_ad_width = 468;
google_ad_height = 60;
google_ad_format = "468x60_as";
google_ad_channel ="";
google_ad_type = "text_image";
//--></script>
<script type="text/javascript"
  src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
</script><BR>	
<TABLE CELLSPACING = 0 CELLPADDING = 0 BORDER = 0>
<TR>
	<TD width="63"><IMG SRC = "graphics/topc000.jpg" WIDTH = 63 HEIGHT = 87></TD>
	<TD width="473"><IMG SRC = "graphics/topc001.jpg" WIDTH = 473 HEIGHT = 87></TD>
	<TD width="64"><IMG SRC = "graphics/topc002.jpg" WIDTH = 64 HEIGHT = 87></TD>
</TR>
	<TD width="63"></TD>
	<TD BGCOLOR="#BEA279" width="460">
	<DIV ALIGN="CENTER">
	<A HREF="maps.php3"><IMG SRC="graphics/atlasheader.jpg" WIDTH ="150" HEIGHT ="75" BORDER="0"></A>
	<TABLE WIDTH="460">
	<TR><TD>
	<CENTER>
<TABLE BORDER="0">
<TR>
<TD><BR><FONT COLOR="#FFFF00" SIZE="4" FACE="Ariel"><CENTER>Now choose a zone...</CENTER></FONT><BR></TD>
</TR>
<TR>
<TD>
<IMG SRC="graphics/neriak_zones.jpg" WIDTH=400 HEIGHT=400 BORDER=0 USEMAP="#neriak">
<MAP NAME="neriak">
<AREA SHAPE=RECT COORDS="80,60,179,102" HREF="map_search.php3?action=zone&add_zone=Temple%20of%20Solusek%20Ro">
<AREA SHAPE=RECT COORDS="149,133,237,174" HREF="map_search.php3?action=zone&add_zone=Solusek's%20Eye%20A">
<AREA SHAPE=RECT COORDS="36,133,118,174" HREF="map_search.php3?action=zone&add_zone=Solusek's%20Eye%20B">
<AREA SHAPE=RECT COORDS="72,204,167,243" HREF="map_search.php3?action=zone&add_zone=Lavastorm%20Mountains">
<AREA SHAPE=RECT COORDS="194,190,257,210" HREF="map_search.php3?action=zone&add_zone=Najena">
<AREA SHAPE=RECT COORDS="215,234,353,254" HREF="map_search.php3?action=zone&add_zone=Neriak%203rd%20Gate">
<AREA SHAPE=RECT COORDS="212,269,361,285" HREF="map_search.php3?action=zone&add_zone=Neriak%20Commons">
<AREA SHAPE=RECT COORDS="184,301,386,319" HREF="map_search.php3?action=zone&add_zone=Neriak%20Foreign%20Quarter">
<AREA SHAPE=RECT COORDS="83,298,166,337" HREF="map_search.php3?action=zone&add_zone=Nektulos%20Forest">
<AREA SHAPE=POLY COORDS="24,226,38,217,37,234,24,226" HREF="halas_zones.phtml" ALT="To Halas Region">
<AREA SHAPE=POLY COORDS="178,385,194,385,185,398,178,385" HREF="freeport_zones.phtml" ALT="To Freeport Region">
</MAP>
</TD>
</TR>
</TABLE>
	</TD></TR>
	</TABLE>
	<TD width="64"></TD>
<TR>
	<TD><IMG SRC = "graphics/botc000.jpg" WIDTH = 63 HEIGHT = 87></TD>
	<TD><IMG SRC = "graphics/botc001.jpg" WIDTH = 473 HEIGHT = 87></TD>
	<TD><IMG SRC = "graphics/botc002.jpg" WIDTH = 64 HEIGHT = 87></TD>
</TR>
</TABLE>
<BR>
<IMG SRC="http://service.bfast.com/bfast/serve?bfmid=1375281&siteid=40292692&bfpage=pc" BORDER="0" WIDTH="1" HEIGHT="1" NOSAVE ><A HREF="http://service.bfast.com/bfast/click?bfmid=1375281&siteid=40292692&bfpage=pc" TARGET="_new"><IMG SRC="http://affiliate.gamestop.com/affIMG/pc_120x60.gif" BORDER="0" WIDTH="120" HEIGHT="60" ALT="PC Games at GameStop.com"></A>
<BR>
<BR>
</DIV>
</BODY>
</HTML>