<!--
                 This page has been created by Renaissance IT
   Renaissance Internet Technologies Copyright (c) 1999 All Rights Reserved.

             for more info on our products, please visit :
                        http://www.renaissance.nl/

	This script has been written by Roy Boverhof <rboverhof@renaissance.nl>
	
        Pagename                : links2.html
        Last Updated    		: 10-24-2000
-->

<HTML>
<HEAD>
	<TITLE>the Seekers of Lore : Class Specific Links</TITLE>
</HEAD>

<BODY BGCOLOR="#000000" TEXT="#000000" LINK="#BEA279" VLINK="#BEA279">
<DIV ALIGN="CENTER">
<BR>
<!-- FGB Banner Code -->
<SCRIPT LANGUAGE="JavaScript">
<!-- Hide from old browsers
now = new Date();
random = now.getTime();

// Modify to reflect site specifics
site = "http://ds.cybereps.com";
target = "/SITE=FGN/AREA=EQLORE/AAMSZ=BANNER";

document.write('<IFRAME SRC="' + site + '/hserver/acc_random=' + random + target + '"');
document.write(' NORESIZE SCROLLING=NO HSPACE=0 VSPACE=0 FRAMEBORDER=0 MARGINHEIGHT=0 MARGINWIDTH=0 WIDTH=468 HEIGHT=60>');

document.write('<SCR');
document.write('IPT SRC="' + site + '/jnserver/acc_random=' + random + target + '">');
document.write('</SCR');
document.write('IPT>');

document.write('</IFRAME>');
// End Hide -->
</SCRIPT>

<NOSCRIPT><A HREF="http://ds.cybereps.com/accipiter/adclick/SITE=FGN/AREA=EQLORE/AAMSZ=BANNER"><IMG SRC="http://ds.cybereps.com/accipiter/nserver/SITE=FGN/AREA=EQLORE/AAMSZ=BANNER" border="0"></A></NOSCRIPT>
<!-- END FGB Banner Code --><BR>
<TABLE CELLSPACING = 0 CELLPADDING = 0 BORDER = 0>
<TR>
	<TD width="63"><IMG SRC = "graphics/topc000.jpg" WIDTH = 63 HEIGHT = 87></TD>
	<TD width="473"><IMG SRC = "graphics/topc001.jpg" WIDTH = 473 HEIGHT = 87></TD>
	<TD width="64"><IMG SRC = "graphics/topc002.jpg" WIDTH = 64 HEIGHT = 87></TD>
</TR>
	<TD width="63"></TD>
	<TD BGCOLOR="#BEA279" width="460">
	<DIV ALIGN="CENTER">
	<A HREF="links.phtml"><IMG SRC="graphics/linkheader.jpg" WIDTH ="200" HEIGHT ="75" ALT="Back to Links Index"></A>
	<TABLE WIDTH="440" ALIGN="center">
	<TR><TD></TD></TR>
	<TR>
		<TD>
		<A HREF="http://www.eqforge.com/warrior/" TARGET="_new"><IMG SRC="graphics/warriors_forge_link.jpg" WIDTH ="220" HEIGHT ="75"></A>
		</TD>
		<TD><FONT FACE="Verdana" SIZE="-2"><FONT COLOR="#FF0000">New!&nbsp;&nbsp;</FONT>The Warrior's Forge. Another fine addition to the EQForge sites.</FONT></TD>
	</TR>
	<TR>
		<TD>
		<A HREF="http://enchanter.atomicgamers.com/index.html" TARGET="_new"><IMG SRC="graphics/enchanters_assembly_link.jpg" WIDTH ="220" HEIGHT ="75"></A>
		</TD>
		<TD><FONT FACE="Verdana" SIZE="-2"><FONT COLOR="#FF0000">New!&nbsp;&nbsp;</FONT>The Enchanter's Assembly. Focusing on all things for the Enchanters of Norrath</FONT></TD>
	</TR>
	<!--
	This site is down.... 
	<TR>
		<TD>
		<A HREF="http://www.eqnecro.com/" TARGET="_new"><IMG SRC="graphics/eqnecro_link.jpg" WIDTH ="220" HEIGHT ="75"></A>
		</TD>
		<TD><FONT FACE="Verdana" SIZE="-2">EQnecro.com - dark site for the dark in heart.</FONT></TD>
	</TR>
	// -->
	<TR>
		<TD>
		<A HREF="http://eq.castersrealm.com/" TARGET="_new"><IMG SRC="graphics/eqcasters_link.jpg" WIDTH ="220" HEIGHT ="75"></A>
		</TD>
		<TD><FONT FACE="Verdana" SIZE="-2">Excellent site specializing in the pure caster classes.</FONT></TD>
	</TR>
	<TR>
		<TD>
		<A HREF="http://www.eqdruids.com/" TARGET="_new"><IMG SRC="graphics/eqdruids_link.jpg" WIDTH ="220" HEIGHT ="75"></A>
		</TD>
		<TD><FONT FACE="Verdana" SIZE="-2">EQ Druids - Home of the coolest class on Norrath!</FONT></TD>
	</TR>
	<TR>
		<TD>
		<A HREF="http://www.eqshaman.com/" TARGET="_new"><IMG SRC="graphics/eqshaman_link.jpg" WIDTH ="220" HEIGHT ="75"></A>
		</TD>
		<TD><FONT FACE="Verdana" SIZE="-2">EQ Shamans - Finally a site for one of the most enjoyable classes to play!</FONT></TD>
	</TR>
	<TR>
		<TD>
		<A HREF="http://home.elp.rr.com/wolfclan/alchemy/alchemyindex.html" TARGET="_new"><IMG SRC="graphics/belgars_link.jpg" WIDTH ="220" HEIGHT ="75"></A>
		</TD>
		<TD><FONT FACE="Verdana" SIZE="-2">Belgar's Ultimate Guide to Alchemy. A new site for research into the Shaman's art of potions.</FONT></TD>
	</TR>
	<TR>
		<TD>
		<A HREF="http://eqcleric.gameglow.com/" TARGET="_new"><IMG SRC="graphics/eqc_link.jpg" WIDTH ="220" HEIGHT ="75"></A>
		</TD>
		<TD><FONT FACE="Verdana" SIZE="-2">Best site for the Cleric</FONT></TD>
	</TR>
	<TR>
		<TD>
		<A HREF="http://www.eqforge.com/ranger" TARGET="_new"><IMG SRC="graphics/trg_link.jpg" WIDTH ="220" HEIGHT ="75"></A>
		</TD>
		<TD><FONT FACE="Verdana" SIZE="-2">One of the EQ Forge's fine sites</FONT></TD>
	</TR>
		<TR>
		<TD>
		<A HREF="http://www.eqforge.com/shadowknight" TARGET="_new"><IMG SRC="graphics/tkw_link.jpg" WIDTH ="220" HEIGHT ="75"></A>
		</TD>
		<TD><FONT FACE="Verdana" SIZE="-2">One of the EQ Forge's fine sites</FONT></TD>
	</TR>
	<TR>
		<TD>
		<A HREF="http://www.eqforge.com/shaman" TARGET="_new"><IMG SRC="graphics/tsc_link.jpg" WIDTH ="220" HEIGHT ="75"></A>
		</TD>
		<TD><FONT FACE="Verdana" SIZE="-2">One of the EQ Forge's fine sites</FONT></TD>
	</TR>
	<TR>
		<TD>
		<A HREF="http://www.graffe.com/" TARGET="_new"><IMG SRC="graphics/graffe_link.gif" WIDTH ="220" HEIGHT ="75"></A>
		</TD>
		<TD><FONT FACE="Verdana" SIZE="-2">Graffe's Wizard Compilation - Finally an excellant resource for Wizards only.</FONT></TD>
	</TR>
	<TR>
		<TD>
		<A HREF="http://kadanit.com/eqmonks/" TARGET="_new"><IMG SRC="graphics/eqmonks_link.jpg" WIDTH ="220" HEIGHT ="75"></A>
		</TD>
		<TD><FONT FACE="Verdana" SIZE="-2">Monk information site</FONT></TD>
	</TR>
	<TR>
		<TD>
		<A HREF="http://amtgard.pinkpig.com/everquest/eqbard.htm" TARGET="_new"><IMG SRC="graphics/eqbard_link.jpg" WIDTH ="220" HEIGHT ="75"></A>
		</TD>
		<TD><FONT FACE="Verdana" SIZE="-2">The EverQuesting Bard - Bardic information</FONT></TD>
	</TR>
	<TR>
		<TD>
		<A HREF="http://www2.hpcdsb.edu.on.ca/~jeff_cameron/" TARGET="_new"><IMG SRC="graphics/pon_link.jpg" WIDTH ="220" HEIGHT ="75"></A>
		</TD>
		<TD><FONT FACE="Verdana" SIZE="-2">Site devoted to the Holy Paladin</FONT></TD>
	</TR>
	<TR>
		<TD>
		<A HREF="http://www.eqportal.com/rogue/" TARGET="_new"><IMG SRC="graphics/rogue_link.jpg" WIDTH ="220" HEIGHT ="75"></A>
		</TD>
		<TD><FONT FACE="Verdana" SIZE="-2">A site devoted to the stealthy rogue!.</FONT></TD>
	</TR>
	<TR>
		<TD>
		<A HREF="mailto:webmaster@loreseekers.com?subject=links"><IMG SRC="graphics/submit_link.jpg" WIDTH ="220" HEIGHT ="75"></A>
		</TD>
		<TD><I>Do you know of a quality class specific site? Email us your link!</I></TD>
	</TR>
	</TABLE>
	<TD width="64"></TD>
<TR>
	<TD><IMG SRC = "graphics/botc000.jpg" WIDTH = 63 HEIGHT = 87></TD>
	<TD><IMG SRC = "graphics/botc001.jpg" WIDTH = 473 HEIGHT = 87></TD>
	<TD><IMG SRC = "graphics/botc002.jpg" WIDTH = 64 HEIGHT = 87></TD>
</TR>
</TABLE>
<BR>
<SCRIPT LANGUAGE="JavaScript">
<!-- Hide from old browsers
now = new Date();
random = now.getTime();

// Modify to reflect site specifics
site = "http://ds.cybereps.com";
target = "/SITE=FGN/AREA=EQLORE/AAMSZ=BUTTON1";

document.write('<IFRAME SRC="' + site + '/hserver/acc_random=' + random + target + '"');
document.write(' NORESIZE SCROLLING=NO HSPACE=0 VSPACE=0 FRAMEBORDER=0 MARGINHEIGHT=0 MARGINWIDTH=0 WIDTH=120 HEIGHT=90>');

document.write('<SCR');
document.write('IPT SRC="' + site + '/jnserver/acc_random=' + random + target + '">');
document.write('</SCR');
document.write('IPT>');

document.write('</IFRAME>');
// End Hide -->
</SCRIPT>
<NOSCRIPT> <A HREF="http://ds.cybereps.com/accipiter/adclick/SITE=FGN/AREA=EQLORE/AAMSZ=BUTTON1">
<IMG SRC="http://ds.cybereps.com/accipiter/nserver/SITE=FGN/AREA=EQLORE/AAMSZ=BUTTON1" border="0"></A>
</NOSCRIPT>
<BR>
<BR>
</DIV>
</BODY>
</HTML>


