<!--
                 This page has been created by Renaissance IT
   Renaissance Internet Technologies Copyright (c) 1999 All Rights Reserved.

             for more info on our products, please visit :
                        http://www.renaissance.nl/

	This script has been written by Roy Boverhof <rboverhof@renaissance.nl>
	
        Pagename                : death.html
        Last Updated    		: 26-01-2000
-->

<HTML>
<HEAD>
	<TITLE>the Seekers of Lore : In the Eyes of Death</TITLE>
</HEAD>

<BODY BGCOLOR="#000000" TEXT="#000000" LINK="#000000" VLINK="#000000" ALINK="#000000">
<DIV ALIGN="CENTER">
<BR>
<!-- FGN Banner Code -->
<script language="JavaScript">
	<!-- Hide from old browsers
	var random = new Number(Math.floor(9999999 * Math.random())+1);

	// Modify to reflect site specifics
	page = "eqlore.com/";
	target = "@Top1,x02,x05,x08!Top1";

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript1.1" SRC="http://oascentral.cybereps.com/RealMedia/ads/adstream_jx.ads/' + page + 1 + random + target + '">');
	document.write('</SCR');
	document.write('IPT>');

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript">');
	document.write('_version=10; //-->');
	document.write('</SCR');
	document.write('IPT>');

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript1.1">');
	document.write('_version=11; //-->');
	document.write('</SCR');
	document.write('IPT>');

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript">');

	if (navigator.appVersion.indexOf('MSIE 3') != -1){
	document.write('<IFRAME MARGINWIDTH=0 MARGINHEIGHT=0 HSPACE=0 VSPACE=0 FRAMEBORDER=0 SCROLLING=no BORDERCOLOR="#000000" SRC="oascentral.cybereps.com/RealMedia/ads/adstream_sx.ads/' + page + random + target + '"></IFRAME>');
	  }
	else if (_version < 11) {
	document.write ('<A HREF="http://oascentral.cybereps.com/RealMedia/ads/click_nx.ads/' + page + random + target + '"><IMG SRC="http://oascentral.cybereps.com/RealMedia/ads/adstream_nx.ads/' + page + random + target + '"></a>');
	  }

	document.write('</SCR');
	document.write('IPT>');

	// End Hide -->
</script>
<!-- END FGN Banner Code --><BR>
<TABLE CELLSPACING = 0 CELLPADDING = 0 BORDER = 0>
<TR>
	<TD width="63"><IMG SRC = "../graphics/topc000.jpg" WIDTH = 63 HEIGHT = 87></TD>
	<TD width="473"><IMG SRC = "../graphics/topc001.jpg" WIDTH = 473 HEIGHT = 87></TD>
	<TD width="64"><IMG SRC = "../graphics/topc002.jpg" WIDTH = 64 HEIGHT = 87></TD>
</TR>
	<TD width="63"></TD>
	<TD BGCOLOR="#BEA279" width="460">
	<DIV ALIGN="CENTER">
	<TABLE>
	<TR>
	<TD BGCOLOR="#BEA279" width="400">
		<FONT FACE="Verdana">
				<P><CENTER><B><FONT SIZE="+1">The Battle</FONT></B></CENTER>
		<FONT SIZE="-1">
		
        <P><FONT SIZE="+1">F</FONT>oladen smiled grimly as he strode through the deserted streets of
		freeport. No one was out this night. In fact, they had
		all fled hours ago vainly hoping to reach safety by ship, but there was
		no escape. The apocalyptic doom of this night had been
		foretold a millennia ago. Sighing, he strode through the gates of the
		city out into the plain ahead, towards the campfires that
		awaited him. He hailed the guard around the camp and made his way to the
		center of the camp. there was no cheer tonight, no singing,
		no dancing, no bardic tales of lore. Instead, all could be heard was the
		sound of whetstones upon blades already so sharp they could slice
		bone. Occasionally, the chant of a cleric could be heard as they prayed
		to their deities for strength and salvation on this night of doom.
		As he reached the center of the camp, he blew upon his horn to call his
		guildmates near. The time had come.

		<P><FONT SIZE="+1">H</FONT>ours later, they were all lined up upon the hills of the commonlands. 
		He glanced at the sky and noticed the position of the moon
		declaring it almost midnight. He looked back at the ranks of Seekers
		behind him. Each face was a friend and a memory. Tears welled in his 
		eyes as he glanced upon Trinitii, the young druid who was to be wed 2
		days hence.  He wondered if any of them would be alive then. Bracing
		himself, he addressed his guild mates, his friends. 
		
	    <P>"<FONT SIZE="+1">T</FONT>onight, we fight not for honor but for all of Norath. If we fail,
		everyone dies. Look at those next to you, many of them will not
		be here when the night is done. Know that you are the only thing that
		stands between your families and annihilation. Know that for each one of
		us that falls, another will rise. They say that the armageddon comes and
		that we are doomed. I refuse to accept that! We WILL fight!"
		        
		<P><FONT SIZE="+1">S</FONT>lowly he began to chant the Seeker oath and the others joined in with
		him." I am a Seeker. My sword is my guildmates weapon. My life is his
		shield. I live for honor and glory and the pursuit of knowledge. For
		without those there is nothing. We are Seekers. We are one." Foladen
		pulled his lute from his back and played a dirge to fallen comrades as
		the chant ended. He continued to play as the ground trembled
		beneath him and the sky split apart, heralding the coming of the end. He
		continued to play as the foretold bane of the world arose from the 
		ground and glared at them. He continued to play as the creature that
		even Nagafen feared, the Y2k bug marched towards them. Well over 100 ft
		high it towered above them, venom dripping from its mandibles. where the
		venom hit the ground, it ate through the earth. Swords and spells were
		held at the ready. Not one Seeker fled. Yet Foladen continued to play,
		for he had swore to play till the end.
		
		
		<P><FONT SIZE="+1">O</FONT>nward came the beast, the proclaimed end of the world. And with it
		came the denizens of the underworld. By the hundreds they scrambled from
		a fissure in the earth. Clawing and climbing over each other in their
		eagerness to spill blood. The seekers braced themselves for the impact
		as the horde rushed onwards and slammed into them with the force of a
		hurricane. dozens died in the first few seconds alone, yet more came to
		replace those who fell. Again and again the unholy horde pushed the
		warriors only to be shoved back as the seekers held their ground. They
		had nowhere to run. they would die here tonight.
		 
		<P><FONT SIZE="+1">Y</FONT>et even as the seekers rained death upon the demons, the Y2K bug
		caused mayhem itself. Shudders went through Foladen as the bug , picked
		up an elven warrior in its mandibles and tossed his broken body to the
		ground. The warrior's screams of pains were quickly cut off as a 
		cleric ran to his side using what little art he had left to heal the
		man's wounds. The most serious of his wounds healed, the warrior arose
		and limped his way back to the battle line, leaving behind the cleric
		who has lapsed into unconsciousness.
		
		<P><FONT SIZE="+1">A</FONT>nd so it went through the night, the demon horde rushed them and
		always were pushed back. The screams of the dying, the clash of steel,
		and the thundering roar of fireballs filled the night. But somehow, the
		music was heard above it all. It envigored them and urged them onward in
		a futile battle they could not win. And hours after the battle began,
		Foladen fell to his knees and stopped playing. His voice had gone out
		hours ago and his fingers bled. Begrudgingly he prepared to face the
		end. It had been a good life; he would not regret the way he had lived
		it. He closed his eyes and prepared himself. But it was silent.
		Startled, he wearily raised his head to look upon the field of battle.
		Through a body numb with fatigue and pain, he watched the horde retreat
		to the nether world. He watched as the Y2K bug came crashing to the
		ground, and atop its corpse stood a single warrior. Trintii, the young
		maid who would still be married 2 days hence, raised her sword
		triumphantly from where she has slain the creature. And off her blade
		glinted the first shining rays of the dawns light. 
		
		<P><FONT SIZE="+1">A</FONT>nd so it came to pass, that the Y2K bug passed in the night. It did
		not bring the armageddon. Instead it signaled a new age of glory for the Seekers of Lore.
		</FONT>
		<BR>
		<BR>
		<B>Foladen Moonsong</B>, <FONT SIZE="-1">bard of the isles.</FONT><BR>
	</TD>
	</TR>
	</TABLE>

<TABLE>
<TR>
<TD><A HREF="http://www.loreseekers.com/tales.phtml"><IMG SRC="http://www.loreseekers.com/graphics/tales_return_link.jpg" WIDTH=200 HEIGHT=75 ALT="Read some other stories by our members!" BORDER="0"></A></TD>
</TR>
</TABLE>

	<TD width="64"></TD>
<TR>
	<TD><IMG SRC = "../graphics/botc000.jpg" WIDTH = 63 HEIGHT = 87></TD>
	<TD><IMG SRC = "../graphics/botc001.jpg" WIDTH = 473 HEIGHT = 87></TD>
	<TD><IMG SRC = "../graphics/botc002.jpg" WIDTH = 64 HEIGHT = 87></TD>
</TR>
</TABLE>
<BR>
<IMG SRC="http://service.bfast.com/bfast/serve?bfmid=1375281&siteid=40292692&bfpage=pc" BORDER="0" WIDTH="1" HEIGHT="1" NOSAVE ><A HREF="http://service.bfast.com/bfast/click?bfmid=1375281&siteid=40292692&bfpage=pc" TARGET="_new"><IMG SRC="http://affiliate.gamestop.com/affIMG/pc_120x60.gif" BORDER="0" WIDTH="120" HEIGHT="60" ALT="PC Games at GameStop.com"></A>
<BR>
<BR>
</DIV>
</BODY>
</HTML>