<!--
                 This page has been created by Renaissance IT
   Renaissance Internet Technologies Copyright (c) 1999 All Rights Reserved.

             for more info on our products, please visit :
                        http://www.renaissance.nl/

	This script has been written by Roy Boverhof <rboverhof@renaissance.nl>
	
        Pagename                : apply.html
        Last Updated    		: 11-7-1999
-->

<HTML>
<HEAD>
	<TITLE>the Seekers of Lore : Apply</TITLE>
</HEAD>
<SCRIPT LANGUAGE="JavaScript" TYPE="text/javascript">
<!--
function go(){
if (document.selecter.select1.options[document.selecter.select1.selectedIndex].value != "none") {
location = document.selecter.select1.options[document.selecter.select1.selectedIndex].value
		}
	}
//-->
</SCRIPT>
<BODY BGCOLOR="#000000" TEXT="#000000" LINK="#FFF000">
<DIV ALIGN="CENTER">
<BR>
<!-- FGB Banner Code -->
<SCRIPT LANGUAGE="JavaScript">
   <!-- Hide from old browsers
   now = new Date();
   random = now.getTime();
     
   // Modify to reflect site specifics
   site = "http://ds.cybereps.com";
   target = "/SITE=FGN/AREA=EQLORE/AAMSZ=BANNER";
   
   document.write('<IFRAME SRC="' + site + '/hserver/acc_random=' + random + target + '"');
   document.write(' NORESIZE SCROLLING=NO HSPACE=0 VSPACE=0 FRAMEBORDER=0 MARGINHEIGHT=0 MARGINWIDTH=0 WIDTH=468 HEIGHT=60>');
   
   document.write('<SCR');
   document.write('IPT SRC="' + site + '/jnserver/acc_random=' + random + target + '">');
   document.write('</SCR');
   document.write('IPT>');
   
   document.write('</IFRAME>');
   // End Hide -->
 </SCRIPT>
 <NOSCRIPT> 
   <A HREF="http://ds.cybereps.com/accipiter/adclick/SITE=FGN/AREA=EQLORE/AAMSZ=BANNER">
   <IMG SRC="http://ds.cybereps.com/accipiter/nserver/SITE=FGN/AREA=EQLORE/AAMSZ=BANNER" border="0"></A>
 </NOSCRIPT>
<!-- END FGB Banner Code --><BR>
<TABLE CELLSPACING = 0 CELLPADDING = 0 BORDER = 0>
<TR>
	<TD width="63"><IMG SRC = "graphics/topc000.jpg" WIDTH = 63 HEIGHT = 87></TD>
	<TD width="473"><IMG SRC = "graphics/topc001.jpg" WIDTH = 473 HEIGHT = 87></TD>
	<TD width="64"><IMG SRC = "graphics/topc002.jpg" WIDTH = 64 HEIGHT = 87></TD>
</TR>
	<TD width="63"></TD>
	<TD BGCOLOR="#BEA279" width="460">
	<DIV ALIGN="CENTER">
	<IMG SRC="graphics/apply.jpg">
	<TABLE WIDTH="460">
	<TR>
		<TD>		
		<DIV ALIGN="CENTER">
		Before you apply, make sure you have read our <A HREF="charter.phtml">charter</A>, and agree with it.<BR>
		Make sure you read our <A HREF="faq.phtml">faq</A>, there is a detailed list of steps you have to take to become a Seeker of Lore.<BR>
		<BR>
		<BR>
		If you have followed the steps in the FAQ and one of our officers has given you this weeks password, you may continue to the application page of the branch you want to join.</A> .
		<BR>
		<BR>
			<SCRIPT LANGUAGE="JavaScript" TYPE="text/javascript">
			<!--
			document.write('<TABLE CELLPADDING=2 CELLSPACING=2>');
			document.write('<form name="selecter"><TR><TD><B><FONT SIZE="-1">Branch : </FONT></B></TD><TD bgcolor=#00001f align=center valign=top><select name="select1" size=1 OnChange=go()>');
			document.write('<option value="apply.phtml">Select a branch');
			document.write('<option value="apply.phtml">');
			document.write('<option value="/branches/bertoxxulous">Bertoxxulous');
			document.write('<option value="/branches/bristlebane">Bristlebane');
			// document.write('<option value="/branches/cazic-thule">Cazic-Thule');
			document.write('<option value="/branches/innoruuk">Innoruuk');
			document.write('<option value="/branches/morell-thule">Morell-Thule');
			// document.write('<option value="/branches/quellios">Quellios');
			document.write('<option value="/branches/rodcet_nife">Rodcet Nife');
			document.write('<option value="/branches/tallon_zek">Tallon Zek');
			document.write('<option value="/branches/tarew_marr">Tarew Marr');
			document.write('<option value="/branches/the_rathe">The Rathe');
			// document.write('<option value="/branches/tunare">Tunare');
			document.write('<option value="/branches/veeshan">Veeshan');
			document.write('<option value="/branches/xegony">Xegony');
			document.write('</select>');
			document.write('</TD></TR>');
			document.write('</form>');
			document.write('</TABLE>');
			// end hiding contents -->
			</SCRIPT>
		<BR><BR>
		</DIV>
		</TD>
	</TR>
	</TABLE>	
	</TD>
	<TD width="64"></TD>
<TR>
	<TD><IMG SRC = "graphics/botc000.jpg" WIDTH = 63 HEIGHT = 87></TD>
	<TD><IMG SRC = "graphics/botc001.jpg" WIDTH = 473 HEIGHT = 87></TD>
	<TD><IMG SRC = "graphics/botc002.jpg" WIDTH = 64 HEIGHT = 87></TD>
</TR>
</TABLE>
<BR>
 <SCRIPT LANGUAGE="JavaScript">
   <!-- Hide from old browsers
   now = new Date();
   random = now.getTime();
   
   // Modify to reflect site specifics
   site = "http://ds.cybereps.com";
   target = "/SITE=FGN/AREA=EQLORE/AAMSZ=BOX";
   
   document.write('<IFRAME SRC="' + site + '/hserver/acc_random=' + random + target + '"');
   document.write(' NORESIZE SCROLLING=NO HSPACE=0 VSPACE=0 FRAMEBORDER=0 MARGINHEIGHT=0 MARGINWIDTH=0 WIDTH=125 HEIGHT=125>');
      
   document.write('<SCR');
   document.write('IPT SRC="' + site + '/jnserver/acc_random=' + random + target + '">');
   document.write('</SCR');
   document.write('IPT>');
   
   document.write('</IFRAME>');
   // End Hide -->
 </SCRIPT>
 <NOSCRIPT> 
   <A HREF="http://ds.cybereps.com/accipiter/adclick/SITE=FGN/AREA=EQLORE/AAMSZ=BOX">
   <IMG SRC="http://ds.cybereps.com/accipiter/nserver/SITE=FGN/AREA=EQLORE/AAMSZ=BOX" border="0"></A>
 </NOSCRIPT>
<BR>
<BR>
</DIV>
</BODY>
</HTML>
