
<HTML>

<HEAD>
<META name="description" content="Media and Games Online Network - MGON - The Gamers' Choice for pc game news, reviews, interviews, downloads, and communities.">
<META name="keywords" content="MGON, MGO, computer, game, games, pc, windows, news, review, reviews, preview, previews, interview, inerviews, article, articles, demo, demos, media, trailer, teaser, rpg, roleplay, roleplaying, action, fps, shooter, strategy, sim, simulation, god, rts, real time, racing, screenshot, screenshots, patch, patches, hardware, cheat, cheats, tip, tips, trick, tricks, hint, hints, walkthru, walkthrus, walkthroughs, walkthrough, faq, faqs, entertainment, fun, forum, forums, shop, buy, message board, irc, chat">
<META name="robots" content="index,follow">
<meta name="distribution" content="GLOBAL">
<meta name="rating" content="GENERAL">
<meta name="copyright" content="MGON International AB">
<meta name="Author" content="MGON">
<meta http-equiv="reply-to" content="admin@mgon.com">
<meta name="Language" content="en-us"> 
<script src="http://www.adready.net/clnt/network/mgon/AdPointer.js" language="javascript"></script><TITLE>Welcome to Media and Games Online Network - MGON</TITLE>

<META name="description" content="MGON - The Gamer's Choice for gaming news. Get the hottest info from the gaming industry.

.">

<META name="keywords" content="MGON, MGO, Interviews, Game previews, Game downloads, Gaming Network, , Gaming News, News, Multiplayer, Games, PC Games, Console Games, Reviews, Forum, MGON International AB, Action, Strategy, Simulation, Roleplay, Racing">

<META name="robots" content="index,follow">

<link rel="stylesheet" href="/newstyle.css" type="text/css">

<!--

-->

<script language="JavaScript" type="text/javascript">
<!--
function go(where) {
  if(where != "void" && where!="") location.href = where;
}
wallPaperWindowsLength = 0;

function reply(tid,pid,cid,lang) {

  url = "/reply.phtml?tid=" + tid + "&pid=" + pid + "&id=" + cid + "&language=" + lang + '&ref=%2Farticleindex.phtml';
  ipwindow = open("","prewindow","scrollbars=yes,toolbar=no,height=400,width=400");
  ipwindow.location.href = url;
        
}

function rateit(id,vote) {
    if(vote != "") {
		document.rate.content_id.value = id;
		document.rate.vote.value = vote;
		document.rate.submit();
	}
}

function screenshot(cid,pid) {

  url = "/screenshot.phtml?cid=" + cid + "&pid=" + pid;
  ipwindow = open("","prewindow","scrollbars=yes,toolbar=no,height=630,width=710");
  ipwindow.location.href = url;
        
}

function relatedmedia(url) {

  ipwindow = open("","prewindow","scrollbars=yes,toolbar=no,height=300,width=300");
  ipwindow.location.href = url;
        
}
function MM_preloadImages() { //v3.0
  var d=document; if(d.images){ if(!d.MM_p) d.MM_p=new Array();
    var i,j=d.MM_p.length,a=MM_preloadImages.arguments; for(i=0; i<a.length; i++)
    if (a[i].indexOf("#")!=0){ d.MM_p[j]=new Image; d.MM_p[j++].src=a[i];}}
}
function MM_findObj(n, d) { //v4.0
  var p,i,x;  if(!d) d=document; if((p=n.indexOf("?"))>0&&parent.frames.length) {
    d=parent.frames[n.substring(p+1)].document; n=n.substring(0,p);}
  if(!(x=d[n])&&d.all) x=d.all[n]; for (i=0;!x&&i<d.forms.length;i++) x=d.forms[i][n];
  for(i=0;!x&&d.layers&&i<d.layers.length;i++) x=MM_findObj(n,d.layers[i].document);
  if(!x && document.getElementById) x=document.getElementById(n); return x;
}
function MM_swapImgRestore() { //v3.0
  var i,x,a=document.MM_sr; for(i=0;a&&i<a.length&&(x=a[i])&&x.oSrc;i++) x.src=x.oSrc;
}
function MM_swapImage() { //v3.0
  var i,j=0,x,a=MM_swapImage.arguments; document.MM_sr=new Array; for(i=0;i<(a.length-2);i+=3)
   if ((x=MM_findObj(a[i]))!=null){document.MM_sr[j++]=x; if(!x.oSrc) x.oSrc=x.src; x.src=a[i+2];}
}

function getWall(id,name) {
  url = "/getwall.phtml?thisid=" + id + "&thisname=" + name;

	ipwindow = open("","prewindow_"+wallPaperWindowsLength,"fullscreen=no,resizable=yes,scrollbars=yes,toolbar=yes,height=600,width=800");        
        ipwindow.location.href = url;
	wallPaperWindowsLength++;

}

function getFile(id,name) {
  url = "/common/getfile.phtml?thisid=" + id + "&thisname=" + name;
  ipwindow = open("","prewindow","scrollbars=no,toolbar=no,height=200,width=495");
  ipwindow.location.href = url;
}
function localDate(dateStr) {
  now = new Date();
  var ar1 = now.toString().split(" ");
  var addH = -100;
  var addM = -100;
  var gmt = new Array(new Array());
  gmt["PST"] = -8;
  gmt["MST"] = -7;
  gmt["CST"] = -6;
  gmt["EST"] = -5;
  gmt["UTC"] = 0;
  if(ar1[4].indexOf("+") != -1) {
    var gm = ar1[4].split("+");
    gm[2] = 0-gm[1].substr(0,2);
    addH = Number(gm[2]);
    gm[2] = 0-gm[1].substr(2,2);
    addM = Number(gm[2]);
  }
  if(ar1[4].indexOf("-") != -1) {
    var gm = ar1[4].split("-");
    gm[2] = gm[1].substr(0,2);
    addH = Number(gm[2]);
    gm[2] = gm[1].substr(2,2);
    addM = Number(gm[2]);
  }
  if(addH == -100) {
    addH = gmt[ar1[4]];
    addM = 0;
  }
  there = new Date(dateStr);
  nowP = Date.parse(there);
  if(addH > 0) nowP -= 3600000;
  nowP += Number(addH)*3600000;
  nowP += Number(addM)*60000;
  realD = new Date(nowP);
  real = realD.toLocaleString();
  //  document.write(real[0] + " " + real[1] + " " + real[2] + " " +real[3]);
  document.write(real);
}
//-->
</script>


</HEAD>

<body bgcolor="#000000" text="#EEEEEE" link="#FFFFFF" vlink="#FFFFFF" alink="#FFFFFF" background="/newimages/backgrounds/bluelines.gif" leftmargin="0" topmargin="0" marginwidth="0" marginheight="0">

<table width="772" border="0" align="center" cellpadding="1" cellspacing="0" bgcolor="#000000">

  <tr>

    <td align="center"><!-- Webserver: w13 --><!-- loginUrl: http://everquest.mgon.com/common/loginNew.phtml?ref=www.mgon.com&page=/articleindex.phtml !--><!-- loginUrl: http://everquest.mgon.com/common/members.phtml?ref=www.mgon.com&page=/articleindex.phtml !--><script language="JavaScript">
<!--
function MM_openBrWindow(theURL,winName,features) { //v2.0
  window.open(theURL,winName,features);  
}
function login() {
  window.open('http://everquest.mgon.com/common/loginNew.phtml?ref=www.mgon.com&page=/articleindex.phtml', 'Login', 'width=250,height=250,scrollbars=yes'); 
}
function member() {
  window.open('http://everquest.mgon.com/common/members.phtml?ref=www.mgon.com&page=/articleindex.phtml', 'Member', 'width=500,height=600,scrollbars=yes'); 
}
//-->
</script>
<!-- Place the following code where you want an ad to appear -->
<!-- VC active -->
<SCRIPT language="JavaScript" SRC="http://oz.valueclick.com/cycle?host=hs0208926&t=pop&size=medium">
</SCRIPT>
<!-- vc active -->

<table width="100%" border="0" cellspacing="0" cellpadding="0" background="/common/images/topplate/resize.gif">
  <tr> 
    <td> 
      <table width="488" border="0" cellspacing="0" cellpadding="0" background="/common/images/topplate/resize.gif">
				<tr> 
          <td><img src="/common/images/topplate/metalcorner.gif" width="5" height="20"></td>
				          <td><a href="javascript:login();"><img src="/common/images/topplate/memberlogin.gif" width="80" height="20" border="0"></a></td>					
			            <td><img src="/common/images/topplate/arrow.gif" width="10" height="20"></td>
          <td><img src="/common/images/topplate/metalcolumn.gif" width="3" height="20"></td>
          <td><a href="javascript:;" onClick="MM_openBrWindow('/common/sitemap.html','navigation','width=540,height=450')"><img src="/common/images/topplate/pc.gif" width="23" height="20" border="0"></a></td>
          <td><img src="/common/images/topplate/metalcolumn.gif" width="3" height="20"></td>
          <td><a href="javascript:;" onClick="MM_openBrWindow('/common/sitemap.html','navigation','width=540,height=450')"><img src="/common/images/topplate/action.gif" width="47" height="20" border="0"></a></td>
          <td><img src="/common/images/topplate/metalcolumn.gif" width="3" height="20"></td>
          <td><a href="javascript:;" onClick="MM_openBrWindow('/common/sitemap.html','navigation','width=540,height=450')"><img src="/common/images/topplate/roleplay.gif" width="62" height="20" border="0"></a></td>
          <td><img src="/common/images/topplate/metalcolumn.gif" width="3" height="20"></td>
          <td><a href="javascript:;" onClick="MM_openBrWindow('/common/sitemap.html','navigation','width=540,height=450')"><img src="/common/images/topplate/simulation.gif" width="70" height="20" border="0"></a></td>
          <td><img src="/common/images/topplate/metalcolumn.gif" width="3" height="20"></td>
          <td><a href="javascript:;" onClick="MM_openBrWindow('/common/sitemap.html','navigation','width=540,height=450')"><img src="/common/images/topplate/console.gif" width="56" height="20" border="0"></a></td>
          <td><img src="/common/images/topplate/metalcolumn.gif" width="3" height="20"></td>
          <td><a href="javascript:;" onClick="MM_openBrWindow('/common/sitemap.html','navigation','width=540,height=450')"><img src="/common/images/topplate/strategy.gif" width="64" height="20" border="0"></a></td>
          <td><img src="/common/images/topplate/metalcolumn.gif" width="3" height="20"></td>
          <td><a href="javascript:;" onClick="MM_openBrWindow('/common/sitemap.html','navigation','width=540,height=450')"><img src="/common/images/topplate/racing.gif" width="47" height="20" border="0"></a></td>
          <td><img src="/common/images/topplate/metalcolumn.gif" width="3" height="20"></td>
<td>
</td>
</tr>
      </table>
    </td>
    <td background="/common/images/topplate/resize.gif" width="100%"><img src="/common/images/topplate/resize.gif" width="100%" height="20"></td>
    <td>
      <table width="88" border="0" cellspacing="0" cellpadding="0" background="/common/images/topplate/resize.gif">
        <tr>
          <td><img src="/common/images/topplate/metalcolumn.gif" width="3" height="20"></td>
          <td><a href="javascript:;" onClick="MM_openBrWindow('/common/sitemap.html','navigation','width=540,height=450')"><img src="/common/images/topplate/mgonetwork.gif" width="82" height="20" border="0"></a></td>
          <td><img src="/common/images/topplate/metalcorner.gif" width="5" height="20"></td>
        </tr>
      </table>
    </td>
  </tr>
</table>
<table width="100%" border="0" cellspacing="0" cellpadding="0" bgcolor="#000000">
  <tr> 
    <td><img src="http://193.45.143.3:81/1_1pix.gif?1008316750" width="1" height="1" nosave></td>
  </tr>
</table>

<!-- ---------- Open AdBonus AdServ Code -------------- -->
<!--  popup per hour per unique user -->
<script language="JavaScript">
<!--
function setCookie(NameOfCookie, value, expirehours) {
var ExpireDate = new Date ();
ExpireDate.setTime(ExpireDate.getTime() + (expirehours * 3600 * 1000));
document.cookie = NameOfCookie + "=" + escape(value) +
((expirehours == null) ? "" : "; expires=" + ExpireDate.toGMTString()) +

"; path=/;" ;
}
if (document.cookie.indexOf('AdPopUpC11')==-1)
{
  setCookie('AdPopUpC11','yes',1);
 document.write('<'+'SCRIPT LANGUAGE="JavaScript" SRC="');
 document.write('http://adserv.adbonus.com/cgi-bin/track.cgi?');
 document.write('c=getmedia&pid=52769">'+'<'+'/SCRIPT>');

}
// -->
</script>
<script language="JavaScript">
window.focus();
</script>
<!-- ---------- End AdBonus AdServ Code -------------- --></td>

  </tr>

</table>

<table width="772" border="0" cellspacing="0" cellpadding="0" align="center">

  <tr> 

    <td>

<TABLE width="772" border="0" cellspacing="0" cellpadding="0">

  <TR> 

    <TD><IMG src="/newimages/top/topleft.gif" width="592" height="81" border="0" usemap="#Map"><MAP name="Map"><AREA shape="rect" coords="13,36,138,76" href="http://www.mgon.com" alt="MGON Home" title="MGON Home"></MAP></TD>

    <TD width="100%" background="/newimages/top/resize.gif"><IMG src="/newimages/top/resize.gif" width="1" height="81"></TD>

    <TD><IMG src="/newimages/top/topright.gif" width="157" height="81"></TD>

  </TR>

</TABLE>


<TABLE width="772" border="0" cellspacing="0" cellpadding="0" bgcolor="#000000">
  <TR> 
		<TD align="center" width="130"> 
			<TABLE width="100%" border="0" cellspacing="0" cellpadding="0">
				<TR> 
					
          <TD align="center" background="/newimages/bannerarea/resize.gif"><OBJECT classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=4,0,2,0" width="120" height="60">
							<param name=movie value="http://se.fs.mgon.com/flashmovies/mgochannel3.swf">
							<PARAM name=quality value=high>
							<PARAM name="menu" value="false">
							<embed src="http://se.fs.mgon.com/flashmovies/mgochannel3.swf" 
quality=high 
pluginspage="http://www.macromedia.com/shockwave/download/index.cgi?P1_Prod_Version=ShockwaveFlash" 
type="application/x-shockwave-flash" menu="false" width="120" height="60">
							</EMBED> 
						</OBJECT></TD>
				</TR>
				<TR> 
					
          <TD><IMG src="/newimages/bannerarea/mgonchannel.gif" width="130" height="13"></TD>
				</TR>
			</TABLE>
		</TD>
		
    <TD align="center" width="490" valign="top"> 
      <!--Ad 468x60-->      <span class="smalltext"><NOLAYER><IFRAME SRC="http://ad.se.doubleclick.net/adi/mgon.com/;sz=468x60;ord=1008316750?" bgcolor="#000000" width="468" height="60" frameborder="no" border="0" MARGINWIDTH="0" MARGINHEIGHT="0" SCROLLING="no"><A HREF="http://ad.se.doubleclick.net/jump/mgon.com/;abr=!ie;sz=468x60;ord=1008316750?"><IMG SRC="http://ad.se.doubleclick.net/ad/mgon.com/;abr=!ie;sz=468x60;ord=1008316750?" border="0" height="60" width="468"></A></IFRAME></NOLAYER><ILAYER id="layer3" visibility="hidden" width="468" height="60" align="center"></ILAYER></span><!--/Ad 468x60-->    </TD>
		
    <TD width="150" align="center" valign="top" background="/newimages/resizes/rightnav_black.gif"> 
      <!-- 120x60 code goes here -->
      
      <!-- 120x60 code goes here -->
    </TD>
	</TR>
</TABLE>
</td></tr></table>

<table width="772" border="0" cellspacing="0" cellpadding="0" align="center" background="/newimages/misc/50x50pix.gif">

  <tr>

    <td width="130" background="/newimages/resizes/leftnav.gif" valign="top"> 

<img src="/newimages/columns/sitecontent.gif" width="130" height="24"><br> 
<table width="130" border="0" cellspacing="0" cellpadding="0" bgcolor="#000000" background="/newimages/misc/50x50pix.gif">
  <tr bgcolor="#000000"> 
    <td> 
      <table width="100%" border=0 cellpadding=0 cellspacing=1>
        <tr bgcolor="#18355C"> 
          <td style="border='1 #18355C'" onMouseOver="style.backgroundColor='#FFFFFF'; style.cursor='hand'; style.border='1 #18355C'" onMouseOut="style.backgroundColor='#719FC6'; style.border='1 #18355C';" height="21" bgcolor="#719FC6"> 
            <table width="100%" border="0" cellspacing="0" cellpadding="0">
              <tr> 
                <td class="Bolded"><img src="/newimages/misc/navarrow.gif" width="12" height="21"></td>
                <td bgcolor="#18355C" height="21" width="100%"><a href="/" class="bluelinks" style="margin:0;"> 
                  <div><img src="/newimages/misc/1pix.gif" width="5" height="1" border="0">Home</div>
                  </a></td>
              </tr>
            </table>
          </td>
        </tr>
        <tr bgcolor="#18355C"> 
          <td style="border='1 #18355C'" onMouseOver="style.backgroundColor='#FFFFFF'; style.cursor='hand'; style.border='1 #18355C'" onMouseOut="style.backgroundColor='#719FC6'; style.border='1 #18355C';" height="21" bgcolor="#719FC6"> 
            <table width="100%" border="0" cellspacing="0" cellpadding="0">
              <tr> 
                <td class="Bolded"><img src="/newimages/misc/navarrow.gif" width="12" height="21"></td>
                <td bgcolor="#18355C" height="21" width="100%"><a href="/news.phtml" class="bluelinks" style="margin:0;"> 
                  <div><img src="/newimages/misc/1pix.gif" width="5" height="1" border="0">News</div>
                  </a></td>
              </tr>
            </table>
          </td>
        </tr>
        <tr bgcolor="#18355C"> 
          <td style="border='1 #18355C'" onMouseOver="style.backgroundColor='#FFFFFF'; style.cursor='hand'; style.border='1 #18355C'" onMouseOut="style.backgroundColor='#719FC6'; style.border='1 #18355C';" height="21" bgcolor="#719FC6"> 
            <table width="100%" border="0" cellspacing="0" cellpadding="0">
              <tr> 
                <td class="Bolded"><img src="/newimages/misc/navarrow.gif" width="12" height="21"></td>
                <td bgcolor="#18355C" height="21" width="100%"><a href="/reviewindex.phtml" class="bluelinks" style="margin:0;"> 
                  <div><img src="/newimages/misc/1pix.gif" width="5" height="1" border="0">Reviews</div>
                  </a></td>
              </tr>
            </table>
          </td>
        </tr>
        <tr bgcolor="#18355C"> 
          <td style="border='1 #18355C'" onMouseOver="style.backgroundColor='#FFFFFF'; style.cursor='hand'; style.border='1 #18355C'" onMouseOut="style.backgroundColor='#719FC6'; style.border='1 #18355C';" height="21" bgcolor="#719FC6"> 
            <table width="100%" border="0" cellspacing="0" cellpadding="0">
              <tr> 
                <td class="Bolded"><img src="/newimages/misc/navarrow.gif" width="12" height="21"></td>
                <td bgcolor="#18355C" height="21" width="100%"><a href="/previewindex.phtml" class="bluelinks" style="margin:0;"> 
                  <div><img src="/newimages/misc/1pix.gif" width="5" height="1" border="0">Previews</div>
                  </a></td>
              </tr>
            </table>
          </td>
        </tr>
        <tr bgcolor="#18355C"> 
          <td style="border='1 #18355C'" onMouseOver="style.backgroundColor='#FFFFFF'; style.cursor='hand'; style.border='1 #18355C'" onMouseOut="style.backgroundColor='#719FC6'; style.border='1 #18355C';" height="21" bgcolor="#719FC6"> 
            <table width="100%" border="0" cellspacing="0" cellpadding="0">
              <tr> 
                <td class="Bolded"><img src="/newimages/misc/navarrow.gif" width="12" height="21"></td>
                <td bgcolor="#18355C" height="21" width="100%"><a href="/interviewindex.phtml" class="bluelinks" style="margin:0;"> 
                  <div><img src="/newimages/misc/1pix.gif" width="5" height="1" border="0">Interviews</div>
                  </a></td>
              </tr>
            </table>
          </td>
        </tr>
        <tr bgcolor="#18355C"> 
          <td style="border='1 #18355C'" onMouseOver="style.backgroundColor='#FFFFFF'; style.cursor='hand'; style.border='1 #18355C'" onMouseOut="style.backgroundColor='#719FC6'; style.border='1 #18355C';" height="21" bgcolor="#719FC6"> 
            <table width="100%" border="0" cellspacing="0" cellpadding="0">
              <tr> 
                <td class="Bolded"><img src="/newimages/misc/navarrow.gif" width="12" height="21"></td>
                <td bgcolor="#18355C" height="21" width="100%"><a href="/articleindex.phtml" class="bluelinks" style="margin:0;"> 
                  <div><img src="/newimages/misc/1pix.gif" width="5" height="1" border="0">Articles</div>
                  </a></td>
              </tr>
            </table>
          </td>
        </tr>
        <tr bgcolor="#18355C"> 
          <td style="border='1 #18355C'" onMouseOver="style.backgroundColor='#FFFFFF'; style.cursor='hand'; style.border='1 #18355C'" onMouseOut="style.backgroundColor='#719FC6'; style.border='1 #18355C';" height="21" bgcolor="#719FC6"> 
            <table width="100%" border="0" cellspacing="0" cellpadding="0">
              <tr> 
                <td class="Bolded"><img src="/newimages/misc/navarrow.gif" width="12" height="21"></td>
                <td bgcolor="#18355C" height="21" width="100%"><a href="/hardwareindex.phtml" class="bluelinks" style="margin:0;"> 
                  <div><img src="/newimages/misc/1pix.gif" width="5" height="1" border="0">Hardware</div>
                  </a></td>
              </tr>
            </table>
          </td>
        </tr>
        <tr bgcolor="#18355C"> 
          <td style="border='1 #18355C'" onMouseOver="style.backgroundColor='#FFFFFF'; style.cursor='hand'; style.border='1 #18355C'" onMouseOut="style.backgroundColor='#719FC6'; style.border='1 #18355C';" height="21" bgcolor="#719FC6"> 
            <table width="100%" border="0" cellspacing="0" cellpadding="0">
              <tr> 
                <td class="Bolded"><img src="/newimages/misc/navarrow.gif" width="12" height="21"></td>
                <td bgcolor="#18355C" height="21" width="100%"><a href="/fileindex.phtml" class="bluelinks" style="margin:0;"> 
                  <div><img src="/newimages/misc/1pix.gif" width="5" height="1" border="0">Downloads</div>
                  </a></td>
              </tr>
            </table>
          </td>
        </tr>
        <tr bgcolor="#18355C"> 
          <td style="border='1 #18355C'" onMouseOver="style.backgroundColor='#FFFFFF'; style.cursor='hand'; style.border='1 #18355C'" onMouseOut="style.backgroundColor='#719FC6'; style.border='1 #18355C';" height="21" bgcolor="#719FC6"> 
            <table width="100%" border="0" cellspacing="0" cellpadding="0">
              <tr> 
                <td class="Bolded"><img src="/newimages/misc/navarrow.gif" width="12" height="21"></td>
                <td bgcolor="#18355C" height="21" width="100%"><a href="http://www.mgoforum.com" class="bluelinks" style="margin:0;"> 
                  <div><img src="/newimages/misc/1pix.gif" width="5" height="1" border="0">MGOforums</div>
                  </a></td>
              </tr>
            </table>
          </td>
        </tr>
        <tr bgcolor="#18355C"> 
          <td style="border='1 #18355C'" onMouseOver="style.backgroundColor='#FFFFFF'; style.cursor='hand'; style.border='1 #18355C'" onMouseOut="style.backgroundColor='#719FC6'; style.border='1 #18355C';" height="21" bgcolor="#719FC6"> 
            <table width="100%" border="0" cellspacing="0" cellpadding="0">
              <tr> 
                <td class="Bolded"><img src="/newimages/misc/navarrow.gif" width="12" height="21"></td>
                <td bgcolor="#18355C" height="21" width="100%"><a href="http://www.mgoshop.com" class="bluelinks" style="margin:0;"> 
                  <div><img src="/newimages/misc/1pix.gif" width="5" height="1" border="0">MGOshop</div>
                  </a></td>
              </tr>
            </table>
          </td>
        </tr>
        <tr bgcolor="#18355C"> 
          <td style="border='1 #18355C'" onMouseOver="style.backgroundColor='#FFFFFF'; style.cursor='hand'; style.border='1 #18355C'" onMouseOut="style.backgroundColor='#719FC6'; style.border='1 #18355C';" height="21" bgcolor="#719FC6"> 
            <table width="100%" border="0" cellspacing="0" cellpadding="0">
              <tr> 
                <td class="Bolded"><img src="/newimages/misc/navarrow.gif" width="12" height="21"></td>
                <td bgcolor="#18355C" height="21" width="100%"><a href="/corporate/index.phtml" class="bluelinks" style="margin:0;"> 
                  <div><img src="/newimages/misc/1pix.gif" width="5" height="1" border="0">Corporate 
                    Info </div>
                  </a></td>
              </tr>
            </table>
          </td>
        </tr>
      </table>
    </td>
  </tr>
</table>

    </td>

    <TD width="642" valign="top" background="/newimages/backgrounds/middlecolumn_black.gif"> 

      <TABLE width="100%" border="0" cellspacing="0" cellpadding="0">

        <TR> 

          <td width="492" valign="top" background="/newimages/backgrounds/middlecolumn_black.gif"> 

            <table width="492" border="0" cellspacing="0" cellpadding="0" background="/newimages/misc/50x50pix.gif">

              <tr valign="top"> 
          <td background="/newimages/backgrounds/top3_titles_text.gif"> 

            <table width="164" border="0" cellspacing="0" cellpadding="0" background="/newimages/misc/50x50pix.gif">

              <tr> 

                <td><img src="/newimages/titles/article.gif" width="108" height="25"></td>

                <td background="/newimages/titles/resize.gif" width="100%" align="right" class="whitebolded">09/12</td>

                <td><img src="/newimages/titles/rightcorner.gif" width="6" height="25"></td>

              </tr>

            </table>

          

            <table width="164" border="0" cellspacing="0" cellpadding="0" background="/newimages/articles/resize.gif">

              <tr> 

                <td><img src="/newimages/articles/blueborder.gif" width="1" height="85"></td>

                <td><img src="/newimages/articles/blackborder.gif" width="1" height="85"></td>

                <td width="161"><a href="/articles.phtml?id=115350&language=en"><IMG src="http://193.45.143.9/scaled/w-161h-85-136378_patchpatrol.jpg" width="161" height="85" border="0"></a></td>

                <td><img src="/newimages/articles/blackborder.gif" width="1" height="85"></td>

              </tr>

            </table>

          

            <table width="164" border="0" cellspacing="0" cellpadding="0" background="/newimages/misc/50x50pix.gif">

              <tr>

                <td height="27" background="/newimages/backgrounds/top3_titles_27.gif" class="smalltext" width="100%">&nbsp;&nbsp;&nbsp;<a href="/articles.phtml?id=115350&language=en" class="articlelinks">Patch Patrol</a></td>

              </tr>

			  <TR>

				<TD>

				<table width="163" border="0" cellspacing="0" cellpadding="9" background="/newimages/misc/50x50pix.gif"><TR>

                <TD class="smalltext"></TD></TR>

				</table>

				</TD>

              </TR>

            </table>

          </td>

          <td background="/newimages/backgrounds/top3_titles_text.gif"> 

            <table width="164" border="0" cellspacing="0" cellpadding="0" background="/newimages/misc/50x50pix.gif">

              <tr> 

                <td><img src="/newimages/titles/article.gif" width="108" height="25"></td>

                <td background="/newimages/titles/resize.gif" width="100%" align="right" class="whitebolded">07/12</td>

                <td><img src="/newimages/titles/rightcorner.gif" width="6" height="25"></td>

              </tr>

            </table>

          

            <table width="164" border="0" cellspacing="0" cellpadding="0" background="/newimages/articles/resize.gif">

              <tr> 

                <td><img src="/newimages/articles/blueborder.gif" width="1" height="85"></td>

                <td><img src="/newimages/articles/blackborder.gif" width="1" height="85"></td>

                <td width="161"><a href="/articles.phtml?id=115293&language=en"><IMG src="http://193.45.143.9/scaled/w-161h-85-136327_pcintro_esport_q3.jpg" height="85" width="161" border="0"></a></td>

                <td><img src="/newimages/articles/blackborder.gif" width="1" height="85"></td>

              </tr>

            </table>

          

            <table width="164" border="0" cellspacing="0" cellpadding="0" background="/newimages/misc/50x50pix.gif">

              <tr>

                <td height="27" background="/newimages/backgrounds/top3_titles_27.gif" class="smalltext" width="100%">&nbsp;&nbsp;&nbsp;<a href="/articles.phtml?id=115293&language=en" class="articlelinks">A Diary of eSports</a></td>

              </tr>

			  <TR>

				<TD>

				<table width="164" border="0" cellspacing="0" cellpadding="9" background="/newimages/misc/50x50pix.gif"><TR>

                <TD class="smalltext">Our resident Dane Morten checks in with another report on <A TARGET="_blank" HREF="http://www.esports-europe.com/">eSports</A> and the ongoing Beta Tournament.</TD></TR>

				</table>

				</TD>

              </TR>

            </table>

          </td>

          <td background="/newimages/backgrounds/top3_titles_text.gif"> 

            <table width="164" border="0" cellspacing="0" cellpadding="0" background="/newimages/misc/50x50pix.gif">

              <tr> 

                <td><img src="/newimages/titles/article.gif" width="108" height="25"></td>

                <td background="/newimages/titles/resize.gif" width="100%" align="right" class="whitebolded">06/12&nbsp;&nbsp;</td>

              </tr>

            </table>

          

            <table width="164" border="0" cellspacing="0" cellpadding="0" background="/newimages/articles/resize.gif">

              <tr> 

                <td><img src="/newimages/articles/blueborder.gif" width="1" height="85"></td>

                <td width="161"><a href="/articles.phtml?id=115084&language=en"><IMG src="http://193.45.143.9/scaled/w-161h-85-136013_pcintro_blahblah.jpg>" height="85" width="161" border="0"></a></td>

                <td><img src="/newimages/articles/blackborder.gif" width="1" height="85"></td>

                <td><img src="/newimages/articles/blueborder.gif" width="1" height="85"></td>

              </tr>

            </table>

          

            <table width="164" border="0" cellspacing="0" cellpadding="0" background="/newimages/misc/50x50pix.gif">

              <tr>

				<td>

				<table width="164" border="0" cellspacing="0" cellpadding="0"><tr>

                <td height="27" background="/newimages/backgrounds/top3_titles_27.gif" class="smalltext" width="163">&nbsp;&nbsp;&nbsp;<a href="/articles.phtml?id=115084&language=en" class="articlelinks">Grand Theft Auto 3 Illegal?</a></td>

				<td width="1"><img src="/newimages/articles/blueborder.gif" width="1" height="27"></td>

                </tr>

				</table>

				</td>

			  </tr>

			</table>

			<table width="164" border="0" cellspacing="0" cellpadding="0" background="/newimages/misc/50x50pix.gif">

			  <TR>

				<TD>

				<table width="163" border="0" cellspacing="0" cellpadding="9" background="/newimages/misc/50x50pix.gif"><TR>

                <TD class="smalltext" valign="top">The censors in Australia have hit out at games like AvP2, Ghost Recon and GTA3.  So what's the sory?  They're only games, right?</TD></TR>

				</table>

				</TD>

                <td background="/newimages/articles/blueborder.gif"><img src="/newimages/misc/1pix.gif" width="1" height="1"></td>

              </TR>

            </table>

          </td>
 </TR>

            </TABLE>

            <table width="100%" border="0" cellspacing="0" cellpadding="0" background="/newimages/titles/lowresize.gif">

              <tr> 

                <td width="100%"><img src="/newimages/titles/archive.gif"></td>

                <td align="right"><img src="/newimages/titles/lowrightcorner.gif" width="6" height="24"></td>

                <td><img src="/newimages/articles/blueborder.gif" width="1" height="24"></td>

              </tr>

            </table>

            <table width="100%" border="0" cellspacing="0" cellpadding="0" background="/newimages/backgrounds/middlecolumn_blue.gif">

              <form method="post" action="/articles.phtml">

                <tr> 

                  <td height="40"><img src="/newimages/misc/1pix.gif" width="12" height="8"></td>

                  <td height="40" width="100%" nowrap><span class="bluebolded">Search Articles:&nbsp;</span>&nbsp; 

                    <input type="text" name="search" class="formbody" size="14" maxlength="50" value="">

                    &nbsp; 

                    <select name="rel_category" class="formbody">

                      <option selected value="0">All</option>
<option  value="1">Action</option>
<option  value="15">Adventure</option>
<option  value="20">eSports in the Press</option>
<option  value="3">Hardware</option>
<option  value="18">News</option>
<option  value="16">Other</option>
<option  value="14">Peripherals</option>
<option  value="19">Press Release</option>
<option  value="17">Puzzle</option>
<option  value="12">Racing</option>
<option  value="11">RPG</option>
<option  value="2">Simulation</option>
<option  value="4">Software</option>
<option  value="8">Sport</option>
<option  value="9">Strategy</option>

                    </select>

                    &nbsp; &nbsp; 

                    <input type="image" border="0" name="imageField2" src="/newimages/buttons/search_go.gif" width="24" height="22" align="top">

                  </td>

                  <td align="right"><img src="/newimages/misc/1pix.gif" width="12" height="8"></td>

                </tr>

              </form>

            </table>

            <img src="/newimages/misc/492blueborder.gif" width="492" height="1"><br>

            <TABLE width="100%" border="0" cellspacing="0" cellpadding="0" background="/newimages/misc/50x50pix.gif">

              <TR>

                <TD><IMG src="/newimages/misc/1pix.gif" width="12" height="8"></TD>

                <TD class="smalltext" height="30" width="100%"> 

                  
                  Now displaying the 15 latest Articles. 

                  
                </TD>

                <TD><IMG src="/newimages/misc/1pix.gif" width="12" height="8"></TD>

              </TR>

            </TABLE>

            <TABLE width="100%" border="0" cellspacing="0" cellpadding="0" background="/newimages/misc/50x50pix.gif">

              <tr> 

                <td class="smalltext" valign="top">&nbsp;</td>

                <td width="55%" class="smalltext" valign="top">&nbsp;</td>

                <td class="smalltext" valign="top" width="15%">&nbsp;</td>

                <td class="smalltext" valign="top" width="20%">&nbsp;</td>

                <td class="smalltext" valign="top" width="10%">&nbsp;</td>

                <td class="smalltext" valign="top">&nbsp;</td>

              </tr>

              <tr> 

                <td class="smalltext" valign="top"><img src="/newimages/misc/1pix.gif" width="12" height="1"></td>

                <td height="30" class="Bolded" valign="top" nowrap> 

                  
                  <a class="brightlinks" href="/articleindex.phtml?search=&rel_category=&order=header ASC"> 

                  Title
                  </a><br>

                </td>

                <td class="Bolded" valign="top" nowrap> 

                  
                  <a class="brightlinks" href="/articleindex.phtml?search=&rel_category=&order="> 

                  Added
                  </a></td>

                <td class="Bolded" valign="top" nowrap> 

                  
                  <a class="brightlinks" href="/articleindex.phtml?search=&rel_category=&order=rel_category"> 

                  Category
                  </a></td>

                <td class="Bolded" valign="top" nowrap> C's</td>

                <td class="smalltext" valign="top"><img src="/newimages/misc/1pix.gif" width="12" height="8"></td>

              </tr>

              
              <TR> 

                <TD class="smalltext" valign="top">&nbsp;</TD>

                <TD height="25" nowrap><A href="/articles.phtml?id=115350&language=en">• Patch Patrol</A></TD>

                <TD>09/12</TD>

                <TD>Action</TD>

                <TD valign="top" class="gray_normal">0</TD>

                <TD class="smalltext">&nbsp;</TD>

              </TR>

              <TR> 

                <TD class="smalltext" valign="top">&nbsp;</TD>

                <TD height="25" nowrap><A href="/articles.phtml?id=115293&language=en">• A Diary of eSports</A></TD>

                <TD>07/12</TD>

                <TD>Action</TD>

                <TD valign="top" class="gray_normal">0</TD>

                <TD class="smalltext">&nbsp;</TD>

              </TR>

              <TR> 

                <TD class="smalltext" valign="top">&nbsp;</TD>

                <TD height="25" nowrap><A href="/articles.phtml?id=115084&language=en">• Grand Theft Auto 3 Illegal?</A></TD>

                <TD>06/12</TD>

                <TD>Action</TD>

                <TD valign="top" class="gray_normal">1</TD>

                <TD class="smalltext">&nbsp;</TD>

              </TR>

              <TR> 

                <TD class="smalltext" valign="top">&nbsp;</TD>

                <TD height="25" nowrap><A href="/articles.phtml?id=114186&language=en">• A Diary of eSports</A></TD>

                <TD>30/11</TD>

                <TD>Action</TD>

                <TD valign="top" class="gray_normal">1</TD>

                <TD class="smalltext">&nbsp;</TD>

              </TR>

              <TR> 

                <TD class="smalltext" valign="top">&nbsp;</TD>

                <TD height="25" nowrap><A href="/articles.phtml?id=114161&language=en">• Patch Patrol</A></TD>

                <TD>30/11</TD>

                <TD>Action</TD>

                <TD valign="top" class="gray_normal">0</TD>

                <TD class="smalltext">&nbsp;</TD>

              </TR>

              <TR> 

                <TD class="smalltext" valign="top">&nbsp;</TD>

                <TD height="25" nowrap><A href="/articles.phtml?id=113131&language=en">• Patch Patrol</A></TD>

                <TD>23/11</TD>

                <TD>Action</TD>

                <TD valign="top" class="gray_normal">0</TD>

                <TD class="smalltext">&nbsp;</TD>

              </TR>

              <TR> 

                <TD class="smalltext" valign="top">&nbsp;</TD>

                <TD height="25" nowrap><A href="/articles.phtml?id=112760&language=en">• Jedi Outcast Q&A</A></TD>

                <TD>21/11</TD>

                <TD>Action</TD>

                <TD valign="top" class="gray_normal">1</TD>

                <TD class="smalltext">&nbsp;</TD>

              </TR>

              <TR> 

                <TD class="smalltext" valign="top">&nbsp;</TD>

                <TD height="25" nowrap><A href="/articles.phtml?id=112274&language=en">• Patch Patrol</A></TD>

                <TD>17/11</TD>

                <TD>Action</TD>

                <TD valign="top" class="gray_normal">0</TD>

                <TD class="smalltext">&nbsp;</TD>

              </TR>

              <TR> 

                <TD class="smalltext" valign="top">&nbsp;</TD>

                <TD height="25" nowrap><A href="/articles.phtml?id=112086&language=en">• Xbox in Oz!</A></TD>

                <TD>16/11</TD>

                <TD>Action</TD>

                <TD valign="top" class="gray_normal">1</TD>

                <TD class="smalltext">&nbsp;</TD>

              </TR>

              <TR> 

                <TD class="smalltext" valign="top">&nbsp;</TD>

                <TD height="25" nowrap><A href="/articles.phtml?id=112001&language=en">• Taking the Reigns</A></TD>

                <TD>15/11</TD>

                <TD>Action</TD>

                <TD valign="top" class="gray_normal">0</TD>

                <TD class="smalltext">&nbsp;</TD>

              </TR>

              <TR> 

                <TD class="smalltext" valign="top">&nbsp;</TD>

                <TD height="25" nowrap><A href="/articles.phtml?id=111267&language=en">• XBox xplored further</A></TD>

                <TD>12/11</TD>

                <TD>Action</TD>

                <TD valign="top" class="gray_normal">0</TD>

                <TD class="smalltext">&nbsp;</TD>

              </TR>

              <TR> 

                <TD class="smalltext" valign="top">&nbsp;</TD>

                <TD height="25" nowrap><A href="/articles.phtml?id=111139&language=en">• Patch Patrol</A></TD>

                <TD>09/11</TD>

                <TD>Action</TD>

                <TD valign="top" class="gray_normal">0</TD>

                <TD class="smalltext">&nbsp;</TD>

              </TR>

              <TR> 

                <TD class="smalltext" valign="top">&nbsp;</TD>

                <TD height="25" nowrap><A href="/articles.phtml?id=111137&language=en">• PCs Vs Console</A></TD>

                <TD>09/11</TD>

                <TD>Action</TD>

                <TD valign="top" class="gray_normal">0</TD>

                <TD class="smalltext">&nbsp;</TD>

              </TR>

              <TR> 

                <TD class="smalltext" valign="top">&nbsp;</TD>

                <TD height="25" nowrap><A href="/articles.phtml?id=111017&language=en">• Demo Watch</A></TD>

                <TD>08/11</TD>

                <TD>Action</TD>

                <TD valign="top" class="gray_normal">0</TD>

                <TD class="smalltext">&nbsp;</TD>

              </TR>

              <TR> 

                <TD class="smalltext" valign="top">&nbsp;</TD>

                <TD height="25" nowrap><A href="/articles.phtml?id=110693&language=en">• PC Gaming as Good Value</A></TD>

                <TD>06/11</TD>

                <TD>Action</TD>

                <TD valign="top" class="gray_normal">0</TD>

                <TD class="smalltext">&nbsp;</TD>

              </TR>

            </TABLE>

            <img src="/newimages/misc/492blueborder.gif" width="492" height="1"><br>

            <TABLE cellspacing="0" cellpadding="12" border="0" width="100%" background="/newimages/backgrounds/middlecolumn_blue.gif">

              <TR> 

                <TD class="smalltext"> 

                  
                  For more articles and sort options, visit the <A href="/articles.phtml">archive 

                  &raquo;</A> 

                  
                </TD>

              </TR>

</TABLE>

          </TD>

          <TD align="center" valign="top" background="/newimages/resizes/rightnav_brightblue.gif" width="150"> 

            <TABLE width="100%" border="0" cellspacing="0" cellpadding="0">

              <TR> 

                <TD><IMG src="newimages/columns/feedback.gif" width="150" height="25"></TD>

              </TR>

            </TABLE>

            <table width="148" border="0" cellspacing="0" cellpadding="0" background="/newimages/misc/50x50pix.gif">

              <tr> 

                <td height="25" class="smalltext">&nbsp;<img src="/newimages/misc/yellowarrow.gif" width="9" height="11"><a href="mailto:feedback@mgon.com" class="brightlinks"> 

                  Submit Feedback
                  !</a></td>

              </tr>

              <tr> 

                <td height="25" class="smalltext">&nbsp;<img src="/newimages/misc/yellowarrow.gif" width="9" height="11"><a href="mailto:articles@mgon.com" class="brightlinks"> 

                  Suggest Articles
                  </a></td>

              </tr>

              <tr> 

                <td height="25" class="smalltext">&nbsp;<img src="/newimages/misc/yellowarrow.gif" width="9" height="11"> 

                  
                  <a href="http://www.mgoforum.com/forumdisplay.php?&forumid=44" class="brightlinks">Discuss 

                  This!</a> 

                  
                </td>

              </tr>

            </table>

          </TD>

        </TR>

      </TABLE>

    </TD>

  </TR>

</TABLE>

 
<table width="772" border="0" cellspacing="0" cellpadding="0" align="center">
  <tr>
    <td><img src="/newimages/bottom/copyright.gif" width="621" height="30" border="0" usemap="#Map2"></td>
    <td><a href="/"><img src="/newimages/bottom/home.gif" width="75" height="30" border="0"></a></td>
    <td><a href="#top"><img src="/newimages/bottom/top.gif" width="76" height="30" border="0"></a></td>
  </tr>
</table>
<TABLE width="772" border="0" cellspacing="0" cellpadding="0" height="90" background="/images2/misc/50x50pix.gif" align="center">
  <TR bgcolor="#000000" align="center"> 
    <TD class="smalltext"><SCRIPT language="JavaScript"
src="http://adtegrity.spinbox.net/?DC=Mgon+Bottom&JS=Y&TARGET=_new">
</SCRIPT><NOSCRIPT><A href="http://adtegrity.spinbox.net/?SHT=Mgon+Bottom" target="_new"
height="468" width="60"><IMG src="http://adtegrity.spinbox.net/?SIT=Mgon+Bottom" border="0"></A></NOSCRIPT></TD>
  </TR>
</TABLE>
<map name="Map">
  <area shape="rect" coords="387,7,495,25" href="/privacy.phtml">
</map>
<map name="Map2">
  <area shape="rect" coords="384,4,496,26" href="/privacy">
</map>
  

<!--Bottom Layer-->
      <LAYER SRC="http://ad.se.doubleclick.net/adl/mgon.com/;sz=140x350;ord=1008316750?" bgcolor="#000000" width="140" height="350" visibility="hidden" onLoad="moveToAbsolute(layer1.pageX,layer1.pageY);clip.height=350;clip.width=140; visibility='show';"></LAYER>      <LAYER SRC="http://ad.se.doubleclick.net/adl/mgon.com/;sz=140x350;ord=1008316750?" bgcolor="#000000" width="140" height="350" visibility="hidden" onLoad="moveToAbsolute(layer2.pageX,layer2.pageY);clip.height=350;clip.width=140; visibility='show';"></LAYER>      <LAYER SRC="http://ad.se.doubleclick.net/adl/mgon.com/;sz=468x60;ord=1008316750?" bgcolor="#000000" width="468" height="60" visibility="hidden" onLoad="moveToAbsolute(layer3.pageX,layer3.pageY);clip.height=60;clip.width=468; visibility='show';"></LAYER><!--End Bottom Layer-->
</BODY>

</HTML>









