<!--
                 This page has been created by Renaissance IT
   Renaissance Internet Technologies Copyright (c) 1999 All Rights Reserved.

             for more info on our products, please visit :
                        http://www.renaissance.nl/

	This script has been written by Roy Boverhof <rboverhof@renaissance.nl>
	
        Pagename                : pottery.html
        Last Updated    		: 28-7-1999
-->

<HTML>
<HEAD>
	<TITLE>the Seekers of Lore : Gorthag Bashinfletcher’s Treatise on Disciplines J</TITLE>
</HEAD>

<BODY BGCOLOR="#000000" TEXT="#000000" LINK="#FFF000">
<DIV ALIGN="CENTER">
<BR>
<!-- FGB Banner Code -->
<SCRIPT LANGUAGE="JavaScript">
   <!-- Hide from old browsers
   now = new Date();
   random = now.getTime();
     
   // Modify to reflect site specifics
   site = "http://ds.cybereps.com";
   target = "/SITE=FGN/AREA=EQLORE/AAMSZ=BANNER";
   
   document.write('<IFRAME SRC="' + site + '/hserver/acc_random=' + random + target + '"');
   document.write(' NORESIZE SCROLLING=NO HSPACE=0 VSPACE=0 FRAMEBORDER=0 MARGINHEIGHT=0 MARGINWIDTH=0 WIDTH=468 HEIGHT=60>');
   
   document.write('<SCR');
   document.write('IPT SRC="' + site + '/jnserver/acc_random=' + random + target + '">');
   document.write('</SCR');
   document.write('IPT>');
   
   document.write('</IFRAME>');
   // End Hide -->
 </SCRIPT>
 <NOSCRIPT> 
   <A HREF="http://ds.cybereps.com/accipiter/adclick/SITE=FGN/AREA=EQLORE/AAMSZ=BANNER">
   <IMG SRC="http://ds.cybereps.com/accipiter/nserver/SITE=FGN/AREA=EQLORE/AAMSZ=BANNER" border="0"></A>
 </NOSCRIPT>
<!-- END FGB Banner Code --><BR>
<TABLE CELLSPACING = 0 CELLPADDING = 0 BORDER = 0>
<TR>
	<TD width="63"><IMG SRC = "../graphics/topc000.jpg" WIDTH = 63 HEIGHT = 87></TD>
	<TD width="473"><IMG SRC = "../graphics/topc001.jpg" WIDTH = 473 HEIGHT = 87></TD>
	<TD width="64"><IMG SRC = "../graphics/topc002.jpg" WIDTH = 64 HEIGHT = 87></TD>
</TR>
	<TD width="63"></TD>
	<TD BGCOLOR="#BEA279" width="460">
	<TABLE WIDTH="460">
	<TR>
		<TD>
			<B><FONT FACE="Arial" SIZE=4>Treatise on Disciplines J</B></font>
			<BR>
			<FONT SIZE=3><B>By Gorthag Bashinfletcher</B></font>
			<P>
			<font face="Verdana" size="3"><FONT SIZE="+1">D</FONT>isciplines are special abilities, with a long re-use timer,
			that melee and hybrid classes begin to gain as early as level 30, though the
			majority are learned after level 50. While the time to reuse these abilities is
			incredibly long, generally 60-72 minutes, the re-use time decreases as your
			level advances, with the shortest re-use time being attained at level 60. The
			actual effects of discipline use will not be shown on your character profile,
			however, anyone who has seen ‘Soandso feels like a killing machine’, followed
			by an incredible string of critical hits, will attest to the fact that some
			disciplines are incredibly useful when used at the proper time. The following
			is a listing of all current disciplines, and their effects, organized by class.
			For quick in game reference, type /di to see a list of all discipline use
			commands for your class. To use, simply type /di &lt;discipline name&gt;.
			Thanks go to the fine people at Caster’s Realm for providing the majority of
			source material in this compilation.</font>
			
			<BR><BR>
			<font face="Verdana"><b>Bard</b></font>
			
			&nbsp;
			
			<table border=1 cellspacing=0 cellpadding=0>
			 <tr>
			  <td width=91 valign=top>
			  <font face="Verdana" size="-1"><B>Discipline</B></font>
			  </td>
			  <td width=46 valign=top>
			  <font face="Verdana" size="-1"><B>Level</B></font>
			  </td>
			  <td width=181 valign=top>
			  <font face="Verdana" size="-1"><B>Effect</B></font>
			  </td>
			  <td width=81 valign=top>
			  <font face="Verdana" size="-1"><B>Duration</B></font>
			  </td>
			  <td width=91 valign=top>
			  <font face="Verdana" size="-1"><B>Delay</B></font>
			  </td>
			  <td width=100 valign=top>
			  <font face="Verdana" size="-1"><B>L60 Delay</B></font>
			  </td>
			 </tr>
			 <tr>
			  <td width=91>
			  <font face="Verdana" size="-1"><B>Resistant</B></font>
			  </td>
			  <td width=46>
			  <font face="Verdana" size="-1"><B>51</B></font>
			  </td>
			  <td width=181 valign=top>
			  <font face="Verdana" size="-1"><B>Add 10 to all resists</B></font>
			  </td>
			  <td width=81 valign=top>
			  <font face="Verdana" size="-1"><B>1 min</B></font>
			  </td>
			  <td width=91 valign=top>
			  <font face="Verdana" size="-1"><B>60 min</B></font>
			  </td>
			  <td width=100 valign=top>
			  <font face="Verdana" size="-1"><B>51 min</B></font>
			  </td>
			 </tr>
			 <tr>
			  <td width=91 valign=top>
			  <font face="Verdana" size="-1"><B>Fearless</B></font>
			  </td>
			  <td width=46 valign=top>
			  <font face="Verdana" size="-1"><B>54</B></font>
			  </td>
			  <td width=181 valign=top>
			  <font face="Verdana" size="-1"><B>Immunity to fear effects</B></font>
			  </td>
			  <td width=81 valign=top>
			  <font face="Verdana" size="-1"><B>11 sec</B></font>
			  </td>
			  <td width=91 valign=top>
			  <font face="Verdana" size="-1"><B>60 min</B></font>
			  </td>
			  <td width=100 valign=top>
			  <font face="Verdana" size="-1"><B>54 min</B></font>
			  </td>
			 </tr>
			 <tr>
			  <td width=91 valign=top>
			  <font face="Verdana" size="-1"><B>Deft Dance</B></font>
			  </td>
			  <td width=46 valign=top>
			  <font face="Verdana" size="-1"><B>55</B></font>
			  </td>
			  <td width=181 valign=top>
			  <font face="Verdana" size="-1"><B>Automatic dodge and dual wield</B></font>
			  </td>
			  <td width=81 valign=top>
			  <font face="Verdana" size="-1"><B>10 sec</B></font>
			  </td>
			  <td width=91 valign=top>
			  <font face="Verdana" size="-1"><B>72 min</B></font>
			  </td>
			  <td width=100 valign=top>
			  <font face="Verdana" size="-1"><B>67 min</B></font>
			  </td>
			 </tr>
			 <tr>
			  <td width=91 valign=top>
			  <font face="Verdana" size="-1"><B>Puretone</B></font>
			  </td>
			  <td width=46 valign=top>
			  <font face="Verdana" size="-1"><B>60</B></font>
			  </td>
			  <td width=181 valign=top>
			  <font face="Verdana" size="-1"><B>Effect as if wielding best instrument of every type</B></font>
			  </td>
			  <td width=81 valign=top>
			  <font face="Verdana" size="-1"><B>2 min</B></font>
			  </td>
			  <td width=91 valign=top>
			  <font face="Verdana" size="-1"><B>72 min</B></font>
			  </td>
			  <td width=100 valign=top>
			  <font face="Verdana" size="-1"><B>72 min</B></font>
			  </td>
			 </tr>
			</table>
			
			<p class="MsoNormal">&nbsp;
			
			<font face="Verdana"><b>Monk</b></B></font>
			
			&nbsp;
			
			<table border=1 cellspacing=0 cellpadding=0>
			 <tr>
			  <td width=115 valign=top>
			  <font face="Verdana" size="-1"><B>Discipline</B></font>
			  </td>
			  <td width=60 valign=top>
			  <font face="Verdana" size="-1"><B>Level</B></font>
			  </td>
			  <td width=192 valign=top>
			  <font face="Verdana" size="-1"><B>Effect</B></font>
			  </td>
			  <td width=72 valign=top>
			  <font face="Verdana" size="-1"><B>Duration</B></font>
			  </td>
			  <td width=60 valign=top>
			  <font face="Verdana" size="-1"><B>Delay</B></font>
			  </td>
			  <td width=91 valign=top>
			  <font face="Verdana" size="-1"><B>L60 Delay</B></font>
			  </td>
			 </tr>
			 <tr>
			  <td width=115 valign=top>
			  <font face="Verdana" size="-1"><B>Resistant</B></font>
			  </td>
			  <td width=60 valign=top>
			  <font face="Verdana" size="-1"><B>30</B></font>
			  </td>
			  <td width=192 valign=top>
			  <font face="Verdana" size="-1"><B>+3 resist all, +10 at 50+</B></font>
			  </td>
			  <td width=72 valign=top>
			  <font face="Verdana" size="-1"><B>1 min</B></font>
			  </td>
			  <td width=60 valign=top>
			  <font face="Verdana" size="-1"><B>60 min</B></font>
			  </td>
			  <td width=91 valign=top>
			  <font face="Verdana" size="-1"><B>30 min</B></font>
			  </td>
			 </tr>
			 <tr>
			  <td width=115 valign=top>
			  <font face="Verdana" size="-1"><B>Fearless</B></font>
			  </td>
			  <td width=60 valign=top>
			  <font face="Verdana" size="-1"><B>40</B></font>
			  </td>
			  <td width=192 valign=top>
			  <font face="Verdana" size="-1"><B>Immunity to fear effects</B></font>
			  </td>
			  <td width=72 valign=top>
			  <font face="Verdana" size="-1"><B>11 sec</B></font>
			  </td>
			  <td width=60 valign=top>
			  <font face="Verdana" size="-1"><B>60 min</B></font>
			  </td>
			  <td width=91 valign=top>
			  <font face="Verdana" size="-1"><B>40 min</B></font>
			  </td>
			 </tr>
			 <tr>
			  <td width=115 valign=top>
			  <font face="Verdana" size="-1"><B>Stone Stance</B></font>
			  </td>
			  <td width=60 valign=top >
			  <font face="Verdana" size="-1"><B>51</B></font>
			  </td>
			  <td width=192 valign=top>
			  <font face="Verdana" size="-1"><B>Reduce physical damage taken by 90%</B></font>
			  </td>
			  <td width=72 valign=top>
			  <font face="Verdana" size="-1"><B>12 sec</B></font>
			  </td>
			  <td width=60 valign=top>
			  <font face="Verdana" size="-1"><B>12 min</B></font>
			  </td>
			  <td width=91 valign=top>
			  <font face="Verdana" size="-1"><B>3 min</B></font>
			  </td>
			 </tr>
			 <tr>
			  <td width=115 valign=top >
			  <font face="Verdana" size="-1"><B>Thunder Kick</B></font>
			  </td>
			  <td width=60 valign=top>
			  <font face="Verdana" size="-1"><B>52</B></font>
			  </td>
			  <td width=192 valign=top>
			  <font face="Verdana" size="-1"><B>Increase next flying kick damage</B></font>
			  </td>
			  <td width=72 valign=top>
			  <font face="Verdana" size="-1"><B>Instant</B></font>
			  </td>
			  <td width=60 valign=top>
			  <font face="Verdana" size="-1"><B>7 min</B></font>
			  </td>
			  <td width=91 valign=top>
			  <font face="Verdana" size="-1"><B>1 min</B></font>
			  </td>
			 </tr>
			 <tr>
			  <td width=115 valign=top >
			  <font face="Verdana" size="-1"><B>Whirlwind</B></font>
			  </td>
			  <td width=60 valign=top>
			  <font face="Verdana" size="-1"><B>53</B></font>
			  </td>
			  <td width=192 valign=top>
			  <font face="Verdana" size="-1"><B>Automatic Riposte</B></font>
			  </td>
			  <td width=72 valign=top>
			  <font face="Verdana" size="-1"><B>9 sec</B></font>
			  </td>
			  <td width=60 valign=top>
			  <font face="Verdana" size="-1"><B>60 min</B></font>
			  </td>
			  <td width=91 valign=top>
			  <font face="Verdana" size="-1"><B>53 min</B></font>
			  </td>
			 </tr>
			 <tr>
			  <td width=115 valign=top >
			  <font face="Verdana" size="-1"><B>Void Dance</B></font>
			  </td>
			  <td width=60 valign=top>
			  <font face="Verdana" size="-1"><B>54</B></font>
			  </td>
			  <td width=192 valign=top>
			  <font face="Verdana" size="-1"><B>Can not be hit in melee</B></font>
			  </td>
			  <td width=72 valign=top>
			  <font face="Verdana" size="-1"><B>8 sec</B></font>
			  </td>
			  <td width=60 valign=top>
			  <font face="Verdana" size="-1"><B>60 min</B></font>
			  </td>
			  <td width=91 valign=top>
			  <font face="Verdana" size="-1"><B>54 min</B></font>
			  </td>
			 </tr>
			 <tr>
			  <td width=115 valign=top >
			  <font face="Verdana" size="-1"><B>Inner Flame</B></font>
			  </td>
			  <td width=60 valign=top>
			  <font face="Verdana" size="-1"><B>56</B></font>
			  </td>
			  <td width=192 valign=top>
			  <font face="Verdana" size="-1"><B>All hits minimum 4 times base damage</B></font>
			  </td>
			  <td width=72 valign=top>
			  <font face="Verdana" size="-1"><B>12 sec</B></font> 
			  </td>
			  <td width=60 valign=top>
			  <font face="Verdana" size="-1"><B>30 min</B></font>
			  </td>
			  <td width=91 valign=top>
			  <font face="Verdana" size="-1"><B>26 min</B></font>
			  </td>
			 </tr>
			 <tr>
			  <td width=115 valign=top >
			  <font face="Verdana" size="-1"><B>100 Fist</B></font>
			  </td>
			  <td width=60 valign=top>
			  <font face="Verdana" size="-1"><B>57</B></font>
			  </td>
			  <td width=192 valign=top>
			  <font face="Verdana" size="-1"><B>Haste, stacks with all haste</B></font>
			  </td>
			  <td width=72 valign=top>
			  <font face="Verdana" size="-1"><B>15 sec</B></font>
			  </td>
			  <td width=60 valign=top>
			  <font face="Verdana" size="-1"><B>30 min</B></font>
			  </td>
			  <td width=91 valign=top>
			  <font face="Verdana" size="-1"><B>27 min</B></font>
			  </td>
			 </tr>
			 <tr>
			  <td width=115 valign=top >
			  <font face="Verdana" size="-1"><B>Ashenhand</B></font>
			  </td>
			  <td width=60 valign=top>
			  <font face="Verdana" size="-1"><B>59</B></font>
			  </td>
			  <td width=192 valign=top>
			  <font face="Verdana" size="-1"><B>Next Eagle stick – increased dmg, chance for instant kill</B></font>
			  </td>
			  <td width=72 valign=top>
			  <font face="Verdana" size="-1"><B>Instant</B></font>
			  </td>
			  <td width=60 valign=top>
			  <font face="Verdana" size="-1"><B>72 min</B></font>
			  </td>
			  <td width=91 valign=top>
			  <font face="Verdana" size="-1"><B>71 min</B></font>
			  </td>
			 </tr>
			 <tr>
			  <td width=115 valign=top >
			  <font face="Verdana" size="-1"><B>Silent Fist</B></font>
			  </td>
			  <td width=60 valign=top>
			  <font face="Verdana" size="-1"><B>60</B></font>
			  </td>
			  <td width=192 valign=top>
			  <font face="Verdana" size="-1"><B>Next Dragon punch – increased dmg, stun chance</B></font>
			  </td>
			  <td width=72 valign=top>
			  <font face="Verdana" size="-1"><B>Instant</B></font>
			  </td>
			  <td width=60 valign=top>
			  <font face="Verdana" size="-1"><B>7 min</B></font>
			  </td>
			  <td width=91 valign=top>
			  <font face="Verdana" size="-1"><B>6 min</B></font>
			  </td>
			 </tr>
			</table>
			
			<p class="MsoNormal">&nbsp;
			
			<font face="Verdana"><b>Paladin</b></B></font>
			
			&nbsp;
			
			<table border=1 cellspacing=0 cellpadding=0>
			 <tr>
			  <td width=115 valign=top>
			  <font face="Verdana" size="-1"><B>Discipline</B></font>
			  </td>
			  <td width=60 valign=top>
			  <font face="Verdana" size="-1"><B>Level</B></font>
			  </td>
			  <td width=192 valign=top>
			  <font face="Verdana" size="-1"><B>Effect</B></font>
			  </td>
			  <td width=72 valign=top >
			  <font face="Verdana" size="-1"><B>Duration</B></font>
			  </td>
			  <td width=60 valign=top>
			  <font face="Verdana" size="-1"><B>Delay</B></font>
			  </td>
			  <td width=91 valign=top>
			  <font face="Verdana" size="-1"><B>L60 Delay</B></font>
			  </td>
			 </tr>
			 <tr>
			  <td width=115 valign=top >
			  <font face="Verdana" size="-1"><B>Resistant</B></font>
			  </td>
			  <td width=60 valign=top>
			  <font face="Verdana" size="-1"><B>51</B></font>
			  </td>
			  <td width=192 valign=top>
			  <font face="Verdana" size="-1"><B>+10 all resists</B></font>
			  </td>
			  <td width=72 valign=top>
			  <font face="Verdana" size="-1"><B>1 min</B></font>
			  </td>
			  <td width=60 valign=top>
			  <font face="Verdana" size="-1"><B>60 min</B></font>
			  </td>
			  <td width=91 valign=top>
			  <font face="Verdana" size="-1"><B>51 min</B></font>
			  </td>
			 </tr>
			 <tr>
			  <td width=115 valign=top >
			  <font face="Verdana" size="-1"><B>Fearless</B></font>
			  </td>
			  <td width=60 valign=top>
			  <font face="Verdana" size="-1"><B>54</B></font>
			  </td>
			  <td width=192 valign=top>
			  <font face="Verdana" size="-1"><B>Immunity to fear effects</B></font>
			  </td>
			  <td width=72 valign=top>
			  <font face="Verdana" size="-1"><B>11 sec</B></font>
			  </td>
			  <td width=60 valign=top>
			  <font face="Verdana" size="-1"><B>60 min</B></font>
			  </td>
			  <td width=91 valign=top>
			  <font face="Verdana" size="-1"><B>54 min</B></font>
			  </td>
			 </tr>
			 <tr>
			  <td width=115 valign=top >
			  <font face="Verdana" size="-1"><B>Holy Forge</B></font>
			  </td>
			  <td width=60 valign=top>
			  <font face="Verdana" size="-1"><B>55</B></font>
			  </td>
			  <td width=192 valign=top>
			  <font face="Verdana" size="-1"><B>Allow critical/crippling hits, 3x normal chances</B></font>
			  </td>
			  <td width=72 valign=top>
			  <font face="Verdana" size="-1"><B>2 min</B></font>
			  </td>
			  <td width=60 valign=top>
			  <font face="Verdana" size="-1"><B>72 min</B></font>
			  </td>
			  <td width=91 valign=top>
			  <font face="Verdana" size="-1"><B>67 min</B></font>
			  </td>
			 </tr>
			 <tr>
			  <td width=115 valign=top >
			  <font face="Verdana" size="-1"><B>Sanctification</B></font>
			  </td>
			  <td width=60 valign=top>
			  <font face="Verdana" size="-1"><B>60</B></font>
			  </td>
			  <td width=192 valign=top>
			  <font face="Verdana" size="-1"><B>Immunity to most harmful spells</B></font>
			  </td>
			  <td width=72 valign=top>
			  <font face="Verdana" size="-1"><B>10 sec</B></font>
			  </td>
			  <td width=60 valign=top>
			  <font face="Verdana" size="-1"><B>72 min</B></font>
			  </td>
			  <td width=91 valign=top>
			  <font face="Verdana" size="-1"><B>72 min</B></font>
			  </td>
			 </tr>
			</table>
			
			<p class="MsoNormal">&nbsp;
			
			<font face="Verdana"><b>Ranger</b></B></font>
			
			&nbsp;
			
			<table border=1 cellspacing=0 cellpadding=0>
			 <tr>
			  <td width=115 valign=top>
			  <font face="Verdana" size="-1"><B>Discipline</B></font>
			  </td>
			  <td width=60 valign=top>
			  <font face="Verdana" size="-1"><B>Level</B></font>
			  </td>
			  <td width=192 valign=top>
			  <font face="Verdana" size="-1"><B>Effect</B></font>
			  </td>
			  <td width=72 valign=top >
			  <font face="Verdana" size="-1"><B>Duration</B></font>
			  </td>
			  <td width=60 valign=top>
			  <font face="Verdana" size="-1"><B>Delay</B></font>
			  </td>
			  <td width=91 valign=top>
			  <font face="Verdana" size="-1"><B>L60 Delay</B></font>
			  </td>
			 </tr>
			 <tr>
			  <td width=115 valign=top >
			  <font face="Verdana" size="-1"><B>Resistant</B></font>
			  </td>
			  <td width=60 valign=top>
			  <font face="Verdana" size="-1"><B>51</B></font>
			  </td>
			  <td width=192 valign=top>
			  <font face="Verdana" size="-1"><B>+10 all resists</B></font>
			  </td>
			  <td width=72 valign=top>
			  <font face="Verdana" size="-1"><B>1 min</B></font>
			  </td>
			  <td width=60 valign=top>
			  <font face="Verdana" size="-1"><B>60 min</B></font>
			  </td>
			  <td width=91 valign=top>
			  <font face="Verdana" size="-1"><B>51 min</B></font>
			  </td>
			 </tr>
			 <tr>
			  <td width=115 valign=top >
			  <font face="Verdana" size="-1"><B>Fearless</B></font>
			  </td>
			  <td width=60 valign=top>
			  <font face="Verdana" size="-1"><B>54</B></font>
			  </td>
			  <td width=192 valign=top>
			  <font face="Verdana" size="-1"><B>Immunity to fear effects</B></font>
			  </td>
			  <td width=72 valign=top>
			  <font face="Verdana" size="-1"><B>11 sec</B></font>
			  </td>
			  <td width=60 valign=top>
			  <font face="Verdana" size="-1"><B>60 min</B></font>
			  </td>
			  <td width=91 valign=top>
			  <font face="Verdana" size="-1"><B>54 min</B></font>
			  </td>
			 </tr>
			 <tr>
			  <td width=115 valign=top >
			  <font face="Verdana" size="-1"><B>Trueshot</B></font>
			  </td>
			  <td width=60 valign=top>
			  <font face="Verdana" size="-1"><B>55</B></font>
			  </td>
			  <td width=192 valign=top>
			  <font face="Verdana" size="-1"><B>Up to double max bow dmg, increased hit chance</B></font>
			  </td>
			  <td width=72 valign=top>
			  <font face="Verdana" size="-1"><B>2 min</B></font>
			  </td>
			  <td width=60 valign=top>
			  <font face="Verdana" size="-1"><B>72 min</B></font>
			  </td>
			  <td width=91 valign=top>
			  <font face="Verdana" size="-1"><B>67 min</B></font>
			  </td>
			 </tr>
			 <tr>
			  <td width=115 valign=top >
			  <font face="Verdana" size="-1"><B>Weapon Shield</B></font>
			  </td>
			  <td width=60 valign=top>
			  <font face="Verdana" size="-1"><B>60</B></font>
			  </td>
			  <td width=192 valign=top>
			  <font face="Verdana" size="-1"><B>Automatic Parry</B></font>
			  </td>
			  <td width=72 valign=top>
			  <font face="Verdana" size="-1"><B>15 sec</B></font>
			  </td>
			  <td width=60 valign=top>
			  <font face="Verdana" size="-1"><B>72 min</B></font>
			  </td>
			  <td width=91 valign=top>
			  <font face="Verdana" size="-1"><B>72 min</B></font>
			  </td>
			 </tr>
			</table>
			
			<p class="MsoNormal">&nbsp;
			
			<font face="Verdana"><b>Rogue</b></B></font>
			
			&nbsp;
			
			<table border=1 cellspacing=0 cellpadding=0>
			 <tr>
			  <td width=115 valign=top>
			  <font face="Verdana" size="-1"><B>Discipline</B></font>
			  </td>
			  <td width=60 valign=top>
			  <font face="Verdana" size="-1"><B>Level</B></font>
			  </td>
			  <td width=192 valign=top>
			  <font face="Verdana" size="-1"><B>Effect</B></font>
			  </td>
			  <td width=72 valign=top >
			  <font face="Verdana" size="-1"><B>Duration</B></font>
			  </td>
			  <td width=60 valign=top>
			  <font face="Verdana" size="-1"><B>Delay</B></font>
			  </td>
			  <td width=91 valign=top>
			  <font face="Verdana" size="-1"><B>L60 Delay</B></font>
			  </td>
			 </tr>
			 <tr>
			  <td width=115 valign=top >
			  <font face="Verdana" size="-1"><B>Resistant</B></font>
			  </td>
			  <td width=60 valign=top>
			  <font face="Verdana" size="-1"><B>30</B></font>
			  </td>
			  <td width=192 valign=top>
			  <font face="Verdana" size="-1"><B>+3 resist all, +10 at 50+</B></font>
			  </td>
			  <td width=72 valign=top>
			  <font face="Verdana" size="-1"><B>1 min</B></font>
			  </td>
			  <td width=60 valign=top>
			  <font face="Verdana" size="-1"><B>60 min</B></font>
			  </td>
			  <td width=91 valign=top>
			  <font face="Verdana" size="-1"><B>30 min</B></font>
			  </td>
			 </tr>
			 <tr>
			  <td width=115 valign=top >
			  <font face="Verdana" size="-1"><B>Fearless</B></font>
			  </td>
			  <td width=60 valign=top>
			  <font face="Verdana" size="-1"><B>40</B></font>
			  </td>
			  <td width=192 valign=top>
			  <font face="Verdana" size="-1"><B>Immunity to fear effects</B></font>
			  </td>
			  <td width=72 valign=top>
			  <font face="Verdana" size="-1"><B>11 sec</B></font>
			  </td>
			  <td width=60 valign=top>
			  <font face="Verdana" size="-1"><B>60 min</B></font>
			  </td>
			  <td width=91 valign=top>
			  <font face="Verdana" size="-1"><B>40 min</B></font>
			  </td>
			 </tr>
			 <tr>
			  <td width=115 valign=top >
			  <font face="Verdana" size="-1"><B>Counterattack</B></font>
			  </td>
			  <td width=60 valign=top>
			  <font face="Verdana" size="-1"><B>53</B></font>
			  </td>
			  <td width=192 valign=top>
			  <font face="Verdana" size="-1"><B>Automatic Riposte</B></font>
			  </td>
			  <td width=72 valign=top>
			  <font face="Verdana" size="-1"><B>9 sec</B></font>
			  </td>
			  <td width=60 valign=top>
			  <font face="Verdana" size="-1"><B>60 min</B></font>
			  </td>
			  <td width=91 valign=top>
			  <font face="Verdana" size="-1"><B>53 min</B></font>
			  </td>
			 </tr>
			 <tr>
			  <td width=115 valign=top >
			  <font face="Verdana" size="-1"><B>Deadeye</B></font>
			  </td>
			  <td width=60 valign=top>
			  <font face="Verdana" size="-1"><B>54</B></font>
			  </td>
			  <td width=192 valign=top>
			  <font face="Verdana" size="-1"><B>Auto hit all attacks</B></font>
			  </td>
			  <td width=72 valign=top>
			  <font face="Verdana" size="-1"><B>14 sec</B></font>
			  </td>
			  <td width=60 valign=top>
			  <font face="Verdana" size="-1"><B>30 min</B></font>
			  </td>
			  <td width=91 valign=top>
			  <font face="Verdana" size="-1"><B>24 min</B></font>
			  </td>
			 </tr>
			 <tr>
			  <td width=115 valign=top >
			  <font face="Verdana" size="-1"><B>Nimble</B></font>
			  </td>
			  <td width=60 valign=top>
			  <font face="Verdana" size="-1"><B>55</B></font>
			  </td>
			  <td width=192 valign=top>
			  <font face="Verdana" size="-1"><B>Auto dodge frontal attacks</B></font>
			  </td>
			  <td width=72 valign=top>
			  <font face="Verdana" size="-1"><B>12 sec</B></font>
			  </td>
			  <td width=60 valign=top>
			  <font face="Verdana" size="-1"><B>30 min</B></font>
			  </td>
			  <td width=91 valign=top>
			  <font face="Verdana" size="-1"><B>25 min</B></font>
			  </td>
			 </tr>
			 <tr>
			  <td width=115 valign=top >
			  <font face="Verdana" size="-1"><B>Kinesthetics</B></font>
			  </td>
			  <td width=60 valign=top>
			  <font face="Verdana" size="-1"><B>57</B></font>
			  </td>
			  <td width=192 valign=top>
			  <font face="Verdana" size="-1"><B>Auto dual wield &amp; double attack</B></font>
			  </td>
			  <td width=72 valign=top>
			  <font face="Verdana" size="-1"><B>18 sec</B></font>
			  </td>
			  <td width=60 valign=top>
			  <font face="Verdana" size="-1"><B>30 min</B></font>
			  </td>
			  <td width=91 valign=top>
			  <font face="Verdana" size="-1"><B>27 min</B></font>
			  </td>
			 </tr>
			 <tr>
			  <td width=115 valign=top >
			  <font face="Verdana" size="-1"><B>Blinding Speed</B></font>
			  </td>
			  <td width=60 valign=top>
			  <font face="Verdana" size="-1"><B>58</B></font>
			  </td>
			  <td width=192 valign=top>
			  <font face="Verdana" size="-1"><B>Haste – stacks with all</B></font>
			  </td>
			  <td width=72 valign=top>
			  <font face="Verdana" size="-1"><B>15 sec</B></font>
			  </td>
			  <td width=60 valign=top>
			  <font face="Verdana" size="-1"><B>30 min</B></font>
			  </td>
			  <td width=91 valign=top>
			  <font face="Verdana" size="-1"><B>28 min</B></font>
			  </td>
			 </tr>
			 <tr>
			  <td width=115 valign=top >
			  <font face="Verdana" size="-1"><B>Duelist</B></font>
			  </td>
			  <td width=60 valign=top>
			  <font face="Verdana" size="-1"><B>59</B></font>
			  </td>
			  <td width=192 valign=top>
			  <font face="Verdana" size="-1"><B>All hits minimum 4 times base damage</B></font>
			  </td>
			  <td width=72 valign=top>
			  <font face="Verdana" size="-1"><B>12 sec</B></font>
			  </td>
			  <td width=60 valign=top>
			  <font face="Verdana" size="-1"><B>30 min</B></font>
			  </td>
			  <td width=91 valign=top>
			  <font face="Verdana" size="-1"><B>29 min</B></font>
			  </td>
			 </tr>
			</table>
			
			<p class="MsoNormal">&nbsp;
			
			<font face="Verdana"><b>Shadowknight</b></B></font>
			
			&nbsp;
			
			<table border=1 cellspacing=0 cellpadding=0>
			 <tr>
			  <td width=115 valign=top>
			  <font face="Verdana" size="-1"><B>Discipline</B></font>
			  </td>
			  <td width=60 valign=top>
			  <font face="Verdana" size="-1"><B>Level</B></font>
			  </td>
			  <td width=192 valign=top>
			  <font face="Verdana" size="-1"><B>Effect</B></font>
			  </td>
			  <td width=72 valign=top >
			  <font face="Verdana" size="-1"><B>Duration</B></font>
			  </td>
			  <td width=60 valign=top>
			  <font face="Verdana" size="-1"><B>Delay</B></font>
			  </td>
			  <td width=91 valign=top>
			  <font face="Verdana" size="-1"><B>L60 Delay</B></font>
			  </td>
			 </tr>
			 <tr>
			  <td width=115 valign=top >
			  <font face="Verdana" size="-1"><B>Resistant</B></font>
			  </td>
			  <td width=60 valign=top>
			  <font face="Verdana" size="-1"><B>51</B></font>
			  </td>
			  <td width=192 valign=top>
			  <font face="Verdana" size="-1"><B>+10 all resists</B></font>
			  </td>
			  <td width=72 valign=top>
			  <font face="Verdana" size="-1"><B>1 min</B></font>
			  </td>
			  <td width=60 valign=top>
			  <font face="Verdana" size="-1"><B>60 min</B></font>
			  </td>
			  <td width=91 valign=top>
			  <font face="Verdana" size="-1"><B>51 min</B></font>
			  </td>
			 </tr>
			 <tr>
			  <td width=115 valign=top >
			  <font face="Verdana" size="-1"><B>Fearless</B></font>
			  </td>
			  <td width=60 valign=top>
			  <font face="Verdana" size="-1"><B>54</B></font>
			  </td>
			  <td width=192 valign=top>
			  <font face="Verdana" size="-1"><B>Immunity to fear effects</B></font>
			  </td>
			  <td width=72 valign=top>
			  <font face="Verdana" size="-1"><B>11 sec</B></font>
			  </td>
			  <td width=60 valign=top>
			  <font face="Verdana" size="-1"><B>60 min</B></font>
			  </td>
			  <td width=91 valign=top>
			  <font face="Verdana" size="-1"><B>54 min</B></font>
			  </td>
			 </tr>
			 <tr>
			  <td width=115 valign=top >
			  <font face="Verdana" size="-1"><B>Unholy Aura</B></font>
			  </td>
			  <td width=60 valign=top>
			  <font face="Verdana" size="-1"><B>55</B></font>
			  </td>
			  <td width=192 valign=top>
			  <font face="Verdana" size="-1"><B>Increase Harmtouch 50%</B></font>
			  </td>
			  <td width=72 valign=top>
			  <font face="Verdana" size="-1"><B>Instant</B></font>
			  </td>
			  <td width=60 valign=top>
			  <font face="Verdana" size="-1"><B>72 min</B></font>
			  </td>
			  <td width=91 valign=top>
			  <font face="Verdana" size="-1"><B>67 min</B></font>
			  </td>
			 </tr>
			 <tr>
			  <td width=115 valign=top >
			  <font face="Verdana" size="-1"><B>Leechcurse</B></font>
			  </td>
			  <td width=60 valign=top>
			  <font face="Verdana" size="-1"><B>60</B></font>
			  </td>
			  <td width=192 valign=top>
			  <font face="Verdana" size="-1"><B>Heal 1 point per point dealt in melee</B></font>
			  </td>
			  <td width=72 valign=top>
			  <font face="Verdana" size="-1"><B>15 sec</B></font>
			  </td>
			  <td width=60 valign=top>
			  <font face="Verdana" size="-1"><B>72 min</B></font>
			  </td>
			  <td width=91 valign=top>
			  <font face="Verdana" size="-1"><B>72 min</B></font>
			  </td>
			 </tr>
			</table>
			
			<p class="MsoNormal">&nbsp;
			
			<font face="Verdana"><b>Warrior</b></B></font>
			
			&nbsp;
			
			<table border=1 cellspacing=0 cellpadding=0>
			 <tr>
			  <td width=115 valign=top>
			  <font face="Verdana" size="-1"><B>Discipline</B></font>
			  </td>
			  <td width=60 valign=top>
			  <font face="Verdana" size="-1"><B>Level</B></font>
			  </td>
			  <td width=192 valign=top>
			  <font face="Verdana" size="-1"><B>Effect</B></font>
			  </td>
			  <td width=72 valign=top >
			  <font face="Verdana" size="-1"><B>Duration</B></font>
			  </td>
			  <td width=60 valign=top>
			  <font face="Verdana" size="-1"><B>Delay</B></font>
			  </td>
			  <td width=91 valign=top>
			  <font face="Verdana" size="-1"><B>L60 Delay</B></font>
			  </td>
			 </tr>
			 <tr>
			  <td width=115 valign=top >
			  <font face="Verdana" size="-1"><B>Resistant</B></font>
			  </td>
			  <td width=60 valign=top>
			  <font face="Verdana" size="-1"><B>30</B></font>
			  </td>
			  <td width=192 valign=top>
			  <font face="Verdana" size="-1"><B>+3 resist all, +10 at 50+</B></font>
			  </td>
			  <td width=72 valign=top>
			  <font face="Verdana" size="-1"><B>1 min</B></font>
			  </td>
			  <td width=60 valign=top>
			  <font face="Verdana" size="-1"><B>60 min</B></font>
			  </td>
			  <td width=91 valign=top>
			  <font face="Verdana" size="-1"><B>30 min</B></font>
			  </td>
			 </tr>
			 <tr>
			  <td width=115 valign=top >
			  <font face="Verdana" size="-1"><B>Fearless</B></font>
			  </td>
			  <td width=60 valign=top>
			  <font face="Verdana" size="-1"><B>40</B></font>
			  </td>
			  <td width=192 valign=top>
			  <font face="Verdana" size="-1"><B>Immunity to fear effects</B></font>
			  </td>
			  <td width=72 valign=top>
			  <font face="Verdana" size="-1"><B>11 sec</B></font>
			  </td>
			  <td width=60 valign=top>
			  <font face="Verdana" size="-1"><B>60 min</B></font>
			  </td>
			  <td width=91 valign=top>
			  <font face="Verdana" size="-1"><B>40 min</B></font>
			  </td>
			 </tr>
			 <tr>
			  <td width=115 valign=top >
			  <font face="Verdana" size="-1"><B>Evasive</B></font>
			  </td>
			  <td width=60 valign=top>
			  <font face="Verdana" size="-1"><B>52</B></font>
			  </td>
			  <td width=192 valign=top>
			  <font face="Verdana" size="-1"><B>Reduces hit and be hit %</B></font>
			  </td>
			  <td width=72 valign=top>
			  <font face="Verdana" size="-1"><B>3 min</B></font>
			  </td>
			  <td width=60 valign=top>
			  <font face="Verdana" size="-1"><B>15 min</B></font>
			  </td>
			  <td width=91 valign=top>
			  <font face="Verdana" size="-1"><B>7 min</B></font>
			  </td>
			 </tr>
			 <tr>
			  <td width=115 valign=top >
			  <font face="Verdana" size="-1"><B>Charge</B></font>
			  </td>
			  <td width=60 valign=top>
			  <font face="Verdana" size="-1"><B>53</B></font>
			  </td>
			  <td width=192 valign=top>
			  <font face="Verdana" size="-1"><B>Auto hit all attacks</B></font>
			  </td>
			  <td width=72 valign=top>
			  <font face="Verdana" size="-1"><B>14 sec</B></font>
			  </td>
			  <td width=60 valign=top>
			  <font face="Verdana" size="-1"><B>30 min</B></font>
			  </td>
			  <td width=91 valign=top>
			  <font face="Verdana" size="-1"><B>23 min</B></font>
			  </td>
			 </tr>
			 <tr>
			  <td width=115 valign=top >
			  <font face="Verdana" size="-1"><B>Mighty Strike</B></font>
			  </td>
			  <td width=60 valign=top>
			  <font face="Verdana" size="-1"><B>54</B></font>
			  </td>
			  <td width=192 valign=top>
			  <font face="Verdana" size="-1"><B>All hits are critical/cripples</B></font>
			  </td>
			  <td width=72 valign=top>
			  <font face="Verdana" size="-1"><B>10 sec</B></font>
			  </td>
			  <td width=60 valign=top>
			  <font face="Verdana" size="-1"><B>60 min</B></font>
			  </td>
			  <td width=91 valign=top>
			  <font face="Verdana" size="-1"><B>54 min</B></font>
			  </td>
			 </tr>
			 <tr>
			  <td width=115 valign=top >
			  <font face="Verdana" size="-1"><B>Defensive</B></font>
			  </td>
			  <td width=60 valign=top>
			  <font face="Verdana" size="-1"><B>55</B></font>
			  </td>
			  <td width=192 valign=top>
			  <font face="Verdana" size="-1"><B>Reduce damage dealt and received</B></font>
			  </td>
			  <td width=72 valign=top>
			  <font face="Verdana" size="-1"><B>3 min</B></font>
			  </td>
			  <td width=60 valign=top>
			  <font face="Verdana" size="-1"><B>15 min</B></font>
			  </td>
			  <td width=91 valign=top>
			  <font face="Verdana" size="-1"><B>10 min</B></font>
			  </td>
			 </tr>
			 <tr>
			  <td width=115 valign=top >
			  <font face="Verdana" size="-1"><B>Furious</B></font>
			  </td>
			  <td width=60 valign=top>
			  <font face="Verdana" size="-1"><B>56</B></font>
			  </td>
			  <td width=192 valign=top>
			  <font face="Verdana" size="-1"><B>Automatic Riposte</B></font>
			  </td>
			  <td width=72 valign=top>
			  <font face="Verdana" size="-1"><B>9 sec</B></font>
			  </td>
			  <td width=60 valign=top>
			  <font face="Verdana" size="-1"><B>60 min</B></font>
			  </td>
			  <td width=91 valign=top>
			  <font face="Verdana" size="-1"><B>56 min</B></font>
			  </td>
			 </tr>
			 <tr>
			  <td width=115 valign=top >
			  <font face="Verdana" size="-1"><B>Precision</B></font>
			  </td>
			  <td width=60 valign=top>
			  <font face="Verdana" size="-1"><B>57</B></font>
			  </td>
			  <td width=192 valign=top>
			  <font face="Verdana" size="-1"><B>Increase hit and be hit %</B></font>
			  </td>
			  <td width=72 valign=top>
			  <font face="Verdana" size="-1"><B>3 min</B></font>
			  </td>
			  <td width=60 valign=top>
			  <font face="Verdana" size="-1"><B>30 min</B></font>
			  </td>
			  <td width=91 valign=top>
			  <font face="Verdana" size="-1"><B>27 min</B></font>
			  </td>
			 </tr>
			 <tr>
			  <td width=115 valign=top >
			  <font face="Verdana" size="-1"><B>Fell Strike</B></font>
			  </td>
			  <td width=60 valign=top>
			  <font face="Verdana" size="-1"><B>58</B></font>
			  </td>
			  <td width=192 valign=top>
			  <font face="Verdana" size="-1"><B>All hits min 4 times base damage</B></font>
			  </td>
			  <td width=72 valign=top>
			  <font face="Verdana" size="-1"><B>12 sec</B></font>
			  </td>
			  <td width=60 valign=top>
			  <font face="Verdana" size="-1"><B>30 min</B></font>
			  </td>
			  <td width=91 valign=top>
			  <font face="Verdana" size="-1"><B>28 min</B></font>
			  </td>
			 </tr>
			 <tr>
			  <td width=115 valign=top >
			  <font face="Verdana" size="-1"><B>Fortitude</B></font>
			  </td>
			  <td width=60 valign=top>
			  <font face="Verdana" size="-1"><B>59</B></font>
			  </td>
			  <td width=192 valign=top>
			  <font face="Verdana" size="-1"><B>Can not be hit in melee</B></font>
			  </td>
			  <td width=72 valign=top>
			  <font face="Verdana" size="-1"><B>8 sec</B></font>
			  </td>
			  <td width=60 valign=top>
			  <font face="Verdana" size="-1"><B>60 min</B></font>
			  </td>
			  <td width=91 valign=top>
			  <font face="Verdana" size="-1"><B>59 min</B></font>
			  </td>
			 </tr>
			 <tr>
			  <td width=115 valign=top >
			  <font face="Verdana" size="-1"><B>Aggressive</B></font>
			  </td>
			  <td width=60 valign=top>
			  <font face="Verdana" size="-1"><B>60</B></font>
			  </td>
			  <td width=192 valign=top>
			  <font face="Verdana" size="-1"><B>Increase damage dealt and received</B></font>
			  </td>
			  <td width=72 valign=top>
			  <font face="Verdana" size="-1"><B>3 min</B></font>
			  </td>
			  <td width=60 valign=top>
			  <font face="Verdana" size="-1"><B>27 min</B></font>
			  </td>
			  <td width=91 valign=top>
			  <font face="Verdana" size="-1"><B>27 min</B></font>
			  </td>
			 </tr>
			</table>
			</div>
		</TD>
	</TR>
	</TABLE>	
	</TD>
	<TD width="64"></TD>
<TR>
	<TD><IMG SRC = "../graphics/botc000.jpg" WIDTH = 63 HEIGHT = 87></TD>
	<TD><IMG SRC = "../graphics/botc001.jpg" WIDTH = 473 HEIGHT = 87></TD>
	<TD><IMG SRC = "../graphics/botc002.jpg" WIDTH = 64 HEIGHT = 87></TD>
</TR>
</TABLE>
<BR>
 <SCRIPT LANGUAGE="JavaScript">
   <!-- Hide from old browsers
   now = new Date();
   random = now.getTime();
   
   // Modify to reflect site specifics
   site = "http://ds.cybereps.com";
   target = "/SITE=FGN/AREA=EQLORE/AAMSZ=BOX";
   
   document.write('<IFRAME SRC="' + site + '/hserver/acc_random=' + random + target + '"');
   document.write(' NORESIZE SCROLLING=NO HSPACE=0 VSPACE=0 FRAMEBORDER=0 MARGINHEIGHT=0 MARGINWIDTH=0 WIDTH=125 HEIGHT=125>');
      
   document.write('<SCR');
   document.write('IPT SRC="' + site + '/jnserver/acc_random=' + random + target + '">');
   document.write('</SCR');
   document.write('IPT>');
   
   document.write('</IFRAME>');
   // End Hide -->
 </SCRIPT>
 <NOSCRIPT> 
   <A HREF="http://ds.cybereps.com/accipiter/adclick/SITE=FGN/AREA=EQLORE/AAMSZ=BOX">
   <IMG SRC="http://ds.cybereps.com/accipiter/nserver/SITE=FGN/AREA=EQLORE/AAMSZ=BOX" border="0"></A>
 </NOSCRIPT>
<BR>
<BR>
</DIV>
</BODY>
</HTML>
