<HTML>
<HEAD>
<TITLE>MGON - Company Information</TITLE>
<LINK rel="stylesheet" href="/pagestyle.css">

</HEAD>
<BODY bgcolor="#FFFFFF" text="#000000" link="#000000" vlink="#000000" alink="#000000" marginwidth="0" marginheight="0" leftmargin="0" rightmargin="0" topmargin="0">
<!-- Webserver: w18 --><script language="JavaScript">
<!--
function MM_openBrWindow(theURL,winName,features) { //v2.0
  window.open(theURL,winName,features);  
}
function login() {
  window.open('/common/loginNew.phtml', 'Login', 'width=250,height=250,scrollbars=yes'); 
}
function member() {
  window.open('/common/members.phtml', 'Member', 'width=500,height=600,scrollbars=yes'); 
}
//-->
</script>
<table width="100%" border="0" cellspacing="0" cellpadding="0" background="/common/images/topplate/resize.gif">
  <tr> 
    <td> 
      <table width="488" border="0" cellspacing="0" cellpadding="0" background="/common/images/topplate/resize.gif">
        <tr> 
          <td><img src="/common/images/topplate/metalcorner.gif" width="5" height="20"></td>
          <td><a href="javascript:login();"><img src="/common/images/topplate/memberlogin.gif" width="80" height="20" border="0"></a></td>
          <td><img src="/common/images/topplate/arrow.gif" width="10" height="20"></td>
          <td><img src="/common/images/topplate/metalcolumn.gif" width="3" height="20"></td>
          <td><a href="javascript:;" onClick="MM_openBrWindow('/common/sitemap.html','navigation','width=540,height=420')"><img src="/common/images/topplate/pc.gif" width="23" height="20" border="0"></a></td>
          <td><img src="/common/images/topplate/metalcolumn.gif" width="3" height="20"></td>
          <td><a href="javascript:;" onClick="MM_openBrWindow('/common/sitemap.html','navigation','width=540,height=420')"><img src="/common/images/topplate/action.gif" width="47" height="20" border="0"></a></td>
          <td><img src="/common/images/topplate/metalcolumn.gif" width="3" height="20"></td>
          <td><a href="javascript:;" onClick="MM_openBrWindow('/common/sitemap.html','navigation','width=540,height=420')"><img src="/common/images/topplate/roleplay.gif" width="62" height="20" border="0"></a></td>
          <td><img src="/common/images/topplate/metalcolumn.gif" width="3" height="20"></td>
          <td><a href="javascript:;" onClick="MM_openBrWindow('/common/sitemap.html','navigation','width=540,height=420')"><img src="/common/images/topplate/simulation.gif" width="70" height="20" border="0"></a></td>
          <td><img src="/common/images/topplate/metalcolumn.gif" width="3" height="20"></td>
          <td><a href="javascript:;" onClick="MM_openBrWindow('/common/sitemap.html','navigation','width=540,height=420')"><img src="/common/images/topplate/console.gif" width="56" height="20" border="0"></a></td>
          <td><img src="/common/images/topplate/metalcolumn.gif" width="3" height="20"></td>
          <td><a href="javascript:;" onClick="MM_openBrWindow('/common/sitemap.html','navigation','width=540,height=420')"><img src="/common/images/topplate/strategy.gif" width="64" height="20" border="0"></a></td>
          <td><img src="/common/images/topplate/metalcolumn.gif" width="3" height="20"></td>
          <td><a href="javascript:;" onClick="MM_openBrWindow('/common/sitemap.html','navigation','width=540,height=420')"><img src="/common/images/topplate/racing.gif" width="47" height="20" border="0"></a></td>
          <td><img src="/common/images/topplate/metalcolumn.gif" width="3" height="20"></td>
        </tr>
      </table>
    </td>
    <td background="/common/images/topplate/resize.gif" width="100%"><img src="/common/images/topplate/resize.gif" width="100%" height="20"></td>
    <td>
      <table width="88" border="0" cellspacing="0" cellpadding="0" background="/common/images/topplate/resize.gif">
        <tr>
          <td><img src="/common/images/topplate/metalcolumn.gif" width="3" height="20"></td>
          <td><a href="javascript:;" onClick="MM_openBrWindow('/common/sitemap.html','navigation','width=540,height=420')"><img src="/common/images/topplate/mgonetwork.gif" width="82" height="20" border="0"></a></td>
          <td><img src="/common/images/topplate/metalcorner.gif" width="5" height="20"></td>
        </tr>
      </table>
    </td>
  </tr>
</table>
<table width="100%" border="0" cellspacing="0" cellpadding="0" bgcolor="#000000">
  <tr> 
    <td><img src="/images/misc/1pix.gif" width="1" height="1"></td>
  </tr>
</table><script language="javascript">
var compname='Ad/mgon';
</script>
<script language="javascript" src="http://www.rankyou.com/cpt_transfers/single_month_enter.js">
</script> 
<TABLE width="100%" border="0" cellspacing="0" cellpadding="0">
  <TR> 
    <TD background="/images/top/resize.gif"><IMG src="/images/top/logo.gif" width="145" height="99" border="0" usemap="#Map"><map name="Map"><area shape="rect" coords="10,30,135,70" href="http://www.mgon.com" alt="MGON Home" title="MGON Home"></map></TD>
    <TD width="100%" background="/images/top/resize.gif"><IMG src="/images/top/networklogo.gif" width="459" height="99"></TD>
    <TD> 
      <table width="100%" border="0" cellspacing="0" cellpadding="0">
        <tr background="/images/top/mgochannel2.gif"> 
          <td colspan="3"><img src="/images/top/mgochannel_top2.gif" width="133" height="13"></td>
        </tr>
        <tr> 
          <td><img src="/images/top/mgochannelleft2.gif" width="7" height="60"></td>
          <td bgcolor="#FFFFFF" width="120" height="60"><object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=4,0,2,0" width="120" height="60">
              <param name=movie value="http://www.mgon.com/flashmovies/mgochannel2.swf">
              <param name=quality value=high>
              <param name="menu" value="false">
              
              <embed src="http://www.mgon.com/flashmovies/mgochannel2.swf" quality=high pluginspage="http://www.macromedia.com/shockwave/download/index.cgi?P1_Prod_Version=ShockwaveFlash" 
type="application/x-shockwave-flash" menu="false" width="120" height="60"></embed></object></td>
          <td><img src="/images/top/mgochannelright2.gif" width="6" height="60"></td>
        </tr>
        <tr background="/images/top/mgochannel2.gif"> 
          <td colspan="3"><img src="/images/top/mgochannel2.gif" width="133" height="26"></td>
        </tr>
      </table>
    </TD>
  </TR>
</TABLE>
 
<TABLE width="100%" border="0" cellspacing="0" cellpadding="0" background="/images/topnavigation/resize.gif">
  <TR> 
    <TD>&nbsp;</TD>
  </TR>
</TABLE>
<TABLE width="100%" border="0" cellspacing="0" cellpadding="0">
  <TR> 
    <TD valign="top" bgcolor="#263041">
  
 
<form name="form1" >
  <IMG src="/images/buttons/sitecontent.gif" width="144" height="21"><BR>
  <TABLE width="144" border="0" cellspacing="0" cellpadding="0">
    <TR bgcolor="#000000"> 
      <TD><IMG src="/images/misc/1pix.gif" width="1" height="1"></TD>
    </TR>
  </TABLE>
  <TABLE width="144" border="0" cellspacing="0" cellpadding="0">
    <TR bgcolor="#000E24"> 
      <TD> 
        <TABLE width=144 border=0 cellpadding=0 cellspacing=1>
          <TR bgcolor="#000E24"> 
            <TD style="border='1 solid #809ECB'" onMouseOver="style.backgroundColor='#809ECB'; style.cursor='hand'; style.border='1 solid #809ECB'" onMouseOut="style.backgroundColor='#000E24'; style.border='1 solid #809ECB';" height="21"> 
              <TABLE width="100%" border="0" cellspacing="0" cellpadding="2">
                <TR> 
                  <TD bgcolor="#34435B">&nbsp;</TD>
                  <TD bgcolor="#000E24" height="21" width="100%"><A href="/" class="navlinks" style="margin:0;"> 
                    <DIV><IMG src="/images/misc/1pix.gif" width="1" height="1" border="0">&nbsp;<SPAN class="navlinks">Home</SPAN></DIV>
                    </A></TD>
                  <TD class="Bolded"><FONT size="2" face="Verdana, Arial, Helvetica, sans-serif" color="#000E24">&laquo;</FONT></TD>
                </TR>
              </TABLE>
            </TD>
          </TR>
          <TR bgcolor="#000E24"> 
            <TD style="border='1 solid #809ECB'" onMouseOver="style.backgroundColor='#809ECB'; style.cursor='hand'; style.border='1 solid #809ECB'" onMouseOut="style.backgroundColor='#000E24'; style.border='1 solid #809ECB';" height="21"> 
              <TABLE width="100%" border="0" cellspacing="0" cellpadding="2">
                <TR> 
                  <TD bgcolor="#34435B">&nbsp;</TD>
                  <TD bgcolor="#000E24" height="21" width="100%"><A href="/news.phtml" class="navlinks" style="margin:0;"> 
                    <DIV><IMG src="/images/misc/1pix.gif" width="1" height="1" border="0">&nbsp;<SPAN class="navlinks">News</SPAN></DIV>
                    </A></TD>
                  <TD class="Bolded"><FONT size="2" face="Verdana, Arial, Helvetica, sans-serif" color="#000E24">&laquo;</FONT></TD>
                </TR>
              </TABLE>
            </TD>
          </TR>
          <TR bgcolor="#000E24"> 
            <TD style="border='1 solid #809ECB'" onMouseOver="style.backgroundColor='#809ECB'; style.cursor='hand'; style.border='1 solid #809ECB'" onMouseOut="style.backgroundColor='#000E24'; style.border='1 solid #809ECB';" height="21"> 
              <TABLE width="100%" border="0" cellspacing="0" cellpadding="2">
                <TR> 
                  <TD bgcolor="#34435B">&nbsp;</TD>
                  <TD bgcolor="#000E24" height="21" width="100%"><A href="/mgonews.phtml" class="navlinks" style="margin:0;"> 
                    <DIV><IMG src="/images/misc/1pix.gif" width="1" height="1" border="0">&nbsp;<SPAN class="navlinks">MGONews</SPAN></DIV>
                    </A></TD>
                  <TD class="Bolded"><FONT size="2" face="Verdana, Arial, Helvetica, sans-serif" color="#000E24">&laquo;</FONT></TD>
                </TR>
              </TABLE>
            </TD>
          </TR>
          <TR bgcolor="#000E24"> 
            <TD style="border='1 solid #809ECB'" onMouseOver="style.backgroundColor='#809ECB'; style.cursor='hand'; style.border='1 solid #809ECB'" onMouseOut="style.backgroundColor='#000E24'; style.border='1 solid #809ECB';" height="21"> 
              <TABLE width="100%" border="0" cellspacing="0" cellpadding="2">
                <TR> 
                  <TD bgcolor="#34435B">&nbsp;</TD>
                  <TD bgcolor="#000E24" height="21" width="100%"><A href="/reviews.phtml" class="navlinks" style="margin:0;"> 
                    <DIV><IMG src="/images/misc/1pix.gif" width="1" height="1" border="0">&nbsp;<SPAN class="navlinks">Reviews</SPAN></DIV>
                    </A></TD>
                  <TD class="Bolded"><FONT size="2" face="Verdana, Arial, Helvetica, sans-serif" color="#000E24">&laquo;</FONT></TD>
                </TR>
              </TABLE>
            </TD>
          </TR>
          <TR bgcolor="#000E24"> 
            <TD style="border='1 solid #809ECB'" onMouseOver="style.backgroundColor='#809ECB'; style.cursor='hand'; style.border='1 solid #809ECB'" onMouseOut="style.backgroundColor='#000E24'; style.border='1 solid #809ECB';" height="21"> 
              <TABLE width="100%" border="0" cellspacing="0" cellpadding="2">
                <TR> 
                  <TD bgcolor="#34435B">&nbsp;</TD>
                  <TD bgcolor="#000E24" height="21" width="100%"><A href="/previews.phtml" class="navlinks" style="margin:0;"> 
                    <DIV><IMG src="/images/misc/1pix.gif" width="1" height="1" border="0">&nbsp;<SPAN class="navlinks">Previews</SPAN></DIV>
                    </A></TD>
                  <TD class="Bolded"><FONT size="2" face="Verdana, Arial, Helvetica, sans-serif" color="#000E24">&laquo;</FONT></TD>
                </TR>
              </TABLE>
            </TD>
          </TR>
          <TR bgcolor="#000E24"> 
            <TD style="border='1 solid #809ECB'" onMouseOver="style.backgroundColor='#809ECB'; style.cursor='hand'; style.border='1 solid #809ECB'" onMouseOut="style.backgroundColor='#000E24'; style.border='1 solid #809ECB';" height="21"> 
              <TABLE width="100%" border="0" cellspacing="0" cellpadding="2">
                <TR> 
                  <TD bgcolor="#34435B">&nbsp;</TD>
                  <TD bgcolor="#000E24" height="21" width="100%"><A href="/interviews.phtml" class="navlinks" style="margin:0;"> 
                    <DIV><IMG src="/images/misc/1pix.gif" width="1" height="1" border="0">&nbsp;<SPAN class="navlinks">Interviews</SPAN></DIV>
                    </A></TD>
                  <TD class="Bolded"><FONT size="2" face="Verdana, Arial, Helvetica, sans-serif" color="#000E24">&laquo;</FONT></TD>
                </TR>
              </TABLE>
            </TD>
          </TR>
          <TR bgcolor="#000E24"> 
            <TD style="border='1 solid #809ECB'" onMouseOver="style.backgroundColor='#809ECB'; style.cursor='hand'; style.border='1 solid #809ECB'" onMouseOut="style.backgroundColor='#000E24'; style.border='1 solid #809ECB';" height="21"> 
              <TABLE width="100%" border="0" cellspacing="0" cellpadding="2">
                <TR> 
                  <TD bgcolor="#34435B">&nbsp;</TD>
                  <TD bgcolor="#000E24" height="21" width="100%"><A href="/articles.phtml" class="navlinks" style="margin:0;"> 
                    <DIV><IMG src="/images/misc/1pix.gif" width="1" height="1" border="0">&nbsp;<SPAN class="navlinks">Articles</SPAN></DIV>
                    </A></TD>
                  <TD class="Bolded"><FONT size="2" face="Verdana, Arial, Helvetica, sans-serif" color="#000E24">&laquo;</FONT></TD>
                </TR>
              </TABLE>
            </TD>
          </TR>
          <TR bgcolor="#000E24"> 
            <TD style="border='1 solid #809ECB'" onMouseOver="style.backgroundColor='#809ECB'; style.cursor='hand'; style.border='1 solid #809ECB'" onMouseOut="style.backgroundColor='#000E24'; style.border='1 solid #809ECB';" height="21"> 
              <TABLE width="100%" border="0" cellspacing="0" cellpadding="2">
                <TR> 
                  <TD bgcolor="#34435B">&nbsp;</TD>
                  <TD bgcolor="#000E24" height="21" width="100%"><A href="http://www.mgoforum.com/forumdisplay.phtml?forumid=44" class="navlinks" style="margin:0;"> 
                    <DIV><IMG src="/images/misc/1pix.gif" width="1" height="1" border="0">&nbsp;<SPAN class="navlinks">MGON Forum</SPAN></DIV>
                    </A></TD>
                  <TD class="Bolded"><FONT size="2" face="Verdana, Arial, Helvetica, sans-serif" color="#000E24">&laquo;</FONT></TD>
                </TR>
              </TABLE>
            </TD>
          </TR>
        </TABLE>
      </TD>
    </TR>
  </TABLE>
  <IMG src="/images/buttons/siteinfo.gif" width="144" height="21"><BR>
  <TABLE width="144" border="0" cellspacing="0" cellpadding="0">
    <TR bgcolor="#000000"> 
      <TD><IMG src="/images/misc/1pix.gif" width="1" height="1"></TD>
    </TR>
  </TABLE>
  <TABLE width="144" border="0" cellspacing="0" cellpadding="0">
    <TR bgcolor="#000E24"> 
      <TD> 
        <TABLE width=144 border=0 cellpadding=0 cellspacing=1>
          <TR bgcolor="#000E24"> 
            <TD style="border='1 solid #809ECB'" onMouseOver="style.backgroundColor='#809ECB'; style.cursor='hand'; style.border='1 solid #809ECB'" onMouseOut="style.backgroundColor='#000E24'; style.border='1 solid #809ECB';" height="21"> 
              <TABLE width="100%" border="0" cellspacing="0" cellpadding="2">
                <TR> 
                  <TD bgcolor="#34435B">&nbsp;</TD>
                  <TD bgcolor="#000E24" height="21" width="100%"><A href="/company/" class="navlinks" style="margin:0;"> 
                    <DIV><IMG src="/images/misc/1pix.gif" width="1" height="1" border="0">&nbsp;<SPAN class="navlinks">The Company</SPAN></DIV>
                    </A></TD>
                  <TD class="Bolded"><FONT size="2" face="Verdana, Arial, Helvetica, sans-serif" color="#000E24">&laquo;</FONT></TD>
                </TR>
              </TABLE>
            </TD>
          </TR>
          <TR bgcolor="#000E24"> 
            <TD style="border='1 solid #809ECB'" onMouseOver="style.backgroundColor='#809ECB'; style.cursor='hand'; style.border='1 solid #809ECB'" onMouseOut="style.backgroundColor='#000E24'; style.border='1 solid #809ECB';" height="21"> 
              <TABLE width="100%" border="0" cellspacing="0" cellpadding="2">
                <TR> 
                  <TD bgcolor="#34435B">&nbsp;</TD>
                  <TD bgcolor="#000E24" height="21" width="100%"><A href="/jobs.phtml" class="navlinks" style="margin:0;"> 
                    <DIV><IMG src="/images/misc/1pix.gif" width="1" height="1" border="0">&nbsp;<SPAN class="navlinks">MGON Jobs</SPAN></DIV>
                    </A></TD>
                  <TD class="Bolded"><FONT size="2" face="Verdana, Arial, Helvetica, sans-serif" color="#000E24">&laquo;</FONT></TD>
                </TR>
              </TABLE>
            </TD>
          </TR>
          <TR bgcolor="#000E24"> 
            <TD style="border='1 solid #809ECB'" onMouseOver="style.backgroundColor='#809ECB'; style.cursor='hand'; style.border='1 solid #809ECB'" onMouseOut="style.backgroundColor='#000E24'; style.border='1 solid #809ECB';" height="21"> 
              <TABLE width="100%" border="0" cellspacing="0" cellpadding="2">
                <TR> 
                  <TD bgcolor="#34435B">&nbsp;</TD>
                  <TD bgcolor="#000E24" height="21" width="100%"><A href="/partnerships/" class="navlinks" style="margin:0;"> 
                    <DIV><IMG src="/images/misc/1pix.gif" width="1" height="1" border="0">&nbsp;<SPAN class="navlinks">Our Partners</SPAN></DIV>
                    </A></TD>
                  <TD class="Bolded"><FONT size="2" face="Verdana, Arial, Helvetica, sans-serif" color="#000E24">&laquo;</FONT></TD>
                </TR>
              </TABLE>
            </TD>
          </TR>
          <TR bgcolor="#000E24"> 
            <TD style="border='1 solid #809ECB'" onMouseOver="style.backgroundColor='#809ECB'; style.cursor='hand'; style.border='1 solid #809ECB'" onMouseOut="style.backgroundColor='#000E24'; style.border='1 solid #809ECB';" height="21"> 
              <TABLE width="100%" border="0" cellspacing="0" cellpadding="2">
                <TR> 
                  <TD bgcolor="#34435B">&nbsp;</TD>
                  <TD bgcolor="#000E24" height="21" width="100%"><A href="/mediakit/" class="navlinks" style="margin:0;"> 
                    <DIV><IMG src="/images/misc/1pix.gif" width="1" height="1" border="0">&nbsp;<SPAN class="navlinks">Our Mediakit</SPAN></DIV>
                    </A></TD>
                  <TD class="Bolded"><FONT size="2" face="Verdana, Arial, Helvetica, sans-serif" color="#000E24">&laquo;</FONT></TD>
                </TR>
              </TABLE>
            </TD>
          </TR>
          <TR bgcolor="#000E24"> 
            <TD style="border='1 solid #809ECB'" onMouseOver="style.backgroundColor='#809ECB'; style.cursor='hand'; style.border='1 solid #809ECB'" onMouseOut="style.backgroundColor='#000E24'; style.border='1 solid #809ECB';" height="21"> 
              <TABLE width="100%" border="0" cellspacing="0" cellpadding="2">
                <TR> 
                  <TD bgcolor="#34435B">&nbsp;</TD>
                  <TD bgcolor="#000E24" height="21" width="100%"><A href="/press.phtml" class="navlinks" style="margin:0;"> 
                    <DIV><IMG src="/images/misc/1pix.gif" width="1" height="1" border="0">&nbsp;<SPAN class="navlinks">Press Material</SPAN></DIV>
                    </A></TD>
                  <TD class="Bolded"><FONT size="2" face="Verdana, Arial, Helvetica, sans-serif" color="#000E24">&laquo;</FONT></TD>
                </TR>
              </TABLE>
            </TD>
          </TR>
          <TR bgcolor="#000E24"> 
            <TD style="border='1 solid #809ECB'" onMouseOver="style.backgroundColor='#809ECB'; style.cursor='hand'; style.border='1 solid #809ECB'" onMouseOut="style.backgroundColor='#000E24'; style.border='1 solid #809ECB';" height="21"> 
              <TABLE width="100%" border="0" cellspacing="0" cellpadding="2">
                <TR> 
                  <TD bgcolor="#34435B">&nbsp;</TD>
                  <TD bgcolor="#000E24" height="21" width="100%"><A href="/contactus/" class="navlinks" style="margin:0;"> 
                    <DIV><IMG src="/images/misc/1pix.gif" width="1" height="1" border="0">&nbsp;<SPAN class="navlinks">Contact Us</SPAN></DIV>
                    </A></TD>
                  <TD class="Bolded"><FONT size="2" face="Verdana, Arial, Helvetica, sans-serif" color="#000E24">&laquo;</FONT></TD>
                </TR>
              </TABLE>
            </TD>
          </TR>
        </TABLE>
      </TD>
    </TR>
  </TABLE>
</form>

      
      <TABLE width="144" border="0" cellspacing="0" cellpadding="0">
        <TR>
          <TD>&nbsp;</TD>
        </TR>
      </TABLE>
    </TD>
    <TD valign="top" width="100%" background="/images/news/leftresize.gif">
<table width="100%" border="0" cellspacing="0" cellpadding="0" background="/images/bannerarea/squares.gif" bgcolor="#000000">
  <tr> 
    <td align="center" width="100%" height="83"> 
<!--- Start New Adcode -->
<span class="smalltext"><NOLAYER><IFRAME SRC="http://ad.se.doubleclick.net/adi/mgon.com/;sz=468x60;ord=984075437?" bgcolor="#000000" width="468" height="60" frameborder="no" border="0" MARGINWIDTH="0" MARGINHEIGHT="0" SCROLLING="no"><A HREF="http://ad.se.doubleclick.net/jump/mgon.com/;abr=!ie;sz=468x60;ord=984075437?"><IMG SRC="http://ad.se.doubleclick.net/ad/mgon.com/;abr=!ie;sz=468x60;ord=984075437?" border="0" height="60" width="468"></A></IFRAME></NOLAYER><ILAYER id="layer1" visibility="hidden" width="468" height="60" align="center"></ILAYER></span><!--- End New Adcode -->
    </td>
  </tr>
</table>

<TABLE width="100%" border="0" cellspacing="0" cellpadding="0">
  <TR> 
    <TD background="/images/articles/resize.gif" align="right"><IMG src="/images/articles/leftshadow.gif" width="13" height="85"></TD>
    <TD background="/images/articles/resize.gif" width="100%" align="right"><IMG src="/images/sections/privacy.gif" width="275" height="85"></TD>
  </TR>
</TABLE>
<TABLE width="100%" border="0" cellspacing="0" cellpadding="12">
  <TR> 
    <TD class="Boldyellow" background="/images/misc/50x50black.gif">Below 
      you will find  information about MGON's privacy policy.</TD>
  </TR>
</TABLE>
<TABLE width="100%" border="0" cellspacing="0" cellpadding="4">
  <TR> 
    <TD valign="top" width="50%" class="sections" background="/images/news/coloredleft.gif" height="30"> 
      <IMG src="/images/misc/1pix.gif" width="8" height="1">MGON International 
      AB's Privacy Statement </TD>
  </TR>
</TABLE>
<TABLE width="100%" border="0" cellspacing="0" cellpadding="12">
  <TR> 
    <TD valign="top" width="50%"> 
      <P>MGON International AB is committed to the responsible management of consumer 
        information. Internet user privacy is a high priority to MGON International 
        AB, our advertisers and our Web publishers. </P>
      <P>MGON International AB continually reviews its data practices and privacy 
        policy in light of consumer demands, public interests and governmental 
        concerns. </P>
      <P>MGON International AB operates a network several Web site properties 
        including this one, and causes advertisements to be delivered to such 
        Web sites on behalf of advertisers. For more information about the business 
        of MGON International AB, please return to our <a href="/index.phtml">Home 
        Page</a>. </P>
      </TD>
  </TR>
</TABLE>
<TABLE width="100%" border="0" cellspacing="0" cellpadding="0">
  <TR> 
    <TD background="/images/misc/50x50black.gif"><IMG src="/images/misc/1pix.gif" width="1" height="1"></TD>
  </TR>
</TABLE>
<TABLE width="100%" border="0" cellspacing="0" cellpadding="4">
  <TR> 
    <TD valign="top" width="50%" class="sections" background="/images/news/coloredleft.gif" height="30"> 
      <IMG src="/images/misc/1pix.gif" width="8" height="1">Personal </TD>
  </TR>
</TABLE>
<TABLE width="100%" border="0" cellspacing="0" cellpadding="12">
  <TR> 
    <TD valign="top" width="50%"> 
      <P>Throughout the entire network of Official MGON sites, MGON will not collect 
        any personally-identifiable information about you (name, address, telephone 
        number, email address) unless you provide it to us voluntarily. If you 
        do not want your personal information collected, please do not submit 
        it. (An Official MGON site is one that is designed and controlled by us. 
        It will also be listed in the MGO Channel list.)</P>
      <P> If you do submit your email or postal addresses online, you may receive 
        periodic mailings from us with information on new services or products. 
        If you do not wish to receive such mailings, please let us know by contacting 
        us at the email or phone listed at the bottom of this Statement.</P>
      <P> If you submit your telephone number online, you may receive telephone 
        contact from us regarding information you have requested online. You may 
        also receive telephone contact regarding new services or products. If 
        you do not wish to receive telephone calls, please let us know by contacting 
        us at the email or phone listed at the bottom of this Statement.</P>
      <P> If you have already submitted this information and would like for us 
        to remove it from our files, please contact us at the email or phone listed 
        at the bottom of this Statement. We will use reasonable efforts to delete 
        your information from our existing files. </P>
      <p><i>Non-personally Identifiable Information Collected Automatically </i></p>
      <p>For each visitor to an MGON International website, our Web server automatically 
        recognizes your domain, the type of Internet browser you are using, the 
        type of computer operating system you are using, and the domain name of 
        the Web site from which you linked to our site. This non-personally identifiable 
        information is collected automatically, used for internal review, then 
        discarded. </p>
      </TD>
  </TR>
</TABLE>
<TABLE width="100%" border="0" cellspacing="0" cellpadding="0">
  <TR> 
    <TD background="/images/misc/50x50black.gif"><IMG src="/images/misc/1pix.gif" width="1" height="1"></TD>
  </TR>
</TABLE>
<table width="100%" border="0" cellspacing="0" cellpadding="4">
  <tr> 
    <td valign="top" width="50%" class="sections" background="/images/news/coloredleft.gif" height="30"> 
      <img src="/images/misc/1pix.gif" width="8" height="1">Who to Contact </td>
  </tr>
</table>
<TABLE width="100%" border="0" cellspacing="0" cellpadding="12">
  <TR> 
    <TD valign="top" width="50%"> 
      <P>Please e-mail questions or requests for more information about MGON International 
        AB's privacy policies and initiatives to <a href="mailto:privacy@mgon.com">privacy@mgon.com</a>. 
      </P>
      <p>Any consumer may request removal of his or her name from MGON International 
        AB's any consumer database MGON may maintain by sending e-mail to <a href="mailto:optout@mgon.com">optout@mgon.com</a>. 
        You must provide your name, complete street address, city, state, ZIP 
        code and e-mail address. We will use reasonable efforts to delete this 
        information from our existing files. </p>
      <p>Or alternatively, our office can be contacted on +46 (0)270 - 73532 </p>
        </TD>
  </TR>
</TABLE>
<table width="100%" border="0" cellspacing="0" cellpadding="0">
  <tr> 
    <td background="/images/misc/50x50black.gif"><img src="/images/misc/1pix.gif" width="1" height="1"></td>
  </tr>
</table>
<table width="100%" border="0" cellspacing="0" cellpadding="4">
  <tr> 
    <td valign="top" width="50%" class="sections" background="/images/news/coloredleft.gif" height="30"> 
      <img src="/images/misc/1pix.gif" width="8" height="1">Consumers' Privacy 
      Rights</td>
  </tr>
</table>
<table width="100%" border="0" cellspacing="0" cellpadding="12">
  <tr> 
    <td valign="top" width="50%"> 
      <p>MGON International AB holds the consumer relationship in the highest 
        regard and pledges: </p>
      <ul>
        <p>To insure that consumers have the ultimate right to control dissemination 
          of their personal information. We support the self-regulation efforts 
          of the direct marketing industry and believe this action is the best 
          way to protect consumer privacy. We support legislation and regulatory 
          efforts, which introduce fair, workable guidelines that protect the 
          privacy of consumers. We will work to ensure that any such guidelines 
          are consistent with and complement established self-regulatory measures, 
          and that they allow the consumer to continue receiving the benefits 
          that sophisticated marketing techniques can provide.</p>
        <p>To respond quickly to questions about the accuracy of information we 
          process for our customers. We appreciate the fact that inaccurate data 
          can have a negative impact upon consumers. If a data error is called 
          to our attention, we will use our best efforts to determine the source 
          of the error and to notify the responsible party and update our records. 
          If the error is in data, which originates with us, we will promptly 
          correct it. </p>
        <p>To monitor privacy issues and assure that any changes in legislation 
          or industry standards regarding privacy issues are reflected in our 
          Privacy Policy. MGON International AB has appointed an executive level 
          Privacy Committee, which uses a variety of resources to stay informed 
          about changes in legislation and regulation. We are in constant contact 
          with our network affiliates to identify and resolve misunderstandings 
          about the law, industry standards or our Privacy Policy. </p>
        <p>To maintain strict data security systems that ensure specific individual 
          information will not be made available to any unauthorized person. We 
          use a multi-level security system to control access to information stored 
          for our customers. We also provide stringent physical security and only 
          provided access to authorized personal. Now go play some games!!!</p>
      </ul>
      <p><span class="Bolded">Enjoy your stay in the MGONetwork!</span></p>
      </td>
  </tr>
</table>
<TABLE width="100%" border="0" cellspacing="0" cellpadding="0">
  <TR> 
    <TD background="/images/misc/50x50black.gif"><IMG src="/images/misc/1pix.gif" width="1" height="1"></TD>
  </TR>
</TABLE>
<TABLE width="100%" border="0" cellspacing="0" cellpadding="4">
  <TR> 
    <TD valign="top" width="50%" class="sections" background="/images/news/coloredleft.gif" height="30"> 
      <IMG src="/images/misc/1pix.gif" width="8" height="1">Engage Privacy Statement 
    </TD>
  </TR>
</TABLE>
<TABLE width="100%" border="0" cellspacing="0" cellpadding="12">
  <TR> 
    <TD valign="top" width="50%"> 
      <P>This site, Media and Games Online Network, uses the services of Engage 
        for the serving and/or targeting of ads, promotions and other marketing 
        messages. To do this, Engage collects anonymous data through the use of 
        cookies. To learn more about Engage, including your ability to opt out 
        of the Engage system, go to <a href="http://www.engage.com/privacy">http://www.engage.com/privacy</a>. 
      </P>
      </TD>
  </TR>
</TABLE>
</TD>
  </TR>
</TABLE>
 
<TABLE width="750" border="0" cellspacing="0" cellpadding="0">
  <TR> 
    <TD><IMG src="/images2/bottom/copyright.gif" width="340" height="30" border="0"><A href="/privacy.phtml"><IMG src="/images2/bottom/privacy.gif" width="101" height="30" border="0"></A></TD>
    <TD><IMG src="/images2/bottom/bottomplate.gif" width="177" height="30"></TD>
    <TD><A href="#top"><IMG src="/images2/bottom/top.gif" width="68" height="30" border="0"></A></TD>
    <TD><A href="/index.phtml"><IMG src="/images2/bottom/home.gif" width="64" height="30" border="0"></A></TD>
  </TR>
</TABLE>
<TABLE width="750" border="0" cellspacing="0" cellpadding="0" height="90" background="/images2/misc/50x50pix.gif">
  <TR bgcolor="#000000" align="center"> 
    <TD class="smalltext"><SCRIPT language="JavaScript"
src="http://adtegrity.spinbox.net/?DC=Mgon+Bottom&JS=Y&TARGET=_new">
</SCRIPT><NOSCRIPT><A href="http://adtegrity.spinbox.net/?SHT=Mgon+Bottom" target="_new"
height="468" width="60"><IMG src="http://adtegrity.spinbox.net/?SIT=Mgon+Bottom" border="0"></A></NOSCRIPT></TD>
  </TR>
</TABLE>
<!--Bottom Layer-->
<LAYER SRC="http://ad.se.doubleclick.net/adl/mgon.com/;sz=468x60;ord=984075437?" bgcolor="#000000" width="468" height="60" visibility="hidden" onLoad="moveToAbsolute(layer1.pageX,layer1.pageY);clip.height=60;clip.width=468; visibility='show';"></LAYER><!--End Bottom Layer--></body>

</HTML>

