<HTML>
<HEAD>
<TITLE>Welcome to Media and Games Online Network - MGON</TITLE>
<META name="description" content="MGON - The Gamer's Choice for gaming news. Get the hottest info from the gaming industry.
.">
<META name="keywords" content="MGON, MGO, Interviews, Game previews, Game downloads, Gaming Network, , Gaming News, News, Multiplayer, Games, PC Games, Console Games, Reviews, Forum, MGON International AB, Action, Strategy, Simulation, Roleplay, Racing">
<META name="robots" content="index,follow">
<link rel="stylesheet" href="/newstyle.css" type="text/css">
<!--
-->

<script language="JavaScript" type="text/javascript">
<!--
function go(where) {
  if(where != "void" && where!="") location.href = where;
}

function reply(tid,pid,cid,lang) {

  url = "/reply.phtml?tid=" + tid + "&pid=" + pid + "&id=" + cid + "&language=" + lang + '&ref=%2Fcompany%2Findex.phtml';
  ipwindow = open("","prewindow","scrollbars=yes,toolbar=no,height=400,width=400");
  ipwindow.location.href = url;
        
}

function rateit(id,vote) {
    if(vote != "") {
		document.rate.content_id.value = id;
		document.rate.vote.value = vote;
		document.rate.submit();
	}
}

function screenshot(cid,pid) {

  url = "/screenshot.phtml?cid=" + cid + "&pid=" + pid;
  ipwindow = open("","prewindow","scrollbars=yes,toolbar=no,height=630,width=710");
  ipwindow.location.href = url;
        
}

function relatedmedia(url) {

  ipwindow = open("","prewindow","scrollbars=yes,toolbar=no,height=300,width=300");
  ipwindow.location.href = url;
        
}
function MM_preloadImages() { //v3.0
  var d=document; if(d.images){ if(!d.MM_p) d.MM_p=new Array();
    var i,j=d.MM_p.length,a=MM_preloadImages.arguments; for(i=0; i<a.length; i++)
    if (a[i].indexOf("#")!=0){ d.MM_p[j]=new Image; d.MM_p[j++].src=a[i];}}
}
function MM_findObj(n, d) { //v4.0
  var p,i,x;  if(!d) d=document; if((p=n.indexOf("?"))>0&&parent.frames.length) {
    d=parent.frames[n.substring(p+1)].document; n=n.substring(0,p);}
  if(!(x=d[n])&&d.all) x=d.all[n]; for (i=0;!x&&i<d.forms.length;i++) x=d.forms[i][n];
  for(i=0;!x&&d.layers&&i<d.layers.length;i++) x=MM_findObj(n,d.layers[i].document);
  if(!x && document.getElementById) x=document.getElementById(n); return x;
}
function MM_swapImgRestore() { //v3.0
  var i,x,a=document.MM_sr; for(i=0;a&&i<a.length&&(x=a[i])&&x.oSrc;i++) x.src=x.oSrc;
}
function MM_swapImage() { //v3.0
  var i,j=0,x,a=MM_swapImage.arguments; document.MM_sr=new Array; for(i=0;i<(a.length-2);i+=3)
   if ((x=MM_findObj(a[i]))!=null){document.MM_sr[j++]=x; if(!x.oSrc) x.oSrc=x.src; x.src=a[i+2];}
}

function getWall(id,name) {
  url = "/getwall.phtml?thisid=" + id + "&thisname=" + name;
  ipwindow = open("","prewindow","fullscreen=no,resizable=yes,scrollbars=yes,toolbar=yes,height=600,width=800");
  ipwindow.location.href = url;
}

function getFile(id,name) {
  url = "/common/getfile.phtml?thisid=" + id + "&thisname=" + name;
  ipwindow = open("","prewindow","scrollbars=no,toolbar=no,height=200,width=495");
  ipwindow.location.href = url;
}
function localDate(dateStr) {
  now = new Date();
  var ar1 = now.toString().split(" ");
  var addH = -100;
  var addM = -100;
  var gmt = new Array(new Array());
  gmt["PST"] = -8;
  gmt["MST"] = -7;
  gmt["CST"] = -6;
  gmt["EST"] = -5;
  gmt["UTC"] = 0;
  if(ar1[4].indexOf("+") != -1) {
    var gm = ar1[4].split("+");
    gm[2] = 0-gm[1].substr(0,2);
    addH = Number(gm[2]);
    gm[2] = 0-gm[1].substr(2,2);
    addM = Number(gm[2]);
  }
  if(ar1[4].indexOf("-") != -1) {
    var gm = ar1[4].split("-");
    gm[2] = gm[1].substr(0,2);
    addH = Number(gm[2]);
    gm[2] = gm[1].substr(2,2);
    addM = Number(gm[2]);
  }
  if(addH == -100) {
    addH = gmt[ar1[4]];
    addM = 0;
  }
  there = new Date(dateStr);
  nowP = Date.parse(there);
  if(addH > 0) nowP -= 3600000;
  nowP += Number(addH)*3600000;
  nowP += Number(addM)*60000;
  realD = new Date(nowP);
  real = realD.toLocaleString();
  //  document.write(real[0] + " " + real[1] + " " + real[2] + " " +real[3]);
  document.write(real);
}
//-->
</script>
</HEAD>

<body bgcolor="#000000" text="#EEEEEE" link="#FFFFFF" vlink="#FFFFFF" alink="#FFFFFF" background="/newimages/backgrounds/bluelines.gif" leftmargin="0" topmargin="0" marginwidth="0" marginheight="0" onLoad="MM_preloadImages('/newimages/misc/arrow_on.gif')">
<table width="772" border="0" align="center" cellpadding="1" cellspacing="0" bgcolor="#000000">
  <tr>
    <td align="center"><!-- Webserver: w20 --><!-- loginUrl: http://everquest.mgon.com/common/loginNew.phtml?ref=www.mgon.com&page=/company/index.phtml !--><!-- loginUrl: http://everquest.mgon.com/common/members.phtml?ref=www.mgon.com&page=/company/index.phtml !--><script language="JavaScript">
<!--
function MM_openBrWindow(theURL,winName,features) { //v2.0
  window.open(theURL,winName,features);  
}
function login() {
  window.open('http://everquest.mgon.com/common/loginNew.phtml?ref=www.mgon.com&page=/company/index.phtml', 'Login', 'width=250,height=250,scrollbars=yes'); 
}
function member() {
  window.open('http://everquest.mgon.com/common/members.phtml?ref=www.mgon.com&page=/company/index.phtml', 'Member', 'width=500,height=600,scrollbars=yes'); 
}
//-->
</script>
<!-- Place the following code where you want an ad to appear -->
<SCRIPT LANGUAGE="JavaScript" SRC="http://ads.ad-flow.com/?DC=mgon-pop&JS=Y"></SCRIPT>
<NOSCRIPT>
<A HREF="http://ads.ad-flow.com/?SHT=mgon-pop"><IMG SRC="http://ads.ad-flow.com/?SIT=mgon-pop"></A>
</NOSCRIPT>
<table width="100%" border="0" cellspacing="0" cellpadding="0" background="/common/images/topplate/resize.gif">
  <tr> 
    <td> 
      <table width="488" border="0" cellspacing="0" cellpadding="0" background="/common/images/topplate/resize.gif">
				<tr> 
          <td><img src="/common/images/topplate/metalcorner.gif" width="5" height="20"></td>
				          <td><a href="javascript:login();"><img src="/common/images/topplate/memberlogin.gif" width="80" height="20" border="0"></a></td>					
			            <td><img src="/common/images/topplate/arrow.gif" width="10" height="20"></td>
          <td><img src="/common/images/topplate/metalcolumn.gif" width="3" height="20"></td>
          <td><a href="javascript:;" onClick="MM_openBrWindow('/common/sitemap.html','navigation','width=540,height=450')"><img src="/common/images/topplate/pc.gif" width="23" height="20" border="0"></a></td>
          <td><img src="/common/images/topplate/metalcolumn.gif" width="3" height="20"></td>
          <td><a href="javascript:;" onClick="MM_openBrWindow('/common/sitemap.html','navigation','width=540,height=450')"><img src="/common/images/topplate/action.gif" width="47" height="20" border="0"></a></td>
          <td><img src="/common/images/topplate/metalcolumn.gif" width="3" height="20"></td>
          <td><a href="javascript:;" onClick="MM_openBrWindow('/common/sitemap.html','navigation','width=540,height=450')"><img src="/common/images/topplate/roleplay.gif" width="62" height="20" border="0"></a></td>
          <td><img src="/common/images/topplate/metalcolumn.gif" width="3" height="20"></td>
          <td><a href="javascript:;" onClick="MM_openBrWindow('/common/sitemap.html','navigation','width=540,height=450')"><img src="/common/images/topplate/simulation.gif" width="70" height="20" border="0"></a></td>
          <td><img src="/common/images/topplate/metalcolumn.gif" width="3" height="20"></td>
          <td><a href="javascript:;" onClick="MM_openBrWindow('/common/sitemap.html','navigation','width=540,height=450')"><img src="/common/images/topplate/console.gif" width="56" height="20" border="0"></a></td>
          <td><img src="/common/images/topplate/metalcolumn.gif" width="3" height="20"></td>
          <td><a href="javascript:;" onClick="MM_openBrWindow('/common/sitemap.html','navigation','width=540,height=450')"><img src="/common/images/topplate/strategy.gif" width="64" height="20" border="0"></a></td>
          <td><img src="/common/images/topplate/metalcolumn.gif" width="3" height="20"></td>
          <td><a href="javascript:;" onClick="MM_openBrWindow('/common/sitemap.html','navigation','width=540,height=450')"><img src="/common/images/topplate/racing.gif" width="47" height="20" border="0"></a></td>
          <td><img src="/common/images/topplate/metalcolumn.gif" width="3" height="20"></td>
        </tr>
      </table>
    </td>
    <td background="/common/images/topplate/resize.gif" width="100%"><img src="/common/images/topplate/resize.gif" width="100%" height="20"></td>
    <td>
      <table width="88" border="0" cellspacing="0" cellpadding="0" background="/common/images/topplate/resize.gif">
        <tr>
          <td><img src="/common/images/topplate/metalcolumn.gif" width="3" height="20"></td>
          <td><a href="javascript:;" onClick="MM_openBrWindow('/common/sitemap.html','navigation','width=540,height=450')"><img src="/common/images/topplate/mgonetwork.gif" width="82" height="20" border="0"></a></td>
          <td><img src="/common/images/topplate/metalcorner.gif" width="5" height="20"></td>
        </tr>
      </table>
    </td>
  </tr>
</table>
<table width="100%" border="0" cellspacing="0" cellpadding="0" bgcolor="#000000">
  <tr> 
    <td><img src="http://193.45.143.23/1_1pix.gif?996801992" width="1" height="1" nosave></td>
  </tr>
</table>
</td>
  </tr>
</table>
<table width="772" border="0" cellspacing="0" cellpadding="0" align="center">
  <tr> 
    <td>

<TABLE width="772" border="0" cellspacing="0" cellpadding="0">

  <TR> 

    <TD><IMG src="/newimages/top/topleft.gif" width="592" height="81" border="0" usemap="#Map"><MAP name="Map"><AREA shape="rect" coords="13,36,138,76" href="http://www.mgon.com" alt="MGON Home" title="MGON Home"></MAP></TD>

    <TD width="100%" background="/newimages/top/resize.gif"><IMG src="/newimages/top/resize.gif" width="1" height="81"></TD>

    <TD><IMG src="/newimages/top/topright.gif" width="157" height="81"></TD>

  </TR>

</TABLE>


<TABLE width="772" border="0" cellspacing="0" cellpadding="0" bgcolor="#000000">
  <TR> 
		<TD align="center" width="130"> 
			<TABLE width="100%" border="0" cellspacing="0" cellpadding="0">
				<TR> 
					
          <TD align="center" background="/newimages/bannerarea/resize.gif"><OBJECT classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=4,0,2,0" width="120" height="60">
							<param name=movie value="http://www.mgon.com/flashmovies/mgochannel3.swf">
							<PARAM name=quality value=high>
							<PARAM name="menu" value="false">
							<embed src="http://www.mgon.com/flashmovies/mgochannel3.swf" quality=high pluginspage="http://www.macromedia.com/shockwave/download/index.cgi?P1_Prod_Version=ShockwaveFlash" 
type="application/x-shockwave-flash" menu="false" width="120" height="60">
							</EMBED> 
						</OBJECT></TD>
				</TR>
				<TR> 
					
          <TD><IMG src="/newimages/bannerarea/mgonchannel.gif" width="130" height="13"></TD>
				</TR>
			</TABLE>
		</TD>
		
    <TD align="center" width="490" valign="top"> 
      <!--Ad 468x60-->      <span class="smalltext"><NOLAYER><IFRAME SRC="http://ad.se.doubleclick.net/adi/mgon.com/;sz=468x60;ord=996801992?" bgcolor="#000000" width="468" height="60" frameborder="no" border="0" MARGINWIDTH="0" MARGINHEIGHT="0" SCROLLING="no"><A HREF="http://ad.se.doubleclick.net/jump/mgon.com/;abr=!ie;sz=468x60;ord=996801992?"><IMG SRC="http://ad.se.doubleclick.net/ad/mgon.com/;abr=!ie;sz=468x60;ord=996801992?" border="0" height="60" width="468"></A></IFRAME></NOLAYER><ILAYER id="layer1" visibility="hidden" width="468" height="60" align="center"></ILAYER></span><!--/Ad 468x60-->    </TD>
		
    <TD width="150" align="center" valign="top" background="/newimages/resizes/rightnav_black.gif"> 
      <!-- 120x60 code goes here -->
      
      <!-- 120x60 code goes here -->
    </TD>
	</TR>
</TABLE>
</td></tr></table>

<table width="772" border="0" cellspacing="0" cellpadding="0" align="center" background="/newimages/misc/50x50pix.gif">
  <tr>
    <td width="130" background="/newimages/resizes/leftnav.gif" valign="top"> 

<img src="/newimages/columns/sitecontent.gif" width="130" height="24"><br> 
<table width="130" border="0" cellspacing="0" cellpadding="0" bgcolor="#000000" background="/newimages/misc/50x50pix.gif">
  <tr bgcolor="#000000"> 
    <td> 
      <table width="100%" border=0 cellpadding=0 cellspacing=1>
        <tr bgcolor="#18355C"> 
          <td style="border='1 #18355C'" onMouseOver="style.backgroundColor='#FFFFFF'; style.cursor='hand'; style.border='1 #18355C'" onMouseOut="style.backgroundColor='#719FC6'; style.border='1 #18355C';" height="21" bgcolor="#719FC6"> 
            <table width="100%" border="0" cellspacing="0" cellpadding="0">
              <tr> 
                <td class="Bolded"><img src="/newimages/misc/navarrow.gif" width="12" height="21"></td>
                <td bgcolor="#18355C" height="21" width="100%"><a href="/" class="bluelinks" style="margin:0;">
<div><img src="/newimages/misc/1pix.gif" width="5" height="1" border="0">Home</div>
                  </a></td>
              </tr>
            </table>
          </td>
        </tr>
        <tr bgcolor="#18355C"> 
          <td style="border='1 #18355C'" onMouseOver="style.backgroundColor='#FFFFFF'; style.cursor='hand'; style.border='1 #18355C'" onMouseOut="style.backgroundColor='#719FC6'; style.border='1 #18355C';" height="21" bgcolor="#719FC6"> 
            <table width="100%" border="0" cellspacing="0" cellpadding="0">
              <tr> 
                <td class="Bolded"><img src="/newimages/misc/navarrow.gif" width="12" height="21"></td>
                <td bgcolor="#18355C" height="21" width="100%"><a href="/news.phtml" class="bluelinks" style="margin:0;"><div><img src="/newimages/misc/1pix.gif" width="5" height="1" border="0">News</div></a></td>
              </tr>
            </table>
          </td>
        </tr>
        <tr bgcolor="#18355C"> 
          <td style="border='1 #18355C'" onMouseOver="style.backgroundColor='#FFFFFF'; style.cursor='hand'; style.border='1 #18355C'" onMouseOut="style.backgroundColor='#719FC6'; style.border='1 #18355C';" height="21" bgcolor="#719FC6"> 
            <table width="100%" border="0" cellspacing="0" cellpadding="0">
              <tr> 
                <td class="Bolded"><img src="/newimages/misc/navarrow.gif" width="12" height="21"></td>
                <td bgcolor="#18355C" height="21" width="100%"><a href="/reviewindex.phtml" class="bluelinks" style="margin:0;">
<div><img src="/newimages/misc/1pix.gif" width="5" height="1" border="0">Reviews</div></a></td>
              </tr>
            </table>
          </td>
        </tr>
        <tr bgcolor="#18355C"> 
          <td style="border='1 #18355C'" onMouseOver="style.backgroundColor='#FFFFFF'; style.cursor='hand'; style.border='1 #18355C'" onMouseOut="style.backgroundColor='#719FC6'; style.border='1 #18355C';" height="21" bgcolor="#719FC6"> 
            <table width="100%" border="0" cellspacing="0" cellpadding="0">
              <tr> 
                <td class="Bolded"><img src="/newimages/misc/navarrow.gif" width="12" height="21"></td>
                <td bgcolor="#18355C" height="21" width="100%"><a href="/previewindex.phtml" class="bluelinks" style="margin:0;">
<div><img src="/newimages/misc/1pix.gif" width="5" height="1" border="0">Previews</div></a></td>
              </tr>
            </table>
          </td>
        </tr>
        <tr bgcolor="#18355C"> 
          <td style="border='1 #18355C'" onMouseOver="style.backgroundColor='#FFFFFF'; style.cursor='hand'; style.border='1 #18355C'" onMouseOut="style.backgroundColor='#719FC6'; style.border='1 #18355C';" height="21" bgcolor="#719FC6"> 
            <table width="100%" border="0" cellspacing="0" cellpadding="0">
              <tr> 
                <td class="Bolded"><img src="/newimages/misc/navarrow.gif" width="12" height="21"></td>
                <td bgcolor="#18355C" height="21" width="100%"><a href="/interviewindex.phtml" class="bluelinks" style="margin:0;">
<div><img src="/newimages/misc/1pix.gif" width="5" height="1" border="0">Interviews</div></a></td>
              </tr>
            </table>
          </td>
        </tr>
        <tr bgcolor="#18355C"> 
          <td style="border='1 #18355C'" onMouseOver="style.backgroundColor='#FFFFFF'; style.cursor='hand'; style.border='1 #18355C'" onMouseOut="style.backgroundColor='#719FC6'; style.border='1 #18355C';" height="21" bgcolor="#719FC6"> 
            <table width="100%" border="0" cellspacing="0" cellpadding="0">
              <tr> 
                <td class="Bolded"><img src="/newimages/misc/navarrow.gif" width="12" height="21"></td>
                <td bgcolor="#18355C" height="21" width="100%"><a href="/articleindex.phtml" class="bluelinks" style="margin:0;">
<div><img src="/newimages/misc/1pix.gif" width="5" height="1" border="0">Articles</div></a></td>
              </tr>
            </table>
          </td>
        </tr>
        <tr bgcolor="#18355C"> 
          <td style="border='1 #18355C'" onMouseOver="style.backgroundColor='#FFFFFF'; style.cursor='hand'; style.border='1 #18355C'" onMouseOut="style.backgroundColor='#719FC6'; style.border='1 #18355C';" height="21" bgcolor="#719FC6"> 
            <table width="100%" border="0" cellspacing="0" cellpadding="0">
              <tr> 
                <td class="Bolded"><img src="/newimages/misc/navarrow.gif" width="12" height="21"></td>
                <td bgcolor="#18355C" height="21" width="100%"><a href="/hardwareindex.phtml" class="bluelinks" style="margin:0;"> 
                  <div><img src="/newimages/misc/1pix.gif" width="5" height="1" border="0">Hardware</div>
                  </a></td>
              </tr>
            </table>
          </td>
        </tr>
        <tr bgcolor="#18355C"> 
          <td style="border='1 #18355C'" onMouseOver="style.backgroundColor='#FFFFFF'; style.cursor='hand'; style.border='1 #18355C'" onMouseOut="style.backgroundColor='#719FC6'; style.border='1 #18355C';" height="21" bgcolor="#719FC6"> 
            <table width="100%" border="0" cellspacing="0" cellpadding="0">
              <tr> 
                <td class="Bolded"><img src="/newimages/misc/navarrow.gif" width="12" height="21"></td>
                <td bgcolor="#18355C" height="21" width="100%"><a href="/fileindex.phtml" class="bluelinks" style="margin:0;"> 
                  <div><img src="/newimages/misc/1pix.gif" width="5" height="1" border="0">Downloads</div></a></td>
              </tr>
            </table>
          </td>
        </tr>
        <tr bgcolor="#18355C"> 
          <td style="border='1 #18355C'" onMouseOver="style.backgroundColor='#FFFFFF'; style.cursor='hand'; style.border='1 #18355C'" onMouseOut="style.backgroundColor='#719FC6'; style.border='1 #18355C';" height="21" bgcolor="#719FC6"> 
            <table width="100%" border="0" cellspacing="0" cellpadding="0">
              <tr> 
                <td class="Bolded"><img src="/newimages/misc/navarrow.gif" width="12" height="21"></td>
                <td bgcolor="#18355C" height="21" width="100%"><a href="http://www.mgoforum.com" class="bluelinks" style="margin:0;">
<div><img src="/newimages/misc/1pix.gif" width="5" height="1" border="0">MGOforums</div></a></td>
              </tr>
            </table>
          </td>
        </tr>
        <tr bgcolor="#18355C"> 
          <td style="border='1 #18355C'" onMouseOver="style.backgroundColor='#FFFFFF'; style.cursor='hand'; style.border='1 #18355C'" onMouseOut="style.backgroundColor='#719FC6'; style.border='1 #18355C';" height="21" bgcolor="#719FC6"> 
            <table width="100%" border="0" cellspacing="0" cellpadding="0">
              <tr> 
                <td class="Bolded"><img src="/newimages/misc/navarrow.gif" width="12" height="21"></td>
                <td bgcolor="#18355C" height="21" width="100%"><a href="http://www.mgoshop.com" class="bluelinks" style="margin:0;">
<div><img src="/newimages/misc/1pix.gif" width="5" height="1" border="0">MGOshop</div></a></td>
              </tr>
            </table>
          </td>
        </tr>
      </table>
    </td>
  </tr>
</table>
<table width="128" border="0" cellspacing="0" cellpadding="0" bgcolor="#000000">
  <tr> 
    <td> 
      <table width="100%" border="0" cellspacing="0" cellpadding="0" background="http://www.mgon.com/images/webtop_blue/websearch_bg.gif" align="center">
        <form name="MGON" action="http://www.mgon.com/search/search.phtml" method="get">
          <input type="hidden" name="INCLUDE" value="results">
          <tr> 
            <td> 
              <table width="100%" border="0" cellspacing="0" cellpadding="0" background="http://www.mgon.com/images/misc/50x50pix.gif">
                <tr> 
                  <td colspan="2"><img src="http://www.mgon.com/images/webtop_blue/finalsearch_01.gif" width="128" height="25"></td>
                </tr>
                <tr> 
                  <td align="center" colspan="2"> 
                    <input type="text" name="QUERY" style='WIDTH: 110; HEIGHT: 17; FONT-FAMILY: arial,helvetica; font-size:10px;' maxlength="50" size="13">
                  </td>
                </tr>
                <tr> 
                  <td><img src="http://www.mgon.com/images/webtop_blue/zone.gif" width="39" height="15"></td>
                  <td> 
                    <select name="ZONE" style='WIDTH: 75; HEIGHT: 15; FONT-FAMILY: arial,helvetica; font-size:10px;'>
                      <option value="mgon" selected>MGON</option>
                      <option value="web">Web</option>
                      <option value="games">Games</option>
                    </select>
                  </td>
                </tr>
              </table>
              <table width="100%" border="0" cellspacing="0" cellpadding="0">
                <tr> 
                  <td><input type="image" border="0" name="Search" src="http://www.mgon.com/images/webtop_blue/search.gif" width="75" height="22" alt="Search" align="top"></td>
                  <td><a href="http://www.mgon.com/search/search.phtml?INCLUDE=help"><img src="http://www.mgon.com/images/webtop_blue/help.gif" width="53" height="22" border="0" alt="Help"></a></td>
                </tr>
                <tr> 
                  <td colspan="2"><a href="http://www.mgon.com/search/powersearch.phtml"><img src="http://www.mgon.com/images/webtop_blue/powersearch.gif" width="128" height="20" border="0" alt="Power Search"></a></td>
                </tr>
                <tr> 
                  <td colspan="2"><a href="/search/download.phtml"><img src="http://www.mgon.com/images/webtop_blue/download.gif" width="128" height="31" border="0" alt="Download free search tool"></a></td>
                </tr>
              </table>
            </td>
          </tr>
        </form>
      </table>
    </td>
  </tr>
</table>
<table width="130" border="0" cellspacing="0" cellpadding="0" bgcolor="#000000" background="/newimages/misc/50x50pix.gif">
  <tr bgcolor="#000000"> 
    <td> 
      <table width="100%" border=0 cellpadding=0 cellspacing=1>
        <tr bgcolor="#18355C"> 
          <td style="border='1 #18355C'" onMouseOver="style.backgroundColor='#FFFFFF'; style.cursor='hand'; style.border='1 #18355C'" onMouseOut="style.backgroundColor='#719FC6'; style.border='1 #18355C';" height="21" bgcolor="#719FC6"> 
            <table width="100%" border="0" cellspacing="0" cellpadding="0">
              <tr> 
                <td class="Bolded"><img src="/newimages/misc/navarrow.gif" width="12" height="21"></td>
                <td bgcolor="#18355C" height="21" width="100%"><a href="/company/index.phtml" class="bluelinks" style="margin:0;">
<div><img src="/newimages/misc/1pix.gif" width="5" height="1" border="0">The Company</div></a></td>
              </tr>
            </table>
          </td>
        </tr>
        <tr bgcolor="#18355C"> 
          <td style="border='1 #18355C'" onMouseOver="style.backgroundColor='#FFFFFF'; style.cursor='hand'; style.border='1 #18355C'" onMouseOut="style.backgroundColor='#719FC6'; style.border='1 #18355C';" height="21" bgcolor="#719FC6"> 
            <table width="100%" border="0" cellspacing="0" cellpadding="0">
              <tr> 
                <td class="Bolded"><img src="/newimages/misc/navarrow.gif" width="12" height="21"></td>
                <td bgcolor="#18355C" height="21" width="100%"><a href="/mediakit/index.phtml" class="bluelinks" style="margin:0;">
<div><img src="/newimages/misc/1pix.gif" width="5" height="1" border="0">Our Mediakit</div></a></td>
              </tr>
            </table>
          </td>
        </tr>
        <tr bgcolor="#18355C"> 
          <td style="border='1 #18355C'" onMouseOver="style.backgroundColor='#FFFFFF'; style.cursor='hand'; style.border='1 #18355C'" onMouseOut="style.backgroundColor='#719FC6'; style.border='1 #18355C';" height="21" bgcolor="#719FC6"> 
            <table width="100%" border="0" cellspacing="0" cellpadding="0">
              <tr> 
                <td class="Bolded"><img src="/newimages/misc/navarrow.gif" width="12" height="21"></td>
                <td bgcolor="#18355C" height="21" width="100%"><a href="/press.phtml" class="bluelinks" style="margin:0;">
<div><img src="/newimages/misc/1pix.gif" width="5" height="1" border="0">Press Material</div></a></td>
              </tr>
            </table>
          </td>
        </tr>
        <tr bgcolor="#18355C"> 
          <td style="border='1 #18355C'" onMouseOver="style.backgroundColor='#FFFFFF'; style.cursor='hand'; style.border='1 #18355C'" onMouseOut="style.backgroundColor='#719FC6'; style.border='1 #18355C';" height="21" bgcolor="#719FC6"> 
            <table width="100%" border="0" cellspacing="0" cellpadding="0">
              <tr> 
                <td class="Bolded"><img src="/newimages/misc/navarrow.gif" width="12" height="21"></td>
                <td bgcolor="#18355C" height="21" width="100%"><a href="/contactus/index.phtml" class="bluelinks" style="margin:0;">
<div><img src="/newimages/misc/1pix.gif" width="5" height="1" border="0">Contact Us</div></a></td>
              </tr>
            </table>
          </td>
        </tr>
      </table>
    </td>
  </tr>
</table>

    </td>
    <TD width="642" valign="top" background="/newimages/backgrounds/middlecolumn_black_wide.gif"> 
      <table width="100%" border="0" cellspacing="0" cellpadding="0" background="/newimages/sections/resize.gif">
        <tr> 
          <td width="100%" valign="bottom">&nbsp; </td>
          <td align="right"><img src="/newimages/sections/thecompany.gif"></td>
        </tr>
      </table>
      <table width="100%" border="0" cellspacing="0" cellpadding="12">
        <tr> 
          <td valign="top" width="100%"> 
            <p class="Headline"><a name="briefdesc"></a>Brief Description of MGON</p>
            <p>What started out as the hobby of a handful of game enthusiasts 
              2 years ago has grown into a large multinational corporation employing 
              over 400 professionals across the globe. Media and Games Online 
              Network, the Gamers' Choice, is quickly becoming the premier portal 
              for avid gamers on the web. Built to be the ultimate games community 
              resource, by the people who play the games, MGON's fan sites provide 
              a huge spectrum of gaming information and resources for the web 
              generation audience. Today, the MGONetwork consists of over 40 top 
              quality websites.</p>
            <p class="Headline">Management </p>
            <p><span class="Bolded"><b>Owners/Management</b></span><br>
              The company is fully owned by Jan Isacsson, Lars Furubom, Thomas 
              Isacsson, Johan Isacsson and Ledstiernan. </p>
            <p><span class="Bolded"><b>The Board of Directors</b></span><br>
              Jan Isacsson - CEO<br>
              Lars Furubom - Chairman of the Board and Marketing, Sales and PR 
              Director<br>
              Thomas Isacsson - Production Director<br>
              Johan Isacsson - CTO<br>
              Thomas Ros&eacute;n - Ledstiernan Partner.<br>
              Fredrik Linton - Ledstiernan Investment Manager</p>
            <p><b>Core Staff</b><br>
              <a href="mailto:steve@mgon.com">Steve Bonham</a> - Site Manager, 
              The Sims Resource<br>
              <a href="mailto:per@mgon.com">Per Burstr&ouml;m</a> - Senior Programmer, 
              NetOffice<br>
              <a href="mailto:warren@mgon.com">Warren Chandler</a> - Site Manager, 
              Playstation Center<br>
              <a href="mailto:miff@mgon.com">Mike Fahey</a> - Content Editor and 
              Newsletter Editor<br>
              <a href="mailto:hans@mgon.com">Hans Forsman</a> - Financial Controller<br>
              <a href="mailto:lars@mgon.com">Lars Furubom</a> - Marketing, Sales 
              and PR Director<br>
              <a href="mailto:jan@mgon.com">Jan Isacsson</a> - CEO <br>
              <a href="mailto:johan@mgon.com">Johan Isacsson</a> - CTO<br>
              <a href="mailto:thomas@mgon.com">Thomas Isacsson</a> - Production 
              Director <br>
              <a href="mailto:ka2@mgon.com">Ben Lewis</a> - Programmer and Hosting 
              Administrator<br>
              <a href="mailto:niklas@mgon.com">Niklas Lundqvist</a> - Senior Graphics 
              Artist <br>
              <a href="mailto:peter@mgon.com">Peter L&ouml;fstrand</a> - Production 
              Manager<br>
              <a href="mailto:fredrik@mgon.com">Fredrik Olofsson</a> - Site and 
              Staff Management and Editor-in-Chief MGON.se<br>
              <a href="mailto:satu@mgon.com">Satu Rajam&auml;ki</a> - Marketing 
              Manager<br>
              <a href="mailto:oscar@mgon.com">Oscar Rylin</a> - Programmer and 
              Forum Administrator<br>
              <a href="mailto:kris@mgon.com">Kris Saw</a> - Network Administration 
              and Editor-in-Chief MGON.com<br>
              <a href="mailto:pommes@mgon.com">Micke Sundberg</a> - Senior Programmer<br>
              <a href="mailto:corven@mgon.com">Colin Tutty</a> - Content Manager<br>
              <a href="mailto:dale@mgon.com">Dale Wynn</a> - Public Relations 
              Manager<br>
            </p>
            <p> <b>Site Managers</b><br>
              35 people</p>
            <p><b>Site Contributors</b><br>
              150 - 250 people</p>
            <p>&nbsp;</p>
            <p class="Headline"><a name="partnerships"></a>Our Partnerships </p>
            <p><span class="Bolded">Enter The Game IRC Network</span><br>
              In June 2000 we partnered with ETG, putting all our channels on 
              their network and thus give both them and ourselves more traffic 
              and possibilities to cross promote our services. We are also working 
              on a hosting service together with them which we hope to release 
              more information about during Quarter 3.</p>
            <p>Connect to irc.enterthegame.com and join #lounge or #mgon for MGON 
              related chats and #etg for ETG related chats. See you there!</p>
            <p><span class="Bolded">If you are interested in discussing potential 
              partnerships with us, please use the contact information available 
              on the</span> <a href="/contactus">Contact Us</a> <span class="Bolded">page.</span></p>
            </td>
        </tr>
      </table>
    </TD>
  </TR>
</TABLE>
 
<table width="772" border="0" cellspacing="0" cellpadding="0" align="center">
  <tr>
    <td><img src="/newimages/bottom/copyright.gif" width="621" height="30" border="0" usemap="#Map2"></td>
    <td><a href="/"><img src="/newimages/bottom/home.gif" width="75" height="30" border="0"></a></td>
    <td><a href="#top"><img src="/newimages/bottom/top.gif" width="76" height="30" border="0"></a></td>
  </tr>
</table>
<TABLE width="772" border="0" cellspacing="0" cellpadding="0" height="90" background="/images2/misc/50x50pix.gif" align="center">
  <TR bgcolor="#000000" align="center"> 
    <TD class="smalltext"><SCRIPT language="JavaScript"
src="http://adtegrity.spinbox.net/?DC=Mgon+Bottom&JS=Y&TARGET=_new">
</SCRIPT><NOSCRIPT><A href="http://adtegrity.spinbox.net/?SHT=Mgon+Bottom" target="_new"
height="468" width="60"><IMG src="http://adtegrity.spinbox.net/?SIT=Mgon+Bottom" border="0"></A></NOSCRIPT></TD>
  </TR>
</TABLE>
<map name="Map">
  <area shape="rect" coords="387,7,495,25" href="/privacy.phtml">
</map>
<map name="Map2">
  <area shape="rect" coords="384,4,496,26" href="/privacy">
</map>
  
<!--Bottom Layer-->
      <LAYER SRC="http://ad.se.doubleclick.net/adl/mgon.com/;sz=468x60;ord=996801992?" bgcolor="#000000" width="468" height="60" visibility="hidden" onLoad="moveToAbsolute(layer1.pageX,layer1.pageY);clip.height=60;clip.width=468; visibility='show';"></LAYER><!--End Bottom Layer--></BODY>

</HTML>


