<!--
                 This page has been created by Renaissance IT
   Renaissance Internet Technologies Copyright (c) 1999 All Rights Reserved.

             for more info on our products, please visit :
                        http://www.renaissance.nl/

	This script has been written by Roy Boverhof <rboverhof@renaissance.nl>
	
        Pagename                : electrum_analysis.html
        Last Updated    		: 31-01-2000
-->

<HTML>
<HEAD>
	<TITLE>the Seekers of Lore : Electrum Analysis Chart</TITLE>
</HEAD>

<BODY BGCOLOR="#000000" TEXT="#000000" LINK="#000000" VLINK="#000000" ALINK="#000000">
<DIV ALIGN="CENTER">
<BR>
<!-- FGN Banner Code -->
<script language="JavaScript">
	<!-- Hide from old browsers
	var random = new Number(Math.floor(9999999 * Math.random())+1);

	// Modify to reflect site specifics
	page = "eqlore.com/";
	target = "@Top1,x02,x05,x08!Top1";

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript1.1" SRC="http://oascentral.cybereps.com/RealMedia/ads/adstream_jx.ads/' + page + 1 + random + target + '">');
	document.write('</SCR');
	document.write('IPT>');

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript">');
	document.write('_version=10; //-->');
	document.write('</SCR');
	document.write('IPT>');

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript1.1">');
	document.write('_version=11; //-->');
	document.write('</SCR');
	document.write('IPT>');

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript">');

	if (navigator.appVersion.indexOf('MSIE 3') != -1){
	document.write('<IFRAME MARGINWIDTH=0 MARGINHEIGHT=0 HSPACE=0 VSPACE=0 FRAMEBORDER=0 SCROLLING=no BORDERCOLOR="#000000" SRC="oascentral.cybereps.com/RealMedia/ads/adstream_sx.ads/' + page + random + target + '"></IFRAME>');
	  }
	else if (_version < 11) {
	document.write ('<A HREF="http://oascentral.cybereps.com/RealMedia/ads/click_nx.ads/' + page + random + target + '"><IMG SRC="http://oascentral.cybereps.com/RealMedia/ads/adstream_nx.ads/' + page + random + target + '"></a>');
	  }

	document.write('</SCR');
	document.write('IPT>');

	// End Hide -->
</script>
<!-- END FGN Banner Code --><BR>
<TABLE CELLSPACING = 0 CELLPADDING = 0 BORDER = 0>
<TR>
	<TD width="63"><IMG SRC = "http://www.loreseekers.com/graphics/topc000.jpg" WIDTH = 63 HEIGHT = 87></TD>
	<TD width="473"><IMG SRC = "http://www.loreseekers.com/graphics/topc001.jpg" WIDTH = 473 HEIGHT = 87></TD>
	<TD width="64"><IMG SRC = "http://www.loreseekers.com/graphics/topc002.jpg" WIDTH = 64 HEIGHT = 87></TD>
</TR>
	<TD width="63"></TD>
	<TD BGCOLOR="#BEA279" width="460">
	<DIV ALIGN="CENTER">
	<TABLE>
	<TR>
	<TD BGCOLOR="#BEA279" width="450">
	
<P ALIGN="left"><FONT SIZE="4" face="helvetica"><STRONG>D. Electrum Analysis</STRONG></FONT></A></P>


<!-- START OF CONVERTED OUTPUT -->
<!-- ------------------------- -->
<Table border>
<TR ALIGN="center" VALIGN="bottom">
<TD BGCOLOR=#C0C0C0><FONT FACE="Verdana" SIZE="1" COLOR=#FFFFFF><B>
Stone</B></FONT></TD>
<TD BGCOLOR=#C0C0C0><FONT FACE="Verdana" SIZE="1" COLOR=#FFFFFF><B>
Property</B></FONT></TD>
<TD BGCOLOR=#C0C0C0><FONT FACE="Verdana" SIZE="1" COLOR=#FFFFFF><B>
Cost (cp)</B></FONT></TD>
<TD BGCOLOR=#C0C0C0><FONT FACE="Verdana" SIZE="1" COLOR=#FFFFFF><B>
Ench Electrum</B></FONT></TD>
<TD BGCOLOR=#C0C0C0><FONT FACE="Verdana" SIZE="1" COLOR=#FFFFFF><B>
Type</B></FONT></TD>
<TD BGCOLOR=#C0C0C0><FONT FACE="Verdana" SIZE="1" COLOR=#FFFFFF><B>
PP</B></FONT></TD>
<TD BGCOLOR=#C0C0C0><FONT FACE="Verdana" SIZE="1" COLOR=#FFFFFF><B>
GP</B></FONT></TD>
<TD BGCOLOR=#C0C0C0><FONT FACE="Verdana" SIZE="1" COLOR=#FFFFFF><B>
Profit (pp)</B></FONT></TD>
<TD BGCOLOR=#C0C0C0><FONT FACE="Verdana" SIZE="1" COLOR=#FFFFFF><B>
Profit (%)</B></FONT></TD>
</TR>
<TR ALIGN="center" VALIGN="bottom">
<TD BGCOLOR=#FF9900 COLSPAN=9><FONT FACE="Verdana" SIZE="2"><B>
Useful Items (Minimum)</B></FONT></TD>
</TR>
<TR ALIGN="center" VALIGN="bottom">
<TD><FONT FACE="Verdana" SIZE="1">
Cat's Eye Agate</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
CHR</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
2835</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1">
+4</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Bracelet</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
5</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
0</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0.00"><FONT FACE="Verdana" SIZE="1">
2.17</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0%"><FONT FACE="Verdana" SIZE="1">
76%</FONT></TD>
</TR>
<TR ALIGN="center" VALIGN="bottom">
<TD><FONT FACE="Verdana" SIZE="1">
Bloodstone</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
STA</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
3150</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1">
+3</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Necklace</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
5</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
5</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0.00"><FONT FACE="Verdana" SIZE="1">
2.35</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0%"><FONT FACE="Verdana" SIZE="1">
75%</FONT></TD>
</TR>
<TR ALIGN="center" VALIGN="bottom">
<TD><FONT FACE="Verdana" SIZE="1">
Onyx</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
DEX</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
3277</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1">
+3</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Necklace</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
6</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
0</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0.00"><FONT FACE="Verdana" SIZE="1">
2.72</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0%"><FONT FACE="Verdana" SIZE="1">
83%</FONT></TD>
</TR>
<TR ALIGN="center" VALIGN="bottom">
<TD><FONT FACE="Verdana" SIZE="1">
Jasper</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
WIS</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
3412</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1">
+2</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Earring</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
7</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
0</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0.00"><FONT FACE="Verdana" SIZE="1">
3.59</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0%"><FONT FACE="Verdana" SIZE="1">
105%</FONT></TD>
</TR>
<TR ALIGN="center" VALIGN="bottom">
<TD><FONT FACE="Verdana" SIZE="1">
Carnelian</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
AGI</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
3517</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1">
+3</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Ring</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
7</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
0</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0.00"><FONT FACE="Verdana" SIZE="1">
3.48</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0%"><FONT FACE="Verdana" SIZE="1">
99%</FONT></TD>
</TR>
<TR ALIGN="center" VALIGN="bottom">
<TD><FONT FACE="Verdana" SIZE="1">
Star Rose Quartz</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
INT</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
3675</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1">
+2</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Necklace</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
7</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
0</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0.00"><FONT FACE="Verdana" SIZE="1">
3.33</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0%"><FONT FACE="Verdana" SIZE="1">
90%</FONT></TD>
</TR>
<TR ALIGN="center" VALIGN="bottom">
<TD><FONT FACE="Verdana" SIZE="1">
Jade</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Mana / HP / AC</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
6300</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1">
+10/+10/+2</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Bracelet</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
7</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
0</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0.00"><FONT FACE="Verdana" SIZE="1">
0.70</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0%"><FONT FACE="Verdana" SIZE="1">
11%</FONT></TD>
</TR>
<TR ALIGN="center" VALIGN="bottom">
<TD><FONT FACE="Verdana" SIZE="1">
Opal</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Sta / Agi</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
20475</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1">
+4/+3</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Necklace</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
30</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
0</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0.00"><FONT FACE="Verdana" SIZE="1">
9.53</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0%"><FONT FACE="Verdana" SIZE="1">
47%</FONT></TD>
</TR>
<TR ALIGN="center" VALIGN="bottom">
<TD><FONT FACE="Verdana" SIZE="1">
Star Ruby</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Dex / Chr</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
70875</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1">
+5/+7</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Ring</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
120</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
0</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0.00"><FONT FACE="Verdana" SIZE="1">
49.13</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0%"><FONT FACE="Verdana" SIZE="1">
69%</FONT></TD>
</TR>
<TR ALIGN="center" VALIGN="bottom">
<TD><FONT FACE="Verdana" SIZE="1">
Fire Emerald</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Str / Dex</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
91875</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1">
+3/+5</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Bracelet</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
150</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
0</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0.00"><FONT FACE="Verdana" SIZE="1">
58.13</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0%"><FONT FACE="Verdana" SIZE="1">
63%</FONT></TD>
</TR>
<TR ALIGN="center" VALIGN="bottom">
<TD><FONT FACE="Verdana" SIZE="1">
Sapphire</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Str / Int</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
107625</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1">
+4/+2</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Earring</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
180</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
0</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0.00"><FONT FACE="Verdana" SIZE="1">
72.38</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0%"><FONT FACE="Verdana" SIZE="1">
67%</FONT></TD>
</TR>
<TR ALIGN="center" VALIGN="bottom">
<TD><FONT FACE="Verdana" SIZE="1">
Ruby</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Str / Wis</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
133625</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1">
+4/+2</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Ring</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
200</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
0</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0.00"><FONT FACE="Verdana" SIZE="1">
66.38</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0%"><FONT FACE="Verdana" SIZE="1">
50%</FONT></TD>
</TR>
<TR ALIGN="center" VALIGN="bottom">
<TD BGCOLOR=#FF9900 COLSPAN=9><FONT FACE="Verdana" SIZE="2"><B>
Useful Items (Recommended)</B></FONT></TD>
</TR>
<TR ALIGN="center" VALIGN="bottom">
<TD><FONT FACE="Verdana" SIZE="1">
Cat's Eye Agate</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
CHR</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
2835</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1">
+4</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Bracelet</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
12</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
0</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0.00"><FONT FACE="Verdana" SIZE="1">
9.17</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0%"><FONT FACE="Verdana" SIZE="1">
323%</FONT></TD>
</TR>
<TR ALIGN="center" VALIGN="bottom">
<TD><FONT FACE="Verdana" SIZE="1">
Bloodstone</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
STA</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
3150</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1">
+3</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Necklace</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
10</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
0</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0.00"><FONT FACE="Verdana" SIZE="1">
6.85</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0%"><FONT FACE="Verdana" SIZE="1">
217%</FONT></TD>
</TR>
<TR ALIGN="center" VALIGN="bottom">
<TD><FONT FACE="Verdana" SIZE="1">
Onyx</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
DEX</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
3277</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1">
+3</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Necklace</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
10</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
0</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0.00"><FONT FACE="Verdana" SIZE="1">
6.72</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0%"><FONT FACE="Verdana" SIZE="1">
205%</FONT></TD>
</TR>
<TR ALIGN="center" VALIGN="bottom">
<TD><FONT FACE="Verdana" SIZE="1">
Jasper</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
WIS</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
3412</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1">
+2</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Earring</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
12</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
0</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0.00"><FONT FACE="Verdana" SIZE="1">
8.59</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0%"><FONT FACE="Verdana" SIZE="1">
252%</FONT></TD>
</TR>
<TR ALIGN="center" VALIGN="bottom">
<TD><FONT FACE="Verdana" SIZE="1">
Carnelian</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
AGI</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
3517</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1">
+3</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Ring</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
10</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
0</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0.00"><FONT FACE="Verdana" SIZE="1">
6.48</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0%"><FONT FACE="Verdana" SIZE="1">
184%</FONT></TD>
</TR>
<TR ALIGN="center" VALIGN="bottom">
<TD><FONT FACE="Verdana" SIZE="1">
Star Rose Quartz</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
INT</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
3675</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1">
+2</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Necklace</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
10</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
0</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0.00"><FONT FACE="Verdana" SIZE="1">
6.33</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0%"><FONT FACE="Verdana" SIZE="1">
172%</FONT></TD>
</TR>
<TR ALIGN="center" VALIGN="bottom">
<TD><FONT FACE="Verdana" SIZE="1">
Jade</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Mana / HP / AC</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
6300</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1">
+10/+10/+2</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Bracelet</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
17</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
0</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0.00"><FONT FACE="Verdana" SIZE="1">
10.70</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0%"><FONT FACE="Verdana" SIZE="1">
170%</FONT></TD>
</TR>
<TR ALIGN="center" VALIGN="bottom">
<TD><FONT FACE="Verdana" SIZE="1">
Opal</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Sta / Agi</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
20475</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1">
+4/+3</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Necklace</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
50</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
0</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0.00"><FONT FACE="Verdana" SIZE="1">
29.53</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0%"><FONT FACE="Verdana" SIZE="1">
144%</FONT></TD>
</TR>
<TR ALIGN="center" VALIGN="bottom">
<TD><FONT FACE="Verdana" SIZE="1">
Star Ruby</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Dex / Chr</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
70875</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1">
+5/+7</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Ring</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
160</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
0</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0.00"><FONT FACE="Verdana" SIZE="1">
89.13</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0%"><FONT FACE="Verdana" SIZE="1">
126%</FONT></TD>
</TR>
<TR ALIGN="center" VALIGN="bottom">
<TD><FONT FACE="Verdana" SIZE="1">
Fire Emerald</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Str / Dex</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
91875</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1">
+3/+5</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Bracelet</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
180</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
0</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0.00"><FONT FACE="Verdana" SIZE="1">
88.13</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0%"><FONT FACE="Verdana" SIZE="1">
96%</FONT></TD>
</TR>
<TR ALIGN="center" VALIGN="bottom">
<TD><FONT FACE="Verdana" SIZE="1">
Sapphire</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Str / Int</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
107625</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1">
+4/+2</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Earring</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
200</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
0</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0.00"><FONT FACE="Verdana" SIZE="1">
92.38</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0%"><FONT FACE="Verdana" SIZE="1">
86%</FONT></TD>
</TR>
<TR ALIGN="center" VALIGN="bottom">
<TD><FONT FACE="Verdana" SIZE="1">
Ruby</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Str / Wis</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
133625</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1">
+4/+2</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Ring</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
220</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
0</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0.00"><FONT FACE="Verdana" SIZE="1">
86.38</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0%"><FONT FACE="Verdana" SIZE="1">
65%</FONT></TD>
</TR>
<TR ALIGN="center" VALIGN="bottom">
<TD BGCOLOR=#FF9900 COLSPAN=9><FONT FACE="Verdana" SIZE="2"><B>
Monster Loot</B></FONT></TD>
</TR>
<TR ALIGN="center" VALIGN="bottom">
<TD><FONT FACE="Verdana" SIZE="1">
Jacinth</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Vs Magic / AC</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
3517</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1">
?</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
?</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
?</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
?</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0.00"><FONT FACE="Verdana" SIZE="1">
?</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0%"><FONT FACE="Verdana" SIZE="1">
?</FONT></TD>
</TR>
<TR ALIGN="center" VALIGN="bottom">
<TD><FONT FACE="Verdana" SIZE="1">
Wolf's Eye Agate</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Vs Magic</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
5625</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1">
+4</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Necklace</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
?</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
?</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0.00"><FONT FACE="Verdana" SIZE="1">
?</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0%"><FONT FACE="Verdana" SIZE="1">
?</FONT></TD>
</TR>
<TR ALIGN="center" VALIGN="bottom">
<TD><FONT FACE="Verdana" SIZE="1">
Black Pearl</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Dex / Agi</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
23625</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1">
+3/+3</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Ring</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
?</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
?</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0.00"><FONT FACE="Verdana" SIZE="1">
?</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0%"><FONT FACE="Verdana" SIZE="1">
?</FONT></TD>
</TR>
<TR ALIGN="center" VALIGN="bottom">
<TD><FONT FACE="Verdana" SIZE="1">
Diamond</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Vs All</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
213625</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1">
+3</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Ring</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
?</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
?</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
?</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
?</FONT></TD>
</TR>
<TR ALIGN="center" VALIGN="bottom">
<TD><FONT FACE="Verdana" SIZE="1">
Black Sapphire</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
HP / Mana</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
252625</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1">
?</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
?</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
?</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
?</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0.00"><FONT FACE="Verdana" SIZE="1">
?</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0%"><FONT FACE="Verdana" SIZE="1">
?</FONT></TD>
</TR>
<TR ALIGN="center" VALIGN="bottom">
<TD><FONT FACE="Verdana" SIZE="1">
Fire Opal</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
HP/ AC</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
252625</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1">
+30/+2</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Ring</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
?</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
?</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
?</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
?</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD BGCOLOR=#FF9900 COLSPAN=9><FONT FACE="Verdana" SIZE="2">&nbsp;</FONT></TD>
</TR>
<TR ALIGN="center" VALIGN="bottom">
<TD COLSPAN=4><FONT FACE="Verdana" SIZE="1">
&nbsp;</FONT></TD>
<TD COLSPAN=5><FONT FACE="Verdana" SIZE="1">
Based on Information From</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="right"><FONT FACE="Verdana" SIZE="1">
&nbsp;</FONT></TD>
<TD ALIGN="right"><FONT FACE="Verdana" SIZE="1">
&nbsp;</FONT></TD>
<TD ALIGN="right"><FONT FACE="Verdana" SIZE="1">
&nbsp;</FONT></TD>
<TD ALIGN="right"><FONT FACE="Verdana" SIZE="1">
&nbsp;</FONT></TD>
<TD COLSPAN=5 ALIGN="center"><FONT FACE="Verdana" SIZE="1">
Casters Realm</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="right"><FONT FACE="Verdana" SIZE="1">
&nbsp;</FONT></TD>
<TD ALIGN="right"><FONT FACE="Verdana" SIZE="1">
&nbsp;</FONT></TD>
<TD ALIGN="right"><FONT FACE="Verdana" SIZE="1">
&nbsp;</FONT></TD>
<TD ALIGN="right"><FONT FACE="Verdana" SIZE="1">
&nbsp;</FONT></TD>
<TD COLSPAN=5 ALIGN="center"><FONT FACE="Verdana" SIZE="1">
http://eq.castersrealm.com</FONT></TD>
</TR>
</Table>
<!-- ------------------------- -->
<!-- END OF CONVERTED OUTPUT -->
<!-- ------------------------- -->


<BR><BR><DIV ALIGN="center"><A HREF="new_jewelry_guide.phtml" TARGET="_self"><IMG SRC="back_button.jpg" WIDTH=200 HEIGHT=50 BORDER=0 ALIGN="MIDDLE" ALT="Back to the Guide"></A></DIV><BR><BR>


</TR>
</TABLE>
	<TD width="64"></TD>
<TR>
	<TD><IMG SRC = "http://www.loreseekers.com/graphics/botc000.jpg" WIDTH = 63 HEIGHT = 87></TD>
	<TD><IMG SRC = "http://www.loreseekers.com/graphics/botc001.jpg" WIDTH = 473 HEIGHT = 87></TD>
	<TD><IMG SRC = "http://www.loreseekers.com/graphics/botc002.jpg" WIDTH = 64 HEIGHT = 87></TD>
</TR>
</TABLE>
<BR>
<IMG SRC="http://service.bfast.com/bfast/serve?bfmid=1375281&siteid=40292692&bfpage=pc" BORDER="0" WIDTH="1" HEIGHT="1" NOSAVE ><A HREF="http://service.bfast.com/bfast/click?bfmid=1375281&siteid=40292692&bfpage=pc" TARGET="_new"><IMG SRC="http://affiliate.gamestop.com/affIMG/pc_120x60.gif" BORDER="0" WIDTH="120" HEIGHT="60" ALT="PC Games at GameStop.com"></A>
<BR>
<BR>
</DIV>
</BODY>
</HTML>
