<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">

<html>
<head>
	<title>..:: EQBard : le site de Jonili le petit barde ::..</title>

<SCRIPT LANGUAGE="Javascript">
<!--
function fenetre(intitule,params) { 
var fen = window.open(intitule,'zoom',params); 
}
//-->
</script>

<style>
a.lientexte {color:#0B5040;text-decoration:none;}
a.lientexte:hover {color:#0B5040;text-decoration:underline;}
</style>
</head>

<body bgcolor='#CFE6E3' text='#000000' link='#0B5040' vlink='#000000' alink='#000000'>
<table width='680' border='0' cellspacing='0' cellpadding='0'>
<tr><td>
<table width='680' border='0' cellspacing='0' cellpadding='0'>
<tr>
<td width='680' align='right' valign='top'>
<img src='./img/commun/c01/carre80.gif' width='10' height='10' border='0' alt=''>
<img src='./img/commun/c01/carre70.gif' width='10' height='10' border='0' alt=''>
<img src='./img/commun/c01/carre60.gif' width='10' height='10' border='0' alt=''>
<img src='./img/commun/c01/carre50.gif' width='10' height='10' border='0' alt=''>
</td></tr>
<tr><td height='2'><img src='./img/commun/transparent.gif' height='2' alt='' border='0'></td></tr>
<tr><td width='680' height='1'><img src='./img/commun/c01/carre50.gif' width='680' height='1' alt='' border='0'></td></tr>
</table>
</td></tr><tr><td>
<table width='680' border='0' cellspacing='0' cellpadding='0'>
<tr><td width='120' valign='top'><table width='100%' border='0' cellspacing='0' cellpadding='0'>
<tr><td>
<font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>&nbsp;<br>
<img src='./img/commun/c01/carre70.gif' width='10' height='10' border='0' alt=''>&nbsp;<a href=index.php?menu=1&data=1 class=lientexte><b>Accueil</b></a><br>&nbsp;<br>
<img src='./img/commun/c01/carre70.gif' width='10' height='10' border='0' alt=''>&nbsp;<a href=index.php?menu=2&data=2&order=1 class=lientexte><b>Chants</b></a><br>&nbsp;<br>
<img src='./img/commun/c01/carre70.gif' width='10' height='10' border='0' alt=''>&nbsp;<b>Equipement</b><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=31&data=31&inc=instruments class=lientexte>Instruments</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=32&data=31&inc=armures class=lientexte>Armures</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=33&data=31&inc=armes&order=1&sens=1&bard=1 class=lientexte>Armes</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=34&data=31&inc=resist class=lientexte>Resist gear</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=35&data=31&inc=slot class=lientexte>Par slot</a><br>&nbsp;<br>
<img src='./img/commun/c01/carre70.gif' width='10' height='10' border='0' alt=''>&nbsp;<b>Guides</b><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=41&data=41 class=lientexte>Général</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carreselect.gif' width='5' height='5' border='0' alt=''>&nbsp;Tactiques<br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=43&data=43 class=lientexte>Quêtes</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=44&data=44 class=lientexte>Zones</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=45&data=45 class=lientexte>Procs</a><br>&nbsp;<br>
<img src='./img/commun/c01/carre70.gif' width='10' height='10' border='0' alt=''>&nbsp;<b>Photos</b><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=51&data=51 class=lientexte>Atlas</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=52&data=52 class=lientexte>Bardes</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=54&data=54 class=lientexte>GM</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=55&data=55 class=lientexte>Divers</a><br>&nbsp;<br>
<img src='./img/commun/c01/carre70.gif' width='10' height='10' border='0' alt=''>&nbsp;<a href=index.php?menu=8&data=8 class=lientexte><b>Mode</b></a><br>&nbsp;<br>
<img src='./img/commun/c01/carre70.gif' width='10' height='10' border='0' alt=''>&nbsp;<a href=index.php?menu=6&data=6 class=lientexte><b>Liens</b></a><br>
<img src='./img/commun/c01/carre70.gif' width='10' height='10' border='0' alt=''>&nbsp;<a href=index.php?menu=7&data=7 class=lientexte><b>Download</b></a><br>
<img src='./img/commun/c01/carre70.gif' width='10' height='10' border='0' alt=''>&nbsp;<a href='http://forumsfr.ubi.com/messages/overview.asp?name=eq_themaeq_eqbardes' target='_blank' class=lientexte><b>Forum</b></a><br>
<img src='./img/commun/c01/carre70.gif' width='10' height='10' border='0' alt=''>&nbsp;<a href=mailto:jonili@eqbard.eqloft.com class=lientexte><b>M'écrire</b></a><br>&nbsp;<br>
<img src='./img/commun/c01/carre70.gif' width='10' height='10' border='0' alt=''>&nbsp;<a href=index.php?menu=9&data=9 class=lientexte><b>Backstage</b></a><br>&nbsp;<br></font></td></tr></table>
</td><td width='20' valign='top'><img src='./img/commun/c01/carre50.gif' width='10' height='10' border='0' alt=''>
<img src='./img/commun/c01/carre60.gif' width='10' height='10' border='0' alt=''>
<img src='./img/commun/c01/carre70.gif' width='10' height='10' border='0' alt=''>
<img src='./img/commun/c01/carre80.gif' width='10' height='10' border='0' alt=''>
</td><td width='540' align='left' valign='top'><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>&nbsp;<br><a href='index.php?menu=42&data=42 class=lientexte' class=lientexte><b>< Retour</b></a><br>&nbsp;<br><table width='100%' border='0' cellspacing='0' cellpadding='0'><tr><td colspan='2' bgcolor='#0B5040'><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2' color='white'><b>&nbsp;Potion de gate pour Thurgadin</b></font></td></tr><tr><td width ='10'>&nbsp;</td><td><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>&nbsp;<br>
Voilà la recette de la potion de gate pour Thurgadin.
<br>&nbsp;<br>
Il faut être 122 en poterie pour la faire facilement. 
<br>&nbsp;<br>
La potion vous amène sur le petit pont à l'entree de la ville. Pour l'activer, mettre la potion dans l'inventaire (pas dans un sac) et cliquer dessus avec le bouton droit : LOADING, PLEASE WQAIT....
<br>&nbsp;<br>

</font>&nbsp;<br></td></tr><tr><td colspan='2' bgcolor='#0B5040'><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2' color='white'><b>&nbsp;Monter son skill poterie</b></font></td></tr><tr><td width ='10'>&nbsp;</td><td><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>&nbsp;<br>
La poterie se fait en 2 étapes : faire l'objet sur le tour (wheel) et le
cuire dans le four (Kine). On trouve les deux à la banque de Thurgadin. 
Pour s'entraîner, seul le tour est utile : les objets fabriqués ne valent rien.
Petit détail important : sur le tour, il faut TOUJOURS ajouter une flasque
d'eau, sinon ça ne marche pas. Il faut de l'eau achetée au marchand : l'eau
foragée ne marche pas.
<br>&nbsp;<br>
Il faut achter le livre au marchand le plus à gauche dans la banque. Il vend
aussi les blocks de glaise nécessaires. La marchande juste à côté de lui
vend les trucs pour faire des bols. Le livre contient les recettes
nécessaires. Ne pas prendre les Sheets qui ne servent que pour la cuisson.
Faire d'abord des petits bols (trivial à 122), puis des moyens (trivial à
142). Détruire les bols fabriqués au fur et à mesure (ils ne valent rien non cuit et les cuire
coûte le prix de vente).
<br>&nbsp;<br>

</font>&nbsp;<br></td></tr><tr><td colspan='2' bgcolor='#0B5040'><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2' color='white'><b>&nbsp;La potion de gate</b></font></td></tr><tr><td width ='10'>&nbsp;</td><td><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>&nbsp;<br>
Combiner sur le tour de potier :
<ul>
<li>1 small brick of velium (poids 7)
<li>3 crystalline silks (non stackées)
<li>2 glass shards (achetés au vendeur tout à gauche dans la banque) (non
stackees)
</ul>
<b>On obtient une unfired velium vial</b>
<br>&nbsp;<br>
Combiner dans le four :
<ul>
<li>Unfired velium vial
<li>HQ firing sheet (achetée au même vendeur)
</ul>
<b>On obtient une velium vial</b>
<br>&nbsp;<br>
Aller pres du temple dans la boutique du milieu (Frundle Frenkler)<br>
Lui dire "what velium vapors"<br>
Elle vous donne un velium purifier
<br>&nbsp;<br>
Combiner dans le velium purifier :
<ul>
<li>velium vial
<li>2 small pieces of velium (non stackées)
</ul>
Et le tour est joué....




</font>&nbsp;<br></td></tr></table>&nbsp;<br></font></td></tr></table>
</td></tr><tr><td>
<table width='680' border='0' cellspacing='0' cellpadding='0'>
<tr><td width='680' height='1'><img src='./img/commun/c01/carre50.gif' width='680' height='1' alt='' border='0'></td></tr>
<tr><td height='2'><img src='./img/commun/transparent.gif' height='2' alt='' border='0'></td></tr>
<tr>
<td width='680' align='left' valign='top'>
<img src='./img/commun/c01/carre50.gif' width='10' height='10' border='0' alt=''>
<img src='./img/commun/c01/carre60.gif' width='10' height='10' border='0' alt=''>
<img src='./img/commun/c01/carre70.gif' width='10' height='10' border='0' alt=''>
<img src='./img/commun/c01/carre80.gif' width='10' height='10' border='0' alt=''>
</td></tr>
</table>
</td></tr><tr><td align='center'>
<A target='_blank' href='http://www.eqloft.com/'><img src='./img/commun/hebergement.gif' width='122' height='31' border='0' alt=''></a></td></tr></table>

</body>
</html>
