<!-- WARNING!  DO NOT EDIT THIS FILE BY HAND OR USING AN HTML EDITOR! -->
<HTML>
<HEAD>
<TITLE>Contact Moderators</TITLE>
<SCRIPT LANGUAGE="JavaScript">
<!-- ;
function setStatus(msg) {
  window.status = msg;
  return true;
}
function initpage () {
  window.defaultStatus = ""
  if (document.userpass) {
    if (document.userpass.username) {
      document.userpass.username.value = readcookie("user")
    }
    if (document.userpass.passwd) {
      document.userpass.passwd.value = readcookie("rpwd")
    }
  }
}
function readcookie(name) {
  var i = 0; var lookfor = name + "="
  while (i < document.cookie.length) {
    var j = i + lookfor.length
    if (document.cookie.substring(i,j) == lookfor) {
      var endstr = document.cookie.indexOf(";", j)
      if (endstr == -1) {
        endstr = document.cookie.length
      }
      return unescape(document.cookie.substring(j, endstr))
    }
    i = document.cookie.indexOf(" ", i) + 1
    if (i == 0) {
      break
    }
  }
  return ""
}
// end hide -->
</SCRIPT>
</HEAD>
<BODY BGCOLOR="#ffffff" TEXT="#000000" LINK="#330099" VLINK="#333333" ALINK="#ff0000" BACKGROUND="" onLoad="initpage()">
<BASEFONT SIZE="3"><FONT FACE="Verdana,Arial,Helvetica">
<A NAME="">
<a name=MT>
<CENTER><FONT SIZE=+1><B>Contact Moderators</B></FONT></CENTER>
<HR>
<P>Moderators:<P><UL>
<LI><A HREF="mailto:tigguhr@bestweb.net">Tha Webdwarf</A></LI>
</UL><P>
<P>Please address general questions and concerns to <A HREF="mailto:tygguhr@axepeak.com">Tygguhr, Tha Webdwarf</A>.<P>
<HR><CENTER><BR>
<A HREF="javascript:history.back()">Back to previous page</A>
</CENTER>
</FONT>
<BR>
<BR>
</BODY>
</HTML>
