<!--
                 This page has been created by Renaissance IT
   Renaissance Internet Technologies Copyright (c) 1999 All Rights Reserved.
             for more info on our products, please visit :
                        http://www.renaissance.nl/

	This script has been written by Roy Boverhof <rboverhof@renaissance.nl>

        Pagename                : links1.html
        Last Updated    		: 03-16-2001
-->


<HTML>
<HEAD>
	<TITLE>the Seekers of Lore : General EQ Links</TITLE>
</HEAD>

<BODY BGCOLOR="#000000" TEXT="#000000" LINK="#000000" VLINK="#000000" ALINK="#000000">
<DIV ALIGN="CENTER">
<BR>
<script type="text/javascript"><!--
google_ad_client = "pub-0988179937943699";
google_ad_width = 468;
google_ad_height = 60;
google_ad_format = "468x60_as";
google_ad_channel ="7352298734";
google_page_url = document.location;
google_color_border = "FFFFFF";
google_color_bg = "00001F";
google_color_link = "FFFFFF";
google_color_url = "FFF000";
google_color_text = "0000FF";
//--></script>
<script type="text/javascript"
  src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
</script>
<BR>
<TABLE CELLSPACING = 0 CELLPADDING = 0 BORDER = 0>
<TR>
	<TD width="63"><IMG SRC = "graphics/topc000.jpg" WIDTH = 63 HEIGHT = 87></TD>
	<TD width="473"><IMG SRC = "graphics/topc001.jpg" WIDTH = 473 HEIGHT = 87></TD>
	<TD width="64"><IMG SRC = "graphics/topc002.jpg" WIDTH = 64 HEIGHT = 87></TD>
</TR>
<TR>
	<TD width="63"></TD>
	<TD BGCOLOR="#BEA279" width="460">
	<DIV ALIGN="CENTER">
	<A HREF="links.phtml"><IMG SRC="graphics/linkheader.jpg" WIDTH ="200" HEIGHT ="75" ALT="Back to Links Index" BORDER="0"></A>
	<TABLE WIDTH=440 ALIGN="center">
	<TR><TD></TD></TR>
	<TR>
		<TD align=center>
		<b><A HREF="http://www.mmorpg.com/gamelist.cfm/setView/overview/gameID/9" TARGET="_new">MMORPG.COM - EverQuest</A></b>
		</TD>
		<TD><FONT FACE="Verdana" SIZE="-2"><FONT FACE="Verdana" SIZE="-2" COLOR="#FF0000">New! - </FONT>Information About EQ and lots of other MMORPG's</FONT></TD>
	</TR>
	<TR>
		<TD align=center>
		<b><A HREF="http://www.onlinegamecommands.com/everquest/everquestguide.htm" TARGET="_new">Everquest Game Commands</A></b>
		</TD>
		<TD><FONT FACE="Verdana" SIZE="-2"><FONT FACE="Verdana" SIZE="-2" COLOR="#FF0000">New! - </FONT>Game Commands for online play.</FONT></TD>
	</TR>
	<TR>
		<TD align=center>
		<b><A HREF="http://www.everquestplatinum.net" TARGET="_new">EverQuest Platinum</A></b>
		</TD>
		<TD><FONT FACE="Verdana" SIZE="-2"><FONT FACE="Verdana" SIZE="-2" COLOR="#FF0000">New! - </FONT>EverQuest Platinum: A large site that covers all aspects of the game. (Recommended)</FONT></TD>
	</TR>
	<TR>
		<TD>
		<A HREF="http://www.everquest.com/hht/index.jsp" TARGET="_new"><IMG SRC="graphics/harpys_link.jpg" WIDTH ="220" HEIGHT ="75" BORDER="0"></A>
		</TD>
		<TD><FONT FACE="Verdana" SIZE="-2">Harpy's Head Tavern. Come to this entertaining site to learn more about the lore, history, people and players of EQ. Hosted by Sony.</FONT></TD>
	</TR>
	<TR>
		<TD>
		<A HREF="http://www.everquest.com/" TARGET="_new"><IMG SRC="graphics/everquest_link.jpg" WIDTH ="220" HEIGHT ="75" BORDER="0"></A>
		</TD>
		<TD><FONT FACE="Verdana" SIZE="-2">Sony's Official <I>EverQuest</I>™ Homepage</FONT></TD>
	</TR>
	<TR>
		<TD>
		<A HREF="http://www.verant.com/" TARGET="_new"><IMG SRC="graphics/verant_link.jpg" WIDTH ="220" HEIGHT ="75" BORDER="0"></A>
		</TD>
		<TD><FONT FACE="Verdana" SIZE="-2">Verant Interactive. Producers of EverQuest.</FONT></TD>
	</TR>
	<TR>
		<TD>
		<A HREF="http://eqvault.ign.com/" TARGET="_new"><IMG SRC="graphics/eqvault_link.jpg" WIDTH ="220" HEIGHT ="75" BORDER="0"></A>
		</TD>
		<TD><FONT FACE="Verdana" SIZE="-2">One of the oldest and most popular EQ sites on the net.</FONT></TD>
	</TR>
	<TR>
		<TD>
		<A HREF="http://everquest.allakhazam.com/" TARGET="_new"><IMG SRC="graphics/allakhazam_link.jpg" WIDTH ="220" HEIGHT ="75" BORDER="0"></A>
		</TD>
		<TD><FONT FACE="Verdana" SIZE="-2">The most complete and up to date information on EQ available! ***New URL***</FONT></TD>
	</TR>
	<TR>
		<TD>
		<A HREF="http://eq.stratics.com/" TARGET="_new"><IMG SRC="graphics/eqss_link.jpg" WIDTH ="220" HEIGHT ="75 BORDER="0"></A>
		</TD>
		<TD><FONT FACE="Verdana" SIZE="-2">EverQuest Stratics - another excellant site. Very well laid out and informative forums.</FONT></TD>
	</TR>
	<TR>
		<TD>
		<A HREF="http://www.gameznet.com/eq/index.shtml" TARGET="_new"><IMG SRC="graphics/eqlizer_link.jpg" WIDTH ="220" HEIGHT ="75" BORDER="0"></A>
		</TD>
		<TD><FONT FACE="Verdana" SIZE="-2">Quality information site with many higher level items and information.</FONT></TD>
	</TR>
	<TR>
		<TD>
		<A HREF="http://www.everlore.com/" TARGET="_new"><IMG SRC="graphics/everlore_link.jpg" WIDTH ="220" HEIGHT ="75" BORDER="0"></A>
		</TD>
		<TD><FONT FACE="Verdana" SIZE="-2">Another quality site with especially good spell information.</FONT></TD>
	</TR>
	<TR>
		<TD>
		<B><DIV ALIGN="center"><A HREF="http://www.angelfire.com/games3/EverTry/index.html" TARGET="_new">Uber Quest</A></DIV></B>
		</TD>
		<TD><FONT FACE="Verdana" SIZE="-2">General site with quest and item info.</FONT></TD>
	</TR>	

	<TR>
		<TD></TD>
		<TD><BR></TD>
	</TR>
	
	<TR>
		<TD>
		<B><DIV ALIGN="center"><A HREF="http://www.jibantik.com/" TARGET="_new">Jibantik</A></DIV></B>
		</TD>
		<TD><FONT FACE="Verdana" SIZE="-2"><FONT FACE="Verdana" SIZE="-2" COLOR="#FF0000">New! - </FONT>This is a handy EverQuest search engine</FONT></TD>
	</TR>		
	
	<TR>
		<TD></TD>
		<TD><BR></TD>
	</TR>	
	
	<TR>
		<TD>
		<A HREF="mailto:webmaster@loreseekers.com?subject=links"><IMG SRC="graphics/submit_link.jpg" WIDTH ="220" HEIGHT ="75" BORDER="0"></A>
		</TD>
		<TD><I>Do you know a quality EverQuest site? Email us your link!</I></TD>
	</TR>
	</TABLE>
	<TD width="64"></TD>
<TR>
	<TD><IMG SRC = "graphics/botc000.jpg" WIDTH = 63 HEIGHT = 87></TD>
	<TD><IMG SRC = "graphics/botc001.jpg" WIDTH = 473 HEIGHT = 87></TD>
	<TD><IMG SRC = "graphics/botc002.jpg" WIDTH = 64 HEIGHT = 87></TD>
</TR>
</TABLE>
<BR>
<a href="http://wetrack.it/guidefox/a/16/b/20/e/2" TARGET="_new"><img src="http://guidefox.com/resources/atn/135x48_ani_eq2_1.gif" border="0"></a><BR>
<BR>
</DIV>
</BODY>
</HTML>