#!/usr/local/bin/php

<br>
<b>Warning</b>:  Supplied argument is not a valid MySQL result resource in <b>/var/www/berthall.com/calendar/admin/deleteCalendar.phtml</b> on line <b>9</b><br>
<center><h2><font color='Red'>You are about to remove </font><font color='Black'></font> <font color='Red'>from the calendar!<br>ARE YOU SURE?</font></h2><br><br>
<FORM ACTION="deleteCalendarResponse.phtml" METHOD="POST">
<INPUT TYPE='hidden' NAME='Event_ID' VALUE=''><INPUT TYPE="submit" NAME="Submit" VALUE="DO IT!">
</FORM>

<FORM ACTION="/calendar/admin/" METHOD="POST">
<INPUT TYPE="submit" NAME="Submit" VALUE="Just Kidding">
</FORM>

            <!--  End  Body  -->
<CENTER>
<br><hr width='70%'><br><font face='Arial'>
| <a href="../index.phtml">View Calendar</a> |
 <a href="./admin.phtml">Admin Page</a> |
<br>
</font>
</CENTER>
</BODY>
</HTML>
