<!-- comment check: ok -->
<HTML>
<HEAD>
<TITLE>Welcome to Media and Games Online Network - MGON</TITLE>
<META name="description" content="Media and Games Online Network - MGON - The Gamers' Choice for pc game news, reviews, interviews, downloads, and communities.">
<META name="keywords" content="MGON, MGO, computer, game, games, pc, windows, news, review, reviews, preview, previews, interview, inerviews, article, articles, demo, demos, media, trailer, teaser, rpg, roleplay, roleplaying, action, fps, shooter, strategy, sim, simulation, god, rts, real time, racing, screenshot, screenshots, patch, patches, hardware, cheat, cheats, tip, tips, trick, tricks, hint, hints, walkthru, walkthrus, walkthroughs, walkthrough, faq, faqs, entertainment, fun, forum, forums, shop, buy, message board, irc, chat">
<META name="robots" content="index,follow">
<meta name="distribution" content="GLOBAL">
<meta name="rating" content="GENERAL">
<meta name="copyright" content="MGON International AB">
<meta name="Author" content="MGON">
<meta http-equiv="reply-to" content="admin@mgon.com">
<meta name="Language" content="en-us"> 
<script src="http://www.adready.net/clnt/network/mgon/AdPointer.js" language="javascript"></script><link rel="stylesheet" href="/newstyle.css" type="text/css">
<STYLE type="text/css">
<!--
-->
</STYLE>
<script language="JavaScript" type="text/javascript">
<!--
function go(where) {
  if(where != "void" && where!="") location.href = where;
}
wallPaperWindowsLength = 0;

function reply(tid,pid,cid,lang) {

  url = "/reply.phtml?tid=" + tid + "&pid=" + pid + "&id=" + cid + "&language=" + lang + '&ref=%2Fnews.phtml';
  ipwindow = open("","prewindow","scrollbars=yes,toolbar=no,height=400,width=400");
  ipwindow.location.href = url;
        
}

function rateit(id,vote) {
    if(vote != "") {
		document.rate.content_id.value = id;
		document.rate.vote.value = vote;
		document.rate.submit();
	}
}

function screenshot(cid,pid) {

  url = "/screenshot.phtml?cid=" + cid + "&pid=" + pid;
  ipwindow = open("","prewindow","scrollbars=yes,toolbar=no,height=630,width=710");
  ipwindow.location.href = url;
        
}

function relatedmedia(url) {

  ipwindow = open("","prewindow","scrollbars=yes,toolbar=no,height=300,width=300");
  ipwindow.location.href = url;
        
}
function MM_preloadImages() { //v3.0
  var d=document; if(d.images){ if(!d.MM_p) d.MM_p=new Array();
    var i,j=d.MM_p.length,a=MM_preloadImages.arguments; for(i=0; i<a.length; i++)
    if (a[i].indexOf("#")!=0){ d.MM_p[j]=new Image; d.MM_p[j++].src=a[i];}}
}
function MM_findObj(n, d) { //v4.0
  var p,i,x;  if(!d) d=document; if((p=n.indexOf("?"))>0&&parent.frames.length) {
    d=parent.frames[n.substring(p+1)].document; n=n.substring(0,p);}
  if(!(x=d[n])&&d.all) x=d.all[n]; for (i=0;!x&&i<d.forms.length;i++) x=d.forms[i][n];
  for(i=0;!x&&d.layers&&i<d.layers.length;i++) x=MM_findObj(n,d.layers[i].document);
  if(!x && document.getElementById) x=document.getElementById(n); return x;
}
function MM_swapImgRestore() { //v3.0
  var i,x,a=document.MM_sr; for(i=0;a&&i<a.length&&(x=a[i])&&x.oSrc;i++) x.src=x.oSrc;
}
function MM_swapImage() { //v3.0
  var i,j=0,x,a=MM_swapImage.arguments; document.MM_sr=new Array; for(i=0;i<(a.length-2);i+=3)
   if ((x=MM_findObj(a[i]))!=null){document.MM_sr[j++]=x; if(!x.oSrc) x.oSrc=x.src; x.src=a[i+2];}
}

function getWall(id,name) {
  url = "/getwall.phtml?thisid=" + id + "&thisname=" + name;

	ipwindow = open("","prewindow_"+wallPaperWindowsLength,"fullscreen=no,resizable=yes,scrollbars=yes,toolbar=yes,height=600,width=800");        
        ipwindow.location.href = url;
	wallPaperWindowsLength++;

}

function getFile(id,name) {
  url = "/common/getfile.phtml?thisid=" + id + "&thisname=" + name;
  ipwindow = open("","prewindow","scrollbars=no,toolbar=no,height=200,width=495");
  ipwindow.location.href = url;
}
function localDate(dateStr) {
  now = new Date();
  var ar1 = now.toString().split(" ");
  var addH = -100;
  var addM = -100;
  var gmt = new Array(new Array());
  gmt["PST"] = -8;
  gmt["MST"] = -7;
  gmt["CST"] = -6;
  gmt["EST"] = -5;
  gmt["UTC"] = 0;
  if(ar1[4].indexOf("+") != -1) {
    var gm = ar1[4].split("+");
    gm[2] = 0-gm[1].substr(0,2);
    addH = Number(gm[2]);
    gm[2] = 0-gm[1].substr(2,2);
    addM = Number(gm[2]);
  }
  if(ar1[4].indexOf("-") != -1) {
    var gm = ar1[4].split("-");
    gm[2] = gm[1].substr(0,2);
    addH = Number(gm[2]);
    gm[2] = gm[1].substr(2,2);
    addM = Number(gm[2]);
  }
  if(addH == -100) {
    addH = gmt[ar1[4]];
    addM = 0;
  }
  there = new Date(dateStr);
  nowP = Date.parse(there);
  if(addH > 0) nowP -= 3600000;
  nowP += Number(addH)*3600000;
  nowP += Number(addM)*60000;
  realD = new Date(nowP);
  real = realD.toLocaleString();
  //  document.write(real[0] + " " + real[1] + " " + real[2] + " " +real[3]);
  document.write(real);
}
//-->
</script>

 
</HEAD>

<body bgcolor="#000000" text="#EEEEEE" link="#FFFFFF" vlink="#FFFFFF" alink="#FFFFFF" background="/newimages/backgrounds/bluelines.gif" leftmargin="0" topmargin="0" marginwidth="0" marginheight="0" onLoad="MM_preloadImages('/newimages/misc/arrow_on.gif')">

<table width="772" border="0" align="center" cellpadding="1" cellspacing="0" bgcolor="#000000">

  <tr>

    <td align="center"><!-- Webserver: w13 --><!-- loginUrl: http://everquest.mgon.com/common/loginNew.phtml?ref=www.mgon.com&page=/news.phtml !--><!-- loginUrl: http://everquest.mgon.com/common/members.phtml?ref=www.mgon.com&page=/news.phtml !--><script language="JavaScript">
<!--
function MM_openBrWindow(theURL,winName,features) { //v2.0
  window.open(theURL,winName,features);  
}
function login() {
  window.open('http://everquest.mgon.com/common/loginNew.phtml?ref=www.mgon.com&page=/news.phtml', 'Login', 'width=250,height=250,scrollbars=yes'); 
}
function member() {
  window.open('http://everquest.mgon.com/common/members.phtml?ref=www.mgon.com&page=/news.phtml', 'Member', 'width=500,height=600,scrollbars=yes'); 
}
//-->
</script>
<!-- Place the following code where you want an ad to appear -->
<!-- VC active -->
<SCRIPT language="JavaScript" SRC="http://oz.valueclick.com/cycle?host=hs0208926&t=pop&size=medium">
</SCRIPT>
<!-- vc active -->

<table width="100%" border="0" cellspacing="0" cellpadding="0" background="/common/images/topplate/resize.gif">
  <tr> 
    <td> 
      <table width="488" border="0" cellspacing="0" cellpadding="0" background="/common/images/topplate/resize.gif">
				<tr> 
          <td><img src="/common/images/topplate/metalcorner.gif" width="5" height="20"></td>
				          <td><a href="javascript:login();"><img src="/common/images/topplate/memberlogin.gif" width="80" height="20" border="0"></a></td>					
			            <td><img src="/common/images/topplate/arrow.gif" width="10" height="20"></td>
          <td><img src="/common/images/topplate/metalcolumn.gif" width="3" height="20"></td>
          <td><a href="javascript:;" onClick="MM_openBrWindow('/common/sitemap.html','navigation','width=540,height=450')"><img src="/common/images/topplate/pc.gif" width="23" height="20" border="0"></a></td>
          <td><img src="/common/images/topplate/metalcolumn.gif" width="3" height="20"></td>
          <td><a href="javascript:;" onClick="MM_openBrWindow('/common/sitemap.html','navigation','width=540,height=450')"><img src="/common/images/topplate/action.gif" width="47" height="20" border="0"></a></td>
          <td><img src="/common/images/topplate/metalcolumn.gif" width="3" height="20"></td>
          <td><a href="javascript:;" onClick="MM_openBrWindow('/common/sitemap.html','navigation','width=540,height=450')"><img src="/common/images/topplate/roleplay.gif" width="62" height="20" border="0"></a></td>
          <td><img src="/common/images/topplate/metalcolumn.gif" width="3" height="20"></td>
          <td><a href="javascript:;" onClick="MM_openBrWindow('/common/sitemap.html','navigation','width=540,height=450')"><img src="/common/images/topplate/simulation.gif" width="70" height="20" border="0"></a></td>
          <td><img src="/common/images/topplate/metalcolumn.gif" width="3" height="20"></td>
          <td><a href="javascript:;" onClick="MM_openBrWindow('/common/sitemap.html','navigation','width=540,height=450')"><img src="/common/images/topplate/console.gif" width="56" height="20" border="0"></a></td>
          <td><img src="/common/images/topplate/metalcolumn.gif" width="3" height="20"></td>
          <td><a href="javascript:;" onClick="MM_openBrWindow('/common/sitemap.html','navigation','width=540,height=450')"><img src="/common/images/topplate/strategy.gif" width="64" height="20" border="0"></a></td>
          <td><img src="/common/images/topplate/metalcolumn.gif" width="3" height="20"></td>
          <td><a href="javascript:;" onClick="MM_openBrWindow('/common/sitemap.html','navigation','width=540,height=450')"><img src="/common/images/topplate/racing.gif" width="47" height="20" border="0"></a></td>
          <td><img src="/common/images/topplate/metalcolumn.gif" width="3" height="20"></td>
<td>
</td>
</tr>
      </table>
    </td>
    <td background="/common/images/topplate/resize.gif" width="100%"><img src="/common/images/topplate/resize.gif" width="100%" height="20"></td>
    <td>
      <table width="88" border="0" cellspacing="0" cellpadding="0" background="/common/images/topplate/resize.gif">
        <tr>
          <td><img src="/common/images/topplate/metalcolumn.gif" width="3" height="20"></td>
          <td><a href="javascript:;" onClick="MM_openBrWindow('/common/sitemap.html','navigation','width=540,height=450')"><img src="/common/images/topplate/mgonetwork.gif" width="82" height="20" border="0"></a></td>
          <td><img src="/common/images/topplate/metalcorner.gif" width="5" height="20"></td>
        </tr>
      </table>
    </td>
  </tr>
</table>
<table width="100%" border="0" cellspacing="0" cellpadding="0" bgcolor="#000000">
  <tr> 
    <td><img src="http://193.45.143.3:81/1_1pix.gif?1008305302" width="1" height="1" nosave></td>
  </tr>
</table>

<!-- ---------- Open AdBonus AdServ Code -------------- -->
<!--  popup per hour per unique user -->
<script language="JavaScript">
<!--
function setCookie(NameOfCookie, value, expirehours) {
var ExpireDate = new Date ();
ExpireDate.setTime(ExpireDate.getTime() + (expirehours * 3600 * 1000));
document.cookie = NameOfCookie + "=" + escape(value) +
((expirehours == null) ? "" : "; expires=" + ExpireDate.toGMTString()) +

"; path=/;" ;
}
if (document.cookie.indexOf('AdPopUpC11')==-1)
{
  setCookie('AdPopUpC11','yes',1);
 document.write('<'+'SCRIPT LANGUAGE="JavaScript" SRC="');
 document.write('http://adserv.adbonus.com/cgi-bin/track.cgi?');
 document.write('c=getmedia&pid=52769">'+'<'+'/SCRIPT>');

}
// -->
</script>
<script language="JavaScript">
window.focus();
</script>
<!-- ---------- End AdBonus AdServ Code -------------- --></td>

  </tr>

</table>

<table width="772" border="0" cellspacing="0" cellpadding="0" align="center">

  <tr> 

    <td>

<TABLE width="772" border="0" cellspacing="0" cellpadding="0">

  <TR> 

    <TD><IMG src="/newimages/top/topleft.gif" width="592" height="81" border="0" usemap="#Map"><MAP name="Map"><AREA shape="rect" coords="13,36,138,76" href="http://www.mgon.com" alt="MGON Home" title="MGON Home"></MAP></TD>

    <TD width="100%" background="/newimages/top/resize.gif"><IMG src="/newimages/top/resize.gif" width="1" height="81"></TD>

    <TD><IMG src="/newimages/top/topright.gif" width="157" height="81"></TD>

  </TR>

</TABLE>


<TABLE width="750" border="0" cellspacing="0" cellpadding="0" bgcolor="#000000">
	<TR> 
		<TD align="center" width="130"> 
			<TABLE width="100%" border="0" cellspacing="0" cellpadding="0">
				<TR> 
					<TD align="center" background="/images2/top/channelresize.gif"><OBJECT classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=4,0,2,0" width="120" height="60">
							<param name=movie value="http://www.mgon.com/flashmovies/mgochannel3.swf">
							<PARAM name=quality value=high>
							<PARAM name="menu" value="false">
							<embed src="http://www.mgon.com/flashmovies/mgochannel3.swf" quality=high pluginspage="http://www.macromedia.com/shockwave/download/index.cgi?P1_Prod_Version=ShockwaveFlash" 
type="application/x-shockwave-flash" menu="false" width="120" height="60">
							</EMBED> 
						</OBJECT></TD>
				</TR>
				<TR> 
					<TD><IMG src="/images/top/channelbottom.gif" width="130" height="13"></TD>
				</TR>
			</TABLE>
		</TD>
		
    <TD align="center" width="490" valign="top"> 
      <!--Ad 468x60-->      <span class="smalltext"><NOLAYER><IFRAME SRC="http://ad.se.doubleclick.net/adi/mgon.com/;sz=468x60;ord=1008305302?" bgcolor="#000000" width="468" height="60" frameborder="no" border="0" MARGINWIDTH="0" MARGINHEIGHT="0" SCROLLING="no"><A HREF="http://ad.se.doubleclick.net/jump/mgon.com/;abr=!ie;sz=468x60;ord=1008305302?"><IMG SRC="http://ad.se.doubleclick.net/ad/mgon.com/;abr=!ie;sz=468x60;ord=1008305302?" border="0" height="60" width="468"></A></IFRAME></NOLAYER><ILAYER id="layer3" visibility="hidden" width="468" height="60" align="center"></ILAYER></span><!--/Ad 468x60-->    </TD>
		
    <TD width="130" align="center" valign="top">
</TD>
	</TR>
</TABLE>
</td></tr></table>
 
<table width="772" border="0" cellspacing="0" cellpadding="0" align="center" background="/newimages/misc/50x50pix.gif">
  <tr>
    <td width="130" background="/newimages/resizes/leftnav.gif" valign="top"> 
      <img src="/newimages/columns/sitecontent.gif" width="130" height="24"><br> 
<table width="130" border="0" cellspacing="0" cellpadding="0" bgcolor="#000000" background="/newimages/misc/50x50pix.gif">
  <tr bgcolor="#000000"> 
    <td> 
      <table width="100%" border=0 cellpadding=0 cellspacing=1>
        <tr bgcolor="#18355C"> 
          <td style="border='1 #18355C'" onMouseOver="style.backgroundColor='#FFFFFF'; style.cursor='hand'; style.border='1 #18355C'" onMouseOut="style.backgroundColor='#719FC6'; style.border='1 #18355C';" height="21" bgcolor="#719FC6"> 
            <table width="100%" border="0" cellspacing="0" cellpadding="0">
              <tr> 
                <td class="Bolded"><img src="/newimages/misc/navarrow.gif" width="12" height="21"></td>
                <td bgcolor="#18355C" height="21" width="100%"><a href="/" class="bluelinks" style="margin:0;"> 
                  <div><img src="/newimages/misc/1pix.gif" width="5" height="1" border="0">Home</div>
                  </a></td>
              </tr>
            </table>
          </td>
        </tr>
        <tr bgcolor="#18355C"> 
          <td style="border='1 #18355C'" onMouseOver="style.backgroundColor='#FFFFFF'; style.cursor='hand'; style.border='1 #18355C'" onMouseOut="style.backgroundColor='#719FC6'; style.border='1 #18355C';" height="21" bgcolor="#719FC6"> 
            <table width="100%" border="0" cellspacing="0" cellpadding="0">
              <tr> 
                <td class="Bolded"><img src="/newimages/misc/navarrow.gif" width="12" height="21"></td>
                <td bgcolor="#18355C" height="21" width="100%"><a href="/news.phtml" class="bluelinks" style="margin:0;"> 
                  <div><img src="/newimages/misc/1pix.gif" width="5" height="1" border="0">News</div>
                  </a></td>
              </tr>
            </table>
          </td>
        </tr>
        <tr bgcolor="#18355C"> 
          <td style="border='1 #18355C'" onMouseOver="style.backgroundColor='#FFFFFF'; style.cursor='hand'; style.border='1 #18355C'" onMouseOut="style.backgroundColor='#719FC6'; style.border='1 #18355C';" height="21" bgcolor="#719FC6"> 
            <table width="100%" border="0" cellspacing="0" cellpadding="0">
              <tr> 
                <td class="Bolded"><img src="/newimages/misc/navarrow.gif" width="12" height="21"></td>
                <td bgcolor="#18355C" height="21" width="100%"><a href="/reviewindex.phtml" class="bluelinks" style="margin:0;"> 
                  <div><img src="/newimages/misc/1pix.gif" width="5" height="1" border="0">Reviews</div>
                  </a></td>
              </tr>
            </table>
          </td>
        </tr>
        <tr bgcolor="#18355C"> 
          <td style="border='1 #18355C'" onMouseOver="style.backgroundColor='#FFFFFF'; style.cursor='hand'; style.border='1 #18355C'" onMouseOut="style.backgroundColor='#719FC6'; style.border='1 #18355C';" height="21" bgcolor="#719FC6"> 
            <table width="100%" border="0" cellspacing="0" cellpadding="0">
              <tr> 
                <td class="Bolded"><img src="/newimages/misc/navarrow.gif" width="12" height="21"></td>
                <td bgcolor="#18355C" height="21" width="100%"><a href="/previewindex.phtml" class="bluelinks" style="margin:0;"> 
                  <div><img src="/newimages/misc/1pix.gif" width="5" height="1" border="0">Previews</div>
                  </a></td>
              </tr>
            </table>
          </td>
        </tr>
        <tr bgcolor="#18355C"> 
          <td style="border='1 #18355C'" onMouseOver="style.backgroundColor='#FFFFFF'; style.cursor='hand'; style.border='1 #18355C'" onMouseOut="style.backgroundColor='#719FC6'; style.border='1 #18355C';" height="21" bgcolor="#719FC6"> 
            <table width="100%" border="0" cellspacing="0" cellpadding="0">
              <tr> 
                <td class="Bolded"><img src="/newimages/misc/navarrow.gif" width="12" height="21"></td>
                <td bgcolor="#18355C" height="21" width="100%"><a href="/interviewindex.phtml" class="bluelinks" style="margin:0;"> 
                  <div><img src="/newimages/misc/1pix.gif" width="5" height="1" border="0">Interviews</div>
                  </a></td>
              </tr>
            </table>
          </td>
        </tr>
        <tr bgcolor="#18355C"> 
          <td style="border='1 #18355C'" onMouseOver="style.backgroundColor='#FFFFFF'; style.cursor='hand'; style.border='1 #18355C'" onMouseOut="style.backgroundColor='#719FC6'; style.border='1 #18355C';" height="21" bgcolor="#719FC6"> 
            <table width="100%" border="0" cellspacing="0" cellpadding="0">
              <tr> 
                <td class="Bolded"><img src="/newimages/misc/navarrow.gif" width="12" height="21"></td>
                <td bgcolor="#18355C" height="21" width="100%"><a href="/articleindex.phtml" class="bluelinks" style="margin:0;"> 
                  <div><img src="/newimages/misc/1pix.gif" width="5" height="1" border="0">Articles</div>
                  </a></td>
              </tr>
            </table>
          </td>
        </tr>
        <tr bgcolor="#18355C"> 
          <td style="border='1 #18355C'" onMouseOver="style.backgroundColor='#FFFFFF'; style.cursor='hand'; style.border='1 #18355C'" onMouseOut="style.backgroundColor='#719FC6'; style.border='1 #18355C';" height="21" bgcolor="#719FC6"> 
            <table width="100%" border="0" cellspacing="0" cellpadding="0">
              <tr> 
                <td class="Bolded"><img src="/newimages/misc/navarrow.gif" width="12" height="21"></td>
                <td bgcolor="#18355C" height="21" width="100%"><a href="/hardwareindex.phtml" class="bluelinks" style="margin:0;"> 
                  <div><img src="/newimages/misc/1pix.gif" width="5" height="1" border="0">Hardware</div>
                  </a></td>
              </tr>
            </table>
          </td>
        </tr>
        <tr bgcolor="#18355C"> 
          <td style="border='1 #18355C'" onMouseOver="style.backgroundColor='#FFFFFF'; style.cursor='hand'; style.border='1 #18355C'" onMouseOut="style.backgroundColor='#719FC6'; style.border='1 #18355C';" height="21" bgcolor="#719FC6"> 
            <table width="100%" border="0" cellspacing="0" cellpadding="0">
              <tr> 
                <td class="Bolded"><img src="/newimages/misc/navarrow.gif" width="12" height="21"></td>
                <td bgcolor="#18355C" height="21" width="100%"><a href="/fileindex.phtml" class="bluelinks" style="margin:0;"> 
                  <div><img src="/newimages/misc/1pix.gif" width="5" height="1" border="0">Downloads</div>
                  </a></td>
              </tr>
            </table>
          </td>
        </tr>
        <tr bgcolor="#18355C"> 
          <td style="border='1 #18355C'" onMouseOver="style.backgroundColor='#FFFFFF'; style.cursor='hand'; style.border='1 #18355C'" onMouseOut="style.backgroundColor='#719FC6'; style.border='1 #18355C';" height="21" bgcolor="#719FC6"> 
            <table width="100%" border="0" cellspacing="0" cellpadding="0">
              <tr> 
                <td class="Bolded"><img src="/newimages/misc/navarrow.gif" width="12" height="21"></td>
                <td bgcolor="#18355C" height="21" width="100%"><a href="http://www.mgoforum.com" class="bluelinks" style="margin:0;"> 
                  <div><img src="/newimages/misc/1pix.gif" width="5" height="1" border="0">MGOforums</div>
                  </a></td>
              </tr>
            </table>
          </td>
        </tr>
        <tr bgcolor="#18355C"> 
          <td style="border='1 #18355C'" onMouseOver="style.backgroundColor='#FFFFFF'; style.cursor='hand'; style.border='1 #18355C'" onMouseOut="style.backgroundColor='#719FC6'; style.border='1 #18355C';" height="21" bgcolor="#719FC6"> 
            <table width="100%" border="0" cellspacing="0" cellpadding="0">
              <tr> 
                <td class="Bolded"><img src="/newimages/misc/navarrow.gif" width="12" height="21"></td>
                <td bgcolor="#18355C" height="21" width="100%"><a href="http://www.mgoshop.com" class="bluelinks" style="margin:0;"> 
                  <div><img src="/newimages/misc/1pix.gif" width="5" height="1" border="0">MGOshop</div>
                  </a></td>
              </tr>
            </table>
          </td>
        </tr>
        <tr bgcolor="#18355C"> 
          <td style="border='1 #18355C'" onMouseOver="style.backgroundColor='#FFFFFF'; style.cursor='hand'; style.border='1 #18355C'" onMouseOut="style.backgroundColor='#719FC6'; style.border='1 #18355C';" height="21" bgcolor="#719FC6"> 
            <table width="100%" border="0" cellspacing="0" cellpadding="0">
              <tr> 
                <td class="Bolded"><img src="/newimages/misc/navarrow.gif" width="12" height="21"></td>
                <td bgcolor="#18355C" height="21" width="100%"><a href="/corporate/index.phtml" class="bluelinks" style="margin:0;"> 
                  <div><img src="/newimages/misc/1pix.gif" width="5" height="1" border="0">Corporate 
                    Info </div>
                  </a></td>
              </tr>
            </table>
          </td>
        </tr>
      </table>
    </td>
  </tr>
</table>
    </td>
    <TD width="642" valign="top" background="/newimages/backgrounds/middlecolumn_black_wide.gif">

  
      <TABLE width="100%" border="0" cellspacing="0" cellpadding="0" background="/images2/sections/resize.gif">
        <TR> 
          <TD><IMG src="/images2/misc/1pixblack.gif" width="1" height="63"></TD>
          <TD width="100%" valign="bottom"> 
            <TABLE width="100%" border="0" cellspacing="0" cellpadding="0" background="/images2/misc/50x50pix.gif">
              <TR> 
                <TD height="28"><SPAN class="Bolded"><IMG src="/images2/misc/1pix.gif" width="11" height="1">Page:</SPAN> 
									<SPAN class="bluebolded"> &nbsp;1&nbsp;of&nbsp;173</SPAN></TD>
              </TR>
            </TABLE>
          </TD>
          <TD align="right"><IMG src="/newimages/sections/newsarchive.gif" width="275" height="63"></TD>
        </TR>
      </TABLE>
      <TABLE width="100%" border="0" cellspacing="0" cellpadding="0">
				<TR> 
					
          <TD valign="top" width="100%" align="center"> 
            <table width="100%" border="0" cellspacing="0" cellpadding="0" background="/newimages/titles/lowresize.gif">
              <tr> 
                <td width="100%"><img src="/newimages/titles/archive.gif" width="130" height="24"></td>
                <td><img src="/newimages/titles/lowrightcorner.gif" width="6" height="24"></td>
              </tr>
            </table>
            <TABLE width="100%" border="0" cellspacing="1" cellpadding="0">
							<FORM method="post" action="/news.phtml">
								<TR> 
									<TD height="40"><IMG src="/images2/misc/1pix.gif" width="10" height="8"></TD>
									<TD height="40" width="100%" nowrap><SPAN class="Bolded"><SPAN class="bluebolded">Search 
										News:&nbsp;</SPAN></SPAN>&nbsp; 
										<INPUT type="text" name="search" class="formbody" size="14" maxlength="50" value="">
										&nbsp; 
										<SELECT name="rel_category" class="formbody">
											<option selected value="0">All</option>
<option  value="1">Action</option>
<option  value="15">Adventure</option>
<option  value="20">eSports in the Press</option>
<option  value="3">Hardware</option>
<option  value="18">News</option>
<option  value="16">Other</option>
<option  value="14">Peripherals</option>
<option  value="19">Press Release</option>
<option  value="17">Puzzle</option>
<option  value="12">Racing</option>
<option  value="11">RPG</option>
<option  value="2">Simulation</option>
<option  value="4">Software</option>
<option  value="8">Sport</option>
<option  value="9">Strategy</option>
 
										</SELECT>
										&nbsp; &nbsp; 
										<INPUT type="image" border="0" name="imageField2" src="/images2/buttons/search_go.gif" width="24" height="22" align="top">
									</TD>
									<TD height="40" class="Bolded" align="right" nowrap> <!--Offset: 0 -->
1&nbsp;|&nbsp;<a href="?page=1&search=&cnt=172&rel_category=&sortby=">2</a>&nbsp;|&nbsp;<a href="?page=2&search=&cnt=172&rel_category=&sortby=">3</a>&nbsp;|&nbsp;<a href="?page=3&search=&cnt=172&rel_category=&sortby=">4</a>&nbsp;|&nbsp;<a href="?page=4&search=&cnt=172&rel_category=&sortby=">5</a>&nbsp;|&nbsp;<a href="?page=5&search=&cnt=172&rel_category=&sortby=">6</a>&nbsp;|&nbsp;<a href="?page=6&search=&cnt=172&rel_category=&sortby=">7</a>&nbsp;|&nbsp;<a href="?page=10&search=&cnt=172&rel_category=&sortby=">&gt;&gt;</a>
 &nbsp;&nbsp; <IMG src="/images2/misc/1pix.gif" width="10" height="1"></TD>
								</TR>
							</FORM>
						</TABLE>
							
<TABLE width="100%" border="0" cellspacing="0" cellpadding="0">
<TR>
<TD nowrap class="Bluebolded" background="/images2/buttons/resize.gif" height="25"><IMG src="/images2/misc/1pix.gif" width="11" height="1">Friday, December 14</TD>
<TD width="100%" background="/images2/buttons/resize.gif" height="25" align="right" nowrap><A href="mailto:news@mgon.com">Report news</A>&nbsp;&nbsp;|&nbsp;&nbsp;<A href="/news.phtml">Archive</A>&nbsp;&nbsp;|&nbsp;&nbsp;<A href="#top">Top</A>&nbsp;&nbsp;&nbsp;</TD>
</TR>
</TABLE><TABLE width="100%" border="0" cellspacing="0" cellpadding="11"><TR><TD width="100%"><P><SPAN class="Headline">Buzz Monkey Unveiled</SPAN> 
<TABLE width="100%" border="0" cellspacing="1" cellpadding="0">
<TR bgcolor="#335F5F"> 
<TD colspan="2" nowrap><IMG src="/images2/misc/1pix.gif" width="1" height="1"></TD>
</TR>
<TR>
<TD height="20" width="100%" nowrap><SPAN class="Bolded">Reported by: </SPAN><A href="javascript:Profile=open('/common/showprofile.phtml?id=', 'Profile','width=480,height=480,scrollbars=no,toolbar=no');Profile.focus();" >Mike</A>&nbsp;&nbsp;|&nbsp;&nbsp;<SPAN class="Bolded">Source: </SPAN> </TD>
<TD align="right" bgcolor="#001F39" nowrap>&nbsp;&nbsp;<A href="/news.phtml?id=116140&language=en&action=comments">0 Comments</A> | <A href="/news.phtml?id=116140&language=en&action=comments#addcomment">Add</A>&nbsp;&nbsp;</TD>
</TR>
</TABLE>
<P><SPAN class="normal">Ex-Dynamix employees Randy Thompson, Stephen Cordon, Jon Milnes, and David Sandgathe have teamed up to form Buzz Monkey Software to develope games for the PC as well as next generation consoles.  These gentlemen have quite a bit of experience behind them.  They are responsible for some very well known products including the Incredible Machine series and the award-winning Betrayal at Krondor and the Tribes games.  <br />
<br />
<A TARGET="_blank" HREF="http://www.buzzmonkeysoftware.com">Visit the official Buzz Monkey website</A><BR><!--No link--></SPAN></TD></TR></TABLE>
<TABLE width="100%" border="0" cellspacing="0" cellpadding="0">
<TR>
<TD nowrap class="Bluebolded" background="/images2/buttons/resize.gif" height="25"><IMG src="/images2/misc/1pix.gif" width="11" height="1">Thursday, December 13</TD>
<TD width="100%" background="/images2/buttons/resize.gif" height="25" align="right" nowrap><A href="mailto:news@mgon.com">Report news</A>&nbsp;&nbsp;|&nbsp;&nbsp;<A href="/news.phtml">Archive</A>&nbsp;&nbsp;|&nbsp;&nbsp;<A href="#top">Top</A>&nbsp;&nbsp;&nbsp;</TD>
</TR>
</TABLE><TABLE width="100%" border="0" cellspacing="0" cellpadding="11"><TR><TD width="100%"><P><SPAN class="Headline">Wolfenstein Single Player Demo Tommorow</SPAN> 
<TABLE width="100%" border="0" cellspacing="1" cellpadding="0">
<TR bgcolor="#335F5F"> 
<TD colspan="2" nowrap><IMG src="/images2/misc/1pix.gif" width="1" height="1"></TD>
</TR>
<TR>
<TD height="20" width="100%" nowrap><SPAN class="Bolded">Reported by: </SPAN><A href="javascript:Profile=open('/common/showprofile.phtml?id=', 'Profile','width=480,height=480,scrollbars=no,toolbar=no');Profile.focus();" >Simon</A>&nbsp;&nbsp;|&nbsp;&nbsp;<SPAN class="Bolded">Source: </SPAN> </TD>
<TD align="right" bgcolor="#001F39" nowrap>&nbsp;&nbsp;<A href="/news.phtml?id=115993&language=en&action=comments">0 Comments</A> | <A href="/news.phtml?id=115993&language=en&action=comments#addcomment">Add</A>&nbsp;&nbsp;</TD>
</TR>
</TABLE>
<P><SPAN class="normal">Activision sends word that they will be releasing the RTCW Single Player demo sometime tommorow morning. MGON will have it mirrored as soon as it is released so check back here every so often. Also if you want to view more information about RTCW visit <a href="http://www.wolfensteincenter.com"<a>Wolfenstein Center</a><BR><!--No link--></SPAN></TD></TR></TABLE><TABLE width="100%" border="0" cellspacing="0" cellpadding="11"><TR><TD width="100%"><P><SPAN class="Headline">Top 10</SPAN> 
<TABLE width="100%" border="0" cellspacing="1" cellpadding="0">
<TR bgcolor="#335F5F"> 
<TD colspan="2" nowrap><IMG src="/images2/misc/1pix.gif" width="1" height="1"></TD>
</TR>
<TR>
<TD height="20" width="100%" nowrap><SPAN class="Bolded">Reported by: </SPAN><A href="javascript:Profile=open('/common/showprofile.phtml?id=', 'Profile','width=480,height=480,scrollbars=no,toolbar=no');Profile.focus();" >Mike</A>&nbsp;&nbsp;|&nbsp;&nbsp;<SPAN class="Bolded">Source: </SPAN> </TD>
<TD align="right" bgcolor="#001F39" nowrap>&nbsp;&nbsp;<A href="/news.phtml?id=115981&language=en&action=comments">0 Comments</A> | <A href="/news.phtml?id=115981&language=en&action=comments#addcomment">Add</A>&nbsp;&nbsp;</TD>
</TR>
</TABLE>
<P><SPAN class="normal">Christmas is just around the corner making NPD's top ten a battle ground for the various hot-commodities being squeezed out for the holiday push.  It seems the wrath of Harry Potter cannot be escaped.  He has clogged movie theatres and home PCs alike.<br />
<br />
1) Harry Potter & The Sorcerer's Stone; Electronic Arts<br />
2) The Sims: Hot Date Expansion Pack; Electronic Arts <br />
3) The Sims; Electronic Arts <br />
4) Backyard Basketball; Infogrames Entertainment <br />
5) Survivor: The Interactive Game; Infogrames Entertainment <br />
6) MP Roller Coaster Tycoon; Infogrames Entertainment <br />
7) Return To Castle Wolfenstein; Activision <br />
8) MS Zoo Tycoon; Microsoft<br />
9) MP Civilization 3; Infogrames Entertainment <br />
10) Backyard Football 2002; Infogrames Entertainment<br />
  <BR><!--No link--></SPAN></TD></TR></TABLE><TABLE width="100%" border="0" cellspacing="0" cellpadding="11"><TR><TD width="100%"><P><SPAN class="Headline">New Warcraft 3 screen posted</SPAN> 
<TABLE width="100%" border="0" cellspacing="1" cellpadding="0">
<TR bgcolor="#335F5F"> 
<TD colspan="2" nowrap><IMG src="/images2/misc/1pix.gif" width="1" height="1"></TD>
</TR>
<TR>
<TD height="20" width="100%" nowrap><SPAN class="Bolded">Reported by: </SPAN><A href="javascript:Profile=open('/common/showprofile.phtml?id=', 'Profile','width=480,height=480,scrollbars=no,toolbar=no');Profile.focus();" >Rogey</A>&nbsp;&nbsp;|&nbsp;&nbsp;<SPAN class="Bolded">Source: </SPAN> </TD>
<TD align="right" bgcolor="#001F39" nowrap>&nbsp;&nbsp;<A href="/news.phtml?id=115982&language=en&action=comments">0 Comments</A> | <A href="/news.phtml?id=115982&language=en&action=comments#addcomment">Add</A>&nbsp;&nbsp;</TD>
</TR>
</TABLE>
<P><SPAN class="normal">There’s a new Warcraft 3 screenshot kicking around the Blizzard website at the moment and so we’ve grabbed it and posted it here on MGON.com for you to have a look at.  Also stop by at MGON’s <A TARGET="_blank" HREF="http://www.warcraftcenter.com/">Warcraft Center</A> if you’re after more Warcraft stuff.  Click below to see this screen.<BR><P>[&nbsp;<a href="/news.phtml?id=115982&language=en">Read More...</a>&nbsp;]</SPAN></TD></TR></TABLE><TABLE width="100%" border="0" cellspacing="0" cellpadding="11"><TR><TD width="100%"><P><SPAN class="Headline">A jolly free Christmas game</SPAN> 
<TABLE width="100%" border="0" cellspacing="1" cellpadding="0">
<TR bgcolor="#335F5F"> 
<TD colspan="2" nowrap><IMG src="/images2/misc/1pix.gif" width="1" height="1"></TD>
</TR>
<TR>
<TD height="20" width="100%" nowrap><SPAN class="Bolded">Reported by: </SPAN><A href="javascript:Profile=open('/common/showprofile.phtml?id=', 'Profile','width=480,height=480,scrollbars=no,toolbar=no');Profile.focus();" >Rogey</A>&nbsp;&nbsp;|&nbsp;&nbsp;<SPAN class="Bolded">Source: </SPAN> </TD>
<TD align="right" bgcolor="#001F39" nowrap>&nbsp;&nbsp;<A href="/news.phtml?id=115949&language=en&action=comments">0 Comments</A> | <A href="/news.phtml?id=115949&language=en&action=comments#addcomment">Add</A>&nbsp;&nbsp;</TD>
</TR>
</TABLE>
<P><SPAN class="normal">Ho, Ho, Ho and so forth.  We’re a jolly bunch of gamers here at MGON and to get into the spirit of the season we’ve found a fun little Christmas game for you to download and play for free.  It’s called Elves Inc. and it sees you firing wrapping paper at gifts that need to be wrapped.  There are even two player modes to try!  Click <A TARGET="_blank" HREF="http://www.stardock.com/products/elves/">here</A> to go to the Stardock site to have a look.  We’ve posted a few screens below too.<BR><P>[&nbsp;<a href="/news.phtml?id=115949&language=en">Read More...</a>&nbsp;]</SPAN></TD></TR></TABLE>
<TABLE width="100%" border="0" cellspacing="0" cellpadding="0">
<TR>
<TD nowrap class="Bluebolded" background="/images2/buttons/resize.gif" height="25"><IMG src="/images2/misc/1pix.gif" width="11" height="1">Wednesday, December 12</TD>
<TD width="100%" background="/images2/buttons/resize.gif" height="25" align="right" nowrap><A href="mailto:news@mgon.com">Report news</A>&nbsp;&nbsp;|&nbsp;&nbsp;<A href="/news.phtml">Archive</A>&nbsp;&nbsp;|&nbsp;&nbsp;<A href="#top">Top</A>&nbsp;&nbsp;&nbsp;</TD>
</TR>
</TABLE><TABLE width="100%" border="0" cellspacing="0" cellpadding="11"><TR><TD width="100%"><P><SPAN class="Headline">New P O W screens</SPAN> 
<TABLE width="100%" border="0" cellspacing="1" cellpadding="0">
<TR bgcolor="#335F5F"> 
<TD colspan="2" nowrap><IMG src="/images2/misc/1pix.gif" width="1" height="1"></TD>
</TR>
<TR>
<TD height="20" width="100%" nowrap><SPAN class="Bolded">Reported by: </SPAN><A href="javascript:Profile=open('/common/showprofile.phtml?id=', 'Profile','width=480,height=480,scrollbars=no,toolbar=no');Profile.focus();" >Rogey</A>&nbsp;&nbsp;|&nbsp;&nbsp;<SPAN class="Bolded">Source: </SPAN> </TD>
<TD align="right" bgcolor="#001F39" nowrap>&nbsp;&nbsp;<A href="/news.phtml?id=115948&language=en&action=comments">0 Comments</A> | <A href="/news.phtml?id=115948&language=en&action=comments#addcomment">Add</A>&nbsp;&nbsp;</TD>
</TR>
</TABLE>
<P><SPAN class="normal">Codemasters have released a new set of screenshots from the upcoming PC game Prisoner of War.  POW is being developed by the lads at Wide Games and will be ready for release around mid next year. In the meantime you can read the <A TARGET="_blank" HREF="http://www.mgon.com/previews.phtml?id=93117&language=en">MGON preview</A> of the game, or click below to see the screens.<BR><P>[&nbsp;<a href="/news.phtml?id=115948&language=en">Read More...</a>&nbsp;]</SPAN></TD></TR></TABLE><TABLE width="100%" border="0" cellspacing="0" cellpadding="11"><TR><TD width="100%"><P><SPAN class="Headline">GameWallpapers.com update</SPAN> 
<TABLE width="100%" border="0" cellspacing="1" cellpadding="0">
<TR bgcolor="#335F5F"> 
<TD colspan="2" nowrap><IMG src="/images2/misc/1pix.gif" width="1" height="1"></TD>
</TR>
<TR>
<TD height="20" width="100%" nowrap><SPAN class="Bolded">Reported by: </SPAN><A href="javascript:Profile=open('/common/showprofile.phtml?id=', 'Profile','width=480,height=480,scrollbars=no,toolbar=no');Profile.focus();" >Rogey</A>&nbsp;&nbsp;|&nbsp;&nbsp;<SPAN class="Bolded">Source: </SPAN> </TD>
<TD align="right" bgcolor="#001F39" nowrap>&nbsp;&nbsp;<A href="/news.phtml?id=115947&language=en&action=comments">0 Comments</A> | <A href="/news.phtml?id=115947&language=en&action=comments#addcomment">Add</A>&nbsp;&nbsp;</TD>
</TR>
</TABLE>
<P><SPAN class="normal">Nico from Gamewallpapers.com has had a busy week and the result is several new PC wallpapers for you to install on your PC.  There are new <A TARGET="_blank" HREF="http://www.gamewallpapers.com/wallpapers.phtml?rel_product=514">Comanche 4</A>, <A TARGET="_blank" HREF="http://www.gamewallpapers.com/wallpapers.phtml?rel_product=497">Grand Theft Auto 3</A> and <A TARGET="_blank" HREF="http://www.gamewallpapers.com/wallpapers.phtml?rel_product=635">Tropico: Paradise Island</A> wallpapers, which are ready to download right now.<BR><!--No link--></SPAN></TD></TR></TABLE><TABLE width="100%" border="0" cellspacing="0" cellpadding="11"><TR><TD width="100%"><P><SPAN class="Headline">EA launches V8 Challenge website</SPAN> 
<TABLE width="100%" border="0" cellspacing="1" cellpadding="0">
<TR bgcolor="#335F5F"> 
<TD colspan="2" nowrap><IMG src="/images2/misc/1pix.gif" width="1" height="1"></TD>
</TR>
<TR>
<TD height="20" width="100%" nowrap><SPAN class="Bolded">Reported by: </SPAN><A href="javascript:Profile=open('/common/showprofile.phtml?id=', 'Profile','width=480,height=480,scrollbars=no,toolbar=no');Profile.focus();" >Rogey</A>&nbsp;&nbsp;|&nbsp;&nbsp;<SPAN class="Bolded">Source: </SPAN> </TD>
<TD align="right" bgcolor="#001F39" nowrap>&nbsp;&nbsp;<A href="/news.phtml?id=115945&language=en&action=comments">0 Comments</A> | <A href="/news.phtml?id=115945&language=en&action=comments#addcomment">Add</A>&nbsp;&nbsp;</TD>
</TR>
</TABLE>
<P><SPAN class="normal">EA Sports has revved up a <A TARGET="_blank" HREF="www.v8challenge.com">website</A> to show off their upcoming racing game called V8 Challenge, which is based on the Aussie 5 liter V8 touring car racing.  The site has plenty of pictures from the racetarcks and some behind the scenes looks at how the game is being made. You can also read the MGON <A TARGET="_blank" HREF="http://www.mgon.com/previews.phtml?id=105924&language=en">preview</A> of V8 Challenge and soon we’ll have an interview with the game’s developers.  Click below to see a few of the latest screenshots from the game too, which were taken from the Bathurst track.<BR><P>[&nbsp;<a href="/news.phtml?id=115945&language=en">Read More...</a>&nbsp;]</SPAN></TD></TR></TABLE><TABLE width="100%" border="0" cellspacing="0" cellpadding="11"><TR><TD width="100%"><P><SPAN class="Headline">eSports Beta Competition Winners</SPAN> 
<TABLE width="100%" border="0" cellspacing="1" cellpadding="0">
<TR bgcolor="#335F5F"> 
<TD colspan="2" nowrap><IMG src="/images2/misc/1pix.gif" width="1" height="1"></TD>
</TR>
<TR>
<TD height="20" width="100%" nowrap><SPAN class="Bolded">Reported by: </SPAN><A href="javascript:Profile=open('/common/showprofile.phtml?id=', 'Profile','width=480,height=480,scrollbars=no,toolbar=no');Profile.focus();" >Corven</A>&nbsp;&nbsp;|&nbsp;&nbsp;<SPAN class="Bolded">Source: </SPAN> </TD>
<TD align="right" bgcolor="#001F39" nowrap>&nbsp;&nbsp;<A href="/news.phtml?id=115870&language=en&action=comments">0 Comments</A> | <A href="/news.phtml?id=115870&language=en&action=comments#addcomment">Add</A>&nbsp;&nbsp;</TD>
</TR>
</TABLE>
<P><SPAN class="normal">The <A TARGET="_blank" HREF="http://www.esports-europe.com">eSports</A> Beta Competition has now ended and the winners have been announced, congratz to the following:<br />
<br />
<li><b>Best Player - All*Nirvana</b><br />
He won a Hercules 3D Prophet III 500 Titanium graphics card.<br />
<li><b>Most Matches - cky</b><br />
He won a Hercules 3D Prophet III 200 Titanium graphics card.<br />
<li><b>Random Winner - KiLLerRoY</b><br />
He won a Hercules 3D Prophet III 200 Titanium graphics card.<br />
<br />
But the fun isn't over yet folks, we're announcing the big final <A TARGET="_blank" HREF="http://www.esports-europe.com">eSports</A> "Clash of the Titans". This event will launch on Friday the 14th and will have the 10 best players from the beta and 6 invited star players playing for a really nice prize! We'll have the recoded demos for your viewing pleasure posted to <A TARGET="_blank" HREF="http://www.q3center.com">Q3Center</A> so you can watch the event.<BR><!--No link--></SPAN></TD></TR></TABLE><TABLE width="100%" border="0" cellspacing="0" cellpadding="11"><TR><TD width="100%"><P><SPAN class="Headline">Doom Center update</SPAN> 
<TABLE width="100%" border="0" cellspacing="1" cellpadding="0">
<TR bgcolor="#335F5F"> 
<TD colspan="2" nowrap><IMG src="/images2/misc/1pix.gif" width="1" height="1"></TD>
</TR>
<TR>
<TD height="20" width="100%" nowrap><SPAN class="Bolded">Reported by: </SPAN><A href="javascript:Profile=open('/common/showprofile.phtml?id=', 'Profile','width=480,height=480,scrollbars=no,toolbar=no');Profile.focus();" >Rogey</A>&nbsp;&nbsp;|&nbsp;&nbsp;<SPAN class="Bolded">Source: </SPAN> </TD>
<TD align="right" bgcolor="#001F39" nowrap>&nbsp;&nbsp;<A href="/news.phtml?id=115857&language=en&action=comments">0 Comments</A> | <A href="/news.phtml?id=115857&language=en&action=comments#addcomment">Add</A>&nbsp;&nbsp;</TD>
</TR>
</TABLE>
<P><SPAN class="normal">Big Dog from Doom Center has sent MGON another site update, which you'll find just below.<br />
<br />
We have <A TARGET="_blank" HREF="http://www.doomcenter.com/features/features.phtml?id=115740&language=en">part 4</A> of Rick Clark's Doom/Wolfenstein story, Tomorrow's Yesterday, online at Doom Center. It's a great read, and as always, links to the previous parts of the story are provided.<BR><!--No link--></SPAN></TD></TR></TABLE><TABLE width="100%" border="0" cellspacing="0" cellpadding="11"><TR><TD width="100%"><P><SPAN class="Headline">Aliens Vs Predator 2 Patch</SPAN> 
<TABLE width="100%" border="0" cellspacing="1" cellpadding="0">
<TR bgcolor="#335F5F"> 
<TD colspan="2" nowrap><IMG src="/images2/misc/1pix.gif" width="1" height="1"></TD>
</TR>
<TR>
<TD height="20" width="100%" nowrap><SPAN class="Bolded">Reported by: </SPAN><A href="javascript:Profile=open('/common/showprofile.phtml?id=', 'Profile','width=480,height=480,scrollbars=no,toolbar=no');Profile.focus();" >Simon</A>&nbsp;&nbsp;|&nbsp;&nbsp;<SPAN class="Bolded">Source: </SPAN> </TD>
<TD align="right" bgcolor="#001F39" nowrap>&nbsp;&nbsp;<A href="/news.phtml?id=115856&language=en&action=comments">0 Comments</A> | <A href="/news.phtml?id=115856&language=en&action=comments#addcomment">Add</A>&nbsp;&nbsp;</TD>
</TR>
</TABLE>
<P><SPAN class="normal">Sierra and Monolith have released yet another patch for this popular first person game. The patch at this time has no details as to what is changed or fixed and is only downloadable via the in game Sierra client.<BR><!--No link--></SPAN></TD></TR></TABLE><TABLE width="100%" border="0" cellspacing="0" cellpadding="11"><TR><TD width="100%"><P><SPAN class="Headline">Console Update</SPAN> 
<TABLE width="100%" border="0" cellspacing="1" cellpadding="0">
<TR bgcolor="#335F5F"> 
<TD colspan="2" nowrap><IMG src="/images2/misc/1pix.gif" width="1" height="1"></TD>
</TR>
<TR>
<TD height="20" width="100%" nowrap><SPAN class="Bolded">Reported by: </SPAN><A href="javascript:Profile=open('/common/showprofile.phtml?id=', 'Profile','width=480,height=480,scrollbars=no,toolbar=no');Profile.focus();" >Warren</A>&nbsp;&nbsp;|&nbsp;&nbsp;<SPAN class="Bolded">Source: </SPAN> </TD>
<TD align="right" bgcolor="#001F39" nowrap>&nbsp;&nbsp;<A href="/news.phtml?id=115844&language=en&action=comments">0 Comments</A> | <A href="/news.phtml?id=115844&language=en&action=comments#addcomment">Add</A>&nbsp;&nbsp;</TD>
</TR>
</TABLE>
<P><SPAN class="normal">MGON's console channels have some great new media and information for those of you that are tired of sitting at a keyboard and monitor all day.  Want to see some exclusive Timesplitters 2 media at <A TARGET="_blank" HREF="http://www.playstationcenter.com">PlayStationCenter</A>?  How about the lowdown on the first Resident Evil title for the Gamecube at <A TARGET="_blank" HREF="http://www.nintendocenter.com">NintendoCenter</A>?  Whatever your console requirements, MGON has it covered.<BR><!--No link--></SPAN></TD></TR></TABLE>  
						</TABLE>
					</TD>
				</TR>
			</TABLE>
			<P> 					
				</table></td>

        </tr>

      </table>

     
		

 
<table width="772" border="0" cellspacing="0" cellpadding="0" align="center">
  <tr>
    <td><img src="/newimages/bottom/copyright.gif" width="621" height="30" border="0" usemap="#Map2"></td>
    <td><a href="/"><img src="/newimages/bottom/home.gif" width="75" height="30" border="0"></a></td>
    <td><a href="#top"><img src="/newimages/bottom/top.gif" width="76" height="30" border="0"></a></td>
  </tr>
</table>
<TABLE width="772" border="0" cellspacing="0" cellpadding="0" height="90" background="/images2/misc/50x50pix.gif" align="center">
  <TR bgcolor="#000000" align="center"> 
    <TD class="smalltext"><SCRIPT language="JavaScript"
src="http://adtegrity.spinbox.net/?DC=Mgon+Bottom&JS=Y&TARGET=_new">
</SCRIPT><NOSCRIPT><A href="http://adtegrity.spinbox.net/?SHT=Mgon+Bottom" target="_new"
height="468" width="60"><IMG src="http://adtegrity.spinbox.net/?SIT=Mgon+Bottom" border="0"></A></NOSCRIPT></TD>
  </TR>
</TABLE>
<map name="Map">
  <area shape="rect" coords="387,7,495,25" href="/privacy.phtml">
</map>
<map name="Map2">
  <area shape="rect" coords="384,4,496,26" href="/privacy">
</map>

 

<!--Bottom Layer-->
      <LAYER SRC="http://ad.se.doubleclick.net/adl/mgon.com/;sz=140x350;ord=1008305302?" bgcolor="#000000" width="140" height="350" visibility="hidden" onLoad="moveToAbsolute(layer1.pageX,layer1.pageY);clip.height=350;clip.width=140; visibility='show';"></LAYER>      <LAYER SRC="http://ad.se.doubleclick.net/adl/mgon.com/;sz=140x350;ord=1008305302?" bgcolor="#000000" width="140" height="350" visibility="hidden" onLoad="moveToAbsolute(layer2.pageX,layer2.pageY);clip.height=350;clip.width=140; visibility='show';"></LAYER>      <LAYER SRC="http://ad.se.doubleclick.net/adl/mgon.com/;sz=468x60;ord=1008305302?" bgcolor="#000000" width="468" height="60" visibility="hidden" onLoad="moveToAbsolute(layer3.pageX,layer3.pageY);clip.height=60;clip.width=468; visibility='show';"></LAYER><!--End Bottom Layer-->
</BODY>

</HTML>


