var MENU_ITEMS = [
	['Home', '/index.htm', null,
		['Credits', ['/credits.htm', '_self', 'Credits From the Webmaster to All the People Who Make This Site Possible']],
		['Memorial', ['/memorial.htm', '_self', 'Memorial to a Fallen Soldier']],
	],
	['Guild Forms', 'http://sofeq.sofguild.com/database/forms.htm', null,
		['Membership Application', ['/forms/newapp.htm', '_self', 'Sign up to become a member of the Soldiers of Fortune Guild']],
		['Member Update', ['http://forum.sofguild.com/login.php?Cat=', '_self', 'Members Update Your Personal Roster Information Here']],
		['Character Update', ['http://forum.sofguild.com/login.php?Cat=', '_self', 'Members Update Your Character Information Here']],
		['Delete Character', ['http://forum.sofguild.com/login.php?Cat=', '_self', 'Remove A Character From Your Record']],
		['Order Application', ['/forms/order_form.htm', '_self', 'Members Apply for an Order Here']],
	],
	['Guild Hall', null, null,
		['Guild Charter', ['/charter.htm', '_self', 'Read the Guild Charter']],
		['Guild History', ['/history.htm', '_self', 'Read the Guild History']],
		['Guild Organization', ['/organization.htm', '_self', 'Guild Rank Structure']],
		['High Council', ['/hc.htm', '_self', 'List of SoF High Council Members']],
	],
	['Library', null, null,
		['Strategy & Lore', ['/strategy.htm', '_self', 'Read Strategy and Tips for EverQuest Written by SoF Members']],
		['Zone Guides', ['/zone.htm', '_self', 'Read Zone Guides Written by SoF Members']],
	],
	['Tavern', null, null,
		['Allies', ['/allies.htm', '_self', 'Allies of SoF']],
		['Bards Corner', ['/bard.htm', '_self', 'Sonnets and Poetry Written by SoF Members']],
		['Members Gallery', ['/gallery.htm', '_self', 'Images Drawn by SoF Members']],
		['Tales of SoF', ['/tales.htm', '_self', 'Stories Written by SoF Members']],
		['Scenes of Norrath', ['/scenes.htm', '_self', 'Screenshots Taken by SoF Members']],
	],
	['E-Mail', null, null,
		['Check SoFmail', ['http://mail.sofguild.com', '_self', 'SoF Members Can Check Their Email Here']],
		['Email High Council', ['/email_hc.htm', '_self', 'Email the Entire SoF High Council']],
		['Email Webmaster', ['mailto:zack@sofguild.com', '_self', 'Email the SoF-EQ Webmaster']],
	],
	['Calendar', ['/calendar.htm', '_self', 'Check the SoF Raid Calendar for Upcoming Events']],
	['Forums', 'http://forum.sofguild.com/index.php', null],
];