<!--
                 This page has been created by Renaissance IT
   Renaissance Internet Technologies Copyright (c) 1999 All Rights Reserved.

             for more info on our products, please visit :
                        http://www.renaissance.nl/

	This script has been written by Roy Boverhof <rboverhof@renaissance.nl>
	
        Pagename                : oggok_zones.html
        Last Updated    		: 05-02-2000
-->

<HTML>
<HEAD>
	<TITLE>the Seekers of Lore : Oggok Region</TITLE>
</HEAD>

<BODY BGCOLOR="#000000" TEXT="#000000" LINK="#000000" VLINK="#000000" ALINK="#000000">
<DIV ALIGN="CENTER">
<BR>
<script type="text/javascript"><!--
google_ad_client = "pub-0988179937943699";
google_ad_width = 468;
google_ad_height = 60;
google_ad_format = "468x60_as";
google_ad_channel ="";
google_page_url = document.location;
google_color_border = "FFFFFF";
google_color_bg = "00001F";
google_color_link = "FFFFFF";
google_color_url = "FFF000";
google_color_text = "0000FF";
//--></script>
<script type="text/javascript"
  src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
</script><BR>	
<TABLE CELLSPACING = 0 CELLPADDING = 0 BORDER = 0>
<TR>
	<TD width="63"><IMG SRC = "graphics/topc000.jpg" WIDTH = 63 HEIGHT = 87></TD>
	<TD width="473"><IMG SRC = "graphics/topc001.jpg" WIDTH = 473 HEIGHT = 87></TD>
	<TD width="64"><IMG SRC = "graphics/topc002.jpg" WIDTH = 64 HEIGHT = 87></TD>
</TR>
	<TD width="63"></TD>
	<TD BGCOLOR="#BEA279" width="460">
	<DIV ALIGN="CENTER">
	<A HREF="maps.php3"><IMG SRC="graphics/atlasheader.jpg" WIDTH ="150" HEIGHT ="75" BORDER="0"></A>
	<TABLE WIDTH="460">
	<TR><TD>
	<CENTER>
<TABLE BORDER="0">
<TR>
<TD><BR><FONT COLOR="#FFFF00" SIZE="4" FACE="Ariel"><CENTER>Now choose a zone...</CENTER></FONT><BR></TD>
</TR>
<TR>
<TD>
<IMG SRC="graphics/oggok_zones.jpg" WIDTH=400 HEIGHT=300 BORDER=0 USEMAP="#oggok">
<MAP NAME="oggok">
<AREA SHAPE=RECT COORDS="10,153,54,172" HREF="map_search.php3?action=zone&add_zone=Infected%20Paw">
<AREA SHAPE=RECT COORDS="80,141,148,181" HREF="map_search.php3?action=zone&add_zone=South%20Karana">
<AREA SHAPE=RECT COORDS="239,130,320,157" HREF="map_search.php3?action=zone&add_zone=Oggok">
<AREA SHAPE=RECT COORDS="244,177,319,199" HREF="map_search.php3?action=zone&add_zone=Feerrott">
<AREA SHAPE=RECT COORDS="170,185,224,222" HREF="map_search.php3?action=zone&add_zone=Rathe%20Mountains">
<AREA SHAPE=RECT COORDS="78,211,166,249" HREF="map_search.php3?action=zone&add_zone=Lake%20Rathetear">
<AREA SHAPE=RECT COORDS="10,223,64,243" HREF="http://files.loreseekers.com/maps/ot_arena.jpg">
<AREA SHAPE=RECT COORDS="248,224,353,264" HREF="map_search.php3?action=zone&add_zone=Temple%20of%20Cazic-Thule">
<AREA SHAPE=POLY COORDS="189,57,214,57,202,37,189,57" HREF="qeynos_zones.phtml" ALT="To Qeynos Region">
<AREA SHAPE=POLY COORDS="345,199,345,172,364,186,345,199" HREF="grobb_zones.phtml" ALT="To Grobb Region">
</MAP>
</TD>
</TR>
</TABLE>
	</TD></TR>
	</TABLE>
	<TD width="64"></TD>
<TR>
	<TD><IMG SRC = "graphics/botc000.jpg" WIDTH = 63 HEIGHT = 87></TD>
	<TD><IMG SRC = "graphics/botc001.jpg" WIDTH = 473 HEIGHT = 87></TD>
	<TD><IMG SRC = "graphics/botc002.jpg" WIDTH = 64 HEIGHT = 87></TD>
</TR>
</TABLE>
<BR>
<IMG SRC="http://service.bfast.com/bfast/serve?bfmid=1375281&siteid=40292692&bfpage=pc" BORDER="0" WIDTH="1" HEIGHT="1" NOSAVE ><A HREF="http://service.bfast.com/bfast/click?bfmid=1375281&siteid=40292692&bfpage=pc" TARGET="_new"><IMG SRC="http://affiliate.gamestop.com/affIMG/pc_120x60.gif" BORDER="0" WIDTH="120" HEIGHT="60" ALT="PC Games at GameStop.com"></A>
<BR>
<BR>
</DIV>
</BODY>
</HTML>