<!--
                 This page has been created by Renaissance IT
   Renaissance Internet Technologies Copyright (c) 1999 All Rights Reserved.

             for more info on our products, please visit :
                        http://www.renaissance.nl/

	This script has been written by Roy Boverhof <rboverhof@renaissance.nl>
	
        Pagename                : faith.html
        Last Updated    		: 26-01-2000
-->

<HTML>
<HEAD>
	<TITLE>the Seekers of Lore : Faith</TITLE>
</HEAD>

<BODY BGCOLOR="#000000" TEXT="#000000" LINK="#000000" VLINK="#000000" ALINK="#000000">
<DIV ALIGN="CENTER">
<BR>
<!-- FGN Banner Code -->
<script language="JavaScript">
	<!-- Hide from old browsers
	var random = new Number(Math.floor(9999999 * Math.random())+1);

	// Modify to reflect site specifics
	page = "eqlore.com/";
	target = "@Top1,x02,x05,x08!Top1";

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript1.1" SRC="http://oascentral.cybereps.com/RealMedia/ads/adstream_jx.ads/' + page + 1 + random + target + '">');
	document.write('</SCR');
	document.write('IPT>');

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript">');
	document.write('_version=10; //-->');
	document.write('</SCR');
	document.write('IPT>');

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript1.1">');
	document.write('_version=11; //-->');
	document.write('</SCR');
	document.write('IPT>');

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript">');

	if (navigator.appVersion.indexOf('MSIE 3') != -1){
	document.write('<IFRAME MARGINWIDTH=0 MARGINHEIGHT=0 HSPACE=0 VSPACE=0 FRAMEBORDER=0 SCROLLING=no BORDERCOLOR="#000000" SRC="oascentral.cybereps.com/RealMedia/ads/adstream_sx.ads/' + page + random + target + '"></IFRAME>');
	  }
	else if (_version < 11) {
	document.write ('<A HREF="http://oascentral.cybereps.com/RealMedia/ads/click_nx.ads/' + page + random + target + '"><IMG SRC="http://oascentral.cybereps.com/RealMedia/ads/adstream_nx.ads/' + page + random + target + '"></a>');
	  }

	document.write('</SCR');
	document.write('IPT>');

	// End Hide -->
</script>
<!-- END FGN Banner Code --><BR>
<TABLE CELLSPACING = 0 CELLPADDING = 0 BORDER = 0>
<TR>
	<TD width="63"><IMG SRC = "../graphics/topc000.jpg" WIDTH = 63 HEIGHT = 87></TD>
	<TD width="473"><IMG SRC = "../graphics/topc001.jpg" WIDTH = 473 HEIGHT = 87></TD>
	<TD width="64"><IMG SRC = "../graphics/topc002.jpg" WIDTH = 64 HEIGHT = 87></TD>
</TR>
	<TD width="63"></TD>
	<TD BGCOLOR="#BEA279" width="460">
	<DIV ALIGN="CENTER">
	<TABLE>
	<TR>
	<TD>
		<FONT FACE="Verdana">
		<P><CENTER><B><FONT SIZE="+1">Faith</FONT></B></CENTER>
		<FONT SIZE="-1">
		May the light of Tunare shine upon you<BR>
		and make your journeys go so well<BR>
		Let the need for justice drive you<BR>
		and bring you success where others fail
		
		<P>Have faith in your fellow seekers<BR>
		always give them a helping hand<BR>
		for honor and glory are the foundations<BR>
		of this guild upon which we stand
		
		<P>Remember all our fallen comrades<BR>
		and their deeds live forever on<BR>
		Let their sacrifices live in our memories<BR>
		for in our minds they are never gone
		
		<P>During this time and this season<BR>
		I bid you joy with all i say<BR>
		I hope your family bring you joy<BR>
		and have a happy holiday<BR>
		</FONT>
		<BR>
		<B>Foladen Moonsong</B>, <FONT SIZE="-1">bard of the isles.</FONT>

		</FONT>
	</TD>
	</TR>
	</TABLE>

<TABLE>
<TR>
<TD><A HREF="http://www.loreseekers.com/tales.phtml"><IMG SRC="http://www.loreseekers.com/graphics/tales_return_link.jpg" WIDTH=200 HEIGHT=75 ALT="Read some other stories by our members!" BORDER="0"></A></TD>
</TR>
</TABLE>

	<TD width="64"></TD>
<TR>
	<TD><IMG SRC = "../graphics/botc000.jpg" WIDTH = 63 HEIGHT = 87></TD>
	<TD><IMG SRC = "../graphics/botc001.jpg" WIDTH = 473 HEIGHT = 87></TD>
	<TD><IMG SRC = "../graphics/botc002.jpg" WIDTH = 64 HEIGHT = 87></TD>
</TR>
</TABLE>
<BR>
<IMG SRC="http://service.bfast.com/bfast/serve?bfmid=1375281&siteid=40292692&bfpage=pc" BORDER="0" WIDTH="1" HEIGHT="1" NOSAVE ><A HREF="http://service.bfast.com/bfast/click?bfmid=1375281&siteid=40292692&bfpage=pc" TARGET="_new"><IMG SRC="http://affiliate.gamestop.com/affIMG/pc_120x60.gif" BORDER="0" WIDTH="120" HEIGHT="60" ALT="PC Games at GameStop.com"></A>
<BR>
<BR>
</DIV>
</BODY>
</HTML>

