<!-- WARNING!  DO NOT EDIT THIS FILE BY HAND OR USING AN HTML EDITOR! -->
<HTML>
<HEAD>
<TITLE>Profile Editor</TITLE>
<SCRIPT LANGUAGE="JavaScript">
<!-- ;
function setStatus(msg) {
  window.status = msg;
  return true;
}
function initpage () {
  window.defaultStatus = ""
  if (document.userpass) {
    if (document.userpass.username) {
      if (document.userpass.username.value == "") {
        document.userpass.username.value = readcookie("user")
      }
    }
    if (document.userpass.passwd) {
      if (document.userpass.passwd.value == "") {
        document.userpass.passwd.value = readcookie("rpwd")
      }
    }
  }
}function readcookie(name) {
  var i = 0; var lookfor = name + "="
  while (i < document.cookie.length) {
    var j = i + lookfor.length
    if (document.cookie.substring(i,j) == lookfor) {
      var endstr = document.cookie.indexOf(";", j)
      if (endstr == -1) {
        endstr = document.cookie.length
      }
      return unescape(document.cookie.substring(j, endstr))
    }
    i = document.cookie.indexOf(" ", i) + 1
    if (i == 0) {
      break
    }
  }
  return ""
}
// end hide -->
</SCRIPT>
</HEAD>
<BODY BGCOLOR="#eeeeee" TEXT="#000000" LINK="#0000ff" VLINK="#800080" ALINK="#ff0000" BACKGROUND="http://www.eq-continuum.com/images/lebkgnd.jpg" onLoad="initpage()">
<BASEFONT SIZE="2"><FONT FACE="Verdana,Arial,Helvetica">
<A NAME="">
<a name=MT>
<CENTER><FONT SIZE=+1><B>Profile Editor</B></FONT></CENTER><HR>
Enter your username and password below to edit your profile.<FORM ACTION="http://www.eq-continuum.com/cgi-bin/board-profile.cgi" METHOD=POST>
<TABLE><TR><TD><FONT FACE="Verdana,Arial,Helvetica" SIZE=2><B>Username:</B></FONT></TD>
<TD><INPUT TYPE=TEXT NAME=username VALUE="" SIZE=15></TD></TR>
<TR><TD><FONT FACE="Verdana,Arial,Helvetica" SIZE=2><B>Password:</B></FONT></TD>
<TD><INPUT TYPE=PASSWORD NAME=password VALUE="" SIZE=15></TD></TR>
</TABLE><P><INPUT TYPE=SUBMIT VALUE="Log In">
<INPUT TYPE=HIDDEN NAME=action VALUE=profile_editor_screen>
</FORM>
<SCRIPT LANGUAGE="JavaScript">
<!--
document.forms[0].username.focus();
// -->
</SCRIPT>
<FONT SIZE=1><B></B></FONT>
</FONT>
<P>
<P>
</BODY>
</HTML>
