<!--
                 This page has been created by Renaissance IT
   Renaissance Internet Technologies Copyright (c) 1999 All Rights Reserved.

             for more info on our products, please visit :
                        http://www.renaissance.nl/

	This script has been written by Roy Boverhof <rboverhof@renaissance.nl>
	
        Pagename                : poem.html
        Last Updated    		: 26-01-2000
-->

<HTML>
<HEAD>
	<TITLE>the Seekers of Lore : Poems</TITLE>
</HEAD>

<BODY BGCOLOR="#000000" TEXT="#000000" LINK="#000000" VLINK="#000000" ALINK="#000000">
<DIV ALIGN="CENTER">
<BR>
<!-- FGN Banner Code -->
<script language="JavaScript">
	<!-- Hide from old browsers
	var random = new Number(Math.floor(9999999 * Math.random())+1);

	// Modify to reflect site specifics
	page = "eqlore.com/";
	target = "@Top1,x02,x05,x08!Top1";

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript1.1" SRC="http://oascentral.cybereps.com/RealMedia/ads/adstream_jx.ads/' + page + 1 + random + target + '">');
	document.write('</SCR');
	document.write('IPT>');

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript">');
	document.write('_version=10; //-->');
	document.write('</SCR');
	document.write('IPT>');

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript1.1">');
	document.write('_version=11; //-->');
	document.write('</SCR');
	document.write('IPT>');

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript">');

	if (navigator.appVersion.indexOf('MSIE 3') != -1){
	document.write('<IFRAME MARGINWIDTH=0 MARGINHEIGHT=0 HSPACE=0 VSPACE=0 FRAMEBORDER=0 SCROLLING=no BORDERCOLOR="#000000" SRC="oascentral.cybereps.com/RealMedia/ads/adstream_sx.ads/' + page + random + target + '"></IFRAME>');
	  }
	else if (_version < 11) {
	document.write ('<A HREF="http://oascentral.cybereps.com/RealMedia/ads/click_nx.ads/' + page + random + target + '"><IMG SRC="http://oascentral.cybereps.com/RealMedia/ads/adstream_nx.ads/' + page + random + target + '"></a>');
	  }

	document.write('</SCR');
	document.write('IPT>');

	// End Hide -->
</script>
<!-- END FGN Banner Code --><BR>
<TABLE CELLSPACING = 0 CELLPADDING = 0 BORDER = 0>
<TR>
	<TD width="63"><IMG SRC = "../graphics/topc000.jpg" WIDTH = 63 HEIGHT = 87></TD>
	<TD width="473"><IMG SRC = "../graphics/topc001.jpg" WIDTH = 473 HEIGHT = 87></TD>
	<TD width="64"><IMG SRC = "../graphics/topc002.jpg" WIDTH = 64 HEIGHT = 87></TD>
</TR>
	<TD width="63"></TD>
	<TD BGCOLOR="#BEA279" width="460">
	<DIV ALIGN="CENTER">
	<TABLE>
	<TR>
	<TD VALIGN="top"><IMG SRC="snowman.gif" WIDTH=80 HEIGHT=100 ALT="" BORDER="0"></TD>
	<TD>
	<FONT FACE="Verdana">
	<FONT SIZE="+1"><B><CENTER>A Foladen Xmas story</CENTER></B></FONT>
	<P>
	<FONT SIZE="-1">
	Twas the night before christmas<BR>
	and all through the guild<BR>
	everyone was stirring<BR>
	for the raid to be soon held<BR>
	<P>
	Blades were soon sharpened<BR>
	spells were quickly spun<BR>
	and requests came flowing<BR>
	for the now active jewelers fund<BR>
	<P>
	But the occasion was not joyous<BR>
	for there was a horrid tale<BR>
	Of many kendrid elves held in slavery<BR>
	and forced to work a living .....well<BR>
	<P>
	They were forced to work in shackles<BR>
	And edible goo was their fare<BR>
	They worked for a cruel master<BR>
	who for their health did not care<BR>
	<P>
	So the seekers came to pay a visit<BR>
	Upon this creature this night<BR>
	to free their captured Brethren<BR>
	To lead them to the light<BR>
	<P>
	Then the cry came from Foladen<BR>
	to attack with no mercy<BR>
	to beat the merciless beast<BR>
	and take your time do not hurry<BR>
	<P>
	Twas Dinia and Hrvatsko<BR>
	and Shraeven and Nekkon<BR>
	there was Trinitii and Blackmaer<BR>
	and of course. Dip was not forgotten<BR>
	<P>
	Onward they charged<BR>
	with lust for battle in their eyes<BR>
	while singing out<BR>
	"The Fat man must die!!!"<BR>
	<P>
	And on fought the guild<BR>
	and not a single one was slew<BR>
	for those who stand against us<BR>
	are far and very few<BR>
	<P>
	When the dust had cleared<BR>
	and the battle was over<BR>
	of the enemy only one stood<BR>
	the fat man, the reindeer lover<BR>
	<P>
	With a sense of irony<BR>
	(and a good sense of humor)<BR>
	They chained him to his own sled<BR>
	and spread a few good rumors<BR>
	<P>
	And with a smile on his face<BR>
	and tipsy from drink and fight<BR>
	Foladen shouted merry christmas to all<BR>
	and to all a good night<BR>
	</FONT>
	<BR>
	<BR>
	<B>Foladen Moonsong</B>, <FONT SIZE="-1">bard of the isles.</FONT>
	</FONT>
	<BR>
	</TD>
	<TD VALIGN="bottom"><IMG SRC="santawave.gif" WIDTH=100 HEIGHT=100 ALT="" BORDER="0"></TD>
	</TR>
	</TABLE>

<TABLE>
<TR>
<TD><A HREF="http://www.loreseekers.com/tales.phtml"><IMG SRC="http://www.loreseekers.com/graphics/tales_return_link.jpg" WIDTH=200 HEIGHT=75 ALT="Read some other stories by our members!" BORDER="0"></A></TD>
</TR>
</TABLE>

	<TD width="64"></TD>
<TR>
	<TD><IMG SRC = "../graphics/botc000.jpg" WIDTH = 63 HEIGHT = 87></TD>
	<TD><IMG SRC = "../graphics/botc001.jpg" WIDTH = 473 HEIGHT = 87></TD>
	<TD><IMG SRC = "../graphics/botc002.jpg" WIDTH = 64 HEIGHT = 87></TD>
</TR>
</TABLE>
<BR>
<IMG SRC="http://service.bfast.com/bfast/serve?bfmid=1375281&siteid=40292692&bfpage=pc" BORDER="0" WIDTH="1" HEIGHT="1" NOSAVE ><A HREF="http://service.bfast.com/bfast/click?bfmid=1375281&siteid=40292692&bfpage=pc" TARGET="_new"><IMG SRC="http://affiliate.gamestop.com/affIMG/pc_120x60.gif" BORDER="0" WIDTH="120" HEIGHT="60" ALT="PC Games at GameStop.com"></A>
<BR>
<BR>
</DIV>
</BODY>
</HTML>

