#!/usr/local/bin/php

<center><h2><font color='Red'>You are about to expire the entire month of , !<br>ARE YOU SURE?</font></h2><br><br>
<FORM ACTION="expireResponseDoIt.phtml" METHOD="POST">
<INPUT TYPE='hidden' NAME='Month' VALUE=''><INPUT TYPE='hidden' NAME='Year' VALUE=''><INPUT TYPE="submit" NAME="Submit" VALUE="DO IT!">
</FORM>

<FORM ACTION="/calendar/admin/" METHOD="POST">
<INPUT TYPE="submit" NAME="Submit" VALUE="Just Kidding">
</FORM>

            <!--  End  Body  -->
<CENTER>
<br><hr width='70%'><br><font face='Arial'>
| <a href="../index.phtml">View Calendar</a> |
 <a href="./admin.phtml">Admin Page</a> |
<br>
</font>
</CENTER>
</BODY>
</HTML>
