<!--
                 This page has been created by Renaissance IT
   Renaissance Internet Technologies Copyright (c) 1999 All Rights Reserved.

             for more info on our products, please visit :
                        http://www.renaissance.nl/

	This script has been written by Roy Boverhof <rboverhof@renaissance.nl>
	
        Pagename                : east_faydwer_zones.html
        Last Updated    		: 05-02-2000
-->

<HTML>
<HEAD>
	<TITLE>the Seekers of Lore : East Faydwer Region</TITLE>
</HEAD>

<BODY BGCOLOR="#000000" TEXT="#000000" LINK="#000000" VLINK="#000000" ALINK="#000000">
<DIV ALIGN="CENTER">
<BR>
<script type="text/javascript"><!--
google_ad_client = "pub-0988179937943699";
google_ad_width = 468;
google_ad_height = 60;
google_ad_format = "468x60_as";
google_ad_channel ="";
google_ad_type = "text_image";
//--></script>
<script type="text/javascript"
  src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
</script><BR>
<TABLE CELLSPACING = 0 CELLPADDING = 0 BORDER = 0>
<TR>
	<TD width="63"><IMG SRC = "graphics/topc000.jpg" WIDTH = 63 HEIGHT = 87></TD>
	<TD width="473"><IMG SRC = "graphics/topc001.jpg" WIDTH = 473 HEIGHT = 87></TD>
	<TD width="64"><IMG SRC = "graphics/topc002.jpg" WIDTH = 64 HEIGHT = 87></TD>
</TR>
	<TD width="63"></TD>
	<TD BGCOLOR="#BEA279" width="460">
	<DIV ALIGN="CENTER">
	<A HREF="maps.php3"><IMG SRC="graphics/atlasheader.jpg" WIDTH ="150" HEIGHT ="75" BORDER="0"></A>
	<TABLE WIDTH="460">
	<TR><TD>
	<CENTER>
<TABLE BORDER="0">
<TR>
<TD><BR><FONT COLOR="#FFFF00" SIZE="4" FACE="Ariel"><CENTER>Now choose a zone...</CENTER></FONT><BR></TD>
</TR>
<TR>
<TD>
<IMG SRC="graphics/east_faydwer_zones.jpg" WIDTH=400 HEIGHT=400 BORDER=0 USEMAP="#eastfaydwer">
<MAP NAME="eastfaydwer">
<AREA SHAPE=RECT COORDS="65,97,167,119" HREF="map_search.php3?action=zone&add_zone=Crushbone">
<AREA SHAPE=RECT COORDS="75,140,149,177" HREF="map_search.php3?action=zone&add_zone=Greater%20Faydark">
<AREA SHAPE=RECT COORDS="162,149,290,168" HREF="map_search.php3?action=zone&add_zone=Felwithe">
<AREA SHAPE=RECT COORDS="162,174,290,191" HREF="map_search.php3?action=zone&add_zone=Felwithe">
<AREA SHAPE=RECT COORDS="176,214,267,251" HREF="map_search.php3?action=zone&add_zone=Steamfont%20Mountains">
<AREA SHAPE=RECT COORDS="217,281,315,303" HREF="map_search.php3?action=zone&add_zone=Ak'Anon">
<AREA SHAPE=RECT COORDS="52,256,152,291" HREF="map_search.php3?action=zone&add_zone=Castle%20Mistmoore">
<AREA SHAPE=RECT COORDS="80,199,152,238" HREF="map_search.php3?action=zone&add_zone=Lesser%20Faydark">
<AREA SHAPE=POLY COORDS="69,151,69,177,51,164,69,151" HREF="west_faydwer_zones.phtml" ALT="To West Faydwer Region">
</MAP>
</TD>
</TR>
</TABLE>
	</TD></TR>
	</TABLE>
	<TD width="64"></TD>
<TR>
	<TD><IMG SRC = "graphics/botc000.jpg" WIDTH = 63 HEIGHT = 87></TD>
	<TD><IMG SRC = "graphics/botc001.jpg" WIDTH = 473 HEIGHT = 87></TD>
	<TD><IMG SRC = "graphics/botc002.jpg" WIDTH = 64 HEIGHT = 87></TD>
</TR>
</TABLE>
<BR>
<IMG SRC="http://service.bfast.com/bfast/serve?bfmid=1375281&siteid=40292692&bfpage=pc" BORDER="0" WIDTH="1" HEIGHT="1" NOSAVE ><A HREF="http://service.bfast.com/bfast/click?bfmid=1375281&siteid=40292692&bfpage=pc" TARGET="_new"><IMG SRC="http://affiliate.gamestop.com/affIMG/pc_120x60.gif" BORDER="0" WIDTH="120" HEIGHT="60" ALT="PC Games at GameStop.com"></A>
<BR>
<BR>
</DIV>
</BODY>
</HTML>