<html>
<body>
<!-- AdSpace size=468x60 affiliate=castersrealm channel=games subchannel=rpg Network=affiliates rating=g --><iframe width=468 height=60 marginwidth=0 marginheight=0 frameborder=0 bordercolor="000000" scrolling=no src="http://ads2.crgaming.com/cgi-bin/AdServ32.dll?GetAdd&amp;region=2&burst=12345"><script language="javascript1.1" src="http://mediamgr.ugo.com:80/js.ng/params.richmedia=yes&size=468x60&affiliate=castersrealm&channel=games&subchannel=rpg&Network=affiliates&rating=g"></script><noscript><a href="http://mediamgr.ugo.com:80/click.ng/params.richmedia=yes&UID=$random$&size=468x60&affiliate=castersrealm&channel=games&subchannel=rpg&Network=affiliates&rating=g"><img src="http://mediamgr.ugo.com:80/image.ng/params.richmedia=yes&UID=$random$&size=468x60&affiliate=castersrealm&channel=games&subchannel=rpg&Network=affiliates&rating=g" border=0></a></noscript></iframe><!-- /AdSpace -->
</body>
</html>


