#!/usr/local/bin/php


<FORM ACTION="expireResponse.phtml" METHOD="POST">

<table border='0' cellspacing='5' cellpadding='0'>
<tr>

<td>
<font face='Arial' color='Blue'>Month:</font><br>
<SELECT NAME='Month'>
<OPTION VALUE='01'> January </OPTION>
<OPTION VALUE='02'> February </OPTION>
<OPTION VALUE='03'> March </OPTION>
<OPTION VALUE='04'> April </OPTION>
<OPTION VALUE='05'> May </OPTION>
<OPTION VALUE='06'> June </OPTION>
<OPTION VALUE='07'> July </OPTION>
<OPTION VALUE='08'> August </OPTION>
<OPTION VALUE='09'> September </OPTION>
<OPTION VALUE='10'> October </OPTION>
<OPTION VALUE='11'> November </OPTION>
<OPTION VALUE='12'> December </OPTION>
</SELECT>
</td>

<td>
<font face='Arial' color='Blue'>Year:</font><br>
<SELECT NAME='Year'>
<OPTION VALUE='1998'> 1998 </OPTION>
<OPTION VALUE='1999'> 1999 </OPTION>
<OPTION VALUE='2000'> 2000 </OPTION>
<OPTION VALUE='2001'> 2001 </OPTION>
<OPTION VALUE='2002'> 2002 </OPTION>
<OPTION VALUE='2003'> 2003 </OPTION>
<OPTION VALUE='2004'> 2004 </OPTION>
<OPTION VALUE='2005'> 2005 </OPTION>
</SELECT>
</td>
</tr>


<center>
<td>
<INPUT TYPE="submit" NAME="Submit" VALUE="Submit">
</td>
</center>
</table>

            <!--  End  Body  -->
<CENTER>
<br><hr width='70%'><br><font face='Arial'>
| <a href="../index.phtml">View Calendar</a> |
 <a href="./admin.phtml">Admin Page</a> |
<br>
</font>
</CENTER>
</BODY>
</HTML>

