<!--
                 This page has been created by Renaissance IT
   Renaissance Internet Technologies Copyright (c) 1999 All Rights Reserved.

             for more info on our products, please visit :
                        http://www.renaissance.nl/

	This script has been written by Roy Boverhof <rboverhof@renaissance.nl>
	
        Pagename                : tales.html
        Last Updated    		: 08-29-2000
-->

<HTML>
<HEAD>
	<TITLE>the Seekers of Lore : Member Story Page</TITLE>
</HEAD>

<BODY BGCOLOR="#000000" TEXT="#000000" LINK="#000000" VLINK="#000000" ALINK="#000000">

<DIV ALIGN="center">
<BR>
<script type="text/javascript"><!--
google_ad_client = "pub-0988179937943699";
google_ad_width = 468;
google_ad_height = 60;
google_ad_format = "468x60_as";
google_ad_channel ="7352298734";
google_page_url = document.location;
google_color_border = "FFFFFF";
google_color_bg = "00001F";
google_color_link = "FFFFFF";
google_color_url = "FFF000";
google_color_text = "0000FF";
//--></script>
<script type="text/javascript"
  src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
</script><BR>	
<TABLE CELLSPACING=0 CELLPADDING=0 BORDER=0>
<TR>
	<TD WIDTH=63><IMG SRC="../graphics/topc000.jpg" WIDTH=63 HEIGHT=87></TD>
	<TD WIDTH=473><IMG SRC="../graphics/topc001.jpg" WIDTH=473 HEIGHT=87></TD>
	<TD WIDTH=64><IMG SRC="../graphics/topc002.jpg" WIDTH=64 HEIGHT=87></TD>
</TR>
	<TD width=63></TD>
	<TD BGCOLOR="#BEA279" WIDTH=460>
		<FONT FACE="Verdana">

		<DIV ALIGN="center">
		<TABLE WIDTH=400 ALIGN="center">
		<TR>
		<TD><IMG SRC="http://www.loreseekers.com/graphics/spinning_globe_1.gif" WIDTH=150 HEIGHT=150 BORDER=0></TD>
		<TD><IMG SRC="http://www.loreseekers.com/graphics/tale_header.jpg" WIDTH=200 HEIGHT=150 BORDER=0></TD>
		</TR>
		</TABLE>
		</DIV>

<DIV ALIGN="center">
<FONT SIZE=3><B>Stories of Norrath by our members</B></FONT><BR>
</DIV>

<TABLE BGCOLOR="#BEA279" width=460 CELLPADDING=5 CELLSPACING=5>
<TR>
<TD BGCOLOR="#BEA279" width=100></TD>
<TD GCOLOR="#BEA279" width=260>

<HR>
<OL>
<FONT FACE="Verdana" SIZE="-1"><B><LI> <A HREF="stories/fishing.phtml">Fishing for Trouble</A><FONT FACE="Verdana" SIZE="-2" COLOR="#FF0000"> - New!</FONT></B><BR>&nbsp;&nbsp;&nbsp; - <FONT FACE="Verdana" SIZE="-2">by Galun Stormfury</FONT></FONT><BR><BR>

<FONT FACE="Verdana" SIZE="-1"><B><LI> <A HREF="stories/hyppy_poem.phtml">A Winter's Afternoon</A></B><BR>&nbsp;&nbsp;&nbsp; - <FONT FACE="Verdana" SIZE="-2">by Hyppy</FONT></FONT><BR><BR>

<FONT FACE="Verdana" SIZE="-1"><B><LI> <A HREF="stories/fear.phtml">Fear</A></B><BR>&nbsp;&nbsp;&nbsp; - <FONT FACE="Verdana" SIZE="-2">by Foladen Moonsong</FONT></FONT><BR><BR>

<FONT FACE="Verdana" SIZE="-1"><B><LI> <A HREF="stories/travels3.phtml">Travels - Part Three</A></B><BR>&nbsp;&nbsp;&nbsp; - <FONT FACE="Verdana" SIZE="-2">by Mandos Turambar</FONT></FONT><BR><BR>

<FONT FACE="Verdana" SIZE="-1"><B><LI> <A HREF="stories/travels1.phtml">Travels - Part One</A></B><BR>&nbsp;&nbsp;&nbsp; - <FONT FACE="Verdana" SIZE="-2">by Mandos Turambar</FONT></FONT><BR><BR>

<FONT FACE="Verdana" SIZE="-1"><B><LI> <A HREF="stories/travels2.phtml">Travels - Part Two</A></B><BR>&nbsp;&nbsp;&nbsp; - <FONT FACE="Verdana" SIZE="-2">by Mandos Turambar</FONT></FONT><BR><BR>

<FONT FACE="Verdana" SIZE="-1"><B><LI> <A HREF="stories/shin_kao.phtml">Shin Kao</A></B><BR>&nbsp;&nbsp;&nbsp; - <FONT FACE="Verdana" SIZE="-2">by Mordier Morvran</FONT></FONT><BR><BR>

<FONT FACE="Verdana" SIZE="-1"><B><LI> <A HREF="stories/diary1.phtml">Diary of a Dark Elf</A></B><BR>&nbsp;&nbsp;&nbsp; - <FONT FACE="Verdana" SIZE="-2">Part #1 by Nalfein T'sarran</FONT></FONT><BR><BR>

<FONT FACE="Verdana" SIZE="-1"><B><LI> <A HREF="stories/mordier2.phtml">Reunion at Chops</A></B><BR>&nbsp;&nbsp;&nbsp; - <FONT FACE="Verdana" SIZE="-2">by Mordier Morvran</FONT></FONT><BR><BR>

<FONT FACE="Verdana" SIZE="-1"><B><LI> <A HREF="stories/mordier.phtml">I am Mordier</A></B><BR>&nbsp;&nbsp;&nbsp; - <FONT FACE="Verdana" SIZE="-2">by Mordier Morvran</FONT></FONT><BR><BR>

<FONT FACE="Verdana" SIZE="-1"><B><LI> <A HREF="stories/spider_room_poem.phtml">Spider Room (Poem)</A></B><BR>&nbsp;&nbsp;&nbsp; - <FONT FACE="Verdana" SIZE="-2">by Cendan Tankenpriest </FONT></FONT><BR><BR>

<FONT FACE="Verdana" SIZE="-1"><B><LI> <A HREF="stories/caves.phtml">Caves of Peril!</A></B><BR>&nbsp;&nbsp;&nbsp; - <FONT FACE="Verdana" SIZE="-2">by Nalfein T'sarran</FONT></FONT><BR><BR>

<FONT FACE="Verdana" SIZE="-1"><B><LI> <A HREF="stories/cazic.phtml">Battle at Cazic~Thule</A></B><BR>&nbsp;&nbsp;&nbsp; - <FONT FACE="Verdana" SIZE="-2">by Nalfein T'sarran</FONT></FONT><BR><BR>

<FONT FACE="Verdana" SIZE="-1"><B><LI> <A HREF="stories/poem.phtml">A Christmas Poem</A></B><BR>&nbsp;&nbsp;&nbsp; - <FONT FACE="Verdana" SIZE="-2">by Foladen Moonsong</FONT></FONT><BR><BR>

<FONT FACE="Verdana" SIZE="-1"><B><LI> <A HREF="stories/faith.phtml">Faith</A></B><BR>&nbsp;&nbsp;&nbsp; - <FONT FACE="Verdana" SIZE="-2">by Foladen Moonsong</FONT></FONT><BR><BR>

<FONT FACE="Verdana" SIZE="-1"><B><LI> <A HREF="stories/battle.phtml">the Battle</A></B><BR>&nbsp;&nbsp;&nbsp; - <FONT FACE="Verdana" SIZE="-2">by Foladen Moonsong</FONT></FONT><BR><BR>

<FONT FACE="Verdana" SIZE="-1"><B><LI> <A HREF="stories/death.phtml">In the Eyes of Death</A></B><BR>&nbsp;&nbsp;&nbsp; - <FONT FACE="Verdana" SIZE="-2">by Multam Weatherlight</FONT></FONT><BR>
</OL>
<HR>

</TD>
<TD BGCOLOR="#BEA279" width=100></TD>
</TR>
</TABLE>
	<TD width=64></TD>
<TR>
	<TD><IMG SRC="../graphics/botc000.jpg" WIDTH=63 HEIGHT=87></TD>
	<TD><IMG SRC="../graphics/botc001.jpg" WIDTH=473 HEIGHT=87></TD>
	<TD><IMG SRC="../graphics/botc002.jpg" WIDTH=64 HEIGHT=87></TD>
</TR>
</TABLE>
</DIV>

<DIV ALIGN="center">
<script type="text/javascript"><!--
google_ad_client = "pub-0988179937943699";
google_ad_width = 180;
google_ad_height = 60;
google_ad_format = "180x60_as_rimg";
google_cpa_choice = "CAAQ56j8zwEaCHvU9tBAqJJaKMu293M";
//--></script>
<script type="text/javascript" src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
</script>
<BR>
</DIV>
<BR>
<BR>
</BODY>
</HTML>
