<!--
                 This page has been created by Renaissance IT
   Renaissance Internet Technologies Copyright (c) 1999 All Rights Reserved.

             for more info on our products, please visit :
                        http://www.renaissance.nl/

	This script has been written by Roy Boverhof <rboverhof@renaissance.nl>
	
        Pagename                : velious_shots.phtml
        Last Updated    		: 09-11-2000
-->

<HTML>
<HEAD>
	<TITLE>the Seekers of Lore : Scars of Velious Shots</TITLE>
</HEAD>

<BODY BGCOLOR="#000000" TEXT="#000000" LINK="#000000" VLINK="#000000" ALINK="#000000">
<DIV ALIGN="CENTER">
<BR>
<!-- FGB Banner Code -->
<SCRIPT LANGUAGE="JavaScript">
<!-- Hide from old browsers
now = new Date();
random = now.getTime();

// Modify to reflect site specifics
site = "http://ds.cybereps.com";
target = "/SITE=FGN/AREA=EQLORE/AAMSZ=BANNER";

document.write('<IFRAME SRC="' + site + '/hserver/acc_random=' + random + target + '"');
document.write(' NORESIZE SCROLLING=NO HSPACE=0 VSPACE=0 FRAMEBORDER=0 MARGINHEIGHT=0 MARGINWIDTH=0 WIDTH=468 HEIGHT=60>');

document.write('<SCR');
document.write('IPT SRC="' + site + '/jnserver/acc_random=' + random + target + '">');
document.write('</SCR');
document.write('IPT>');

document.write('</IFRAME>');
// End Hide -->
</SCRIPT>

<NOSCRIPT><A HREF="http://ds.cybereps.com/accipiter/adclick/SITE=FGN/AREA=EQLORE/AAMSZ=BANNER"><IMG SRC="http://ds.cybereps.com/accipiter/nserver/SITE=FGN/AREA=EQLORE/AAMSZ=BANNER" border="0"></A></NOSCRIPT>
<!-- END FGB Banner Code --><BR>	
<TABLE CELLSPACING = 0 CELLPADDING = 0 BORDER = 0>
<TR>
	<TD width="63"><IMG SRC = "graphics/topc000.jpg" WIDTH = 63 HEIGHT = 87></TD>
	<TD width="473"><IMG SRC = "graphics/topc001.jpg" WIDTH = 473 HEIGHT = 87></TD>
	<TD width="64"><IMG SRC = "graphics/topc002.jpg" WIDTH = 64 HEIGHT = 87></TD>
</TR>
	<TD width="63"></TD>
	<TD BGCOLOR="#BEA279" width="460">
	<DIV ALIGN="CENTER">
		<A HREF="http://www.loreseekers.com/screenshots.phtml"><IMG SRC="graphics/screencap_header.gif" WIDTH ="200" HEIGHT ="75" BORDER="0"></A>
	<TABLE WIDTH="460">
	<TR><TD>
	<CENTER>

<TABLE BORDER="0">
<TR>
<TD ALIGN="center">
<FONT SIZE="4" FACE="Ariel">Newest <A HREF="http://everquest.station.sony.com/velious/index.html" TARGET="_new">Scars of Velious™</A> screenshots</FONT><BR>
</TD>
</TR>
<TR>
<TD ALIGN="center"><FONT SIZE="2" FACE="Arial">From various SoV previews</FONT></TD>
</TR>
</TABLE>

<TABLE BORDER="0">
<TR> 
	<TD><A HREF="http://www.loreseekers.com/screenshots/quest1.jpg" TARGET="_new"><IMG SRC="http://www.loreseekers.com/screenshots/tn_quest1.jpg" WIDTH ="130" HEIGHT ="98" ALT="Click to view image full size"></A></TD>
	<TD><A HREF="http://www.loreseekers.com/screenshots/quest2.jpg" TARGET="_new"><IMG SRC="http://www.loreseekers.com/screenshots/tn_quest2.jpg" WIDTH ="130" HEIGHT ="98" ALT="Click to view image full size"></A></TD>
	<TD><A HREF="http://www.loreseekers.com/screenshots/quest4.jpg" TARGET="_new"><IMG SRC="http://www.loreseekers.com/screenshots/tn_quest4.jpg" WIDTH ="130" HEIGHT ="98" ALT="Click to view image full size"></A></TD>
</TR>
<TR> 
	<TD><A HREF="http://www.loreseekers.com/screenshots/quest5.jpg" TARGET="_new"><IMG SRC="http://www.loreseekers.com/screenshots/tn_quest5.jpg" WIDTH ="130" HEIGHT ="98" ALT="Click to view image full size"></A></TD>
	<TD><A HREF="http://www.loreseekers.com/screenshots/quest6.jpg" TARGET="_new"><IMG SRC="http://www.loreseekers.com/screenshots/tn_quest6.jpg" WIDTH ="130" HEIGHT ="98" ALT="Click to view image full size"></A></TD>
	<TD><A HREF="http://www.loreseekers.com/screenshots/quest7.jpg" TARGET="_new"><IMG SRC="http://www.loreseekers.com/screenshots/tn_quest7.jpg" WIDTH ="130" HEIGHT ="98" ALT="Click to view image full size"></A></TD>
</TR>
<TR> 
	<TD><A HREF="http://www.loreseekers.com/screenshots/quest8.jpg" TARGET="_new"><IMG SRC="http://www.loreseekers.com/screenshots/tn_quest8.jpg" WIDTH ="130" HEIGHT ="98" ALT="Click to view image full size"></A></TD>
	<TD><A HREF="http://www.loreseekers.com/screenshots/quest9.jpg" TARGET="_new"><IMG SRC="http://www.loreseekers.com/screenshots/tn_quest9.jpg" WIDTH ="130" HEIGHT ="98" ALT="Click to view image full size"></A></TD>
	<TD><A HREF="http://www.loreseekers.com/screenshots/shot12big.jpg" TARGET="_new"><IMG SRC="http://www.loreseekers.com/screenshots/tn_shot12big.jpg" WIDTH ="130" HEIGHT ="98" ALT="Click to view image full size"></A></TD>
</TR>
<TR>
	<TD><A HREF="http://www.loreseekers.com/screenshots/shot4big.jpg" TARGET="_new"><IMG SRC="http://www.loreseekers.com/screenshots/tn_shot4big.jpg" WIDTH ="130" HEIGHT ="98" ALT="Click to view image full size"></A></TD>
	<TD><A HREF="http://www.loreseekers.com/screenshots/shot5big.jpg" TARGET="_new"><IMG SRC="http://www.loreseekers.com/screenshots/tn_shot5big.jpg" WIDTH ="130" HEIGHT ="98" ALT="Click to view image full size"></A></TD>
	<TD><A HREF="http://www.loreseekers.com/screenshots/shot6big.jpg" TARGET="_new"><IMG SRC="http://www.loreseekers.com/screenshots/tn_shot6big.jpg" WIDTH ="130" HEIGHT ="98" ALT="Click to view image full size"></A></TD>
</TR>
<TR>
	<TD><A HREF="http://www.loreseekers.com/screenshots/shot7big.jpg" TARGET="_new"><IMG SRC="http://www.loreseekers.com/screenshots/tn_shot7big.jpg" WIDTH ="130" HEIGHT ="98" ALT="Click to view image full size"></A></TD>
	<TD><A HREF="http://www.loreseekers.com/screenshots/shot9big.jpg" TARGET="_new"><IMG SRC="http://www.loreseekers.com/screenshots/tn_shot9big.jpg" WIDTH ="130" HEIGHT ="98" ALT="Click to view image full size"></A></TD>
	<TD><A HREF="http://www.loreseekers.com/screenshots/shot2big.jpg" TARGET="_new"><IMG SRC="http://www.loreseekers.com/screenshots/tn_shot2big.jpg" WIDTH ="130" HEIGHT ="116" ALT="Click to view image full size"></A></TD>
</TR>
</TABLE>

<BR><BR>
<TABLE BORDER="0">
<TR>
<TD>
<FONT SIZE="4" FACE="Ariel">Previous <A HREF="http://everquest.station.sony.com/velious/index.html" TARGET="_new">Scars of Velious™</A> screenshots</FONT><BR>
</TD>
</TR>
</TABLE>

<TABLE BORDER="0">
<TR> 
	<TD><A HREF="http://www.loreseekers.com/screenshots/sov001.jpg" TARGET="_new"><IMG SRC="http://www.loreseekers.com/screenshots/tn_sov001.jpg" WIDTH ="200" HEIGHT ="150" ALT="Click to view image full size"></A></TD>
	<TD><A HREF="http://www.loreseekers.com/screenshots/sov002.jpg" TARGET="_new"><IMG SRC="http://www.loreseekers.com/screenshots/tn_sov002.jpg" WIDTH ="200" HEIGHT ="150" ALT="Click to view image full size"></A></TD>
</TR>
<TR>
	<TD><FONT SIZE="2" FACE="ARIEL"><CENTER>Voodoo 3 in 800 X 600</CENTER></FONT></TD>
	<TD><FONT SIZE="2" FACE="ARIEL"><CENTER>Voodoo 3 in 800 X 600</CENTER></FONT></TD>
</TR>
<TR> 
	<TD><A HREF="http://www.loreseekers.com/screenshots/sov003.jpg" TARGET="_new"><IMG SRC="http://www.loreseekers.com/screenshots/tn_sov003.jpg" WIDTH ="200" HEIGHT ="150" ALT="Click to view image full size"></A></TD>
	<TD>&nbsp;</TD>
</TR>
<TR>
	<TD><FONT SIZE="2" FACE="ARIEL"><CENTER>Voodoo 3 in 800 X 600</CENTER></FONT></TD>
	<TD>&nbsp;</TD>
</TR>
</TABLE>

</CENTER>
	<P>
	<BR>
	<BR>
	</P>
	</TD></TR>
	</TABLE>
	<TD width="64"></TD>
<TR>
	<TD><IMG SRC = "graphics/botc000.jpg" WIDTH = 63 HEIGHT = 87></TD>
	<TD><IMG SRC = "graphics/botc001.jpg" WIDTH = 473 HEIGHT = 87></TD>
	<TD><IMG SRC = "graphics/botc002.jpg" WIDTH = 64 HEIGHT = 87></TD>
</TR>
</TABLE>
<BR>
<SCRIPT LANGUAGE="JavaScript">
<!-- Hide from old browsers
now = new Date();
random = now.getTime();

// Modify to reflect site specifics
site = "http://ds.cybereps.com";
target = "/SITE=FGN/AREA=EQLORE/AAMSZ=BUTTON1";

document.write('<IFRAME SRC="' + site + '/hserver/acc_random=' + random + target + '"');
document.write(' NORESIZE SCROLLING=NO HSPACE=0 VSPACE=0 FRAMEBORDER=0 MARGINHEIGHT=0 MARGINWIDTH=0 WIDTH=120 HEIGHT=90>');

document.write('<SCR');
document.write('IPT SRC="' + site + '/jnserver/acc_random=' + random + target + '">');
document.write('</SCR');
document.write('IPT>');

document.write('</IFRAME>');
// End Hide -->
</SCRIPT>
<NOSCRIPT> <A HREF="http://ds.cybereps.com/accipiter/adclick/SITE=FGN/AREA=EQLORE/AAMSZ=BUTTON1">
<IMG SRC="http://ds.cybereps.com/accipiter/nserver/SITE=FGN/AREA=EQLORE/AAMSZ=BUTTON1" border="0"></A>
</NOSCRIPT>
<BR>
<BR>
</DIV>
</BODY>
</HTML>


