<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">

<html>
<head>
	<title>..:: EQBard : le site de Jonili le petit barde ::..</title>

<SCRIPT LANGUAGE="Javascript">
<!--
function fenetre(intitule,params) { 
var fen = window.open(intitule,'zoom',params); 
}
//-->
</script>

<style>
a.lientexte {color:#0B5040;text-decoration:none;}
a.lientexte:hover {color:#0B5040;text-decoration:underline;}
</style>
</head>

<body bgcolor='#CFE6E3' text='#000000' link='#0B5040' vlink='#000000' alink='#000000'>
<table width='680' border='0' cellspacing='0' cellpadding='0'>
<tr><td>
<table width='680' border='0' cellspacing='0' cellpadding='0'>
<tr>
<td width='680' align='right' valign='top'>
<img src='./img/commun/c01/carre80.gif' width='10' height='10' border='0' alt=''>
<img src='./img/commun/c01/carre70.gif' width='10' height='10' border='0' alt=''>
<img src='./img/commun/c01/carre60.gif' width='10' height='10' border='0' alt=''>
<img src='./img/commun/c01/carre50.gif' width='10' height='10' border='0' alt=''>
</td></tr>
<tr><td height='2'><img src='./img/commun/transparent.gif' height='2' alt='' border='0'></td></tr>
<tr><td width='680' height='1'><img src='./img/commun/c01/carre50.gif' width='680' height='1' alt='' border='0'></td></tr>
</table>
</td></tr><tr><td>
<table width='680' border='0' cellspacing='0' cellpadding='0'>
<tr><td width='120' valign='top'><table width='100%' border='0' cellspacing='0' cellpadding='0'>
<tr><td>
<font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>&nbsp;<br>
<img src='./img/commun/c01/carre70.gif' width='10' height='10' border='0' alt=''>&nbsp;<a href=index.php?menu=1&data=1 class=lientexte><b>Accueil</b></a><br>&nbsp;<br>
<img src='./img/commun/c01/carre70.gif' width='10' height='10' border='0' alt=''>&nbsp;<b>Equipement</b><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=32&data=31&inc=armures class=lientexte>Armures</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=33&data=31&inc=armes&order=1&sens=1&bard=1 class=lientexte>Armes</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=35&data=31&inc=slot class=lientexte>Par slot</a><br>&nbsp;<br>
<img src='./img/commun/c01/carre70.gif' width='10' height='10' border='0' alt=''>&nbsp;<b>Guides</b><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=41&data=41 class=lientexte>Général</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=42&data=42 class=lientexte>Tactiques</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carreselect.gif' width='5' height='5' border='0' alt=''>&nbsp;Quêtes<br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=44&data=44 class=lientexte>Zones</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=45&data=45 class=lientexte>Procs</a><br>&nbsp;<br>
<img src='./img/commun/c01/carre70.gif' width='10' height='10' border='0' alt=''>&nbsp;<b>Photos</b><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=51&data=51 class=lientexte>Atlas</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=52&data=52 class=lientexte>Bardes</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=54&data=54 class=lientexte>GM</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=55&data=55 class=lientexte>Divers</a><br>&nbsp;<br>
<img src='./img/commun/c01/carre70.gif' width='10' height='10' border='0' alt=''>&nbsp;<a href=index.php?menu=8&data=8 class=lientexte><b>Mode</b></a><br>&nbsp;<br>
<img src='./img/commun/c01/carre70.gif' width='10' height='10' border='0' alt=''>&nbsp;<b>Spells Sebilis</b><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=1001&data=10 class=lientexte>Barde</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=1002&data=10 class=lientexte>Belluaire</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=1003&data=10 class=lientexte>Chaman</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=1004&data=10 class=lientexte>Clerc</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=1005&data=10 class=lientexte>Druide</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=1006&data=10 class=lientexte>Enchanteur</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=1007&data=10 class=lientexte>Fléau d'ombre</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=1009&data=10 class=lientexte>Magicien</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=1012&data=10 class=lientexte>Nécromancien</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=1013&data=10 class=lientexte>Paladin</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=1014&data=10 class=lientexte>Rôdeur</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=1015&data=10 class=lientexte>Sorcier</a><br>&nbsp;<br>
<img src='./img/commun/c01/carre70.gif' width='10' height='10' border='0' alt=''>&nbsp;<a href=index.php?menu=6&data=6 class=lientexte><b>Liens</b></a><br>
<img src='./img/commun/c01/carre70.gif' width='10' height='10' border='0' alt=''>&nbsp;<a href=index.php?menu=7&data=7 class=lientexte><b>Download</b></a><br>
<img src='./img/commun/c01/carre70.gif' width='10' height='10' border='0' alt=''>&nbsp;<a href='http://forumsfr.ubi.com/messages/overview.asp?name=eq_themaeq_eqbardes' target='_blank' class=lientexte><b>Forum</b></a><br>
<img src='./img/commun/c01/carre70.gif' width='10' height='10' border='0' alt=''>&nbsp;<a href=mailto:jonili@eqbard.eqloft.com class=lientexte><b>M'écrire</b></a><br>&nbsp;<br>
<img src='./img/commun/c01/carre70.gif' width='10' height='10' border='0' alt=''>&nbsp;<a href=index.php?menu=9&data=9 class=lientexte><b>Backstage</b></a><br>&nbsp;<br></font></td></tr></table>
</td><td width='20' valign='top'><img src='./img/commun/c01/carre50.gif' width='10' height='10' border='0' alt=''>
<img src='./img/commun/c01/carre60.gif' width='10' height='10' border='0' alt=''>
<img src='./img/commun/c01/carre70.gif' width='10' height='10' border='0' alt=''>
<img src='./img/commun/c01/carre80.gif' width='10' height='10' border='0' alt=''>
</td><td width='540' align='left' valign='top'><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>&nbsp;<br><a href='index.php?menu=43&data=43 class=lientexte' class=lientexte><b>< Retour</b></a><br>&nbsp;<br><table width='100%' border='0' cellspacing='0' cellpadding='0'><tr><td colspan='2' bgcolor='#0B5040'><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2' color='white'><b>&nbsp;La quête du Rallic Pack</b></font></td></tr><tr><td width ='10'>&nbsp;</td><td><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>&nbsp;<br>
Le Rallic pack est un sac de réduction de poids très intéressant. Voici les caractéristiques :
<ul>
<li>10 slots (10 emplacements, il n'y a pas mieux)
<li>weight réduction 85% (tous les objets contenus dans le sac ont leur poids réduit de 85%)
<li>Size giant (vous pouvez y mettre les objets géants, donc tous les objets possibles)
<li>Weight 1.0 (poids 1, ce qui est très peu et devrait même plaire aux moines)
<li>Lore item (vous ne pouvez en avoir qu'un, dommage !)
</ul>

La quête se finit dans Katta Castellum. Vous devez avoir une bonne faction avec les humains de Katta pour la faire. Vaux mieux aussi ne pas être koS à Shar Vahl.
<br>&nbsp;<br>
Il faut avoir à peu près 30 en couture pour faire la quête.
<br>&nbsp;<br>
Vous pouvez faire la quête complète en allantd'abord trouver Rallic Aristos dans Katta Castellum. Il est dans le château, au rez-de-chaussée. Mais ce n'est pas indispensable, vous pouvez récolter les ingrédients d'abord et aller le voir à la fin pour avoir le sac.
<br>&nbsp;<br>
Voici le dialogue avec Rallic (en supposant que vous vous appelez Maestro : 
<ul>
<li>You say, 'Hail, Rallic Aristos' 
<li>Rallic Aristos says 'Well met Maestro ! I am Rallic Aristos, Governor of trade and economy here in Katta Castellum. I know it sounds like a lot of parchment pushing and coin counting but maintaining good trade relations with the various Houses of Shadow Haven and the haggling Vah Shir of Shar Vahl is not as easy at it may sound. Then there is the issue of the [acrylia mines] in the Tenebrous Mountains.
<li>You say, 'what acrylia mines?' 
<li>Rallic Aristos says 'The Tenebrous Mountains are rich with veins of the valuable acrylia ore. Unfortunately the mines were dug and controlled by a tribe of savage grimlings from the forests to the south. Negotiations have been attempted with the grimlings but to no avail. Several of the other governors and I have been developing a [plan] to take the mines or establish mines of our own. In either case the mines will have to be defended from attacks by the grimlings unless when placed in that predicament they finally resort to trade negotiations.
<li>You say, 'what plan?' 
<li>Rallic Aristos says 'The full plans are not at my disposal but one of my concerns that may be instrumental in our success is the acquisition of grimling documents carried by a grimling courier who is seen frequently running from the forest to the mines. If one of the Validus Custodus attempts to obtain the runners pouch the grimlings will surely retaliate, if adventurers like yourselves obtained it however and quietly delivered it to me we may be able to move forward with our plans.
</ul>
Le même dialogue, traduit en français (traduction à la hauteur de mes capacités en anglais) :
<ul>
<li>Vous dites, 'Hail, Rallic Aristos' 
<li>Rallic Aristos dits Bienvenue Maestro ! Je suis Rallic Aristos, Gouverneur des échanges et de l'économie ici à Katta Castellum. Je sais que cela ressemble à beaucoup de parchemins à lire et à écrire et d'argent à compter, mais maintenir de bonnes relations commerciales avec les différentes maisons de Shadow Haven et de Shar Vahl n'est pas aussi facile que cela pourrait paraître. Ensuite il y a le problème des mines d'acrilia dans les Tenebrous Mountains.
<li>Vous dites 'quelles mines d'acrilia?' 
<li>Rallic Aristos dit 'Les Tenebrous Mountains sont pleines de filons de minerai d'acrilia, qui vaut beaucoup d'argent. Malheureusement les mines sont exploitées et contrôlées par une tribu de sauvages grimlings qui viennent des forêts du sud. Des négociations ont été tentées avec les grimlings, mais sans résultat. Plusieurs des autres gouverneurs et moi avons mis au point un plan pour reprendre les mines ou établir des mines à nous. Dans les deux cas les mines doivent être défendues contre les attaques des grimlings tant qu'ils ne sont pas dans l'état d'esprit d'entamer des négociations.
<li>Vous dites, 'quel plan?' 
<li>Rallic Aristos dit 'La totalité du plan n'est pas en ma possession, mais une partie dont je suis responsable peut être la clé de notre succès. Il s'agit d'acquérir les documents des grimlings convoyés par un grimling courier qui est couramment vu courir depuis la forêt vers les mines. Si un des membres du Validus Custodus (le Conseil de la ville de Katta) arrive à obtenir le sac de ce courrier les grimlings seront bien attrappés. Si un aventurier comme vous arrivait à l'obtenir et à me le donner, nous pourrions continuer la mise en œuvre de notre plan d'action.
</ul>
Le mob à tuer est le grimling runner. Il est niveau 35, genre guerrier (il ne caste pas).
Par contre, il ne peut pas être snaré, ni rooté, ni ralenti.
<br>&nbsp;<br>
Il spawne dans Tenebrous Mountains, à la zone de Grimling Forest.
Le temps de spawn est de 90 minutes (une fois tué il revient 90 minutes plus tard).
Sur le serveur EM ce spawn est souvent campé. Vous devez attendre qu'il soit libre. Attention, restez bien à l'entrée du tunnel qui mène à la zone, il y a beaucoup de monstres errants aux alentours (à moins que vous fassiez de l'exp).
<br>&nbsp;<br>
L'objet pour la quête est un pouch ou un pack, enfin un sac quoi (lore item no drop). Il droppe à chaque fois.
<br>&nbsp;<br>
Vous donnez ce pouch à Rallic Aristos dans Katta. Il vous donne un pattern (un patron pour la couture).
<br>&nbsp;<br>
Pour avoir le Rallic Pack, il suffit de combiner dans un sewing kit : Rallic Pattern, une perfect owlbear pelt, un shade silk thread et un shade silk cord.
<br>&nbsp;<br>
Les owlbears se trouvent dans Zones possibles : 
<ul>
<li>Hollowshade Moor. Ils sont là de niveau entre 20 et 30. Mais cette zone est connue pour sa guerre perpétuelle entre les owlbears, les sonic wolfs et les grimlings. Les deux seules fois où j'y suis allée, il n'y avait plus d'owlbears, ils avaient été éliminés dans la guerre.
<li>Dans Paludal Caverns il y a un spawn de 4 owlbears, pas très loins de la zone de Shadeweaver's Thicket. Ils sont de niveau 10 à 20.
<li>Dans Grimling Forest il y en a un peu. Ils sont plus forts, niveau 35 au moins, certains étaint bleu ciel pour Tranule au 59. Mais il y en a peu et le track est très utile. C'est là que j'ai looté ma perfect pelt.
</ul>
Le shade silk se loote sur les Xakra silkworms dans Shadeweaver's Thicket. Ces vers sont niveau 1 ou 2 (comme les spiderlings).
<br>&nbsp;<br>
Il faut faire de la couture pour fabriquer les threads et les cords. Mais les threads sont triviaux à 15 et les cords à 25. C'est donc facile.
Il faut 2 silks pour faire un thread et 3 threads pour faire une cord.
<br>&nbsp;<br>
Tranule
</font>&nbsp;<br></td></tr></table>&nbsp;<br></font></td></tr></table>
</td></tr><tr><td>
<table width='680' border='0' cellspacing='0' cellpadding='0'>
<tr><td width='680' height='1'><img src='./img/commun/c01/carre50.gif' width='680' height='1' alt='' border='0'></td></tr>
<tr><td height='2'><img src='./img/commun/transparent.gif' height='2' alt='' border='0'></td></tr>
<tr>
<td width='680' align='left' valign='top'>
<img src='./img/commun/c01/carre50.gif' width='10' height='10' border='0' alt=''>
<img src='./img/commun/c01/carre60.gif' width='10' height='10' border='0' alt=''>
<img src='./img/commun/c01/carre70.gif' width='10' height='10' border='0' alt=''>
<img src='./img/commun/c01/carre80.gif' width='10' height='10' border='0' alt=''>
</td></tr>
</table>
</td></tr><tr><td align='center'>
<A target='_blank' href='http://www.eqloft.com/'><img src='./img/commun/hebergement.gif' width='122' height='31' border='0' alt=''></a></td></tr></table>

</body>
</html>
