<!--
                 This page has been created by Renaissance IT
   Renaissance Internet Technologies Copyright (c) 1999 All Rights Reserved.

             for more info on our products, please visit :
                        http://www.renaissance.nl/

	This script has been written by Roy Boverhof <rboverhof@renaissance.nl>
	
        Pagename                : death.html
        Last Updated    		: 26-01-2000
-->

<HTML>
<HEAD>
	<TITLE>the Seekers of Lore : In the Eyes of Death</TITLE>
</HEAD>

<BODY BGCOLOR="#000000" TEXT="#000000" LINK="#000000" VLINK="#000000" ALINK="#000000">
<DIV ALIGN="CENTER">
<BR>
<!-- FGN Banner Code -->
<script language="JavaScript">
	<!-- Hide from old browsers
	var random = new Number(Math.floor(9999999 * Math.random())+1);

	// Modify to reflect site specifics
	page = "eqlore.com/";
	target = "@Top1,x02,x05,x08!Top1";

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript1.1" SRC="http://oascentral.cybereps.com/RealMedia/ads/adstream_jx.ads/' + page + 1 + random + target + '">');
	document.write('</SCR');
	document.write('IPT>');

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript">');
	document.write('_version=10; //-->');
	document.write('</SCR');
	document.write('IPT>');

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript1.1">');
	document.write('_version=11; //-->');
	document.write('</SCR');
	document.write('IPT>');

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript">');

	if (navigator.appVersion.indexOf('MSIE 3') != -1){
	document.write('<IFRAME MARGINWIDTH=0 MARGINHEIGHT=0 HSPACE=0 VSPACE=0 FRAMEBORDER=0 SCROLLING=no BORDERCOLOR="#000000" SRC="oascentral.cybereps.com/RealMedia/ads/adstream_sx.ads/' + page + random + target + '"></IFRAME>');
	  }
	else if (_version < 11) {
	document.write ('<A HREF="http://oascentral.cybereps.com/RealMedia/ads/click_nx.ads/' + page + random + target + '"><IMG SRC="http://oascentral.cybereps.com/RealMedia/ads/adstream_nx.ads/' + page + random + target + '"></a>');
	  }

	document.write('</SCR');
	document.write('IPT>');

	// End Hide -->
</script>
<!-- END FGN Banner Code --><BR>
<TABLE CELLSPACING = 0 CELLPADDING = 0 BORDER = 0>
<TR>
	<TD width="63"><IMG SRC = "../graphics/topc000.jpg" WIDTH = 63 HEIGHT = 87></TD>
	<TD width="473"><IMG SRC = "../graphics/topc001.jpg" WIDTH = 473 HEIGHT = 87></TD>
	<TD width="64"><IMG SRC = "../graphics/topc002.jpg" WIDTH = 64 HEIGHT = 87></TD>
</TR>
	<TD width="63"></TD>
	<TD BGCOLOR="#BEA279" width="460">
	<DIV ALIGN="CENTER">
	<TABLE>
	<TR>
	<TD BGCOLOR="#BEA279" width="400">
		<FONT FACE="Verdana">
		<P><CENTER><B><FONT SIZE="+1">In the Eyes of Death</FONT></B></CENTER>
		<FONT SIZE="-1">

<P><FONT SIZE="+1"><B>T</B></FONT>he Hall of Lore was seemingly filled to the brim. Seekers of Lore from all over Norrath had come to the gathering outside Freeport. There were at least fifty from each race, even the Barbarians from the cold, harsh lands around their city, Halas. All around him, Multam Weatherlight could see people talking. Multam was a fairly young elf by their standards, being only at the age of eighty-eight. He had brown, scraggly hair and azure blue eyes. He was a Wood Elven Ranger, respectful of nature but not worshipful of it. Multam had no permanent home and usually wandered the fields and forests, foraging what food and water he needed. His polished granite tomahawk and infamous short sword gleamed under the bright glow of the chandeliers as did his banded mail armor. "What do you think this is all about?" he asked his longtime companion Remelio Gemweaver, trying to talk over the chatter but trying not to shout.

<P>"<FONT SIZE="+1"><B>I</B></FONT> don't know, but it must be important," replied the High Elven Enchanter. Remelio was settled on the seat next to Multam, fidgeting nervously. He was wearing a sky blue robe with gold trim around the edges of his sleeves and collar. It had a giant, golden sun imprinted on it near Remelio's chest. He wielded no staff, as he worked his magic better with his hands free. 

<P><FONT SIZE="+1"><B>T</B></FONT>hen, the mighty ruler of the Seekers, Sorontar, stepped up to the podium. Sorontar was a powerful Human. He was cloaked in black robes with intricate red patterns running down a strip of yellow in the front. His mighty staff clonked on the hard wooden floor as he walked and he seemed to radiate energy from his very being (quite possible for a mage of his power). The room was immediately hushed. Sorontar cleared his throat. The sound reverberated throughout the Hall of Lore due to a spell cast by Remelio. He began speaking.

<P>"<FONT SIZE="+1"><B>W</B></FONT>elcome Seekers of Lore! You probably wondered why I have called you all here today. What I have to share is grim news. It affects all of us and everything around us; all of Norrath. But, I will not keep you long, for the news will need to be acted upon immediately." There was a pause, as if all time had stopped. "What I have to share with you is this. The Dark Elves of Neriak have been making an evil plan to-" He stopped short. Sorontar looked down at his chest where an arrow had embedded itself. He then wobbled...and fell to the ground. There were screams of terror and surprise and the deafening noise of everyone getting out of their seats at once.

<P><FONT SIZE="+1"><B>M</B></FONT>ultam got up quickly and spun around to stare at the doorway from which the arrow had come. He saw a blotch of blue, black, and shiny silver dart from the doorway where it had just stood. He shoved through the mobs of people to chase the shadowy figure out of the Hall. When he got out of the door to look around, there was no one there. Only a black bear and a few spiderlings had seen what had come out of the door that day.

<P>"<FONT SIZE="+1"><B>W</B></FONT>e've got to do something about this! We can't just let our leader die and do nothing about it!" screamed Kinsey Tellurian. In her dark blue and silver armor and wielding a GhoulBane, the Half Elven Bard was already imposing enough without her being enraged.

<P>"<FONT SIZE="+1"><B>W</B></FONT>e know, Kinsey. But we don't know what to do about it," replied Aviger Blackmane. Aviger had called together this council two days after the murder of Sorontar. The Seekers present were Multam, Remelio, Kinsey, and Aviger. Aviger was a tall Human Cleric. He looked very dignified in his steel armor and shining mace. Aviger also wore an eye patch over one eye. Everyone wanted to know what had caused him to lose an eye, but no one was brave enough to ask. His fellow guildmates just suspected that it had been during a great battle in his past.

<P><FONT SIZE="+1"><B>M</B></FONT>ultam told his friends about the figure he had seen darting out of the Hall door and suggested, "I say that we go to Neriak and try to find out this dark plan he spoke of. At least that will give us an idea of why someone would have wanted to assassinate Sorontar."

<P>"<FONT SIZE="+1"><B>H</B></FONT>ah," Remelio laughed, "You speak the impossible. How would we ever make it into Neriak?"

<P>"<FONT SIZE="+1"><B>I</B></FONT> don't know, but that seems to be our only choice here...unless any of you can think of a better one?" said Multam grimly. They were silent. "All right then, all who favor going to Neriak say Aye." A few muffled "Aye"s could be heard. "All who oppose?" Silence. "Then it's settled. We shall depart tomorrow at noon. Try to get some rest, for we have a long, hard journey ahead of us."

<P><FONT SIZE="+1"><B>T</B></FONT>he next day, all four travelers were ready. They each had packs full of food and supplies (excluding Multam, who had only other supplies because of his foraging skills). The warriors had polished their armor and the casters (Multam, Aviger, and Remelio could cast spells but Multam was not a true caster and Bard songs are not considered spells by most) practiced their spells. When they were ready and had said goodbye to their fellow Seekers of Lore, they departed across the East Commonlands toward Nektulos Forest.

<P><FONT SIZE="+1"><B>U</B></FONT>sing Multam's tracking skills and acute sense of direction, they made it to the entrance of Nektulos Forest in only three days. They met little resistance besides a few feeble skeletons and orc pawns along the way. The only real danger they had encountered was a camp of hill giants roasting what looked like a kabob of human and dark elf corpses. They were forced to go in a long half-circle around so that they would not be sighted. When they set up camp that day next to Nektulos, they lit a fire and ate some dried fruit and wolf meat they had packed. 

<P><FONT SIZE="+1"><B>A</B></FONT>fter they had finished eating, and Aviger sat back against a tree picking his teeth with a chip of bone from a skeleton, Kinsey sighed and said, "Well, this may be my last chance to sing a song before we enter the dark forest beyond." Remelio glanced toward the evil timberland and shuddered. Kinsey then pulled out a lute from her pack and strummed on it until she had a good beat and began to sing, ...<BR><BR>

<TABLE>
<TR>
<TD BGCOLOR="#BEA279" width="50"></TD>
<TD BGCOLOR="#BEA279" width="300">
<CENTER><I>
"The adventurer traveled across the land,<BR>
Searching far and wide,<BR>
His eyes showed much brave-ery,<BR>
And his heart was filled with pride.<BR><BR>
</I></CENTER>
</TD>
<TD><IMG SRC="http://www.loreseekers.com/graphics/note.jpg" WIDTH=50 HEIGHT=75 ALT="" BORDER="0"></TD>
</TR>
</TABLE>

<TABLE>
<TR>
<TD><IMG SRC="http://www.loreseekers.com/graphics/note.jpg" WIDTH=50 HEIGHT=75 ALT="" BORDER="0"></TD>
<TD BGCOLOR="#BEA279" width="300">
<CENTER><I>
Although he searched the hills and plains,<BR>
And into forest glens,<BR>
He could not find what he sought,<BR>
So he turned back uh-gain.<BR><BR>
</I></CENTER>
</TD>
<TD BGCOLOR="#BEA279" width="50"></TD>
</TR>
</TABLE>

<TABLE>
<TR>
<TD BGCOLOR="#BEA279" width="50"></TD>
<TD BGCOLOR="#BEA279" width="300">
<CENTER><I>
But when he arrived back at home,<BR>
He was very distraught,<BR>
Because it seemed to his dismay,<BR>
That orcs and men had fought.<BR><BR>
</I></CENTER>
</TD>
<TD><IMG SRC="http://www.loreseekers.com/graphics/note.jpg" WIDTH=50 HEIGHT=75 ALT="" BORDER="0"></TD>
</TR>
</TABLE>

<TABLE>
<TR>
<TD><IMG SRC="http://www.loreseekers.com/graphics/note.jpg" WIDTH=50 HEIGHT=75 ALT="" BORDER="0"></TD>
<TD BGCOLOR="#BEA279" width="300">
<CENTER><I>
His village was wrecked,<BR>
And filled with despair,<BR>
But into his house he went,<BR>
Through the hallway and up the stair,<BR>
And life he found naught."<BR><BR>
</I></CENTER>
</TD>
<TD BGCOLOR="#BEA279" width="50"></TD>
</TR>
</TABLE>

<FONT SIZE="+1"><B>S</B></FONT>he sang the last verse a bit slower and quieter...<BR><BR>

<TABLE>
<TR>
<TD BGCOLOR="#BEA279" width="50"></TD>
<TD BGCOLOR="#BEA279" width="300">
<CENTER><I>
"His parents were killed,<BR>
His dwelling destroyed,<BR>
Then he left his abode,<BR>
And with great mis-ery,<BR>
He walked from his village that day..."<BR><BR>
</I></CENTER>
</TD>
<TD><IMG SRC="http://www.loreseekers.com/graphics/note.jpg" WIDTH=50 HEIGHT=75 ALT="" BORDER="0"></TD>
</TR>
</TABLE>

<P><FONT SIZE="+1"><B>K</B></FONT>insey strummed on the lute one more time before ending the song.

<P><FONT SIZE="+1"><B>A</B></FONT>fter a few days of wandering in Nektulos Forest, Multam admitted that they were lost. After camping for the night, Aviger casted a spell that let him sense all of the evil beings around him. The wood itself seemed to be emanating evil, so it was hard to locate any people, but he finally found one. Homing in on its evil aura, the group found a Dark Elven guard wandering the forest. Sneaking up behind him, they knocked him unconscious and took off his helm. When he awoke, they had tied him to a tree and he had Multam's short sword gazing at his neck. "What is your name, swine?" questioned Multam.

<P><FONT SIZE="+1"><B>T</B></FONT>he inky (a nickname for the Dark Elves because of their ink-colored skin) swallowed hard and stated, "My name is Daggerborn. Daggerborn N'Rowan."

<P>"<FONT SIZE="+1"><B>W</B></FONT>hy are you out in the forest? I heard most inkies like you stayed near your death pit, Neriak." asked Multam, his face showing no expression except hatred.

<P>"<FONT SIZE="+1"><B>I</B></FONT>-I was on a mission," he stuttered.

<P>"<FONT SIZE="+1"><B>A </B></FONT>mission? Well so are we. We are looking for the one who killed our leader Sorontar. Might you know of such a scoundrel?"

<P><FONT SIZE="+1"><B>D</B></FONT>aggerborn smiled and laughed evilly. "Yes, I know him well...He is I." And with that, he swung his hand around and bashed Multam with the hilt of the dirk he had cut his binds with. Multam fell to the ground with a thump, unconscious. Daggerborn ducked under a swing from Kinsey's GhoulBane, picked up a large branch from the ground, and smashed the side of her head, putting her unconscious as well. He smiled at Aviger and approached him, but got his leg charred by a fireball from Remelio. Daggerborn screamed from the pain and fell, but struck out with the stick and tripped Remelio, making him fall against a tree and black out. Then, he advanced on Aviger and dodging four swipes from his mace, whacked to the ground the last of the group.

<P><FONT SIZE="+1"><B>W</B></FONT>hen Multam awoke, it appeared to be mid-afternoon of the next day because of the slight lightening of the permanent gloom. Rubbing the swelling bruise on his head, he got up and looked around. His companions were waking up as well. Aviger seemed a bit more dazed than Multam, and Remelio was trying to prop himself up against the tree he had fallen on. But, to their horror, they saw that Kinsey was gone. After a little searching through the underbrush and quite a bit of shouting, they concluded that Daggerborn had dragged Kinsey along with him. Following some scrapes on the ground discovered by Remelio, they walked about two miles before finding a vast mountain with a geometric-shaped hole drilled into it. Above the hole was a carving into the rock of what looked like a bat's head and under it were three guards.

<P>"<FONT SIZE="+1"><B>W</B></FONT>ell," said Multam, "What should we do now?" The other two stood silently, going over their choices.

<P>"<FONT SIZE="+1"><B>W</B></FONT>e could try to sneak in," suggested Remelio.

<P>"<FONT SIZE="+1"><B>N</B></FONT>o," commented Multam, "There are too many guards for us to get very far past the front gate."

<P>"<FONT SIZE="+1"><B>I </B></FONT>know!" yelled Aviger, startling the other two and making him get many "Be quiet you idiot!"s. "Do you still have your Illusion: Dark Elf spell, Remelio?"

<P><FONT SIZE="+1"><B>R</B></FONT>emelio blinked. "Yes, I had forgotten about it completely." He sat and frantically searched through his spell book. "Here it is!" he exclaimed much quieter than Aviger. Remelio stood up and began chanting softly. Blue sparks of light spilled from his open palms as he waved them through the air in intricate patterns. Then there was a flash of light and Remelio's High Elven visage was gone. In his place stood an elf with black-blue tinted skin, white hair, and dark, evil eyes. Remelio smiled. "Now we have a way in."

<P><FONT SIZE="+1"><B>A</B></FONT>fter Remelio had done the same to Multam and Aviger, they walked inside the tunnel and softly killed the three guards to take their armor. Then the companions walked into Neriak and began searching for Daggerborn. Asking a few citizens, they found out that he had taken Kinsey down to the dungeon to be executed. They found their way down into the deep, dark caves that housed the dungeon and started searching the cells. Most of the prisoners were just old, decaying skeletons, obviously forgotten about by the Dark Elves. Then, they found Kinsey. 

<P>"<FONT SIZE="+1"><B>A</B></FONT>re you all right?" whispered Inky-Multam.

<P><FONT SIZE="+1"><B>K</B></FONT>insey spat at the three inkies and said, "Why would you care, dark slime?"

<P>"<FONT SIZE="+1"><B>K</B></FONT>insey, it's us, Remelio illusioned us," said Inky-Aviger. Kinsey was overjoyed and when they had broken her out of the cell, she told them, "I know why the Dark Elves wanted Sorontar dead."

<P>"<FONT SIZE="+1"><B>W</B></FONT>hy?" asked the other three simultaneously. Kinsey then explained the information she had heard from the guards that had locked her up, "It seems that the Dark Elves are planning an attack on Freeport! After they conquer Freeport, they would have access to Faydwer and could go take it over also! It's a world conquest!"

<P>"<FONT SIZE="+1"><B>E</B></FONT>xactly," said Daggerborn, stepping from the shadows, "It is a chain reaction. If one city falls, all of Norrath will fall to the powerful Dark Elves! And I am their ruler. Yes, I am Daggerborn N'Rowan. I am King Daggerborn N'Rowan!"

<P><FONT SIZE="+1"><B>A</B></FONT>fter that, the company of four attacked. They cut, bruised, and gashed him many times (or in the case of the casters, burnt, froze, and ignited him) before he fell to the ground. Daggerborn said, "Even if I die, you are too late. The armies are already on their way toward Freeport! No one will escape the eyes of death!" Then, with blood oozing from his wounds, the murderer of Sorontar perished.

<P><FONT SIZE="+1"><B>W</B></FONT>ith a sense of failure in his voice, Multam uttered, "He's right. We'll never make it back in time."

<P><FONT SIZE="+1"><B>A</B></FONT>t Freeport's gate, the forces of the pure races of Norrath were assembled, ready for war. They knew the onslaught was coming. All of the Seekers of Lore had seen the dungeon battle in their dreams that last night and knew what to do. Courageous were the faces standing there atop the battlements and on the field. The day of judgement had come. And through the trees of the Commonlands appeared the first of the Dark Elven horde. Their evil eyes were grim as they saw the forces of Freeport assembled there. It was quiet in those first few moments, just the clinking of armor and the padding of feet could be heard. Then a great shout rose above it all. "Attack!"

<P><FONT SIZE="+1"><CENTER>The End</FONT>
</FONT>
<BR>
<BR>
<B>Multam Weatherlight,</B><FONT SIZE="-1"> Ranger of Tarew Marr</FONT></CENTER>


	</TD>
	</TR>
	</TABLE>

<TABLE>
<TR>
<TD><A HREF="http://www.loreseekers.com/tales.phtml"><IMG SRC="http://www.loreseekers.com/graphics/tales_return_link.jpg" WIDTH=200 HEIGHT=75 ALT="Read some other stories by our members!" BORDER="0"></A></TD>
</TR>
</TABLE>

	<TD width="64"></TD>
<TR>
	<TD><IMG SRC = "../graphics/botc000.jpg" WIDTH = 63 HEIGHT = 87></TD>
	<TD><IMG SRC = "../graphics/botc001.jpg" WIDTH = 473 HEIGHT = 87></TD>
	<TD><IMG SRC = "../graphics/botc002.jpg" WIDTH = 64 HEIGHT = 87></TD>
</TR>
</TABLE>
<BR>
<IMG SRC="http://service.bfast.com/bfast/serve?bfmid=1375281&siteid=40292692&bfpage=pc" BORDER="0" WIDTH="1" HEIGHT="1" NOSAVE ><A HREF="http://service.bfast.com/bfast/click?bfmid=1375281&siteid=40292692&bfpage=pc" TARGET="_new"><IMG SRC="http://affiliate.gamestop.com/affIMG/pc_120x60.gif" BORDER="0" WIDTH="120" HEIGHT="60" ALT="PC Games at GameStop.com"></A>
<BR>
<BR>
</DIV>
</BODY>
</HTML>