<HTML>

<HEAD>

<TITLE>Fellowship of Justice - An EverQuest Guild</TITLE>

<meta name="Description" content="">
<meta name="keywords" content="foj, fellowship, justice, everquest, eq, guild, ranks, bard, beastlord, cleric, druid, enchanter, magician, mage, monk, necro, necromancer, paladin, ranger, rogue, shadowknight, shadow, knight, warrior, shaman, wizard, norrath, kelethin, history, members, raid, barons, organizer, roster, website, ">

</HEAD>

<BODY bgcolor="black" text="white" link="#FFCC66" alink="#FFCC66" vlink="#FFCC66">

<center>
<img src="FOJ.jpg">
<br>| <a href="http://www.fellowshipofjustice.com">Home</a> | <a href="http://forum.fellowshipofjustice.com">Forum</a> | <a href="roster.php">Members</a> | <a href="contact.php">Submit News</a> | <a href="gdocs.php">Guild Documents</a> |<br><br>
<table width="750" border="1" bordercolor="#CCCCCC" bgcolor="#333333" style="border-collapse:1">
  <tr> 
    <td> <center>

<!-- Generated by newsPHP -->
<!-- http://www.nphp.net/ -->

A New Day Has Arisen.
<B>Friday 13th June, 2003</B><BR><HR width=750px color=#FFCC00><BR>
<A NAME="nPHP1055548153"><B><font color="#0099FF">Guild Hosting!</font></B></A><font size=1> at 16:49 GMT by <A HREF="MAILTO:jc82@mindspring.com">flamewalker</A></font><BR>
<font size=-2>Head on over to <a href="http://www.rpghost.org">http://www.rpghost.org</a> for hosting just for rpg-based guilds, such as this one. Pricing ranges from free to $5/month. <BR><BR>Check it out!<BR></font>
<BR>
<BR><BR>
A New Day Has Arisen.
<B>Sunday 1st June, 2003</B><BR><HR width=750px color=#FFCC00><BR>
<A NAME="nPHP1054528924"><B><font color="#0099FF">Roster is up!</font></B></A><font size=1> at 21:42 GMT by <A HREF="MAILTO:jc82@mindspring.com">flamewalker</A></font><BR>
<font size=-2>FoJ Roster has been created. You can click on `Members` above, or go to www.fellowshipofjustice.com/roster.php . </font>
<BR>
<BR><BR>
<A NAME="nPHP1054516018"><B><font color="#0099FF">Hacked! GRR!</font></B></A><font size=1> at 18:06 GMT by <A HREF="MAILTO:jc82@mindspring.com">flamewalker</A></font><BR>
<font size=-2>Well, I fell victim to a hacker apparently on the 30th of May...found a keylogger on my system. I knew something was wrong when I pressed control-alt-delete and the task manager disappears almost instantly. Tracked the sucker down and terminated the keylogger, deleted it, and moved the keyloggin file and changed all my passwords that were picked up by it. Guess its time for a firewall...</font>
<BR>
<BR><BR>
<A NAME="nPHP1054490871"><B><font color="#0099FF">Guild Roster</font></B></A><font size=1> at 11:07 GMT by <A HREF="MAILTO:jc82@mindspring.com">flamewalker</A></font><BR>
<font size=-2>I will be installing a guild roster system soon.... if I can find a good one. If not, I will write one myself. It should be up within a weeks time or less.<BR><BR>Also, for FoJ members, when you sign up on the new forums, please pm me so I can add you to the FoJ members list. Officers, please pm me as well and I will add you to the Leaders list. And no funny business... I do have a list of members and their status so I will know if you are messing with me or not ;)</font>
<BR>
<BR><BR>
A New Day Has Arisen.
<img src="/cgi-sys/Count.cgi?df=fellow.dat|display=Counter|ft=6|md=5|frgb=100;139;216|dd=A">
      </center></td>
  </tr>
</table>
<center>
<a href="http://www.tstrike.net">ThunderStrike Network</a> | <a href="http://www.rpgtrader.com">RPGTrader</a> | <a href="http://www.rpghost.org">RPGHost</a> | <a href="http://www.journey-soft.com">JourneySoft</a> | <a href="http://www.pcgamersforum.com">PC Gamers' Forum</a> | 

</BODY>

</HTML>