<!--
                 This page has been created by Renaissance IT
   Renaissance Internet Technologies Copyright (c) 1999 All Rights Reserved.

             for more info on our products, please visit :
                        http://www.renaissance.nl/

	This script has been written by Roy Boverhof <rboverhof@renaissance.nl>
	
        Pagename                : npc.html
        Last Updated    		: 27-6-1999
-->

<html>
<head>
	<title>Non Player Characters</title>
</head>

<body BGCOLOR="#000000" TEXT="#000000">
<DIV ALIGN="CENTER">
<BR>
<!-- FGN Banner Code -->
<script language="JavaScript">
	<!-- Hide from old browsers
	var random = new Number(Math.floor(9999999 * Math.random())+1);

	// Modify to reflect site specifics
	page = "eqlore.com/";
	target = "@Top1,x02,x05,x08!Top1";

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript1.1" SRC="http://oascentral.cybereps.com/RealMedia/ads/adstream_jx.ads/' + page + 1 + random + target + '">');
	document.write('</SCR');
	document.write('IPT>');

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript">');
	document.write('_version=10; //-->');
	document.write('</SCR');
	document.write('IPT>');

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript1.1">');
	document.write('_version=11; //-->');
	document.write('</SCR');
	document.write('IPT>');

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript">');

	if (navigator.appVersion.indexOf('MSIE 3') != -1){
	document.write('<IFRAME MARGINWIDTH=0 MARGINHEIGHT=0 HSPACE=0 VSPACE=0 FRAMEBORDER=0 SCROLLING=no BORDERCOLOR="#000000" SRC="oascentral.cybereps.com/RealMedia/ads/adstream_sx.ads/' + page + random + target + '"></IFRAME>');
	  }
	else if (_version < 11) {
	document.write ('<A HREF="http://oascentral.cybereps.com/RealMedia/ads/click_nx.ads/' + page + random + target + '"><IMG SRC="http://oascentral.cybereps.com/RealMedia/ads/adstream_nx.ads/' + page + random + target + '"></a>');
	  }

	document.write('</SCR');
	document.write('IPT>');

	// End Hide -->
</script>
<!-- END FGN Banner Code --><BR>	
<TABLE CELLSPACING = 0 CELLPADDING = 0 BORDER = 0>
<TR>
	<TD width="63"><IMG SRC = "graphics/topc000.jpg" WIDTH = 63 HEIGHT = 87></TD>
	<TD width="473"><IMG SRC = "graphics/topc001.jpg" WIDTH = 473 HEIGHT = 87></TD>
	<TD width="64"><IMG SRC = "graphics/topc002.jpg" WIDTH = 64 HEIGHT = 87></TD>
</TR>
	<TD width="63"></TD>
	<TD BGCOLOR="#BEA279" width="460">
	<DIV ALIGN="CENTER">
	<TABLE WIDTH="460">
<TR>
</TR>
	<TR>
		<TD>
		<DIV ALIGN="CENTER">
		<IMG SRC="graphics/npc_header.jpg" WIDTH=170 HEIGHT=75 ALT="" BORDER="0"><BR><BR>
		<FONT FACE="Arial" SIZE="2" COLOR="#000000">Welcome to the Seekers' list of Non Player Characters ! Here you will find pictures and statistics on all the varied npc's of Norrath.</FONT>

		<BR><BR>
		Just fill in the name of an NPC to search our database.
		<FORM ACTION="npc_search.php3" METHOD="POST"> 
		<INPUT TYPE="Hidden" NAME="action" VALUE="name">
		<TABLE>
		<TR>
			<TD>Name : </TD>
			<TD><INPUT TYPE="text" NAME="search" SIZE="20"></TD>
			<TD><INPUT TYPE="submit" VALUE="Search"></TD>
		</TR>
		</TABLE>
		</FORM>
		<BR>
		<BR>
		Search the descriptions / items they sell.
		<FORM ACTION="npc_search.php3" METHOD="POST">
		<INPUT TYPE="Hidden" NAME="action" VALUE="description">
		<TABLE>
		<TR>
			<TD>Keyword : </TD>
			<TD><INPUT TYPE="text" NAME="search" SIZE="20"></TD>
			<TD><INPUT TYPE="submit" VALUE="Search"></TD>
		</TR>
		</TABLE>
		</FORM>
		<BR>
		<BR>
		Search by zone.
		<FORM ACTION="npc_search.php3" METHOD="POST"> 
		<INPUT TYPE="Hidden" NAME="action" VALUE="zone">
		<TABLE>
		<TR>
			<TD>Zone : </TD>
			<TD>
				<SELECT NAME="search">
				<OPTION VALUE="Antonica">Antonica</OPTION>
				<OPTION VALUE=""></OPTION>
				<OPTION VALUE="HAL">Halas</OPTION>
				<OPTION VALUE="EFT">Everfrost Peaks</OPTION>
				<OPTION VALUE="PRF">Permafrost</OPTION>
				<OPTION VALUE="BBW">Black Burrow</OPTION>
				<OPTION VALUE="BHM">Beholder's Maze</OPTION>
				<OPTION VALUE="GKX">Gorge of King Xorbb</OPTION>
				<OPTION VALUE="RYC">Runneye Citadel</OPTION>
				<OPTION VALUE="MTH">Misty Thicket</OPTION>
				<OPTION VALUE="NAJ">Najena</OPTION>
				<OPTION VALUE="SLA">Solusek's Eye A</OPTION>
				<OPTION VALUE="SLB">Solusek's Eye B</OPTION>
				<OPTION VALUE="LSM">Lavastorm Mountains</OPTION>
				<OPTION VALUE="NRG">Neriak 3rd Gate</OPTION>
				<OPTION VALUE="NRC">Neriak Commons</OPTION>
				<OPTION VALUE="NRQ">Neriak Foriegn Quarters</OPTION>
				<OPTION VALUE="NKF">Nektulos Forrest</OPTION>
				<OPTION VALUE="HKP">High Keep</OPTION>
				<OPTION VALUE="HHP">HighHold Pass</OPTION>
				<OPTION VALUE="RIV">Rivervale</OPTION>
				<OPTION VALUE="KIT">Kithicor Forest</OPTION>
				<OPTION VALUE="EPK">Eastern Plains of Karana</OPTION>
				<OPTION VALUE="WPK">Western Plains of Karana</OPTION>
				<OPTION VALUE="NPK">Northern Plains of Karana</OPTION>
				<OPTION VALUE="SPK">Southern Plains of Karana</OPTION>
				<OPTION VALUE="LOS">Lair of SplitPaw</OPTION>
				<OPTION VALUE="BEF">Befallen</OPTION>
				<OPTION VALUE="WCL">West Commonlands</OPTION>
				<OPTION VALUE="ECL">East Commonlands</OPTION>
				<OPTION VALUE="WFP">West Freeport</OPTION>
				<OPTION VALUE="EFP">East Freeport</OPTION>
				<OPTION VALUE="NFP">North Freeport</OPTION>
				<OPTION VALUE="NDR">Northern Desert of Ro</OPTION>
				<OPTION VALUE="SDR">Southern Desert of Ro</OPTION>
				<OPTION VALUE="OOT">Ocean of Tears</OPTION>
				<OPTION VALUE="SFG">Surefall Glades</OPTION>
				<OPTION VALUE="QEH">Qeynos Hills</OPTION>
				<OPTION VALUE="NQE">North Qeynos</OPTION>
				<OPTION VALUE="SQE">South Qeynos</OPTION>
				<OPTION VALUE="QEC">Qeynos Catacombs</OPTION>
				<OPTION VALUE="ERC">Erud's Crossing</OPTION>
				<OPTION VALUE="LRT">Lake Rathe</OPTION>
				<OPTION VALUE="RTM">Rathe Mountains</OPTION>
				<OPTION VALUE="FRT">Feerott</OPTION>
				<OPTION VALUE="LTT">Lost Temple of Thule</OPTION>
				<OPTION VALUE="OGG">Oggok</OPTION>
				<OPTION VALUE="OOM">Oasis of Marr</OPTION>
				<OPTION VALUE="INS">Innothule Swamp</OPTION>
				<OPTION VALUE="UGK">Upper Guk</OPTION>
				<OPTION VALUE="LGK">Lower Guk</OPTION>
				<OPTION VALUE="GRB">Grobb</OPTION>
				<OPTION VALUE="TSR">Temple of Solusek Ro</OPTION>
				<OPTION VALUE=""></OPTION>
				<OPTION VALUE=""></OPTION>
				<OPTION VALUE="Faydwer">Faydwer</OPTION>
				<OPTION VALUE=""></OPTION>
				<OPTION VALUE="CBN">Crushbone</OPTION>
				<OPTION VALUE="GFD">Greater Faydark</OPTION>
				<OPTION VALUE="LFD">Lesser Faydark</OPTION>
				<OPTION VALUE="NFL">Northern Felwithe</OPTION>
				<OPTION VALUE="SFL">Southern Felwithe</OPTION>
				<OPTION VALUE="CMM">Castle Mistmoore</OPTION>
				<OPTION VALUE="NKD">Northern Kaladim</OPTION>
				<OPTION VALUE="SKD">Southern Kaladim</OPTION>
				<OPTION VALUE="BBM">Butcherblock Mountains</OPTION>
				<OPTION VALUE="DAG">Dagnor's Cauldron</OPTION>
				<OPTION VALUE="KDD">Kedg Dungeon</OPTION>
				<OPTION VALUE="EUN">Estate of Unrest</OPTION>
				<OPTION VALUE="SFM">Steamfont Mountains</OPTION>
				<OPTION VALUE="AKA">Ak'anon</OPTION>
				<OPTION VALUE="OOT">Ocean of Tears</OPTION>
				<OPTION VALUE=""></OPTION>
				<OPTION VALUE=""></OPTION>
				<OPTION VALUE="Odus">Odus</OPTION>
				<OPTION VALUE=""></OPTION>
				<OPTION VALUE="ERU">Erudin</OPTION>
				<OPTION VALUE="ERP">Erudin Palace</OPTION>
				<OPTION VALUE="TXF">Toxxulia Forest</OPTION>
				<OPTION VALUE="ERC">Erud's Crossing</OPTION>
				<OPTION VALUE="KER">Kerra Ridge</OPTION>
				<OPTION VALUE=""></OPTION>
				<OPTION VALUE=""></OPTION>
				<OPTION VALUE="Other">Other</OPTION>
				</SELECT>
			</TD>
			<TD><INPUT TYPE="submit" VALUE="Search"></TD>
		</TR>
		</TABLE>
		</FORM>
		<BR>
		<BR>
		<BR>
		Or click <A HREF="npc_list.php3">here</A> for a complete list of our database.<BR>
		</DIV>
		</TD>
	</TR>
	</TABLE>
	<TD width="64"></TD>
	<TR>
	<TD><IMG SRC = "graphics/botc000.jpg" WIDTH = 63 HEIGHT = 87></TD>
	<TD><IMG SRC = "graphics/botc001.jpg" WIDTH = 473 HEIGHT = 87></TD>
	<TD><IMG SRC = "graphics/botc002.jpg" WIDTH = 64 HEIGHT = 87></TD>
</TR>
</TABLE>
<BR>
<IMG SRC="http://service.bfast.com/bfast/serve?bfmid=1375281&siteid=40292692&bfpage=pc" BORDER="0" WIDTH="1" HEIGHT="1" NOSAVE ><A HREF="http://service.bfast.com/bfast/click?bfmid=1375281&siteid=40292692&bfpage=pc" TARGET="_new"><IMG SRC="http://affiliate.gamestop.com/affIMG/pc_120x60.gif" BORDER="0" WIDTH="120" HEIGHT="60" ALT="PC Games at GameStop.com"></A>
<BR>
<BR>
</DIV>
</body>
</html>
