<HTML>
<HEAD>
<TITLE>Welcome to Media and Games Online Network - MGON</TITLE>
<META name="description" content="MGON - The Gamer's Choice for gaming news. Get the hottest info from the gaming industry.
.">
<META name="keywords" content="MGON, MGO, Interviews, Game previews, Game downloads, Gaming Network, Articles, Gaming News, News, Multiplayer, Games, PC Games, Console Games, Reviews, Forum, MGON International AB, Action, Strategy, Simulation, Roleplay, Racing">
<META name="robots" content="index,follow">
<LINK rel="stylesheet" href="/pagestyle2.css">
<STYLE type="text/css">
<!--
-->
</STYLE>
<script language="JavaScript" type="text/javascript">
<!--
function go(where) {
  if(where != "void" && where!="") location.href = where;
}

function reply(tid,pid,cid,lang) {

  url = "/reply.phtml?tid=" + tid + "&pid=" + pid + "&id=" + cid + "&language=" + lang + '&ref=%2Fpress.phtml';
  ipwindow = open("","prewindow","scrollbars=yes,toolbar=no,height=330,width=400");
  ipwindow.location.href = url;
        
}

function rateit(id,vote) {
    if(vote != "") {
		document.rate.content_id.value = id;
		document.rate.vote.value = vote;
		document.rate.submit();
	}
}

function screenshot(cid,pid) {

  url = "/screenshot.phtml?cid=" + cid + "&pid=" + pid;
  ipwindow = open("","prewindow","scrollbars=yes,toolbar=no,height=630,width=710");
  ipwindow.location.href = url;
        
}

function relatedmedia(url) {

  ipwindow = open("","prewindow","scrollbars=yes,toolbar=no,height=300,width=300");
  ipwindow.location.href = url;
        
}
//-->
</script></HEAD>

<BODY bgcolor="#FFFFFF" text="#000000" link="#000000" vlink="#000000" alink="#000000" leftmargin="0" topmargin="0" marginwidth="0" marginheight="0" background="/images2/backgrounds/resize.gif">
<TABLE width="750" border="0" cellspacing="0" cellpadding="0"><TR><TD><!-- hostname =  -->


<SCRIPT language="JavaScript" type="text/javascript">
<!--
if (window != top) top.location.href = location.href;

     NS4 = (document.layers);
     IE4 = (document.all);
    ver4 = (NS4 || IE4);
     IE5 = (IE4 && navigator.appVersion.indexOf("5.")!=-1);
   isMac = (navigator.appVersion.indexOf("Mac") != -1);
  isMenu = (NS4 || (IE4 && !isMac) || (IE5 && isMac));

function popUp(){return};
function popDown(){return};

if (!ver4) event = null;

//-->
</SCRIPT>
<script language="JavaScript1.2" type="text/javascript">
<!--

if (isMenu) {
    menuVersion = 3;
    
    menuWidth = 100;
    childOverlap = 1;
    childOffset = -109;
    perCentOver = null;
    secondsVisible = .5;
    
    fntCol = "blue";
    fntSiz = "7";
    fntBold = true;
    fntItal = false;
    fntFam = "arial, helvetica";
    
    backCol = "#DDDDDD";
    overCol = "#FFCCCC";
    overFnt = "purple";
    
    borWid = 1;
    borCol = "black";
    borSty = "solid";
    itemPad = 3;
    
    imgSrc = "http://www.mgon.com/images/misc/menuarrow.gif";
    imgSiz = 10;
    
    separator = 1;
    separatorCol = "red";
    
    isFrames = false;      // <-- IMPORTANT for full window
    navFrLoc = "left";     // <-- display. see below
    
    keepHilite = true; 
    NSfontOver = true;
    clickStart = false;
    clickKill = false;
}

//-->
</script>
<SCRIPT language="JavaScript1.2" type="text/javascript">
<!--
if (isMenu) {

  //document.write("<SCRIPT LANGUAGE='JavaScript1.2' SRC='http://www.mgon.com/shared/js/hierArrays.js'><\/SCRIPT>");

arMenu1 = new Array(
105,184,"19",
"white","white",
"#813E09","#FF9216",
"black","black",
"&nbsp;Deus Ex","http://www.deusexcenter.com/common/quickLoginAndRedirect?id=&pw=&ref=/",0,
"&nbsp;Duke Nukem","http://www.dukenukemcenter.com/common/quickLoginAndRedirect?id=&pw=&ref=/",0,
"&nbsp;Elite Force","http://www.eliteforcecenter.com/common/quickLoginAndRedirect?id=&pw=&ref=/",0,
"&nbsp;Half Life","http://www.hlcenter.com/common/quickLoginAndRedirect?id=&pw=&ref=/",0,
"&nbsp;Halo","http://www.halocenter.com/common/quickLoginAndRedirect?id=&pw=&ref=/",0,
"&nbsp;Quake 3","http://www.q3center.com/common/quickLoginAndRedirect?id=&pw=&ref=/",0,
"&nbsp;<i>More Action Sites</i>","#",1
)

arMenu1_7 = new Array(

"&nbsp;Rainbow Six","http://www.rainbowsixcenter.com/common/quickLoginAndRedirect?id=&pw=&ref=/",0,
"&nbsp;Rune","http://www.runecenter.com/common/quickLoginAndRedirect?id=&pw=&ref=/",0,
"&nbsp;Soldier of Fortune","http://www.sofcenter.com/common/quickLoginAndRedirect?id=&pw=&ref=/",0,
"&nbsp;Team Fortress","http://www.fortresscenter.com/common/quickLoginAndRedirect?id=&pw=&ref=/",0,
"&nbsp;StrikeForce","http://www.strikeforcecenter.com/common/quickLoginAndRedirect?id=&pw=&ref=/",0,
"&nbsp;Tribes","http://www.tribescenter.com/common/quickLoginAndRedirect?id=&pw=&ref=/",0,
"&nbsp;<i>More Action Sites</i>","#",1
)

arMenu1_7_7 = new Array(

"&nbsp;Unreal","http://www.unrealcenter.com/common/quickLoginAndRedirect?id=&pw=&ref=/",0,
"&nbsp;Wheel of Time","http://www.wotgame.com/common/quickLoginAndRedirect?id=&pw=&ref=/",0,
"&nbsp;&nbsp;","#",0,
"&nbsp;&nbsp;","#",0,
"&nbsp;&nbsp;","#",0,
"&nbsp;&nbsp;","#",0,
"&nbsp;&nbsp;","#",0
)

arMenu2 = new Array(
105,268,"19",
"white","white",
"#003355","#0078C8",
"black","black",
"&nbsp;Black & White","http://www.bwcenter.com/common/quickLoginAndRedirect?id=&pw=&ref=/",0,
"&nbsp;Dark Reign","http://www.darkreigncenter.com/common/quickLoginAndRedirect?id=&pw=&ref=/",0,
"&nbsp;Ground Control","http://www.gccenter.com/common/quickLoginAndRedirect?id=&pw=&ref=/",0,
"&nbsp;Sacrifice","http://www.sacrificecenter.com/common/quickLoginAndRedirect?id=&pw=&ref=/",0,
"&nbsp;Worms","http://www.wormscenter.com/common/quickLoginAndRedirect?id=&pw=&ref=/",0
)

arMenu3 = new Array(
115,352,"19",
"white","white",
"#A40307","#E80005",
"black","black",
"&nbsp;Baldurs Gate","http://www.baldursgatehaven.com/common/quickLoginAndRedirect?id=&pw=&ref=/",0,
"&nbsp;Diablo","http://www.diablohaven.com/common/quickLoginAndRedirect?id=&pw=&ref=/",0,
"&nbsp;Horizons","http://www.horizonshaven.com/common/quickLoginAndRedirect?id=&pw=&ref=/",0,
"&nbsp;MUD's","http://www.mudcenter.com/common/quickLoginAndRedirect?id=&pw=&ref=/",0,
"&nbsp;Neocron","http://www.neocroncenter.com/common/quickLoginAndRedirect?id=&pw=&ref=/",0,
"&nbsp;Neverwinter &nbsp;Nights","http://www.neverwinterhaven.com/common/quickLoginAndRedirect?id=&pw=&ref=/",0,
"&nbsp;<i>More Roleplay Sites</i>","#",1
)

arMenu3_7 = new Array(

"&nbsp;Throne of Darkness","http://www.todhaven.com/common/quickLoginAndRedirect?id=&pw=&ref=/",0,
"&nbsp;Ultima","http://www.ultimahaven.com/common/quickLoginAndRedirect?id=&pw=&ref=/",0,
"&nbsp;Vampire","http://www.vampirehaven.com/common/quickLoginAndRedirect?id=&pw=&ref=/",0,
"&nbsp;&nbsp;","#",0,
"&nbsp;&nbsp;","#",0,
"&nbsp;&nbsp;","#",0,
"&nbsp;&nbsp;","#",0
)

arMenu4 = new Array(
105,436,"19",
"white","white",
"#004612","#009526",
"black","black",
"&nbsp;CManager","http://www.cmanagercenter.com/common/quickLoginAndRedirect?id=&pw=&ref=/",0,
"&nbsp;Creatures","http://www.homecreatures.com/common/quickLoginAndRedirect?id=&pw=&ref=/",0,
"&nbsp;Pokémon","http://www.pokeball.net/common/quickLoginAndRedirect?id=&pw=&ref=/",0,
"&nbsp;The Sims","http://www.thesimsresource.com/common/quickLoginAndRedirect?id=&pw=&ref=/",0,
"&nbsp;Tycoon","http://www.tycoonresource.com/common/quickLoginAndRedirect?id=&pw=&ref=/",0
)

arMenu5 = new Array(
105,520,"19",
"white","white",
"#383838","#8A8A8A",
"black","black",
"&nbsp;Racing Source","http://www.racingsource.com/common/quickLoginAndRedirect?id=&pw=&ref=/",0,
"&nbsp;Driver","http://www.driverhq.com/common/quickLoginAndRedirect?id=&pw=&ref=/",0
)

arMenu6 = new Array(
105,100,"19",
"white","white",
"#48003F","#B2009C",
"black","black",
"&nbsp;MGON","http://www.mgon.com/common/quickLoginAndRedirect?id=&pw=&ref=/",0,
"&nbsp;MGON - SE","http://se.mgon.com/common/quickLoginAndRedirect?id=&pw=&ref=/",0,
"&nbsp;ESports - Live","http://www.esports-live.com/common/quickLoginAndRedirect?id=&pw=&ref=/",0,
"&nbsp;Nintendo","http://www.nintendocenter.com/common/quickLoginAndRedirect?id=&pw=&ref=/",0,
"&nbsp;Playstation","http://www.playstationcenter.com/common/quickLoginAndRedirect?id=&pw=&ref=/",0,
"&nbsp;Playstation - SE","http://se.playstationcenter.com/common/quickLoginAndRedirect?id=&pw=&ref=/",0
)

arMenu7 = new Array(
105,1,"19",
"white","white",
"#101040","#101090",
"black","black",
"&nbsp;Edit Profile", "javascript:member()",0,
"&nbsp;Logout", "http://everquest.mgon.com/common/logout.phtml?ref=/press.phtml",0
)

arMenu8 = new Array(
105,1,"19",
"white","white",
"#101040","#101090",
"black","black",
"&nbsp;Login","javascript:login()",0,
"&nbsp;New member","javascript:member()",0,
"&nbsp;Forgot it?","javascript:forgotit()",0)

}

//-->
</SCRIPT>
<SCRIPT language="JavaScript1.2" type="text/javascript">
<!--
if (isMenu) {
document.write("<SCRIPT LANGUAGE='JavaScript1.2' SRC='http://www.mgon.com/shared/js/hierMenus.js'><\/SCRIPT>");
}
function logout() {
  location.href = "http://everquest.mgon.com/common/logout.phtml?ref=/press.phtml";
}
function login() {
  ipwindow = open("","Login","scrollbars=no,toolbar=no,height=200,width=240");
  ipwindow.location.href = "http://everquest.mgon.com/common/login.phtml?ref=www.mgon.com&page=/press.phtml";        
}
function forgotit() {
  ipwindow = open("","Login","scrollbars=no,toolbar=no,height=250,width=400");
  ipwindow.location.href = "/common/forgotit.phtml";        
}
function member() {
  ipwindow = open("","Members","scrollbars=yes,toolbar=no,height=600,width=500");
  ipwindow.location.href = "http://everquest.mgon.com/common/members.phtml?ref=www.mgon.com&page=/press.phtml";        
}
//-->
</SCRIPT>
<table width="100%" border="0" cellspacing="0" cellpadding="0" background="/images/network_nav/resize.gif">
  <tr> 
    <td><img src="/images/network_nav/left.gif" width="2" height="20"></td>
    <td><a href="#" onClick="javascript:login()" onMouseOver="popUp('elMenu8',event)" onMouseOut="popDown('elMenu8')"><img src="/images/network_nav/member_login.gif" width="97" height="20" border="0"></a></td>
    <td><a href="#" onMouseOver="popUp('elMenu6',event)" onMouseOut="popDown('elMenu6')"><img src="/images/network_nav/console_new.gif" width="84" height="20" border="0"></a></td>
    <td><a href="#" onMouseOver="popUp('elMenu1',event)" onMouseOut="popDown('elMenu1')"><img src="/images/network_nav/action.gif" width="84" height="20" border="0"></a></td>
    <td><a href="#" onMouseOver="popUp('elMenu2',event)" onMouseOut="popDown('elMenu2')"><img src="/images/network_nav/strategy.gif" width="84" height="20" border="0"></a></td>
    <td><a href="#" onMouseOver="popUp('elMenu3',event)" onMouseOut="popDown('elMenu3')"><img src="/images/network_nav/roleplay.gif" width="84" height="20" border="0"></a></td>
    <td><a href="#" onMouseOver="popUp('elMenu4',event)" onMouseOut="popDown('elMenu4')"><img src="/images/network_nav/simulation.gif" width="84" height="20" border="0"></a></td>
    <td><a href="#" onMouseOver="popUp('elMenu5',event)" onMouseOut="popDown('elMenu5')"><img src="/images/network_nav/racing.gif" width="85" height="20" border="0"></a></td><td width="100%">&nbsp;</td><td><A href="http://www.mgon.com/common/quickLoginAndRedirect?id=&pw=&ref=/"><img src="/images/network_nav/network.gif" width="144" height="20" border="0"></A></td>
  </tr>
</table>
<script language="javascript">
var compname='Ad/mgon';
</script>
<script language="javascript" src="http://www.rankyou.com/cpt_transfers/single_month_enter.js">
</script></TD></TR></TABLE>

<TABLE width="750" border="0" cellspacing="0" cellpadding="0">

  <TR> 

    <TD><IMG src="/images2/top/topleft.jpg" width="152" height="136" border="0" usemap="#Map"><MAP name="Map"><AREA shape="rect" coords="13,36,138,76" href="http://www.mgon.com" alt="MGON Home" title="MGON Home"></MAP></TD>

    <TD width="100%" background="/images2/top/resize.jpg"><IMG src="/images2/top/logo.jpg" width="455" height="136"></TD>

    <TD align="center"><IMG src="/images2/top/topright.jpg" width="142" height="136"></TD>

  </TR>

</TABLE>


<TABLE width="750" border="0" cellspacing="0" cellpadding="0" bgcolor="#000000">
	<TR> 
		<TD align="center" width="130"> 
			<TABLE width="100%" border="0" cellspacing="0" cellpadding="0">
				<TR> 
					<TD align="center" background="/images2/top/channelresize.gif"><OBJECT classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=4,0,2,0" width="120" height="60">
							<PARAM name=movie value="http://www.mgon.com/flashmovies/mgochannel2.swf">
							<PARAM name=quality value=high>
							<PARAM name="menu" value="false">
							<EMBED src="http://www.mgon.com/flashmovies/mgochannel2.swf" quality=high pluginspage="http://www.macromedia.com/shockwave/download/index.cgi?P1_Prod_Version=ShockwaveFlash" 
type="application/x-shockwave-flash" menu="false" width="120" height="60">
							</EMBED> 
						</OBJECT></TD>
				</TR>
				<TR> 
					<TD><IMG src="/images/top/channelbottom.gif" width="130" height="13"></TD>
				</TR>
			</TABLE>
		</TD>
		
    <TD align="center" width="490" valign="top"> 
      <span class="smalltext"><NOLAYER><IFRAME SRC="http://ad.se.doubleclick.net/adi/mgon.com/;sz=468x60;ord=981209766?" bgcolor="#000000" width="468" height="60" frameborder="no" border="0" MARGINWIDTH="0" MARGINHEIGHT="0" SCROLLING="no"><A HREF="http://ad.se.doubleclick.net/jump/mgon.com/;abr=!ie;sz=468x60;ord=981209766?"><IMG SRC="http://ad.se.doubleclick.net/ad/mgon.com/;abr=!ie;sz=468x60;ord=981209766?" border="0" height="60" width="468"></A></IFRAME></NOLAYER><ILAYER id="layer1" visibility="hidden" width="468" height="60" align="center"></ILAYER></span>    </TD>
		
    <TD width="130" align="center" valign="top"><IMG
SRC="http://service.bfast.com/bfast/serve?bfmid=1375281&siteid=34593362&bfpa
ge=pc" BORDER="0" WIDTH="1" HEIGHT="1" NOSAVE > <A
HREF="http://service.bfast.com/bfast/click?bfmid=1375281&siteid=34593362&bfp
age=pc" TARGET="_top"><IMG
SRC="http://affiliate.gamestop.com/affimg/120_pc3_gs.gif" BORDER="0"
WIDTH="120" HEIGHT="60" ALT="PC titles from Gamestop.com"></A></TD>
	</TR>
</TABLE>
 
<TABLE width="750" border="0" cellspacing="0" cellpadding="0">
  <TR> 
    <TD valign="top" width="130" align="center"> 
       
<TABLE width="130" border="0" cellspacing="0" cellpadding="0">
  <TR> 
    <TD><IMG src="/images2/buttons/sitecontent.gif" width="130" height="25"></TD>
  </TR>
</TABLE>
<table width="130" border="0" cellspacing="0" cellpadding="0">
  <tr bgcolor="#000E24"> 
    <td> 
      <table width="100%" border=0 cellpadding=0 cellspacing=1>
        <tr bgcolor="#000E24"> 
          <td style="border='1 solid #809ECB'" onMouseOver="style.backgroundColor='#809ECB'; style.cursor='hand'; style.border='1 solid #809ECB'" onMouseOut="style.backgroundColor='#000E24'; style.border='1 solid #809ECB';" height="21"> 
            <table width="100%" border="0" cellspacing="0" cellpadding="2">
              <tr> 
                <td bgcolor="#000E24" height="21" width="100%"><a href="/" class="navlinks" style="margin:0;"> 
                  <div><img src="/images2/misc/1pix.gif" width="1" height="1" border="0">&nbsp;<span class="navlinks">Home</span></div>
                  </a></td>
                <td class="Bolded"><font size="2" face="Verdana, Arial, Helvetica, sans-serif" color="#000E24">&laquo;</font></td>
              </tr>
            </table>
          </td>
        </tr>
        <tr bgcolor="#000E24"> 
          <td style="border='1 solid #809ECB'" onMouseOver="style.backgroundColor='#809ECB'; style.cursor='hand'; style.border='1 solid #809ECB'" onMouseOut="style.backgroundColor='#000E24'; style.border='1 solid #809ECB';" height="21"> 
            <table width="100%" border="0" cellspacing="0" cellpadding="2">
              <tr> 
                <td bgcolor="#000E24" height="21" width="100%"><a href="/news.phtml" class="navlinks" style="margin:0;"> 
                  <div><img src="/images2/misc/1pix.gif" width="1" height="1" border="0">&nbsp;<span class="navlinks">News</span></div>
                  </a></td>
                <td class="Bolded"><font size="2" face="Verdana, Arial, Helvetica, sans-serif" color="#000E24">&laquo;</font></td>
              </tr>
            </table>
          </td>
        </tr>
        <tr bgcolor="#000E24"> 
          <td style="border='1 solid #809ECB'" onMouseOver="style.backgroundColor='#809ECB'; style.cursor='hand'; style.border='1 solid #809ECB'" onMouseOut="style.backgroundColor='#000E24'; style.border='1 solid #809ECB';" height="21"> 
            <table width="100%" border="0" cellspacing="0" cellpadding="2">
              <tr> 
                <td bgcolor="#000E24" height="21" width="100%"><a href="/reviewindex.phtml" class="navlinks" style="margin:0;"> 
                  <div><img src="/images2/misc/1pix.gif" width="1" height="1" border="0">&nbsp;<span class="navlinks">Reviews</span></div>
                  </a></td>
                <td class="Bolded"><font size="2" face="Verdana, Arial, Helvetica, sans-serif" color="#000E24">&laquo;</font></td>
              </tr>
            </table>
          </td>
        </tr>
        <tr bgcolor="#000E24"> 
          <td style="border='1 solid #809ECB'" onMouseOver="style.backgroundColor='#809ECB'; style.cursor='hand'; style.border='1 solid #809ECB'" onMouseOut="style.backgroundColor='#000E24'; style.border='1 solid #809ECB';" height="21"> 
            <table width="100%" border="0" cellspacing="0" cellpadding="2">
              <tr> 
                <td bgcolor="#000E24" height="21" width="100%"><a href="/previewindex.phtml" class="navlinks" style="margin:0;"> 
                  <div><img src="/images2/misc/1pix.gif" width="1" height="1" border="0">&nbsp;<span class="navlinks">Previews</span></div>
                  </a></td>
                <td class="Bolded"><font size="2" face="Verdana, Arial, Helvetica, sans-serif" color="#000E24">&laquo;</font></td>
              </tr>
            </table>
          </td>
        </tr>
        <tr bgcolor="#000E24"> 
          <td style="border='1 solid #809ECB'" onMouseOver="style.backgroundColor='#809ECB'; style.cursor='hand'; style.border='1 solid #809ECB'" onMouseOut="style.backgroundColor='#000E24'; style.border='1 solid #809ECB';" height="21"> 
            <table width="100%" border="0" cellspacing="0" cellpadding="2">
              <tr> 
                <td bgcolor="#000E24" height="21" width="100%"><a href="/interviewindex.phtml" class="navlinks" style="margin:0;"> 
                  <div><img src="/images2/misc/1pix.gif" width="1" height="1" border="0">&nbsp;<span class="navlinks">Interviews</span></div>
                  </a></td>
                <td class="Bolded"><font size="2" face="Verdana, Arial, Helvetica, sans-serif" color="#000E24">&laquo;</font></td>
              </tr>
            </table>
          </td>
        </tr>

        <tr bgcolor="#000E24"> 
          <td style="border='1 solid #809ECB'" onMouseOver="style.backgroundColor='#809ECB'; style.cursor='hand'; style.border='1 solid #809ECB'" onMouseOut="style.backgroundColor='#000E24'; style.border='1 solid #809ECB';" height="21"> 
            <table width="100%" border="0" cellspacing="0" cellpadding="2">
              <tr> 
                <td bgcolor="#000E24" height="21" width="100%"><a href="/articleindex.phtml" class="navlinks" style="margin:0;"> 
                  <div><img src="/images2/misc/1pix.gif" width="1" height="1" border="0">&nbsp;<span class="navlinks">Articles</span></div>
                  </a></td>
                <td class="Bolded"><font size="2" face="Verdana, Arial, Helvetica, sans-serif" color="#000E24">&laquo;</font></td>
              </tr>
            </table>
          </td>
        </tr>
        <tr bgcolor="#000E24"> 
          <td style="border='1 solid #809ECB'" onMouseOver="style.backgroundColor='#809ECB'; style.cursor='hand'; style.border='1 solid #809ECB'" onMouseOut="style.backgroundColor='#000E24'; style.border='1 solid #809ECB';" height="21"> 
            <table width="100%" border="0" cellspacing="0" cellpadding="2">
              <tr> 
                <td bgcolor="#000E24" height="21" width="100%"><a href="/fileindex.phtml" class="navlinks" style="margin:0;"> 
                  <div><img src="/images2/misc/1pix.gif" width="1" height="1" border="0">&nbsp;<span class="navlinks">Downloads</span></div>
                  </a></td>
                <td class="Bolded"><font size="2" face="Verdana, Arial, Helvetica, sans-serif" color="#000E24">&laquo;</font></td>
              </tr>
            </table>
          </td>
        </tr>
        <tr bgcolor="#000E24"> 
          <td style="border='1 solid #809ECB'" onMouseOver="style.backgroundColor='#809ECB'; style.cursor='hand'; style.border='1 solid #809ECB'" onMouseOut="style.backgroundColor='#000E24'; style.border='1 solid #809ECB';" height="21"> 
            <table width="100%" border="0" cellspacing="0" cellpadding="2">
              <tr> 
                <td bgcolor="#000E24" height="21" width="100%"><a href="http://www.mgoforum.com/" class="navlinks" style="margin:0;"> 
                  <div><img src="/images2/misc/1pix.gif" width="1" height="1" border="0">&nbsp;<span class="navlinks">MGON 
                    Forum</span></div>
                  </a></td>
                <td class="Bolded"><font size="2" face="Verdana, Arial, Helvetica, sans-serif" color="#000E24">&laquo;</font></td>
              </tr>
            </table>
          </td>
        </tr>
      </table>
    </td>
  </tr>
</table>
<TABLE width="130" border="0" cellspacing="0" cellpadding="0">
  <TR> 
    <TD><IMG src="/images2/buttons/siteinfo.gif" width="130" height="25"></TD>
  </TR>
</TABLE>
<table width="130" border="0" cellspacing="0" cellpadding="0">
  <tr bgcolor="#000E24"> 
    <td> 
      <table width="100%" border=0 cellpadding=0 cellspacing=1>
        <tr bgcolor="#000E24"> 
          <td style="border='1 solid #809ECB'" onMouseOver="style.backgroundColor='#809ECB'; style.cursor='hand'; style.border='1 solid #809ECB'" onMouseOut="style.backgroundColor='#000E24'; style.border='1 solid #809ECB';" height="21"> 
            <table width="100%" border="0" cellspacing="0" cellpadding="2">
              <tr> 
                <td bgcolor="#000E24" height="21" width="100%"><a href="/company/" class="navlinks" style="margin:0;"> 
                  <div><img src="/images2/misc/1pix.gif" width="1" height="1" border="0">&nbsp;<span class="navlinks">The 
                    Company</span></div>
                  </a></td>
                <td class="Bolded"><font size="2" face="Verdana, Arial, Helvetica, sans-serif" color="#000E24">&laquo;</font></td>
              </tr>
            </table>
          </td>
        </tr>
        <tr bgcolor="#000E24"> 
          <td style="border='1 solid #809ECB'" onMouseOver="style.backgroundColor='#809ECB'; style.cursor='hand'; style.border='1 solid #809ECB'" onMouseOut="style.backgroundColor='#000E24'; style.border='1 solid #809ECB';" height="21"> 
            <table width="100%" border="0" cellspacing="0" cellpadding="2">
              <tr> 
                <td bgcolor="#000E24" height="21" width="100%"><a href="/mediakit/" class="navlinks" style="margin:0;"> 
                  <div><img src="/images2/misc/1pix.gif" width="1" height="1" border="0">&nbsp;<span class="navlinks">Our 
                    Mediakit</span></div>
                  </a></td>
                <td class="Bolded"><font size="2" face="Verdana, Arial, Helvetica, sans-serif" color="#000E24">&laquo;</font></td>
              </tr>
            </table>
          </td>
        </tr>
        <tr bgcolor="#000E24"> 
          <td style="border='1 solid #809ECB'" onMouseOver="style.backgroundColor='#809ECB'; style.cursor='hand'; style.border='1 solid #809ECB'" onMouseOut="style.backgroundColor='#000E24'; style.border='1 solid #809ECB';" height="21"> 
            <table width="100%" border="0" cellspacing="0" cellpadding="2">
              <tr> 
                <td bgcolor="#000E24" height="21" width="100%"><a href="/press.phtml" class="navlinks" style="margin:0;"> 
                  <div><img src="/images2/misc/1pix.gif" width="1" height="1" border="0">&nbsp;<span class="navlinks">Press 
                    Material</span></div>
                  </a></td>
                <td class="Bolded"><font size="2" face="Verdana, Arial, Helvetica, sans-serif" color="#000E24">&laquo;</font></td>
              </tr>
            </table>
          </td>
        </tr>
        <tr bgcolor="#000E24"> 
          <td style="border='1 solid #809ECB'" onMouseOver="style.backgroundColor='#809ECB'; style.cursor='hand'; style.border='1 solid #809ECB'" onMouseOut="style.backgroundColor='#000E24'; style.border='1 solid #809ECB';" height="21"> 
            <table width="100%" border="0" cellspacing="0" cellpadding="2">
              <tr> 
                <td bgcolor="#000E24" height="21" width="100%"><a href="/contactus/" class="navlinks" style="margin:0;"> 
                  <div><img src="/images2/misc/1pix.gif" width="1" height="1" border="0">&nbsp;<span class="navlinks">Contact 
                    Us</span></div>
                  </a></td>
                <td class="Bolded"><font size="2" face="Verdana, Arial, Helvetica, sans-serif" color="#000E24">&laquo;</font></td>
              </tr>
            </table>
          </td>
        </tr>
      </table>
    </td>
  </tr>
</table>    
<TABLE width="122" border="0" cellspacing="0" cellpadding="1" bgcolor="#000000" background="/images/misc/50x50pix.gif">
  <TR align="center"> 
          <TD><IMG SRC="http://service.bfast.com/bfast/serve?bfmid=1307357&siteid=36766142&bfpage=1" BORDER="0" WIDTH="1" HEIGHT="1" NOSAVE ><BR>
<A HREF="http://service.bfast.com/bfast/click?bfmid=1307357&siteid=36766142&bfpage=1" TARGET="_top">
<IMG SRC="http://www.gator.com/images/banners/gator_tired_120x90.gif" BORDER="0" WIDTH="120" HEIGHT="90" ALT="Gator fills out forms and remembers passwords!"></A><!--index: 1 num: 5 --></TD>
        </TR>
      </TABLE>
    </TD>
    <TD width="620" valign="top"> 
      <TABLE width="100%" border="0" cellspacing="0" cellpadding="0" background="/images2/sections/resize.gif">
        <TR> 
          <TD><IMG src="/images2/misc/1pixblack.gif" width="1" height="63"></TD>
          <TD width="100%" valign="bottom"> 
            <TABLE width="100%" border="0" cellspacing="0" cellpadding="0" background="/images2/misc/50x50pix.gif">
              <TR> 
                <TD height="28"><SPAN class="Bolded"><IMG src="/images2/misc/1pix.gif" width="11" height="1"></SPAN></TD>
              </TR>
            </TABLE>
          </TD>
          <TD align="right"><IMG src="/images2/sections/press.gif" width="275" height="63"></TD>
        </TR>
      </TABLE>
      <table width="100%" border="0" cellspacing="0" cellpadding="0" background="/images2/buttons/resize.gif">
        <tr> 
          <td height="25"><img src="/images2/misc/1pixblack.gif" width="1" height="25"></td>
        </tr>
      </table>
      <TABLE width="100%" border="0" cellspacing="0" cellpadding="0">
        <TR> 
          <TD width="100%"> 
            <TABLE width="100%" border="0" cellspacing="0" cellpadding="11">
        <TR>
          <TD width="100%"> 
            <P><SPAN class="Headline">MGON opens Throne of Darkness&#8482;  Haven and Neverwinter Haven</SPAN><BR><SPAN class="Bolded">Location:</SPAN> Söderhamn, SWEDEN&nbsp;<SPAN class="Bolded">Date:</SPAN> 18/12/01 
			<P><SPAN class="normal"><i><A HREF="http://www.mgon.com/">Media and Games Online Network</A>, a leading internet games and entertainment portal, announced today the official opening of Throne of Darkness&#8482; Haven and Neverwinter Haven.</i><BR><P><SPAN class="smalltext"> [ <A href="/press.phtml?id=49461&language=en">Read the press release...</A> ]</SPAN></P></SPAN></p>
            <P>
            <TABLE width="100%" border="0" cellspacing="1" cellpadding="0">
              <TR> 
                <TD height="20" bgcolor="#001F39" width="100%">&nbsp;&nbsp;<A href="#top">Top of page</A> | <A href="/press.phtml">Press archive</A></TD>
              </TR>
            </TABLE>
</TD></TR></TABLE><TABLE width="100%" border="0" cellspacing="0" cellpadding="11">
        <TR>
          <TD width="100%"> 
            <P><SPAN class="Headline">MGON announces sponsorship of QIL4 finals</SPAN><BR><SPAN class="Bolded">Location:</SPAN> St. Louis, IL, USA&nbsp;<SPAN class="Bolded">Date:</SPAN> 12/02/01
			<P><SPAN class="normal"><i><A HREF="http://www.mgon.com/">Media and Games Online Network </A>, a leading internet games and entertainment portal, announced today the sponsorship of the Quake Invitational League 4 (QIL4) finals taking place in St. Louis, IL this weekend (12-14 Jan 2001) and exclusive coverage of the event through <A HREF="http://www.esports-live.com/">Esports-Live</A>.</i><BR><P><SPAN class="smalltext"> [ <A href="/press.phtml?id=48229&language=en">Read the press release...</A> ]</SPAN></P></SPAN></p>
            <P>
            <TABLE width="100%" border="0" cellspacing="1" cellpadding="0">
              <TR> 
                <TD height="20" bgcolor="#001F39" width="100%">&nbsp;&nbsp;<A href="#top">Top of page</A> | <A href="/press.phtml">Press archive</A></TD>
              </TR>
            </TABLE>
</TD></TR></TABLE><TABLE width="100%" border="0" cellspacing="0" cellpadding="11">
        <TR>
          <TD width="100%"> 
            <P><SPAN class="Headline">MGON partners WebTop in new Game Zone move</SPAN><BR><SPAN class="Bolded">Location:</SPAN> Söderhamn, SWEDEN&nbsp;<SPAN class="Bolded">Date:</SPAN> 04/01/01
			<P><SPAN class="normal"><i>Over a million gamers a month visiting the <a href="http://www.mgon.com/">Media and Games Online Network</a> will soon be able to search the web even more effectively for all the latest news, reviews, hints and deals concerning PC, Playstation, Nintendo, Sega and more, following the company&#8217;s new partnership with <a href="http://www.webtop.com/">WebTop</a>, the Cambridge-based Internet search solutions company.</i><BR><P><SPAN class="smalltext"> [ <A href="/press.phtml?id=46399&language=en">Read the press release...</A> ]</SPAN></P></SPAN></p>
            <P>
            <TABLE width="100%" border="0" cellspacing="1" cellpadding="0">
              <TR> 
                <TD height="20" bgcolor="#001F39" width="100%">&nbsp;&nbsp;<A href="#top">Top of page</A> | <A href="/press.phtml">Press archive</A></TD>
              </TR>
            </TABLE>
</TD></TR></TABLE><TABLE width="100%" border="0" cellspacing="0" cellpadding="11">
        <TR>
          <TD width="100%"> 
            <P><SPAN class="Headline">Media and Games Online Network and PS2City announce the launch of PlaystationCenter.com</SPAN><BR><SPAN class="Bolded">Location:</SPAN> Söderhamn, SWEDEN&nbsp;<SPAN class="Bolded">Date:</SPAN> 07/12/00
			<P><SPAN class="normal"><i>&#8211; <a href="http://www.mgon.com/">Media and Games Online Network</a>, a leading internet games and entertainment portal, and <a href="http://www.ps2city.com/">PS2City</a> announced today the launch of <a href="http://www.playstationcenter.com/">Playstation Center</a>.</i><BR><P><SPAN class="smalltext"> [ <A href="/press.phtml?id=42322&language=en">Read the press release...</A> ]</SPAN></P></SPAN></p>
            <P>
            <TABLE width="100%" border="0" cellspacing="1" cellpadding="0">
              <TR> 
                <TD height="20" bgcolor="#001F39" width="100%">&nbsp;&nbsp;<A href="#top">Top of page</A> | <A href="/press.phtml">Press archive</A></TD>
              </TR>
            </TABLE>
</TD></TR></TABLE><TABLE width="100%" border="0" cellspacing="0" cellpadding="11">
        <TR>
          <TD width="100%"> 
            <P><SPAN class="Headline">Media and Games Online Network opens Neocron Center and SacrificeCenter</SPAN><BR><SPAN class="Bolded">Location:</SPAN> Söderhamn, SWEDEN&nbsp;<SPAN class="Bolded">Date:</SPAN> 20/11/00
			<P><SPAN class="normal"><i><a href="http://www.mgon.com/">Media and Games Online Network</a>, a leading internet games and entertainment portal, announced today the official launch of <a href="http://www.neocroncenter.com/">Neocron Center</a> and <a href="http://www.sacrificecenter.com/">Sacrifice Center</a>.<br>
<br>
</i><BR><P><SPAN class="smalltext"> [ <A href="/press.phtml?id=40301&language=en">Read the press release...</A> ]</SPAN></P></SPAN></p>
            <P>
            <TABLE width="100%" border="0" cellspacing="1" cellpadding="0">
              <TR> 
                <TD height="20" bgcolor="#001F39" width="100%">&nbsp;&nbsp;<A href="#top">Top of page</A> | <A href="/press.phtml">Press archive</A></TD>
              </TR>
            </TABLE>
</TD></TR></TABLE><TABLE width="100%" border="0" cellspacing="0" cellpadding="11">
        <TR>
          <TD width="100%"> 
            <P><SPAN class="Headline">Media and Games Online Network announces the launch of Tycoon Resource</SPAN><BR><SPAN class="Bolded">Location:</SPAN> Söderhamn; SWEDEN&nbsp;<SPAN class="Bolded">Date:</SPAN> 01/11/00
			<P><SPAN class="normal"><i><a href="http://www.mgon.com/">Media and Games Online Network</a>, a leading internet games and entertainment portal, announced today the official launch of <a href="http://www.tycoonresource.com/">Tycoon Resource</a>.</i><BR><P><SPAN class="smalltext"> [ <A href="/press.phtml?id=38151&language=en">Read the press release...</A> ]</SPAN></P></SPAN></p>
            <P>
            <TABLE width="100%" border="0" cellspacing="1" cellpadding="0">
              <TR> 
                <TD height="20" bgcolor="#001F39" width="100%">&nbsp;&nbsp;<A href="#top">Top of page</A> | <A href="/press.phtml">Press archive</A></TD>
              </TR>
            </TABLE>
</TD></TR></TABLE><TABLE width="100%" border="0" cellspacing="0" cellpadding="11">
        <TR>
          <TD width="100%"> 
            <P><SPAN class="Headline">Media and Games Online Network announces the opening of four new websites</SPAN><BR><SPAN class="Bolded">Location:</SPAN> Söderhamn, SWEDEN&nbsp;<SPAN class="Bolded">Date:</SPAN> 10/10/00
			<P><SPAN class="normal"><i><a href="http://www.mgon.com">Media and Games Online Network</a>, a leading internet games and entertainment portal, announced today the official launch of <a href="http://www.baldursgatehaven.com">Baldurs Gate Haven</a>, <a href="http://www.bwcenter.com">Black&White Center</a>, <a href="http://www.eliteforcecenter.com">Elite Force Center</a> and <a href="http://www.tribescenter.com">Tribes Center</a>.</i><BR><P><SPAN class="smalltext"> [ <A href="/press.phtml?id=35479&language=en">Read the press release...</A> ]</SPAN></P></SPAN></p>
            <P>
            <TABLE width="100%" border="0" cellspacing="1" cellpadding="0">
              <TR> 
                <TD height="20" bgcolor="#001F39" width="100%">&nbsp;&nbsp;<A href="#top">Top of page</A> | <A href="/press.phtml">Press archive</A></TD>
              </TR>
            </TABLE>
</TD></TR></TABLE><TABLE width="100%" border="0" cellspacing="0" cellpadding="11">
        <TR>
          <TD width="100%"> 
            <P><SPAN class="Headline">Media and Games Online Network announces a sponsorship deal with Clan Stickmen</SPAN><BR><SPAN class="Bolded">Location:</SPAN> Söderhamn, SWEDEN&nbsp;<SPAN class="Bolded">Date:</SPAN> 14/09/00
			<P><SPAN class="normal"><i><a href="http://www.mgon.com">Media and Games Online Network</a>, a leading internet games and entertainment portal, announced today a sponsorship agreement with <a href="http://www.thestickmen.com">Clan Stickmen</a>, the world renowned Quake3 clan. </i><BR><P><SPAN class="smalltext"> [ <A href="/press.phtml?id=32897&language=en">Read the press release...</A> ]</SPAN></P></SPAN></p>
            <P>
            <TABLE width="100%" border="0" cellspacing="1" cellpadding="0">
              <TR> 
                <TD height="20" bgcolor="#001F39" width="100%">&nbsp;&nbsp;<A href="#top">Top of page</A> | <A href="/press.phtml">Press archive</A></TD>
              </TR>
            </TABLE>
</TD></TR></TABLE><TABLE width="100%" border="0" cellspacing="0" cellpadding="11">
        <TR>
          <TD width="100%"> 
            <P><SPAN class="Headline">Media and Games Online Network announces the launch of NintendoCenter.com</SPAN><BR><SPAN class="Bolded">Location:</SPAN> Söderhamn, SWEDEN&nbsp;<SPAN class="Bolded">Date:</SPAN> 04/09/00
			<P><SPAN class="normal"><i>Media and Games Online Network, a leading internet games and entertainment portal, announced today the official opening of <a href="http://www.nintendocenter.com">NintendoCenter.com</a>.</i><BR><P><SPAN class="smalltext"> [ <A href="/press.phtml?id=31842&language=en">Read the press release...</A> ]</SPAN></P></SPAN></p>
            <P>
            <TABLE width="100%" border="0" cellspacing="1" cellpadding="0">
              <TR> 
                <TD height="20" bgcolor="#001F39" width="100%">&nbsp;&nbsp;<A href="#top">Top of page</A> | <A href="/press.phtml">Press archive</A></TD>
              </TR>
            </TABLE>
</TD></TR></TABLE><TABLE width="100%" border="0" cellspacing="0" cellpadding="11">
        <TR>
          <TD width="100%"> 
            <P><SPAN class="Headline">Media and Games Online Network announces a Swedish version of the award-winning &#8220;The Sims Resource&#8221;</SPAN><BR><SPAN class="Bolded">Location:</SPAN> Söderhamn, SWEDEN&nbsp;<SPAN class="Bolded">Date:</SPAN> 21/08/00
			<P><SPAN class="normal"><i>Media and Games Online Network, a leading internet games and entertainment portal, announced today the official opening of a Swedish mirror site for the award-winning <a href ="http://se.thesimsresource.com">"The Sims Resource."</a></i><BR><P><SPAN class="smalltext"> [ <A href="/press.phtml?id=30038&language=en">Read the press release...</A> ]</SPAN></P></SPAN></p>
            <P>
            <TABLE width="100%" border="0" cellspacing="1" cellpadding="0">
              <TR> 
                <TD height="20" bgcolor="#001F39" width="100%">&nbsp;&nbsp;<A href="#top">Top of page</A> | <A href="/press.phtml">Press archive</A></TD>
              </TR>
            </TABLE>
</TD></TR></TABLE>
          <p>&nbsp;</p></TD>
        </TR>
      </TABLE>
    </TD>
  </TR>
</TABLE>
 
<TABLE width="750" border="0" cellspacing="0" cellpadding="0">
  <TR> 
    <TD><IMG src="/images2/bottom/copyright.gif" width="340" height="30" border="0"><A href="/privacy.phtml"><IMG src="/images2/bottom/privacy.gif" width="101" height="30" border="0"></A></TD>
    <TD><IMG src="/images2/bottom/bottomplate.gif" width="177" height="30"></TD>
    <TD><A href="#top"><IMG src="/images2/bottom/top.gif" width="68" height="30" border="0"></A></TD>
    <TD><A href="/index.phtml"><IMG src="/images2/bottom/home.gif" width="64" height="30" border="0"></A></TD>
  </TR>
</TABLE>
<TABLE width="750" border="0" cellspacing="0" cellpadding="0" height="90" background="/images2/misc/50x50pix.gif">
  <TR bgcolor="#000000" align="center"> 
    <TD class="smalltext">
      <SCRIPT language="JavaScript"
src="http://adtegrity.spinbox.net/?DC=Mgon+Bottom&JS=Y&TARGET=_new">
</SCRIPT>
      <NOSCRIPT><A href="http://adtegrity.spinbox.net/?SHT=Mgon+Bottom" target="_new"
height="468" width="60"><IMG src="http://adtegrity.spinbox.net/?SIT=Mgon+Bottom" border="0"></A></NOSCRIPT></TD>
  </TR>
</TABLE>
<!--Bottom Layer-->
<LAYER SRC="http://ad.se.doubleclick.net/adl/mgon.com/;sz=468x60;ord=981209766?" bgcolor="#000000" width="468" height="60" visibility="hidden" onLoad="moveToAbsolute(layer1.pageX,layer1.pageY);clip.height=60;clip.width=468; visibility='show';"></LAYER><!--End Bottom Layer--></BODY>

</HTML>


