<!--
                 This page has been created by Renaissance IT
   Renaissance Internet Technologies Copyright (c) 1999 All Rights Reserved.

             for more info on our products, please visit :
                        http://www.renaissance.nl/

	This script has been written by Roy Boverhof <rboverhof@renaissance.nl>
	
        Pagename                : rok_screenshots.html
        Last Updated    		: 04-05-2000
-->

<HTML>
<HEAD>
	<TITLE>the Seekers of Lore : RoK™ Screenshots</TITLE>
</HEAD>

<BODY BGCOLOR="#000000" TEXT="#000000" LINK="#000000" VLINK="#000000" ALINK="#000000">
<DIV ALIGN="CENTER">
<BR>
<script type="text/javascript"><!--
google_ad_client = "pub-0988179937943699";
google_ad_width = 468;
google_ad_height = 60;
google_ad_format = "468x60_as";
google_ad_channel ="7352298734";
google_page_url = document.location;
google_color_border = "FFFFFF";
google_color_bg = "00001F";
google_color_link = "FFFFFF";
google_color_url = "FFF000";
google_color_text = "0000FF";
//--></script>
<script type="text/javascript"
  src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
</script><BR>	
<TABLE CELLSPACING = 0 CELLPADDING = 0 BORDER = 0>
<TR>
	<TD width="63"><IMG SRC = "graphics/topc000.jpg" WIDTH = 63 HEIGHT = 87></TD>
	<TD width="473"><IMG SRC = "graphics/topc001.jpg" WIDTH = 473 HEIGHT = 87></TD>
	<TD width="64"><IMG SRC = "graphics/topc002.jpg" WIDTH = 64 HEIGHT = 87></TD>
</TR>
	<TD width="63"></TD>
	<TD BGCOLOR="#BEA279" width="460">
	<DIV ALIGN="CENTER">
	<A HREF="http://www.loreseekers.com/screenshots.phtml"><IMG SRC="graphics/screencap_header.gif" WIDTH ="200" HEIGHT ="75" BORDER="0"></A>
	<TABLE WIDTH="460">
	<TR><TD>

<TABLE BGCOLOR="#BEA279" width="420" CELLPADDING="5" CELLSPACING="5">
<TR>
<TD BGCOLOR="#BEA279" width="20"></TD>
<TD GCOLOR="#BEA279" width="380">
<FONT FACE="Verdana" SIZE="2">
<HR>

<B>1. <A HREF="rok_shots_new.phtml">Newest Screenshots</A><FONT COLOR="#FF0000"> - UPDATED</FONT></B><BR>&nbsp;&nbsp;&nbsp; - <FONT SIZE="-1">The latest RoK™ screenshots</FONT><BR><BR>

<B>2. <A HREF="rok_shots_old.phtml">Previous Screenshots</A></B><BR>&nbsp;&nbsp;&nbsp; - <FONT SIZE="-1">Archive of past released screenshots</FONT><BR><BR>

<HR>
</FONT>
</TD>
<TD BGCOLOR="#BEA279" width="20"></TD>
</TR>
</TABLE>
	</TD></TR>
	</TABLE>
	<TD width="64"></TD>
<TR>
	<TD><IMG SRC = "graphics/botc000.jpg" WIDTH = 63 HEIGHT = 87></TD>
	<TD><IMG SRC = "graphics/botc001.jpg" WIDTH = 473 HEIGHT = 87></TD>
	<TD><IMG SRC = "graphics/botc002.jpg" WIDTH = 64 HEIGHT = 87></TD>
</TR>
</TABLE>
<BR>
<a href="http://wetrack.it/guidefox/a/16/b/20/e/2" TARGET="_new"><img src="http://guidefox.com/resources/atn/135x48_ani_eq2_1.gif" border="0"></a><BR>
<BR>
</DIV>
</BODY>
</HTML>


