<!--
                 This page has been created by Renaissance IT
   Renaissance Internet Technologies Copyright (c) 1999 All Rights Reserved.

             for more info on our products, please visit :
                        http://www.renaissance.nl/

	This script has been written by Roy Boverhof <rboverhof@renaissance.nl>
	
        Pagename                : credits.html
        Last Updated    		: 04-08-2000
-->

<HTML>
<HEAD>
	<TITLE>the Seekers of Lore : Credits</TITLE>
</HEAD>

<BODY BGCOLOR="#000000" TEXT="#000000" LINK="#000000" VLINK="#000000" ALINK="#000000">
<DIV ALIGN="CENTER">
<BR>
<script type="text/javascript"><!--
google_ad_client = "pub-0988179937943699";
google_ad_width = 468;
google_ad_height = 60;
google_ad_format = "468x60_as";
google_ad_channel ="7352298734";
google_page_url = document.location;
google_color_border = "FFFFFF";
google_color_bg = "00001F";
google_color_link = "FFFFFF";
google_color_url = "FFF000";
google_color_text = "0000FF";
//--></script>
<script type="text/javascript"
  src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
</script><BR>
<TABLE CELLSPACING = 0 CELLPADDING = 0 BORDER = 0>
<TR>
	<TD width="63"><IMG SRC = "graphics/topc000.jpg" WIDTH = 63 HEIGHT = 87></TD>
	<TD width="473"><IMG SRC = "graphics/topc001.jpg" WIDTH = 473 HEIGHT = 87></TD>
	<TD width="64"><IMG SRC = "graphics/topc002.jpg" WIDTH = 64 HEIGHT = 87></TD>
</TR>
	<TD width="63"></TD>
	<TD BGCOLOR="#BEA279" width="460">
	<DIV ALIGN="CENTER">
	<IMG SRC="graphics/credits_header.jpg" WIDTH ="200" HEIGHT ="50">
	<TABLE WIDTH="460">
	<TR><TD>

<TABLE BGCOLOR="#BEA279" width="430" CELLPADDING="5" CELLSPACING="5" ALIGN="center">
<TR>
<TD BGCOLOR="#BEA279" width="10"></TD>
<TD GCOLOR="#BEA279" width="410">
<FONT FACE="Verdana" SIZE="2">
<HR>

<B><A HREF="mailto:madwand@home.com">MadWand</A></B><BR>&nbsp;&nbsp; - <FONT SIZE="-1">Founder, Content, Graphics, Maps</FONT><BR><BR>

<B><A HREF="mailto:webmaster@loreseekers.com">Sorontar</A></B><BR>&nbsp;&nbsp; - <FONT SIZE="-1">Site Design, PHP3, MySQL, Site Hosting</FONT><BR><BR>

<B><A HREF="http://www.loreseekers.com/mem_detail.php3?search=58">Alchemys</A></B><BR>&nbsp;&nbsp; - <FONT SIZE="-1">PHP & Database Guru</FONT><BR><BR>

<B><A HREF="http://www.loreseekers.com/mem_detail.php3?search=46">Sora</A></B><BR>&nbsp;&nbsp; - <FONT SIZE="-1">and <A HREF="http://arctic.net" TARGET="_new">Arctic.Net</A> for their hosting of the mailing list</FONT><BR><BR>

<B>Frashii</B><BR>&nbsp;&nbsp; - <FONT SIZE="-1">Donation of webspace for our growing Lore!</FONT><BR><BR>

<B><A HREF="http://www.loreseekers.com/mem_detail.php3?search=924">Hyppy</A></B><BR>&nbsp;&nbsp; - <FONT SIZE="-1">Head Zookeeper</FONT><BR><BR>

<B>Zealott</B><BR>&nbsp;&nbsp; - <FONT SIZE="-1">Head Cartographer</FONT><BR><BR>

<B>Many Others!</B><BR>&nbsp;&nbsp; - <FONT SIZE="-1">Thanks to all who contibuted over the past year!</FONT><BR><BR>

<HR>
</FONT>
</TD>
<TD BGCOLOR="#BEA279" width="10"></TD>
</TR>
</TABLE>

	</TD></TR>
	</TABLE>
	<TD width="64"></TD>
<TR>
	<TD><IMG SRC = "graphics/botc000.jpg" WIDTH = 63 HEIGHT = 87></TD>
	<TD><IMG SRC = "graphics/botc001.jpg" WIDTH = 473 HEIGHT = 87></TD>
	<TD><IMG SRC = "graphics/botc002.jpg" WIDTH = 64 HEIGHT = 87></TD>
</TR>
</TABLE>
<script type="text/javascript"><!--
google_ad_client = "pub-0988179937943699";
google_ad_width = 180;
google_ad_height = 60;
google_ad_format = "180x60_as_rimg";
google_cpa_choice = "CAAQ56j8zwEaCHvU9tBAqJJaKMu293M";
//--></script>
<script type="text/javascript" src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
</script>
<BR>
<BR>
<BR>
</DIV>
</BODY>
</HTML>
