<!--
                 This page has been created by Renaissance IT
   Renaissance Internet Technologies Copyright (c) 1999 All Rights Reserved.

             for more info on our products, please visit :
                        http://www.renaissance.nl/

	This script has been written by Roy Boverhof <rboverhof@renaissance.nl>
	
        Pagename                : bertox_shots.html
        Last Updated    		: 05-01-2000
-->

<HTML>
<HEAD>
	<TITLE>the Seekers of Lore : Bertoxxulous Server Screenshots</TITLE>
</HEAD>

<BODY BGCOLOR="#000000" TEXT="#000000" LINK="#000000" VLINK="#000000" ALINK="#000000">
<DIV ALIGN="CENTER">
<BR>
<!-- FGB Banner Code -->
<SCRIPT LANGUAGE="JavaScript">
   <!-- Hide from old browsers
   now = new Date();
   random = now.getTime();
     
   // Modify to reflect site specifics
   site = "http://ds.cybereps.com";
   target = "/SITE=FGN/AREA=EQLORE/AAMSZ=BANNER";
   
   document.write('<IFRAME SRC="' + site + '/hserver/acc_random=' + random + target + '"');
   document.write(' NORESIZE SCROLLING=NO HSPACE=0 VSPACE=0 FRAMEBORDER=0 MARGINHEIGHT=0 MARGINWIDTH=0 WIDTH=468 HEIGHT=60>');
   
   document.write('<SCR');
   document.write('IPT SRC="' + site + '/jnserver/acc_random=' + random + target + '">');
   document.write('</SCR');
   document.write('IPT>');
   
   document.write('</IFRAME>');
   // End Hide -->
 </SCRIPT>
 <NOSCRIPT> 
   <A HREF="http://ds.cybereps.com/accipiter/adclick/SITE=FGN/AREA=EQLORE/AAMSZ=BANNER">
   <IMG SRC="http://ds.cybereps.com/accipiter/nserver/SITE=FGN/AREA=EQLORE/AAMSZ=BANNER" border="0"></A>
 </NOSCRIPT>
<!-- END FGB Banner Code --><BR>
<TABLE CELLSPACING = 0 CELLPADDING = 0 BORDER = 0>
<TR>
	<TD width="63"><IMG SRC = "graphics/topc000.jpg" WIDTH = 63 HEIGHT = 87></TD>
	<TD width="473"><IMG SRC = "graphics/topc001.jpg" WIDTH = 473 HEIGHT = 87></TD>
	<TD width="64"><IMG SRC = "graphics/topc002.jpg" WIDTH = 64 HEIGHT = 87></TD>
</TR>
	<TD width="63"></TD>
	<TD BGCOLOR="#BEA279" width="460">
	<DIV ALIGN="CENTER">
	<A HREF="http://www.loreseekers.com/screenshots.phtml"><IMG SRC="graphics/screencap_header.gif" WIDTH ="200" HEIGHT ="75" BORDER="0"></A>
	<TABLE WIDTH="460">
	<TR><TD>
	<CENTER>
<TABLE BORDER="0">
<TR>
<TD><BR><FONT SIZE="4" FACE="Ariel"><CENTER>Screenshots from our Bertoxxulous Members</CENTER></FONT><BR></TD>
</TR>
</TABLE>

<TABLE BORDER="0" WIDTH="440">
<TR> 
	<TD><A HREF="http://www.loreseekers.com/screenshots/blackdragon2.jpg" TARGET="_new"><IMG SRC="http://www.loreseekers.com/screenshots/tn_blackdragon2.jpg" WIDTH ="200" HEIGHT ="150" ALT="Click to view image full size"></A></TD>
	<TD><A HREF="http://www.loreseekers.com/screenshots/king.jpg" TARGET="_new"><IMG SRC="http://www.loreseekers.com/screenshots/tn_king.jpg" WIDTH ="200" HEIGHT ="150" ALT="Click to view image full size"></A></TD>
</TR>
<TR>
<TD><FONT SIZE="2" FACE="ariel"><CENTER><FONT COLOR="#FF00000">NEW</FONT> - 640 x 480</CENTER></FONT></TD>
<TD><FONT SIZE="2" FACE="ariel"><CENTER><FONT COLOR="#FF00000">NEW</FONT> - 640 x 480</CENTER></FONT></TD>
</TR>
<TR> 
	<TD><A HREF="http://www.loreseekers.com/screenshots/najena.jpg" TARGET="_new"><IMG SRC="http://www.loreseekers.com/screenshots/tn_najena.jpg" WIDTH ="200" HEIGHT ="150" ALT="Click to view image full size"></A></TD>
	<TD><A HREF="http://www.loreseekers.com/screenshots/najena2.jpg" TARGET="_new"><IMG SRC="http://www.loreseekers.com/screenshots/tn_najena2.jpg" WIDTH ="200" HEIGHT ="150" ALT="Click to view image full size"></A></TD>
</TR>
<TR>
<TD><FONT SIZE="2" FACE="ariel"><CENTER><FONT COLOR="#FF00000">NEW</FONT> - 640 x 480</CENTER></FONT></TD>
<TD><FONT SIZE="2" FACE="ariel"><CENTER><FONT COLOR="#FF00000">NEW</FONT> - 640 x 480</CENTER></FONT></TD>
</TR>
<TR> 
	<TD><A HREF="http://www.loreseekers.com/screenshots/najena3.jpg" TARGET="_new"><IMG SRC="http://www.loreseekers.com/screenshots/tn_najena3.jpg" WIDTH ="200" HEIGHT ="150" ALT="Click to view image full size"></A></TD>
	<TD><A HREF="http://www.loreseekers.com/screenshots/guildmeeting.jpg" TARGET="_new"><IMG SRC="http://www.loreseekers.com/screenshots/tn_guildmeeting.jpg" WIDTH ="200" HEIGHT ="150" ALT="Click to view image full size"></A></TD>
</TR>
<TR>
<TD><FONT SIZE="2" FACE="ariel"><CENTER><FONT COLOR="#FF00000">NEW</FONT> - 640 x 480</CENTER></FONT></TD>
<TD><FONT SIZE="2" FACE="ariel"><CENTER>640 x 480</CENTER></FONT></TD>
</TR>
<TR> 
	<TD><A HREF="http://www.loreseekers.com/screenshots/Meldrath.jpg" TARGET="_new"><IMG SRC="http://www.loreseekers.com/screenshots/tn_meldrath.jpg" WIDTH ="200" HEIGHT ="150" ALT="Click to view image full size"></A></TD>
	<TD><A HREF="http://www.loreseekers.com/screenshots/eq000034.jpg" TARGET="_new"><IMG SRC="http://www.loreseekers.com/screenshots/tn_eq000034.jpg" WIDTH ="200" HEIGHT ="150" ALT="Click to view image full size"></A></TD>
</TR>
<TR>
<TD COLSPAN=2><FONT SIZE="2" FACE="ariel"><CENTER>Read the story of this adventure <A HREF="http://www.loreseekers.com/stories/caves.phtml">HERE</A>!</CENTER></FONT></TD>
</TR>
<TR> 
	<TD><A HREF="http://www.loreseekers.com/screenshots/eq000037.jpg" TARGET="_new"><IMG SRC="http://www.loreseekers.com/screenshots/tn_eq000037.jpg" WIDTH ="200" HEIGHT ="150" ALT="Click to view image full size"></A></TD>
	<TD><A HREF="http://www.loreseekers.com/screenshots/eq000039.jpg" TARGET="_new"><IMG SRC="http://www.loreseekers.com/screenshots/tn_eq000039.jpg" WIDTH ="200" HEIGHT ="150" ALT="Click to view image full size"></A></TD>
</TR>
<TR>
<TD><FONT SIZE="2" FACE="ariel"><CENTER>640 x 480</CENTER></FONT></TD>
<TD><FONT SIZE="2" FACE="ariel"><CENTER>640 x 480</CENTER></FONT></TD>
</TR>
<TR> 
	<TD><A HREF="http://www.loreseekers.com/screenshots/eq000040.jpg" TARGET="_new"><IMG SRC="http://www.loreseekers.com/screenshots/tn_eq000040.jpg" WIDTH ="200" HEIGHT ="150" ALT="Click to view image full size"></A></TD>
	<TD><A HREF="http://www.loreseekers.com/screenshots/just-a-bunch-of-puppies.jpg" TARGET="_new"><IMG SRC="http://www.loreseekers.com/screenshots/tn_just-a-bunch-of-puppies.jpg" WIDTH ="200" HEIGHT ="150" ALT="Click to view image full size"></A></TD>
</TR>
<TR>
<TD><FONT SIZE="2" FACE="ariel"><CENTER>640 x 480</CENTER></FONT></TD>
<TD><FONT SIZE="2" FACE="ariel"><CENTER>640 x 480</CENTER></FONT></TD>
</TR>
</TABLE>

	</CENTER>
	<P>
	<BR>
	<BR>
	</P>

	</TD></TR>
	</TABLE>
	<TD width="64"></TD>
<TR>
	<TD><IMG SRC = "graphics/botc000.jpg" WIDTH = 63 HEIGHT = 87></TD>
	<TD><IMG SRC = "graphics/botc001.jpg" WIDTH = 473 HEIGHT = 87></TD>
	<TD><IMG SRC = "graphics/botc002.jpg" WIDTH = 64 HEIGHT = 87></TD>
</TR>
</TABLE>
<BR>
 <SCRIPT LANGUAGE="JavaScript">
   <!-- Hide from old browsers
   now = new Date();
   random = now.getTime();
   
   // Modify to reflect site specifics
   site = "http://ds.cybereps.com";
   target = "/SITE=FGN/AREA=EQLORE/AAMSZ=BOX";
   
   document.write('<IFRAME SRC="' + site + '/hserver/acc_random=' + random + target + '"');
   document.write(' NORESIZE SCROLLING=NO HSPACE=0 VSPACE=0 FRAMEBORDER=0 MARGINHEIGHT=0 MARGINWIDTH=0 WIDTH=125 HEIGHT=125>');
      
   document.write('<SCR');
   document.write('IPT SRC="' + site + '/jnserver/acc_random=' + random + target + '">');
   document.write('</SCR');
   document.write('IPT>');
   
   document.write('</IFRAME>');
   // End Hide -->
 </SCRIPT>
 <NOSCRIPT> 
   <A HREF="http://ds.cybereps.com/accipiter/adclick/SITE=FGN/AREA=EQLORE/AAMSZ=BOX">
   <IMG SRC="http://ds.cybereps.com/accipiter/nserver/SITE=FGN/AREA=EQLORE/AAMSZ=BOX" border="0"></A>
 </NOSCRIPT>
<BR>
<BR>
</DIV>
</BODY>
</HTML>