<!--
                 This page has been created by Renaissance IT
   Renaissance Internet Technologies Copyright (c) 1999 All Rights Reserved.

             for more info on our products, please visit :
                        http://www.renaissance.nl/

	This script has been written by Roy Boverhof <rboverhof@renaissance.nl>
	
        Pagename                : east_kunark_zones.html
        Last Updated    		: 05-08-2000
-->

<HTML>
<HEAD>
	<TITLE>the Seekers of Lore : East Kunark Region</TITLE>
</HEAD>

<BODY BGCOLOR="#000000" TEXT="#000000" LINK="#000000" VLINK="#000000" ALINK="#000000">
<DIV ALIGN="CENTER">
<BR>
<script type="text/javascript"><!--
google_ad_client = "pub-0988179937943699";
google_ad_width = 468;
google_ad_height = 60;
google_ad_format = "468x60_as";
google_ad_channel ="";
google_page_url = document.location;
google_color_border = "FFFFFF";
google_color_bg = "00001F";
google_color_link = "FFFFFF";
google_color_url = "FFF000";
google_color_text = "0000FF";
//--></script>
<script type="text/javascript"
  src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
</script><BR>
<TABLE CELLSPACING = 0 CELLPADDING = 0 BORDER = 0>
<TR>
	<TD width="63"><IMG SRC = "graphics/topc000.jpg" WIDTH = 63 HEIGHT = 87></TD>
	<TD width="473"><IMG SRC = "graphics/topc001.jpg" WIDTH = 473 HEIGHT = 87></TD>
	<TD width="64"><IMG SRC = "graphics/topc002.jpg" WIDTH = 64 HEIGHT = 87></TD>
</TR>
	<TD width="63"></TD>
	<TD BGCOLOR="#BEA279" width="460">
	<DIV ALIGN="CENTER">
	<A HREF="maps.php3"><IMG SRC="graphics/atlasheader.jpg" WIDTH ="150" HEIGHT ="75" BORDER="0"></A>
	<TABLE WIDTH="460">
	<TR><TD>
	<CENTER>
<TABLE BORDER="0">
<TR>
<TD><BR><FONT COLOR="#FFFF00" SIZE="4" FACE="Ariel"><CENTER>Now choose a zone...</CENTER></FONT><BR></TD>
</TR>
<TR>
<TD>
<IMG SRC="graphics/east_kunark_zones.jpg" WIDTH=400 HEIGHT=600 BORDER=0 USEMAP="#eastkunark">
<MAP NAME="eastkunark">
<AREA SHAPE=RECT COORDS="47,164,104,183" HREF="map_search.php3?action=zone&add_zone=Dalnir">
<AREA SHAPE=RECT COORDS="188,177,247,218" HREF="map_search.php3?action=zone&add_zone=Kurn's%20Tower">
<AREA SHAPE=RECT COORDS="258,160,338,182" HREF="map_search.php3?action=zone&add_zone=Kaesora">
<AREA SHAPE=RECT COORDS="262,212,321,247" HREF="map_search.php3?action=zone&add_zone=City%20of%20Mist">
<AREA SHAPE=RECT COORDS="264,256,337,293" HREF="map_search.php3?action=zone&add_zone=Emerald%20Jungle">
<AREA SHAPE=RECT COORDS="185,233,250,272" HREF="map_search.php3?action=zone&add_zone=Field%20of%20Bone">
<AREA SHAPE=RECT COORDS="32,221,119,259" HREF="map_search.php3?action=zone&add_zone=Warslik's%20Wood">
<AREA SHAPE=RECT COORDS="99,288,157,324" HREF="map_search.php3?action=zone&add_zone=West%20Cabilis">
<AREA SHAPE=RECT COORDS="162,287,220,325" HREF="map_search.php3?action=zone&add_zone=East%20Cabilis">
<AREA SHAPE=RECT COORDS="22,323,98,360" HREF="map_search.php3?action=zone&add_zone=Lake%20of%20Ill%20Omen">
<AREA SHAPE=RECT COORDS="169,345,257,383" HREF="map_search.php3?action=zone&add_zone=Swamp%20of%20No%20Hope">
<AREA SHAPE=RECT COORDS="269,344,367,384" HREF="map_search.php3?action=zone&add_zone=Trakanon's%20Teeth">
<AREA SHAPE=RECT COORDS="240,413,305,429" HREF="map_search.php3?action=zone&add_zone=Old%20Sebilis">
<AREA SHAPE=RECT COORDS="52,521,137,571" HREF="map_search.php3?action=zone&add_zone=Firiona">
<AREA SHAPE=RECT COORDS="157,555,242,593" HREF="map_search.php3?action=zone&add_zone=Timorous%20Deep">
<AREA SHAPE=POLY COORDS="17,354,17,327,1,340,17,354" HREF="west_kunark_zones.phtml" ALT="To West Kunark Region">
</MAP>
</TD>
</TR>
</TABLE>
	</TD></TR>
	</TABLE>
	<TD width="64"></TD>
<TR>
	<TD><IMG SRC = "graphics/botc000.jpg" WIDTH = 63 HEIGHT = 87></TD>
	<TD><IMG SRC = "graphics/botc001.jpg" WIDTH = 473 HEIGHT = 87></TD>
	<TD><IMG SRC = "graphics/botc002.jpg" WIDTH = 64 HEIGHT = 87></TD>
</TR>
</TABLE>
<BR>
<IMG SRC="http://service.bfast.com/bfast/serve?bfmid=1375281&siteid=40292692&bfpage=pc" BORDER="0" WIDTH="1" HEIGHT="1" NOSAVE ><A HREF="http://service.bfast.com/bfast/click?bfmid=1375281&siteid=40292692&bfpage=pc" TARGET="_new"><IMG SRC="http://affiliate.gamestop.com/affIMG/pc_120x60.gif" BORDER="0" WIDTH="120" HEIGHT="60" ALT="PC Games at GameStop.com"></A>
<BR>
<BR>
</DIV>
</BODY>
</HTML>