<!--
                 This page has been created by Renaissance IT
   Renaissance Internet Technologies Copyright (c) 1999 All Rights Reserved.

             for more info on our products, please visit :
                        http://www.renaissance.nl/

	This script has been written by Roy Boverhof <rboverhof@renaissance.nl>
	
        Pagename		: rok_shots_old.html
        Last Updated	: 04-08-2000
-->

<HTML>
<HEAD>
	<TITLE>the Seekers of Lore : RoK™ Old Screenshots</TITLE>
</HEAD>

<BODY BGCOLOR="#000000" TEXT="#000000" LINK="#000000" VLINK="#000000" ALINK="#000000">
<DIV ALIGN="CENTER">
<BR>
<script type="text/javascript"><!--
google_ad_client = "pub-0988179937943699";
google_ad_width = 468;
google_ad_height = 60;
google_ad_format = "468x60_as";
google_ad_channel ="7352298734";
google_page_url = document.location;
google_color_border = "FFFFFF";
google_color_bg = "00001F";
google_color_link = "FFFFFF";
google_color_url = "FFF000";
google_color_text = "0000FF";
//--></script>
<script type="text/javascript"
  src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
</script><BR>	
<TABLE CELLSPACING = 0 CELLPADDING = 0 BORDER = 0>
<TR>
	<TD width="63"><IMG SRC = "graphics/topc000.jpg" WIDTH = 63 HEIGHT = 87></TD>
	<TD width="473"><IMG SRC = "graphics/topc001.jpg" WIDTH = 473 HEIGHT = 87></TD>
	<TD width="64"><IMG SRC = "graphics/topc002.jpg" WIDTH = 64 HEIGHT = 87></TD>
</TR>
	<TD width="63"></TD>
	<TD BGCOLOR="#BEA279" width="460">
	<DIV ALIGN="CENTER">
		<A HREF="http://www.loreseekers.com/screenshots.phtml"><IMG SRC="graphics/screencap_header.gif" WIDTH ="200" HEIGHT ="75" BORDER="0"></A>
	<TABLE WIDTH="460">
	<TR><TD>
	<CENTER>
<TABLE BORDER="0">
<TR>
<TD><BR><FONT SIZE="4" FACE="Ariel"><CENTER>Older <A HREF="http://everquest.station.sony.com/kunark/index.html" TARGET="_new">Ruins of Kunark™</A> screenshots</CENTER></FONT><BR></TD>
</TR>
</TABLE>
<DIV ALIGN="center">
<TABLE WIDTH=410 BORDER=0 ALIGN="center">
<TR> 
	<TD><A HREF="http://www.loreseekers.com/screenshots/012100eqkun1.jpg" TARGET="_new"><IMG SRC="http://www.loreseekers.com/screenshots/tn_012100eqkun1.jpg" WIDTH ="200" HEIGHT ="150" ALT="Click to view image full size"></A></TD>
	<TD><A HREF="http://www.loreseekers.com/screenshots/012100eqkun2.jpg" TARGET="_new"><IMG SRC="http://www.loreseekers.com/screenshots/tn_012100eqkun2.jpg" WIDTH ="200" HEIGHT ="150" ALT="Click to view image full size"></A></TD>
</TR>
<TR>
	<TD><FONT SIZE="2" FACE="ARIEL"><CENTER>1024 X 768</CENTER></FONT></TD>
	<TD><FONT SIZE="2" FACE="ARIEL"><CENTER>1024 X 768</CENTER></FONT></TD>
</TR>
<TR> 
	<TD><A HREF="http://www.loreseekers.com/screenshots/012100eqkun3.jpg" TARGET="_new"><IMG SRC="http://www.loreseekers.com/screenshots/tn_012100eqkun3.jpg" WIDTH ="200" HEIGHT ="150" ALT="Click to view image full size"></A></TD>
</TR>
<TR>
	<TD><FONT SIZE="2" FACE="ARIEL"><CENTER>1024 X 768</CENTER></FONT></TD>
	<TD><FONT SIZE="2" FACE="ARIEL"><CENTER>1024 X 768</CENTER></FONT></TD>
</TR>
<TR> 
	<TD><A HREF="http://www.loreseekers.com/screenshots/EQ000001_tnt_1024.jpg" TARGET="_new"><IMG SRC="http://www.loreseekers.com/screenshots/tn_EQ000001_tnt_1024.jpg" WIDTH ="200" HEIGHT ="150" ALT="Click to view image full size"></A></TD>
	<TD><A HREF="http://www.loreseekers.com/screenshots/EQ000002_tnt_1024.jpg" TARGET="_new"><IMG SRC="http://www.loreseekers.com/screenshots/tn_EQ000002_tnt_1024.jpg" WIDTH ="200" HEIGHT ="150" ALT="Click to view image full size"></A></TD>
</TR>
<TR>
	<TD><FONT SIZE="2" FACE="ARIEL"><CENTER>1024 X 768</CENTER></FONT></TD>
	<TD><FONT SIZE="2" FACE="ARIEL"><CENTER>1024 X 768</CENTER></FONT></TD>
</TR>
<TR> 
	<TD><A HREF="http://www.loreseekers.com/screenshots/EQ000003_tnt_1024.jpg" TARGET="_new"><IMG SRC="http://www.loreseekers.com/screenshots/tn_EQ000003_tnt_1024.jpg" WIDTH ="200" HEIGHT ="150" ALT="Click to view image full size"></A></TD>
	<TD><A HREF="http://www.loreseekers.com/screenshots/EQ000004_tnt_1024.jpg" TARGET="_new"><IMG SRC="http://www.loreseekers.com/screenshots/tn_EQ000004_tnt_1024.jpg" WIDTH ="200" HEIGHT ="150" ALT="Click to view image full size"></A></TD>
</TR>
<TR>
	<TD><FONT SIZE="2" FACE="ARIEL"><CENTER>1024 X 768</CENTER></FONT></TD>
	<TD><FONT SIZE="2" FACE="ARIEL"><CENTER>1024 X 768</CENTER></FONT></TD>
</TR>
<TR> 
	<TD><A HREF="http://www.loreseekers.com/screenshots/EQ000005_tnt_1024.jpg" TARGET="_new"><IMG SRC="http://www.loreseekers.com/screenshots/tn_EQ000005_tnt_1024.jpg" WIDTH ="200" HEIGHT ="150" ALT="Click to view image full size"></A></TD>
	<TD><A HREF="http://www.loreseekers.com/screenshots/EQ000006_tnt_1024.jpg" TARGET="_new"><IMG SRC="http://www.loreseekers.com/screenshots/tn_EQ000006_tnt_1024.jpg" WIDTH ="200" HEIGHT ="150" ALT="Click to view image full size"></A></TD>
</TR>
<TR>
	<TD><FONT SIZE="2" FACE="ARIEL"><CENTER>1024 X 768</CENTER></FONT></TD>
	<TD><FONT SIZE="2" FACE="ARIEL"><CENTER>1024 X 768</CENTER></FONT></TD>
</TR>
<TR> 
	<TD><A HREF="http://www.loreseekers.com/screenshots/EQ000007_tnt_1024.jpg" TARGET="_new"><IMG SRC="http://www.loreseekers.com/screenshots/tn_EQ000007_tnt_1024.jpg" WIDTH ="200" HEIGHT ="150" ALT="Click to view image full size"></A></TD>
	<TD><A HREF="http://www.loreseekers.com/screenshots/EQ000008_tnt_1024.jpg" TARGET="_new"><IMG SRC="http://www.loreseekers.com/screenshots/tn_EQ000008_tnt_1024.jpg" WIDTH ="200" HEIGHT ="150" ALT="Click to view image full size"></A></TD>
</TR>
<TR>
	<TD><FONT SIZE="2" FACE="ARIEL"><CENTER>1024 X 768</CENTER></FONT></TD>
	<TD><FONT SIZE="2" FACE="ARIEL"><CENTER>1024 X 768</CENTER></FONT></TD>
</TR>
<TR> 
	<TD><A HREF="http://www.loreseekers.com/screenshots/EQ000009_tnt_1024.jpg" TARGET="_new"><IMG SRC="http://www.loreseekers.com/screenshots/tn_EQ000009_tnt_1024.jpg" WIDTH ="200" HEIGHT ="150" ALT="Click to view image full size"></A></TD>
	<TD><A HREF="http://www.loreseekers.com/screenshots/EQ000010_tnt_1024.jpg" TARGET="_new"><IMG SRC="http://www.loreseekers.com/screenshots/tn_EQ000010_tnt_1024.jpg" WIDTH ="200" HEIGHT ="150" ALT="Click to view image full size"></A></TD>
</TR>
<TR>
	<TD><FONT SIZE="2" FACE="ARIEL"><CENTER>1024 X 768</CENTER></FONT></TD>
	<TD><FONT SIZE="2" FACE="ARIEL"><CENTER>1024 X 768</CENTER></FONT></TD>
</TR>
<TR> 
	<TD><A HREF="http://www.loreseekers.com/screenshots/EQ000011_tnt_1024.jpg" TARGET="_new"><IMG SRC="http://www.loreseekers.com/screenshots/tn_EQ000011_tnt_1024.jpg" WIDTH ="200" HEIGHT ="150" ALT="Click to view image full size"></A></TD>
	<TD><A HREF="http://www.loreseekers.com/screenshots/EQ000012_tnt_1024.jpg" TARGET="_new"><IMG SRC="http://www.loreseekers.com/screenshots/tn_EQ000012_tnt_1024.jpg" WIDTH ="200" HEIGHT ="150" ALT="Click to view image full size"></A></TD>
</TR>
<TR>
	<TD><FONT SIZE="2" FACE="ARIEL"><CENTER>1024 X 768</CENTER></FONT></TD>
	<TD><FONT SIZE="2" FACE="ARIEL"><CENTER>1024 X 768</CENTER></FONT></TD>
</TR>
<TR> 
	<TD><A HREF="http://www.loreseekers.com/screenshots/EQ000013_tnt_1024.jpg" TARGET="_new"><IMG SRC="http://www.loreseekers.com/screenshots/tn_EQ000013_tnt_1024.jpg" WIDTH ="200" HEIGHT ="150" ALT="Click to view image full size"></A></TD>
	<TD><A HREF="http://www.loreseekers.com/screenshots/EQ000014_tnt_1024.jpg" TARGET="_new"><IMG SRC="http://www.loreseekers.com/screenshots/tn_EQ000014_tnt_1024.jpg" WIDTH ="200" HEIGHT ="150" ALT="Click to view image full size"></A></TD>
</TR>
<TR>
	<TD><FONT SIZE="2" FACE="ARIEL"><CENTER>1024 X 768</CENTER></FONT></TD>
	<TD><FONT SIZE="2" FACE="ARIEL"><CENTER>1024 X 768</CENTER></FONT></TD>
</TR>
<TR> 
	<TD><A HREF="http://www.loreseekers.com/screenshots/EQ000001_1024.jpg" TARGET="_new"><IMG SRC="http://www.loreseekers.com/screenshots/tn_eq000001_1024.jpg" WIDTH ="200" HEIGHT ="150" ALT="Click to view image full size"></A></TD>
	<TD><A HREF="http://www.loreseekers.com/screenshots/EQ000002-1024.jpg" TARGET="_new"><IMG SRC="http://www.loreseekers.com/screenshots/tn_eq000002-1024.jpg" WIDTH ="200" HEIGHT ="150" ALT="Click to view image full size"></A></TD>
</TR>
<TR>
	<TD><FONT SIZE="2" FACE="ARIEL"><CENTER>1024 X 768</CENTER></FONT></TD>
	<TD><FONT SIZE="2" FACE="ARIEL"><CENTER>1024 X 768</CENTER></FONT></TD>
</TR>
<TR> 
	<TD><A HREF="http://www.loreseekers.com/screenshots/EQ000005_1024.jpg" TARGET="_new"><IMG SRC="http://www.loreseekers.com/screenshots/tn_eq000005_1024.jpg" WIDTH ="200" HEIGHT ="150" ALT="Click to view image full size"></A></TD>
	<TD><A HREF="http://www.loreseekers.com/screenshots/EQ000006_1024.jpg" TARGET="_new"><IMG SRC="http://www.loreseekers.com/screenshots/tn_eq000006_1024.jpg" WIDTH ="200" HEIGHT ="150" ALT="Click to view image full size"></A></TD>
</TR>
<TR>
	<TD><FONT SIZE="2" FACE="ARIEL"><CENTER>1024 X 768</CENTER></FONT></TD>
	<TD><FONT SIZE="2" FACE="ARIEL"><CENTER>1024 X 768</CENTER></FONT></TD>
</TR>
<TR> 
	<TD><A HREF="http://www.loreseekers.com/screenshots/EQ000016_1024.jpg" TARGET="_new"><IMG SRC="http://www.loreseekers.com/screenshots/tn_eq000016_1024.jpg" WIDTH ="200" HEIGHT ="150" ALT="Click to view image full size"></A></TD>
	<TD><A HREF="http://www.loreseekers.com/screenshots/EQ000017_1024.jpg" TARGET="_new"><IMG SRC="http://www.loreseekers.com/screenshots/tn_eq000017_1024.jpg" WIDTH ="200" HEIGHT ="150" ALT="Click to view image full size"></A></TD>
</TR>
<TR>
	<TD><FONT SIZE="2" FACE="ARIEL"><CENTER>1024 X 768</CENTER></FONT></TD>
	<TD><FONT SIZE="2" FACE="ARIEL"><CENTER>1024 X 768</CENTER></FONT></TD>
</TR>
</TABLE>
<TABLE BORDER="0">
<TR> 
	<TD><A HREF="http://www.loreseekers.com/screenshots/EQ000014_800.jpg" TARGET="_new"><IMG SRC="http://www.loreseekers.com/screenshots/tn_eq000014_800.jpg" WIDTH ="200" HEIGHT ="150" ALT="Click to view image full size"></A></TD>
	<TD><A HREF="http://www.loreseekers.com/screenshots/EQ000021_800.jpg" TARGET="_new"><IMG SRC="http://www.loreseekers.com/screenshots/tn_eq000021_800.jpg" WIDTH ="200" HEIGHT ="150" ALT="Click to view image full size"></A></TD>
</TR>
<TR>
	<TD><FONT SIZE="2" FACE="ARIEL"><CENTER>800 X 600</CENTER></FONT></TD>
	<TD><FONT SIZE="2" FACE="ARIEL"><CENTER>800 X 600</CENTER></FONT></TD>
</TR>
<TR> 
	<TD><A HREF="http://www.loreseekers.com/screenshots/EQ000022_800.jpg" TARGET="_new"><IMG SRC="http://www.loreseekers.com/screenshots/tn_eq000022_800.jpg" WIDTH ="200" HEIGHT ="150" ALT="Click to view image full size"></A></TD>
	<TD><A HREF="http://www.loreseekers.com/screenshots/EQ000024_800.jpg" TARGET="_new"><IMG SRC="http://www.loreseekers.com/screenshots/tn_eq000024_800.jpg" WIDTH ="200" HEIGHT ="150" ALT="Click to view image full size"></A></TD>
</TR>
<TR>
	<TD><FONT SIZE="2" FACE="ARIEL"><CENTER>800 X 600</CENTER></FONT></TD>
	<TD><FONT SIZE="2" FACE="ARIEL"><CENTER>800 X 600</CENTER></FONT></TD>
</TR>
<TR> 
	<TD><A HREF="http://www.loreseekers.com/screenshots/EQ000030_800.jpg" TARGET="_new"><IMG SRC="http://www.loreseekers.com/screenshots/tn_eq000030_800.jpg" WIDTH ="200" HEIGHT ="150" ALT="Click to view image full size"></A></TD>
	<TD><A HREF="http://www.loreseekers.com/screenshots/EQ000032_800.jpg" TARGET="_new"><IMG SRC="http://www.loreseekers.com/screenshots/tn_eq000032_800.jpg" WIDTH ="200" HEIGHT ="150" ALT="Click to view image full size"></A></TD>
</TR>
<TR>
	<TD><FONT SIZE="2" FACE="ARIEL"><CENTER>800 X 600</CENTER></FONT></TD>
	<TD><FONT SIZE="2" FACE="ARIEL"><CENTER>800 X 600</CENTER></FONT></TD>
</TR>
<TR> 
	<TD><A HREF="http://www.loreseekers.com/screenshots/EQ000041_800.jpg" TARGET="_new"><IMG SRC="http://www.loreseekers.com/screenshots/tn_eq000041_800.jpg" WIDTH ="200" HEIGHT ="150" ALT="Click to view image full size"></A></TD>
	<TD><A HREF="http://www.loreseekers.com/screenshots/EQ000044_800.jpg" TARGET="_new"><IMG SRC="http://www.loreseekers.com/screenshots/tn_eq000044_800.jpg" WIDTH ="200" HEIGHT ="150" ALT="Click to view image full size"></A></TD>
</TR>
<TR>
	<TD><FONT SIZE="2" FACE="ARIEL"><CENTER>800 X 600</CENTER></FONT></TD>
	<TD><FONT SIZE="2" FACE="ARIEL"><CENTER>800 X 600</CENTER></FONT></TD>
</TR>
<TR> 
	<TD><A HREF="http://www.loreseekers.com/screenshots/EQ000048_800.jpg" TARGET="_new"><IMG SRC="http://www.loreseekers.com/screenshots/tn_eq000048_800.jpg" WIDTH ="200" HEIGHT ="150" ALT="Click to view image full size"></A></TD>
	<TD><A HREF="http://www.loreseekers.com/screenshots/EQ000050_800.jpg" TARGET="_new"><IMG SRC="http://www.loreseekers.com/screenshots/tn_eq000050_800.jpg" WIDTH ="200" HEIGHT ="150" ALT="Click to view image full size"></A></TD>
</TR>
<TR>
	<TD><FONT SIZE="2" FACE="ARIEL"><CENTER>800 X 600</CENTER></FONT></TD>
	<TD><FONT SIZE="2" FACE="ARIEL"><CENTER>800 X 600</CENTER></FONT></TD>
</TR>
<TR> 
	<TD><A HREF="http://www.loreseekers.com/screenshots/EQ000057_800.jpg" TARGET="_new"><IMG SRC="http://www.loreseekers.com/screenshots/tn_eq000057_800.jpg" WIDTH ="200" HEIGHT ="150" ALT="Click to view image full size"></A></TD>
	<TD><A HREF="http://www.loreseekers.com/screenshots/EQ000078_800.jpg" TARGET="_new"><IMG SRC="http://www.loreseekers.com/screenshots/tn_eq000078_800.jpg" WIDTH ="200" HEIGHT ="150" ALT="Click to view image full size"></A></TD>
</TR>
<TR>
	<TD><FONT SIZE="2" FACE="ARIEL"><CENTER>800 X 600</CENTER></FONT></TD>
	<TD><FONT SIZE="2" FACE="ARIEL"><CENTER>800 X 600</CENTER></FONT></TD>
</TR>
</TABLE>
</DIV>

	</CENTER>
	<P>
	<BR>
	<BR>
	</P>
	</TD></TR>
	</TABLE>
	<TD width="64"></TD>
<TR>
	<TD><IMG SRC = "graphics/botc000.jpg" WIDTH = 63 HEIGHT = 87></TD>
	<TD><IMG SRC = "graphics/botc001.jpg" WIDTH = 473 HEIGHT = 87></TD>
	<TD><IMG SRC = "graphics/botc002.jpg" WIDTH = 64 HEIGHT = 87></TD>
</TR>
</TABLE>
<script type="text/javascript"><!--
google_ad_client = "pub-0988179937943699";
google_ad_width = 180;
google_ad_height = 60;
google_ad_format = "180x60_as_rimg";
google_cpa_choice = "CAAQ56j8zwEaCHvU9tBAqJJaKMu293M";
//--></script>
<script type="text/javascript" src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
</script>
<BR>
<BR>
<BR>
</DIV>
</BODY>
</HTML>


