<!--
                 This page has been created by Renaissance IT
   Renaissance Internet Technologies Copyright (c) 1999 All Rights Reserved.

             for more info on our products, please visit :
                        http://www.renaissance.nl/

	This script has been written by Roy Boverhof <rboverhof@renaissance.nl>
	
        Pagename                : links3.html
        Last Updated    		: 03-16-2001
-->

<HTML>
<HEAD>
	<TITLE>the Seekers of Lore : Forums and Discussion Boards</TITLE>
</HEAD>

<BODY BGCOLOR="#000000" TEXT="#000000" LINK="#BEA279" VLINK="#BEA279">
<DIV ALIGN="CENTER">
<BR>
<!-- FGB Banner Code -->
<SCRIPT LANGUAGE="JavaScript">
   <!-- Hide from old browsers
   now = new Date();
   random = now.getTime();
     
   // Modify to reflect site specifics
   site = "http://ds.cybereps.com";
   target = "/SITE=FGN/AREA=EQLORE/AAMSZ=BANNER";
   
   document.write('<IFRAME SRC="' + site + '/hserver/acc_random=' + random + target + '"');
   document.write(' NORESIZE SCROLLING=NO HSPACE=0 VSPACE=0 FRAMEBORDER=0 MARGINHEIGHT=0 MARGINWIDTH=0 WIDTH=468 HEIGHT=60>');
   
   document.write('<SCR');
   document.write('IPT SRC="' + site + '/jnserver/acc_random=' + random + target + '">');
   document.write('</SCR');
   document.write('IPT>');
   
   document.write('</IFRAME>');
   // End Hide -->
 </SCRIPT>
 <NOSCRIPT> 
   <A HREF="http://ds.cybereps.com/accipiter/adclick/SITE=FGN/AREA=EQLORE/AAMSZ=BANNER">
   <IMG SRC="http://ds.cybereps.com/accipiter/nserver/SITE=FGN/AREA=EQLORE/AAMSZ=BANNER" border="0"></A>
 </NOSCRIPT>
<!-- END FGB Banner Code --><BR>
<TABLE CELLSPACING = 0 CELLPADDING = 0 BORDER = 0>
<TR>
	<TD width="63"><IMG SRC = "graphics/topc000.jpg" WIDTH = 63 HEIGHT = 87></TD>
	<TD width="473"><IMG SRC = "graphics/topc001.jpg" WIDTH = 473 HEIGHT = 87></TD>
	<TD width="64"><IMG SRC = "graphics/topc002.jpg" WIDTH = 64 HEIGHT = 87></TD>
</TR>
	<TD width="63"></TD>
	<TD BGCOLOR="#BEA279" width="460">
	<DIV ALIGN="CENTER">
	<A HREF="links.phtml"><IMG SRC="graphics/linkheader.jpg" WIDTH ="200" HEIGHT ="75" ALT="Back to Links Index"></A>
	<TABLE WIDTH=440 ALIGN="center">
	<TR><TD></TD></TR>
	<TR>
		<TD>
		<A HREF="http://pub6.ezboard.com/bthemagicianstower.html" TARGET="_new"><IMG SRC="graphics/magicians_tower_link.jpg" WIDTH ="220" HEIGHT ="75"></A>
		</TD>
		<TD><FONT FACE="Verdana" SIZE="-2">An 'ezboard' forum for the magicians out there.</FONT></TD>
	</TR>
	<TR>
		<TD>
		<A HREF="http://boards.station.sony.com/cgi-bin/Ultimate.cgi?action=intro" TARGET="_new"><IMG SRC="graphics/everquest_link.jpg" WIDTH ="220" HEIGHT ="75"></A>
		</TD>
		<TD><FONT FACE="Verdana" SIZE="-2">The official Sony EQ message boards.</FONT></TD>
	</TR>
	<TR>
		<TD>
		<A HREF="http://vnboards.ign.com/default.asp?cat=5001" TARGET="_new"><IMG SRC="graphics/eqvault_link.jpg" WIDTH ="220" HEIGHT ="75"></A>
		</TD>
		<TD><FONT FACE="Verdana" SIZE="-2">EQVaults very popular discussion boards</FONT></TD>
	</TR>
	<TR>
		<TD>
		<A HREF="http://boards.stratics.com/cgi-bin/ubb/Ultimate.cgi?action=intro&BypassCookie=true" TARGET="_new"><IMG SRC="graphics/eqss_link.jpg" WIDTH ="220" HEIGHT ="75"></A>
		</TD>
		<TD><FONT FACE="Verdana" SIZE="-2">EQ Stratics' busy boards</FONT></TD>
	</TR>

<!--

Down...

	<TR>
		<TD>
		<A HREF="http://eqforge.com/cgi-bin/Ultimate.cgi?action=intro&BypassCookie=true" TARGET="_new"><IMG SRC="graphics/eq_forge_link.jpg" WIDTH ="220" HEIGHT ="75"></A>
		</TD>
		<TD><FONT FACE="Verdana" SIZE="-2">Forums hosted by the EQ Forge</FONT></TD>
	</TR>

-->

	<TR>
		<TD>
		<A HREF="http://pub13.ezboard.com/bthesafehouse" TARGET="_new"><IMG SRC="graphics/safehouse_link.jpg" WIDTH ="220" HEIGHT ="75"></A>
		</TD>
		<TD><FONT FACE="Verdana" SIZE="-2">The "All Things Rogue" Message Board.</FONT></TD>
	</TR>
	<TR>
		<TD>
		<A HREF="mailto:webmaster@loreseekers.com?subject=links"><IMG SRC="graphics/submit_link.jpg" WIDTH ="220" HEIGHT ="75"></A>
		</TD>
		<TD><I>Do you know of a good discussion board? Email us your link!</I></TD>
	</TR>
	</TABLE>
	<TD width="64"></TD>
<TR>
	<TD><IMG SRC = "graphics/botc000.jpg" WIDTH = 63 HEIGHT = 87></TD>
	<TD><IMG SRC = "graphics/botc001.jpg" WIDTH = 473 HEIGHT = 87></TD>
	<TD><IMG SRC = "graphics/botc002.jpg" WIDTH = 64 HEIGHT = 87></TD>
</TR>
</TABLE>
<BR>
 <SCRIPT LANGUAGE="JavaScript">
   <!-- Hide from old browsers
   now = new Date();
   random = now.getTime();
   
   // Modify to reflect site specifics
   site = "http://ds.cybereps.com";
   target = "/SITE=FGN/AREA=EQLORE/AAMSZ=BOX";
   
   document.write('<IFRAME SRC="' + site + '/hserver/acc_random=' + random + target + '"');
   document.write(' NORESIZE SCROLLING=NO HSPACE=0 VSPACE=0 FRAMEBORDER=0 MARGINHEIGHT=0 MARGINWIDTH=0 WIDTH=125 HEIGHT=125>');
      
   document.write('<SCR');
   document.write('IPT SRC="' + site + '/jnserver/acc_random=' + random + target + '">');
   document.write('</SCR');
   document.write('IPT>');
   
   document.write('</IFRAME>');
   // End Hide -->
 </SCRIPT>
 <NOSCRIPT> 
   <A HREF="http://ds.cybereps.com/accipiter/adclick/SITE=FGN/AREA=EQLORE/AAMSZ=BOX">
   <IMG SRC="http://ds.cybereps.com/accipiter/nserver/SITE=FGN/AREA=EQLORE/AAMSZ=BOX" border="0"></A>
 </NOSCRIPT>
<BR>
<BR>
</DIV>
</BODY>
</HTML>



