<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">

<html>
<head>
	<title>..:: EQBard : le site de Jonili le petit barde ::..</title>

<SCRIPT LANGUAGE="Javascript">
<!--
function fenetre(intitule,params) { 
var fen = window.open(intitule,'zoom',params); 
}
//-->
</script>

<style>
a.lientexte {color:#0B5040;text-decoration:none;}
a.lientexte:hover {color:#0B5040;text-decoration:underline;}
</style>
</head>

<body bgcolor='#CFE6E3' text='#000000' link='#0B5040' vlink='#000000' alink='#000000'>
<table width='680' border='0' cellspacing='0' cellpadding='0'>
<tr><td>
<table width='680' border='0' cellspacing='0' cellpadding='0'>
<tr>
<td width='680' align='right' valign='top'>
<img src='./img/commun/c01/carre80.gif' width='10' height='10' border='0' alt=''>
<img src='./img/commun/c01/carre70.gif' width='10' height='10' border='0' alt=''>
<img src='./img/commun/c01/carre60.gif' width='10' height='10' border='0' alt=''>
<img src='./img/commun/c01/carre50.gif' width='10' height='10' border='0' alt=''>
</td></tr>
<tr><td height='2'><img src='./img/commun/transparent.gif' height='2' alt='' border='0'></td></tr>
<tr><td width='680' height='1'><img src='./img/commun/c01/carre50.gif' width='680' height='1' alt='' border='0'></td></tr>
</table>
</td></tr><tr><td>
<table width='680' border='0' cellspacing='0' cellpadding='0'>
<tr><td width='120' valign='top'><table width='100%' border='0' cellspacing='0' cellpadding='0'>
<tr><td>
<font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>&nbsp;<br>
<img src='./img/commun/c01/carre70.gif' width='10' height='10' border='0' alt=''>&nbsp;<a href=index.php?menu=1&data=1 class=lientexte><b>Accueil</b></a><br>&nbsp;<br>
<img src='./img/commun/c01/carre70.gif' width='10' height='10' border='0' alt=''>&nbsp;<b>Equipement</b><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=32&data=31&inc=armures class=lientexte>Armures</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=33&data=31&inc=armes&order=1&sens=1&bard=1 class=lientexte>Armes</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=35&data=31&inc=slot class=lientexte>Par slot</a><br>&nbsp;<br>
<img src='./img/commun/c01/carre70.gif' width='10' height='10' border='0' alt=''>&nbsp;<b>Guides</b><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=41&data=41 class=lientexte>Général</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=42&data=42 class=lientexte>Tactiques</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carreselect.gif' width='5' height='5' border='0' alt=''>&nbsp;Quêtes<br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=44&data=44 class=lientexte>Zones</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=45&data=45 class=lientexte>Procs</a><br>&nbsp;<br>
<img src='./img/commun/c01/carre70.gif' width='10' height='10' border='0' alt=''>&nbsp;<b>Photos</b><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=51&data=51 class=lientexte>Atlas</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=52&data=52 class=lientexte>Bardes</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=54&data=54 class=lientexte>GM</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=55&data=55 class=lientexte>Divers</a><br>&nbsp;<br>
<img src='./img/commun/c01/carre70.gif' width='10' height='10' border='0' alt=''>&nbsp;<a href=index.php?menu=8&data=8 class=lientexte><b>Mode</b></a><br>&nbsp;<br>
<img src='./img/commun/c01/carre70.gif' width='10' height='10' border='0' alt=''>&nbsp;<b>Spells Sebilis</b><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=1001&data=10 class=lientexte>Barde</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=1002&data=10 class=lientexte>Belluaire</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=1003&data=10 class=lientexte>Chaman</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=1004&data=10 class=lientexte>Clerc</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=1005&data=10 class=lientexte>Druide</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=1006&data=10 class=lientexte>Enchanteur</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=1007&data=10 class=lientexte>Fléau d'ombre</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=1009&data=10 class=lientexte>Magicien</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=1012&data=10 class=lientexte>Nécromancien</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=1013&data=10 class=lientexte>Paladin</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=1014&data=10 class=lientexte>Rôdeur</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=1015&data=10 class=lientexte>Sorcier</a><br>&nbsp;<br>
<img src='./img/commun/c01/carre70.gif' width='10' height='10' border='0' alt=''>&nbsp;<a href=index.php?menu=6&data=6 class=lientexte><b>Liens</b></a><br>
<img src='./img/commun/c01/carre70.gif' width='10' height='10' border='0' alt=''>&nbsp;<a href=index.php?menu=7&data=7 class=lientexte><b>Download</b></a><br>
<img src='./img/commun/c01/carre70.gif' width='10' height='10' border='0' alt=''>&nbsp;<a href='http://forumsfr.ubi.com/messages/overview.asp?name=eq_themaeq_eqbardes' target='_blank' class=lientexte><b>Forum</b></a><br>
<img src='./img/commun/c01/carre70.gif' width='10' height='10' border='0' alt=''>&nbsp;<a href=mailto:jonili@eqbard.eqloft.com class=lientexte><b>M'écrire</b></a><br>&nbsp;<br>
<img src='./img/commun/c01/carre70.gif' width='10' height='10' border='0' alt=''>&nbsp;<a href=index.php?menu=9&data=9 class=lientexte><b>Backstage</b></a><br>&nbsp;<br></font></td></tr></table>
</td><td width='20' valign='top'><img src='./img/commun/c01/carre50.gif' width='10' height='10' border='0' alt=''>
<img src='./img/commun/c01/carre60.gif' width='10' height='10' border='0' alt=''>
<img src='./img/commun/c01/carre70.gif' width='10' height='10' border='0' alt=''>
<img src='./img/commun/c01/carre80.gif' width='10' height='10' border='0' alt=''>
</td><td width='540' align='left' valign='top'><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>&nbsp;<br><a href='index.php?menu=43&data=43 class=lientexte' class=lientexte><b>< Retour</b></a><br>&nbsp;<br><table width='100%' border='0' cellspacing='0' cellpadding='0'><tr><td colspan='2' bgcolor='#0B5040'><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2' color='white'><b>&nbsp;Bravado armor</b></font></td></tr><tr><td width ='10'>&nbsp;</td><td><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>&nbsp;<br>
La découverte de Luclin nous a apporté une nouvelle quête d'armure. Cette quête se situe entre la quête des lambent et les quêtes de Velious du point de vue de la difficulté.
<br>&nbsp;<br>
Toutes ces quêtes sont données dans the Twilight Sea. L'armure obtenue s'appelle la Bravado... Pour chaque item il faut une gemme, un mark, une medaille et parfois un quatrième item.
<br>&nbsp;<br>
Les gemmes doivent s'acheter chez les marchands. Pas d'info là dessus pour le moment.
<br>&nbsp;<br>
Toutes ces infos sont à confirmer...<br>
En particulier :<br>
glorious flower : zone et mob inconnus (peut-être à scarlet desert)<br>
mark of composition : zone et mob inconnus<br>
sapphire studded medal : zone et mob à confirmer
<br>&nbsp;<br>

</font>&nbsp;<br></td></tr><tr><td colspan='2' bgcolor='#0B5040'><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2' color='white'><b>&nbsp;Boots</b></font></td></tr><tr><td width ='10'>&nbsp;</td><td><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>&nbsp;<br>
<b>NPC</b> : Herald Shelia Gransith<br>
<b>Ingrédients</b> : sky jewel, mark of poetry, star ruby studded medal<br>
Sky jewel :<br>
Mark of poetry : venerable sea turtle dans Twilight Sea<br>
Star ruby studded medal : honored spire spirit dans Mons Letalis<br>
Stats : 11ac, 3str, 1dex, 3cha, 8hp, 1cr
<br>&nbsp;<br>

</font>&nbsp;<br></td></tr><tr><td colspan='2' bgcolor='#0B5040'><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2' color='white'><b>&nbsp;Bracer</b></font></td></tr><tr><td width ='10'>&nbsp;</td><td><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>&nbsp;<br>
<b>NPC</b> : Herald Shelia Gransith<br>
<b>Ingrédients</b> : cloud jewel, mark of song, pearl studded medal<br>
Cloud jewel :<br>
Mark of song : immense underbulk dans Twilight Sea<br>
Pearl studded medal : vigorous rockhopper dans Scarlet Desert<br>
Stats : 9ac, 3str, 1dex, 3cha, 8hp, 1fr
<br>&nbsp;<br>

</font>&nbsp;<br></td></tr><tr><td colspan='2' bgcolor='#0B5040'><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2' color='white'><b>&nbsp;Breastplate</b></font></td></tr><tr><td width ='10'>&nbsp;</td><td><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>&nbsp;<br>
<b>NPC</b> : Herald Shelia Gransith<br>
<b>Ingrédients</b> : astral jewel, mark of music, diamond studded medal, glorious flower<br>
Astral jewel : Fungi Shroom à Dawnshroup Peaks<br>
Mark of music : coterie duelist dans Tenebrous Mountains<br>
Diamond studded medal : studded stonegrabber dans Mons Letalis<br>
Glorious flower : dans Scarlet Desert (?)<br>
Stats : 21ac, 8str, 3dex, 5cha, 8hp, 2fr/cr/mr 

<br>&nbsp;<br>

</font>&nbsp;<br></td></tr><tr><td colspan='2' bgcolor='#0B5040'><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2' color='white'><b>&nbsp;Cloak</b></font></td></tr><tr><td width ='10'>&nbsp;</td><td><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>&nbsp;<br>
<b>NPC</b> : Brolan Geppal<br>
<b>Ingrédients</b> : astral jewel, mark of melody, onyx studded medal, porous rock<br>
Astral jewel : Fungi Shroom à Dawnshroup Peaks<br>
Mark of melody : ancient darkwing bat dans Tenebrous Mountains<br>
Onyx studded medal : cunning rockhopper dans Dawnshroud Peaks<br>
Porous rock : cral ligi rocklord dans Twilight Sea<br>
Stats : 7ac, 4str, 1dex, 3cha, 8hp, 1fr/cr 

<br>&nbsp;<br>

</font>&nbsp;<br></td></tr><tr><td colspan='2' bgcolor='#0B5040'><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2' color='white'><b>&nbsp;Gauntlets</b></font></td></tr><tr><td width ='10'>&nbsp;</td><td><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>&nbsp;<br>
<b>NPC</b> : Brolan Geppal<br>
<b>Ingrédients</b> : sun jewel, mark of anthems, fire emerald studded medal<br>
Sun jewel : <br>
Mark of anthems : dire wolf dans Dawnshroud Peaks<br>
Fire emerald studded medal : shik nar legionnaire dans Mons Letalis<br>
Stats : 11ac, 3str, 1dex, 3cha, 8hp, 1dr 

<br>&nbsp;<br>

</font>&nbsp;<br></td></tr><tr><td colspan='2' bgcolor='#0B5040'><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2' color='white'><b>&nbsp;Girdle</b></font></td></tr><tr><td width ='10'>&nbsp;</td><td><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>&nbsp;<br>
<b>NPC</b> : Brolan Geppal<br>
<b>Ingrédients</b> : star jewel, mark of composition, peridot studded medal, seared brand<br>
Star jewel :<br>
Mark of composition : ???<br>
Peridot studded medal : tenacious turtle dans Twilight Sea<br>
Seared brand : sambata brander dans Dawnshroud Peaks<br>
Stats :

<br>&nbsp;<br>

</font>&nbsp;<br></td></tr><tr><td colspan='2' bgcolor='#0B5040'><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2' color='white'><b>&nbsp;Gorget</b></font></td></tr><tr><td width ='10'>&nbsp;</td><td><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>&nbsp;<br>
<b>NPC</b> : Brolan Geppal<br>
<b>Ingrédients</b> : moon jewel, mark of psalms, black pearl studded medal<br>
Moon jewel : sur un Large Zelniak à Dawnshroud Peaks<br>
Mark of psalms : scavenger minnow dans Twilight Sea<br>
Black pearl studded medal : sun revenant hero dans Scarlet Desert<br>
Stats :

<br>&nbsp;<br>

</font>&nbsp;<br></td></tr><tr><td colspan='2' bgcolor='#0B5040'><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2' color='white'><b>&nbsp;Greaves</b></font></td></tr><tr><td width ='10'>&nbsp;</td><td><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>&nbsp;<br>
<b>NPC</b> : Herald Shelia Gransith<br>
<b>Ingrédients</b> : moon jewel, mark of the drum, emerald studded medal, memory crystal<br>
Moon jewel :  sur un Large Zelniak à Dawnshroud Peaks<br>
Mark of the drum : grol baku drummer dans Twilight Sea<br>
Emerald studded medal : meeda hune hero dans Tenebrous Mountains<br>
Memory crystal : grol baku wiseman dans Scarlet Desert<br>
Stats : 13ac, 4str, 1dex, 3cha, 20hp, 1cr 

<br>&nbsp;<br>

</font>&nbsp;<br></td></tr><tr><td colspan='2' bgcolor='#0B5040'><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2' color='white'><b>&nbsp;Helm</b></font></td></tr><tr><td width ='10'>&nbsp;</td><td><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>&nbsp;<br>
<b>NPC</b> : Herald Shelia Gransith<br>
<b>Ingrédients</b> : meteor jewel, mark of rythm, ruby studded medal, fancy necklace<br>
Meteor jewel : sur un fungi shroom à Dawnshroud Peaks<br>
Mark of rythm : grol baku chanter dans Tenebrous Mountains<br>
Ruby studded medal : studded stonegrabber dans Dawnshroud Peaks<br>
Fancy necklace : tenacious shadow dans Twilight Sea<br>
Stats : 12ac, 3str, 1dex, 3cha, 8hp, 1mr 

<br>&nbsp;<br>

</font>&nbsp;<br></td></tr><tr><td colspan='2' bgcolor='#0B5040'><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2' color='white'><b>&nbsp;Mask</b></font></td></tr><tr><td width ='10'>&nbsp;</td><td><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>&nbsp;<br>
<b>NPC</b> : Brolan Geppal<br>
<b>Ingrédients</b> : meteor jewel, mark of tenor, star sapphire studded medal<br>
Meteor jewel :  sur un fungi shroom à Dawnshroud Peaks<br>
Mark of tenor : vas ren tenor dans Twilight Sea<br>
Star sapphire studded medal : forsaken lightcrawler dans Scarlet Desert<br>
Stats :


<br>&nbsp;<br>

</font>&nbsp;<br></td></tr><tr><td colspan='2' bgcolor='#0B5040'><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2' color='white'><b>&nbsp;Pauldrons</b></font></td></tr><tr><td width ='10'>&nbsp;</td><td><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>&nbsp;<br>
<b>NPC</b> : Herald Shelia Gransith<br>
<b>Ingrédients</b> : star jewel, mark of the mandolin, opal studded medal<br>
Star jewel :<br>
Mark of the mandolin : vas ren musician dans Scarlet Desert<br>
Opal studded medal : greater zelniak dans Dawnshroud Peaks<br>
Stats : 10ac, 3str, 1dex, 3cha, 8hp, 1mr 

<br>&nbsp;<br>

</font>&nbsp;<br></td></tr><tr><td colspan='2' bgcolor='#0B5040'><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2' color='white'><b>&nbsp;Sword</b></font></td></tr><tr><td width ='10'>&nbsp;</td><td><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>&nbsp;<br>
<b>NPC</b> : Brolan Geppal<br>
<b>Ingrédients</b> : cloud jewel, mark of chants, moonstone studded medal, red stone idol<br>
Cloud jewel :<br>
Mark of chants : bloodtribe chanter dans Scarlet Desert<br>
Moonstone studded medal : cral ligi hero dans Twilight Sea<br>
Red stone idol : vigorous rockhopper dans Mons Letalis<br>
Stats :

<br>&nbsp;<br>

</font>&nbsp;<br></td></tr><tr><td colspan='2' bgcolor='#0B5040'><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2' color='white'><b>&nbsp;Vambraces</b></font></td></tr><tr><td width ='10'>&nbsp;</td><td><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>&nbsp;<br>
<b>NPC</b> : Herald Shelia Gransith<br>
<b>Ingrédients</b> : sun jewel, mark of entertainment, sapphire studded medal, velvet sleeves<br>
Sun jewel :<br>
Mark of entertainment : tro jeg entertainer dans Scarlet Desert<br>
Sapphire studded medal : dishonorable horror dans Mons Letalis (?)<br>
Velvet sleeves : cral ligi tailor dans Tenebrous mountains<br>
Stats :

<br>&nbsp;<br>

</font>&nbsp;<br></td></tr><tr><td colspan='2' bgcolor='#0B5040'><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2' color='white'><b>&nbsp;Liste des drops par zone</b></font></td></tr><tr><td width ='10'>&nbsp;</td><td><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>&nbsp;<br>
<b>Dawnshroud Peaks</b>
<ul>
<li>cunning rockhopper - onyx studded medal - cloak
<li>dire wolf - mark of anthems - gauntlets
<li>sambata brander - seared brand - gridle
<li>studded stinegrabber - ruby studded medal - helm
<li>greater zelniak - opal studded medal - pauldrons
</ul>
<b>Mons Letalis</b>
<ul>
<li>honored spire spirit - star ruby studded medal - boots
<li>studded stonegrabber - diamond studded medal - breastplate
<li>shik nar legionnaire - fire emerald studded medal - gauntlets
<li>vigorous rockhopper - red stone idol - sword
<li>dishonorable rockhopper - sapphire studded medal - vambraces (?)
</ul>
<b>Tenebrous Mountains</b>
<ul>
<li>coterie duelist - mark of music - breasplate
<li>ancient darkwing bat - mark of melody - cloak
<li>meeda hune hero - emerald studded medal - greaves
<li>grol baku chanter - mark of rythm - helm
<li>cral ligi tailor - velvet sleeves - vambraces
</ul>
<b>Twilight Sea</b>
<ul>
<li>venerable sea turtle -  mark of poetry - boots
<li>immense underbulk - mark of song - bracers
<li>cral ligi rocklord - porous rock - cloak
<li>tenacious turtle - peridot studded medal - girdle
<li>scanveger minnow - mark of psalms - gorget
<li>grol baku drummer - mark of the drum - greaves
<li>tenacious shadow - fancy necklace - helm
<li>vas ren tenor - mark of tenor - mask
<li>cral ligi hero - moonstone studded medal - sword
</ul>
<b>Scarlet Desert</b>
<ul>
<li>vigorous rockhopper - pearl studded medal - bracer
<li>sun revenant - blakc pearl studded medal - gorget
<li>grol baku wiseman - memory crystal - greaves
<li>forsaken lightcrawler - star sapphire studded medal - mask
<li>vas ren musician - mark of the mandolin - pauldrons
<li>bloodtribe chanter - mark of chants - sword
<li>tro jeg entertainer - mark of entertainment - vambraces
</ul>



</font>&nbsp;<br></td></tr></table>&nbsp;<br></font></td></tr></table>
</td></tr><tr><td>
<table width='680' border='0' cellspacing='0' cellpadding='0'>
<tr><td width='680' height='1'><img src='./img/commun/c01/carre50.gif' width='680' height='1' alt='' border='0'></td></tr>
<tr><td height='2'><img src='./img/commun/transparent.gif' height='2' alt='' border='0'></td></tr>
<tr>
<td width='680' align='left' valign='top'>
<img src='./img/commun/c01/carre50.gif' width='10' height='10' border='0' alt=''>
<img src='./img/commun/c01/carre60.gif' width='10' height='10' border='0' alt=''>
<img src='./img/commun/c01/carre70.gif' width='10' height='10' border='0' alt=''>
<img src='./img/commun/c01/carre80.gif' width='10' height='10' border='0' alt=''>
</td></tr>
</table>
</td></tr><tr><td align='center'>
<A target='_blank' href='http://www.eqloft.com/'><img src='./img/commun/hebergement.gif' width='122' height='31' border='0' alt=''></a></td></tr></table>

</body>
</html>
