<!--
                 This page has been created by Renaissance IT
   Renaissance Internet Technologies Copyright (c) 1999 All Rights Reserved.

             for more info on our products, please visit :
                        http://www.renaissance.nl/

	This script has been written by Roy Boverhof <rboverhof@renaissance.nl>
	
        Pagename                : gold_analysis.html
        Last Updated    		: 31-01-2000
-->

<HTML>
<HEAD>
	<TITLE>the Seekers of Lore : Gold Analysis Chart</TITLE>
</HEAD>

<BODY BGCOLOR="#000000" TEXT="#000000" LINK="#000000" VLINK="#000000" ALINK="#000000">
<DIV ALIGN="CENTER">
<TABLE CELLSPACING = 0 CELLPADDING = 0 BORDER = 0>
<TR>
	<TD width="63"><IMG SRC = "http://www.loreseekers.com/graphics/topc000.jpg" WIDTH = 63 HEIGHT = 87></TD>
	<TD width="473"><IMG SRC = "http://www.loreseekers.com/graphics/topc001.jpg" WIDTH = 473 HEIGHT = 87></TD>
	<TD width="64"><IMG SRC = "http://www.loreseekers.com/graphics/topc002.jpg" WIDTH = 64 HEIGHT = 87></TD>
</TR>
	<TD width="63"></TD>
	<TD BGCOLOR="#BEA279" width="460">
	<DIV ALIGN="CENTER">
	<TABLE>
	<TR>
	<TD BGCOLOR="#BEA279" width="450">
	
<P ALIGN="left"><FONT SIZE="4" face="helvetica"><STRONG>E. Gold Analysis</STRONG></FONT></A></P>


<!-- START OF CONVERTED OUTPUT -->
<!-- ------------------------- -->
<Table border>
<TR ALIGN="center" VALIGN="bottom">
<TD BGCOLOR=#C0C0C0><FONT FACE="Verdana" SIZE="1" COLOR=#FFFFFF><B>
Stone</B></FONT></TD>
<TD BGCOLOR=#C0C0C0><FONT FACE="Verdana" SIZE="1" COLOR=#FFFFFF><B>
Property</B></FONT></TD>
<TD BGCOLOR=#C0C0C0><FONT FACE="Verdana" SIZE="1" COLOR=#FFFFFF><B>
Cost (cp)</B></FONT></TD>
<TD BGCOLOR=#C0C0C0 STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#FFFFFF><B>
Ench Gold</B></FONT></TD>
<TD BGCOLOR=#C0C0C0><FONT FACE="Verdana" SIZE="1" COLOR=#FFFFFF><B>
Type</B></FONT></TD>
<TD BGCOLOR=#C0C0C0><FONT FACE="Verdana" SIZE="1" COLOR=#FFFFFF><B>
PP</B></FONT></TD>
<TD BGCOLOR=#C0C0C0><FONT FACE="Verdana" SIZE="1" COLOR=#FFFFFF><B>
GP</B></FONT></TD>
<TD BGCOLOR=#C0C0C0><FONT FACE="Verdana" SIZE="1" COLOR=#FFFFFF><B>
Profit (pp)</B></FONT></TD>
<TD BGCOLOR=#C0C0C0><FONT FACE="Verdana" SIZE="1" COLOR=#FFFFFF><B>
Profit (%)</B></FONT></TD>
</TR>
<TR VALIGN="bottom">
</TR>
<TR ALIGN="center" VALIGN="bottom" STYLE="vnd.ms-excel.numberformat:@">
<TD BGCOLOR=#FF9900 COLSPAN=9><FONT FACE="Verdana" SIZE="2"><B>
Useful Items (Minimum)</B></FONT></TD>
</TR>
<TR ALIGN="center" VALIGN="bottom">
<TD><FONT FACE="Verdana" SIZE="1">
Cat's Eye Agate</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
CHR</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
10710</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1">
+7</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Bracelet</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
17</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
0</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0.00"><FONT FACE="Verdana" SIZE="1">
6.29</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0%"><FONT FACE="Verdana" SIZE="1">
59%</FONT></TD>
</TR>
<TR ALIGN="center" VALIGN="bottom">
<TD><FONT FACE="Verdana" SIZE="1">
Bloodstone</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
STA</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
11025</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1">
+5</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Necklace</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
17</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
0</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0.00"><FONT FACE="Verdana" SIZE="1">
5.98</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0%"><FONT FACE="Verdana" SIZE="1">
54%</FONT></TD>
</TR>
<TR ALIGN="center" VALIGN="bottom">
<TD><FONT FACE="Verdana" SIZE="1">
Onyx</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
DEX</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
11152</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1">
+5</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Necklace</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
17</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
0</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0.00"><FONT FACE="Verdana" SIZE="1">
5.85</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0%"><FONT FACE="Verdana" SIZE="1">
52%</FONT></TD>
</TR>
<TR ALIGN="center" VALIGN="bottom">
<TD><FONT FACE="Verdana" SIZE="1">
Jasper</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
WIS</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
11287</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1">
+3</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Earring</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
18</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
0</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0.00"><FONT FACE="Verdana" SIZE="1">
6.71</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0%"><FONT FACE="Verdana" SIZE="1">
59%</FONT></TD>
</TR>
<TR ALIGN="center" VALIGN="bottom">
<TD><FONT FACE="Verdana" SIZE="1">
Carnelian</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
AGI</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
11392</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1">
+5</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Ring</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
18</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
0</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0.00"><FONT FACE="Verdana" SIZE="1">
6.61</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0%"><FONT FACE="Verdana" SIZE="1">
58%</FONT></TD>
</TR>
<TR ALIGN="center" VALIGN="bottom">
<TD><FONT FACE="Verdana" SIZE="1">
Star Rose Quartz</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
INT</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
11550</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1">
+4</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Necklace</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
18</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
0</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0.00"><FONT FACE="Verdana" SIZE="1">
6.45</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0%"><FONT FACE="Verdana" SIZE="1">
56%</FONT></TD>
</TR>
<TR ALIGN="center" VALIGN="bottom">
<TD><FONT FACE="Verdana" SIZE="1">
Amber</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
STR</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
13125</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1">
+3</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Earring</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
20</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
0</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0.00"><FONT FACE="Verdana" SIZE="1">
6.88</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0%"><FONT FACE="Verdana" SIZE="1">
52%</FONT></TD>
</TR>
<TR ALIGN="center" VALIGN="bottom">
<TD><FONT FACE="Verdana" SIZE="1">
Jade</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Mana / HP / AC</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
14175</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1">
+15/+15/+2</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Bracelet</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
22</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
0</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0.00"><FONT FACE="Verdana" SIZE="1">
7.83</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0%"><FONT FACE="Verdana" SIZE="1">
55%</FONT></TD>
</TR>
<TR ALIGN="center" VALIGN="bottom">
<TD><FONT FACE="Verdana" SIZE="1">
Opal</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Sta / Agi</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
28350</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1">
+9/+6</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Necklace</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
45</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
0</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0.00"><FONT FACE="Verdana" SIZE="1">
16.65</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0%"><FONT FACE="Verdana" SIZE="1">
59%</FONT></TD>
</TR>
<TR ALIGN="center" VALIGN="bottom">
<TD><FONT FACE="Verdana" SIZE="1">
Star Ruby</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Dex / Chr</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
78750</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1">
+7/+5</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Ring</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
130</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
0</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0.00"><FONT FACE="Verdana" SIZE="1">
51.25</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0%"><FONT FACE="Verdana" SIZE="1">
65%</FONT></TD>
</TR>
<TR ALIGN="center" VALIGN="bottom">
<TD><FONT FACE="Verdana" SIZE="1">
Fire Emerald</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Str / Dex</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
99750</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1">
+5/+3</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Bracelet</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
160</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
0</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0.00"><FONT FACE="Verdana" SIZE="1">
60.25</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0%"><FONT FACE="Verdana" SIZE="1">
60%</FONT></TD>
</TR>
<TR ALIGN="center" VALIGN="bottom">
<TD><FONT FACE="Verdana" SIZE="1">
Sapphire</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Str / Int</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
115500</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1">
+2/+4</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Earring</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
180</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
0</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0.00"><FONT FACE="Verdana" SIZE="1">
64.50</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0%"><FONT FACE="Verdana" SIZE="1">
56%</FONT></TD>
</TR>
<TR ALIGN="center" VALIGN="bottom">
<TD><FONT FACE="Verdana" SIZE="1">
Ruby</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Str / Wis</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
141500</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1">
+2/+4</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Ring</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
220</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
0</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0.00"><FONT FACE="Verdana" SIZE="1">
78.50</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0%"><FONT FACE="Verdana" SIZE="1">
55%</FONT></TD>
</TR>
<TR VALIGN="bottom">
</TR>
<TR ALIGN="center" VALIGN="bottom" STYLE="vnd.ms-excel.numberformat:@">
<TD BGCOLOR=#FF9900 COLSPAN=9><FONT FACE="Verdana" SIZE="2"><B>
Useful Items (Recommended)</B></FONT></TD>
</TR>
<TR ALIGN="center" VALIGN="bottom">
<TD><FONT FACE="Verdana" SIZE="1">
Cat's Eye Agate</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
CHR</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
10710</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1">
+7</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Bracelet</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
25</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
0</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0.00"><FONT FACE="Verdana" SIZE="1">
14.29</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0%"><FONT FACE="Verdana" SIZE="1">
133%</FONT></TD>
</TR>
<TR ALIGN="center" VALIGN="bottom">
<TD><FONT FACE="Verdana" SIZE="1">
Bloodstone</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
STA</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
11025</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1">
+5</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Necklace</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
25</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
0</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0.00"><FONT FACE="Verdana" SIZE="1">
13.98</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0%"><FONT FACE="Verdana" SIZE="1">
127%</FONT></TD>
</TR>
<TR ALIGN="center" VALIGN="bottom">
<TD><FONT FACE="Verdana" SIZE="1">
Onyx</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
DEX</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
11152</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1">
+5</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Necklace</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
25</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
0</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0.00"><FONT FACE="Verdana" SIZE="1">
13.85</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0%"><FONT FACE="Verdana" SIZE="1">
124%</FONT></TD>
</TR>
<TR ALIGN="center" VALIGN="bottom">
<TD><FONT FACE="Verdana" SIZE="1">
Jasper</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
WIS</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
11287</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1">
+3</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Earring</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
35</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
0</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0.00"><FONT FACE="Verdana" SIZE="1">
23.71</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0%"><FONT FACE="Verdana" SIZE="1">
210%</FONT></TD>
</TR>
<TR ALIGN="center" VALIGN="bottom">
<TD><FONT FACE="Verdana" SIZE="1">
Carnelian</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
AGI</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
11392</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1">
+5</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Ring</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
30</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
0</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0.00"><FONT FACE="Verdana" SIZE="1">
18.61</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0%"><FONT FACE="Verdana" SIZE="1">
163%</FONT></TD>
</TR>
<TR ALIGN="center" VALIGN="bottom">
<TD><FONT FACE="Verdana" SIZE="1">
Star Rose Quartz</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
INT</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
11550</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1">
+4</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Necklace</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
30</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
0</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0.00"><FONT FACE="Verdana" SIZE="1">
18.45</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0%"><FONT FACE="Verdana" SIZE="1">
160%</FONT></TD>
</TR>
<TR ALIGN="center" VALIGN="bottom">
<TD><FONT FACE="Verdana" SIZE="1">
Amber</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
STR</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
13125</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1">
+3</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Earring</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
35</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
0</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0.00"><FONT FACE="Verdana" SIZE="1">
21.88</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0%"><FONT FACE="Verdana" SIZE="1">
167%</FONT></TD>
</TR>
<TR ALIGN="center" VALIGN="bottom">
<TD><FONT FACE="Verdana" SIZE="1">
Jade</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Mana / HP / AC</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
14175</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1">
+15/+15/+2</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Bracelet</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
35</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
0</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0.00"><FONT FACE="Verdana" SIZE="1">
20.83</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0%"><FONT FACE="Verdana" SIZE="1">
147%</FONT></TD>
</TR>
<TR ALIGN="center" VALIGN="bottom">
<TD><FONT FACE="Verdana" SIZE="1">
Opal</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Sta / Agi</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
28350</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1">
+9/+6</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Necklace</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
60</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
0</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0.00"><FONT FACE="Verdana" SIZE="1">
31.65</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0%"><FONT FACE="Verdana" SIZE="1">
112%</FONT></TD>
</TR>
<TR ALIGN="center" VALIGN="bottom">
<TD><FONT FACE="Verdana" SIZE="1">
Star Ruby</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Dex / Chr</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
78750</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1">
+7/+5</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Ring</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
200</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
0</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0.00"><FONT FACE="Verdana" SIZE="1">
121.25</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0%"><FONT FACE="Verdana" SIZE="1">
154%</FONT></TD>
</TR>
<TR ALIGN="center" VALIGN="bottom">
<TD><FONT FACE="Verdana" SIZE="1">
Fire Emerald</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Str / Dex</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
99750</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1">
+5/+3</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Bracelet</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
220</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
0</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0.00"><FONT FACE="Verdana" SIZE="1">
120.25</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0%"><FONT FACE="Verdana" SIZE="1">
121%</FONT></TD>
</TR>
<TR ALIGN="center" VALIGN="bottom">
<TD><FONT FACE="Verdana" SIZE="1">
Sapphire</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Str / Int</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
115500</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1">
+2/+4</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Earring</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
240</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
0</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0.00"><FONT FACE="Verdana" SIZE="1">
124.50</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0%"><FONT FACE="Verdana" SIZE="1">
108%</FONT></TD>
</TR>
<TR ALIGN="center" VALIGN="bottom">
<TD><FONT FACE="Verdana" SIZE="1">
Ruby</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Str / Wis</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
141500</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1">
+2/+4</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Ring</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
260</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
0</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0.00"><FONT FACE="Verdana" SIZE="1">
118.50</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0%"><FONT FACE="Verdana" SIZE="1">
84%</FONT></TD>
</TR>
<TR VALIGN="bottom">
</TR>
<TR ALIGN="center" VALIGN="bottom" STYLE="vnd.ms-excel.numberformat:@">
<TD BGCOLOR=#FF9900 COLSPAN=9><FONT FACE="Verdana" SIZE="2"><B>
Monster Loot</B></FONT></TD>
</TR>
<TR ALIGN="center" VALIGN="bottom">
<TD><FONT FACE="Verdana" SIZE="1">
Jacinth</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Vs Magic / AC</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
11392</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1">
?</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
?</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
?</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
?</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0.00"><FONT FACE="Verdana" SIZE="1">
?</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0%"><FONT FACE="Verdana" SIZE="1">
?</FONT></TD>
</TR>
<TR ALIGN="center" VALIGN="bottom">
<TD><FONT FACE="Verdana" SIZE="1">
Wolf's Eye Agate</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Vs Magic</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
13500</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1">
+4</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Necklace</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
?</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
?</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0.00"><FONT FACE="Verdana" SIZE="1">
?</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0%"><FONT FACE="Verdana" SIZE="1">
?</FONT></TD>
</TR>
<TR ALIGN="center" VALIGN="bottom">
<TD><FONT FACE="Verdana" SIZE="1">
Black Pearl</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Dex / Agi</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
31500</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1">
+3/+3</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Ring</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
?</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
?</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0.00"><FONT FACE="Verdana" SIZE="1">
?</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0%"><FONT FACE="Verdana" SIZE="1">
?</FONT></TD>
</TR>
<TR ALIGN="center" VALIGN="bottom">
<TD><FONT FACE="Verdana" SIZE="1">
Diamond</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Vs All</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
221500</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1">
+3</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Ring</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
?</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
?</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
?</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
?</FONT></TD>
</TR>
<TR ALIGN="center" VALIGN="bottom">
<TD><FONT FACE="Verdana" SIZE="1">
Black Sapphire</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
HP / Mana</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
260500</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1">
?</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
?</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
?</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
?</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0.00"><FONT FACE="Verdana" SIZE="1">
?</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0%"><FONT FACE="Verdana" SIZE="1">
?</FONT></TD>
</TR>
<TR ALIGN="center" VALIGN="bottom">
<TD><FONT FACE="Verdana" SIZE="1">
Fire Opal</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
HP/ AC</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
260500</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1">
+30/+2</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Ring</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
?</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
?</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
?</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
?</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD BGCOLOR=#FF9900 COLSPAN=9><FONT FACE="Verdana" SIZE="2">&nbsp;</FONT></TD>
</TR>
<TR ALIGN="center" VALIGN="bottom">
<TD COLSPAN=4 STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1">
&nbsp;</FONT></TD>
<TD COLSPAN=5><FONT FACE="Verdana" SIZE="1">
Based on Information From</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="right"><FONT FACE="Verdana" SIZE="1">
&nbsp;</FONT></TD>
<TD ALIGN="right"><FONT FACE="Verdana" SIZE="1">
&nbsp;</FONT></TD>
<TD ALIGN="right"><FONT FACE="Verdana" SIZE="1">
&nbsp;</FONT></TD>
<TD ALIGN="right" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1">
&nbsp;</FONT></TD>
<TD COLSPAN=5 ALIGN="center"><FONT FACE="Verdana" SIZE="1">
Casters Realm</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD ALIGN="right"><FONT FACE="Verdana" SIZE="1">
&nbsp;</FONT></TD>
<TD ALIGN="right"><FONT FACE="Verdana" SIZE="1">
&nbsp;</FONT></TD>
<TD ALIGN="right"><FONT FACE="Verdana" SIZE="1">
&nbsp;</FONT></TD>
<TD ALIGN="right" STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1">
&nbsp;</FONT></TD>
<TD COLSPAN=5 ALIGN="center"><FONT FACE="Verdana" SIZE="1">
http://eq.castersrealm.com</FONT></TD>
</TR>
</Table>
<!-- ------------------------- -->
<!-- END OF CONVERTED OUTPUT -->
<!-- ------------------------- -->


<BR><BR><DIV ALIGN="center"><A HREF="new_jewelry_guide.phtml" TARGET="_self"><IMG SRC="back_button.jpg" WIDTH=200 HEIGHT=50 BORDER=0 ALIGN="MIDDLE" ALT="Back to the Guide"></A></DIV><BR><BR>


</TR>
</TABLE>
	<TD width="64"></TD>
<TR>
	<TD><IMG SRC = "http://www.loreseekers.com/graphics/botc000.jpg" WIDTH = 63 HEIGHT = 87></TD>
	<TD><IMG SRC = "http://www.loreseekers.com/graphics/botc001.jpg" WIDTH = 473 HEIGHT = 87></TD>
	<TD><IMG SRC = "http://www.loreseekers.com/graphics/botc002.jpg" WIDTH = 64 HEIGHT = 87></TD>
</TR>
</TABLE>
<BR>
<IMG SRC="http://service.bfast.com/bfast/serve?bfmid=1375281&siteid=40292692&bfpage=pc" BORDER="0" WIDTH="1" HEIGHT="1" NOSAVE ><A HREF="http://service.bfast.com/bfast/click?bfmid=1375281&siteid=40292692&bfpage=pc" TARGET="_new"><IMG SRC="http://affiliate.gamestop.com/affIMG/pc_120x60.gif" BORDER="0" WIDTH="120" HEIGHT="60" ALT="PC Games at GameStop.com"></A>
<BR>
<BR>
</DIV>
</BODY>
</HTML>