<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">

<html>
<head>
	<title>..:: EQBard : le site de Jonili le petit barde ::..</title>

<SCRIPT LANGUAGE="Javascript">
<!--
function fenetre(intitule,params) { 
var fen = window.open(intitule,'zoom',params); 
}
//-->
</script>

<style>
a.lientexte {color:#0B5040;text-decoration:none;}
a.lientexte:hover {color:#0B5040;text-decoration:underline;}
</style>
</head>

<body bgcolor='#CFE6E3' text='#000000' link='#0B5040' vlink='#000000' alink='#000000'>
<table width='680' border='0' cellspacing='0' cellpadding='0'>
<tr><td>
<table width='680' border='0' cellspacing='0' cellpadding='0'>
<tr>
<td width='680' align='right' valign='top'>
<img src='./img/commun/c01/carre80.gif' width='10' height='10' border='0' alt=''>
<img src='./img/commun/c01/carre70.gif' width='10' height='10' border='0' alt=''>
<img src='./img/commun/c01/carre60.gif' width='10' height='10' border='0' alt=''>
<img src='./img/commun/c01/carre50.gif' width='10' height='10' border='0' alt=''>
</td></tr>
<tr><td height='2'><img src='./img/commun/transparent.gif' height='2' alt='' border='0'></td></tr>
<tr><td width='680' height='1'><img src='./img/commun/c01/carre50.gif' width='680' height='1' alt='' border='0'></td></tr>
</table>
</td></tr><tr><td>
<table width='680' border='0' cellspacing='0' cellpadding='0'>
<tr><td width='120' valign='top'><table width='100%' border='0' cellspacing='0' cellpadding='0'>
<tr><td>
<font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>&nbsp;<br>
<img src='./img/commun/c01/carre70.gif' width='10' height='10' border='0' alt=''>&nbsp;<a href=index.php?menu=1&data=1 class=lientexte><b>Accueil</b></a><br>&nbsp;<br>
<img src='./img/commun/c01/carre70.gif' width='10' height='10' border='0' alt=''>&nbsp;<b>Equipement</b><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=32&data=31&inc=armures class=lientexte>Armures</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=33&data=31&inc=armes&order=1&sens=1&bard=1 class=lientexte>Armes</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=35&data=31&inc=slot class=lientexte>Par slot</a><br>&nbsp;<br>
<img src='./img/commun/c01/carre70.gif' width='10' height='10' border='0' alt=''>&nbsp;<b>Guides</b><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=41&data=41 class=lientexte>Général</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=42&data=42 class=lientexte>Tactiques</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carreselect.gif' width='5' height='5' border='0' alt=''>&nbsp;Quêtes<br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=44&data=44 class=lientexte>Zones</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=45&data=45 class=lientexte>Procs</a><br>&nbsp;<br>
<img src='./img/commun/c01/carre70.gif' width='10' height='10' border='0' alt=''>&nbsp;<b>Photos</b><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=51&data=51 class=lientexte>Atlas</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=52&data=52 class=lientexte>Bardes</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=54&data=54 class=lientexte>GM</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=55&data=55 class=lientexte>Divers</a><br>&nbsp;<br>
<img src='./img/commun/c01/carre70.gif' width='10' height='10' border='0' alt=''>&nbsp;<a href=index.php?menu=8&data=8 class=lientexte><b>Mode</b></a><br>&nbsp;<br>
<img src='./img/commun/c01/carre70.gif' width='10' height='10' border='0' alt=''>&nbsp;<b>Spells Sebilis</b><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=1001&data=10 class=lientexte>Barde</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=1002&data=10 class=lientexte>Belluaire</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=1003&data=10 class=lientexte>Chaman</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=1004&data=10 class=lientexte>Clerc</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=1005&data=10 class=lientexte>Druide</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=1006&data=10 class=lientexte>Enchanteur</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=1007&data=10 class=lientexte>Fléau d'ombre</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=1009&data=10 class=lientexte>Magicien</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=1012&data=10 class=lientexte>Nécromancien</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=1013&data=10 class=lientexte>Paladin</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=1014&data=10 class=lientexte>Rôdeur</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=1015&data=10 class=lientexte>Sorcier</a><br>&nbsp;<br>
<img src='./img/commun/c01/carre70.gif' width='10' height='10' border='0' alt=''>&nbsp;<a href=index.php?menu=6&data=6 class=lientexte><b>Liens</b></a><br>
<img src='./img/commun/c01/carre70.gif' width='10' height='10' border='0' alt=''>&nbsp;<a href=index.php?menu=7&data=7 class=lientexte><b>Download</b></a><br>
<img src='./img/commun/c01/carre70.gif' width='10' height='10' border='0' alt=''>&nbsp;<a href='http://forumsfr.ubi.com/messages/overview.asp?name=eq_themaeq_eqbardes' target='_blank' class=lientexte><b>Forum</b></a><br>
<img src='./img/commun/c01/carre70.gif' width='10' height='10' border='0' alt=''>&nbsp;<a href=mailto:jonili@eqbard.eqloft.com class=lientexte><b>M'écrire</b></a><br>&nbsp;<br>
<img src='./img/commun/c01/carre70.gif' width='10' height='10' border='0' alt=''>&nbsp;<a href=index.php?menu=9&data=9 class=lientexte><b>Backstage</b></a><br>&nbsp;<br></font></td></tr></table>
</td><td width='20' valign='top'><img src='./img/commun/c01/carre50.gif' width='10' height='10' border='0' alt=''>
<img src='./img/commun/c01/carre60.gif' width='10' height='10' border='0' alt=''>
<img src='./img/commun/c01/carre70.gif' width='10' height='10' border='0' alt=''>
<img src='./img/commun/c01/carre80.gif' width='10' height='10' border='0' alt=''>
</td><td width='540' align='left' valign='top'><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>&nbsp;<br><a href='index.php?menu=43&data=43 class=lientexte' class=lientexte><b>< Retour</b></a><br>&nbsp;<br><table width='100%' border='0' cellspacing='0' cellpadding='0'><tr><td colspan='2' bgcolor='#0B5040'><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2' color='white'><b>&nbsp;Nostrolo tambourine</b></font></td></tr><tr><td width ='10'>&nbsp;</td><td><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>&nbsp;<br>
Cette quête se déroule essentiellment sur Kunark. Elle consiste à récolter des pièces dans différentes zones, et à les combiner dans une boite. Pour démarrer la quête, il faut aller voir le banquier à Firiona Vie.
<br>&nbsp;<br>
<b>Commener la quête</b>
<ul>
<li>You say, "Hail Wellford Fargin"<br>
<li>Wellford Fargin turns his frown around and begins to smile. "Oh! Hello. It has been quite some time since someone has been polite and greeted me. Most adventurers are quite rude. To think I gave up my [hobby] to work day and night here!!"<br>
<li>You say, "What hobby?"<br>
<li>Wellford Fargin says "I used to collect rare coins and gems. I came to Fironia Vie to do just that, but I never have the time to [collect rare coins] when I am always here working."<br>
<li>You say, "I can collect rare coins."<br>
<li>Wellford Fargin says "If you want to help, you can begin by replacing my prized Star of Odus which was taken from my vault when I stepped out to dine. Do so, and I may trust you to collect the coins. I will also reward you with an item a composer left here."
</ul>
Il faut tout d'abord aller chercher une <b>Star of Odus</b>. Cette gemme se trouve à Erudin, chez le bijoutier. Il faut remettre la gemme à Wellford Fargin qui vous donne en échange une petite boite dans laquelle il faudra stocker les pièces. Attention, avant de donner la gemme, il faut libérer un slot de l'inventaire, sinon, la boîte disparait et il faut retourner à Erudin chercher une gemme.
<br>&nbsp;<br>
Les 6 pièces à trouver sont :
<ul>
<li>Ik Gran - Captain of the Guard dans City of Mist 
<li>Terraz Ton - Failed Raider dans Kaesora 
<li>Danak Gran - Scorpikis Scrounger dans Overthere 
<li>Veksar Gran - Bloodgill Goblins dans Lake the Ill Omen 
<li>Royal Crown of Dalnir - Kly Imprecator dans Dalnir 
<li>Torsis Ton - foragée dans Emerald Jungle 
</ul>
<b>Ik Gran</b> - Captain of the Guard dans City of Mist <br>
Le Captain of the Guard est un squelette qui pop vers l'entrée. Il suffit de tuer les mobs de l'entrée pour le faire apparaitre. lvl 36-38.
<br>&nbsp;<br>
<b>Terraz Ton</b> - Failed Raider dans Kaesora <br>
Ce mob vit dans la bibliothèque de Kaesora. Ce donjon peut être dangereux. Il vaut mieux emmener un groupe avec un druide ou un wizard pour les evacs. Pour atteidnre la bibliothèque : trou à gauche en entrant, puis à droite (pièce avec les araignées) aller dans la pièce du fond, faux mur à gauche, suivre le tunnel. Il faut nettoyer puis avancer, puis nettoyer.... jusqu'à la bibliothèque. Ensuite il suffit de vider la bibliothèque jusqu'au pop du failed raider. Le repop doit être de 18 mn. lvl 35 (à vérifier).
<br>&nbsp;<br>
<b>Danak Gran</b> - A Scorpikis Scrounger dans Overthere <br>
Les scorpions vivent dans une fosse au milieu de la zone. Le plus simple est de passer par le nord de la fosse : une pente douce permet de descendre. Les scorpions ne vont pas jusque là et il est facile d'établir le camp pour puller au pied de la pente. Les scorpions sont des SK et commencent le combat par un HT de 300-350 HP. Il suffit de puller les scorpions un par un jusqu'au spawn du scrounger. lvl 33-36.
<br>&nbsp;<br>
<b>Veksar Gran</b> - Bloodgill Goblins dans Lake the Ill Omen <br>
Les goblins sont au millieu du lac et sont toujours par 2 et de niveau 35-40.<br>
Il suffit d'avoir avec soit un druide/enchanteur pour harmoniser/mez le groupe de 2 et d'en puller 1 (attention, ils ont 130 de minimum en nage donc, avant bien monter son skill).<br>
Ils tapent entre 50-90. En général, le coin est dropé 1 fois sur 4.<br>
(merci à Velours de Vazaelle pour ces infos)
<br>&nbsp;<br>
<b>Royal Crown of Dalnir</b> - Kly Imprecator dans Dalnir <br>
Le Kly Imprecator vit au premier sous-sol du donjon. Il faut plonger dans la piscine pour atteindre le bon niveau. Il est conseillé de se munir d'une carte des lieux. On peut se déplacer en inviso dans ce donjon. Le Kly Imprecator pop dans une pièce. Il suffit de nettoyer la pièce et de s'installer dedans. lvl 30-35.
<br>&nbsp;<br>
<b>Torsis Ton</b> - foragée dans Emerald Jungle<br> 
Il suffit d'aller dans Emerald Jungle et de forager jusqu'à obtenir la pièce. C'est long.
<br>&nbsp;<br>
<b>Comment identifier les pièces ?</b>
<br>&nbsp;<br>
Dans l'inventaire, toutes les pièces sont marquées 'a rare coin'. Pour les identifier, il suffit de mémoriser le chant Lyssa's Cataloging Libretto (lvl 14). Ensuite, il faut prendre chaque pièce (la mettre au bout du cursueur) plus lancer la chanson pour identifier la pièce.
<br>&nbsp;<br>
Les pièces sont toutes normales (ni lore, ni no drop). Elles peuvent donc être récupérées auprès d'autres joueurs.
<br>&nbsp;<br>
Une fois les 6 pièces obtenues, il suffit de les placer dans la boite et de cliquer sur Combine. Il faut donner l'objet obtenu au banquier en échange du Nostrolo Tambourine.
<br>&nbsp;<br>
Le nostrolo Tambourine donne un bonus de 25% sur tous les chants à base de percussion (chants très utilisés pour le solo).

</font>&nbsp;<br></td></tr></table>&nbsp;<br>
</font></td></tr></table>
</td></tr><tr><td>
<table width='680' border='0' cellspacing='0' cellpadding='0'>
<tr><td width='680' height='1'><img src='./img/commun/c01/carre50.gif' width='680' height='1' alt='' border='0'></td></tr>
<tr><td height='2'><img src='./img/commun/transparent.gif' height='2' alt='' border='0'></td></tr>
<tr>
<td width='680' align='left' valign='top'>
<img src='./img/commun/c01/carre50.gif' width='10' height='10' border='0' alt=''>
<img src='./img/commun/c01/carre60.gif' width='10' height='10' border='0' alt=''>
<img src='./img/commun/c01/carre70.gif' width='10' height='10' border='0' alt=''>
<img src='./img/commun/c01/carre80.gif' width='10' height='10' border='0' alt=''>
</td></tr>
</table>
</td></tr><tr><td align='center'>
<A target='_blank' href='http://www.eqloft.com/'><img src='./img/commun/hebergement.gif' width='122' height='31' border='0' alt=''></a></td></tr></table>

</body>
</html>
