<!--
                 This page has been created by Renaissance IT
   Renaissance Internet Technologies Copyright (c) 1999 All Rights Reserved.

             for more info on our products, please visit :
                        http://www.renaissance.nl/

	This script has been written by Roy Boverhof <rboverhof@renaissance.nl>
	
        Pagename                : west_kunark_zones.html
        Last Updated    		: 05-14-2000
-->

<HTML>
<HEAD>
	<TITLE>the Seekers of Lore : West Kunark Region</TITLE>
</HEAD>

<BODY BGCOLOR="#000000" TEXT="#000000" LINK="#000000" VLINK="#000000" ALINK="#000000">
<DIV ALIGN="CENTER">
<BR>
<!-- FGN Banner Code -->
<script language="JavaScript">
	<!-- Hide from old browsers
	var random = new Number(Math.floor(9999999 * Math.random())+1);

	// Modify to reflect site specifics
	page = "eqlore.com/";
	target = "@Top1,x02,x05,x08!Top1";

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript1.1" SRC="http://oascentral.cybereps.com/RealMedia/ads/adstream_jx.ads/' + page + 1 + random + target + '">');
	document.write('</SCR');
	document.write('IPT>');

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript">');
	document.write('_version=10; //-->');
	document.write('</SCR');
	document.write('IPT>');

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript1.1">');
	document.write('_version=11; //-->');
	document.write('</SCR');
	document.write('IPT>');

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript">');

	if (navigator.appVersion.indexOf('MSIE 3') != -1){
	document.write('<IFRAME MARGINWIDTH=0 MARGINHEIGHT=0 HSPACE=0 VSPACE=0 FRAMEBORDER=0 SCROLLING=no BORDERCOLOR="#000000" SRC="oascentral.cybereps.com/RealMedia/ads/adstream_sx.ads/' + page + random + target + '"></IFRAME>');
	  }
	else if (_version < 11) {
	document.write ('<A HREF="http://oascentral.cybereps.com/RealMedia/ads/click_nx.ads/' + page + random + target + '"><IMG SRC="http://oascentral.cybereps.com/RealMedia/ads/adstream_nx.ads/' + page + random + target + '"></a>');
	  }

	document.write('</SCR');
	document.write('IPT>');

	// End Hide -->
</script>
<!-- END FGN Banner Code --><BR>	
<TABLE CELLSPACING = 0 CELLPADDING = 0 BORDER = 0>
<TR>
	<TD width="63"><IMG SRC = "graphics/topc000.jpg" WIDTH = 63 HEIGHT = 87></TD>
	<TD width="473"><IMG SRC = "graphics/topc001.jpg" WIDTH = 473 HEIGHT = 87></TD>
	<TD width="64"><IMG SRC = "graphics/topc002.jpg" WIDTH = 64 HEIGHT = 87></TD>
</TR>
	<TD width="63"></TD>
	<TD BGCOLOR="#BEA279" width="460">
	<DIV ALIGN="CENTER">
	<A HREF="maps.php3"><IMG SRC="graphics/atlasheader.jpg" WIDTH ="150" HEIGHT ="75" BORDER="0"></A>
	<TABLE WIDTH="460">
	<TR><TD>
	<CENTER>
<TABLE BORDER="0">
<TR>
<TD><BR><FONT COLOR="#FFFF00" SIZE="4" FACE="Ariel"><CENTER>Now choose a zone...</CENTER></FONT><BR></TD>
</TR>
<TR>
<TD>
<IMG SRC="graphics/west_kunark_zones.jpg" WIDTH=400 HEIGHT=500 BORDER=0 USEMAP="#westkunark">
<MAP NAME="westkunark">
<AREA SHAPE=RECT COORDS="146,78,235,118" HREF="map_search.php3?action=zone&add_zone=Timorous%20Deep">
<AREA SHAPE=RECT COORDS="285,92,361,129" HREF="map_search.php3?action=zone&add_zone=Howling%20Stones">
<AREA SHAPE=RECT COORDS="238,137,327,173" HREF="map_search.php3?action=zone&add_zone=The%20Overthere">
<AREA SHAPE=RECT COORDS="83,154,223,168" HREF="map_search.php3?action=zone&add_zone=Veeshan's%20Peak">
<AREA SHAPE=RECT COORDS="180,189,273,227" HREF="map_search.php3?action=zone&add_zone=Skyfire%20Mtns">
<AREA SHAPE=RECT COORDS="213,237,284,272" HREF="map_search.php3?action=zone&add_zone=Frontier%20Mnts">
<AREA SHAPE=RECT COORDS="128,240,195,274" HREF="map_search.php3?action=zone&add_zone=Burning%20Wood">
<AREA SHAPE=RECT COORDS="80,204,156,223" HREF="map_search.php3?action=zone&add_zone=Chardok">
<AREA SHAPE=RECT COORDS="152,288,226,325" HREF="map_search.php3?action=zone&add_zone=Droga">
<AREA SHAPE=RECT COORDS="240,301,338,320" HREF="map_search.php3?action=zone&add_zone=Dreadlands">
<AREA SHAPE=RECT COORDS="151,337,228,375" HREF="map_search.php3?action=zone&add_zone=Nurga">
<AREA SHAPE=RECT COORDS="250,340,324,378" HREF="map_search.php3?action=zone&add_zone=Karnor's%20Castle">
<AREA SHAPE=POLY COORDS="351,243,351,267,371,255,351,243" HREF="east_kunark_zones.phtml" ALT="To East Kunark Region">
</MAP>
</TD>
</TR>
</TABLE>
	</TD></TR>
	</TABLE>
	<TD width="64"></TD>
<TR>
	<TD><IMG SRC = "graphics/botc000.jpg" WIDTH = 63 HEIGHT = 87></TD>
	<TD><IMG SRC = "graphics/botc001.jpg" WIDTH = 473 HEIGHT = 87></TD>
	<TD><IMG SRC = "graphics/botc002.jpg" WIDTH = 64 HEIGHT = 87></TD>
</TR>
</TABLE>
<BR>
<IMG SRC="http://service.bfast.com/bfast/serve?bfmid=1375281&siteid=40292692&bfpage=pc" BORDER="0" WIDTH="1" HEIGHT="1" NOSAVE ><A HREF="http://service.bfast.com/bfast/click?bfmid=1375281&siteid=40292692&bfpage=pc" TARGET="_new"><IMG SRC="http://affiliate.gamestop.com/affIMG/pc_120x60.gif" BORDER="0" WIDTH="120" HEIGHT="60" ALT="PC Games at GameStop.com"></A>
<BR>
<BR>
</DIV>
</BODY>
</HTML>