<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">

<!-- Generated by The Webalizer  Ver. 2.01-09 -->
<!--                                          -->
<!-- Copyright 1997-2000 Bradford L. Barrett  -->
<!-- (brad@mrunix.net  http://www.mrunix.net) -->
<!--                                          -->
<!-- Distributed under the GNU GPL  Version 2 -->
<!--        Full text may be found at:        -->
<!--     http://www.mrunix.net/webalizer/     -->
<!--                                          -->
<!--  Give the power back to the programmers  -->
<!--   Support the Free Software Foundation   -->
<!--           (http://www.fsf.org)           -->
<!--                                          -->
<!-- *** Generated: 21-Dec-2002 05:38 EST *** -->

<HTML>
<HEAD>
 <TITLE>Usage Statistics for www.hossguild.com - Last 12 Months</TITLE>
</HEAD>

<BODY BGCOLOR="#E8E8E8" TEXT="#000000" LINK="#0000FF" VLINK="#FF0000">
<H2>Usage Statistics for www.hossguild.com</H2>
<SMALL><STRONG>
Summary Period: Last 12 Months<BR>
Generated 21-Dec-2002 05:38 EST<BR>
</STRONG></SMALL>
<CENTER>
<HR>
<P>
<IMG SRC="/plugins/Webalizers/hoss/usage.png" ALT="Usage summary for www.hossguild.com" HEIGHT=256 WIDTH=512><P>
<TABLE WIDTH=600 BORDER=2 CELLSPACING=1 CELLPADDING=1>
<TR><TH HEIGHT=4></TH></TR>
<TR><TH COLSPAN=11 BGCOLOR="#C0C0C0" ALIGN=center>Summary by Month</TH></TR>
<TR><TH HEIGHT=4></TH></TR>
<TR><TH ALIGN=left ROWSPAN=2 BGCOLOR="#C0C0C0"><FONT SIZE="-1">Month</FONT></TH>
<TH ALIGN=center COLSPAN=4 BGCOLOR="#C0C0C0"><FONT SIZE="-1">Daily Avg</FONT></TH>
<TH ALIGN=center COLSPAN=6 BGCOLOR="#C0C0C0"><FONT SIZE="-1">Monthly Totals</FONT></TH></TR>
<TR><TH ALIGN=center BGCOLOR="#008040"><FONT SIZE="-1">Hits</FONT></TH>
<TH ALIGN=center BGCOLOR="#0080FF"><FONT SIZE="-1">Files</FONT></TH>
<TH ALIGN=center BGCOLOR="#00E0FF"><FONT SIZE="-1">Pages</FONT></TH>
<TH ALIGN=center BGCOLOR="#FFFF00"><FONT SIZE="-1">Visits</FONT></TH>
<TH ALIGN=center BGCOLOR="#FF8000"><FONT SIZE="-1">Sites</FONT></TH>
<TH ALIGN=center BGCOLOR="#FF0000"><FONT SIZE="-1">KBytes</FONT></TH>
<TH ALIGN=center BGCOLOR="#FFFF00"><FONT SIZE="-1">Visits</FONT></TH>
<TH ALIGN=center BGCOLOR="#00E0FF"><FONT SIZE="-1">Pages</FONT></TH>
<TH ALIGN=center BGCOLOR="#0080FF"><FONT SIZE="-1">Files</FONT></TH>
<TH ALIGN=center BGCOLOR="#008040"><FONT SIZE="-1">Hits</FONT></TH></TR>
<TR><TH HEIGHT=4></TH></TR>
<TR><TD NOWRAP><A HREF="/plugins/Webalizers/hoss/usage_200212.html"><FONT SIZE="-1">Dec 2002</FONT></A></TD>
<TD ALIGN=right><FONT SIZE="-1">83730</FONT></TD>
<TD ALIGN=right><FONT SIZE="-1">32410</FONT></TD>
<TD ALIGN=right><FONT SIZE="-1">2110</FONT></TD>
<TD ALIGN=right><FONT SIZE="-1">781</FONT></TD>
<TD ALIGN=right><FONT SIZE="-1">10353</FONT></TD>
<TD ALIGN=right><FONT SIZE="-1">7440345</FONT></TD>
<TD ALIGN=right><FONT SIZE="-1">16406</FONT></TD>
<TD ALIGN=right><FONT SIZE="-1">44329</FONT></TD>
<TD ALIGN=right><FONT SIZE="-1">680629</FONT></TD>
<TD ALIGN=right><FONT SIZE="-1">1758330</FONT></TD></TR>
<TR><TD NOWRAP><A HREF="/plugins/Webalizers/hoss/usage_200211.html"><FONT SIZE="-1">Nov 2002</FONT></A></TD>
<TD ALIGN=right><FONT SIZE="-1">65626</FONT></TD>
<TD ALIGN=right><FONT SIZE="-1">24404</FONT></TD>
<TD ALIGN=right><FONT SIZE="-1">1571</FONT></TD>
<TD ALIGN=right><FONT SIZE="-1">630</FONT></TD>
<TD ALIGN=right><FONT SIZE="-1">3305</FONT></TD>
<TD ALIGN=right><FONT SIZE="-1">1466812</FONT></TD>
<TD ALIGN=right><FONT SIZE="-1">4415</FONT></TD>
<TD ALIGN=right><FONT SIZE="-1">10997</FONT></TD>
<TD ALIGN=right><FONT SIZE="-1">170831</FONT></TD>
<TD ALIGN=right><FONT SIZE="-1">459385</FONT></TD></TR>
<TR><TH HEIGHT=4></TH></TR>
<TR><TH BGCOLOR="#C0C0C0" COLSPAN=6 ALIGN=left><FONT SIZE="-1">Totals</FONT></TH>
<TH BGCOLOR="#C0C0C0" ALIGN=right><FONT SIZE="-1">8907157</FONT></TH>
<TH BGCOLOR="#C0C0C0" ALIGN=right><FONT SIZE="-1">20821</FONT></TH>
<TH BGCOLOR="#C0C0C0" ALIGN=right><FONT SIZE="-1">55326</FONT></TH>
<TH BGCOLOR="#C0C0C0" ALIGN=right><FONT SIZE="-1">851460</FONT></TH>
<TH BGCOLOR="#C0C0C0" ALIGN=right><FONT SIZE="-1">2217715</FONT></TH></TR>
<TR><TH HEIGHT=4></TH></TR>
</TABLE>
</CENTER>
<P>
<HR>
<TABLE WIDTH="100%" CELLPADDING=0 CELLSPACING=0 BORDER=0>
<TR>
<TD ALIGN=left VALIGN=top>
<SMALL>Generated by
<A HREF="http://www.mrunix.net/webalizer/"><STRONG>Webalizer Version 2.01</STRONG></A>
</SMALL>
</TD>
</TR>
</TABLE>

<!-- Webalizer Version 2.01-09 (Mod: 23-Oct-2001) -->

</BODY>
</HTML>

