<!--
                 This page has been created by Renaissance IT
   Renaissance Internet Technologies Copyright (c) 1999 All Rights Reserved.

             for more info on our products, please visit :
                        http://www.renaissance.nl/

	This script has been written by Roy Boverhof <rboverhof@renaissance.nl>
	
        Pagename                : weapons.html
        Last Updated    		: 27-7-1999
-->

<HTML>
<HEAD>
	<TITLE>Weapons</TITLE>
</HEAD>

<body BGCOLOR="#000000" TEXT="#000000">
<DIV ALIGN="CENTER">
<BR>
<!-- FGN Banner Code -->
<script language="JavaScript">
	<!-- Hide from old browsers
	var random = new Number(Math.floor(9999999 * Math.random())+1);

	// Modify to reflect site specifics
	page = "eqlore.com/";
	target = "@Top1,x02,x05,x08!Top1";

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript1.1" SRC="http://oascentral.cybereps.com/RealMedia/ads/adstream_jx.ads/' + page + 1 + random + target + '">');
	document.write('</SCR');
	document.write('IPT>');

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript">');
	document.write('_version=10; //-->');
	document.write('</SCR');
	document.write('IPT>');

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript1.1">');
	document.write('_version=11; //-->');
	document.write('</SCR');
	document.write('IPT>');

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript">');

	if (navigator.appVersion.indexOf('MSIE 3') != -1){
	document.write('<IFRAME MARGINWIDTH=0 MARGINHEIGHT=0 HSPACE=0 VSPACE=0 FRAMEBORDER=0 SCROLLING=no BORDERCOLOR="#000000" SRC="oascentral.cybereps.com/RealMedia/ads/adstream_sx.ads/' + page + random + target + '"></IFRAME>');
	  }
	else if (_version < 11) {
	document.write ('<A HREF="http://oascentral.cybereps.com/RealMedia/ads/click_nx.ads/' + page + random + target + '"><IMG SRC="http://oascentral.cybereps.com/RealMedia/ads/adstream_nx.ads/' + page + random + target + '"></a>');
	  }

	document.write('</SCR');
	document.write('IPT>');

	// End Hide -->
</script>
<!-- END FGN Banner Code --><BR>	
<TABLE CELLSPACING = 0 CELLPADDING = 0 BORDER = 0>
<TR>
	<TD width="63"><IMG SRC = "graphics/topc000.jpg" WIDTH = 63 HEIGHT = 87></TD>
	<TD width="473"><IMG SRC = "graphics/topc001.jpg" WIDTH = 473 HEIGHT = 87></TD>
	<TD width="64"><IMG SRC = "graphics/topc002.jpg" WIDTH = 64 HEIGHT = 87></TD>
</TR>
	<TD width="63"></TD>
	<TD BGCOLOR="#BEA279" width="460">
	<DIV ALIGN="CENTER">
	<IMG SRC="graphics/weaponheader.jpg" WIDTH=200 HEIGHT=75 ALT="" BORDER="0">
	<TABLE WIDTH="460">
	<TR>
		<TD>
		<DIV ALIGN="CENTER">
		<FONT COLOR="#000000">
		<BR>
		<BR>
		Just fill in the name of an Item to search our database.

		<TABLE border="0" cellpadding="3" cellspacing="3">
		<TR>
			<TD>Name : </TD>
			<TD><FORM ACTION="weapon_search.php3" METHOD="POST"><INPUT TYPE="Hidden" NAME="action" VALUE="namesearch"><INPUT TYPE="text" NAME="name" SIZE="20"></TD>
			<TD>
			<TABLE><TR><TD height=14></TD></TR><TR><TD><INPUT TYPE="Submit" VALUE="Search"></FORM></TD></TR></TABLE>
			</TD>
		</TR>
		<TR>
			<TD>Select your class : </TD>
			<TD>
			<FORM ACTION="weapon_search.php3" METHOD="POST"> 
			<INPUT TYPE="Hidden" NAME="action" VALUE="classsearch">
			<SELECT NAME="class">
			<OPTION SELECTED>Bard</OPTION>
			<OPTION>Cleric</OPTION>
			<OPTION>Druid</OPTION>
			<OPTION>Enchanter</OPTION>
			<OPTION>Magician</OPTION>
			<OPTION>Monk</OPTION>
			<OPTION>Necromancer</OPTION>
			<OPTION>Paladin</OPTION>
			<OPTION>Ranger</OPTION>
			<OPTION>Rogue</OPTION>
			<OPTION>Shadowknight</OPTION>
			<OPTION>Shaman</OPTION>
			<OPTION>Warrior</OPTION>
			<OPTION>Wizard</OPTION>
			</SELECT>
			</TD>
			<TD>
			<TABLE><TR><TD height=14></TD></TR><TR><TD><INPUT TYPE="submit" VALUE="Search"></FORM></TD></TR></TABLE>
			</TD>
		</TR>
		<TR>
			<TD>Type : </TD>
			<TD>
			<FORM ACTION="weapon_search.php3" METHOD="POST"> 
			<INPUT TYPE="Hidden" NAME="action" VALUE="typesearch">
			<SELECT NAME="type">
			<OPTION>One Hand Blunt</OPTION>
			<OPTION>One Hand Slashing</OPTION>
			<OPTION>Two Hand Blunt</OPTION>
			<OPTION>Two Hand Slashing</OPTION>
			<OPTION>Piercing</OPTION>
			<OPTION>Archery</OPTION>
			</SELECT>
			</TD>
			<TD>
			<TABLE><TR><TD height=14></TD></TR><TR><TD><INPUT TYPE="submit" VALUE="Search"></FORM></TD></TR></TABLE>
			</TD>
		</TR>
		</TABLE>
		
		</FONT>
		</DIV>
		</TD>
	</TR>
	</TABLE>
	<TD width="64"></TD>
<TR>
	<TD><IMG SRC = "graphics/botc000.jpg" WIDTH = 63 HEIGHT = 87></TD>
	<TD><IMG SRC = "graphics/botc001.jpg" WIDTH = 473 HEIGHT = 87></TD>
	<TD><IMG SRC = "graphics/botc002.jpg" WIDTH = 64 HEIGHT = 87></TD>
</TR>
</TABLE>
<BR>

<script language="JavaScript">
	<!-- Hide from old browsers
	var random = new Number(Math.floor(9999999 * Math.random())+1);

	// Modify to reflect site specifics
	page = "eqlore.com/";
	target = "@Top1,x02,x05,x08!x02";

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript1.1" SRC="http://oascentral.cybereps.com/RealMedia/ads/adstream_jx.ads/' + page + 1 + random + target + '">');
	document.write('</SCR');
	document.write('IPT>');

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript">');
	document.write('_version=10; //-->');
	document.write('</SCR');
	document.write('IPT>');

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript1.1">');
	document.write('_version=11; //-->');
	document.write('</SCR');
	document.write('IPT>');

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript">');

	if (navigator.appVersion.indexOf('MSIE 3') != -1){
	document.write('<IFRAME MARGINWIDTH=0 MARGINHEIGHT=0 HSPACE=0 VSPACE=0 FRAMEBORDER=0 SCROLLING=no BORDERCOLOR="#000000" SRC="oascentral.cybereps.com/RealMedia/ads/adstream_sx.ads/' + page + random + target + '"></IFRAME>');
	  }
	else if (_version < 11) {
	document.write ('<A HREF="http://oascentral.cybereps.com/RealMedia/ads/click_nx.ads/' + page + random + target + '"><IMG SRC="http://oascentral.cybereps.com/RealMedia/ads/adstream_nx.ads/' + page + random + target + '"></a>');
	  }

	document.write('</SCR');
	document.write('IPT>');

	// End Hide -->
</script><BR>
<BR>
</DIV>
</BODY>
</HTML>
