<!--
                 This page has been created by Renaissance IT
   Renaissance Internet Technologies Copyright (c) 1999 All Rights Reserved.

             for more info on our products, please visit :
                        http://www.renaissance.nl/

	This script has been written by Roy Boverhof <rboverhof@renaissance.nl>
	
        Pagename                : links2.html
        Last Updated    		: 03-16-2001
-->

<HTML>
<HEAD>
	<TITLE>the Seekers of Lore : Class Specific Links</TITLE>
</HEAD>

<BODY BGCOLOR="#000000" TEXT="#000000" LINK="#000000" VLINK="#000000" ALINK="#000000">
<DIV ALIGN="CENTER">
<BR>
<!-- FGN Banner Code -->
<script language="JavaScript">
	<!-- Hide from old browsers
	var random = new Number(Math.floor(9999999 * Math.random())+1);

	// Modify to reflect site specifics
	page = "eqlore.com/";
	target = "@Top1,x02,x05,x08!Top1";

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript1.1" SRC="http://oascentral.cybereps.com/RealMedia/ads/adstream_jx.ads/' + page + 1 + random + target + '">');
	document.write('</SCR');
	document.write('IPT>');

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript">');
	document.write('_version=10; //-->');
	document.write('</SCR');
	document.write('IPT>');

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript1.1">');
	document.write('_version=11; //-->');
	document.write('</SCR');
	document.write('IPT>');

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript">');

	if (navigator.appVersion.indexOf('MSIE 3') != -1){
	document.write('<IFRAME MARGINWIDTH=0 MARGINHEIGHT=0 HSPACE=0 VSPACE=0 FRAMEBORDER=0 SCROLLING=no BORDERCOLOR="#000000" SRC="oascentral.cybereps.com/RealMedia/ads/adstream_sx.ads/' + page + random + target + '"></IFRAME>');
	  }
	else if (_version < 11) {
	document.write ('<A HREF="http://oascentral.cybereps.com/RealMedia/ads/click_nx.ads/' + page + random + target + '"><IMG SRC="http://oascentral.cybereps.com/RealMedia/ads/adstream_nx.ads/' + page + random + target + '"></a>');
	  }

	document.write('</SCR');
	document.write('IPT>');

	// End Hide -->
</script>
<!-- END FGN Banner Code --><BR>
<TABLE CELLSPACING = 0 CELLPADDING = 0 BORDER = 0>
<TR>
	<TD width="63"><IMG SRC = "graphics/topc000.jpg" WIDTH = 63 HEIGHT = 87></TD>
	<TD width="473"><IMG SRC = "graphics/topc001.jpg" WIDTH = 473 HEIGHT = 87></TD>
	<TD width="64"><IMG SRC = "graphics/topc002.jpg" WIDTH = 64 HEIGHT = 87></TD>
</TR>
	<TD width="63"></TD>
	<TD BGCOLOR="#BEA279" width="460">
	<DIV ALIGN="CENTER">
	<A HREF="links.phtml"><IMG SRC="graphics/linkheader.jpg" WIDTH ="200" HEIGHT ="75" ALT="Back to Links Index" BORDER="0"></A>
	<TABLE WIDTH="440" ALIGN="center">
	<TR><TD></TD></TR>
	<TR>
		<TD>
		<A HREF="http://www.terra.es/personal2/eqnecro/" TARGET="_new"><IMG SRC="graphics/eqnecro_link.jpg" WIDTH ="220" HEIGHT ="75"></A>
		</TD>
		<TD><FONT FACE="Verdana" SIZE="-2"><FONT COLOR="#FF0000">New!&nbsp;&nbsp;</FONT> EQnecro - How to play a Necromancer.</FONT></TD>
	</TR>
	<TR>
		<TD>
		<A HREF="http://enchanter.atomicgamers.com/index.html" TARGET="_new"><IMG SRC="graphics/enchanters_assembly_link.jpg" WIDTH ="220" HEIGHT ="75" BORDER="0"></A>
		</TD>
		<TD><FONT FACE="Verdana" SIZE="-2">The Enchanter's Assembly. Focusing on all things for the Enchanters of Norrath</FONT></TD>
	</TR>
	<TR>
		<TD>
		<A HREF="http://eq.castersrealm.com/" TARGET="_new"><IMG SRC="graphics/casters_link.jpg" WIDTH ="220" HEIGHT ="75" BORDER="0" BORDER="0"></A>
		</TD>
		<TD><FONT FACE="Verdana" SIZE="-2">Excellent site specializing in the pure caster classes.</FONT></TD>
	</TR>
	<TR>
		<TD>
		<A HREF="http://www.eqdruids.com/" TARGET="_new"><IMG SRC="graphics/eqdruids_link.jpg" WIDTH ="220" HEIGHT ="75" BORDER="0"></A>
		</TD>
		<TD><FONT FACE="Verdana" SIZE="-2">EQ Druids - Home of the coolest class on Norrath!</FONT></TD>
	</TR>
	<TR>
		<TD>
		<A HREF="http://www.eqshaman.com/" TARGET="_new"><IMG SRC="graphics/eqshaman_link.jpg" WIDTH ="220" HEIGHT ="75" BORDER="0"></A>
		</TD>
		<TD><FONT FACE="Verdana" SIZE="-2">EQ Shamans - Finally a site for one of the most enjoyable classes to play!</FONT></TD>
	</TR>
	<TR>
		<TD>
		<A HREF="http://home.elp.rr.com/wolfclan/alchemy/alchemyindex.html" TARGET="_new"><IMG SRC="graphics/belgars_link.jpg" WIDTH ="220" HEIGHT ="75" BORDER="0"></A>
		</TD>
		<TD><FONT FACE="Verdana" SIZE="-2">Belgar's Ultimate Guide to Alchemy. A new site for research into the Shaman's art of potions.</FONT></TD>
	</TR>
	<TR>
		<TD>
		<A HREF="http://eqcleric.gameglow.com/" TARGET="_new"><IMG SRC="graphics/eqc_link.jpg" WIDTH ="220" HEIGHT ="75" BORDER="0"></A>
		</TD>
		<TD><FONT FACE="Verdana" SIZE="-2">Best site for the Cleric</FONT></TD>
	</TR>
	<TR>
		<TD>
		<A HREF="http://www.eqforge.com/ranger" TARGET="_new"><IMG SRC="graphics/trg_link.jpg" WIDTH ="220" HEIGHT ="75" BORDER="0"></A>
		</TD>
		<TD><FONT FACE="Verdana" SIZE="-2">One of the EQ Forge's fine sites</FONT></TD>
	</TR>
		<TR>
		<TD>
		<A HREF="http://www.eqforge.com/shadowknight" TARGET="_new"><IMG SRC="graphics/tkw_link.jpg" WIDTH ="220" HEIGHT ="75" BORDER="0"></A>
		</TD>
		<TD><FONT FACE="Verdana" SIZE="-2">One of the EQ Forge's fine sites</FONT></TD>
	</TR>
	<TR>
		<TD>
		<A HREF="http://www.eqforge.com/shaman" TARGET="_new"><IMG SRC="graphics/tsc_link.jpg" WIDTH ="220" HEIGHT ="75" BORDER="0"></A>
		</TD>
		<TD><FONT FACE="Verdana" SIZE="-2">One of the EQ Forge's fine sites</FONT></TD>
	</TR>
	<TR>
		<TD>
		<A HREF="http://www.graffe.com/" TARGET="_new"><IMG SRC="graphics/graffe_link.gif" WIDTH ="220" HEIGHT ="75" BORDER="0"></A>
		</TD>
		<TD><FONT FACE="Verdana" SIZE="-2">Graffe's Wizard Compilation - Finally an excellant resource for Wizards only.</FONT></TD>
	</TR>

	<TR>
		<TD>
		<DIV ALIGN="center"><B><A HREF="http://www.monkly-business.com" TARGET="_new"><IMG SRC="graphics/eqmonks_link.jpg" WIDTH ="220" HEIGHT ="75"></A></B></DIV>
		</TD>
		<TD><FONT FACE="Verdana" SIZE="-2">Monkly Business- This is the website authority for monks. It has many guides and quest information.</FONT></TD>
	</TR>
	
	<TR>
		<TD>
		<A HREF="http://amtgard.pinkpig.com/everquest/eqbard.htm" TARGET="_new"><IMG SRC="graphics/eqbard_link.jpg" WIDTH ="220" HEIGHT ="75" BORDER="0"></A>
		</TD>
		<TD><FONT FACE="Verdana" SIZE="-2">The EverQuesting Bard - Bardic information</FONT></TD>
	</TR>
<!--

Site is down...

	<TR>
		<TD>
		<A HREF="http://www.advancedtechnology.on.ca/eqpaladin" TARGET="_new"><IMG SRC="graphics/pon_link.jpg" WIDTH ="220" HEIGHT ="75"></A>
		</TD>
		<TD><FONT FACE="Verdana" SIZE="-2">Site devoted to the Holy Paladin</FONT></TD>
	</TR>
	
-->
	<TR>
		<TD>
		<A HREF="http://u1.lvcm.com/igmon/rogue/rogues_gallery.htm" TARGET="_new"><IMG SRC="graphics/rogue_link.jpg" WIDTH ="220" HEIGHT ="75"></A>
		</TD>
		<TD><FONT FACE="Verdana" SIZE="-2">The Rogue's Den - A site devoted to the stealthy rogue!.</FONT></TD>
	</TR>

	<TR>
		<TD></TD>
		<TD><BR><BR></TD>
	</TR>	
	
	<TR>
		<TD>
		<DIV ALIGN="center"><B><A HREF="http://necro.eqclasses.com/" TARGET="_new">necro.eqclasses.com</A></B></DIV>
		</TD>
		<TD><FONT FACE="Verdana" SIZE="-2">necro.eqclasses.com - A site devoted to necro's !.</FONT></TD>
	</TR>

	<TR>
		<TD></TD>
		<TD><BR><BR></TD>
	</TR>
	
	<TR>
		<TD>
		<A HREF="mailto:webmaster@loreseekers.com?subject=links"><IMG SRC="graphics/submit_link.jpg" WIDTH ="220" HEIGHT ="75" BORDER="0"></A>
		</TD>
		<TD><I>Do you know of a quality class specific site? Email us your link!</I></TD>
	</TR>
	</TABLE>
	<TD width="64"></TD>
<TR>
	<TD><IMG SRC = "graphics/botc000.jpg" WIDTH = 63 HEIGHT = 87></TD>
	<TD><IMG SRC = "graphics/botc001.jpg" WIDTH = 473 HEIGHT = 87></TD>
	<TD><IMG SRC = "graphics/botc002.jpg" WIDTH = 64 HEIGHT = 87></TD>
</TR>
</TABLE>
<BR>

<script language="JavaScript">
	<!-- Hide from old browsers
	var random = new Number(Math.floor(9999999 * Math.random())+1);

	// Modify to reflect site specifics
	page = "eqlore.com/";
	target = "@Top1,x02,x05,x08!x02";

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript1.1" SRC="http://oascentral.cybereps.com/RealMedia/ads/adstream_jx.ads/' + page + 1 + random + target + '">');
	document.write('</SCR');
	document.write('IPT>');

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript">');
	document.write('_version=10; //-->');
	document.write('</SCR');
	document.write('IPT>');

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript1.1">');
	document.write('_version=11; //-->');
	document.write('</SCR');
	document.write('IPT>');

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript">');

	if (navigator.appVersion.indexOf('MSIE 3') != -1){
	document.write('<IFRAME MARGINWIDTH=0 MARGINHEIGHT=0 HSPACE=0 VSPACE=0 FRAMEBORDER=0 SCROLLING=no BORDERCOLOR="#000000" SRC="oascentral.cybereps.com/RealMedia/ads/adstream_sx.ads/' + page + random + target + '"></IFRAME>');
	  }
	else if (_version < 11) {
	document.write ('<A HREF="http://oascentral.cybereps.com/RealMedia/ads/click_nx.ads/' + page + random + target + '"><IMG SRC="http://oascentral.cybereps.com/RealMedia/ads/adstream_nx.ads/' + page + random + target + '"></a>');
	  }

	document.write('</SCR');
	document.write('IPT>');

	// End Hide -->
</script><BR>
<BR>
</DIV>
</BODY>
</HTML>


