<!--
                 This page has been created by Renaissance IT
   Renaissance Internet Technologies Copyright (c) 1999 All Rights Reserved.

             for more info on our products, please visit :
                        http://www.renaissance.nl/

	This script has been written by Roy Boverhof <rboverhof@renaissance.nl>
	
        Pagename                : west_kunark_zones.html
        Last Updated    		: 05-14-2000
-->

<HTML>
<HEAD>
	<TITLE>the Seekers of Lore : West Kunark Region</TITLE>
</HEAD>

<BODY BGCOLOR="#000000" TEXT="#000000" LINK="#000000" VLINK="#000000" ALINK="#000000">
<DIV ALIGN="CENTER">
<BR>
<script type="text/javascript"><!--
google_ad_client = "pub-0988179937943699";
google_ad_width = 468;
google_ad_height = 60;
google_ad_format = "468x60_as";
google_ad_channel ="7352298734";
google_page_url = document.location;
google_color_border = "FFFFFF";
google_color_bg = "00001F";
google_color_link = "FFFFFF";
google_color_url = "FFF000";
google_color_text = "0000FF";
//--></script>
<script type="text/javascript"
  src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
</script><BR>	
<TABLE CELLSPACING = 0 CELLPADDING = 0 BORDER = 0>
<TR>
	<TD width="63"><IMG SRC = "graphics/topc000.jpg" WIDTH = 63 HEIGHT = 87></TD>
	<TD width="473"><IMG SRC = "graphics/topc001.jpg" WIDTH = 473 HEIGHT = 87></TD>
	<TD width="64"><IMG SRC = "graphics/topc002.jpg" WIDTH = 64 HEIGHT = 87></TD>
</TR>
	<TD width="63"></TD>
	<TD BGCOLOR="#BEA279" width="460">
	<DIV ALIGN="CENTER">
	<A HREF="maps.php3"><IMG SRC="graphics/atlasheader.jpg" WIDTH ="150" HEIGHT ="75" BORDER="0"></A>
	<TABLE WIDTH="460">
	<TR><TD>
	<CENTER>
<TABLE BORDER="0">
<TR>
<TD><BR><FONT COLOR="#FFFF00" SIZE="4" FACE="Ariel"><CENTER>Now choose a zone...</CENTER></FONT><BR></TD>
</TR>
<TR>
<TD>
<IMG SRC="graphics/west_kunark_zones.jpg" WIDTH=400 HEIGHT=500 BORDER=0 USEMAP="#westkunark">
<MAP NAME="westkunark">
<AREA SHAPE=RECT COORDS="146,78,235,118" HREF="map_search.php3?action=zone&add_zone=Timorous%20Deep">
<AREA SHAPE=RECT COORDS="285,92,361,129" HREF="map_search.php3?action=zone&add_zone=Howling%20Stones">
<AREA SHAPE=RECT COORDS="238,137,327,173" HREF="map_search.php3?action=zone&add_zone=The%20Overthere">
<AREA SHAPE=RECT COORDS="83,154,223,168" HREF="map_search.php3?action=zone&add_zone=Veeshan's%20Peak">
<AREA SHAPE=RECT COORDS="180,189,273,227" HREF="map_search.php3?action=zone&add_zone=Skyfire%20Mtns">
<AREA SHAPE=RECT COORDS="213,237,284,272" HREF="map_search.php3?action=zone&add_zone=Frontier%20Mnts">
<AREA SHAPE=RECT COORDS="128,240,195,274" HREF="map_search.php3?action=zone&add_zone=Burning%20Wood">
<AREA SHAPE=RECT COORDS="80,204,156,223" HREF="map_search.php3?action=zone&add_zone=Chardok">
<AREA SHAPE=RECT COORDS="152,288,226,325" HREF="map_search.php3?action=zone&add_zone=Droga">
<AREA SHAPE=RECT COORDS="240,301,338,320" HREF="map_search.php3?action=zone&add_zone=Dreadlands">
<AREA SHAPE=RECT COORDS="151,337,228,375" HREF="map_search.php3?action=zone&add_zone=Nurga">
<AREA SHAPE=RECT COORDS="250,340,324,378" HREF="map_search.php3?action=zone&add_zone=Karnor's%20Castle">
<AREA SHAPE=POLY COORDS="351,243,351,267,371,255,351,243" HREF="east_kunark_zones.phtml" ALT="To East Kunark Region">
</MAP>
</TD>
</TR>
</TABLE>
	</TD></TR>
	</TABLE>
	<TD width="64"></TD>
<TR>
	<TD><IMG SRC = "graphics/botc000.jpg" WIDTH = 63 HEIGHT = 87></TD>
	<TD><IMG SRC = "graphics/botc001.jpg" WIDTH = 473 HEIGHT = 87></TD>
	<TD><IMG SRC = "graphics/botc002.jpg" WIDTH = 64 HEIGHT = 87></TD>
</TR>
</TABLE>
<BR>
<IMG SRC="http://service.bfast.com/bfast/serve?bfmid=1375281&siteid=40292692&bfpage=pc" BORDER="0" WIDTH="1" HEIGHT="1" NOSAVE ><A HREF="http://service.bfast.com/bfast/click?bfmid=1375281&siteid=40292692&bfpage=pc" TARGET="_new"><IMG SRC="http://affiliate.gamestop.com/affIMG/pc_120x60.gif" BORDER="0" WIDTH="120" HEIGHT="60" ALT="PC Games at GameStop.com"></A>
<BR>
<BR>
</DIV>
</BODY>
</HTML>