#!/usr/local/bin/php



<FORM ACTION="indexResponse.phtml" METHOD="POST">
<table border="0" cellpadding="20" cellspacing="20">
<tr>
<td>
<SELECT NAME="month" SIZE="1">
<option value='01'> January </option><OPTION VALUE='01'> --------- </OPTION><OPTION VALUE="01"> January </option>
<OPTION VALUE="02"> February </option>
<OPTION VALUE="03"> March </option>
<OPTION VALUE="04"> April </option>
<OPTION VALUE="05"> May </option>
<OPTION VALUE="06"> June </option>
<OPTION VALUE="07"> July </option>
<OPTION VALUE="08"> August </option>
<OPTION VALUE="09"> September </option>
<OPTION VALUE="10"> October </option>
<OPTION VALUE="11"> November </option>
<OPTION VALUE="12"> December </option>
</SELECT><br>
<font color="red" size="-1">Choose a month</font>
</td>
<td>
<SELECT NAME="year" SIZE="1">
<OPTION VALUE='2002'> 2002 </OPTION><OPTION VALUE='2002'> ------ </OPTION><OPTION VALUE="2000"> 2000 </option>
<OPTION VALUE="2001"> 2001 </option>
<OPTION VALUE="2002"> 2002 </option>
<OPTION VALUE="2003"> 2003 </option>
<OPTION VALUE="2004"> 2004 </option>
<OPTION VALUE="2005"> 2005 </option>
</SELECT><br>
<font color="red" size="-1">Choose a year</font>
</td>

</tr>

</table>

<INPUT TYPE="submit" NAME="Submit" VALUE="Submit">
<INPUT TYPE="reset" NAME="Reset" VALUE="Reset">
</FORM>


