<!--
                 This page has been created by Renaissance IT
   Renaissance Internet Technologies Copyright (c) 1999 All Rights Reserved.

             for more info on our products, please visit :
                        http://www.renaissance.nl/

	This script has been written by Roy Boverhof <rboverhof@renaissance.nl>
	
        Pagename                : faith.html
        Last Updated    		: 26-01-2000
-->

<HTML>
<HEAD>
	<TITLE>the Seekers of Lore : Faith</TITLE>
</HEAD>

<BODY BGCOLOR="#000000" TEXT="#000000" LINK="#000000" VLINK="#000000" ALINK="#000000">
<DIV ALIGN="CENTER">
<BR>
<script type="text/javascript"><!--
google_ad_client = "pub-0988179937943699";
google_ad_width = 468;
google_ad_height = 60;
google_ad_format = "468x60_as";
google_ad_channel ="7352298734";
google_page_url = document.location;
google_color_border = "FFFFFF";
google_color_bg = "00001F";
google_color_link = "FFFFFF";
google_color_url = "FFF000";
google_color_text = "0000FF";
//--></script>
<script type="text/javascript"
  src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
</script><BR>
<TABLE CELLSPACING = 0 CELLPADDING = 0 BORDER = 0>
<TR>
	<TD width="63"><IMG SRC = "../graphics/topc000.jpg" WIDTH = 63 HEIGHT = 87></TD>
	<TD width="473"><IMG SRC = "../graphics/topc001.jpg" WIDTH = 473 HEIGHT = 87></TD>
	<TD width="64"><IMG SRC = "../graphics/topc002.jpg" WIDTH = 64 HEIGHT = 87></TD>
</TR>
	<TD width="63"></TD>
	<TD BGCOLOR="#BEA279" width="460">
	<DIV ALIGN="CENTER">
	<TABLE>
	<TR>
	<TD>
		<FONT FACE="Verdana">
		<P><CENTER><B><FONT SIZE="+1">Faith</FONT></B></CENTER>
		<FONT SIZE="-1">
		May the light of Tunare shine upon you<BR>
		and make your journeys go so well<BR>
		Let the need for justice drive you<BR>
		and bring you success where others fail
		
		<P>Have faith in your fellow seekers<BR>
		always give them a helping hand<BR>
		for honor and glory are the foundations<BR>
		of this guild upon which we stand
		
		<P>Remember all our fallen comrades<BR>
		and their deeds live forever on<BR>
		Let their sacrifices live in our memories<BR>
		for in our minds they are never gone
		
		<P>During this time and this season<BR>
		I bid you joy with all i say<BR>
		I hope your family bring you joy<BR>
		and have a happy holiday<BR>
		</FONT>
		<BR>
		<B>Foladen Moonsong</B>, <FONT SIZE="-1">bard of the isles.</FONT>

		</FONT>
	</TD>
	</TR>
	</TABLE>

<TABLE>
<TR>
<TD><A HREF="http://www.loreseekers.com/tales.phtml"><IMG SRC="http://www.loreseekers.com/graphics/tales_return_link.jpg" WIDTH=200 HEIGHT=75 ALT="Read some other stories by our members!" BORDER="0"></A></TD>
</TR>
</TABLE>

	<TD width="64"></TD>
<TR>
	<TD><IMG SRC = "../graphics/botc000.jpg" WIDTH = 63 HEIGHT = 87></TD>
	<TD><IMG SRC = "../graphics/botc001.jpg" WIDTH = 473 HEIGHT = 87></TD>
	<TD><IMG SRC = "../graphics/botc002.jpg" WIDTH = 64 HEIGHT = 87></TD>
</TR>
</TABLE>
<BR>
<a href="http://wetrack.it/guidefox/a/16/b/20/e/2" TARGET="_new"><img src="http://guidefox.com/resources/atn/135x48_ani_eq2_1.gif" border="0"></a><BR>
<BR>
</DIV>
</BODY>
</HTML>

