<!--
                 This page has been created by Renaissance IT
   Renaissance Internet Technologies Copyright (c) 1999 All Rights Reserved.

             for more info on our products, please visit :
                        http://www.renaissance.nl/

	This script has been written by Roy Boverhof <rboverhof@renaissance.nl>
	
        Pagename                : links4.html
        Last Updated    		: 03-16-2001
-->

<HTML>
<HEAD>
	<TITLE>the Seekers of Lore : Specialized EQ Links</TITLE>
</HEAD>

<BODY BGCOLOR="#000000" TEXT="#000000" LINK="#BEA279" VLINK="#BEA279">
<DIV ALIGN="CENTER">
<BR>
<!-- FGN Banner Code -->
<script language="JavaScript">
	<!-- Hide from old browsers
	var random = new Number(Math.floor(9999999 * Math.random())+1);

	// Modify to reflect site specifics
	page = "eqlore.com/";
	target = "@Top1,x02,x05,x08!Top1";

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript1.1" SRC="http://oascentral.cybereps.com/RealMedia/ads/adstream_jx.ads/' + page + 1 + random + target + '">');
	document.write('</SCR');
	document.write('IPT>');

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript">');
	document.write('_version=10; //-->');
	document.write('</SCR');
	document.write('IPT>');

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript1.1">');
	document.write('_version=11; //-->');
	document.write('</SCR');
	document.write('IPT>');

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript">');

	if (navigator.appVersion.indexOf('MSIE 3') != -1){
	document.write('<IFRAME MARGINWIDTH=0 MARGINHEIGHT=0 HSPACE=0 VSPACE=0 FRAMEBORDER=0 SCROLLING=no BORDERCOLOR="#000000" SRC="oascentral.cybereps.com/RealMedia/ads/adstream_sx.ads/' + page + random + target + '"></IFRAME>');
	  }
	else if (_version < 11) {
	document.write ('<A HREF="http://oascentral.cybereps.com/RealMedia/ads/click_nx.ads/' + page + random + target + '"><IMG SRC="http://oascentral.cybereps.com/RealMedia/ads/adstream_nx.ads/' + page + random + target + '"></a>');
	  }

	document.write('</SCR');
	document.write('IPT>');

	// End Hide -->
</script>
<!-- END FGN Banner Code --><BR>
<TABLE CELLSPACING = 0 CELLPADDING = 0 BORDER = 0>
<TR>
	<TD width="63"><IMG SRC = "graphics/topc000.jpg" WIDTH = 63 HEIGHT = 87></TD>
	<TD width="473"><IMG SRC = "graphics/topc001.jpg" WIDTH = 473 HEIGHT = 87></TD>
	<TD width="64"><IMG SRC = "graphics/topc002.jpg" WIDTH = 64 HEIGHT = 87></TD>
</TR>
	<TD width="63"></TD>
	<TD BGCOLOR="#BEA279" width="460">
	<DIV ALIGN="CENTER">
	<A HREF="links.phtml"><IMG SRC="graphics/linkheader.jpg" WIDTH ="200" HEIGHT ="75" ALT="Back to Links Index"></A>
	<TABLE WIDTH=440 ALIGN="center">
	<TR><TD></TD></TR>
	<TR>
		<TD>
		<A HREF="http://www.eqmaps.com" TARGET="_new"><IMG SRC="graphics/eqmaps_link.jpg" WIDTH ="220" HEIGHT ="75" ></A>
		</TD>
		<TD><FONT FACE="Verdana" SIZE="-2">Large collection of EQ maps, as well as a huge zone database containing items, npcs, landmarks etc.</FONT></TD>
	</TR>
	<TR>
		<TD>
		<A HREF="http://www.eqatlas.com" TARGET="_new"><IMG SRC="graphics/eqatlas_link.jpg" WIDTH ="220" HEIGHT ="75" ></A>
		</TD>
		<TD><FONT FACE="Verdana" SIZE="-2">Muse just does maps, and he does them very well. Detailed simple maps that are easy to print and regularily updated.</FONT></TD>
	</TR>
	<TR>
		<TD>
		<A HREF="http://www.nx.sakura.ne.jp/~chizuya/indexe.html" TARGET="_new"><IMG SRC="graphics/quester_link.jpg" WIDTH ="220" HEIGHT ="75" ></A>
		</TD>
		<TD><FONT FACE="Verdana" SIZE="-2">The Questers of Norrath, home of the great Maps of Veeshan server, who makes the best maps of EQ anywhere.</FONT></TD>
	</TR>
	<TR>
		<TD>
		<A HREF="http://www.eqtraders.com/" TARGET="_new"><IMG SRC="graphics/traders_link.jpg" WIDTH ="220" HEIGHT ="75" ></A>
		</TD>
		<TD><FONT FACE="Verdana" SIZE="-2">Site specializing in Trade Skills</FONT></TD>
	</TR>
	<TR>
		<TD>
		<A HREF="http://www.eqlinks.com" TARGET="_new"><IMG SRC="graphics/eqlinks_link.jpg" WIDTH ="220" HEIGHT ="75" ></A>
		</TD>
		<TD><FONT FACE="Verdana" SIZE="-2">An organized compilation of links to all EQ related websites</FONT></TD>
	</TR>
	<TR>
		<TD>
		<A HREF="http://members.home.net/federici2753/MainPage.html" TARGET="_new"><IMG SRC="graphics/eq_best_link.jpg" WIDTH ="220" HEIGHT ="75" ></A>
		</TD>
		<TD><FONT FACE="Verdana" SIZE="-2">Large compilation of Eq related links, all on one page</FONT></TD>
	</TR>
	<TR>
		<TD>
		<A HREF="mailto:webmaster@loreseekers.com?subject=links"><IMG SRC="graphics/submit_link.jpg" WIDTH ="220" HEIGHT ="75" ></A>
		</TD>
		<TD><I>Do you know a quality EverQuest site? Email us your link!</I></TD>
	</TR>
	</TABLE>
	<TD width="64"></TD>
<TR>
	<TD><IMG SRC = "graphics/botc000.jpg" WIDTH = 63 HEIGHT = 87></TD>
	<TD><IMG SRC = "graphics/botc001.jpg" WIDTH = 473 HEIGHT = 87></TD>
	<TD><IMG SRC = "graphics/botc002.jpg" WIDTH = 64 HEIGHT = 87></TD>
</TR>
</TABLE>
<BR>
<IMG SRC="http://service.bfast.com/bfast/serve?bfmid=1375281&siteid=40292692&bfpage=pc" BORDER="0" WIDTH="1" HEIGHT="1" NOSAVE ><A HREF="http://service.bfast.com/bfast/click?bfmid=1375281&siteid=40292692&bfpage=pc" TARGET="_new"><IMG SRC="http://affiliate.gamestop.com/affIMG/pc_120x60.gif" BORDER="0" WIDTH="120" HEIGHT="60" ALT="PC Games at GameStop.com"></A>
<BR>
<BR>
</DIV>
</BODY>
</HTML>

