<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">

<html>
<head>
	<title>..:: EQBard : le site de Jonili le petit barde ::..</title>

<SCRIPT LANGUAGE="Javascript">
<!--
function fenetre(intitule,params) { 
var fen = window.open(intitule,'zoom',params); 
}
//-->
</script>

<style>
a.lientexte {color:#0B5040;text-decoration:none;}
a.lientexte:hover {color:#0B5040;text-decoration:underline;}
</style>
</head>

<body bgcolor='#CFE6E3' text='#000000' link='#0B5040' vlink='#000000' alink='#000000'>
<table width='680' border='0' cellspacing='0' cellpadding='0'>
<tr><td>
<table width='680' border='0' cellspacing='0' cellpadding='0'>
<tr>
<td width='680' align='right' valign='top'>
<img src='./img/commun/c01/carre80.gif' width='10' height='10' border='0' alt=''>
<img src='./img/commun/c01/carre70.gif' width='10' height='10' border='0' alt=''>
<img src='./img/commun/c01/carre60.gif' width='10' height='10' border='0' alt=''>
<img src='./img/commun/c01/carre50.gif' width='10' height='10' border='0' alt=''>
</td></tr>
<tr><td height='2'><img src='./img/commun/transparent.gif' height='2' alt='' border='0'></td></tr>
<tr><td width='680' height='1'><img src='./img/commun/c01/carre50.gif' width='680' height='1' alt='' border='0'></td></tr>
</table>
</td></tr><tr><td>
<table width='680' border='0' cellspacing='0' cellpadding='0'>
<tr><td width='120' valign='top'><table width='100%' border='0' cellspacing='0' cellpadding='0'>
<tr><td>
<font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>&nbsp;<br>
<img src='./img/commun/c01/carre70.gif' width='10' height='10' border='0' alt=''>&nbsp;<a href=index.php?menu=1&data=1 class=lientexte><b>Accueil</b></a><br>&nbsp;<br>
<img src='./img/commun/c01/carre70.gif' width='10' height='10' border='0' alt=''>&nbsp;<b>Equipement</b><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=32&data=31&inc=armures class=lientexte>Armures</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=33&data=31&inc=armes&order=1&sens=1&bard=1 class=lientexte>Armes</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=35&data=31&inc=slot class=lientexte>Par slot</a><br>&nbsp;<br>
<img src='./img/commun/c01/carre70.gif' width='10' height='10' border='0' alt=''>&nbsp;<b>Guides</b><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=41&data=41 class=lientexte>Général</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=42&data=42 class=lientexte>Tactiques</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=43&data=43 class=lientexte>Quêtes</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carreselect.gif' width='5' height='5' border='0' alt=''>&nbsp;Zones<br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=45&data=45 class=lientexte>Procs</a><br>&nbsp;<br>
<img src='./img/commun/c01/carre70.gif' width='10' height='10' border='0' alt=''>&nbsp;<b>Photos</b><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=51&data=51 class=lientexte>Atlas</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=52&data=52 class=lientexte>Bardes</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=54&data=54 class=lientexte>GM</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=55&data=55 class=lientexte>Divers</a><br>&nbsp;<br>
<img src='./img/commun/c01/carre70.gif' width='10' height='10' border='0' alt=''>&nbsp;<a href=index.php?menu=8&data=8 class=lientexte><b>Mode</b></a><br>&nbsp;<br>
<img src='./img/commun/c01/carre70.gif' width='10' height='10' border='0' alt=''>&nbsp;<b>Spells Sebilis</b><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=1001&data=10 class=lientexte>Barde</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=1002&data=10 class=lientexte>Belluaire</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=1003&data=10 class=lientexte>Chaman</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=1004&data=10 class=lientexte>Clerc</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=1005&data=10 class=lientexte>Druide</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=1006&data=10 class=lientexte>Enchanteur</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=1007&data=10 class=lientexte>Fléau d'ombre</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=1009&data=10 class=lientexte>Magicien</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=1012&data=10 class=lientexte>Nécromancien</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=1013&data=10 class=lientexte>Paladin</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=1014&data=10 class=lientexte>Rôdeur</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=1015&data=10 class=lientexte>Sorcier</a><br>&nbsp;<br>
<img src='./img/commun/c01/carre70.gif' width='10' height='10' border='0' alt=''>&nbsp;<a href=index.php?menu=6&data=6 class=lientexte><b>Liens</b></a><br>
<img src='./img/commun/c01/carre70.gif' width='10' height='10' border='0' alt=''>&nbsp;<a href=index.php?menu=7&data=7 class=lientexte><b>Download</b></a><br>
<img src='./img/commun/c01/carre70.gif' width='10' height='10' border='0' alt=''>&nbsp;<a href='http://forumsfr.ubi.com/messages/overview.asp?name=eq_themaeq_eqbardes' target='_blank' class=lientexte><b>Forum</b></a><br>
<img src='./img/commun/c01/carre70.gif' width='10' height='10' border='0' alt=''>&nbsp;<a href=mailto:jonili@eqbard.eqloft.com class=lientexte><b>M'écrire</b></a><br>&nbsp;<br>
<img src='./img/commun/c01/carre70.gif' width='10' height='10' border='0' alt=''>&nbsp;<a href=index.php?menu=9&data=9 class=lientexte><b>Backstage</b></a><br>&nbsp;<br></font></td></tr></table>
</td><td width='20' valign='top'><img src='./img/commun/c01/carre50.gif' width='10' height='10' border='0' alt=''>
<img src='./img/commun/c01/carre60.gif' width='10' height='10' border='0' alt=''>
<img src='./img/commun/c01/carre70.gif' width='10' height='10' border='0' alt=''>
<img src='./img/commun/c01/carre80.gif' width='10' height='10' border='0' alt=''>
</td><td width='540' align='left' valign='top'><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>&nbsp;<br><a href='index.php?menu=44&data=44 class=lientexte' class=lientexte><b>< Retour</b></a><br>&nbsp;<br><table width='100%' border='0' cellspacing='0' cellpadding='0'><tr><td colspan='2' bgcolor='#0B5040'><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2' color='white'><b>&nbsp;Tower of the Frozen Shadow : généralités</b></font></td></tr><tr><td width ='10'>&nbsp;</td><td><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>&nbsp;<br>
Chaque étage dispose d'au moins 2 miroirs. Un miroir permet d'aller à Iceclad et ne nécessite pas de clé. Pour utiliser ce miroir, chaque joueur doit cliquer dessus. Le second miroir mène à l'étage supérieur. Ces miroirs nécessitent une clé, mais il suffit qu'un membre du groupe ait la clé. Ce membre clique sur le miroir pour emmener les membres du groupe placés à proximité du miroir à l'étage suivant (sauf pour le 6eme étage, voir plus loin).
<br>&nbsp;<br>
A part quelques rares named, tous les monstres de la tour ont la faction Tserinna. Tserinna est la boss de la tour. C'est une caster et elle donne quelques beaux objets (la plupart pour casters). Il y a un certains nombre de named répartis sur tous les étages qui droppent quelques beaux objets. A partir du 4eme, on peut looter des spells de lvl 39 et +.
<br>&nbsp;<br>
Les clés sont lore et no drop. On ne peut donc pas en stocker d'avance à la banque. Et si on meurt, elles restent sur le cadavre…. Il est recommandé de mémoriser un evac et, si possible, qu'un perso conserve un jeu de clé à la banque. Le plus souvent, la clé est sur un keyholder, qui, le plus souvent, spawne immédiatement après avoir tué un autre mob (soit un mob fixe, soit un mob aléatoire).
<br>&nbsp;<br>
Ce document est une compilation de plusieurs documents trouvés sur le net complétés de plusieurs visites dans la tour. Il peut comporter des erreurs, des manques, des oublis….
&nbsp;<br>

</font>&nbsp;<br></td></tr><tr><td colspan='2' bgcolor='#0B5040'><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2' color='white'><b>&nbsp;Entrée</b></font></td></tr><tr><td width ='10'>&nbsp;</td><td><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>&nbsp;<br>




En venant du camp icepaw gnoll, il y a une petite porte sur la tour (loc 2500 3000). Il suffit de cliquer dessus pour entrer.
<br>&nbsp;<br>
Légende :
<ul>
<li>E (jaune) = Point d'entrée dans l'etage
<li>X (rouge) = Miroir de sortie (au pied de la tour dans Iceclad)
<li>S (bleu) = Miroir etage suivant
</ul>
 </font>&nbsp;<br></td></tr><tr><td colspan='2' bgcolor='#0B5040'><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2' color='white'><b>&nbsp;1er Etage :</b></font></td></tr><tr><td width ='10'>&nbsp;</td><td><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>&nbsp;<br>
 

<b>Clé : </b>Pas besoin de clé pour entrer<br>
<b>Zone out : </b>Juste après être entré, il suffit de faire demi-tour, le miroir est là.<br>
<b>Zone étage supérieur : </b>En face, dans le couloir de droite.<br>
<b>Keyholder :</b> Enraged Shadow Beast<br>
<b>Placeholder : </b>N'importe quel mob de l'étage.<br>
<b>Safest Travel: </b>Invisibility to Undead
<br>&nbsp;<br>
Sur cet étage : Ice Shades, Shadowbones, et Fading Shadow Guards. Ce sont tous des undead. L'entrée sur la zone est un safe point, pas d'attaque à craindre. 
<br>&nbsp;<br>
Juste après ce passage, se trouve une grande pièce avec plusieurs couloirs. Attention, cette pièce est très glissante et il y a une fosse au mileu.
<br>&nbsp;<br>
Le miroir situé dans le couloir de gauche permet, avec la clé de Tserinna, d'aller directmeent au 7ème étage.
<br>&nbsp;<br>
Common et rare drop : Gnomeskin Armor, Fading Shadow Weapons.
<br>&nbsp;<br>
<img src="img/guides/zones/tofs/image002.gif" border="0" alt=""></img>
&nbsp;<br>
 
</font>&nbsp;<br></td></tr><tr><td colspan='2' bgcolor='#0B5040'><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2' color='white'><b>&nbsp;2eme étage : la bibliothèque</b></font></td></tr><tr><td width ='10'>&nbsp;</td><td><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>&nbsp;<br>

<b>Clé : </b>Crystal Key<br>
<b>Zone out : </b>Traverser la zone. Ne pas entrer dans le couloir en face. Longer le mur sur la gauche jusqu'à rencontrer une bibliothèque. Cliquer sur la bibliothèque pour découvrir le passage secret vers le miroir.<br>
<b>Zone étage supérieur : </b>Traverser la zone. Entrer dans le couloir en face. Le miroir est au bout.<br>
<b>Keyholder : </b>Angry librarian.;<br>
<b>Placeholder : </b>N'importe quel mob de l'étage.<br>
<b>Safest Travel : </b>Invisibility to Undead
<br>&nbsp;<br>
L'entrée sur la zone est un safe point, pas d'attaque à craindre. <br>
Tous les monstres de cet étage sont des undeads. La plupart sont des casters. Les premiers mobs à tuer sont le bibliothécaire (librarian) et son assistante.<br>
Il y a quelques named à cet étage.
<br>&nbsp;<br>
Mobs: ghostly Students, ghostly Scholars, Teacher, Librarian, Librarian Assitant
<br>&nbsp;<br>
Common et Rare Drop : Crystallized Shadow Armor (no drop)
<br>&nbsp;<br>
<b>Student's Homework (Range)</b><br>
Magic Item Lore Item, +3 INT, +15 MANA, +10 MR, WT: 1.0 <br>
Class: NEC, WIZ, MAG, ENC, Race: HUM, ERU, HIE, DEF, HEF, GNM, IKS
<br>&nbsp;<br>
<b>Teacher's Syllabus (Range)</b><br>
Magic Item Lore Item, +3 WIS, +3 INT, +20 MANA, +20 PR, WT: 0.5<br>
Class: CLR, SHM, NEC, WIZ, MAG, ENC, Race: HUM, ERU, HIE, DEF, HEF, DWF, GNM, IKS
<br>&nbsp;<br>
<b>Crystallized Shadow Tunic (Chest)</b><br>
Magic, Lore, No Drop, AC: 18, +3 STR, +2 STA, +2 CHA, +3 WIS, +10 HP, +5 MANA, WT: 5.0<br>
Class: WAR, CLR, SHD, MNK, BRD, ROG, SHM<br>
Race: HUM, BAR, ELF, DEF, TRL, OGR, GNM, IKS
<br>&nbsp;<br>
<img src="img/guides/zones/tofs/image004.gif" border="0" alt=""></img>
&nbsp;<br>
</font>&nbsp;<br></td></tr><tr><td colspan='2' bgcolor='#0B5040'><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2' color='white'><b>&nbsp;3eme étage : la cuisine</b></font></td></tr><tr><td width ='10'>&nbsp;</td><td><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>&nbsp;<br>
 


<b>Clé : </b>Three Toothed Key<br>
<b>Zone out :</b> Aller à droite. Puis deuxième couloir à gauche. Et au carrefour, à droite. Le miroir est dans la pièce.<br>
<b>Zone étage supérieur : </b>Aller à droite. Puis deuxième couloir à gauche. Ensuite, à fond. Il y a un raccourci en passant à travers la tapisserie juste avant d'arriver. Sur ce chemin, on ne rencontre que des rodeurs à priori.<br>
<b>Keyholder : </b>Enraged Shadow Beast<br>
<b>Placeholder : </b>N'importe quel mob de l'étage.<br>
<b>Safest Travel : </b>Courir.
<br>&nbsp;<br>
Sur cet étage, il y a des undead et des Armored Shadows (crétures inviquées qui voient IU)
<br>&nbsp;<br>
Il y a un named : Angry Chef. Caster plutot baleze. Drop inconnu. Il est dans la pièce SE de la zone.
<br>&nbsp;<br>
Common et rare drop : Gnomeskin Armor, Fading Shadow Weapons.
<br>&nbsp;<br>
<b>Finely Crafted Velium Ring (Ring)</b><br>
Magic Item Lore Item, AC: 2, +3 STA, +3 AGI, +15 HP, +8 FR, WT: 0.1<br>
Class: ALL, Race: ALL
<br>&nbsp;<br>
<b>Chilled Scythe (Primary)</b><br>
Magic Item Lore Item No Drop, Skill: 2HS Atk Delay: 48, DMG: 23, +4 STR, +4 DEX, +15 HP, 20 MANA, +20 CR<br>
Effect: Shock of Frost, WT: 1.0<br>
Class: WAR, SHD, NEC, Race: ERU, DEF, TRL, OGR, GNM, IKS
<br>&nbsp;<br>
<img src="img/guides/zones/tofs/image006.gif" border="0" alt=""></img>
&nbsp;<br>
 

</font>&nbsp;<br></td></tr><tr><td colspan='2' bgcolor='#0B5040'><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2' color='white'><b>&nbsp;4eme étage</b></font></td></tr><tr><td width ='10'>&nbsp;</td><td><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>&nbsp;<br>


<b>Clé : </b>Frosty Key<br>
<b>Zone out : </b>Juste après être entré, il y a une porte à droite. Elle s'ouvre avec la Frosty Key. Le miroir est au bout du couloir.<br>
<b>Zone étage supérieur : </b>Le miroir est au bout du couloir après la salle des cercueils, là où apparaît Cara.<br>
<b>Keyholder : </b>Cara Omica<br>
<b>Placeholder : </b>Amanhotep (son PH à lui est n'importe quel mob)<br>
<b>Safest Travel : </b>Invisibility (normale... A cet étage, la plupart des mobs sont considérés comme vivants).
<br>&nbsp;<br>
La plupart des mobs ici sont normaux (10% de undeads seulement). Il semblerait que Invisibility marche. Meme les momies sont indifférentes.
<br>&nbsp;<br>
Le point où on zone n'est pas safe…. Il faut être préparé à combattre en zonant. Le mieux est de reculer tout de suite contre le mur après avoir zoner. 
<br>&nbsp;<br>
Il y a des pièges dans le sol. Ils mènent à un sous-sol. Au centre du sous-sol, il y a un pot. En cliquant dessus, on revient au point d'entrée de la zone. Les trous sont symbolisés par les points roses sur le plan.
<br>&nbsp;<br>
Il y a des passages cachés à travers les murs (marqués sur la carte par un trait). Dans le couloir qui mène à Cara, il y a 4 alcôves avec des shadows dedans. Les alcôves se font face 2 à 2 et sont séparées par un faux mur. Un 5eme shadow est au niveau du faux mur. Le puller doit faire attention de puller les 3 premiers shadows sans attirer les 2 qui sont derrière le faux mur.
<br>&nbsp;<br>
De même, avant le miroir, 4 alcôves avec 4 shadows. Les shadows viennent 2 par 2. Le pull est plus facile.
<br>&nbsp;<br>
Cara Omica spawn dans la pièce juste avant le miroir pour changer d'étage.
<br>&nbsp;<br>
 

Common et rare drop : Fading Shadow Weapons, Mummy Wrappings
<br>&nbsp;<br>
<b>Prophecy Scroll (Handheld)</b><br>
Magic Item Lore Item No Drop,+2 CHA, +8 WIS, +50 MANA, WT: 1.0<br>
Class: CLR, SHM, Race: HUM, BAR, ERU, HIE, DEF, HEF
<br>&nbsp;<br>
<b>Sparkling Soul Necklace (Neck)</b><br>
Lore Item ,AC: 2,+5 DEX, +6 AGI, +5 DR, +5 MR, +5 PR,WT: 0.5 <br>
Class: ALL, Race: ALL
<br>&nbsp;<br>
<b>Embalmers Skinning Knife (Primary, Secondary)</b><br>
Magic Item, Skill: Piercing Atk Delay: 25, DMG: 4, Effect: Summon Bandages, WT: 2.0 Range: 20<br>
Class: WAR, RNG, SHD, BRD, ROG, NEC, WIZ, MAG, ENC, Race: ALL
<br>&nbsp;<br>
<b>Magnetic Dirk of Distraction (Primary, Secondary)</b><br>
Magic Item Lore Item No Drop, Skill: Piercing Atk Delay: 23, DMG: 8, +4 STR, +10 DEX, +5 MR, Effect: Distraction, WT: 3.0 <br>
Class: WAR, RNG, BRD, ROG, Race: ALL
<br>&nbsp;<br>
<b>Sorcerous Bowl (Primary)</b><br>
Magic Item Lore Item, Skill: 1HB Atk Delay: 25, DMG: 1, -5 CHA, +7 WIS, +7 INT, +50 HP, +10 MANA, +5 FR, +5 CR, +5 MR, WT: 0.5<br>
Class: NEC, WIZ, MAG, ENC, Race: HUM, ERU, HIE, DEF, HEF, GNM, IKS
<br>&nbsp;<br>
<b>Fingerbone Necklace (Neck)</b><br>
Magic Item Lore Item, AC: 2, +3 DEX, +3 WIS, +3 AGI, WT: 0.1<br>
Class: WAR, SHD, MNK, BRD, ROG, SHM, Race: HUM, BAR, ERU, DEF, HEF, TRL, OGR, IKS
<br>&nbsp;<br>
<b>Maggot Ridden Flesh (Face)</b><br>
Magic Item, AC: 2, -20 CHA, -20 DR, -20 PR, WT: 0.5<br>
Class: ALL, Race: ALL
<br>&nbsp;<br>
<b>Frost Covered Tome (Range)</b><br>
Magic Item Lore Item No Drop, +3 STR, +3 STA, +30 HP, +15 FR, WT: 1.0<br>
Class: WAR, PAL, RNG, SHD, Race: ALL
<br>&nbsp;<br>
<b>Shield of Shadows (Secondary)</b><br>
Magic Item Lore Item, AC: 15, +6 INT, 20 MANA, +12 MR, WT: 6.0<br>
Class: SHD, Race: HUM, ERU, DEF, TRL, OGR, IKS
<br>&nbsp;<br>
<img src="img/guides/zones/tofs/image008a.gif" border="0" alt=""></img>
<br>&nbsp;<br>
<img src="img/guides/zones/tofs/image008b.gif" border="0" alt=""></img>
&nbsp;<br>

</font>&nbsp;<br></td></tr><tr><td colspan='2' bgcolor='#0B5040'><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2' color='white'><b>&nbsp;5eme étage : le mariage</b></font></td></tr><tr><td width ='10'>&nbsp;</td><td><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>&nbsp;<br> 



<b>Clé : </b>Small Rusty Key<br>
<b>Zone out :</b> Sur la droite, juste après être entré.<br>
<b>Zone étage supérieur :</b> De l'autre coté de la zone, dans un couloir derrière la salle de mariage.<br>
<b>Keyholder : </b>Enraged Relative<br>
<b>Placeholder : </b>Undead Golem Usher<br>
<b>Safest Travel : </b>Invisibility to undead
<br>&nbsp;<br>
Le point d'arrivée est à priori un safe point. Aller tout de suite à gauche ! (pour éviter de cliquer sur le miroir qui est à droite et qui amène au pied de la tour, dehors…).
<br>&nbsp;<br>
Hormis les golems, tous les mobs ici sont des undeads. Pas de difficultés à cet étage (le 4 est plus difficille). Les golems de l'entrée sont les mobs les plus forts.
<br>&nbsp;<br>
Attention, bug ou skill, les mobs ont tendace à se téléporter quand ils sont low HP. Et à ramener parfois des amis à leur retour.
<br>&nbsp;<br>
Attention à l'undead Bridesmaid qui charme. A éviter.
<br>&nbsp;<br>
Common et rare drop : Crystallized Shadow Weapons, Fading Shadow Weapons, Gnome Skin Armor
<br>&nbsp;<br>
<b>Beer Stained Coldain Tunic (Chest)</b><br>
Magic Item Lore Item, AC: 12, +5 STR, +5 STA, +15 HP, +5 CR, +5 MR, +5 PR, WT: 2.0<br>
Class: WAR, CLR, PAL, RNG, SHD, DRU, MNK, BRD, ROG, SHM, Race: DWF, HFL, GNM
<br>&nbsp;<br>
<b>Velium Spiked Skull Helm (Head)</b><br>
Magic Item Lore Item No Drop, AC: 10, +5 STR, +5 CHA, +20 MANA, +5 CR, +5 DR, +5 FR, +5 MR, +5 PR, WT: 0.0<br>
Class: WAR, CLR, PAL, RNG, SHD, BRD, ROG, Race: ALL
<br>&nbsp;<br>
<b>Diamond Wedding Band (Ring)</b><br>
Magic Item Lore Item, AC: 2, +3 DEX, +5 WIS, +5 INT, +15 MANA, +8 FR, +8 CR, WT: 0.1<br>
Class: ALL, Race: ALL
<br>&nbsp;<br>
<b>Rune Etched Wedding Band (Ring)</b><br>
Magic Item Lore Item, AC: 2, +3 STR, +4 STA, +6 AGI, +15 HP, +8 DR, +8 PR, WT: 0.1<br>
Class: ALL, Race: ALL
<br>&nbsp;<br>
<b>Laced Veil (Face)</b><br>
Magic Item Lore Item, AC: 2, +4 DEX, +8 CHA, +3 AGI, +5 FR, +8 DR, WT: 0.1<br>
Class: ALL, Race: ALL
<br>&nbsp;<br>
<b>Ceremonial Wedding Sword (Primary aucun intérêt mais très belle)</b><br>
Magic Item Lore Item, +5 STR, +3 DEX, +3 STA, +3 AGI, +6 MR, WT: 5.0<br>
Class: WAR, PAL, RNG, SHD, BRD, ROG, Race: ALL
<br>&nbsp;<br>
<img src="img/guides/zones/tofs/image010.gif" border="0" alt=""></img>
&nbsp;<br>
</font>&nbsp;<br></td></tr><tr><td colspan='2' bgcolor='#0B5040'><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2' color='white'><b>&nbsp;6eme étage A</b></font></td></tr><tr><td width ='10'>&nbsp;</td><td><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>&nbsp;<br>  

<b>Clé : </b>Bone Finger Key<br>
<b>Zone out :</b> tout droit et deuxième à gauche. Grand hall rempli de spectres. Dans cette pièce, sur la droite, il y a une statue de dragon : c'est un piège. Si on s'approche, bobo….(500 dmg + dispell, et les spectres arrivent pour achver le boulot). Longer le mur de gauche tout le long de la pièce, jusqu'au miroir qui est au fond d'un petit couloir. <br>
<b>Zone étage supérieur :</b> Suivre le premier couloir à droite. Le miroir est en d'un escalier. Attention de ne pas provoquer les spectres en dessous. Le miroir ne nécessite pas de clé. Chaque membre du groupe doit cliquer sur le miroir pour changer d'étage.<br>
<b>Keyholder : </b>Pas besoin de clé pour aller au 6b.<br>
<b>Safest Travel : </b>Invisibility to undead (? A vérifier)
<br>&nbsp;<br>
Deux principaux types de mobs ici : Icy Shades and Shadow Guardians. L'entrée dans la zone est safe. C'est à priori le meilleur endroit pour établir le camp.
<br>&nbsp;<br>
Dans le couloir de gauche, les alcôves sont assez éloignées et le single pull est facile. Plus difficile dans le couloir de droite….
<br>&nbsp;<br>
Il y a un mob nommé the incoherent spirit. Il est le PH du Lucid Sprit of Abrams. Abrams spawne environ 1 fois sur 5 immédiatement après la mort de l'incoherent spirit. Abrams sert dans une quête (laquelle ?). Il est indifférent à priori. On peut le tuer sans risque pour sa faction.
 <br>&nbsp;<br>
<b>Abram's Axe of the Stoic (Primary)</b><br>
Magic Item Lore Item, AC: 5, Skill: 2HS Atk Delay: 48, DMG: 30, +15 STA, +5 CR, +5 FR, +5 MR, Effect: Invigor, WT: 9.7<br>
Class: WAR, PAL, RNG, SHD, Race: HUM, BAR, DWF, TRL, OGR<br>
Peut être une épée du même style.
<br>&nbsp;<br>
<b>Talismen of Vhal Sera (Neck)</b><br>
Magic Item Lore Item No Drop, AC: 2, +4 CHA, +3 WIS, +3 INT, WT: 0.0<br>
Class: BRD, SHM, NEC, WIZ, MAG, ENC, Race: HUM, ERU, ELF, HIE, DEF, HEF, GNM, IKS
<br>&nbsp;<br>
<b>Vhal'Sera Skull Earring (Earring)</b><br>
Magic Item Lore Item, AC: 2, +2 STR, +20 HP, +15 MANA, WT: 0.5<br>
Class: ALL, Race: ALL
<br>&nbsp;<br>
<img src="img/guides/zones/tofs/image012.gif" border="0" alt=""></img>
&nbsp;<br>
 
</font>&nbsp;<br></td></tr><tr><td colspan='2' bgcolor='#0B5040'><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2' color='white'><b>&nbsp;6eme étage B</b></font></td></tr><tr><td width ='10'>&nbsp;</td><td><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>&nbsp;<br>  

<b>Clé : </b>Pas besoin.<br>
<b>Zone out : </b>L'arrivée se fait dans un salle ronde avec un pont qui permet de sortir de la salle. Sous ce pont, il y a un miroir qui ramène à l'étage 6a. Le miroir pour revenir au pied de la tour est à l'étage 6A.<br>
<b>Zone étage supérieur : </b>Passer sur le pont, et aller derierre la piece. Pas de miroir mais une gemme.<br>
<b>Keyholder :</b> VhalSera<br>
<b>Placeholder :</b> Un spectre du 6A. Ce spectre est le seul à avoir un pet et sa robe est différente de celle des autres spectres. Il suffit de tuer tous les spectres de l'étage pour le faire spawner. Une fois tué, Valsera spawne au 6B.<br>
<b>Safest Travel :</b> None
<br>&nbsp;<br>
L'arrivée à ce niveau n'est pas safe. Une Shade Bat attend. Elle lance un spell qui pompe toute la stamina. Quand elle est morte, un Enraged Vampire spawne. Toutes les bats de l'étage font pareil.
<br>&nbsp;<br>
Ensuite, buff à fond et nettoyage des bats avant d'attaquer VhalSera (le patron de cet étage).
<br>&nbsp;<br>
VhalSera est un caster (necro/sk ?). Il peut aussi charmer (donc MR à fond). Le mieux est de vider la salle avant d'aller l'attaquer à son spawn : il a tendance à faire gate quand il est low HP.
<br>&nbsp;<br>
<img src="img/guides/zones/tofs/image014.gif" border="0" alt=""></img>
&nbsp;<br>
</font>&nbsp;<br></td></tr><tr><td colspan='2' bgcolor='#0B5040'><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2' color='white'><b>&nbsp;7eme étage</b></font></td></tr><tr><td width ='10'>&nbsp;</td><td><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>&nbsp;<br>  
 


<b>Clé : </b>Large Metal Key<br>
<b>Zone out : </b>après l'escalier en colimaçon, il y a une porte fermée. Il faut la clé. Elle ouvre sur une large salle couverte de miroir. N'importe lequel fait l'affaire.<br>
<b>Zone étage supérieur : </b>dernier étage. <br>
<b>Keyholder : </b>Tserrina (cette clé permet de passer directement au 7eme étage depuis le 1er étage)<br>
<b>Placeholder : </b>Tous les Shrouded Bats.<br>
<b>Safest Travel : </b>Y a pas
<br>&nbsp;<br>
L'arrivée est safe. Pour atteindre Tserrina, il faut éviter un piége (avec disarm trap ?). Dans la pièce avec l'escalier en colimaçon, il y a un faux mur. Avec des Shrouded Bats derierre. Il faut  les tuer pour faire spawner Tserrina.
<br>&nbsp;<br>
<b>Tserrina's Robe (Chest)</b><br>
Magic Item Lore Item No Drop, AC: 8, +3 CHA, +6 INT, +10 HP, +50 MANA, +5 CR, +10 MR, WT: 10.0<br>
Class: NEC, WIZ, MAG, ENC, Race: HUM, ERU, HIE, DEF, GNM, IKS
<br>&nbsp;<br>
<b>Tserrina's Staff (Primary)</b><br>
Magic Item Lore Item No Drop, Skill: 2HB Atk Delay: 52, DMG: 12, +5 DEX, +6 CHA, +10 INT, +15 HP, +55 MANA, +8 DR, +8 PR, Effect: Spectre Lifetap, WT: 5.0<br>
Class: NEC, WIZ, MAG, ENC, Race: HUM, ERU, HIE, DEF, HEF, GNM, IKS
<br>&nbsp;<br>
<b>Tserrina's Symbol (Neck)</b><br>
Magic Item Lore Item No Drop, AC: 3, +5 CHA, +5 WIS, +5 INT, +40 MANA, WT: 0.0<br>
Class: CLR, DRU, SHM, NEC, WIZ, MAG, ENC, Race: ALL
<br>&nbsp;<br>
<b>Tserrina's Whip (Primary, Secondary)</b><br>
Magic Item Lore Item No Drop, Skill: 1HS Atk Delay: 22, DMG: 7, +5 STR, +8 DEX, +4 AGI, Effect: Muscle Lock I, WT: 3.0<br>
Class: WAR, PAL, RNG, SHD, BRD, ROG, Race: ALL
<br>&nbsp;<br>
<b>Harnessed Soul Gem (Handheld)</b><br>
Magic Item Lore Item No Drop, +6 INT, +35 MANA, Effect: Reclaim Energy, WT: 0.1<br>
Class: MAG, Race: ALL
<br>&nbsp;<br>
<img src="img/guides/zones/tofs/image016.gif" border="0" alt=""></img>
&nbsp;<br>  

</font>&nbsp;<br></td></tr><tr><td colspan='2' bgcolor='#0B5040'><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2' color='white'><b>&nbsp;Mobs</b></font></td></tr><tr><td width ='10'>&nbsp;</td><td><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>&nbsp;<br>  
<table border=1 cellspacing=0 cellpadding=0 width="100%">
<tr> 
	<td width="35%" bgcolor="#CCCCCC"><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'><b>Nom</b></td>
	<td width="15%" bgcolor="#CCCCCC"><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'><b>Lvl</b></td>
	<td width="50%" bgcolor="#CCCCCC"><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'><b>Rmq</b></td>
</tr>
<tr> 
    <td bgcolor="#F2F2F2"><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>A Blood Familiar</td>
    <td bgcolor="#F2F2F2"><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>38 - 42</td>
    <td bgcolor="#F2F2F2"><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>Drake</td>
</tr>
<tr> 
    <td bgcolor="#CCCCCC"><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>A Frost Familiar</td>
    <td bgcolor="#CCCCCC"><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>38 - 42</td>
    <td bgcolor="#CCCCCC"><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>Drake</td>
  </tr>
  <tr> 
    <td bgcolor="#F2F2F2"><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>A Ghostly Scholar</td>
    <td bgcolor="#F2F2F2"r><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>29 - 30</td>
    <td bgcolor="#F2F2F2"><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>Undead (2)</td>
  </tr>
  <tr> 
    <td bgcolor="#CCCCCC"><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>A Ghostly Student</td>
    <td bgcolor="#CCCCCC"><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>24 - 28</td>
    <td bgcolor="#CCCCCC"><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>Undead (2)</td>
  </tr>
  <tr> 
    <td bgcolor="#F2F2F2"><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>A Ghostly Teacher</td>
    <td bgcolor="#F2F2F2"><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>29 - 30</td>
    <td bgcolor="#F2F2F2"><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>Undead (2)</td>
  </tr>
  <tr> 
    <td bgcolor="#CCCCCC"><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>A Golem Usher</td>
    <td bgcolor="#CCCCCC"><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>33 - 35</td>
    <td bgcolor="#CCCCCC"><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>Monster (4 et + ?)</td>
  </tr>
  <tr> 
    <td bgcolor="#F2F2F2"><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>A Lesser Ice Shade</td>
    <td bgcolor="#F2F2F2"><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>29 - 31</td>
    <td bgcolor="#F2F2F2"><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>Monster (dés l'étage 1)</td>
  </tr>
  <tr> 
    <td bgcolor="#CCCCCC"><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>A Librarian</td>
    <td bgcolor="#CCCCCC"><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>35 - 35</td>
    <td bgcolor="#CCCCCC"><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>Undead (2)</td>
  </tr>
  <tr> 
    <td bgcolor="#F2F2F2"><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>A Shadow</td>
    <td bgcolor="#F2F2F2"><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>32 - 32</td>
    <td bgcolor="#F2F2F2"><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>Monster</td>
  </tr>
  <tr> 
    <td bgcolor="#CCCCCC"><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>A Shadow Beast </td>
    <td bgcolor="#CCCCCC"><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>25 - 27</td>
    <td bgcolor="#CCCCCC"><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>Monster</td>
  </tr>
  <tr> 
    <td bgcolor="#F2F2F2"><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>A Shadow Beast Guard</td>
    <td bgcolor="#F2F2F2"><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>32 - 33</td>
    <td bgcolor="#F2F2F2"><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>Monster</td>
  </tr>
  <tr> 
    <td bgcolor="#CCCCCC"><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>A Shadow Familiar</td>
    <td bgcolor="#CCCCCC"><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>36 - 40</td>
    <td bgcolor="#CCCCCC"><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>Monster</td>
  </tr>
  <tr> 
    <td bgcolor="#F2F2F2"><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>A Shadowbone</td>
    <td bgcolor="#F2F2F2"><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>24 - 28</td>
    <td bgcolor="#F2F2F2"><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>Undead</td>
  </tr>
  <tr> 
    <td bgcolor="#CCCCCC"><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>A Zombie Butler</td>
    <td bgcolor="#CCCCCC"><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>29 - 30</td>
    <td bgcolor="#CCCCCC"><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>Monster</td>
  </tr>
  <tr> 
    <td bgcolor="#F2F2F2"><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>A Zombie Maid</td>
    <td bgcolor="#F2F2F2"><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>30 - 30</td>
    <td bgcolor="#F2F2F2"><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>Monster</td>
  </tr>
  <tr> 
    <td bgcolor="#CCCCCC"><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>An Ancient Mummy</td>
    <td bgcolor="#CCCCCC"><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>32 - 32</td>
    <td bgcolor="#CCCCCC"><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>Undead</td>
  </tr>
  <tr> 
    <td bgcolor="#F2F2F2"><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>An Angry Chef</td>
    <td bgcolor="#F2F2F2"><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>32 - 32</td>
    <td bgcolor="#F2F2F2"><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>Monster</td>
  </tr>
  <tr> 
    <td bgcolor="#CCCCCC"><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>An Armored Shadow</td>
    <td bgcolor="#CCCCCC"><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>35 - 38</td>
    <td bgcolor="#CCCCCC"><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>Monster</td>
  </tr>
  <tr> 
    <td bgcolor="#F2F2F2"><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>An Emerald Familiar</td>
    <td bgcolor="#F2F2F2"><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>38 - 42</td>
    <td bgcolor="#F2F2F2"><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>Drake</td>
  </tr>
  <tr> 
    <td bgcolor="#CCCCCC"><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>An Enraged Relative</td>
    <td bgcolor="#CCCCCC"><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>44 - 45</td>
    <td bgcolor="#CCCCCC"><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>Monster (<b>keyholder</b>)</td>
  </tr>
  <tr> 
    <td bgcolor="#F2F2F2"><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>An Enraged Shadow Beast</td>
    <td bgcolor="#F2F2F2"><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>33 - 34</td>
    <td bgcolor="#F2F2F2"><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>Monster (<b>keyholder</b>)</td>
  </tr>
  <tr> 
    <td bgcolor="#CCCCCC"><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>An Ice Shade</td>
    <td bgcolor="#CCCCCC"><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>36 - 37</td>
    <td bgcolor="#CCCCCC"><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>Monster</td>
  </tr>
  <tr> 
    <td bgcolor="#F2F2F2"><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>An Undead Bridesmaid</td>
    <td bgcolor="#F2F2F2"><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>33 - 33</td>
    <td bgcolor="#F2F2F2"><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>Monster (5 et + ?)</td>
  </tr>
  <tr> 
    <td bgcolor="#CCCCCC"><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>An Undead Dancer</td>
    <td bgcolor="#CCCCCC"><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>30 - 31</td>
    <td bgcolor="#CCCCCC"><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>Monster (5 et + ?)</td>
  </tr>
  <tr> 
    <td bgcolor="#F2F2F2"><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>An Undead Musician</td>
    <td bgcolor="#F2F2F2"><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>30 - 31</td>
    <td bgcolor="#F2F2F2"><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>Monster (5 et + ?)</td>
  </tr>
  <tr> 
    <td bgcolor="#CCCCCC"><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'><b>Cara Omica</b></td>
    <td bgcolor="#CCCCCC"><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>43 - 44</td>
    <td bgcolor="#CCCCCC"><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>Monster – (boss 4) - loot0</td>
  </tr>
  <tr> 
    <td bgcolor="#F2F2F2"><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'><b>Daman</b></td>
    <td bgcolor="#F2F2F2"><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>32 - 32</td>
    <td bgcolor="#F2F2F2"><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>Monster (5) - loot</td>
  </tr>
  <tr> 
    <td bgcolor="#CCCCCC"><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'><b>Incoherent Spirit</b></td>
    <td bgcolor="#CCCCCC"><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>43 - 44</td>
    <td bgcolor="#CCCCCC"><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>Monster (6) – loot ?</td>
  </tr>
  <tr> 
    <td bgcolor="#F2F2F2"><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>Isopca</td>
    <td bgcolor="#F2F2F2"><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>30 - 30</td>
    <td bgcolor="#F2F2F2"><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>Skel</td>
  </tr>
  <tr> 
    <td bgcolor="#CCCCCC"><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>Lerty</td>
    <td bgcolor="#CCCCCC"><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>30 - 30</td>
    <td bgcolor="#CCCCCC"><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>Skel</td>
  </tr>
  <tr> 
    <td bgcolor="#F2F2F2"><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>Librarian Assistant</td>
    <td bgcolor="#F2F2F2"><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>34 - 34</td>
    <td bgcolor="#F2F2F2"><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>Undead (2)</td>
  </tr>
  <tr> 
    <td bgcolor="#CCCCCC"><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>Maggot Infested Flesh /td>
    <td bgcolor="#CCCCCC"><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>37 - 38</td>
    <td bgcolor="#CCCCCC"><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>Monster</td>
  </tr>
  <tr> 
    <td bgcolor="#F2F2F2"><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'><b>Narmak Berreka</b></td>
    <td bgcolor="#F2F2F2"><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>35 - 35</td>
    <td bgcolor="#F2F2F2"><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>Armure invoquée - loot</td>
  </tr>
  <tr> 
    <td bgcolor="#CCCCCC"><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'><b>Nosja</b></td>
    <td bgcolor="#CCCCCC"><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>29 - 29</td>
    <td bgcolor="#CCCCCC"><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>Monster (5) - loot</td>
  </tr>
  <tr> 
    <td bgcolor="#F2F2F2"><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>Oozing Flesh</td>
    <td bgcolor="#F2F2F2"><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>30 - 30</td>
    <td bgcolor="#F2F2F2"><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>Flaque (4)</td>
  </tr>
  <tr> 
    <td bgcolor="#CCCCCC"><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>Priest Majes Medery</td>
    <td bgcolor="#CCCCCC"><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>33 - 33</td>
    <td bgcolor="#CCCCCC"><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>Monster – cleric ?</td>
  </tr>
  <tr> 
    <td bgcolor="#F2F2F2"><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>The Head Usher</td>
    <td bgcolor="#F2F2F2"><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>35 - 37</td>
    <td bgcolor="#F2F2F2"><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>Monster</td>
  </tr>
  <tr> 
    <td bgcolor="#CCCCCC"><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'><b>Tserrina</b></td>
    <td bgcolor="#CCCCCC"><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>51 - 51</td>
    <td bgcolor="#CCCCCC"><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>Monster (boss 7) - loot</td>
  </tr>
  <tr> 
    <td bgcolor="#F2F2F2"><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>Varjie</td>
    <td bgcolor="#F2F2F2"><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>30 - 30</td>
    <td bgcolor="#F2F2F2"><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>Skel</td>
  </tr>
  <tr> 
    <td bgcolor="#CCCCCC"><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'><b>VhalSera</b></td>
    <td bgcolor="#CCCCCC"><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>45 - 45</td>
    <td bgcolor="#CCCCCC"><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>Monster (boss 6)</td>
  </tr>
  <tr> 
    <td bgcolor="#F2F2F2"><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'><b>Zorglim the Dead</b></td>
    <td bgcolor="#F2F2F2"><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>30 - 32</td>
    <td bgcolor="#F2F2F2"><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>Undead (2)</td>
  </tr>
</table>


<br>&nbsp;<br>
</font>&nbsp;<br></td></tr></table>&nbsp;<br></font></td></tr></table>
</td></tr><tr><td>
<table width='680' border='0' cellspacing='0' cellpadding='0'>
<tr><td width='680' height='1'><img src='./img/commun/c01/carre50.gif' width='680' height='1' alt='' border='0'></td></tr>
<tr><td height='2'><img src='./img/commun/transparent.gif' height='2' alt='' border='0'></td></tr>
<tr>
<td width='680' align='left' valign='top'>
<img src='./img/commun/c01/carre50.gif' width='10' height='10' border='0' alt=''>
<img src='./img/commun/c01/carre60.gif' width='10' height='10' border='0' alt=''>
<img src='./img/commun/c01/carre70.gif' width='10' height='10' border='0' alt=''>
<img src='./img/commun/c01/carre80.gif' width='10' height='10' border='0' alt=''>
</td></tr>
</table>
</td></tr><tr><td align='center'>
<A target='_blank' href='http://www.eqloft.com/'><img src='./img/commun/hebergement.gif' width='122' height='31' border='0' alt=''></a></td></tr></table>

</body>
</html>
