<!--
                 This page has been created by Renaissance IT
   Renaissance Internet Technologies Copyright (c) 1999 All Rights Reserved.

             for more info on our products, please visit :
                        http://www.renaissance.nl/

	This script has been written by Roy Boverhof <rboverhof@renaissance.nl>
	
        Pagename                : rules.html
        Last Updated    		: 13-6-1999
-->

<HTML>
<HEAD>
	<TITLE>the Seekers of Lore : Rules</TITLE>
</HEAD>

<BODY BGCOLOR="#000000" TEXT="#FFFFFF" LINK="#FFFFFF">
<DIV ALIGN="CENTER">
<BR>
<!-- FGB Banner Code -->
<SCRIPT LANGUAGE="JavaScript">
<!-- Hide from old browsers
now = new Date();
random = now.getTime();

// Modify to reflect site specifics
site = "http://ds.cybereps.com";
target = "/SITE=FGN/AREA=EQLORE/AAMSZ=BANNER";

document.write('<IFRAME SRC="' + site + '/hserver/acc_random=' + random + target + '"');
document.write(' NORESIZE SCROLLING=NO HSPACE=0 VSPACE=0 FRAMEBORDER=0 MARGINHEIGHT=0 MARGINWIDTH=0 WIDTH=468 HEIGHT=60>');

document.write('<SCR');
document.write('IPT SRC="' + site + '/jnserver/acc_random=' + random + target + '">');
document.write('</SCR');
document.write('IPT>');

document.write('</IFRAME>');
// End Hide -->
</SCRIPT>

<NOSCRIPT><A HREF="http://ds.cybereps.com/accipiter/adclick/SITE=FGN/AREA=EQLORE/AAMSZ=BANNER"><IMG SRC="http://ds.cybereps.com/accipiter/nserver/SITE=FGN/AREA=EQLORE/AAMSZ=BANNER" border="0"></A></NOSCRIPT>
<!-- END FGB Banner Code --><BR>	
<TABLE CELLSPACING = 0 CELLPADDING = 0 BORDER = 0>
<TR>
	<TD width="63"><IMG SRC = "graphics/topc000.jpg" WIDTH = 63 HEIGHT = 87></TD>
	<TD width="473"><IMG SRC = "graphics/topc001.jpg" WIDTH = 473 HEIGHT = 87></TD>
	<TD width="64"><IMG SRC = "graphics/topc002.jpg" WIDTH = 64 HEIGHT = 87></TD>
</TR>
	<TD width="63"></TD>
	<TD BGCOLOR="#BEA279" width="460">
	<DIV ALIGN="CENTER">
	<IMG SRC="graphics/rules.jpg" WIDTH=199 HEIGHT=43 BORDER=0 ALT="">
	<BR>
	<TABLE WIDTH="420" ALIGN="center">
	<TR>
		<TD><FONT FACE="Verdana" SIZE="-1" COLOR="#000000">
		<FONT SIZE="+1">1.</FONT> Above all - HAVE FUN! The ultimate purpose of this guild is to enhance the enjoyment of EverQuest for those of us who play it.<BR><BR>

		<FONT SIZE="+1">2.</FONT> Because this is an RPG and there are so many players who wish total immersion in the world of Norrath, a Seeker should at all times "role - play" his/her character in public.<BR><BR>


Please stay 'in character' at all times you are dealing with others in a public forum. When someone meets a Seeker of Lore for the first time, we want him or her to know that we are people they would like to play with.<BR><BR>

Any 'out of character' conversations should be kept for private /TELL's, /OOC's /GUILDSAY's or /GSAY's. Under no circumstances should /SHOUT be used for any conversations that are not in character and game related.<BR><BR>

		<FONT SIZE="+1">3.</FONT> The use of vulgar or foul language in open text (ie: /OOC, /SHOUT, /AUCTION, or regular /SAY's where a third party/parties could hear it) will not be tolerated, and repeated offences could be grounds for dismissal from the guild.<BR><BR>

		<FONT SIZE="+1">4.</FONT> Harassment of another player will not be tolerated. If a dispute arises between a guild member and another character, and it can not be resolved by either party, then the guild member should then /Ignore the offending character and, if necessary, report the reason for the dispute to a GM. As well, a list of players that are well known for causing trouble, and who would be better left alone, will be maintained by the guild on it's secure member's site.<BR><BR>

		<FONT SIZE="+1">5.</FONT> The practice known as "kill stealing" will also not be tolerated. That is to say, the intentional taking of a kill from someone else who was fighting it first. This is an ambiguous area, and common sense and respect for others in a group situation must be used. For example - You are in a group that is camped at an area and who are using a rotation to take turns there, when someone arrives who attacks out of order. In this case,  "stealing" the kill back from them would be justified.<BR><BR>

Under no conditions is it acceptable to play using tactics that are considered "dirty" or "unfair". Role playing an evil character is no excuse for this type of behavior as there is no provision in the game to defend against it. Also, your actions reflect on the guild as a whole, and therefore you must act in a manor that won't adversely affect our image.<BR><BR>

		<FONT SIZE="+1">6.</FONT> Because of confusion in keeping track of members, there will be a limit of three (3) characters per server, per member that can be tagged as guild members. The reason myself and some of the officers have more then 4 characters tagged is that we need to have complete coverage of the world for guild duties, such as inviting new members.<BR><BR>

		<FONT SIZE="+1">7.</FONT> We will only accept applications from people that have achieved the minimum level of 5. We feel it is necessary for a new player to become familiar with the basic mechanics of the game and the structure of the world before attempting to join into a guild.<BR><BR>

However, if someone is an experienced player, having another character(s) above level 5, and who wishes to enter our guild with a new character, we will accept their application.<BR><BR>

		<FONT SIZE="+1">8.</FONT> All new members will have to read the guild Charter, and agree to these rules before they are accepted into the guild. They will then be considered on probation for their first month, during which time the guild can get to know them and visa versa.<BR><BR>
		</FONT>
	</TR>
	</TABLE>	
	</TD>
	<TD width="64"></TD>
<TR>
	<TD><IMG SRC = "graphics/botc000.jpg" WIDTH = 63 HEIGHT = 87></TD>
	<TD><IMG SRC = "graphics/botc001.jpg" WIDTH = 473 HEIGHT = 87></TD>
	<TD><IMG SRC = "graphics/botc002.jpg" WIDTH = 64 HEIGHT = 87></TD>
</TR>
</TABLE>
<BR>
<SCRIPT LANGUAGE="JavaScript">
<!-- Hide from old browsers
now = new Date();
random = now.getTime();

// Modify to reflect site specifics
site = "http://ds.cybereps.com";
target = "/SITE=FGN/AREA=EQLORE/AAMSZ=BUTTON1";

document.write('<IFRAME SRC="' + site + '/hserver/acc_random=' + random + target + '"');
document.write(' NORESIZE SCROLLING=NO HSPACE=0 VSPACE=0 FRAMEBORDER=0 MARGINHEIGHT=0 MARGINWIDTH=0 WIDTH=120 HEIGHT=90>');

document.write('<SCR');
document.write('IPT SRC="' + site + '/jnserver/acc_random=' + random + target + '">');
document.write('</SCR');
document.write('IPT>');

document.write('</IFRAME>');
// End Hide -->
</SCRIPT>
<NOSCRIPT> <A HREF="http://ds.cybereps.com/accipiter/adclick/SITE=FGN/AREA=EQLORE/AAMSZ=BUTTON1">
<IMG SRC="http://ds.cybereps.com/accipiter/nserver/SITE=FGN/AREA=EQLORE/AAMSZ=BUTTON1" border="0"></A>
</NOSCRIPT>
<BR>
<BR>
</DIV>
</BODY>
</HTML>

