<!--
                 This page has been created by Renaissance IT
   Renaissance Internet Technologies Copyright (c) 1999 All Rights Reserved.

             for more info on our products, please visit :
                        http://www.renaissance.nl/

	This script has been written by Roy Boverhof <rboverhof@renaissance.nl>
	
        Pagename                : files.html
        Last Updated    		: 08-12-2000
-->

<HTML>
<HEAD>
	<TITLE>the Seekers of Lore : File Library</TITLE>
</HEAD>

<BODY BGCOLOR="#000000" TEXT="#000000" LINK="#000000" VLINK="#000000" ALINK="#000000">
<DIV ALIGN="CENTER">
<BR>
<!-- FGB Banner Code -->
<SCRIPT LANGUAGE="JavaScript">
<!-- Hide from old browsers
now = new Date();
random = now.getTime();

// Modify to reflect site specifics
site = "http://ds.cybereps.com";
target = "/SITE=FGN/AREA=EQLORE/AAMSZ=BANNER";

document.write('<IFRAME SRC="' + site + '/hserver/acc_random=' + random + target + '"');
document.write(' NORESIZE SCROLLING=NO HSPACE=0 VSPACE=0 FRAMEBORDER=0 MARGINHEIGHT=0 MARGINWIDTH=0 WIDTH=468 HEIGHT=60>');

document.write('<SCR');
document.write('IPT SRC="' + site + '/jnserver/acc_random=' + random + target + '">');
document.write('</SCR');
document.write('IPT>');

document.write('</IFRAME>');
// End Hide -->
</SCRIPT>

<NOSCRIPT><A HREF="http://ds.cybereps.com/accipiter/adclick/SITE=FGN/AREA=EQLORE/AAMSZ=BANNER"><IMG SRC="http://ds.cybereps.com/accipiter/nserver/SITE=FGN/AREA=EQLORE/AAMSZ=BANNER" border="0"></A></NOSCRIPT>
<!-- END FGB Banner Code --><BR>
<TABLE CELLSPACING=0 CELLPADDING=0 BORDER=0>
<TR>
	<TD width=63><IMG SRC="graphics/topc000.jpg" WIDTH=63 HEIGHT=87></TD>
	<TD width=473><IMG SRC="graphics/topc001.jpg" WIDTH=473 HEIGHT=87></TD>
	<TD width=64><IMG SRC="graphics/topc002.jpg" WIDTH=64 HEIGHT=87></TD>
</TR>
	<TD width=63></TD>
	<TD BGCOLOR="#BEA279" width=460>
	<DIV ALIGN="CENTER">
	<IMG SRC="graphics/fileheader.jpg" WIDTH=200 HEIGHT=75>
	<TABLE WIDTH=460>
	<TR><TD>
	
<TABLE BGCOLOR="#BEA279" WIDTH=430 ALIGN="center" CELLPADDING=5 CELLSPACING=5>
<TR>
<TD BGCOLOR="#BEA279" WIDTH=15></TD>
<TD GCOLOR="#BEA279" WIDTH=400>
<FONT FACE="Verdana" SIZE=2>
<HR SIZE=2>

<B>1. <A HREF="http://files.loreseekers.com/files/EQClient.zip">EQ Client INI writer</A></B><FONT COLOR="#FF0000" SIZE="-2"> - <B>New!</B></FONT><BR>&nbsp;&nbsp;&nbsp; - <FONT SIZE="-1">by <A HREF="mailto:enoch100@hotmail.com?subject=EQClient">Gresham Dagor</A>, Seekers of Lore - Veeshan</FONT><BR><BR>

<B>2. <A HREF="http://files.loreseekers.com/files/corpse128.mp3">"Has Anybody Seen my Corpse?"</A></B><BR>&nbsp;&nbsp;&nbsp; - <FONT SIZE="-1">Very popular EQ song recently remixed<BR>&nbsp;&nbsp;&nbsp; - <FONT SIZE="-1">by <A HREF="http://www.electricfunstuff.com/efs_band.html" TARGET="_new">Electric Funstuff</A></FONT><BR><BR>

<B>3. <A HREF="http://files.loreseekers.com/files/corpse_old.mp3">"Has Anybody Seen my Corpse?"</A></B><FONT COLOR="#FF0000" SIZE="-2"> - <B>Original</B></FONT><BR>&nbsp;&nbsp;&nbsp; - <FONT SIZE="-1">The original version because some people prefer it!<BR>&nbsp;&nbsp;&nbsp; - <FONT SIZE="-1">by <A HREF="http://www.electricfunstuff.com/efs_band.html" TARGET="_new">Electric Funstuff</A></FONT><BR><BR>

<B>4. <A HREF="http://files.loreseekers.com/files/eqmapper.exe">EQMapper Ver. 2</A></B><BR>&nbsp;&nbsp;&nbsp; - <FONT SIZE="-1">by Jebo<BR>&nbsp;&nbsp;&nbsp; - <A HREF="http://www.visi.com/~abc/" TARGET="_new">EQMapper Homepage</A></FONT><BR><BR>

<B>5. <A HREF="http://files.loreseekers.com/files/eqserverscan150.zip">EQ ServerScan 1.5.x</A></B><BR>&nbsp;&nbsp;&nbsp; - <FONT SIZE="-1">by Erik Elamson, aka Duke Elam of Tarew Marr<BR>&nbsp;&nbsp;&nbsp; - <A HREF="http://www.duke.nu/eqserverscan.html">EQServerScan Homepage</A></FONT><BR><BR>

<B>6. <A HREF="http://files.loreseekers.com/files/eq_armor_jan14.zip">All Armor</A></B><BR>&nbsp;&nbsp;&nbsp; - <FONT SIZE="-1">Excel Sheet - Updated January 14th 2000</FONT><BR><BR>

<B>7. <A HREF="http://files.loreseekers.com/files/eq_weapons_mar05.zip">All Weapons</A></B><BR>&nbsp;&nbsp;&nbsp; - <FONT SIZE="-1">Excel Sheet - Updated March 05th 2000</FONT><BR><BR>

<B>8. <A HREF="http://files.loreseekers.com/files/eq_npcs_mar05.zip">All NPC's</A></B><BR>&nbsp;&nbsp;&nbsp; - <FONT SIZE="-1">Excel Sheet - Updated March 05th 2000</FONT><BR><BR>

<B>9. <A HREF="http://files.loreseekers.com/files/EQParse213.zip">EQ Log Parser ver. 2.13</A></B><BR>&nbsp;&nbsp;&nbsp; - <A HREF="http://kqp.mpog.com/EQParse/">EQ Log Parser Homepage</A><BR>&nbsp;&nbsp;&nbsp; - <FONT SIZE="-1">A handy utility</FONT><BR><BR>

<B>10. <A HREF="http://files.loreseekers.com/files/eqtheme.zip">EQ Desktop Theme Pack</A></B><BR>&nbsp;&nbsp;&nbsp; - <FONT SIZE="-1">Eq based desktop themes for Windows</FONT><BR><BR>

<B>11. <A HREF="http://files.loreseekers.com/files/eq_music.zip">EQ Music Files</A></B><BR>&nbsp;&nbsp;&nbsp; - <FONT SIZE="-1">All the MIDI music files from the game.</FONT><BR><BR>

<B>12. <A HREF="http://files.loreseekers.com/files/mwdc3_8full.zip">EQ Mana & Weapon Damage Calc. v3.8</A></B><BR>&nbsp;&nbsp;&nbsp; - <FONT SIZE="-1">A handy utility</FONT><BR><BR>
<HR SIZE=2>
</FONT>
</TD>
<TD BGCOLOR="#BEA279" width=15></TD>
</TR>
</TABLE>

	</TD></TR>
	</TABLE>
	<TD width="64"></TD>
<TR>
	<TD><IMG SRC = "graphics/botc000.jpg" WIDTH = 63 HEIGHT = 87></TD>
	<TD><IMG SRC = "graphics/botc001.jpg" WIDTH = 473 HEIGHT = 87></TD>
	<TD><IMG SRC = "graphics/botc002.jpg" WIDTH = 64 HEIGHT = 87></TD>
</TR>
</TABLE>
<BR>
<SCRIPT LANGUAGE="JavaScript">
<!-- Hide from old browsers
now = new Date();
random = now.getTime();

// Modify to reflect site specifics
site = "http://ds.cybereps.com";
target = "/SITE=FGN/AREA=EQLORE/AAMSZ=BUTTON1";

document.write('<IFRAME SRC="' + site + '/hserver/acc_random=' + random + target + '"');
document.write(' NORESIZE SCROLLING=NO HSPACE=0 VSPACE=0 FRAMEBORDER=0 MARGINHEIGHT=0 MARGINWIDTH=0 WIDTH=120 HEIGHT=90>');

document.write('<SCR');
document.write('IPT SRC="' + site + '/jnserver/acc_random=' + random + target + '">');
document.write('</SCR');
document.write('IPT>');

document.write('</IFRAME>');
// End Hide -->
</SCRIPT>
<NOSCRIPT> <A HREF="http://ds.cybereps.com/accipiter/adclick/SITE=FGN/AREA=EQLORE/AAMSZ=BUTTON1">
<IMG SRC="http://ds.cybereps.com/accipiter/nserver/SITE=FGN/AREA=EQLORE/AAMSZ=BUTTON1" border="0"></A>
</NOSCRIPT>
<BR>
<BR>
</DIV>
</BODY>
</HTML>

