<!--
                 This page has been created by Renaissance IT
   Renaissance Internet Technologies Copyright (c) 1999 All Rights Reserved.

             for more info on our products, please visit :
                        http://www.renaissance.nl/

	This script has been written by Roy Boverhof <rboverhof@renaissance.nl>
	
        Pagename                : poem.html
        Last Updated    		: 26-01-2000
-->

<HTML>
<HEAD>
	<TITLE>the Seekers of Lore : Poems</TITLE>
</HEAD>

<BODY BGCOLOR="#000000" TEXT="#000000" LINK="#000000" VLINK="#000000" ALINK="#000000">
<DIV ALIGN="CENTER">
<BR>
<!-- FGB Banner Code -->
<SCRIPT LANGUAGE="JavaScript">
   <!-- Hide from old browsers
   now = new Date();
   random = now.getTime();
     
   // Modify to reflect site specifics
   site = "http://ds.cybereps.com";
   target = "/SITE=FGN/AREA=EQLORE/AAMSZ=BANNER";
   
   document.write('<IFRAME SRC="' + site + '/hserver/acc_random=' + random + target + '"');
   document.write(' NORESIZE SCROLLING=NO HSPACE=0 VSPACE=0 FRAMEBORDER=0 MARGINHEIGHT=0 MARGINWIDTH=0 WIDTH=468 HEIGHT=60>');
   
   document.write('<SCR');
   document.write('IPT SRC="' + site + '/jnserver/acc_random=' + random + target + '">');
   document.write('</SCR');
   document.write('IPT>');
   
   document.write('</IFRAME>');
   // End Hide -->
 </SCRIPT>
 <NOSCRIPT> 
   <A HREF="http://ds.cybereps.com/accipiter/adclick/SITE=FGN/AREA=EQLORE/AAMSZ=BANNER">
   <IMG SRC="http://ds.cybereps.com/accipiter/nserver/SITE=FGN/AREA=EQLORE/AAMSZ=BANNER" border="0"></A>
 </NOSCRIPT>
<!-- END FGB Banner Code --><BR>
<TABLE CELLSPACING = 0 CELLPADDING = 0 BORDER = 0>
<TR>
	<TD width="63"><IMG SRC = "../graphics/topc000.jpg" WIDTH = 63 HEIGHT = 87></TD>
	<TD width="473"><IMG SRC = "../graphics/topc001.jpg" WIDTH = 473 HEIGHT = 87></TD>
	<TD width="64"><IMG SRC = "../graphics/topc002.jpg" WIDTH = 64 HEIGHT = 87></TD>
</TR>
	<TD width="63"></TD>
	<TD BGCOLOR="#BEA279" width="460">
	<DIV ALIGN="CENTER">
	<TABLE>
	<TR>
	<TD VALIGN="top"><IMG SRC="snowman.gif" WIDTH=80 HEIGHT=100 ALT="" BORDER="0"></TD>
	<TD>
	<FONT FACE="Verdana">
	<FONT SIZE="+1"><B><CENTER>A Foladen Xmas story</CENTER></B></FONT>
	<P>
	<FONT SIZE="-1">
	Twas the night before christmas<BR>
	and all through the guild<BR>
	everyone was stirring<BR>
	for the raid to be soon held<BR>
	<P>
	Blades were soon sharpened<BR>
	spells were quickly spun<BR>
	and requests came flowing<BR>
	for the now active jewelers fund<BR>
	<P>
	But the occasion was not joyous<BR>
	for there was a horrid tale<BR>
	Of many kendrid elves held in slavery<BR>
	and forced to work a living .....well<BR>
	<P>
	They were forced to work in shackles<BR>
	And edible goo was their fare<BR>
	They worked for a cruel master<BR>
	who for their health did not care<BR>
	<P>
	So the seekers came to pay a visit<BR>
	Upon this creature this night<BR>
	to free their captured Brethren<BR>
	To lead them to the light<BR>
	<P>
	Then the cry came from Foladen<BR>
	to attack with no mercy<BR>
	to beat the merciless beast<BR>
	and take your time do not hurry<BR>
	<P>
	Twas Dinia and Hrvatsko<BR>
	and Shraeven and Nekkon<BR>
	there was Trinitii and Blackmaer<BR>
	and of course. Dip was not forgotten<BR>
	<P>
	Onward they charged<BR>
	with lust for battle in their eyes<BR>
	while singing out<BR>
	"The Fat man must die!!!"<BR>
	<P>
	And on fought the guild<BR>
	and not a single one was slew<BR>
	for those who stand against us<BR>
	are far and very few<BR>
	<P>
	When the dust had cleared<BR>
	and the battle was over<BR>
	of the enemy only one stood<BR>
	the fat man, the reindeer lover<BR>
	<P>
	With a sense of irony<BR>
	(and a good sense of humor)<BR>
	They chained him to his own sled<BR>
	and spread a few good rumors<BR>
	<P>
	And with a smile on his face<BR>
	and tipsy from drink and fight<BR>
	Foladen shouted merry christmas to all<BR>
	and to all a good night<BR>
	</FONT>
	<BR>
	<BR>
	<B>Foladen Moonsong</B>, <FONT SIZE="-1">bard of the isles.</FONT>
	</FONT>
	<BR>
	</TD>
	<TD VALIGN="bottom"><IMG SRC="santawave.gif" WIDTH=100 HEIGHT=100 ALT="" BORDER="0"></TD>
	</TR>
	</TABLE>

<TABLE>
<TR>
<TD><A HREF="http://www.loreseekers.com/tales.phtml"><IMG SRC="http://www.loreseekers.com/graphics/tales_return_link.jpg" WIDTH=200 HEIGHT=75 ALT="Read some other stories by our members!" BORDER="0"></A></TD>
</TR>
</TABLE>

	<TD width="64"></TD>
<TR>
	<TD><IMG SRC = "../graphics/botc000.jpg" WIDTH = 63 HEIGHT = 87></TD>
	<TD><IMG SRC = "../graphics/botc001.jpg" WIDTH = 473 HEIGHT = 87></TD>
	<TD><IMG SRC = "../graphics/botc002.jpg" WIDTH = 64 HEIGHT = 87></TD>
</TR>
</TABLE>
<BR>
 <SCRIPT LANGUAGE="JavaScript">
   <!-- Hide from old browsers
   now = new Date();
   random = now.getTime();
   
   // Modify to reflect site specifics
   site = "http://ds.cybereps.com";
   target = "/SITE=FGN/AREA=EQLORE/AAMSZ=BOX";
   
   document.write('<IFRAME SRC="' + site + '/hserver/acc_random=' + random + target + '"');
   document.write(' NORESIZE SCROLLING=NO HSPACE=0 VSPACE=0 FRAMEBORDER=0 MARGINHEIGHT=0 MARGINWIDTH=0 WIDTH=125 HEIGHT=125>');
      
   document.write('<SCR');
   document.write('IPT SRC="' + site + '/jnserver/acc_random=' + random + target + '">');
   document.write('</SCR');
   document.write('IPT>');
   
   document.write('</IFRAME>');
   // End Hide -->
 </SCRIPT>
 <NOSCRIPT> 
   <A HREF="http://ds.cybereps.com/accipiter/adclick/SITE=FGN/AREA=EQLORE/AAMSZ=BOX">
   <IMG SRC="http://ds.cybereps.com/accipiter/nserver/SITE=FGN/AREA=EQLORE/AAMSZ=BOX" border="0"></A>
 </NOSCRIPT>
<BR>
<BR>
</DIV>
</BODY>
</HTML>

