<!--
                 This page has been created by Renaissance IT
   Renaissance Internet Technologies Copyright (c) 1999 All Rights Reserved.

             for more info on our products, please visit :
                        http://www.renaissance.nl/

	This script has been written by Roy Boverhof <rboverhof@renaissance.nl>
	
        Pagename                : spider_room_poem.html
        Last Updated    		: 03-28-2000
-->

<HTML>
<HEAD>
	<TITLE>the Seekers of Lore : The Spider Room Incident</TITLE>
</HEAD>

<BODY BGCOLOR="#000000" TEXT="#000000" LINK="#000000" VLINK="#000000" ALINK="#000000">
<DIV ALIGN="CENTER">
<BR>
<!-- FGN Banner Code -->
<script language="JavaScript">
	<!-- Hide from old browsers
	var random = new Number(Math.floor(9999999 * Math.random())+1);

	// Modify to reflect site specifics
	page = "eqlore.com/";
	target = "@Top1,x02,x05,x08!Top1";

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript1.1" SRC="http://oascentral.cybereps.com/RealMedia/ads/adstream_jx.ads/' + page + 1 + random + target + '">');
	document.write('</SCR');
	document.write('IPT>');

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript">');
	document.write('_version=10; //-->');
	document.write('</SCR');
	document.write('IPT>');

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript1.1">');
	document.write('_version=11; //-->');
	document.write('</SCR');
	document.write('IPT>');

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript">');

	if (navigator.appVersion.indexOf('MSIE 3') != -1){
	document.write('<IFRAME MARGINWIDTH=0 MARGINHEIGHT=0 HSPACE=0 VSPACE=0 FRAMEBORDER=0 SCROLLING=no BORDERCOLOR="#000000" SRC="oascentral.cybereps.com/RealMedia/ads/adstream_sx.ads/' + page + random + target + '"></IFRAME>');
	  }
	else if (_version < 11) {
	document.write ('<A HREF="http://oascentral.cybereps.com/RealMedia/ads/click_nx.ads/' + page + random + target + '"><IMG SRC="http://oascentral.cybereps.com/RealMedia/ads/adstream_nx.ads/' + page + random + target + '"></a>');
	  }

	document.write('</SCR');
	document.write('IPT>');

	// End Hide -->
</script>
<!-- END FGN Banner Code --><BR>
<TABLE CELLSPACING = 0 CELLPADDING = 0 BORDER = 0>
<TR>
	<TD width="63"><IMG SRC = "../graphics/topc000.jpg" WIDTH = 63 HEIGHT = 87></TD>
	<TD width="473"><IMG SRC = "../graphics/topc001.jpg" WIDTH = 473 HEIGHT = 87></TD>
	<TD width="64"><IMG SRC = "../graphics/topc002.jpg" WIDTH = 64 HEIGHT = 87></TD>
</TR>
	<TD width="63"></TD>
	<TD BGCOLOR="#BEA279" width="460">
	<DIV ALIGN="CENTER">
	<TABLE>
	<TR>

	<TD BGCOLOR="#BEA279" width="400">

<CENTER>
<FONT FACE="Times New Roman" SIZE="+2">
<BR><B><I>The Spider Room Incident...</I></B></FONT><BR><BR>
<FONT SIZE="-1">-----------------</FONT>
</CENTER><BR>
	
<DIV ALIGN="center">
<FONT Size="-1">
I stun and burn, watch them fall<BR>
My men all rally to my call<BR><BR>

Spiders, gargoyles, frogs go down<BR>
King of undead, I wear my crown<BR><BR>

Bloody battle aftermath<BR>
I could use a nice warm bath<BR><BR>

Though no time to stop and think<BR>
Once again death is on the brink<BR><BR>

Another pull and mana is low<BR>
Convince the group, take it slow<BR><BR>

We finish up and sit to heal<BR>
We drink our ale and shine our steel<BR><BR>

But look we up, a passer-by<BR>
In out midst he stopped and sighed<BR><BR>

"help" he said with his last breath<BR>
Then he fell consumed by death<BR><BR>

Around the corner came a fury<BR>
Minotaurs and icebones scurried<BR><BR>

One by two they filled the room<BR>
Seemed we were to share this strangers doom<BR><BR>

"Assist", "Assist", "Assist" I say<BR>
Yet at my feet a brother lay<BR><BR>

The wave of enemies proved to much<BR>
Our band can not remain as such<BR><BR>

The druid called the powers that be<BR>
The god of ocean, land, and tree<BR><BR>

Through the flames appears a mystic gate<BR>
We step on through escaping fate<BR><BR>

Across the world we did soar<BR>
Where once stood six, now stand four<BR><BR>
</DIV>
</FONT>

<DIV ALIGN="center">
-----------------<BR>
<P><FONT SIZE="+1"><I>Cendan Tankenpriest </I></FONT><BR>
<FONT FACE="Verdana" Size="-2">40th Level Cleric of the Sylvan Guard</FONT><BR>
<FONT FACE="Verdana" Size="-2"><B>Erollisi Marr</B></FONT><BR><BR>
</DIV>


	</TD>
	</TR>
	</TABLE>
<TABLE>
<TR>
<TD><A HREF="http://www.loreseekers.com/tales.phtml"><IMG SRC="http://www.loreseekers.com/graphics/tales_return_link.jpg" WIDTH=200 HEIGHT=75 ALT="Read some other stories by our members!" BORDER="0"></A></TD>
</TR>
</TABLE>

	<TD width="64"></TD>
<TR>
	<TD><IMG SRC = "../graphics/botc000.jpg" WIDTH = 63 HEIGHT = 87></TD>
	<TD><IMG SRC = "../graphics/botc001.jpg" WIDTH = 473 HEIGHT = 87></TD>
	<TD><IMG SRC = "../graphics/botc002.jpg" WIDTH = 64 HEIGHT = 87></TD>
</TR>
</TABLE>
<BR>
<IMG SRC="http://service.bfast.com/bfast/serve?bfmid=1375281&siteid=40292692&bfpage=pc" BORDER="0" WIDTH="1" HEIGHT="1" NOSAVE ><A HREF="http://service.bfast.com/bfast/click?bfmid=1375281&siteid=40292692&bfpage=pc" TARGET="_new"><IMG SRC="http://affiliate.gamestop.com/affIMG/pc_120x60.gif" BORDER="0" WIDTH="120" HEIGHT="60" ALT="PC Games at GameStop.com"></A>
<BR>
<BR>
</DIV>
</BODY>
</HTML>