<!--
                 This page has been created by Renaissance IT
   Renaissance Internet Technologies Copyright (c) 1999 All Rights Reserved.

             for more info on our products, please visit :
                        http://www.renaissance.nl/

	This script has been written by Roy Boverhof <rboverhof@renaissance.nl>
	
        Pagename                : weapons.html
        Last Updated    		: 27-7-1999
-->

<HTML>
<HEAD>
	<TITLE>Weapons</TITLE>
</HEAD>

<body BGCOLOR="#000000" TEXT="#000000">
<DIV ALIGN="CENTER">
<BR>
<!-- FGB Banner Code -->
<SCRIPT LANGUAGE="JavaScript">
   <!-- Hide from old browsers
   now = new Date();
   random = now.getTime();
     
   // Modify to reflect site specifics
   site = "http://ds.cybereps.com";
   target = "/SITE=FGN/AREA=EQLORE/AAMSZ=BANNER";
   
   document.write('<IFRAME SRC="' + site + '/hserver/acc_random=' + random + target + '"');
   document.write(' NORESIZE SCROLLING=NO HSPACE=0 VSPACE=0 FRAMEBORDER=0 MARGINHEIGHT=0 MARGINWIDTH=0 WIDTH=468 HEIGHT=60>');
   
   document.write('<SCR');
   document.write('IPT SRC="' + site + '/jnserver/acc_random=' + random + target + '">');
   document.write('</SCR');
   document.write('IPT>');
   
   document.write('</IFRAME>');
   // End Hide -->
 </SCRIPT>
 <NOSCRIPT> 
   <A HREF="http://ds.cybereps.com/accipiter/adclick/SITE=FGN/AREA=EQLORE/AAMSZ=BANNER">
   <IMG SRC="http://ds.cybereps.com/accipiter/nserver/SITE=FGN/AREA=EQLORE/AAMSZ=BANNER" border="0"></A>
 </NOSCRIPT>
<!-- END FGB Banner Code --><BR>	
<TABLE CELLSPACING = 0 CELLPADDING = 0 BORDER = 0>
<TR>
	<TD width="63"><IMG SRC = "graphics/topc000.jpg" WIDTH = 63 HEIGHT = 87></TD>
	<TD width="473"><IMG SRC = "graphics/topc001.jpg" WIDTH = 473 HEIGHT = 87></TD>
	<TD width="64"><IMG SRC = "graphics/topc002.jpg" WIDTH = 64 HEIGHT = 87></TD>
</TR>
	<TD width="63"></TD>
	<TD BGCOLOR="#BEA279" width="460">
	<DIV ALIGN="CENTER">
	<IMG SRC="graphics/weaponheader.jpg" WIDTH=200 HEIGHT=75 ALT="" BORDER="0">
	<TABLE WIDTH="460">
	<TR>
		<TD>
		<DIV ALIGN="CENTER">
		<FONT COLOR="#000000">
		<BR>
		<BR>
		Just fill in the name of an Item to search our database.

		<TABLE border="0" cellpadding="3" cellspacing="3">
		<TR>
			<TD>Name : </TD>
			<TD><FORM ACTION="weapon_search.php3" METHOD="POST"><INPUT TYPE="Hidden" NAME="action" VALUE="namesearch"><INPUT TYPE="text" NAME="name" SIZE="20"></TD>
			<TD>
			<TABLE><TR><TD height=14></TD></TR><TR><TD><INPUT TYPE="Submit" VALUE="Search"></FORM></TD></TR></TABLE>
			</TD>
		</TR>
		<TR>
			<TD>Select your class : </TD>
			<TD>
			<FORM ACTION="weapon_search.php3" METHOD="POST"> 
			<INPUT TYPE="Hidden" NAME="action" VALUE="classsearch">
			<SELECT NAME="class">
			<OPTION SELECTED>Bard</OPTION>
			<OPTION>Cleric</OPTION>
			<OPTION>Druid</OPTION>
			<OPTION>Enchanter</OPTION>
			<OPTION>Magician</OPTION>
			<OPTION>Monk</OPTION>
			<OPTION>Necromancer</OPTION>
			<OPTION>Paladin</OPTION>
			<OPTION>Ranger</OPTION>
			<OPTION>Rogue</OPTION>
			<OPTION>Shadowknight</OPTION>
			<OPTION>Shaman</OPTION>
			<OPTION>Warrior</OPTION>
			<OPTION>Wizard</OPTION>
			</SELECT>
			</TD>
			<TD>
			<TABLE><TR><TD height=14></TD></TR><TR><TD><INPUT TYPE="submit" VALUE="Search"></FORM></TD></TR></TABLE>
			</TD>
		</TR>
		<TR>
			<TD>Type : </TD>
			<TD>
			<FORM ACTION="weapon_search.php3" METHOD="POST"> 
			<INPUT TYPE="Hidden" NAME="action" VALUE="typesearch">
			<SELECT NAME="type">
			<OPTION>One Hand Blunt</OPTION>
			<OPTION>One Hand Slashing</OPTION>
			<OPTION>Two Hand Blunt</OPTION>
			<OPTION>Two Hand Slashing</OPTION>
			<OPTION>Piercing</OPTION>
			<OPTION>Archery</OPTION>
			</SELECT>
			</TD>
			<TD>
			<TABLE><TR><TD height=14></TD></TR><TR><TD><INPUT TYPE="submit" VALUE="Search"></FORM></TD></TR></TABLE>
			</TD>
		</TR>
		</TABLE>
		
		</FONT>
		</DIV>
		</TD>
	</TR>
	</TABLE>
	<TD width="64"></TD>
<TR>
	<TD><IMG SRC = "graphics/botc000.jpg" WIDTH = 63 HEIGHT = 87></TD>
	<TD><IMG SRC = "graphics/botc001.jpg" WIDTH = 473 HEIGHT = 87></TD>
	<TD><IMG SRC = "graphics/botc002.jpg" WIDTH = 64 HEIGHT = 87></TD>
</TR>
</TABLE>
<BR>
 <SCRIPT LANGUAGE="JavaScript">
   <!-- Hide from old browsers
   now = new Date();
   random = now.getTime();
   
   // Modify to reflect site specifics
   site = "http://ds.cybereps.com";
   target = "/SITE=FGN/AREA=EQLORE/AAMSZ=BOX";
   
   document.write('<IFRAME SRC="' + site + '/hserver/acc_random=' + random + target + '"');
   document.write(' NORESIZE SCROLLING=NO HSPACE=0 VSPACE=0 FRAMEBORDER=0 MARGINHEIGHT=0 MARGINWIDTH=0 WIDTH=125 HEIGHT=125>');
      
   document.write('<SCR');
   document.write('IPT SRC="' + site + '/jnserver/acc_random=' + random + target + '">');
   document.write('</SCR');
   document.write('IPT>');
   
   document.write('</IFRAME>');
   // End Hide -->
 </SCRIPT>
 <NOSCRIPT> 
   <A HREF="http://ds.cybereps.com/accipiter/adclick/SITE=FGN/AREA=EQLORE/AAMSZ=BOX">
   <IMG SRC="http://ds.cybereps.com/accipiter/nserver/SITE=FGN/AREA=EQLORE/AAMSZ=BOX" border="0"></A>
 </NOSCRIPT>
<BR>
<BR>
</DIV>
</BODY>
</HTML>
