<!--
                 This page has been created by Renaissance IT
   Renaissance Internet Technologies Copyright (c) 1999 All Rights Reserved.

             for more info on our products, please visit :
                        http://www.renaissance.nl/

	This script has been written by Roy Boverhof <rboverhof@renaissance.nl>
	
        Pagename                : platinum_analysis.html
        Last Updated    		: 31-01-2000
-->

<HTML>
<HEAD>
	<TITLE>the Seekers of Lore : Platinum Analysis Chart</TITLE>
</HEAD>

<BODY BGCOLOR="#000000" TEXT="#000000" LINK="#000000" VLINK="#000000" ALINK="#000000">
<DIV ALIGN="CENTER">
<BR>
<!-- FGB Banner Code -->
<SCRIPT LANGUAGE="JavaScript">
   <!-- Hide from old browsers
   now = new Date();
   random = now.getTime();
     
   // Modify to reflect site specifics
   site = "http://ds.cybereps.com";
   target = "/SITE=FGN/AREA=EQLORE/AAMSZ=BANNER";
   
   document.write('<IFRAME SRC="' + site + '/hserver/acc_random=' + random + target + '"');
   document.write(' NORESIZE SCROLLING=NO HSPACE=0 VSPACE=0 FRAMEBORDER=0 MARGINHEIGHT=0 MARGINWIDTH=0 WIDTH=468 HEIGHT=60>');
   
   document.write('<SCR');
   document.write('IPT SRC="' + site + '/jnserver/acc_random=' + random + target + '">');
   document.write('</SCR');
   document.write('IPT>');
   
   document.write('</IFRAME>');
   // End Hide -->
 </SCRIPT>
 <NOSCRIPT> 
   <A HREF="http://ds.cybereps.com/accipiter/adclick/SITE=FGN/AREA=EQLORE/AAMSZ=BANNER">
   <IMG SRC="http://ds.cybereps.com/accipiter/nserver/SITE=FGN/AREA=EQLORE/AAMSZ=BANNER" border="0"></A>
 </NOSCRIPT>
<!-- END FGB Banner Code --><BR>
<TABLE CELLSPACING = 0 CELLPADDING = 0 BORDER = 0>
<TR>
	<TD width="63"><IMG SRC = "http://www.loreseekers.com/graphics/topc000.jpg" WIDTH = 63 HEIGHT = 87></TD>
	<TD width="473"><IMG SRC = "http://www.loreseekers.com/graphics/topc001.jpg" WIDTH = 473 HEIGHT = 87></TD>
	<TD width="64"><IMG SRC = "http://www.loreseekers.com/graphics/topc002.jpg" WIDTH = 64 HEIGHT = 87></TD>
</TR>
	<TD width="63"></TD>
	<TD BGCOLOR="#BEA279" width="460">
	<DIV ALIGN="CENTER">
	<TABLE>
	<TR>
	<TD BGCOLOR="#BEA279" width="450">
	
<P ALIGN="left"><FONT SIZE="4" face="helvetica"><STRONG>F. Platinum Analysis</STRONG></FONT></A></P>


<!-- START OF CONVERTED OUTPUT -->
<!-- ------------------------- -->
<Table border>
<TR ALIGN="center" VALIGN="bottom">
<TD BGCOLOR=#C0C0C0><FONT FACE="Verdana" SIZE="1" COLOR=#FFFFFF><B>
Stone</B></FONT></TD>
<TD BGCOLOR=#C0C0C0><FONT FACE="Verdana" SIZE="1" COLOR=#FFFFFF><B>
Property</B></FONT></TD>
<TD BGCOLOR=#C0C0C0><FONT FACE="Verdana" SIZE="1" COLOR=#FFFFFF><B>
Cost (cp)</B></FONT></TD>
<TD BGCOLOR=#C0C0C0 STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1" COLOR=#FFFFFF><B>
Ench Platinum</B></FONT></TD>
<TD BGCOLOR=#C0C0C0><FONT FACE="Verdana" SIZE="1" COLOR=#FFFFFF><B>
Type</B></FONT></TD>
<TD BGCOLOR=#C0C0C0><FONT FACE="Verdana" SIZE="1" COLOR=#FFFFFF><B>
PP</B></FONT></TD>
<TD BGCOLOR=#C0C0C0><FONT FACE="Verdana" SIZE="1" COLOR=#FFFFFF><B>
GP</B></FONT></TD>
<TD BGCOLOR=#C0C0C0><FONT FACE="Verdana" SIZE="1" COLOR=#FFFFFF><B>
Profit (pp)</B></FONT></TD>
<TD BGCOLOR=#C0C0C0><FONT FACE="Verdana" SIZE="1" COLOR=#FFFFFF><B>
Profit (%)</B></FONT></TD>
</TR>
<TR VALIGN="bottom">
</TR>
<TR ALIGN="center" VALIGN="bottom" STYLE="vnd.ms-excel.numberformat:@">
<TD BGCOLOR=#FF9900 COLSPAN=9><FONT FACE="Verdana" SIZE="2"><B>
Useful Items (Minimum)</B></FONT></TD>
</TR>
<TR ALIGN="center" VALIGN="bottom">
<TD><FONT FACE="Verdana" SIZE="1">
Cat's Eye Agate</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
CHR</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
105210</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1">
+9</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Necklace</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
160</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
0</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0.00"><FONT FACE="Verdana" SIZE="1">
54.79</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0%"><FONT FACE="Verdana" SIZE="1">
52%</FONT></TD>
</TR>
<TR ALIGN="center" VALIGN="bottom">
<TD><FONT FACE="Verdana" SIZE="1">
Bloodstone</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
STA</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
105525</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1">
+6</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Earrings</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
160</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
0</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0.00"><FONT FACE="Verdana" SIZE="1">
54.48</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0%"><FONT FACE="Verdana" SIZE="1">
52%</FONT></TD>
</TR>
<TR ALIGN="center" VALIGN="bottom">
<TD><FONT FACE="Verdana" SIZE="1">
Onyx</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
DEX</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
105652</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1">
+6</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Bracelet</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
160</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
0</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0.00"><FONT FACE="Verdana" SIZE="1">
54.35</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0%"><FONT FACE="Verdana" SIZE="1">
51%</FONT></TD>
</TR>
<TR ALIGN="center" VALIGN="bottom">
<TD><FONT FACE="Verdana" SIZE="1">
Jasper</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
WIS</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
105787</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1">
+6</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Ring</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
170</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
0</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0.00"><FONT FACE="Verdana" SIZE="1">
64.21</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0%"><FONT FACE="Verdana" SIZE="1">
61%</FONT></TD>
</TR>
<TR ALIGN="center" VALIGN="bottom">
<TD><FONT FACE="Verdana" SIZE="1">
Carnelian</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
AGI</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
105892</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1">
+7</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Ring</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
170</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
0</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0.00"><FONT FACE="Verdana" SIZE="1">
64.11</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0%"><FONT FACE="Verdana" SIZE="1">
61%</FONT></TD>
</TR>
<TR ALIGN="center" VALIGN="bottom">
<TD><FONT FACE="Verdana" SIZE="1">
Star Rose Quartz</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
INT</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
106050</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1">
+4</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Ring</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
170</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
0</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0.00"><FONT FACE="Verdana" SIZE="1">
63.95</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0%"><FONT FACE="Verdana" SIZE="1">
60%</FONT></TD>
</TR>
<TR ALIGN="center" VALIGN="bottom">
<TD><FONT FACE="Verdana" SIZE="1">
Amber</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
STR</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
107625</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1">
+4</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Ring</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
180</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
0</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0.00"><FONT FACE="Verdana" SIZE="1">
72.38</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0%"><FONT FACE="Verdana" SIZE="1">
67%</FONT></TD>
</TR>
<TR ALIGN="center" VALIGN="bottom">
<TD><FONT FACE="Verdana" SIZE="1">
Jade</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Mana / HP / AC</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
108675</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1">
+20/+20/+4</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Ring</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
180</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
0</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0.00"><FONT FACE="Verdana" SIZE="1">
71.33</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0%"><FONT FACE="Verdana" SIZE="1">
66%</FONT></TD>
</TR>
<TR ALIGN="center" VALIGN="bottom">
<TD><FONT FACE="Verdana" SIZE="1">
Opal</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Sta / Agi</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
122850</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1">
+7/+5</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Ring</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
190</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
0</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0.00"><FONT FACE="Verdana" SIZE="1">
67.15</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0%"><FONT FACE="Verdana" SIZE="1">
55%</FONT></TD>
</TR>
<TR ALIGN="center" VALIGN="bottom">
<TD><FONT FACE="Verdana" SIZE="1">
Star Ruby</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Dex / Chr</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
173250</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
+9/+9</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Mask</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
280</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
0</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0.00"><FONT FACE="Verdana" SIZE="1">
106.75</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0%"><FONT FACE="Verdana" SIZE="1">
62%</FONT></TD>
</TR>
<TR ALIGN="center" VALIGN="bottom">
<TD><FONT FACE="Verdana" SIZE="1">
Fire Emerald</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Str / Dex</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
194250</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
+5/+5</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Ring</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
300</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
0</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0.00"><FONT FACE="Verdana" SIZE="1">
105.75</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0%"><FONT FACE="Verdana" SIZE="1">
54%</FONT></TD>
</TR>
<TR ALIGN="center" VALIGN="bottom">
<TD><FONT FACE="Verdana" SIZE="1">
Sapphire</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Str / Int</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
210000</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
+7/+7</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Necklace</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
320</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
0</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0.00"><FONT FACE="Verdana" SIZE="1">
110.00</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0%"><FONT FACE="Verdana" SIZE="1">
52%</FONT></TD>
</TR>
<TR ALIGN="center" VALIGN="bottom">
<TD><FONT FACE="Verdana" SIZE="1">
Ruby</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Str / Wis</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
236000</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1">
+7/+7</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Mask</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
370</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
0</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0.00"><FONT FACE="Verdana" SIZE="1">
134.00</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0%"><FONT FACE="Verdana" SIZE="1">
57%</FONT></TD>
</TR>
<TR VALIGN="bottom">
</TR>
<TR ALIGN="center" VALIGN="bottom" STYLE="vnd.ms-excel.numberformat:@">
<TD BGCOLOR=#FF9900 COLSPAN=9><FONT FACE="Verdana" SIZE="2"><B>
Useful Items (Recommended)</B></FONT></TD>
</TR>
<TR ALIGN="center" VALIGN="bottom">
<TD><FONT FACE="Verdana" SIZE="1">
Cat's Eye Agate</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
CHR</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
105210</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1">
+9</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Necklace</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
350</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
0</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0.00"><FONT FACE="Verdana" SIZE="1">
244.79</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0%"><FONT FACE="Verdana" SIZE="1">
233%</FONT></TD>
</TR>
<TR ALIGN="center" VALIGN="bottom">
<TD><FONT FACE="Verdana" SIZE="1">
Bloodstone</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
STA</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
105525</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1">
+6</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Earrings</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
350</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
0</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0.00"><FONT FACE="Verdana" SIZE="1">
244.48</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0%"><FONT FACE="Verdana" SIZE="1">
232%</FONT></TD>
</TR>
<TR ALIGN="center" VALIGN="bottom">
<TD><FONT FACE="Verdana" SIZE="1">
Onyx</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
DEX</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
105652</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1">
+6</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Bracelet</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
350</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
0</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0.00"><FONT FACE="Verdana" SIZE="1">
244.35</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0%"><FONT FACE="Verdana" SIZE="1">
231%</FONT></TD>
</TR>
<TR ALIGN="center" VALIGN="bottom">
<TD><FONT FACE="Verdana" SIZE="1">
Jasper</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
WIS</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
105787</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1">
+6</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Ring</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
350</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
0</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0.00"><FONT FACE="Verdana" SIZE="1">
244.21</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0%"><FONT FACE="Verdana" SIZE="1">
231%</FONT></TD>
</TR>
<TR ALIGN="center" VALIGN="bottom">
<TD><FONT FACE="Verdana" SIZE="1">
Carnelian</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
AGI</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
105892</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1">
+7</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Ring</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
350</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
0</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0.00"><FONT FACE="Verdana" SIZE="1">
244.11</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0%"><FONT FACE="Verdana" SIZE="1">
231%</FONT></TD>
</TR>
<TR ALIGN="center" VALIGN="bottom">
<TD><FONT FACE="Verdana" SIZE="1">
Star Rose Quartz</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
INT</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
106050</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1">
+4</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Ring</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
350</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
0</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0.00"><FONT FACE="Verdana" SIZE="1">
243.95</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0%"><FONT FACE="Verdana" SIZE="1">
230%</FONT></TD>
</TR>
<TR ALIGN="center" VALIGN="bottom">
<TD><FONT FACE="Verdana" SIZE="1">
Amber</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
STR</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
107625</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1">
+4</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Ring</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
350</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
0</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0.00"><FONT FACE="Verdana" SIZE="1">
242.38</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0%"><FONT FACE="Verdana" SIZE="1">
225%</FONT></TD>
</TR>
<TR ALIGN="center" VALIGN="bottom">
<TD><FONT FACE="Verdana" SIZE="1">
Jade</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Mana / HP / AC</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
108675</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1">
+20/+20/+4</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Ring</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
350</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
0</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0.00"><FONT FACE="Verdana" SIZE="1">
241.33</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0%"><FONT FACE="Verdana" SIZE="1">
222%</FONT></TD>
</TR>
<TR ALIGN="center" VALIGN="bottom">
<TD><FONT FACE="Verdana" SIZE="1">
Opal</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Sta / Agi</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
122850</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
+7/+5</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Ring</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
400</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
0</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0.00"><FONT FACE="Verdana" SIZE="1">
277.15</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0%"><FONT FACE="Verdana" SIZE="1">
226%</FONT></TD>
</TR>
<TR ALIGN="center" VALIGN="bottom">
<TD><FONT FACE="Verdana" SIZE="1">
Star Ruby</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Dex / Chr</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
173250</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
+9/+9</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Mask</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
600</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
0</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0.00"><FONT FACE="Verdana" SIZE="1">
426.75</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0%"><FONT FACE="Verdana" SIZE="1">
246%</FONT></TD>
</TR>
<TR ALIGN="center" VALIGN="bottom">
<TD><FONT FACE="Verdana" SIZE="1">
Fire Emerald</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Str / Dex</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
194250</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
+5/+5</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Ring</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
600</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
0</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0.00"><FONT FACE="Verdana" SIZE="1">
405.75</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0%"><FONT FACE="Verdana" SIZE="1">
209%</FONT></TD>
</TR>
<TR ALIGN="center" VALIGN="bottom">
<TD><FONT FACE="Verdana" SIZE="1">
Sapphire</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Str / Int</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
210000</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
+7/+7</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Necklace</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
750</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
0</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0.00"><FONT FACE="Verdana" SIZE="1">
540.00</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0%"><FONT FACE="Verdana" SIZE="1">
257%</FONT></TD>
</TR>
<TR ALIGN="center" VALIGN="bottom">
<TD><FONT FACE="Verdana" SIZE="1">
Ruby</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Str / Wis</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
236000</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1">
+7/+7</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Mask</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
750</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
0</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0.00"><FONT FACE="Verdana" SIZE="1">
514.00</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0%"><FONT FACE="Verdana" SIZE="1">
218%</FONT></TD>
</TR>
<TR VALIGN="bottom">
</TR>
<TR ALIGN="center" VALIGN="bottom" STYLE="vnd.ms-excel.numberformat:@">
<TD BGCOLOR=#FF9900 COLSPAN=9><FONT FACE="Verdana" SIZE="2"><B>
Monster Loot</B></FONT></TD>
</TR>
<TR ALIGN="center" VALIGN="bottom">
<TD><FONT FACE="Verdana" SIZE="1">
Jacinth</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Vs Magic / AC</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
105892</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1">
?</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
?</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
?</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
?</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0.00"><FONT FACE="Verdana" SIZE="1">
?</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0%"><FONT FACE="Verdana" SIZE="1">
?</FONT></TD>
</TR>
<TR ALIGN="center" VALIGN="bottom">
<TD><FONT FACE="Verdana" SIZE="1">
Wolf's Eye Agate</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Vs Magic</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
108000</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1">
+4</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Necklace</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
?</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
?</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0.00"><FONT FACE="Verdana" SIZE="1">
?</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0%"><FONT FACE="Verdana" SIZE="1">
?</FONT></TD>
</TR>
<TR ALIGN="center" VALIGN="bottom">
<TD><FONT FACE="Verdana" SIZE="1">
Black Pearl</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Dex / Agi</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
126000</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1">
+3/+3</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Ring</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
?</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
?</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0.00"><FONT FACE="Verdana" SIZE="1">
?</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0%"><FONT FACE="Verdana" SIZE="1">
?</FONT></TD>
</TR>
<TR ALIGN="center" VALIGN="bottom">
<TD><FONT FACE="Verdana" SIZE="1">
Diamond</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Vs All</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
316000</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1">
+3</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Ring</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
?</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
?</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
?</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
?</FONT></TD>
</TR>
<TR ALIGN="center" VALIGN="bottom">
<TD><FONT FACE="Verdana" SIZE="1">
Black Sapphire</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
HP / Mana</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
355000</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1">
?</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
?</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
?</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
?</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0.00"><FONT FACE="Verdana" SIZE="1">
?</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:0%"><FONT FACE="Verdana" SIZE="1">
?</FONT></TD>
</TR>
<TR ALIGN="center" VALIGN="bottom">
<TD><FONT FACE="Verdana" SIZE="1">
Fire Opal</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
HP/ AC</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
355000</FONT></TD>
<TD STYLE="vnd.ms-excel.numberformat:@"><FONT FACE="Verdana" SIZE="1">
+30/+2</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
Ring</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
?</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
?</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
?</FONT></TD>
<TD><FONT FACE="Verdana" SIZE="1">
?</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD BGCOLOR=#FF9900 COLSPAN=9><FONT FACE="Verdana" SIZE="2">&nbsp;</FONT></TD>
</TR>
<TR ALIGN="center" VALIGN="bottom">
<TD COLSPAN=4><FONT FACE="Verdana" SIZE="1">
Special Note:</FONT></TD>
<TD COLSPAN=5><FONT FACE="Verdana" SIZE="1">
Based on Information From</FONT></TD>
</TR>
<TR ALIGN="center" VALIGN="bottom">
<TD COLSPAN=4><FONT FACE="Verdana" SIZE="1">
I have not progressed to platinum jewelry as of yet, use</FONT></TD>
<TD COLSPAN=5><FONT FACE="Verdana" SIZE="1">
Casters Realm</FONT></TD>
</TR>
<TR ALIGN="center" VALIGN="bottom">
<TD COLSPAN=4><FONT FACE="Verdana" SIZE="1">
this chart only as a guide.</FONT></TD>
<TD COLSPAN=5><FONT FACE="Verdana" SIZE="1">
http://eq.castersrealm.com</FONT></TD>
</TR>
</Table>
<!-- ------------------------- -->
<!-- END OF CONVERTED OUTPUT -->


<BR><BR><DIV ALIGN="center"><A HREF="new_jewelry_guide.phtml" TARGET="_self"><IMG SRC="back_button.jpg" WIDTH=200 HEIGHT=50 BORDER=0 ALIGN="MIDDLE" ALT="Back to the Guide"></A></DIV><BR><BR>


</TR>
</TABLE>
	<TD width="64"></TD>
<TR>
	<TD><IMG SRC = "http://www.loreseekers.com/graphics/botc000.jpg" WIDTH = 63 HEIGHT = 87></TD>
	<TD><IMG SRC = "http://www.loreseekers.com/graphics/botc001.jpg" WIDTH = 473 HEIGHT = 87></TD>
	<TD><IMG SRC = "http://www.loreseekers.com/graphics/botc002.jpg" WIDTH = 64 HEIGHT = 87></TD>
</TR>
</TABLE>
<BR>
 <SCRIPT LANGUAGE="JavaScript">
   <!-- Hide from old browsers
   now = new Date();
   random = now.getTime();
   
   // Modify to reflect site specifics
   site = "http://ds.cybereps.com";
   target = "/SITE=FGN/AREA=EQLORE/AAMSZ=BOX";
   
   document.write('<IFRAME SRC="' + site + '/hserver/acc_random=' + random + target + '"');
   document.write(' NORESIZE SCROLLING=NO HSPACE=0 VSPACE=0 FRAMEBORDER=0 MARGINHEIGHT=0 MARGINWIDTH=0 WIDTH=125 HEIGHT=125>');
      
   document.write('<SCR');
   document.write('IPT SRC="' + site + '/jnserver/acc_random=' + random + target + '">');
   document.write('</SCR');
   document.write('IPT>');
   
   document.write('</IFRAME>');
   // End Hide -->
 </SCRIPT>
 <NOSCRIPT> 
   <A HREF="http://ds.cybereps.com/accipiter/adclick/SITE=FGN/AREA=EQLORE/AAMSZ=BOX">
   <IMG SRC="http://ds.cybereps.com/accipiter/nserver/SITE=FGN/AREA=EQLORE/AAMSZ=BOX" border="0"></A>
 </NOSCRIPT>
<BR>
<BR>
</DIV>
</BODY>
</HTML>