<HTML>
<HEAD>
<TITLE>Welcome to Media and Games Online Network - MGON</TITLE>
<META name="description" content="MGON - The Gamer's Choice for gaming news. Get the hottest info from the gaming industry.
.">
<META name="keywords" content="MGON, MGO, Interviews, Game previews, Game downloads, Gaming Network, Articles, Gaming News, News, Multiplayer, Games, PC Games, Console Games, Reviews, Forum, MGON International AB, Action, Strategy, Simulation, Roleplay, Racing">
<META name="robots" content="index,follow">
<LINK rel="stylesheet" href="/pagestyle2.css">
<STYLE type="text/css">
<!--
-->
</STYLE>
<script language="JavaScript" type="text/javascript">
<!--
function go(where) {
  if(where != "void" && where!="") location.href = where;
}

function reply(tid,pid,cid,lang) {

  url = "/reply.phtml?tid=" + tid + "&pid=" + pid + "&id=" + cid + "&language=" + lang + '&ref=%2Fpreviews.phtml';
  ipwindow = open("","prewindow","scrollbars=yes,toolbar=no,height=400,width=400");
  ipwindow.location.href = url;
        
}

function rateit(id,vote) {
    if(vote != "") {
		document.rate.content_id.value = id;
		document.rate.vote.value = vote;
		document.rate.submit();
	}
}

function screenshot(cid,pid) {

  url = "/screenshot.phtml?cid=" + cid + "&pid=" + pid;
  ipwindow = open("","prewindow","scrollbars=yes,toolbar=no,height=630,width=710");
  ipwindow.location.href = url;
        
}

function relatedmedia(url) {

  ipwindow = open("","prewindow","scrollbars=yes,toolbar=no,height=300,width=300");
  ipwindow.location.href = url;
        
}
//-->
</script> 
</HEAD>

<BODY bgcolor="#FFFFFF" text="#000000" link="#000000" vlink="#000000" alink="#000000" leftmargin="0" topmargin="0" marginwidth="0" marginheight="0" background="/images2/backgrounds/resize.gif">
<TABLE width="750" border="0" cellspacing="0" cellpadding="0">
  <TR> 
    <TD><!-- hostname =  -->


<SCRIPT language="JavaScript" type="text/javascript">
<!--
if (window != top) top.location.href = location.href;

     NS4 = (document.layers);
     IE4 = (document.all);
    ver4 = (NS4 || IE4);
     IE5 = (IE4 && navigator.appVersion.indexOf("5.")!=-1);
   isMac = (navigator.appVersion.indexOf("Mac") != -1);
  isMenu = (NS4 || (IE4 && !isMac) || (IE5 && isMac));

function popUp(){return};
function popDown(){return};

if (!ver4) event = null;

//-->
</SCRIPT>
<script language="JavaScript1.2" type="text/javascript">
<!--

if (isMenu) {
    menuVersion = 3;
    
    menuWidth = 100;
    childOverlap = 1;
    childOffset = -109;
    perCentOver = null;
    secondsVisible = .5;
    
    fntCol = "blue";
    fntSiz = "7";
    fntBold = true;
    fntItal = false;
    fntFam = "arial, helvetica";
    
    backCol = "#DDDDDD";
    overCol = "#FFCCCC";
    overFnt = "purple";
    
    borWid = 1;
    borCol = "black";
    borSty = "solid";
    itemPad = 3;
    
    imgSrc = "http://www.mgon.com/images/misc/menuarrow.gif";
    imgSiz = 10;
    
    separator = 1;
    separatorCol = "red";
    
    isFrames = false;      // <-- IMPORTANT for full window
    navFrLoc = "left";     // <-- display. see below
    
    keepHilite = true; 
    NSfontOver = true;
    clickStart = false;
    clickKill = false;
}

//-->
</script>
<SCRIPT language="JavaScript1.2" type="text/javascript">
<!--
if (isMenu) {

  //document.write("<SCRIPT LANGUAGE='JavaScript1.2' SRC='http://www.mgon.com/shared/js/hierArrays.js'><\/SCRIPT>");

arMenu1 = new Array(
105,184,"19",
"white","white",
"#813E09","#FF9216",
"black","black",
"&nbsp;Deus Ex","http://www.deusexcenter.com/common/quickLoginAndRedirect?id=&pw=&ref=/",0,
"&nbsp;Duke Nukem","http://www.dukenukemcenter.com/common/quickLoginAndRedirect?id=&pw=&ref=/",0,
"&nbsp;Elite Force","http://www.eliteforcecenter.com/common/quickLoginAndRedirect?id=&pw=&ref=/",0,
"&nbsp;Half Life","http://www.hlcenter.com/common/quickLoginAndRedirect?id=&pw=&ref=/",0,
"&nbsp;Halo","http://www.halocenter.com/common/quickLoginAndRedirect?id=&pw=&ref=/",0,
"&nbsp;Quake 3","http://www.q3center.com/common/quickLoginAndRedirect?id=&pw=&ref=/",0,
"&nbsp;<i>More Action Sites</i>","#",1
)

arMenu1_7 = new Array(

"&nbsp;Rainbow Six","http://www.rainbowsixcenter.com/common/quickLoginAndRedirect?id=&pw=&ref=/",0,
"&nbsp;Rune","http://www.runecenter.com/common/quickLoginAndRedirect?id=&pw=&ref=/",0,
"&nbsp;Soldier of Fortune","http://www.sofcenter.com/common/quickLoginAndRedirect?id=&pw=&ref=/",0,
"&nbsp;Team Fortress","http://www.fortresscenter.com/common/quickLoginAndRedirect?id=&pw=&ref=/",0,
"&nbsp;StrikeForce","http://www.strikeforcecenter.com/common/quickLoginAndRedirect?id=&pw=&ref=/",0,
"&nbsp;Tribes","http://www.tribescenter.com/common/quickLoginAndRedirect?id=&pw=&ref=/",0,
"&nbsp;<i>More Action Sites</i>","#",1
)

arMenu1_7_7 = new Array(

"&nbsp;Unreal","http://www.unrealcenter.com/common/quickLoginAndRedirect?id=&pw=&ref=/",0,
"&nbsp;Wheel of Time","http://www.wotgame.com/common/quickLoginAndRedirect?id=&pw=&ref=/",0,
"&nbsp;&nbsp;","#",0,
"&nbsp;&nbsp;","#",0,
"&nbsp;&nbsp;","#",0,
"&nbsp;&nbsp;","#",0,
"&nbsp;&nbsp;","#",0
)

arMenu2 = new Array(
105,268,"19",
"white","white",
"#003355","#0078C8",
"black","black",
"&nbsp;Black & White","http://www.bwcenter.com/common/quickLoginAndRedirect?id=&pw=&ref=/",0,
"&nbsp;Dark Reign","http://www.darkreigncenter.com/common/quickLoginAndRedirect?id=&pw=&ref=/",0,
"&nbsp;Ground Control","http://www.gccenter.com/common/quickLoginAndRedirect?id=&pw=&ref=/",0,
"&nbsp;Sacrifice","http://www.sacrificecenter.com/common/quickLoginAndRedirect?id=&pw=&ref=/",0,
"&nbsp;Worms","http://www.wormscenter.com/common/quickLoginAndRedirect?id=&pw=&ref=/",0
)

arMenu3 = new Array(
115,352,"19",
"white","white",
"#A40307","#E80005",
"black","black",
"&nbsp;Baldurs Gate","http://www.baldursgatehaven.com/common/quickLoginAndRedirect?id=&pw=&ref=/",0,
"&nbsp;Diablo","http://www.diablohaven.com/common/quickLoginAndRedirect?id=&pw=&ref=/",0,
"&nbsp;Horizons","http://www.horizonshaven.com/common/quickLoginAndRedirect?id=&pw=&ref=/",0,
"&nbsp;MUD's","http://www.mudcenter.com/common/quickLoginAndRedirect?id=&pw=&ref=/",0,
"&nbsp;Neocron","http://www.neocroncenter.com/common/quickLoginAndRedirect?id=&pw=&ref=/",0,
"&nbsp;Neverwinter &nbsp;Nights","http://www.neverwinterhaven.com/common/quickLoginAndRedirect?id=&pw=&ref=/",0,
"&nbsp;<i>More Roleplay Sites</i>","#",1
)

arMenu3_7 = new Array(

"&nbsp;Throne of Darkness","http://www.todhaven.com/common/quickLoginAndRedirect?id=&pw=&ref=/",0,
"&nbsp;Ultima","http://www.ultimahaven.com/common/quickLoginAndRedirect?id=&pw=&ref=/",0,
"&nbsp;Vampire","http://www.vampirehaven.com/common/quickLoginAndRedirect?id=&pw=&ref=/",0,
"&nbsp;&nbsp;","#",0,
"&nbsp;&nbsp;","#",0,
"&nbsp;&nbsp;","#",0,
"&nbsp;&nbsp;","#",0
)

arMenu4 = new Array(
105,436,"19",
"white","white",
"#004612","#009526",
"black","black",
"&nbsp;CManager","http://www.cmanagercenter.com/common/quickLoginAndRedirect?id=&pw=&ref=/",0,
"&nbsp;Creatures","http://www.homecreatures.com/common/quickLoginAndRedirect?id=&pw=&ref=/",0,
"&nbsp;Pokémon","http://www.pokeball.net/common/quickLoginAndRedirect?id=&pw=&ref=/",0,
"&nbsp;The Sims","http://www.thesimsresource.com/common/quickLoginAndRedirect?id=&pw=&ref=/",0,
"&nbsp;Tycoon","http://www.tycoonresource.com/common/quickLoginAndRedirect?id=&pw=&ref=/",0
)

arMenu5 = new Array(
105,520,"19",
"white","white",
"#383838","#8A8A8A",
"black","black",
"&nbsp;Racing Source","http://www.racingsource.com/common/quickLoginAndRedirect?id=&pw=&ref=/",0,
"&nbsp;Driver","http://www.driverhq.com/common/quickLoginAndRedirect?id=&pw=&ref=/",0
)

arMenu6 = new Array(
105,100,"19",
"white","white",
"#48003F","#B2009C",
"black","black",
"&nbsp;MGON","http://www.mgon.com/common/quickLoginAndRedirect?id=&pw=&ref=/",0,
"&nbsp;MGON - SE","http://se.mgon.com/common/quickLoginAndRedirect?id=&pw=&ref=/",0,
"&nbsp;ESports - Live","http://www.esports-live.com/common/quickLoginAndRedirect?id=&pw=&ref=/",0,
"&nbsp;Nintendo","http://www.nintendocenter.com/common/quickLoginAndRedirect?id=&pw=&ref=/",0,
"&nbsp;Playstation","http://www.playstationcenter.com/common/quickLoginAndRedirect?id=&pw=&ref=/",0,
"&nbsp;Playstation - SE","http://se.playstationcenter.com/common/quickLoginAndRedirect?id=&pw=&ref=/",0
)

arMenu7 = new Array(
105,1,"19",
"white","white",
"#101040","#101090",
"black","black",
"&nbsp;Edit Profile", "javascript:member()",0,
"&nbsp;Logout", "http://everquest.mgon.com/common/logout.phtml?ref=/previews.phtml",0
)

arMenu8 = new Array(
105,1,"19",
"white","white",
"#101040","#101090",
"black","black",
"&nbsp;Login","javascript:login()",0,
"&nbsp;New member","javascript:member()",0,
"&nbsp;Forgot it?","javascript:forgotit()",0)

}

//-->
</SCRIPT>
<SCRIPT language="JavaScript1.2" type="text/javascript">
<!--
if (isMenu) {
document.write("<SCRIPT LANGUAGE='JavaScript1.2' SRC='http://www.mgon.com/shared/js/hierMenus.js'><\/SCRIPT>");
}
function logout() {
  location.href = "http://everquest.mgon.com/common/logout.phtml?ref=/previews.phtml";
}
function login() {
  ipwindow = open("","Login","scrollbars=no,toolbar=no,height=200,width=240");
  ipwindow.location.href = "http://everquest.mgon.com/common/login.phtml?ref=www.mgon.com&page=/previews.phtml";        
}
function forgotit() {
  ipwindow = open("","Login","scrollbars=no,toolbar=no,height=250,width=400");
  ipwindow.location.href = "/common/forgotit.phtml";        
}
function member() {
  ipwindow = open("","Members","scrollbars=yes,toolbar=no,height=600,width=500");
  ipwindow.location.href = "http://everquest.mgon.com/common/members.phtml?ref=www.mgon.com&page=/previews.phtml";        
}
//-->
</SCRIPT>
<table width="100%" border="0" cellspacing="0" cellpadding="0" background="/images/network_nav/resize.gif">
  <tr> 
    <td><img src="/images/network_nav/left.gif" width="2" height="20"></td>
    <td><a href="#" onClick="javascript:login()" onMouseOver="popUp('elMenu8',event)" onMouseOut="popDown('elMenu8')"><img src="/images/network_nav/member_login.gif" width="97" height="20" border="0"></a></td>
    <td><a href="#" onMouseOver="popUp('elMenu6',event)" onMouseOut="popDown('elMenu6')"><img src="/images/network_nav/console_new.gif" width="84" height="20" border="0"></a></td>
    <td><a href="#" onMouseOver="popUp('elMenu1',event)" onMouseOut="popDown('elMenu1')"><img src="/images/network_nav/action.gif" width="84" height="20" border="0"></a></td>
    <td><a href="#" onMouseOver="popUp('elMenu2',event)" onMouseOut="popDown('elMenu2')"><img src="/images/network_nav/strategy.gif" width="84" height="20" border="0"></a></td>
    <td><a href="#" onMouseOver="popUp('elMenu3',event)" onMouseOut="popDown('elMenu3')"><img src="/images/network_nav/roleplay.gif" width="84" height="20" border="0"></a></td>
    <td><a href="#" onMouseOver="popUp('elMenu4',event)" onMouseOut="popDown('elMenu4')"><img src="/images/network_nav/simulation.gif" width="84" height="20" border="0"></a></td>
    <td><a href="#" onMouseOver="popUp('elMenu5',event)" onMouseOut="popDown('elMenu5')"><img src="/images/network_nav/racing.gif" width="85" height="20" border="0"></a></td><td width="100%">&nbsp;</td><td><A href="http://www.mgon.com/common/quickLoginAndRedirect?id=&pw=&ref=/"><img src="/images/network_nav/network.gif" width="144" height="20" border="0"></A></td>
  </tr>
</table>
<script language="javascript">
var compname='Ad/mgon';
</script>
<script language="javascript" src="http://www.rankyou.com/cpt_transfers/single_month_enter.js">
</script></TD>
  </TR>
</TABLE>


<TABLE width="750" border="0" cellspacing="0" cellpadding="0">

  <TR> 

    <TD><IMG src="/images2/top/topleft.jpg" width="152" height="136" border="0" usemap="#Map"><MAP name="Map"><AREA shape="rect" coords="13,36,138,76" href="http://www.mgon.com" alt="MGON Home" title="MGON Home"></MAP></TD>

    <TD width="100%" background="/images2/top/resize.jpg"><IMG src="/images2/top/logo.jpg" width="455" height="136"></TD>

    <TD align="center"><IMG src="/images2/top/topright.jpg" width="142" height="136"></TD>

  </TR>

</TABLE>


<TABLE width="750" border="0" cellspacing="0" cellpadding="0" bgcolor="#000000">
	<TR> 
		<TD align="center" width="130"> 
			<TABLE width="100%" border="0" cellspacing="0" cellpadding="0">
				<TR> 
					<TD align="center" background="/images2/top/channelresize.gif"><OBJECT classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=4,0,2,0" width="120" height="60">
							<PARAM name=movie value="http://www.mgon.com/flashmovies/mgochannel2.swf">
							<PARAM name=quality value=high>
							<PARAM name="menu" value="false">
							<EMBED src="http://www.mgon.com/flashmovies/mgochannel2.swf" quality=high pluginspage="http://www.macromedia.com/shockwave/download/index.cgi?P1_Prod_Version=ShockwaveFlash" 
type="application/x-shockwave-flash" menu="false" width="120" height="60">
							</EMBED> 
						</OBJECT></TD>
				</TR>
				<TR> 
					<TD><IMG src="/images/top/channelbottom.gif" width="130" height="13"></TD>
				</TR>
			</TABLE>
		</TD>
		
    <TD align="center" width="490" valign="top"> 
      <span class="smalltext"><NOLAYER><IFRAME SRC="http://ad.se.doubleclick.net/adi/mgon.com/;sz=468x60;ord=981210830?" bgcolor="#000000" width="468" height="60" frameborder="no" border="0" MARGINWIDTH="0" MARGINHEIGHT="0" SCROLLING="no"><A HREF="http://ad.se.doubleclick.net/jump/mgon.com/;abr=!ie;sz=468x60;ord=981210830?"><IMG SRC="http://ad.se.doubleclick.net/ad/mgon.com/;abr=!ie;sz=468x60;ord=981210830?" border="0" height="60" width="468"></A></IFRAME></NOLAYER><ILAYER id="layer1" visibility="hidden" width="468" height="60" align="center"></ILAYER></span>    </TD>
		
    <TD width="130" align="center" valign="top"><IMG
SRC="http://service.bfast.com/bfast/serve?bfmid=1375281&siteid=34593362&bfpa
ge=pc" BORDER="0" WIDTH="1" HEIGHT="1" NOSAVE > <A
HREF="http://service.bfast.com/bfast/click?bfmid=1375281&siteid=34593362&bfp
age=pc" TARGET="_top"><IMG
SRC="http://affiliate.gamestop.com/affimg/120_pc3_gs.gif" BORDER="0"
WIDTH="120" HEIGHT="60" ALT="PC titles from Gamestop.com"></A></TD>
	</TR>
</TABLE>
 
<TABLE width="750" border="0" cellspacing="0" cellpadding="0">
  <TR> 
    <TD valign="top" width="130" align="center"> 
       
<TABLE width="130" border="0" cellspacing="0" cellpadding="0">
  <TR> 
    <TD><IMG src="/images2/buttons/sitecontent.gif" width="130" height="25"></TD>
  </TR>
</TABLE>
<table width="130" border="0" cellspacing="0" cellpadding="0">
  <tr bgcolor="#000E24"> 
    <td> 
      <table width="100%" border=0 cellpadding=0 cellspacing=1>
        <tr bgcolor="#000E24"> 
          <td style="border='1 solid #809ECB'" onMouseOver="style.backgroundColor='#809ECB'; style.cursor='hand'; style.border='1 solid #809ECB'" onMouseOut="style.backgroundColor='#000E24'; style.border='1 solid #809ECB';" height="21"> 
            <table width="100%" border="0" cellspacing="0" cellpadding="2">
              <tr> 
                <td bgcolor="#000E24" height="21" width="100%"><a href="/" class="navlinks" style="margin:0;"> 
                  <div><img src="/images2/misc/1pix.gif" width="1" height="1" border="0">&nbsp;<span class="navlinks">Home</span></div>
                  </a></td>
                <td class="Bolded"><font size="2" face="Verdana, Arial, Helvetica, sans-serif" color="#000E24">&laquo;</font></td>
              </tr>
            </table>
          </td>
        </tr>
        <tr bgcolor="#000E24"> 
          <td style="border='1 solid #809ECB'" onMouseOver="style.backgroundColor='#809ECB'; style.cursor='hand'; style.border='1 solid #809ECB'" onMouseOut="style.backgroundColor='#000E24'; style.border='1 solid #809ECB';" height="21"> 
            <table width="100%" border="0" cellspacing="0" cellpadding="2">
              <tr> 
                <td bgcolor="#000E24" height="21" width="100%"><a href="/news.phtml" class="navlinks" style="margin:0;"> 
                  <div><img src="/images2/misc/1pix.gif" width="1" height="1" border="0">&nbsp;<span class="navlinks">News</span></div>
                  </a></td>
                <td class="Bolded"><font size="2" face="Verdana, Arial, Helvetica, sans-serif" color="#000E24">&laquo;</font></td>
              </tr>
            </table>
          </td>
        </tr>
        <tr bgcolor="#000E24"> 
          <td style="border='1 solid #809ECB'" onMouseOver="style.backgroundColor='#809ECB'; style.cursor='hand'; style.border='1 solid #809ECB'" onMouseOut="style.backgroundColor='#000E24'; style.border='1 solid #809ECB';" height="21"> 
            <table width="100%" border="0" cellspacing="0" cellpadding="2">
              <tr> 
                <td bgcolor="#000E24" height="21" width="100%"><a href="/reviewindex.phtml" class="navlinks" style="margin:0;"> 
                  <div><img src="/images2/misc/1pix.gif" width="1" height="1" border="0">&nbsp;<span class="navlinks">Reviews</span></div>
                  </a></td>
                <td class="Bolded"><font size="2" face="Verdana, Arial, Helvetica, sans-serif" color="#000E24">&laquo;</font></td>
              </tr>
            </table>
          </td>
        </tr>
        <tr bgcolor="#000E24"> 
          <td style="border='1 solid #809ECB'" onMouseOver="style.backgroundColor='#809ECB'; style.cursor='hand'; style.border='1 solid #809ECB'" onMouseOut="style.backgroundColor='#000E24'; style.border='1 solid #809ECB';" height="21"> 
            <table width="100%" border="0" cellspacing="0" cellpadding="2">
              <tr> 
                <td bgcolor="#000E24" height="21" width="100%"><a href="/previewindex.phtml" class="navlinks" style="margin:0;"> 
                  <div><img src="/images2/misc/1pix.gif" width="1" height="1" border="0">&nbsp;<span class="navlinks">Previews</span></div>
                  </a></td>
                <td class="Bolded"><font size="2" face="Verdana, Arial, Helvetica, sans-serif" color="#000E24">&laquo;</font></td>
              </tr>
            </table>
          </td>
        </tr>
        <tr bgcolor="#000E24"> 
          <td style="border='1 solid #809ECB'" onMouseOver="style.backgroundColor='#809ECB'; style.cursor='hand'; style.border='1 solid #809ECB'" onMouseOut="style.backgroundColor='#000E24'; style.border='1 solid #809ECB';" height="21"> 
            <table width="100%" border="0" cellspacing="0" cellpadding="2">
              <tr> 
                <td bgcolor="#000E24" height="21" width="100%"><a href="/interviewindex.phtml" class="navlinks" style="margin:0;"> 
                  <div><img src="/images2/misc/1pix.gif" width="1" height="1" border="0">&nbsp;<span class="navlinks">Interviews</span></div>
                  </a></td>
                <td class="Bolded"><font size="2" face="Verdana, Arial, Helvetica, sans-serif" color="#000E24">&laquo;</font></td>
              </tr>
            </table>
          </td>
        </tr>

        <tr bgcolor="#000E24"> 
          <td style="border='1 solid #809ECB'" onMouseOver="style.backgroundColor='#809ECB'; style.cursor='hand'; style.border='1 solid #809ECB'" onMouseOut="style.backgroundColor='#000E24'; style.border='1 solid #809ECB';" height="21"> 
            <table width="100%" border="0" cellspacing="0" cellpadding="2">
              <tr> 
                <td bgcolor="#000E24" height="21" width="100%"><a href="/articleindex.phtml" class="navlinks" style="margin:0;"> 
                  <div><img src="/images2/misc/1pix.gif" width="1" height="1" border="0">&nbsp;<span class="navlinks">Articles</span></div>
                  </a></td>
                <td class="Bolded"><font size="2" face="Verdana, Arial, Helvetica, sans-serif" color="#000E24">&laquo;</font></td>
              </tr>
            </table>
          </td>
        </tr>
        <tr bgcolor="#000E24"> 
          <td style="border='1 solid #809ECB'" onMouseOver="style.backgroundColor='#809ECB'; style.cursor='hand'; style.border='1 solid #809ECB'" onMouseOut="style.backgroundColor='#000E24'; style.border='1 solid #809ECB';" height="21"> 
            <table width="100%" border="0" cellspacing="0" cellpadding="2">
              <tr> 
                <td bgcolor="#000E24" height="21" width="100%"><a href="/fileindex.phtml" class="navlinks" style="margin:0;"> 
                  <div><img src="/images2/misc/1pix.gif" width="1" height="1" border="0">&nbsp;<span class="navlinks">Downloads</span></div>
                  </a></td>
                <td class="Bolded"><font size="2" face="Verdana, Arial, Helvetica, sans-serif" color="#000E24">&laquo;</font></td>
              </tr>
            </table>
          </td>
        </tr>
        <tr bgcolor="#000E24"> 
          <td style="border='1 solid #809ECB'" onMouseOver="style.backgroundColor='#809ECB'; style.cursor='hand'; style.border='1 solid #809ECB'" onMouseOut="style.backgroundColor='#000E24'; style.border='1 solid #809ECB';" height="21"> 
            <table width="100%" border="0" cellspacing="0" cellpadding="2">
              <tr> 
                <td bgcolor="#000E24" height="21" width="100%"><a href="http://www.mgoforum.com/" class="navlinks" style="margin:0;"> 
                  <div><img src="/images2/misc/1pix.gif" width="1" height="1" border="0">&nbsp;<span class="navlinks">MGON 
                    Forum</span></div>
                  </a></td>
                <td class="Bolded"><font size="2" face="Verdana, Arial, Helvetica, sans-serif" color="#000E24">&laquo;</font></td>
              </tr>
            </table>
          </td>
        </tr>
      </table>
    </td>
  </tr>
</table>
<TABLE width="130" border="0" cellspacing="0" cellpadding="0">
  <TR> 
    <TD><IMG src="/images2/buttons/siteinfo.gif" width="130" height="25"></TD>
  </TR>
</TABLE>
<table width="130" border="0" cellspacing="0" cellpadding="0">
  <tr bgcolor="#000E24"> 
    <td> 
      <table width="100%" border=0 cellpadding=0 cellspacing=1>
        <tr bgcolor="#000E24"> 
          <td style="border='1 solid #809ECB'" onMouseOver="style.backgroundColor='#809ECB'; style.cursor='hand'; style.border='1 solid #809ECB'" onMouseOut="style.backgroundColor='#000E24'; style.border='1 solid #809ECB';" height="21"> 
            <table width="100%" border="0" cellspacing="0" cellpadding="2">
              <tr> 
                <td bgcolor="#000E24" height="21" width="100%"><a href="/company/" class="navlinks" style="margin:0;"> 
                  <div><img src="/images2/misc/1pix.gif" width="1" height="1" border="0">&nbsp;<span class="navlinks">The 
                    Company</span></div>
                  </a></td>
                <td class="Bolded"><font size="2" face="Verdana, Arial, Helvetica, sans-serif" color="#000E24">&laquo;</font></td>
              </tr>
            </table>
          </td>
        </tr>
        <tr bgcolor="#000E24"> 
          <td style="border='1 solid #809ECB'" onMouseOver="style.backgroundColor='#809ECB'; style.cursor='hand'; style.border='1 solid #809ECB'" onMouseOut="style.backgroundColor='#000E24'; style.border='1 solid #809ECB';" height="21"> 
            <table width="100%" border="0" cellspacing="0" cellpadding="2">
              <tr> 
                <td bgcolor="#000E24" height="21" width="100%"><a href="/mediakit/" class="navlinks" style="margin:0;"> 
                  <div><img src="/images2/misc/1pix.gif" width="1" height="1" border="0">&nbsp;<span class="navlinks">Our 
                    Mediakit</span></div>
                  </a></td>
                <td class="Bolded"><font size="2" face="Verdana, Arial, Helvetica, sans-serif" color="#000E24">&laquo;</font></td>
              </tr>
            </table>
          </td>
        </tr>
        <tr bgcolor="#000E24"> 
          <td style="border='1 solid #809ECB'" onMouseOver="style.backgroundColor='#809ECB'; style.cursor='hand'; style.border='1 solid #809ECB'" onMouseOut="style.backgroundColor='#000E24'; style.border='1 solid #809ECB';" height="21"> 
            <table width="100%" border="0" cellspacing="0" cellpadding="2">
              <tr> 
                <td bgcolor="#000E24" height="21" width="100%"><a href="/press.phtml" class="navlinks" style="margin:0;"> 
                  <div><img src="/images2/misc/1pix.gif" width="1" height="1" border="0">&nbsp;<span class="navlinks">Press 
                    Material</span></div>
                  </a></td>
                <td class="Bolded"><font size="2" face="Verdana, Arial, Helvetica, sans-serif" color="#000E24">&laquo;</font></td>
              </tr>
            </table>
          </td>
        </tr>
        <tr bgcolor="#000E24"> 
          <td style="border='1 solid #809ECB'" onMouseOver="style.backgroundColor='#809ECB'; style.cursor='hand'; style.border='1 solid #809ECB'" onMouseOut="style.backgroundColor='#000E24'; style.border='1 solid #809ECB';" height="21"> 
            <table width="100%" border="0" cellspacing="0" cellpadding="2">
              <tr> 
                <td bgcolor="#000E24" height="21" width="100%"><a href="/contactus/" class="navlinks" style="margin:0;"> 
                  <div><img src="/images2/misc/1pix.gif" width="1" height="1" border="0">&nbsp;<span class="navlinks">Contact 
                    Us</span></div>
                  </a></td>
                <td class="Bolded"><font size="2" face="Verdana, Arial, Helvetica, sans-serif" color="#000E24">&laquo;</font></td>
              </tr>
            </table>
          </td>
        </tr>
      </table>
    </td>
  </tr>
</table>    
<TABLE width="122" border="0" cellspacing="0" cellpadding="1" bgcolor="#000000" background="/images/misc/50x50pix.gif">
  <TR align="center"> 
          <TD><IMG SRC="http://service.bfast.com/bfast/serve?bfmid=1307357&siteid=36766142&bfpage=1" BORDER="0" WIDTH="1" HEIGHT="1" NOSAVE ><BR>
<A HREF="http://service.bfast.com/bfast/click?bfmid=1307357&siteid=36766142&bfpage=1" TARGET="_top">
<IMG SRC="http://www.gator.com/images/banners/gator_tired_120x90.gif" BORDER="0" WIDTH="120" HEIGHT="90" ALT="Gator fills out forms and remembers passwords!"></A><!--index: 1 num: 5 --></TD>
        </TR>
      </TABLE>
    </TD>
    <TD width="620" valign="top">  
      <TABLE width="100%" border="0" cellspacing="0" cellpadding="0" background="/images2/sections/resize.gif">
        <TR> 
          <TD><IMG src="/images2/misc/1pixblack.gif" width="1" height="63"></TD>
          <TD width="100%" valign="bottom"> 
            <TABLE width="100%" border="0" cellspacing="0" cellpadding="0" background="/images2/misc/50x50pix.gif">
              <TR> 
                <TD height="28"><SPAN class="Bolded"><IMG src="/images2/misc/1pix.gif" width="11" height="1">Page:</SPAN> <SPAN class="bluebolded"> 
                  &nbsp;1&nbsp;of&nbsp;1</SPAN></TD>
              </TR>
            </TABLE>
          </TD>
          <TD align="right"><IMG src="/images2/sections/previews.gif" width="275" height="63"></TD>
        </TR>
      </TABLE>
      <TABLE width="100%" border="0" cellspacing="0" cellpadding="0">
        <TR> 
          <TD valign="top" width="100%" align="center"> 
            <TABLE width="100%" border="0" cellspacing="0" cellpadding="0" background="/images2/buttons/resize.gif">
              <TR> 
                <TD><IMG src="/images2/buttons/archive.gif" width="130" height="25"></TD>
              </TR>
            </TABLE>
            <TABLE width="100%" border="0" cellspacing="1" cellpadding="0">
              <FORM method="post" action="/previews.phtml">
                <TR> 
                  <TD height="40"><IMG src="/images2/misc/1pix.gif" width="10" height="8"></TD>
                  <TD height="40" width="100%" nowrap><SPAN class="Bolded"><SPAN class="bluebolded">Search Previews:&nbsp;</SPAN></SPAN>&nbsp; 
                    <INPUT type="text" name="search" class="formbody" size="14" maxlength="50" value="">
                    &nbsp; 
                    <SELECT name="rel_category" class="formbody">
                      <option selected value="0">All</option>
<option  value="1">Action</option>
<option  value="15">Adventure</option>
<option  value="3">Hardware</option>
<option  value="16">Other</option>
<option  value="14">Peripherals</option>
<option  value="12">Racing</option>
<option  value="11">RPG</option>
<option  value="2">Simulation</option>
<option  value="4">Software</option>
<option  value="8">Sport</option>
<option  value="9">Strategy</option>
 
                    </SELECT>
                    &nbsp; &nbsp; 
                    <INPUT type="image" border="0" name="imageField2" src="/images2/buttons/search_go.gif" width="24" height="22" align="top">
                  </TD>
                  <TD height="40" class="Bolded" align="right" nowrap>  &nbsp;&nbsp; <IMG src="/images2/misc/1pix.gif" width="10" height="1"></TD>
                </TR>
              </FORM>
            </TABLE>
            <TABLE width="596" border="0" cellspacing="0">
              <TR> 
                <TD><IMG src="/images2/misc/coloredpix.gif" width="596" height="1"></TD>
              </TR>
              <TR> 
                <TD height="30" class="smalltext">Click on a genre title to sort the archive. The <IMG src="/images2/misc/yellowarrow.gif" width="12" height="11">indicates 
                  current sort selection.</TD>
              </TR>
            </TABLE>
            <TABLE width="100%" border="0" cellspacing="0" cellpadding="0">
              <TR> 
                <TD class="smalltext" valign="top">&nbsp;</TD>
                <TD width="45%" class="smalltext" valign="top">&nbsp;</TD>
                <TD class="smalltext" valign="top" width="13%">&nbsp;</TD>
                <TD class="smalltext" valign="top" width="17%">&nbsp;</TD>
                <TD class="smalltext" valign="top" width="25%">&nbsp;</TD>
                <TD class="smalltext" valign="top">&nbsp;</TD>
              </TR>
              <TR> 
                <TD class="smalltext" valign="top"><IMG src="/images2/misc/1pix.gif" width="12" height="1"></TD>
                <TD height="30" class="Bolded" valign="top" nowrap><A class="navlinks" href="/previews.phtml?search=&rel_category=&order=header ASC">Title</A><BR>
                </TD>
                <TD class="Bolded" valign="top" nowrap><img src="/images2/misc/yellowarrow.gif" width="9" height="11">&nbsp;<A class="navlinks" href="/previews.phtml?search=&rel_category=&order=">Added</A></TD>
                <TD class="Bolded" valign="top" nowrap><A class="navlinks" href="/previews.phtml?search=&rel_category=&order=part_game-released">Release date</A></TD>
                <TD class="Bolded" valign="top" nowrap><A class="navlinks" href="/previews.phtml?search=&rel_category=&order=rel_category">Category</A></TD>
                <TD class="smalltext" valign="top"><IMG src="/images2/misc/1pix.gif" width="12" height="8"></TD>
              </TR>
                            <TR> 
                <TD class="smalltext" valign="top">&nbsp;</TD>
                <TD height="25" nowrap><A href="/previews.phtml?id=50645&language=en">• Heart of Winter</A><SPAN class="yellowbolded"> - New!</SPAN></TD>
                <TD valign="top">23/01</TD>
                <TD class="Bolded" valign="top">Q1 2001</TD>
                <TD valign="top" class="gray_normal">RPG</TD>
                <TD class="smalltext" valign="top">&nbsp;</TD>
              </TR>              <TR> 
                <TD class="smalltext" valign="top">&nbsp;</TD>
                <TD height="25" nowrap><A href="/previews.phtml?id=43783&language=en">• BattleField: 1942</A></TD>
                <TD valign="top">14/12</TD>
                <TD class="Bolded" valign="top">q3 2001</TD>
                <TD valign="top" class="gray_normal">Action</TD>
                <TD class="smalltext" valign="top">&nbsp;</TD>
              </TR>              <TR> 
                <TD class="smalltext" valign="top">&nbsp;</TD>
                <TD height="25" nowrap><A href="/previews.phtml?id=43330&language=en">• Kingdom under Fire</A></TD>
                <TD valign="top">12/12</TD>
                <TD class="Bolded" valign="top">January 8th 2001</TD>
                <TD valign="top" class="gray_normal">Strategy</TD>
                <TD class="smalltext" valign="top">&nbsp;</TD>
              </TR>              <TR> 
                <TD class="smalltext" valign="top">&nbsp;</TD>
                <TD height="25" nowrap><A href="/previews.phtml?id=40771&language=en">• Tribes 2</A></TD>
                <TD valign="top">25/11</TD>
                <TD class="Bolded" valign="top">Early 2001</TD>
                <TD valign="top" class="gray_normal">Action</TD>
                <TD class="smalltext" valign="top">&nbsp;</TD>
              </TR>              <TR> 
                <TD class="smalltext" valign="top">&nbsp;</TD>
                <TD height="25" nowrap><A href="/previews.phtml?id=39782&language=en">• Mech Warrior 4</A></TD>
                <TD valign="top">18/11</TD>
                <TD class="Bolded" valign="top"></TD>
                <TD valign="top" class="gray_normal"></TD>
                <TD class="smalltext" valign="top">&nbsp;</TD>
              </TR>              <TR> 
                <TD class="smalltext" valign="top">&nbsp;</TD>
                <TD height="25" nowrap><A href="/previews.phtml?id=35226&language=en">• Monkey Island IV</A></TD>
                <TD valign="top">13/10</TD>
                <TD class="Bolded" valign="top">Nov 2000</TD>
                <TD valign="top" class="gray_normal">Action</TD>
                <TD class="smalltext" valign="top">&nbsp;</TD>
              </TR>              <TR> 
                <TD class="smalltext" valign="top">&nbsp;</TD>
                <TD height="25" nowrap><A href="/previews.phtml?id=34650&language=en">• Combat Flight Simulator II</A></TD>
                <TD valign="top">06/10</TD>
                <TD class="Bolded" valign="top">Nov 2000</TD>
                <TD valign="top" class="gray_normal"></TD>
                <TD class="smalltext" valign="top">&nbsp;</TD>
              </TR>              <TR> 
                <TD class="smalltext" valign="top">&nbsp;</TD>
                <TD height="25" nowrap><A href="/previews.phtml?id=32687&language=en">• Rainbow 6: Covert Ops</A></TD>
                <TD valign="top">12/09</TD>
                <TD class="Bolded" valign="top">29th September</TD>
                <TD valign="top" class="gray_normal"></TD>
                <TD class="smalltext" valign="top">&nbsp;</TD>
              </TR>              <TR> 
                <TD class="smalltext" valign="top">&nbsp;</TD>
                <TD height="25" nowrap><A href="/previews.phtml?id=32472&language=en">• Anarchy Online</A></TD>
                <TD valign="top">10/09</TD>
                <TD class="Bolded" valign="top">In Closed Beta</TD>
                <TD valign="top" class="gray_normal"></TD>
                <TD class="smalltext" valign="top">&nbsp;</TD>
              </TR>              <TR> 
                <TD class="smalltext" valign="top">&nbsp;</TD>
                <TD height="25" nowrap><A href="/previews.phtml?id=32256&language=en">• Rune - ECTS Report</A></TD>
                <TD valign="top">08/09</TD>
                <TD class="Bolded" valign="top"></TD>
                <TD valign="top" class="gray_normal"></TD>
                <TD class="smalltext" valign="top">&nbsp;</TD>
              </TR>              <TR> 
                <TD class="smalltext" valign="top">&nbsp;</TD>
                <TD height="25" nowrap><A href="/previews.phtml?id=31905&language=en">• B17: The Mighty 8th</A></TD>
                <TD valign="top">05/09</TD>
                <TD class="Bolded" valign="top">October 2000</TD>
                <TD valign="top" class="gray_normal"></TD>
                <TD class="smalltext" valign="top">&nbsp;</TD>
              </TR>              <TR> 
                <TD class="smalltext" valign="top">&nbsp;</TD>
                <TD height="25" nowrap><A href="/previews.phtml?id=31907&language=en">• Delta Force 3</A></TD>
                <TD valign="top">05/09</TD>
                <TD class="Bolded" valign="top">November 2000</TD>
                <TD valign="top" class="gray_normal"></TD>
                <TD class="smalltext" valign="top">&nbsp;</TD>
              </TR>              <TR> 
                <TD class="smalltext" valign="top">&nbsp;</TD>
                <TD height="25" nowrap><A href="/previews.phtml?id=31832&language=en">• Red Faction</A></TD>
                <TD valign="top">05/09</TD>
                <TD class="Bolded" valign="top">Q1 2001</TD>
                <TD valign="top" class="gray_normal"></TD>
                <TD class="smalltext" valign="top">&nbsp;</TD>
              </TR>              <TR> 
                <TD class="smalltext" valign="top">&nbsp;</TD>
                <TD height="25" nowrap><A href="/previews.phtml?id=31171&language=en">• Baldurs Gate 2</A></TD>
                <TD valign="top">29/08</TD>
                <TD class="Bolded" valign="top"></TD>
                <TD valign="top" class="gray_normal"></TD>
                <TD class="smalltext" valign="top">&nbsp;</TD>
              </TR>              <TR> 
                <TD class="smalltext" valign="top">&nbsp;</TD>
                <TD height="25" nowrap><A href="/previews.phtml?id=26788&language=en">• Crimson Skies</A></TD>
                <TD valign="top">19/08</TD>
                <TD class="Bolded" valign="top">Third Quarter 2000</TD>
                <TD valign="top" class="gray_normal"></TD>
                <TD class="smalltext" valign="top">&nbsp;</TD>
              </TR>              <TR> 
                <TD class="smalltext" valign="top">&nbsp;</TD>
                <TD height="25" nowrap><A href="/previews.phtml?id=26786&language=en">• Midtown Madness 2</A></TD>
                <TD valign="top">19/08</TD>
                <TD class="Bolded" valign="top">Third Quarter 2000</TD>
                <TD valign="top" class="gray_normal"></TD>
                <TD class="smalltext" valign="top">&nbsp;</TD>
              </TR>              <TR> 
                <TD class="smalltext" valign="top">&nbsp;</TD>
                <TD height="25" nowrap><A href="/previews.phtml?id=27343&language=en">• Max Payne</A></TD>
                <TD valign="top">17/08</TD>
                <TD class="Bolded" valign="top">N/A</TD>
                <TD valign="top" class="gray_normal"></TD>
                <TD class="smalltext" valign="top">&nbsp;</TD>
              </TR>              <TR> 
                <TD class="smalltext" valign="top">&nbsp;</TD>
                <TD height="25" nowrap><A href="/previews.phtml?id=26754&language=en">• Final Fantasy IX</A></TD>
                <TD valign="top">04/08</TD>
                <TD class="Bolded" valign="top">October 2000</TD>
                <TD valign="top" class="gray_normal"></TD>
                <TD class="smalltext" valign="top">&nbsp;</TD>
              </TR>  
            </TABLE>
          </TD>
        </TR>
      </TABLE>
      <P> 
</TR>
      </TABLE>
    </TD>
  </TR>
</TABLE>
 
<TABLE width="750" border="0" cellspacing="0" cellpadding="0">
  <TR> 
    <TD><IMG src="/images2/bottom/copyright.gif" width="340" height="30" border="0"><A href="/privacy.phtml"><IMG src="/images2/bottom/privacy.gif" width="101" height="30" border="0"></A></TD>
    <TD><IMG src="/images2/bottom/bottomplate.gif" width="177" height="30"></TD>
    <TD><A href="#top"><IMG src="/images2/bottom/top.gif" width="68" height="30" border="0"></A></TD>
    <TD><A href="/index.phtml"><IMG src="/images2/bottom/home.gif" width="64" height="30" border="0"></A></TD>
  </TR>
</TABLE>
<TABLE width="750" border="0" cellspacing="0" cellpadding="0" height="90" background="/images2/misc/50x50pix.gif">
  <TR bgcolor="#000000" align="center"> 
    <TD class="smalltext">
      <SCRIPT language="JavaScript"
src="http://adtegrity.spinbox.net/?DC=Mgon+Bottom&JS=Y&TARGET=_new">
</SCRIPT>
      <NOSCRIPT><A href="http://adtegrity.spinbox.net/?SHT=Mgon+Bottom" target="_new"
height="468" width="60"><IMG src="http://adtegrity.spinbox.net/?SIT=Mgon+Bottom" border="0"></A></NOSCRIPT></TD>
  </TR>
</TABLE>
 <SCRIPT LANGUAGE="JavaScript">
/*

//<!--
Debug info
--------------------------------------
//Error 0:
Time elapsed in countContent: 0.0028579235076904
No sql info
No more details

//Error 1:
Parsed part <!--part_game-released-->
No sql info
No more details

//Error 2:
Time spent in regexp: 0
No sql info
No more details

//Error 3:
Time spent in regexp: 0
No sql info
No more details

//Error 4:
Time spent in regexp: 0
No sql info
No more details

//Error 5:
Time spent in regexp: 0
No sql info
No more details

//Error 6:
Time spent in regexp: 0
No sql info
No more details

//Error 7:
Time spent in regexp: 0
No sql info
No more details

//Error 8:
Time spent in regexp: 0
No sql info
No more details

//Error 9:
Time spent in regexp: 0
No sql info
No more details

//Error 10:
Time spent in regexp: 0
No sql info
No more details

//Error 11:
Time spent in regexp: 0
No sql info
No more details

//Error 12:
Time spent in regexp: 0
No sql info
No more details

//Error 13:
Time spent in regexp: 0
No sql info
No more details

//Error 14:
Time spent in regexp: 0
No sql info
No more details

//Error 15:
Time spent in regexp: 0
No sql info
No more details

//Error 16:
Time spent in regexp: 0
No sql info
No more details

//Error 17:
Time spent in regexp: 0
No sql info
No more details

//Error 18:
Time spent in regexp: 0
No sql info
No more details

//Error 19:
Time spent in regexp: 0
No sql info
No more details

//Error 20:
Time elapsed in listContent: 0.069155931472778
No sql info
No more details

21 errors.


Queries
--------------------------------------
Query 0:
Query: SELECT COUNT(DISTINCT co.ID) FROM content AS co INNER JOIN content_sections AS s ON(co.section = s.ID) WHERE co.published=1  AND co.section=474 AND co.language='en' 
Result: OK
User: php
Database server: localhost()
Time: 0.0020849704742432 seconds

Query 1:
Query: SELECT rel_category FROM content_sections WHERE ID=474
Result: OK
User: php
Database server: localhost()
Time: 0.00055408477783203 seconds

Query 2:
Query: SELECT ID,name FROM relations_category  ORDER BY name ASC
Result: OK
User: php
Database server: localhost()
Time: 0.00059902667999268 seconds

Query 3:
Query: SELECT DISTINCT co.ID AS ID,co.icon AS icon,co.section AS section,co.header AS header,UNIX_TIMESTAMP(co.created) AS created,co.creatorname as nick,co.creatoremail as email,s.name as section_name,s.location as url,co.language AS language, UNIX_TIMESTAMP(co.created) - UNIX_TIMESTAMP() AS new, `tgame-released`.value AS `part_game-released`, rcategory.name AS rel_category FROM content AS co INNER JOIN content_sections AS s ON(co.section = s.ID) LEFT JOIN content_parts AS `tgame-released` ON(`tgame-released`.name = 'game-released' AND `tgame-released`.parent = co.ID AND `tgame-released`.language = co.language) LEFT JOIN content_relations AS rel ON(rel.parent = co.ID) LEFT JOIN relations_category AS rcategory ON (rcategory.ID = rel.category) WHERE co.published=1  AND co.section=474 AND co.language='en'  ORDER BY co.created DESC LIMIT 0, 50
Result: OK
User: php
Database server: localhost()
Time: 0.0065940618515015 seconds

Query 4:
Query: SELECT COUNT(DISTINCT co.ID) FROM content AS co INNER JOIN content_sections AS s ON(co.section = s.ID) LEFT JOIN content_parts AS `tgame-released` ON(`tgame-released`.name = 'game-released' AND `tgame-released`.parent = co.ID AND `tgame-released`.language = co.language) LEFT JOIN content_relations AS rel ON(rel.parent = co.ID) LEFT JOIN relations_category AS rcategory ON (rcategory.ID = rel.category) WHERE co.published=1  AND co.section=474 AND co.language='en' 
Result: OK
User: php
Database server: localhost()
Time: 0.0040129423141479 seconds

5 queries.
-->
*/

</SCRIPT>
 
<!--Bottom Layer-->
<LAYER SRC="http://ad.se.doubleclick.net/adl/mgon.com/;sz=468x60;ord=981210830?" bgcolor="#000000" width="468" height="60" visibility="hidden" onLoad="moveToAbsolute(layer1.pageX,layer1.pageY);clip.height=60;clip.width=468; visibility='show';"></LAYER><!--End Bottom Layer--></BODY>

</HTML>


