<html>

<head>
<% ' FP_ASP -- ASP Automatically generated by a Frontpage Component. Do not Edit.
FP_CharSet = "windows-1252"
FP_CodePage = 1252 %>
<meta http-equiv="Content-Type" content="text/html; charset=windows-1252">
<meta name="GENERATOR" content="Microsoft FrontPage 5.0">
<meta name="ProgId" content="FrontPage.Editor.Document">
<title>Amber Order Membership</title>
</head>

<body stylesrc="home.htm" bgcolor="#DCDEB4" link="#60709F" vlink="#60709F" alink="#8000FF">

<blockquote>
  <blockquote>

    <p><img border="0" src="images/Title_Roster.gif"></p>
  </blockquote>
</blockquote>
<div align="center">
  <center>
  <table width="80%" border="1" cellspacing="0" cellpadding="0" bordercolor="#DCDEB4" style="border-collapse: collapse">
    <thead>
      <tr>
        <td bgcolor="#60709F" style="font-family: Arial"><b>
        <font size="2" color="#CDD123">MemberAlias</font></b></td>
        <td bgcolor="#60709F" style="font-family: Arial"><b>
        <font size="2" color="#CDD123">Rank</font></b></td>
        <td bgcolor="#60709F" style="font-family: Arial"><b>
        <font size="2" color="#CDD123">Gender</font></b></td>
        <td bgcolor="#60709F" style="font-family: Arial"><b>
        <font size="2" color="#CDD123">Race</font></b></td>
        <td bgcolor="#60709F" style="font-family: Arial"><b>
        <font size="2" color="#CDD123">Class</font></b></td>
        <td bgcolor="#60709F" style="font-family: Arial"><b>
        <font size="2" color="#CDD123">Level</font></b></td>
      </tr>
    </thead>
    <tbody>
      <!--webbot bot="DatabaseRegionStart" s-columnnames="ID,MemberAlias,Rank,Gender,Race,Class,Level" s-columntypes="3,200,200,200,200,200,16" s-dataconnection="AO-MySQL" b-tableformat="TRUE" b-menuformat="FALSE" s-menuchoice="MemberAlias" s-menuvalue="MemberAlias" b-tableborder="TRUE" b-tableexpand="TRUE" b-tableheader="TRUE" b-listlabels="TRUE" b-listseparator="TRUE" i-listformat="0" b-makeform="FALSE" s-recordsource s-displaycolumns="MemberAlias,Rank,Gender,Race,Class,Level" s-criteria s-order s-sql="SELECT * FROM Membership_Roster WHERE ((Rank LIKE '%Commander%' OR Rank LIKE '%Protector%') AND Level &amp;gt;=  50) ORDER BY MemberAlias ASC" b-procedure="FALSE" clientside suggestedext="asp" s-defaultfields s-norecordsfound="No records returned." i-maxrecords="0" i-groupsize="0" botid="0" u-dblib="_fpclass/fpdblib.inc" u-dbrgn1="_fpclass/fpdbrgn1.inc" u-dbrgn2="_fpclass/fpdbrgn2.inc" tag="TBODY" preview="&lt;tr&gt;&lt;td colspan=64 bgcolor=&quot;#FFFF00&quot; align=&quot;left&quot; width=&quot;100%&quot;&gt;&lt;font color=&quot;#000000&quot;&gt;This is the start of a Database Results region.&lt;/font&gt;&lt;/td&gt;&lt;/tr&gt;" b-WasTableFormat="TRUE" b-ReplaceDatabaseRegion="FALSE" startspan --><!--#include file="_fpclass/fpdblib.inc"-->
<% if 0 then %>
<SCRIPT Language="JavaScript">
document.write("<div style='background: yellow; color: black;'>The Database Results component on this page is unable to display database content. The page must have a filename ending in '.asp', and the web must be hosted on a server that supports Active Server Pages.</div>");
</SCRIPT>
<% end if %>
<%
fp_sQry="SELECT * FROM Membership_Roster WHERE ((Rank LIKE '%Commander%' OR Rank LIKE '%Protector%') AND Level >=  50) ORDER BY MemberAlias ASC"
fp_sDefault=""
fp_sNoRecords="<tr><td colspan=6 align=left width=""100%"">No records returned.</td></tr>"
fp_sDataConn="AO-MySQL"
fp_iMaxRecords=0
fp_iCommandType=1
fp_iPageSize=0
fp_fTableFormat=True
fp_fMenuFormat=False
fp_sMenuChoice="MemberAlias"
fp_sMenuValue="MemberAlias"
fp_iDisplayCols=6
fp_fCustomQuery=True
BOTID=0
fp_iRegion=BOTID
%>
<!--#include file="_fpclass/fpdbrgn1.inc"-->
<!--webbot bot="DatabaseRegionStart" endspan --><tr>
        <td style="font-family: Arial"><font size="1" color="#60709F">
        <!--webbot bot="DatabaseResultColumn" s-columnnames="ID,MemberAlias,Rank,Gender,Race,Class,Level" s-column="MemberAlias" b-tableformat="TRUE" b-hashtml="FALSE" b-makelink="FALSE" clientside b-MenuFormat preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;MemberAlias&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" startspan --><%=FP_FieldVal(fp_rs,"MemberAlias")%><!--webbot bot="DatabaseResultColumn" endspan --></font></td>
        <td style="font-family: Arial"><font size="1" color="#60709F">
        <!--webbot bot="DatabaseResultColumn" s-columnnames="ID,MemberAlias,Rank,Gender,Race,Class,Level" s-column="Rank" b-tableformat="TRUE" b-hashtml="FALSE" b-makelink="FALSE" clientside b-MenuFormat preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Rank&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" startspan --><%=FP_FieldVal(fp_rs,"Rank")%><!--webbot bot="DatabaseResultColumn" endspan --></font></td>
        <td style="font-family: Arial"><font size="1" color="#60709F">
        <!--webbot bot="DatabaseResultColumn" s-columnnames="ID,MemberAlias,Rank,Gender,Race,Class,Level" s-column="Gender" b-tableformat="TRUE" b-hashtml="FALSE" b-makelink="FALSE" clientside b-MenuFormat preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Gender&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" startspan --><%=FP_FieldVal(fp_rs,"Gender")%><!--webbot bot="DatabaseResultColumn" endspan --></font></td>
        <td style="font-family: Arial"><font size="1" color="#60709F">
        <!--webbot bot="DatabaseResultColumn" s-columnnames="ID,MemberAlias,Rank,Gender,Race,Class,Level" s-column="Race" b-tableformat="TRUE" b-hashtml="FALSE" b-makelink="FALSE" clientside b-MenuFormat preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Race&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" startspan --><%=FP_FieldVal(fp_rs,"Race")%><!--webbot bot="DatabaseResultColumn" endspan --></font></td>
        <td style="font-family: Arial"><font size="1" color="#60709F">
        <!--webbot bot="DatabaseResultColumn" s-columnnames="ID,MemberAlias,Rank,Gender,Race,Class,Level" s-column="Class" b-tableformat="TRUE" b-hashtml="FALSE" b-makelink="FALSE" clientside b-MenuFormat preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Class&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" startspan --><%=FP_FieldVal(fp_rs,"Class")%><!--webbot bot="DatabaseResultColumn" endspan --></font></td>
        <td style="font-family: Arial"><font size="1" color="#60709F">
        <!--webbot bot="DatabaseResultColumn" s-columnnames="ID,MemberAlias,Rank,Gender,Race,Class,Level" s-column="Level" b-tableformat="TRUE" b-hashtml="FALSE" b-makelink="FALSE" clientside b-MenuFormat preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Level&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" startspan --><%=FP_FieldVal(fp_rs,"Level")%><!--webbot bot="DatabaseResultColumn" endspan --></font></td>
      </tr>
      <!--webbot bot="DatabaseRegionEnd" b-tableformat="TRUE" b-menuformat="FALSE" u-dbrgn2="_fpclass/fpdbrgn2.inc" i-groupsize="0" clientside tag="TBODY" preview="&lt;tr&gt;&lt;td colspan=64 bgcolor=&quot;#FFFF00&quot; align=&quot;left&quot; width=&quot;100%&quot;&gt;&lt;font color=&quot;#000000&quot;&gt;This is the end of a Database Results region.&lt;/font&gt;&lt;/td&gt;&lt;/tr&gt;" startspan --><!--#include file="_fpclass/fpdbrgn2.inc"-->
<!--webbot bot="DatabaseRegionEnd" endspan --></tbody>
  </table>
  </center>
</div>
<p><br>
</p>
<div align="center">
  <center>
  <table width="80%" border="0" cellspacing="0" cellpadding="0" style="border-collapse: collapse" bordercolor="#111111">
    <thead>
      <tr>
        <td bgcolor="#60709F"><font face="Arial" size="2" color="#CDD123"><b>
        MemberAlias</b></font></td>
        <td bgcolor="#60709F"><font face="Arial" size="2" color="#CDD123"><b>
        Rank</b></font></td>
        <td bgcolor="#60709F"><font face="Arial" size="2" color="#CDD123"><b>
        Gender</b></font></td>
        <td bgcolor="#60709F"><font face="Arial" size="2" color="#CDD123"><b>
        Race</b></font></td>
        <td bgcolor="#60709F"><font face="Arial" size="2" color="#CDD123"><b>
        Class</b></font></td>
        <td bgcolor="#60709F"><font face="Arial" size="2" color="#CDD123"><b>
        Level</b></font></td>
      </tr>
    </thead>
    <tbody>
      <!--webbot bot="DatabaseRegionStart" s-columnnames="ID,MemberAlias,Rank,Gender,Race,Class,Level" s-columntypes="3,200,200,200,200,200,16" s-dataconnection="AO-MySQL" b-tableformat="TRUE" b-menuformat="FALSE" s-menuchoice s-menuvalue b-tableborder="TRUE" b-tableexpand="TRUE" b-tableheader="TRUE" b-listlabels="TRUE" b-listseparator="TRUE" i-listformat="0" b-makeform="TRUE" s-recordsource s-displaycolumns="ID,MemberAlias,Rank,Gender,Race,Class,Level" s-criteria s-order s-sql="SELECT * FROM Membership_Roster WHERE ((Rank =  'Knight' OR Rank =  'Squire' OR Rank =  'Initiate') AND Level &gt;= 50)  ORDER BY MemberAlias ASC" b-procedure="FALSE" clientside suggestedext="asp" s-defaultfields s-norecordsfound="No records returned." i-maxrecords="0" i-groupsize="0" botid="1" u-dblib="_fpclass/fpdblib.inc" u-dbrgn1="_fpclass/fpdbrgn1.inc" u-dbrgn2="_fpclass/fpdbrgn2.inc" tag="TBODY" preview="&lt;tr&gt;&lt;td colspan=64 bgcolor=&quot;#FFFF00&quot; align=&quot;left&quot; width=&quot;100%&quot;&gt;&lt;font color=&quot;#000000&quot;&gt;This is the start of a Database Results region.&lt;/font&gt;&lt;/td&gt;&lt;/tr&gt;" startspan --><!--#include file="_fpclass/fpdblib.inc"-->
<% if 0 then %>
<SCRIPT Language="JavaScript">
document.write("<div style='background: yellow; color: black;'>The Database Results component on this page is unable to display database content. The page must have a filename ending in '.asp', and the web must be hosted on a server that supports Active Server Pages.</div>");
</SCRIPT>
<% end if %>
<%
fp_sQry="SELECT * FROM Membership_Roster WHERE ((Rank =  'Knight' OR Rank =  'Squire' OR Rank =  'Initiate') AND Level >= 50)  ORDER BY MemberAlias ASC"
fp_sDefault=""
fp_sNoRecords="<tr><td colspan=7 align=left width=""100%"">No records returned.</td></tr>"
fp_sDataConn="AO-MySQL"
fp_iMaxRecords=0
fp_iCommandType=1
fp_iPageSize=0
fp_fTableFormat=True
fp_fMenuFormat=False
fp_sMenuChoice=""
fp_sMenuValue=""
fp_iDisplayCols=7
fp_fCustomQuery=True
BOTID=1
fp_iRegion=BOTID
%>
<!--#include file="_fpclass/fpdbrgn1.inc"-->
<!--webbot bot="DatabaseRegionStart" endspan --><tr>
        <td><font face="Arial" size="1" color="#60709F">
        <!--webbot bot="DatabaseResultColumn" s-columnnames="ID,MemberAlias,Rank,Gender,Race,Class,Level" s-column="MemberAlias" b-tableformat="TRUE" b-hashtml="FALSE" b-makelink="FALSE" clientside b-MenuFormat preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;MemberAlias&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" startspan --><%=FP_FieldVal(fp_rs,"MemberAlias")%><!--webbot bot="DatabaseResultColumn" endspan --></font></td>
        <td><font face="Arial" size="1" color="#60709F">
        <!--webbot bot="DatabaseResultColumn" s-columnnames="ID,MemberAlias,Rank,Gender,Race,Class,Level" s-column="Rank" b-tableformat="TRUE" b-hashtml="FALSE" b-makelink="FALSE" clientside b-MenuFormat preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Rank&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" startspan --><%=FP_FieldVal(fp_rs,"Rank")%><!--webbot bot="DatabaseResultColumn" endspan --></font></td>
        <td><font face="Arial" size="1" color="#60709F">
        <!--webbot bot="DatabaseResultColumn" s-columnnames="ID,MemberAlias,Rank,Gender,Race,Class,Level" s-column="Gender" b-tableformat="TRUE" b-hashtml="FALSE" b-makelink="FALSE" clientside b-MenuFormat preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Gender&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" startspan --><%=FP_FieldVal(fp_rs,"Gender")%><!--webbot bot="DatabaseResultColumn" endspan --></font></td>
        <td><font face="Arial" size="1" color="#60709F">
        <!--webbot bot="DatabaseResultColumn" s-columnnames="ID,MemberAlias,Rank,Gender,Race,Class,Level" s-column="Race" b-tableformat="TRUE" b-hashtml="FALSE" b-makelink="FALSE" clientside b-MenuFormat preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Race&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" startspan --><%=FP_FieldVal(fp_rs,"Race")%><!--webbot bot="DatabaseResultColumn" endspan --></font></td>
        <td><font face="Arial" size="1" color="#60709F">
        <!--webbot bot="DatabaseResultColumn" s-columnnames="ID,MemberAlias,Rank,Gender,Race,Class,Level" s-column="Class" b-tableformat="TRUE" b-hashtml="FALSE" b-makelink="FALSE" clientside b-MenuFormat preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Class&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" startspan --><%=FP_FieldVal(fp_rs,"Class")%><!--webbot bot="DatabaseResultColumn" endspan --></font></td>
        <td><font face="Arial" size="1" color="#60709F">
        <!--webbot bot="DatabaseResultColumn" s-columnnames="ID,MemberAlias,Rank,Gender,Race,Class,Level" s-column="Level" b-tableformat="TRUE" b-hashtml="FALSE" b-makelink="FALSE" clientside b-MenuFormat preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Level&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" startspan --><%=FP_FieldVal(fp_rs,"Level")%><!--webbot bot="DatabaseResultColumn" endspan --></font></td>
      </tr>
      <!--webbot bot="DatabaseRegionEnd" b-tableformat="TRUE" b-menuformat="FALSE" u-dbrgn2="_fpclass/fpdbrgn2.inc" i-groupsize="0" clientside tag="TBODY" preview="&lt;tr&gt;&lt;td colspan=64 bgcolor=&quot;#FFFF00&quot; align=&quot;left&quot; width=&quot;100%&quot;&gt;&lt;font color=&quot;#000000&quot;&gt;This is the end of a Database Results region.&lt;/font&gt;&lt;/td&gt;&lt;/tr&gt;" startspan --><!--#include file="_fpclass/fpdbrgn2.inc"-->
<!--webbot bot="DatabaseRegionEnd" endspan --></tbody>
  </table>
  </center>
</div>
	<div align="center">
      <center>
	<table border="0" cellpadding="0" cellspacing="0" style="border-collapse: collapse" bordercolor="#111111">
    <tr>
      <td valign="top" width="564" height="40">
      <p align="center">
        &nbsp;</p>
        <p align="center">
        <small><font face="Arial">[ </font><font color="#60709F" face="Arial"><a
    href="http://www.amberorder.com/home.htm" target="main" style="color: rgb(96,112,159)">Home</a></font><font
    face="Arial"> | </font><font color="#60709F" face="Arial"><a
    href="http://www.amberorder.com/charter.htm" style="color: rgb(96,112,159)" target="main">Charter</a></font><font
    face="Arial">&nbsp; | </font><a style="color: rgb(96,112,159)"
    href="http://www.amberorder.com/CoC.htm" target="main"><font color="#60709F" face="Arial">Code
    of Conduct</font></a><font face="Arial"> | </font>
        <a target="main" style="color: rgb(96,112,159)" href="http://www.amberorder.com/ao_application.php"><font color="#60709F" face="Arial">Join</font></a><font
    face="Arial"> | </font><a href="http://www.amberorder.com/chat.htm" target="main"
    style="color: rgb(96,112,159)"><font face="Arial">Chat</font></a><font face="Arial"> | </font><a
    href="http://www.amberorder.com/aoroster.asp" target="main" style="color: rgb(96,112,159)"><font
    color="#60709F" face="Arial">Members</font></a><font face="Arial"> |
        <a href="apps200008/"><span style="color: #60709F">Calendar Admin</span></a> | <font
    color="#60709F"><a href="http://www.amberorder.com/links.htm" target="main"
    style="color: rgb(96,112,159)">Links</a></font> ] </font></small><font face="Arial"> <br>
        <small>[ </small> </font>
        <small>
        <a target="main" style="color: rgb(96,112,159)" href="http://cave.amberorder.com/phpBB2/viewforum.php?f=10"><font color="#60709F" face="Arial">Announcements</font></a><font
    face="Arial"> | </font><a target="_top" href="forums/"><font color="#60709F" face="Arial">Discussions</font></a><font
    face="Arial"> | </font><a href="http://www.amberorder.com/forums/events.asp" target="main" style="color: rgb(96,112,159)"><font color="#60709F" face="Arial">Events</font></a><font
    face="Arial"> | </font><font color="#60709F" face="Arial">
        <a target="main" style="color: rgb(96,112,159)" href="/forums/tales.asp">Tales &amp; Stories</a></font><font face="Arial"> 
        | <a href="roster_db">Members DB Admin</a> ]<br>
        </font></small><br>
    Copyright© 2000,2001, The Amber Order.<br>
        <small>For more information, email
        <a style="color: rgb(96,112,159)" href="mailto:bear[at]amberorder.com">
        Bearpaws</a></small></p>
        <p align="center">&nbsp;<img border="0" src="images/PwrdByMySQL%20copy.gif">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <img border="0" src="images/logo_phpBBsmall.gif"><br>
&nbsp;</td>
    	</tr>
    </table>
      </center>
    </div>

</body></html>