<!--
                 This page has been created by Renaissance IT
   Renaissance Internet Technologies Copyright (c) 1999 All Rights Reserved.

             for more info on our products, please visit :
                        http://www.renaissance.nl/

	This script has been written by Roy Boverhof <rboverhof@renaissance.nl>
	
        Pagename                : brewing.html
        Last Updated    		: 28-7-1999
-->

<HTML>
<HEAD>
	<TITLE>the Seekers of Lore : guide to Brewing</TITLE>
</HEAD>

<BODY BGCOLOR="#000000" TEXT="#000000" LINK="#FFF000">
<DIV ALIGN="CENTER">
<BR>
<!-- FGN Banner Code -->
<script language="JavaScript">
	<!-- Hide from old browsers
	var random = new Number(Math.floor(9999999 * Math.random())+1);

	// Modify to reflect site specifics
	page = "eqlore.com/";
	target = "@Top1,x02,x05,x08!Top1";

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript1.1" SRC="http://oascentral.cybereps.com/RealMedia/ads/adstream_jx.ads/' + page + 1 + random + target + '">');
	document.write('</SCR');
	document.write('IPT>');

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript">');
	document.write('_version=10; //-->');
	document.write('</SCR');
	document.write('IPT>');

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript1.1">');
	document.write('_version=11; //-->');
	document.write('</SCR');
	document.write('IPT>');

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript">');

	if (navigator.appVersion.indexOf('MSIE 3') != -1){
	document.write('<IFRAME MARGINWIDTH=0 MARGINHEIGHT=0 HSPACE=0 VSPACE=0 FRAMEBORDER=0 SCROLLING=no BORDERCOLOR="#000000" SRC="oascentral.cybereps.com/RealMedia/ads/adstream_sx.ads/' + page + random + target + '"></IFRAME>');
	  }
	else if (_version < 11) {
	document.write ('<A HREF="http://oascentral.cybereps.com/RealMedia/ads/click_nx.ads/' + page + random + target + '"><IMG SRC="http://oascentral.cybereps.com/RealMedia/ads/adstream_nx.ads/' + page + random + target + '"></a>');
	  }

	document.write('</SCR');
	document.write('IPT>');

	// End Hide -->
</script>
<!-- END FGN Banner Code --><BR>
<TABLE CELLSPACING = 0 CELLPADDING = 0 BORDER = 0>
<TR>
	<TD width="63"><IMG SRC = "../graphics/topc000.jpg" WIDTH = 63 HEIGHT = 87></TD>
	<TD width="473"><IMG SRC = "../graphics/topc001.jpg" WIDTH = 473 HEIGHT = 87></TD>
	<TD width="64"><IMG SRC = "../graphics/topc002.jpg" WIDTH = 64 HEIGHT = 87></TD>
</TR>
	<TD width="63"></TD>
	<TD BGCOLOR="#BEA279" width="460">
	<TABLE WIDTH="460">
	<TR>
		<TD>		
			<B><FONT SIZE=4><P>The Fine art of Brewing</P>
			</B></FONT><FONT SIZE=2><P>By <A HREF="mailto:mullir@earthlint.net">Nathanial</A>- Teir’Dal Necromancer of Tarew Marr</P>
			<P> </P>
			<P>First, the suggeseted process states to start with about 10pp. And with this, you can master the skill.</P>
			<P> </P>
			<P>To allow you an idea of how this works, I’ll start with letting you know my stats that pertain to this, and MOST trade skills.</P>
			<P> </P>
			<B><I><P>Nathanial</P>
			<P>Int 146</P>
			<P>Wis 83</P>
			<P>Dex 96</P>
			<P>Charisma 65</P>
			</B></I><P> </P>
			<P>First, you need the ingredients:</P>
			<P> </P>
			<B><P>Ale</B> = barley + malt + water + a cask. </P>
			<B><P>Mead</B> = Hops + Malt + Yeasts + a cask. </P>
			<B><P>Ogre Swill</B> = Cask + Froglock meat + Malt + Yeast. </P>
			<B><P>Ol'Tujim's Fierce Brew</B> = Barley + Hops + Yeast + Malt + Cask.</P>
			<B><P>Short Ale</B> = Barley + Hops + Water + a cask. </P>
			<B><P>Short Beer</B> = Barley + hops + malt + a cask. </P>
			<B><P>Tumpy Tonic</B> = 1 Kiola Nut, 1 Flask of water. (Does not require Cask or Bottle)</P>
			<P> </P>
			<P>These are the seven known recepies.</P>
			<P> </P>
			<P>It’s best to start with either Short Ale or Short Beer (Don’t remember which is the easiest)</P>
			<P> </P>
			<P>For me, each ingredient was about 1sp, 9cp. The Cask is 3sp, 6cp.</P>
			<P> </P>
			<P>Brew the Short Ale or Short beer till it becomes trivial. About Skill 30ish. After this, try Ale or Mead. At around 50, you can begin with Ol’Tujim’s Fierce Brew with occasional success. These successes on this brew are not very common until about 90 though.</P>
			<P> </P>
			<P>With the stats listed above, it took me roughly an hour and a half, but I also skipped the middle man. I went straight at 30 skill to brewing Ol’Tujim’s. With rare successes, but rapid advancement. The best part of Ol’Tujim’s, is when you succeed, you get FIVE items of the brew instead of one. So far, this was the only item that produced this many multiples. Ale creates <B><U>TWO</B></U> units.. After you reach 101 (Master) you will tend to make these multiple about 75% of the time. And at 135 skill, where this item becomes trivial, I was succeeding roughly 18 out of 20 times.</P>
			<P> </P>
			<P>When selling, I made 8gp, 8sp off 20 of these. When you stop and calculate it, as my roommate was doing, I was averaging 3.7pp per run, which was nearly a 2pp profit. With a higher Charisma, I should be able to sell for higher profit. Also, I Was selling to a Vendor that only gave me 4sp 4cp when there was another vendor, in another zone that would give me 4sp 6cp. This may not seem like much, but when you sell 80 items of this from one run, which was about what I averaged, that’s an extra 1sp 6cp. Again, with a higher Charisma, we’re looking at no doubt a much greater profit margin, and I will be playing around with this shortly.</P>
			<P> </P>
			<P>Within 2 hours, I had made back my initial funds placed into leveling the skill, and was getting pure profit including what was being sold. I spent roughly 2pp per run, and made 4pp off it.</P>
			<P> </P>
			<P>These profits are straight to Vendors though, as not to many players are in the market for brew and I’ve not seen a high turn over on this as an "In demand" skill."</P>
			<P> </P>
			<P>This strategy is for those that may want to take the time, master a skill, which trade skills are NOT limited by level, and be able to make a pure profit from it. The skill can be mastered without having to pour in large amounts of money such as with blacksmithing, or Fletching (After the last patch), nor do you have to leave the city and hunt, such as with tailoring, and isn’t just sitting there clicking one button such as with fishing. Don’t get me wrong, it’s not "exciting" unless yer doing what I was, and carrying on chats, and working out the details of this with my roommate as a possible means of money. Course, the fact we actually worked out the average time of how long it would take me to earn 5000pp this way is rather scary, but, that’s another matter all together.</P>
			<P> </P>
			<P>I’ll post again at a later time when I’ve tried a suggestion from a friend who stated another trade skill, where in he tells me I can earn 30pp within an hour just straight to a Vendor. Like I said, I’ll get back to ya on this one when I find out if it works as he states.</P>
			<P> </P>
			<B><I><P>Nathanial MB</P>
			<P>Teir’Dal Necromancer</P>
			</B></I><P>(MB = Master Brewer. Figured I’d use it like when ya get a College Degree. Adds a few letters to yer name) </P></FONT>
		</TD>
	</TR>
	</TABLE>	

	</TD>
	<TD width="64"></TD>
<TR>
	<TD><IMG SRC = "../graphics/botc000.jpg" WIDTH = 63 HEIGHT = 87></TD>
	<TD><IMG SRC = "../graphics/botc001.jpg" WIDTH = 473 HEIGHT = 87></TD>
	<TD><IMG SRC = "../graphics/botc002.jpg" WIDTH = 64 HEIGHT = 87></TD>
</TR>
</TABLE>
<BR>
<IMG SRC="http://service.bfast.com/bfast/serve?bfmid=1375281&siteid=40292692&bfpage=pc" BORDER="0" WIDTH="1" HEIGHT="1" NOSAVE ><A HREF="http://service.bfast.com/bfast/click?bfmid=1375281&siteid=40292692&bfpage=pc" TARGET="_new"><IMG SRC="http://affiliate.gamestop.com/affIMG/pc_120x60.gif" BORDER="0" WIDTH="120" HEIGHT="60" ALT="PC Games at GameStop.com"></A>
<BR>
<BR>
</DIV>
</BODY>
</HTML>
