<!--
                 This page has been created by Renaissance IT
   Renaissance Internet Technologies Copyright (c) 1999 All Rights Reserved.

             for more info on our products, please visit :
                        http://www.renaissance.nl/

	This script has been written by Roy Boverhof <rboverhof@renaissance.nl>
	
        Pagename                : madwand.phtml
        Last Updated    		: 08-23-2000
-->

<HTML>
<HEAD>
	<TITLE>the Seekers of Lore : MadWand's Return</TITLE>
</HEAD>

<BODY BGCOLOR="#000000" TEXT="#000000" LINK="#000000" VLINK="#000000" ALINK="#000000">
<DIV ALIGN="CENTER">
<BR>
<!-- FGN Banner Code -->
<script language="JavaScript">
	<!-- Hide from old browsers
	var random = new Number(Math.floor(9999999 * Math.random())+1);

	// Modify to reflect site specifics
	page = "eqlore.com/";
	target = "@Top1,x02,x05,x08!Top1";

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript1.1" SRC="http://oascentral.cybereps.com/RealMedia/ads/adstream_jx.ads/' + page + 1 + random + target + '">');
	document.write('</SCR');
	document.write('IPT>');

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript">');
	document.write('_version=10; //-->');
	document.write('</SCR');
	document.write('IPT>');

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript1.1">');
	document.write('_version=11; //-->');
	document.write('</SCR');
	document.write('IPT>');

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript">');

	if (navigator.appVersion.indexOf('MSIE 3') != -1){
	document.write('<IFRAME MARGINWIDTH=0 MARGINHEIGHT=0 HSPACE=0 VSPACE=0 FRAMEBORDER=0 SCROLLING=no BORDERCOLOR="#000000" SRC="oascentral.cybereps.com/RealMedia/ads/adstream_sx.ads/' + page + random + target + '"></IFRAME>');
	  }
	else if (_version < 11) {
	document.write ('<A HREF="http://oascentral.cybereps.com/RealMedia/ads/click_nx.ads/' + page + random + target + '"><IMG SRC="http://oascentral.cybereps.com/RealMedia/ads/adstream_nx.ads/' + page + random + target + '"></a>');
	  }

	document.write('</SCR');
	document.write('IPT>');

	// End Hide -->
</script>
<!-- END FGN Banner Code --><BR>

<TABLE CELLSPACING=0 CELLPADDING=0 BORDER=0>
<TR>
<TD width="63"><IMG SRC="../graphics/topc000.jpg" WIDTH=63 HEIGHT=87></TD>
<TD width="473"><IMG SRC="../graphics/topc001.jpg" WIDTH=473 HEIGHT=87></TD>
<TD width="64"><IMG SRC="../graphics/topc002.jpg" WIDTH=64 HEIGHT=87></TD>
</TR>
<TD width="63"></TD>
<TD BGCOLOR="#BEA279" width="460">

<DIV ALIGN="CENTER">

<TABLE>
<TR>
<TD BGCOLOR="#BEA279" width="400">

<P><FONT FACE="Times New Roman, Arial, Verdana" SIZE=6>
<DIV ALIGN="center"><I>A Pact with Innoruuk</I></DIV>
</FONT><BR><BR>

<TABLE CELLSPACING=0 CELLPADDING=10>
<TR>
<TD WIDTH=200 ALIGN="left"><IMG SRC="../graphics/old_madwand.jpg" WIDTH=200 HEIGHT=300 BORDER=0></TD>
<TD WIDTH=180 ALIGN="left">
<FONT FACE="Times new roman, Arial" SIZE=3>
<FONT SIZE="+2"><B>M</B></FONT>adwand walks the streets of West Freeport. His steps, heavy and slow with age, echo off the strong high walls that surround the Academy of Arcane Sciences.<BR><BR>

He had another name once. But after almost 300 years on this plane, he can no longer remember what it was. This bothers him.
</FONT>
</TD>
</TR>
</TABLE>

<FONT FACE="Times new roman, Arial" SIZE=3>
<P><FONT SIZE="+2"><B>T</B></FONT>here was a time when he could remember everything he ever read, saw or experienced, yet as his life got ever closer to the end, Madwand started to forget more then he once knew. His whole purpose in life was to seek out and learn all the knowledge in Norrath, and it troubled him greatly that he would soon no longer be able to continue that never-ending quest. He had sacrificed so much for his cause!

<P>You see, Madwand used to be a normal citizen of Freeport, until that fateful day when he discovered &quot;The Book&quot;. No one knows exactly what ancient tome he unearthed while digging the fields to the east of the city, but by the end of that day, he had shed his name and left Freeport, never to be seen again until almost a whole century had past. 

<P>He was called &quot;Madwand&quot; because he was one of rare natural talent. Someone born with the magical abilities but never put to the Academy for training. Instead, he came into the power on his own, learning by himself through painful trial and error. Only a very few wizards ever survived without the guidance of a master, but it was generally thought that those that did were among the most powerful practitioners. The mighty Al'Kabor himself is believed to have been a mad wand as well.

<P>Now he walks alone at night, the streets quiet in these pre-dawn hours. He is almost sure that he will not see the dawn. He despairs because he has no apprentice, none to carry on his life's task. And he has regrets, he regrets that he retired from the Seekers so long ago. Before he could find and train his successor. He can not even take solace from his god because he gave up that when he chose knowledge over religion. 

<P>So absorbed in his self-pity, Madwand doesn't realize that he has walked much further then usual this night. With a start, he glances up at the sound of a distant scream and sees he has walked all the way across town to the eastern quarter of Freeport. Not since his younger days has he walked this part of town at night. For a moment he smiles in remembrance of another life when he used to frequent the taverns in this part of town, where a cold ale and a warm woman were easily found.

<P>Madwand's momentary joy in those thoughts is forgotten when a militia guard comes roaring around the corner pursuing what looks to be a cut purse.

<P>&quot;<I>Halt!</I>&quot; yells the guard, &quot;<I>Filthy scumsuckers like you must be taught a lesson!</I>&quot;

<P>The momentary distraction causes Madwand to realize an old man is not very safe alone in these parts at night. But then he shakes his head in amusement. What matters if he dies by an assassin's blade or by old age this night. The net result is the same.

<P>Still chuckling over that thought, Madwand fails to see the shape that moves behind him, flowing from one shadow to the next as he walks down the road to the port. It isn't until he rounds the corner by the Freeport Inn that a sudden voice brings him to a startled halt.
</FONT>

<TABLE CELLSPACING=0 CELLPADDING=10>
<TR>
<TD WIDTH=180 ALIGN="Left">
<FONT FACE="Times new roman, Arial" SIZE=3>
&quot;<FONT SIZE="+2"><B><I>G</I></B></FONT><I>reetings, old learned one.</I>&quot; whispers someone from the shadow of the porch.<BR><BR>

Madwand quickly mouths an incantation and his eyes suddenly begin to glow a deep violet.
</FONT>
</TD>
<TD WIDTH=200 ALIGN="right"><IMG SRC="../graphics/innoruuk.jpg" WIDTH=200 HEIGHT=300 BORDER=0></TD>
</TR>
</TABLE>

<FONT FACE="Times new roman, Arial" SIZE=3>
<P>&quot;<FONT SIZE="+2"><B><I>W</I></B></FONT><I>ho dares to interrupt my peace this evening?!</I>&quot; he challenges to the twisted and bent creature he can plainly see now that he has cast ultravision. &quot;<I>Be warned, for I am in no mood for conversation this evening! Do not let my age deceive you, I can turn you into a pile of smoking ashes in an instant!</I>&quot; Madwand's staff begins to glow, brighter and brighter as if in warning.

<P>&quot;<I>Peace! I come here with the answer to all your problems! Hear me out at least...</I>&quot; pleads the creature.

<P>&quot;<I>Say on, but be quick about it, for my temper is as short as my time left on this plane. Waste it and you will pay with your life!</I>&quot; growls Madwand.

<P>&quot;<I>I have watched you for a very long time Lawrence.</I>&quot; hisses the as yet unknown being, &quot;<I>I have watched you your whole life in fact. Who do you think it was that left the book in the strong box you unearthed so many decades ago? Do you think a simple farmer would bury something like that in a field? No! It was I! I knew even then that you were not satisfied with digging holes in the ground and harvesting plants. I saw it in you to become the greatest wizard of all ages!</I>&quot;

<P>With each word, Madwand's eyes grow wider and wider. This being is telling him things that none other on this planet know.

<P>&quot;<I>Do you think precious Tunare cared when you renounced her weak guidance and struck out on your own?</I>&quot;, he goes on, &quot;<I>No! She is a weak god, fit only to lead the weak. You saw that and you acted when you discovered my little present that day. I set you on the path that led you here to me today.</I>&quot;

<P>&quot;<I>Who ARE you?!</I>&quot; demands Madwand.

<P>&quot;<I>I am the closest thing to a father you ever had. I made you and I guided you for hundreds of years, step by step down the path of knowledge so that one day you would see the truth! One day you would come serve me in the pursuit of that truth!</I>&quot;

<P>&quot;<I>Power is the only truth! The power to destroy is the only power that matters! If you can destroy something then you have complete power over it! Nothing else can come close! That is my goal! To destroy existence as we know it, thus showing all the other godlings that I am their master!!!</I>&quot;

<P>As he shouts this, the creature swells and ripples, growing in size until he towers over the inn behind him.

<P>&quot;<I>For I am Innoruuk! Avatar of Hate, Father of the Dark, Destroyer of Worlds!!!</I>&quot; Booms the monster, now filling the whole sky above Madwand. 

<P>The God then bends down and puts one black tipped claw directly above Madwand's heart and says in a quieter voice, &quot;<I>Bow down before me Madwand and you will be born again, to pursue you life's quest and to serve me. Refuse me and you shall die this instant.</I>&quot;

<P>Madwand shakes in fear. His power courses through every vein, making him feel a hundred years old again. He could level the walls of this city with the power he is holding right now, but somehow he knows that to unleash it against this God would be instant suicide. What Innoruuk has said echoes over and over in his mind, to live again, to be reborn so that he could continue seeking out knowledge!

<P>Finally, the temptation is too great. Knees shaking with age, Madwand kneels down before the great Innoruuk and says in a simple steady voice, &quot;<I>I will serve you.</I>&quot;

<P>Innoruuk smiles, and then with one fist glowing a dull ugly shade of violet, he touches Madwand on his chest, killing him instantly....

<P>&quot;<I>Awwww, I feel much better now...</I>&quot; grins Innoruuk as he stands back and steps into the black of night.
</FONT>

<TABLE CELLSPACING=0 CELLPADDING=10>
<TR>
<TD WIDTH=200 ALIGN="left"><IMG SRC="../graphics/new_madwand.jpg" WIDTH=200 HEIGHT=350 BORDER=0></TD>
<TD WIDTH=180 ALIGN="left">
<FONT FACE="Times new roman, Arial" SIZE=3>
<FONT SIZE="+2"><B>D</B></FONT>eep under Neriak, a young dark elf awakens to the sound of a ghoul's haunting wail. Startled and a little afraid, he springs up from the ground and reaches inside for his power to blast the offending creature to dust. But when he tries to summon that power he can't!
</FONT>
</TD>
</TR>
</TABLE>

<FONT FACE="Times new roman, Arial" SIZE=3>
<P>&quot;<FONT SIZE="+2"><B><I>W</I></B></FONT><I>hat is this</I>&quot;, he thinks. &quot;<I>Why can't I call lightning down on this miserable creature?</I>&quot;

<P>Worried at what the ghoul might be up to, the dark elf glances outside the room he awoke in, only to see the creature standing guard and looking at him calmly with what could only be called affection in it's small black eyes.

<P>Scratching his head in puzzlement, the elf notices a basin of water on a table in the corner of his small room. Striding over to it, he splashes his face in the cool water. As he lets the water run from his hair he gazes into the bowl. Looking back at him is a stranger's face!

<P>Dark skinned and small boned with delicate features, the person in the bowl is not the one that should be there!

<P>It is then that his memories come flooding back in a torrent!

<P>Staggering, the elf sits down at a table, only now understanding. With shaking fingers, he picks up a piece of parchment that was set on the table so he would notice it and reads the strange text slowly. It was a short message, yet he stares at it, unmoving, for a long, long time.

<P>Finally, with a resolute grunt, the young dark elf stands up, squares his shoulders and strides to the door.

<P>&quot;<I>You there!</I>&quot; he yells at the ghoul outside, &quot;<I>Show me to the Hall of the Dead immediately!</I>&quot;

<P>Moaning in pleasure, the simple creature sets off up a nearby ramp.

<P>Madwand follows.


<P><FONT SIZE="-1"><B>to be continued on Morell-Thule...</B></FONT>
</FONT><BR><BR>
	
</TD>
</TR>
</TABLE>

<TD width="64"></TD>
<TR>
<TD><IMG SRC="../graphics/botc000.jpg" WIDTH=63 HEIGHT=87></TD>
<TD><IMG SRC="../graphics/botc001.jpg" WIDTH=473 HEIGHT=87></TD>
<TD><IMG SRC="../graphics/botc002.jpg" WIDTH=64 HEIGHT=87></TD>
</TR>
</TABLE>
<BR>

<script language="JavaScript">
	<!-- Hide from old browsers
	var random = new Number(Math.floor(9999999 * Math.random())+1);

	// Modify to reflect site specifics
	page = "eqlore.com/";
	target = "@Top1,x02,x05,x08!x02";

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript1.1" SRC="http://oascentral.cybereps.com/RealMedia/ads/adstream_jx.ads/' + page + 1 + random + target + '">');
	document.write('</SCR');
	document.write('IPT>');

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript">');
	document.write('_version=10; //-->');
	document.write('</SCR');
	document.write('IPT>');

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript1.1">');
	document.write('_version=11; //-->');
	document.write('</SCR');
	document.write('IPT>');

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript">');

	if (navigator.appVersion.indexOf('MSIE 3') != -1){
	document.write('<IFRAME MARGINWIDTH=0 MARGINHEIGHT=0 HSPACE=0 VSPACE=0 FRAMEBORDER=0 SCROLLING=no BORDERCOLOR="#000000" SRC="oascentral.cybereps.com/RealMedia/ads/adstream_sx.ads/' + page + random + target + '"></IFRAME>');
	  }
	else if (_version < 11) {
	document.write ('<A HREF="http://oascentral.cybereps.com/RealMedia/ads/click_nx.ads/' + page + random + target + '"><IMG SRC="http://oascentral.cybereps.com/RealMedia/ads/adstream_nx.ads/' + page + random + target + '"></a>');
	  }

	document.write('</SCR');
	document.write('IPT>');

	// End Hide -->
</script><BR>
<BR>
</DIV>

</BODY>
