<!--
                 This page has been created by Renaissance IT
   Renaissance Internet Technologies Copyright (c) 1999 All Rights Reserved.

             for more info on our products, please visit :
                        http://www.renaissance.nl/

	This script has been written by Roy Boverhof <rboverhof@renaissance.nl>
	
        Pagename                : velious_zones.phtml
        Last Updated    		: 02-04-2001
-->

<HTML>
<HEAD>
	<TITLE>the Seekers of Lore : Velious Region</TITLE>
</HEAD>

<BODY BGCOLOR="#000000" TEXT="#000000" LINK="#000000" VLINK="#000000" ALINK="#000000">
<DIV ALIGN="CENTER">
<BR>
<script type="text/javascript"><!--
google_ad_client = "pub-0988179937943699";
google_ad_width = 468;
google_ad_height = 60;
google_ad_format = "468x60_as";
google_ad_channel ="";
google_page_url = document.location;
google_color_border = "FFFFFF";
google_color_bg = "00001F";
google_color_link = "FFFFFF";
google_color_url = "FFF000";
google_color_text = "0000FF";
//--></script>
<script type="text/javascript"
  src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
</script><BR>
<TABLE CELLSPACING = 0 CELLPADDING = 0 BORDER = 0>
<TR>
	<TD width="63"><IMG SRC = "graphics/topc000.jpg" WIDTH = 63 HEIGHT = 87></TD>
	<TD width="473"><IMG SRC = "graphics/topc001.jpg" WIDTH = 473 HEIGHT = 87></TD>
	<TD width="64"><IMG SRC = "graphics/topc002.jpg" WIDTH = 64 HEIGHT = 87></TD>
</TR>
	<TD width="63"></TD>
	<TD BGCOLOR="#BEA279" width="460">
	<DIV ALIGN="CENTER">
	<A HREF="maps.php3"><IMG SRC="graphics/atlasheader.jpg" WIDTH ="150" HEIGHT ="75" BORDER="0"></A>
	<TABLE WIDTH="460">
	<TR><TD>
	<CENTER>
<TABLE BORDER="0">
<TR>
<TD><BR><FONT COLOR="#FFFF00" SIZE="4" FACE="Ariel"><CENTER>Now choose a zone...</CENTER></FONT><BR></TD>
</TR>
<TR>
<TD>
<IMG SRC="graphics/velious_zones.jpg" WIDTH=400 HEIGHT=400 BORDER=0 USEMAP="#velious">
<MAP NAME="velious">
<AREA SHAPE=RECT COORDS="197,88,243,115" HREF="map_search.php3?action=zone&add_zone=Icewell%20Keep">
<AREA SHAPE=RECT COORDS="196,120,242,147" HREF="map_search.php3?action=zone&add_zone=Thurgadin">
<AREA SHAPE=RECT COORDS="333,91,379,118" HREF="antonica_zones.phtml">
<AREA SHAPE=RECT COORDS="195,153,241,180" HREF="map_search.php3?action=zone&add_zone=Great%20Divide">
<AREA SHAPE=RECT COORDS="281,149,327,176" HREF="map_search.php3?action=zone&add_zone=Iceclad%20Ocean">
<AREA SHAPE=RECT COORDS="315,182,361,209" HREF="map_search.php3?action=zone&add_zone=Tower%20of%20Frozen%20Shadow">
<AREA SHAPE=RECT COORDS="236,187,282,214" HREF="map_search.php3?action=zone&add_zone=Eastern%20Wastes">
<AREA SHAPE=RECT COORDS="236,220,282,247" HREF="map_search.php3?action=zone&add_zone=Crystal%20Caverns">
<AREA SHAPE=RECT COORDS="188,204,234,231" HREF="map_search.php3?action=zone&add_zone=Kael%20Drakken">
<AREA SHAPE=RECT COORDS="150,174,196,201" HREF="map_search.php3?action=zone&add_zone=Velketor's%20Labyrinth">
<AREA SHAPE=RECT COORDS="141,213,187,240" HREF="map_search.php3?action=zone&add_zone=Wakening%20lands">
<AREA SHAPE=RECT COORDS="141,247,187,274" HREF="map_search.php3?action=zone&add_zone=Plane%20of%20Growth">
<AREA SHAPE=RECT COORDS="90,160,136,187" HREF="map_search.php3?action=zone&add_zone=Western%20Wastes">
<AREA SHAPE=RECT COORDS="95,197,141,224" HREF="map_search.php3?action=zone&add_zone=Skyshrine">
<AREA SHAPE=RECT COORDS="45,135,91,162" HREF="map_search.php3?action=zone&add_zone=Dragon%20Necropolis">
<AREA SHAPE=RECT COORDS="42,183,88,210" HREF="map_search.php3?action=zone&add_zone=Siren's%20Grotto">
<AREA SHAPE=RECT COORDS="41,213,87,240" HREF="map_search.php3?action=zone&add_zone=Cobalt%20Scar">
</MAP>
</TD>
</TR>
</TABLE>
	</TD></TR>
	</TABLE>
	<TD width="64"></TD>
<TR>
	<TD><IMG SRC = "graphics/botc000.jpg" WIDTH = 63 HEIGHT = 87></TD>
	<TD><IMG SRC = "graphics/botc001.jpg" WIDTH = 473 HEIGHT = 87></TD>
	<TD><IMG SRC = "graphics/botc002.jpg" WIDTH = 64 HEIGHT = 87></TD>
</TR>
</TABLE>
<BR>
<IMG SRC="http://service.bfast.com/bfast/serve?bfmid=1375281&siteid=40292692&bfpage=pc" BORDER="0" WIDTH="1" HEIGHT="1" NOSAVE ><A HREF="http://service.bfast.com/bfast/click?bfmid=1375281&siteid=40292692&bfpage=pc" TARGET="_new"><IMG SRC="http://affiliate.gamestop.com/affIMG/pc_120x60.gif" BORDER="0" WIDTH="120" HEIGHT="60" ALT="PC Games at GameStop.com"></A>
<BR>
<BR>
</DIV>
</BODY>
</HTML>