<!--
                 This page has been created by Renaissance IT
   Renaissance Internet Technologies Copyright (c) 1999 All Rights Reserved.

             for more info on our products, please visit :
                        http://www.renaissance.nl/

	This script has been written by Roy Boverhof <rboverhof@renaissance.nl>
	
        Pagename                : spider_room_poem.html
        Last Updated    		: 03-28-2000
-->

<HTML>
<HEAD>
	<TITLE>the Seekers of Lore : The Spider Room Incident</TITLE>
</HEAD>

<BODY BGCOLOR="#000000" TEXT="#000000" LINK="#000000" VLINK="#000000" ALINK="#000000">
<DIV ALIGN="CENTER">
<BR>
<!-- FGB Banner Code -->
<SCRIPT LANGUAGE="JavaScript">
   <!-- Hide from old browsers
   now = new Date();
   random = now.getTime();
     
   // Modify to reflect site specifics
   site = "http://ds.cybereps.com";
   target = "/SITE=FGN/AREA=EQLORE/AAMSZ=BANNER";
   
   document.write('<IFRAME SRC="' + site + '/hserver/acc_random=' + random + target + '"');
   document.write(' NORESIZE SCROLLING=NO HSPACE=0 VSPACE=0 FRAMEBORDER=0 MARGINHEIGHT=0 MARGINWIDTH=0 WIDTH=468 HEIGHT=60>');
   
   document.write('<SCR');
   document.write('IPT SRC="' + site + '/jnserver/acc_random=' + random + target + '">');
   document.write('</SCR');
   document.write('IPT>');
   
   document.write('</IFRAME>');
   // End Hide -->
 </SCRIPT>
 <NOSCRIPT> 
   <A HREF="http://ds.cybereps.com/accipiter/adclick/SITE=FGN/AREA=EQLORE/AAMSZ=BANNER">
   <IMG SRC="http://ds.cybereps.com/accipiter/nserver/SITE=FGN/AREA=EQLORE/AAMSZ=BANNER" border="0"></A>
 </NOSCRIPT>
<!-- END FGB Banner Code --><BR>
<TABLE CELLSPACING = 0 CELLPADDING = 0 BORDER = 0>
<TR>
	<TD width="63"><IMG SRC = "../graphics/topc000.jpg" WIDTH = 63 HEIGHT = 87></TD>
	<TD width="473"><IMG SRC = "../graphics/topc001.jpg" WIDTH = 473 HEIGHT = 87></TD>
	<TD width="64"><IMG SRC = "../graphics/topc002.jpg" WIDTH = 64 HEIGHT = 87></TD>
</TR>
	<TD width="63"></TD>
	<TD BGCOLOR="#BEA279" width="460">
	<DIV ALIGN="CENTER">
	<TABLE>
	<TR>

	<TD BGCOLOR="#BEA279" width="400">

<CENTER>
<FONT FACE="Times New Roman" SIZE="+2">
<BR><B><I>The Spider Room Incident...</I></B></FONT><BR><BR>
<FONT SIZE="-1">-----------------</FONT>
</CENTER><BR>
	
<DIV ALIGN="center">
<FONT Size="-1">
I stun and burn, watch them fall<BR>
My men all rally to my call<BR><BR>

Spiders, gargoyles, frogs go down<BR>
King of undead, I wear my crown<BR><BR>

Bloody battle aftermath<BR>
I could use a nice warm bath<BR><BR>

Though no time to stop and think<BR>
Once again death is on the brink<BR><BR>

Another pull and mana is low<BR>
Convince the group, take it slow<BR><BR>

We finish up and sit to heal<BR>
We drink our ale and shine our steel<BR><BR>

But look we up, a passer-by<BR>
In out midst he stopped and sighed<BR><BR>

"help" he said with his last breath<BR>
Then he fell consumed by death<BR><BR>

Around the corner came a fury<BR>
Minotaurs and icebones scurried<BR><BR>

One by two they filled the room<BR>
Seemed we were to share this strangers doom<BR><BR>

"Assist", "Assist", "Assist" I say<BR>
Yet at my feet a brother lay<BR><BR>

The wave of enemies proved to much<BR>
Our band can not remain as such<BR><BR>

The druid called the powers that be<BR>
The god of ocean, land, and tree<BR><BR>

Through the flames appears a mystic gate<BR>
We step on through escaping fate<BR><BR>

Across the world we did soar<BR>
Where once stood six, now stand four<BR><BR>
</DIV>
</FONT>

<DIV ALIGN="center">
-----------------<BR>
<P><FONT SIZE="+1"><I>Cendan Tankenpriest </I></FONT><BR>
<FONT FACE="Verdana" Size="-2">40th Level Cleric of the Sylvan Guard</FONT><BR>
<FONT FACE="Verdana" Size="-2"><B>Erollisi Marr</B></FONT><BR><BR>
</DIV>


	</TD>
	</TR>
	</TABLE>
<TABLE>
<TR>
<TD><A HREF="http://www.loreseekers.com/tales.phtml"><IMG SRC="http://www.loreseekers.com/graphics/tales_return_link.jpg" WIDTH=200 HEIGHT=75 ALT="Read some other stories by our members!" BORDER="0"></A></TD>
</TR>
</TABLE>

	<TD width="64"></TD>
<TR>
	<TD><IMG SRC = "../graphics/botc000.jpg" WIDTH = 63 HEIGHT = 87></TD>
	<TD><IMG SRC = "../graphics/botc001.jpg" WIDTH = 473 HEIGHT = 87></TD>
	<TD><IMG SRC = "../graphics/botc002.jpg" WIDTH = 64 HEIGHT = 87></TD>
</TR>
</TABLE>
<BR>
 <SCRIPT LANGUAGE="JavaScript">
   <!-- Hide from old browsers
   now = new Date();
   random = now.getTime();
   
   // Modify to reflect site specifics
   site = "http://ds.cybereps.com";
   target = "/SITE=FGN/AREA=EQLORE/AAMSZ=BOX";
   
   document.write('<IFRAME SRC="' + site + '/hserver/acc_random=' + random + target + '"');
   document.write(' NORESIZE SCROLLING=NO HSPACE=0 VSPACE=0 FRAMEBORDER=0 MARGINHEIGHT=0 MARGINWIDTH=0 WIDTH=125 HEIGHT=125>');
      
   document.write('<SCR');
   document.write('IPT SRC="' + site + '/jnserver/acc_random=' + random + target + '">');
   document.write('</SCR');
   document.write('IPT>');
   
   document.write('</IFRAME>');
   // End Hide -->
 </SCRIPT>
 <NOSCRIPT> 
   <A HREF="http://ds.cybereps.com/accipiter/adclick/SITE=FGN/AREA=EQLORE/AAMSZ=BOX">
   <IMG SRC="http://ds.cybereps.com/accipiter/nserver/SITE=FGN/AREA=EQLORE/AAMSZ=BOX" border="0"></A>
 </NOSCRIPT>
<BR>
<BR>
</DIV>
</BODY>
</HTML>