<!--
                 This page has been created by Renaissance IT
   Renaissance Internet Technologies Copyright (c) 1999 All Rights Reserved.

             for more info on our products, please visit :
                        http://www.renaissance.nl/

	This script has been written by Roy Boverhof <rboverhof@renaissance.nl>
	
        Pagename                : freeport_zones.html
        Last Updated    		: 05-02-2000
-->

<HTML>
<HEAD>
	<TITLE>the Seekers of Lore : Freeport Region</TITLE>
</HEAD>

<BODY BGCOLOR="#000000" TEXT="#000000" LINK="#000000" VLINK="#000000" ALINK="#000000">
<DIV ALIGN="CENTER">
<BR>
<script type="text/javascript"><!--
google_ad_client = "pub-0988179937943699";
google_ad_width = 468;
google_ad_height = 60;
google_ad_format = "468x60_as";
google_ad_channel ="7352298734";
google_page_url = document.location;
google_color_border = "FFFFFF";
google_color_bg = "00001F";
google_color_link = "FFFFFF";
google_color_url = "FFF000";
google_color_text = "0000FF";
//--></script>
<script type="text/javascript"
  src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
</script><BR>
<TABLE CELLSPACING = 0 CELLPADDING = 0 BORDER = 0>
<TR>
	<TD width="63"><IMG SRC = "graphics/topc000.jpg" WIDTH = 63 HEIGHT = 87></TD>
	<TD width="473"><IMG SRC = "graphics/topc001.jpg" WIDTH = 473 HEIGHT = 87></TD>
	<TD width="64"><IMG SRC = "graphics/topc002.jpg" WIDTH = 64 HEIGHT = 87></TD>
</TR>
	<TD width="63"></TD>
	<TD BGCOLOR="#BEA279" width="460">
	<DIV ALIGN="CENTER">
	<A HREF="maps.php3"><IMG SRC="graphics/atlasheader.jpg" WIDTH ="150" HEIGHT ="75" BORDER="0"></A>
	<TABLE WIDTH="460">
	<TR><TD>
	<CENTER>
<TABLE BORDER="0">
<TR>
<TD><BR><FONT COLOR="#FFFF00" SIZE="4" FACE="Ariel"><CENTER>Now choose a zone...</CENTER></FONT><BR></TD>
</TR>
<TR>
<TD>
<IMG SRC="graphics/freeport_zones.jpg" WIDTH=400 HEIGHT=400 BORDER=0 USEMAP="#freeport">
<MAP NAME="freeport">
<AREA SHAPE=POLY COORDS="187,60,176,76,197,76,187,60" HREF="neriak_zones.phtml" ALT="To Neriak Region">
<AREA SHAPE=POLY COORDS="186,350,207,350,195,368,186,350" HREF="grobb_zones.phtml" ALT="To Grobb Region">
<AREA SHAPE=POLY COORDS="2,202,16,192,16,213,2,202" HREF="rivervale_zones.phtml" ALT="To Rivervale Region">
<AREA SHAPE=RECT COORDS="230,137,309,174" HREF="map_search.php3?action=zone&add_zone=Freeport%20North">
<AREA SHAPE=RECT COORDS="328,131,391,162" HREF="map_search.php3?action=zone&add_zone=Other">
<AREA SHAPE=RECT COORDS="317,182,395,222" HREF="map_search.php3?action=zone&add_zone=Freeport%20East">
<AREA SHAPE=RECT COORDS="230,182,307,222" HREF="map_search.php3?action=zone&add_zone=Freeport%20West">
<AREA SHAPE=RECT COORDS="320,254,394,296" HREF="map_search.php3?action=zone&add_zone=Ocean%20of%20Tears">
<AREA SHAPE=RECT COORDS="230,255,312,309" HREF="map_search.php3?action=zone&add_zone=Northern%20Desert%20of%20Ro">
<AREA SHAPE=RECT COORDS="127,182,216,222" HREF="map_search.php3?action=zone&add_zone=East%20Commonlands">
<AREA SHAPE=RECT COORDS="25,182,116,223" HREF="map_search.php3?action=zone&add_zone=West%20Commonlands">
<AREA SHAPE=RECT COORDS="25,247,115,267" HREF="map_search.php3?action=zone&add_zone=Befallen">
</MAP>
</TD>
</TR>
</TABLE>
	</TD></TR>
	</TABLE>
	<TD width="64"></TD>
<TR>
	<TD><IMG SRC = "graphics/botc000.jpg" WIDTH = 63 HEIGHT = 87></TD>
	<TD><IMG SRC = "graphics/botc001.jpg" WIDTH = 473 HEIGHT = 87></TD>
	<TD><IMG SRC = "graphics/botc002.jpg" WIDTH = 64 HEIGHT = 87></TD>
</TR>
</TABLE>
<BR>
<IMG SRC="http://service.bfast.com/bfast/serve?bfmid=1375281&siteid=40292692&bfpage=pc" BORDER="0" WIDTH="1" HEIGHT="1" NOSAVE ><A HREF="http://service.bfast.com/bfast/click?bfmid=1375281&siteid=40292692&bfpage=pc" TARGET="_new"><IMG SRC="http://affiliate.gamestop.com/affIMG/pc_120x60.gif" BORDER="0" WIDTH="120" HEIGHT="60" ALT="PC Games at GameStop.com"></A>
<BR>
<BR>
</DIV>
</BODY>
</HTML>