<!-- comment check: ok -->
<HTML>
<HEAD>
<TITLE>Welcome to Media and Games Online Network - MGON</TITLE>
<META name="description" content="MGON - The Gamer's Choice for gaming news. Get the hottest info from the gaming industry.
.">
<META name="keywords" content="MGON, MGO, Interviews, Game previews, Game downloads, Gaming Network, Articles, Gaming News, News, Multiplayer, Games, PC Games, Console Games, Reviews, Forum, MGON International AB, Action, Strategy, Simulation, Roleplay, Racing">
<META name="robots" content="index,follow">
<link rel="stylesheet" href="/newstyle.css" type="text/css">
<STYLE type="text/css">
<!--
-->
</STYLE>
<script language="JavaScript" type="text/javascript">
<!--
function go(where) {
  if(where != "void" && where!="") location.href = where;
}

function reply(tid,pid,cid,lang) {

  url = "/reply.phtml?tid=" + tid + "&pid=" + pid + "&id=" + cid + "&language=" + lang + '&ref=%2Fnews.phtml';
  ipwindow = open("","prewindow","scrollbars=yes,toolbar=no,height=400,width=400");
  ipwindow.location.href = url;
        
}

function rateit(id,vote) {
    if(vote != "") {
		document.rate.content_id.value = id;
		document.rate.vote.value = vote;
		document.rate.submit();
	}
}

function screenshot(cid,pid) {

  url = "/screenshot.phtml?cid=" + cid + "&pid=" + pid;
  ipwindow = open("","prewindow","scrollbars=yes,toolbar=no,height=630,width=710");
  ipwindow.location.href = url;
        
}

function relatedmedia(url) {

  ipwindow = open("","prewindow","scrollbars=yes,toolbar=no,height=300,width=300");
  ipwindow.location.href = url;
        
}
function MM_preloadImages() { //v3.0
  var d=document; if(d.images){ if(!d.MM_p) d.MM_p=new Array();
    var i,j=d.MM_p.length,a=MM_preloadImages.arguments; for(i=0; i<a.length; i++)
    if (a[i].indexOf("#")!=0){ d.MM_p[j]=new Image; d.MM_p[j++].src=a[i];}}
}
function MM_findObj(n, d) { //v4.0
  var p,i,x;  if(!d) d=document; if((p=n.indexOf("?"))>0&&parent.frames.length) {
    d=parent.frames[n.substring(p+1)].document; n=n.substring(0,p);}
  if(!(x=d[n])&&d.all) x=d.all[n]; for (i=0;!x&&i<d.forms.length;i++) x=d.forms[i][n];
  for(i=0;!x&&d.layers&&i<d.layers.length;i++) x=MM_findObj(n,d.layers[i].document);
  if(!x && document.getElementById) x=document.getElementById(n); return x;
}
function MM_swapImgRestore() { //v3.0
  var i,x,a=document.MM_sr; for(i=0;a&&i<a.length&&(x=a[i])&&x.oSrc;i++) x.src=x.oSrc;
}
function MM_swapImage() { //v3.0
  var i,j=0,x,a=MM_swapImage.arguments; document.MM_sr=new Array; for(i=0;i<(a.length-2);i+=3)
   if ((x=MM_findObj(a[i]))!=null){document.MM_sr[j++]=x; if(!x.oSrc) x.oSrc=x.src; x.src=a[i+2];}
}

function getWall(id,name) {
  url = "/getwall.phtml?thisid=" + id + "&thisname=" + name;
  ipwindow = open("","prewindow","fullscreen=no,resizable=yes,scrollbars=yes,toolbar=yes,height=600,width=800");
  ipwindow.location.href = url;
}

function getFile(id,name) {
  url = "/common/getfile.phtml?thisid=" + id + "&thisname=" + name;
  ipwindow = open("","prewindow","scrollbars=no,toolbar=no,height=200,width=495");
  ipwindow.location.href = url;
}
function localDate(dateStr) {
  now = new Date();
  var ar1 = now.toString().split(" ");
  var addH = -100;
  var addM = -100;
  var gmt = new Array(new Array());
  gmt["PST"] = -8;
  gmt["MST"] = -7;
  gmt["CST"] = -6;
  gmt["EST"] = -5;
  gmt["UTC"] = 0;
  if(ar1[4].indexOf("+") != -1) {
    var gm = ar1[4].split("+");
    gm[2] = 0-gm[1].substr(0,2);
    addH = Number(gm[2]);
    gm[2] = 0-gm[1].substr(2,2);
    addM = Number(gm[2]);
  }
  if(ar1[4].indexOf("-") != -1) {
    var gm = ar1[4].split("-");
    gm[2] = gm[1].substr(0,2);
    addH = Number(gm[2]);
    gm[2] = gm[1].substr(2,2);
    addM = Number(gm[2]);
  }
  if(addH == -100) {
    addH = gmt[ar1[4]];
    addM = 0;
  }
  there = new Date(dateStr);
  nowP = Date.parse(there);
  if(addH > 0) nowP -= 3600000;
  nowP += Number(addH)*3600000;
  nowP += Number(addM)*60000;
  realD = new Date(nowP);
  real = realD.toLocaleString();
  //  document.write(real[0] + " " + real[1] + " " + real[2] + " " +real[3]);
  document.write(real);
}
//-->
</script>
 
</HEAD>

<body bgcolor="#000000" text="#EEEEEE" link="#FFFFFF" vlink="#FFFFFF" alink="#FFFFFF" background="/newimages/backgrounds/bluelines.gif" leftmargin="0" topmargin="0" marginwidth="0" marginheight="0" onLoad="MM_preloadImages('/newimages/misc/arrow_on.gif')">

<table width="772" border="0" align="center" cellpadding="1" cellspacing="0" bgcolor="#000000">

  <tr>

    <td align="center"><!-- Webserver: w24 --><!-- loginUrl: http://everquest.mgon.com/common/loginNew.phtml?ref=www.mgon.com&page=/news.phtml !--><!-- loginUrl: http://everquest.mgon.com/common/members.phtml?ref=www.mgon.com&page=/news.phtml !--><script language="JavaScript">
<!--
function MM_openBrWindow(theURL,winName,features) { //v2.0
  window.open(theURL,winName,features);  
}
function login() {
  window.open('http://everquest.mgon.com/common/loginNew.phtml?ref=www.mgon.com&page=/news.phtml', 'Login', 'width=250,height=250,scrollbars=yes'); 
}
function member() {
  window.open('http://everquest.mgon.com/common/members.phtml?ref=www.mgon.com&page=/news.phtml', 'Member', 'width=500,height=600,scrollbars=yes'); 
}
//-->
</script>
<!-- Place the following code where you want an ad to appear -->
<SCRIPT LANGUAGE="JavaScript" SRC="http://ads.ad-flow.com/?DC=mgon-pop&JS=Y"></SCRIPT>
<NOSCRIPT>
<A HREF="http://ads.ad-flow.com/?SHT=mgon-pop"><IMG SRC="http://ads.ad-flow.com/?SIT=mgon-pop"></A>
</NOSCRIPT>
<table width="100%" border="0" cellspacing="0" cellpadding="0" background="/common/images/topplate/resize.gif">
  <tr> 
    <td> 
      <table width="488" border="0" cellspacing="0" cellpadding="0" background="/common/images/topplate/resize.gif">
				<tr> 
          <td><img src="/common/images/topplate/metalcorner.gif" width="5" height="20"></td>
				          <td><a href="javascript:login();"><img src="/common/images/topplate/memberlogin.gif" width="80" height="20" border="0"></a></td>					
			            <td><img src="/common/images/topplate/arrow.gif" width="10" height="20"></td>
          <td><img src="/common/images/topplate/metalcolumn.gif" width="3" height="20"></td>
          <td><a href="javascript:;" onClick="MM_openBrWindow('/common/sitemap.html','navigation','width=540,height=450')"><img src="/common/images/topplate/pc.gif" width="23" height="20" border="0"></a></td>
          <td><img src="/common/images/topplate/metalcolumn.gif" width="3" height="20"></td>
          <td><a href="javascript:;" onClick="MM_openBrWindow('/common/sitemap.html','navigation','width=540,height=450')"><img src="/common/images/topplate/action.gif" width="47" height="20" border="0"></a></td>
          <td><img src="/common/images/topplate/metalcolumn.gif" width="3" height="20"></td>
          <td><a href="javascript:;" onClick="MM_openBrWindow('/common/sitemap.html','navigation','width=540,height=450')"><img src="/common/images/topplate/roleplay.gif" width="62" height="20" border="0"></a></td>
          <td><img src="/common/images/topplate/metalcolumn.gif" width="3" height="20"></td>
          <td><a href="javascript:;" onClick="MM_openBrWindow('/common/sitemap.html','navigation','width=540,height=450')"><img src="/common/images/topplate/simulation.gif" width="70" height="20" border="0"></a></td>
          <td><img src="/common/images/topplate/metalcolumn.gif" width="3" height="20"></td>
          <td><a href="javascript:;" onClick="MM_openBrWindow('/common/sitemap.html','navigation','width=540,height=450')"><img src="/common/images/topplate/console.gif" width="56" height="20" border="0"></a></td>
          <td><img src="/common/images/topplate/metalcolumn.gif" width="3" height="20"></td>
          <td><a href="javascript:;" onClick="MM_openBrWindow('/common/sitemap.html','navigation','width=540,height=450')"><img src="/common/images/topplate/strategy.gif" width="64" height="20" border="0"></a></td>
          <td><img src="/common/images/topplate/metalcolumn.gif" width="3" height="20"></td>
          <td><a href="javascript:;" onClick="MM_openBrWindow('/common/sitemap.html','navigation','width=540,height=450')"><img src="/common/images/topplate/racing.gif" width="47" height="20" border="0"></a></td>
          <td><img src="/common/images/topplate/metalcolumn.gif" width="3" height="20"></td>
        </tr>
      </table>
    </td>
    <td background="/common/images/topplate/resize.gif" width="100%"><img src="/common/images/topplate/resize.gif" width="100%" height="20"></td>
    <td>
      <table width="88" border="0" cellspacing="0" cellpadding="0" background="/common/images/topplate/resize.gif">
        <tr>
          <td><img src="/common/images/topplate/metalcolumn.gif" width="3" height="20"></td>
          <td><a href="javascript:;" onClick="MM_openBrWindow('/common/sitemap.html','navigation','width=540,height=450')"><img src="/common/images/topplate/mgonetwork.gif" width="82" height="20" border="0"></a></td>
          <td><img src="/common/images/topplate/metalcorner.gif" width="5" height="20"></td>
        </tr>
      </table>
    </td>
  </tr>
</table>
<table width="100%" border="0" cellspacing="0" cellpadding="0" bgcolor="#000000">
  <tr> 
    <td><img src="http://193.45.143.23/1_1pix.gif?996802332" width="1" height="1" nosave></td>
  </tr>
</table>
</td>

  </tr>

</table>

<table width="772" border="0" cellspacing="0" cellpadding="0" align="center">

  <tr> 

    <td>

<TABLE width="772" border="0" cellspacing="0" cellpadding="0">

  <TR> 

    <TD><IMG src="/newimages/top/topleft.gif" width="592" height="81" border="0" usemap="#Map"><MAP name="Map"><AREA shape="rect" coords="13,36,138,76" href="http://www.mgon.com" alt="MGON Home" title="MGON Home"></MAP></TD>

    <TD width="100%" background="/newimages/top/resize.gif"><IMG src="/newimages/top/resize.gif" width="1" height="81"></TD>

    <TD><IMG src="/newimages/top/topright.gif" width="157" height="81"></TD>

  </TR>

</TABLE>


<TABLE width="750" border="0" cellspacing="0" cellpadding="0" bgcolor="#000000">
	<TR> 
		<TD align="center" width="130"> 
			<TABLE width="100%" border="0" cellspacing="0" cellpadding="0">
				<TR> 
					<TD align="center" background="/images2/top/channelresize.gif"><OBJECT classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=4,0,2,0" width="120" height="60">
							<param name=movie value="http://www.mgon.com/flashmovies/mgochannel3.swf">
							<PARAM name=quality value=high>
							<PARAM name="menu" value="false">
							<embed src="http://www.mgon.com/flashmovies/mgochannel3.swf" quality=high pluginspage="http://www.macromedia.com/shockwave/download/index.cgi?P1_Prod_Version=ShockwaveFlash" 
type="application/x-shockwave-flash" menu="false" width="120" height="60">
							</EMBED> 
						</OBJECT></TD>
				</TR>
				<TR> 
					<TD><IMG src="/images/top/channelbottom.gif" width="130" height="13"></TD>
				</TR>
			</TABLE>
		</TD>
		
    <TD align="center" width="490" valign="top"> 
      <!--Ad 468x60-->      <span class="smalltext"><NOLAYER><IFRAME SRC="http://ad.se.doubleclick.net/adi/mgon.com/;sz=468x60;ord=996802332?" bgcolor="#000000" width="468" height="60" frameborder="no" border="0" MARGINWIDTH="0" MARGINHEIGHT="0" SCROLLING="no"><A HREF="http://ad.se.doubleclick.net/jump/mgon.com/;abr=!ie;sz=468x60;ord=996802332?"><IMG SRC="http://ad.se.doubleclick.net/ad/mgon.com/;abr=!ie;sz=468x60;ord=996802332?" border="0" height="60" width="468"></A></IFRAME></NOLAYER><ILAYER id="layer1" visibility="hidden" width="468" height="60" align="center"></ILAYER></span><!--/Ad 468x60-->    </TD>
		
    <TD width="130" align="center" valign="top">
</TD>
	</TR>
</TABLE>
</td></tr></table>
 
<table width="772" border="0" cellspacing="0" cellpadding="0" align="center" background="/newimages/misc/50x50pix.gif">
  <tr>
    <td width="130" background="/newimages/resizes/leftnav.gif" valign="top"> 
      <img src="/newimages/columns/sitecontent.gif" width="130" height="24"><br> 
<table width="130" border="0" cellspacing="0" cellpadding="0" bgcolor="#000000" background="/newimages/misc/50x50pix.gif">
  <tr bgcolor="#000000"> 
    <td> 
      <table width="100%" border=0 cellpadding=0 cellspacing=1>
        <tr bgcolor="#18355C"> 
          <td style="border='1 #18355C'" onMouseOver="style.backgroundColor='#FFFFFF'; style.cursor='hand'; style.border='1 #18355C'" onMouseOut="style.backgroundColor='#719FC6'; style.border='1 #18355C';" height="21" bgcolor="#719FC6"> 
            <table width="100%" border="0" cellspacing="0" cellpadding="0">
              <tr> 
                <td class="Bolded"><img src="/newimages/misc/navarrow.gif" width="12" height="21"></td>
                <td bgcolor="#18355C" height="21" width="100%"><a href="/" class="bluelinks" style="margin:0;">
<div><img src="/newimages/misc/1pix.gif" width="5" height="1" border="0">Home</div>
                  </a></td>
              </tr>
            </table>
          </td>
        </tr>
        <tr bgcolor="#18355C"> 
          <td style="border='1 #18355C'" onMouseOver="style.backgroundColor='#FFFFFF'; style.cursor='hand'; style.border='1 #18355C'" onMouseOut="style.backgroundColor='#719FC6'; style.border='1 #18355C';" height="21" bgcolor="#719FC6"> 
            <table width="100%" border="0" cellspacing="0" cellpadding="0">
              <tr> 
                <td class="Bolded"><img src="/newimages/misc/navarrow.gif" width="12" height="21"></td>
                <td bgcolor="#18355C" height="21" width="100%"><a href="/news.phtml" class="bluelinks" style="margin:0;"><div><img src="/newimages/misc/1pix.gif" width="5" height="1" border="0">News</div></a></td>
              </tr>
            </table>
          </td>
        </tr>
        <tr bgcolor="#18355C"> 
          <td style="border='1 #18355C'" onMouseOver="style.backgroundColor='#FFFFFF'; style.cursor='hand'; style.border='1 #18355C'" onMouseOut="style.backgroundColor='#719FC6'; style.border='1 #18355C';" height="21" bgcolor="#719FC6"> 
            <table width="100%" border="0" cellspacing="0" cellpadding="0">
              <tr> 
                <td class="Bolded"><img src="/newimages/misc/navarrow.gif" width="12" height="21"></td>
                <td bgcolor="#18355C" height="21" width="100%"><a href="/reviewindex.phtml" class="bluelinks" style="margin:0;">
<div><img src="/newimages/misc/1pix.gif" width="5" height="1" border="0">Reviews</div></a></td>
              </tr>
            </table>
          </td>
        </tr>
        <tr bgcolor="#18355C"> 
          <td style="border='1 #18355C'" onMouseOver="style.backgroundColor='#FFFFFF'; style.cursor='hand'; style.border='1 #18355C'" onMouseOut="style.backgroundColor='#719FC6'; style.border='1 #18355C';" height="21" bgcolor="#719FC6"> 
            <table width="100%" border="0" cellspacing="0" cellpadding="0">
              <tr> 
                <td class="Bolded"><img src="/newimages/misc/navarrow.gif" width="12" height="21"></td>
                <td bgcolor="#18355C" height="21" width="100%"><a href="/previewindex.phtml" class="bluelinks" style="margin:0;">
<div><img src="/newimages/misc/1pix.gif" width="5" height="1" border="0">Previews</div></a></td>
              </tr>
            </table>
          </td>
        </tr>
        <tr bgcolor="#18355C"> 
          <td style="border='1 #18355C'" onMouseOver="style.backgroundColor='#FFFFFF'; style.cursor='hand'; style.border='1 #18355C'" onMouseOut="style.backgroundColor='#719FC6'; style.border='1 #18355C';" height="21" bgcolor="#719FC6"> 
            <table width="100%" border="0" cellspacing="0" cellpadding="0">
              <tr> 
                <td class="Bolded"><img src="/newimages/misc/navarrow.gif" width="12" height="21"></td>
                <td bgcolor="#18355C" height="21" width="100%"><a href="/interviewindex.phtml" class="bluelinks" style="margin:0;">
<div><img src="/newimages/misc/1pix.gif" width="5" height="1" border="0">Interviews</div></a></td>
              </tr>
            </table>
          </td>
        </tr>
        <tr bgcolor="#18355C"> 
          <td style="border='1 #18355C'" onMouseOver="style.backgroundColor='#FFFFFF'; style.cursor='hand'; style.border='1 #18355C'" onMouseOut="style.backgroundColor='#719FC6'; style.border='1 #18355C';" height="21" bgcolor="#719FC6"> 
            <table width="100%" border="0" cellspacing="0" cellpadding="0">
              <tr> 
                <td class="Bolded"><img src="/newimages/misc/navarrow.gif" width="12" height="21"></td>
                <td bgcolor="#18355C" height="21" width="100%"><a href="/articleindex.phtml" class="bluelinks" style="margin:0;">
<div><img src="/newimages/misc/1pix.gif" width="5" height="1" border="0">Articles</div></a></td>
              </tr>
            </table>
          </td>
        </tr>
        <tr bgcolor="#18355C"> 
          <td style="border='1 #18355C'" onMouseOver="style.backgroundColor='#FFFFFF'; style.cursor='hand'; style.border='1 #18355C'" onMouseOut="style.backgroundColor='#719FC6'; style.border='1 #18355C';" height="21" bgcolor="#719FC6"> 
            <table width="100%" border="0" cellspacing="0" cellpadding="0">
              <tr> 
                <td class="Bolded"><img src="/newimages/misc/navarrow.gif" width="12" height="21"></td>
                <td bgcolor="#18355C" height="21" width="100%"><a href="/hardwareindex.phtml" class="bluelinks" style="margin:0;"> 
                  <div><img src="/newimages/misc/1pix.gif" width="5" height="1" border="0">Hardware</div>
                  </a></td>
              </tr>
            </table>
          </td>
        </tr>
        <tr bgcolor="#18355C"> 
          <td style="border='1 #18355C'" onMouseOver="style.backgroundColor='#FFFFFF'; style.cursor='hand'; style.border='1 #18355C'" onMouseOut="style.backgroundColor='#719FC6'; style.border='1 #18355C';" height="21" bgcolor="#719FC6"> 
            <table width="100%" border="0" cellspacing="0" cellpadding="0">
              <tr> 
                <td class="Bolded"><img src="/newimages/misc/navarrow.gif" width="12" height="21"></td>
                <td bgcolor="#18355C" height="21" width="100%"><a href="/fileindex.phtml" class="bluelinks" style="margin:0;"> 
                  <div><img src="/newimages/misc/1pix.gif" width="5" height="1" border="0">Downloads</div></a></td>
              </tr>
            </table>
          </td>
        </tr>
        <tr bgcolor="#18355C"> 
          <td style="border='1 #18355C'" onMouseOver="style.backgroundColor='#FFFFFF'; style.cursor='hand'; style.border='1 #18355C'" onMouseOut="style.backgroundColor='#719FC6'; style.border='1 #18355C';" height="21" bgcolor="#719FC6"> 
            <table width="100%" border="0" cellspacing="0" cellpadding="0">
              <tr> 
                <td class="Bolded"><img src="/newimages/misc/navarrow.gif" width="12" height="21"></td>
                <td bgcolor="#18355C" height="21" width="100%"><a href="http://www.mgoforum.com" class="bluelinks" style="margin:0;">
<div><img src="/newimages/misc/1pix.gif" width="5" height="1" border="0">MGOforums</div></a></td>
              </tr>
            </table>
          </td>
        </tr>
        <tr bgcolor="#18355C"> 
          <td style="border='1 #18355C'" onMouseOver="style.backgroundColor='#FFFFFF'; style.cursor='hand'; style.border='1 #18355C'" onMouseOut="style.backgroundColor='#719FC6'; style.border='1 #18355C';" height="21" bgcolor="#719FC6"> 
            <table width="100%" border="0" cellspacing="0" cellpadding="0">
              <tr> 
                <td class="Bolded"><img src="/newimages/misc/navarrow.gif" width="12" height="21"></td>
                <td bgcolor="#18355C" height="21" width="100%"><a href="http://www.mgoshop.com" class="bluelinks" style="margin:0;">
<div><img src="/newimages/misc/1pix.gif" width="5" height="1" border="0">MGOshop</div></a></td>
              </tr>
            </table>
          </td>
        </tr>
      </table>
    </td>
  </tr>
</table>
<table width="128" border="0" cellspacing="0" cellpadding="0" bgcolor="#000000">
  <tr> 
    <td> 
      <table width="100%" border="0" cellspacing="0" cellpadding="0" background="http://www.mgon.com/images/webtop_blue/websearch_bg.gif" align="center">
        <form name="MGON" action="http://www.mgon.com/search/search.phtml" method="get">
          <input type="hidden" name="INCLUDE" value="results">
          <tr> 
            <td> 
              <table width="100%" border="0" cellspacing="0" cellpadding="0" background="http://www.mgon.com/images/misc/50x50pix.gif">
                <tr> 
                  <td colspan="2"><img src="http://www.mgon.com/images/webtop_blue/finalsearch_01.gif" width="128" height="25"></td>
                </tr>
                <tr> 
                  <td align="center" colspan="2"> 
                    <input type="text" name="QUERY" style='WIDTH: 110; HEIGHT: 17; FONT-FAMILY: arial,helvetica; font-size:10px;' maxlength="50" size="13">
                  </td>
                </tr>
                <tr> 
                  <td><img src="http://www.mgon.com/images/webtop_blue/zone.gif" width="39" height="15"></td>
                  <td> 
                    <select name="ZONE" style='WIDTH: 75; HEIGHT: 15; FONT-FAMILY: arial,helvetica; font-size:10px;'>
                      <option value="mgon" selected>MGON</option>
                      <option value="web">Web</option>
                      <option value="games">Games</option>
                    </select>
                  </td>
                </tr>
              </table>
              <table width="100%" border="0" cellspacing="0" cellpadding="0">
                <tr> 
                  <td><input type="image" border="0" name="Search" src="http://www.mgon.com/images/webtop_blue/search.gif" width="75" height="22" alt="Search" align="top"></td>
                  <td><a href="http://www.mgon.com/search/search.phtml?INCLUDE=help"><img src="http://www.mgon.com/images/webtop_blue/help.gif" width="53" height="22" border="0" alt="Help"></a></td>
                </tr>
                <tr> 
                  <td colspan="2"><a href="http://www.mgon.com/search/powersearch.phtml"><img src="http://www.mgon.com/images/webtop_blue/powersearch.gif" width="128" height="20" border="0" alt="Power Search"></a></td>
                </tr>
                <tr> 
                  <td colspan="2"><a href="/search/download.phtml"><img src="http://www.mgon.com/images/webtop_blue/download.gif" width="128" height="31" border="0" alt="Download free search tool"></a></td>
                </tr>
              </table>
            </td>
          </tr>
        </form>
      </table>
    </td>
  </tr>
</table>
<table width="130" border="0" cellspacing="0" cellpadding="0" bgcolor="#000000" background="/newimages/misc/50x50pix.gif">
  <tr bgcolor="#000000"> 
    <td> 
      <table width="100%" border=0 cellpadding=0 cellspacing=1>
        <tr bgcolor="#18355C"> 
          <td style="border='1 #18355C'" onMouseOver="style.backgroundColor='#FFFFFF'; style.cursor='hand'; style.border='1 #18355C'" onMouseOut="style.backgroundColor='#719FC6'; style.border='1 #18355C';" height="21" bgcolor="#719FC6"> 
            <table width="100%" border="0" cellspacing="0" cellpadding="0">
              <tr> 
                <td class="Bolded"><img src="/newimages/misc/navarrow.gif" width="12" height="21"></td>
                <td bgcolor="#18355C" height="21" width="100%"><a href="/company/index.phtml" class="bluelinks" style="margin:0;">
<div><img src="/newimages/misc/1pix.gif" width="5" height="1" border="0">The Company</div></a></td>
              </tr>
            </table>
          </td>
        </tr>
        <tr bgcolor="#18355C"> 
          <td style="border='1 #18355C'" onMouseOver="style.backgroundColor='#FFFFFF'; style.cursor='hand'; style.border='1 #18355C'" onMouseOut="style.backgroundColor='#719FC6'; style.border='1 #18355C';" height="21" bgcolor="#719FC6"> 
            <table width="100%" border="0" cellspacing="0" cellpadding="0">
              <tr> 
                <td class="Bolded"><img src="/newimages/misc/navarrow.gif" width="12" height="21"></td>
                <td bgcolor="#18355C" height="21" width="100%"><a href="/mediakit/index.phtml" class="bluelinks" style="margin:0;">
<div><img src="/newimages/misc/1pix.gif" width="5" height="1" border="0">Our Mediakit</div></a></td>
              </tr>
            </table>
          </td>
        </tr>
        <tr bgcolor="#18355C"> 
          <td style="border='1 #18355C'" onMouseOver="style.backgroundColor='#FFFFFF'; style.cursor='hand'; style.border='1 #18355C'" onMouseOut="style.backgroundColor='#719FC6'; style.border='1 #18355C';" height="21" bgcolor="#719FC6"> 
            <table width="100%" border="0" cellspacing="0" cellpadding="0">
              <tr> 
                <td class="Bolded"><img src="/newimages/misc/navarrow.gif" width="12" height="21"></td>
                <td bgcolor="#18355C" height="21" width="100%"><a href="/press.phtml" class="bluelinks" style="margin:0;">
<div><img src="/newimages/misc/1pix.gif" width="5" height="1" border="0">Press Material</div></a></td>
              </tr>
            </table>
          </td>
        </tr>
        <tr bgcolor="#18355C"> 
          <td style="border='1 #18355C'" onMouseOver="style.backgroundColor='#FFFFFF'; style.cursor='hand'; style.border='1 #18355C'" onMouseOut="style.backgroundColor='#719FC6'; style.border='1 #18355C';" height="21" bgcolor="#719FC6"> 
            <table width="100%" border="0" cellspacing="0" cellpadding="0">
              <tr> 
                <td class="Bolded"><img src="/newimages/misc/navarrow.gif" width="12" height="21"></td>
                <td bgcolor="#18355C" height="21" width="100%"><a href="/contactus/index.phtml" class="bluelinks" style="margin:0;">
<div><img src="/newimages/misc/1pix.gif" width="5" height="1" border="0">Contact Us</div></a></td>
              </tr>
            </table>
          </td>
        </tr>
      </table>
    </td>
  </tr>
</table>
    </td>
    <TD width="642" valign="top" background="/newimages/backgrounds/middlecolumn_black_wide.gif">

  
      <TABLE width="100%" border="0" cellspacing="0" cellpadding="0" background="/images2/sections/resize.gif">
        <TR> 
          <TD><IMG src="/images2/misc/1pixblack.gif" width="1" height="63"></TD>
          <TD width="100%" valign="bottom"> 
            <TABLE width="100%" border="0" cellspacing="0" cellpadding="0" background="/images2/misc/50x50pix.gif">
              <TR> 
                <TD height="28"><SPAN class="Bolded"><IMG src="/images2/misc/1pix.gif" width="11" height="1">Page:</SPAN> 
									<SPAN class="bluebolded"> &nbsp;1&nbsp;of&nbsp;128</SPAN></TD>
              </TR>
            </TABLE>
          </TD>
          <TD align="right"><IMG src="/newimages/sections/newsarchive.gif" width="275" height="63"></TD>
        </TR>
      </TABLE>
      <TABLE width="100%" border="0" cellspacing="0" cellpadding="0">
				<TR> 
					
          <TD valign="top" width="100%" align="center"> 
            <table width="100%" border="0" cellspacing="0" cellpadding="0" background="/newimages/titles/lowresize.gif">
              <tr> 
                <td width="100%"><img src="/newimages/titles/archive.gif" width="130" height="24"></td>
                <td><img src="/newimages/titles/lowrightcorner.gif" width="6" height="24"></td>
              </tr>
            </table>
            <TABLE width="100%" border="0" cellspacing="1" cellpadding="0">
							<FORM method="post" action="/news.phtml">
								<TR> 
									<TD height="40"><IMG src="/images2/misc/1pix.gif" width="10" height="8"></TD>
									<TD height="40" width="100%" nowrap><SPAN class="Bolded"><SPAN class="bluebolded">Search 
										News:&nbsp;</SPAN></SPAN>&nbsp; 
										<INPUT type="text" name="search" class="formbody" size="14" maxlength="50" value="">
										&nbsp; 
										<SELECT name="rel_category" class="formbody">
											<option selected value="0">All</option>
<option  value="1">Action</option>
<option  value="15">Adventure</option>
<option  value="3">Hardware</option>
<option  value="16">Other</option>
<option  value="14">Peripherals</option>
<option  value="17">Puzzle</option>
<option  value="12">Racing</option>
<option  value="11">RPG</option>
<option  value="2">Simulation</option>
<option  value="4">Software</option>
<option  value="8">Sport</option>
<option  value="9">Strategy</option>
 
										</SELECT>
										&nbsp; &nbsp; 
										<INPUT type="image" border="0" name="imageField2" src="/images2/buttons/search_go.gif" width="24" height="22" align="top">
									</TD>
									<TD height="40" class="Bolded" align="right" nowrap> <!--Offset: 0 -->
1&nbsp;|&nbsp;<a href="?page=1&search=&cnt=127&rel_category=&sortby=">2</a>&nbsp;|&nbsp;<a href="?page=2&search=&cnt=127&rel_category=&sortby=">3</a>&nbsp;|&nbsp;<a href="?page=3&search=&cnt=127&rel_category=&sortby=">4</a>&nbsp;|&nbsp;<a href="?page=4&search=&cnt=127&rel_category=&sortby=">5</a>&nbsp;|&nbsp;<a href="?page=5&search=&cnt=127&rel_category=&sortby=">6</a>&nbsp;|&nbsp;<a href="?page=6&search=&cnt=127&rel_category=&sortby=">7</a>&nbsp;|&nbsp;<a href="?page=10&search=&cnt=127&rel_category=&sortby=">&gt;&gt;</a>
 &nbsp;&nbsp; <IMG src="/images2/misc/1pix.gif" width="10" height="1"></TD>
								</TR>
							</FORM>
						</TABLE>
							
<TABLE width="100%" border="0" cellspacing="0" cellpadding="0">
<TR>
<TD nowrap class="Bluebolded" background="/images2/buttons/resize.gif" height="25"><IMG src="/images2/misc/1pix.gif" width="11" height="1">Friday, August 3</TD>
<TD width="100%" background="/images2/buttons/resize.gif" height="25" align="right" nowrap><A href="mailto:news@mgon.com">Report news</A>&nbsp;&nbsp;|&nbsp;&nbsp;<A href="/news.phtml">Archive</A>&nbsp;&nbsp;|&nbsp;&nbsp;<A href="#top">Top</A>&nbsp;&nbsp;&nbsp;</TD>
</TR>
</TABLE><TABLE width="100%" border="0" cellspacing="0" cellpadding="11"><TR><TD width="100%"><P><SPAN class="Headline">Empire Earth Beta sign up begins</SPAN> 
<TABLE width="100%" border="0" cellspacing="1" cellpadding="0">
<TR bgcolor="#335F5F"> 
<TD colspan="2" nowrap><IMG src="/images2/misc/1pix.gif" width="1" height="1"></TD>
</TR>
<TR>
<TD height="20" width="100%" nowrap><SPAN class="Bolded">Reported by: </SPAN><A href="javascript:Profile=open('/common/showprofile.phtml?id=', 'Profile','width=480,height=480,scrollbars=no,toolbar=no');Profile.focus();" >Rogey</A>&nbsp;&nbsp;|&nbsp;&nbsp;<SPAN class="Bolded">Source: </SPAN> </TD>
<TD align="right" bgcolor="#001F39" nowrap>&nbsp;&nbsp;<A href="/news.phtml?id=90593&language=en&action=comments">0 Comments</A> | <A href="/news.phtml?id=90593&language=en&action=comments#addcomment">Add</A>&nbsp;&nbsp;</TD>
</TR>
</TABLE>
<P><SPAN class="normal">If you love tinkering with unfinished games then maybe you should consider doing a little Beta testing work.  You could for instance apply to be a Beta tester for Stainless Steel Studios’ RTS game Empire Earth.  <BR><P>[&nbsp;<a href="/news.phtml?id=90593&language=en">Read More...</a>&nbsp;]</SPAN></TD></TR></TABLE>
<TABLE width="100%" border="0" cellspacing="0" cellpadding="0">
<TR>
<TD nowrap class="Bluebolded" background="/images2/buttons/resize.gif" height="25"><IMG src="/images2/misc/1pix.gif" width="11" height="1">Thursday, August 2</TD>
<TD width="100%" background="/images2/buttons/resize.gif" height="25" align="right" nowrap><A href="mailto:news@mgon.com">Report news</A>&nbsp;&nbsp;|&nbsp;&nbsp;<A href="/news.phtml">Archive</A>&nbsp;&nbsp;|&nbsp;&nbsp;<A href="#top">Top</A>&nbsp;&nbsp;&nbsp;</TD>
</TR>
</TABLE><TABLE width="100%" border="0" cellspacing="0" cellpadding="11"><TR><TD width="100%"><P><SPAN class="Headline">The Latest WADster</SPAN> 
<TABLE width="100%" border="0" cellspacing="1" cellpadding="0">
<TR bgcolor="#335F5F"> 
<TD colspan="2" nowrap><IMG src="/images2/misc/1pix.gif" width="1" height="1"></TD>
</TR>
<TR>
<TD height="20" width="100%" nowrap><SPAN class="Bolded">Reported by: </SPAN><A href="javascript:Profile=open('/common/showprofile.phtml?id=', 'Profile','width=480,height=480,scrollbars=no,toolbar=no');Profile.focus();" >Miff</A>&nbsp;&nbsp;|&nbsp;&nbsp;<SPAN class="Bolded">Source: </SPAN> </TD>
<TD align="right" bgcolor="#001F39" nowrap>&nbsp;&nbsp;<A href="/news.phtml?id=90647&language=en&action=comments">0 Comments</A> | <A href="/news.phtml?id=90647&language=en&action=comments#addcomment">Add</A>&nbsp;&nbsp;</TD>
</TR>
</TABLE>
<P><SPAN class="normal">Karthik Abhirama Krishna is WADster of the Week over at <a href="http://www.doomcenter.com">Doom Center!</a> Along with a massive interview about new projects such as 9th Gate and DW speedmapping, there's a Best of Karthik Pack! Reason enough to tool up that shotgun and head on over for the latest in the world of DOOM!<br />
<br />
Check out WADSter of the Week by clicking <a href="http://www.doomcenter.com/features/features.phtml?id=90512&language=en">here!</a><BR><!--No link--></SPAN></TD></TR></TABLE><TABLE width="100%" border="0" cellspacing="0" cellpadding="11"><TR><TD width="100%"><P><SPAN class="Headline">ATI Ships DV WONDER in Europe</SPAN> 
<TABLE width="100%" border="0" cellspacing="1" cellpadding="0">
<TR bgcolor="#335F5F"> 
<TD colspan="2" nowrap><IMG src="/images2/misc/1pix.gif" width="1" height="1"></TD>
</TR>
<TR>
<TD height="20" width="100%" nowrap><SPAN class="Bolded">Reported by: </SPAN><A href="javascript:Profile=open('/common/showprofile.phtml?id=', 'Profile','width=480,height=480,scrollbars=no,toolbar=no');Profile.focus();" >Simon</A>&nbsp;&nbsp;|&nbsp;&nbsp;<SPAN class="Bolded">Source: </SPAN> </TD>
<TD align="right" bgcolor="#001F39" nowrap>&nbsp;&nbsp;<A href="/news.phtml?id=90600&language=en&action=comments">0 Comments</A> | <A href="/news.phtml?id=90600&language=en&action=comments#addcomment">Add</A>&nbsp;&nbsp;</TD>
</TR>
</TABLE>
<P><SPAN class="normal">From September the ATI DV WONDER will be available in Europe. The DV WONDER is an affordable PC Firewire upgrade for Video editing. For more information about this new innovative product from ATI click read more.<BR><P>[&nbsp;<a href="/news.phtml?id=90600&language=en">Read More...</a>&nbsp;]</SPAN></TD></TR></TABLE><TABLE width="100%" border="0" cellspacing="0" cellpadding="11"><TR><TD width="100%"><P><SPAN class="Headline">MGON looks at Monopoly Tycoon</SPAN> 
<TABLE width="100%" border="0" cellspacing="1" cellpadding="0">
<TR bgcolor="#335F5F"> 
<TD colspan="2" nowrap><IMG src="/images2/misc/1pix.gif" width="1" height="1"></TD>
</TR>
<TR>
<TD height="20" width="100%" nowrap><SPAN class="Bolded">Reported by: </SPAN><A href="javascript:Profile=open('/common/showprofile.phtml?id=', 'Profile','width=480,height=480,scrollbars=no,toolbar=no');Profile.focus();" >Rogey</A>&nbsp;&nbsp;|&nbsp;&nbsp;<SPAN class="Bolded">Source: </SPAN> </TD>
<TD align="right" bgcolor="#001F39" nowrap>&nbsp;&nbsp;<A href="/news.phtml?id=90524&language=en&action=comments">1 Comments</A> | <A href="/news.phtml?id=90524&language=en&action=comments#addcomment">Add</A>&nbsp;&nbsp;</TD>
</TR>
</TABLE>
<P><SPAN class="normal">If you thought this game was a walk in the park, think again! UK based game developer Deep Red is working on a new PC title called Monopoly Tycoon and MGON had a look at the game today.<BR><P>[&nbsp;<a href="/news.phtml?id=90524&language=en">Read More...</a>&nbsp;]</SPAN></TD></TR></TABLE>
<TABLE width="100%" border="0" cellspacing="0" cellpadding="0">
<TR>
<TD nowrap class="Bluebolded" background="/images2/buttons/resize.gif" height="25"><IMG src="/images2/misc/1pix.gif" width="11" height="1">Wednesday, August 1</TD>
<TD width="100%" background="/images2/buttons/resize.gif" height="25" align="right" nowrap><A href="mailto:news@mgon.com">Report news</A>&nbsp;&nbsp;|&nbsp;&nbsp;<A href="/news.phtml">Archive</A>&nbsp;&nbsp;|&nbsp;&nbsp;<A href="#top">Top</A>&nbsp;&nbsp;&nbsp;</TD>
</TR>
</TABLE><TABLE width="100%" border="0" cellspacing="0" cellpadding="11"><TR><TD width="100%"><P><SPAN class="Headline">The Majestic experience begins</SPAN> 
<TABLE width="100%" border="0" cellspacing="1" cellpadding="0">
<TR bgcolor="#335F5F"> 
<TD colspan="2" nowrap><IMG src="/images2/misc/1pix.gif" width="1" height="1"></TD>
</TR>
<TR>
<TD height="20" width="100%" nowrap><SPAN class="Bolded">Reported by: </SPAN><A href="javascript:Profile=open('/common/showprofile.phtml?id=', 'Profile','width=480,height=480,scrollbars=no,toolbar=no');Profile.focus();" >Rogey</A>&nbsp;&nbsp;|&nbsp;&nbsp;<SPAN class="Bolded">Source: </SPAN> </TD>
<TD align="right" bgcolor="#001F39" nowrap>&nbsp;&nbsp;<A href="/news.phtml?id=90484&language=en&action=comments">0 Comments</A> | <A href="/news.phtml?id=90484&language=en&action=comments#addcomment">Add</A>&nbsp;&nbsp;</TD>
</TR>
</TABLE>
<P><SPAN class="normal">EA’s massive online conspiracy game Majestic has been launched and is now ready to play.  You can get it by going to the <A TARGET="_blank" HREF="http://www.majesticthegame.com/">Majestic Online</A> website, and then you’ll need to sign yourself up and hand over the required dollars.<BR><P>[&nbsp;<a href="/news.phtml?id=90484&language=en">Read More...</a>&nbsp;]</SPAN></TD></TR></TABLE><TABLE width="100%" border="0" cellspacing="0" cellpadding="11"><TR><TD width="100%"><P><SPAN class="Headline">Mech Commander 2 update</SPAN> 
<TABLE width="100%" border="0" cellspacing="1" cellpadding="0">
<TR bgcolor="#335F5F"> 
<TD colspan="2" nowrap><IMG src="/images2/misc/1pix.gif" width="1" height="1"></TD>
</TR>
<TR>
<TD height="20" width="100%" nowrap><SPAN class="Bolded">Reported by: </SPAN><A href="javascript:Profile=open('/common/showprofile.phtml?id=', 'Profile','width=480,height=480,scrollbars=no,toolbar=no');Profile.focus();" >Rogey</A>&nbsp;&nbsp;|&nbsp;&nbsp;<SPAN class="Bolded">Source: </SPAN> </TD>
<TD align="right" bgcolor="#001F39" nowrap>&nbsp;&nbsp;<A href="/news.phtml?id=90441&language=en&action=comments">0 Comments</A> | <A href="/news.phtml?id=90441&language=en&action=comments#addcomment">Add</A>&nbsp;&nbsp;</TD>
</TR>
</TABLE>
<P><SPAN class="normal">Mech Commander 2 is out in the stores right now and MGON has a review that will be posted sometime later today (or tonight, depending on where in the world you are!).<br />
<BR><P>[&nbsp;<a href="/news.phtml?id=90441&language=en">Read More...</a>&nbsp;]</SPAN></TD></TR></TABLE><TABLE width="100%" border="0" cellspacing="0" cellpadding="11"><TR><TD width="100%"><P><SPAN class="Headline">Commandos 2 and Shogun Warlord completed</SPAN> 
<TABLE width="100%" border="0" cellspacing="1" cellpadding="0">
<TR bgcolor="#335F5F"> 
<TD colspan="2" nowrap><IMG src="/images2/misc/1pix.gif" width="1" height="1"></TD>
</TR>
<TR>
<TD height="20" width="100%" nowrap><SPAN class="Bolded">Reported by: </SPAN><A href="javascript:Profile=open('/common/showprofile.phtml?id=', 'Profile','width=480,height=480,scrollbars=no,toolbar=no');Profile.focus();" >Rogey</A>&nbsp;&nbsp;|&nbsp;&nbsp;<SPAN class="Bolded">Source: </SPAN> </TD>
<TD align="right" bgcolor="#001F39" nowrap>&nbsp;&nbsp;<A href="/news.phtml?id=90437&language=en&action=comments">0 Comments</A> | <A href="/news.phtml?id=90437&language=en&action=comments#addcomment">Add</A>&nbsp;&nbsp;</TD>
</TR>
</TABLE>
<P><SPAN class="normal">In the last few weeks there have been several big name games completed including Max Payne and Mech Commander 2.  Now Eidos’ strategy game Commandos 2 joins that list and will be released in a few weeks’ time.  <BR><P>[&nbsp;<a href="/news.phtml?id=90437&language=en">Read More...</a>&nbsp;]</SPAN></TD></TR></TABLE><TABLE width="100%" border="0" cellspacing="0" cellpadding="11"><TR><TD width="100%"><P><SPAN class="Headline">Console Roundup</SPAN> 
<TABLE width="100%" border="0" cellspacing="1" cellpadding="0">
<TR bgcolor="#335F5F"> 
<TD colspan="2" nowrap><IMG src="/images2/misc/1pix.gif" width="1" height="1"></TD>
</TR>
<TR>
<TD height="20" width="100%" nowrap><SPAN class="Bolded">Reported by: </SPAN><A href="javascript:Profile=open('/common/showprofile.phtml?id=', 'Profile','width=480,height=480,scrollbars=no,toolbar=no');Profile.focus();" >Venom</A>&nbsp;&nbsp;|&nbsp;&nbsp;<SPAN class="Bolded">Source: </SPAN> </TD>
<TD align="right" bgcolor="#001F39" nowrap>&nbsp;&nbsp;<A href="/news.phtml?id=90354&language=en&action=comments">0 Comments</A> | <A href="/news.phtml?id=90354&language=en&action=comments#addcomment">Add</A>&nbsp;&nbsp;</TD>
</TR>
</TABLE>
<P><SPAN class="normal">MGON's console channels have some great new media and information for you, bringing you as up to date as anywhere on the .net.  Interested in what <A TARGET="_blank" HREF="http://www.playstationcenter.com">PlayStationCenter </A> and <A TARGET="_blank" HREF="http://www.nintendocenter.com">NintendoCenter </A> have to offer today?  Step inside for the full round up...<br><br />
<br />
<BR><P>[&nbsp;<a href="/news.phtml?id=90354&language=en">Read More...</a>&nbsp;]</SPAN></TD></TR></TABLE>
<TABLE width="100%" border="0" cellspacing="0" cellpadding="0">
<TR>
<TD nowrap class="Bluebolded" background="/images2/buttons/resize.gif" height="25"><IMG src="/images2/misc/1pix.gif" width="11" height="1">Tuesday, July 31</TD>
<TD width="100%" background="/images2/buttons/resize.gif" height="25" align="right" nowrap><A href="mailto:news@mgon.com">Report news</A>&nbsp;&nbsp;|&nbsp;&nbsp;<A href="/news.phtml">Archive</A>&nbsp;&nbsp;|&nbsp;&nbsp;<A href="#top">Top</A>&nbsp;&nbsp;&nbsp;</TD>
</TR>
</TABLE><TABLE width="100%" border="0" cellspacing="0" cellpadding="11"><TR><TD width="100%"><P><SPAN class="Headline">SOF soldiers on</SPAN> 
<TABLE width="100%" border="0" cellspacing="1" cellpadding="0">
<TR bgcolor="#335F5F"> 
<TD colspan="2" nowrap><IMG src="/images2/misc/1pix.gif" width="1" height="1"></TD>
</TR>
<TR>
<TD height="20" width="100%" nowrap><SPAN class="Bolded">Reported by: </SPAN><A href="javascript:Profile=open('/common/showprofile.phtml?id=', 'Profile','width=480,height=480,scrollbars=no,toolbar=no');Profile.focus();" >Rogey</A>&nbsp;&nbsp;|&nbsp;&nbsp;<SPAN class="Bolded">Source: </SPAN> </TD>
<TD align="right" bgcolor="#001F39" nowrap>&nbsp;&nbsp;<A href="/news.phtml?id=90236&language=en&action=comments">0 Comments</A> | <A href="/news.phtml?id=90236&language=en&action=comments#addcomment">Add</A>&nbsp;&nbsp;</TD>
</TR>
</TABLE>
<P><SPAN class="normal">There will be yet another Soldier of Fortune game package released.  Raven Software will make available Soldier of Fortune: Platinum Edition, which will contain Soldier of Fortune Gold, patch 1.07 (which fixes troublesome WON.net issues), new weapons, five new multiplayer levels and gameplay footage of Soldier of Fortune II: Double Helix.<BR><P>[&nbsp;<a href="/news.phtml?id=90236&language=en">Read More...</a>&nbsp;]</SPAN></TD></TR></TABLE><TABLE width="100%" border="0" cellspacing="0" cellpadding="11"><TR><TD width="100%"><P><SPAN class="Headline">One more Anachronox patch in the works</SPAN> 
<TABLE width="100%" border="0" cellspacing="1" cellpadding="0">
<TR bgcolor="#335F5F"> 
<TD colspan="2" nowrap><IMG src="/images2/misc/1pix.gif" width="1" height="1"></TD>
</TR>
<TR>
<TD height="20" width="100%" nowrap><SPAN class="Bolded">Reported by: </SPAN><A href="javascript:Profile=open('/common/showprofile.phtml?id=', 'Profile','width=480,height=480,scrollbars=no,toolbar=no');Profile.focus();" >Rogey</A>&nbsp;&nbsp;|&nbsp;&nbsp;<SPAN class="Bolded">Source: </SPAN> </TD>
<TD align="right" bgcolor="#001F39" nowrap>&nbsp;&nbsp;<A href="/news.phtml?id=90230&language=en&action=comments">0 Comments</A> | <A href="/news.phtml?id=90230&language=en&action=comments#addcomment">Add</A>&nbsp;&nbsp;</TD>
</TR>
</TABLE>
<P><SPAN class="normal">The team at Ion Storm Dallas are continuing to work on the ongoing development of Anachronox patches despite the teams’ pending disbandment.  If all goes well there will be a patch released some time next week and a few additions to the game.<BR><P>[&nbsp;<a href="/news.phtml?id=90230&language=en">Read More...</a>&nbsp;]</SPAN></TD></TR></TABLE><TABLE width="100%" border="0" cellspacing="0" cellpadding="11"><TR><TD width="100%"><P><SPAN class="Headline">MGON site updates</SPAN> 
<TABLE width="100%" border="0" cellspacing="1" cellpadding="0">
<TR bgcolor="#335F5F"> 
<TD colspan="2" nowrap><IMG src="/images2/misc/1pix.gif" width="1" height="1"></TD>
</TR>
<TR>
<TD height="20" width="100%" nowrap><SPAN class="Bolded">Reported by: </SPAN><A href="javascript:Profile=open('/common/showprofile.phtml?id=', 'Profile','width=480,height=480,scrollbars=no,toolbar=no');Profile.focus();" >Rogey</A>&nbsp;&nbsp;|&nbsp;&nbsp;<SPAN class="Bolded">Source: </SPAN> </TD>
<TD align="right" bgcolor="#001F39" nowrap>&nbsp;&nbsp;<A href="/news.phtml?id=90213&language=en&action=comments">0 Comments</A> | <A href="/news.phtml?id=90213&language=en&action=comments#addcomment">Add</A>&nbsp;&nbsp;</TD>
</TR>
</TABLE>
<P><SPAN class="normal">We have just received reports from some other sites around the MGON network, so you can check up on what is happening with your favorite gaming community.  Click on the link below to read the updates.<br />
<br />
The current updates include:<br />
Quake3 Center.com<br />
May Payne Center.com<br />
MechWarrior Center.com<br />
<BR><P>[&nbsp;<a href="/news.phtml?id=90213&language=en">Read More...</a>&nbsp;]</SPAN></TD></TR></TABLE>
<TABLE width="100%" border="0" cellspacing="0" cellpadding="0">
<TR>
<TD nowrap class="Bluebolded" background="/images2/buttons/resize.gif" height="25"><IMG src="/images2/misc/1pix.gif" width="11" height="1">Monday, July 30</TD>
<TD width="100%" background="/images2/buttons/resize.gif" height="25" align="right" nowrap><A href="mailto:news@mgon.com">Report news</A>&nbsp;&nbsp;|&nbsp;&nbsp;<A href="/news.phtml">Archive</A>&nbsp;&nbsp;|&nbsp;&nbsp;<A href="#top">Top</A>&nbsp;&nbsp;&nbsp;</TD>
</TR>
</TABLE><TABLE width="100%" border="0" cellspacing="0" cellpadding="11"><TR><TD width="100%"><P><SPAN class="Headline">Operation: Flashpoint up for grabs</SPAN> 
<TABLE width="100%" border="0" cellspacing="1" cellpadding="0">
<TR bgcolor="#335F5F"> 
<TD colspan="2" nowrap><IMG src="/images2/misc/1pix.gif" width="1" height="1"></TD>
</TR>
<TR>
<TD height="20" width="100%" nowrap><SPAN class="Bolded">Reported by: </SPAN><A href="javascript:Profile=open('/common/showprofile.phtml?id=', 'Profile','width=480,height=480,scrollbars=no,toolbar=no');Profile.focus();" >sands</A>&nbsp;&nbsp;|&nbsp;&nbsp;<SPAN class="Bolded">Source: </SPAN> </TD>
<TD align="right" bgcolor="#001F39" nowrap>&nbsp;&nbsp;<A href="/news.phtml?id=89989&language=en&action=comments">0 Comments</A> | <A href="/news.phtml?id=89989&language=en&action=comments#addcomment">Add</A>&nbsp;&nbsp;</TD>
</TR>
</TABLE>
<P><SPAN class="normal">MGON's newly launched <A TARGET="_blank" HREF="http://www.flashpointcenter.com/">Flashpoint Center</A> has 4 copies of Operation Flashpoint to give away. Head over to Flashpoint Center for details on how you can win.<br />
<br />
[ <A TARGET="_blank" HREF="http://www.flashpointcenter.com/competitions/gamecomp.phtml">Read More...</A> ]<BR><!--No link--></SPAN></TD></TR></TABLE>  
						</TABLE>
					</TD>
				</TR>
			</TABLE>
			<P> 					
				</table></td>

        </tr>

      </table>

     
		

 
<table width="772" border="0" cellspacing="0" cellpadding="0" align="center">
  <tr>
    <td><img src="/newimages/bottom/copyright.gif" width="621" height="30" border="0" usemap="#Map2"></td>
    <td><a href="/"><img src="/newimages/bottom/home.gif" width="75" height="30" border="0"></a></td>
    <td><a href="#top"><img src="/newimages/bottom/top.gif" width="76" height="30" border="0"></a></td>
  </tr>
</table>
<TABLE width="772" border="0" cellspacing="0" cellpadding="0" height="90" background="/images2/misc/50x50pix.gif" align="center">
  <TR bgcolor="#000000" align="center"> 
    <TD class="smalltext"><SCRIPT language="JavaScript"
src="http://adtegrity.spinbox.net/?DC=Mgon+Bottom&JS=Y&TARGET=_new">
</SCRIPT><NOSCRIPT><A href="http://adtegrity.spinbox.net/?SHT=Mgon+Bottom" target="_new"
height="468" width="60"><IMG src="http://adtegrity.spinbox.net/?SIT=Mgon+Bottom" border="0"></A></NOSCRIPT></TD>
  </TR>
</TABLE>
<map name="Map">
  <area shape="rect" coords="387,7,495,25" href="/privacy.phtml">
</map>
<map name="Map2">
  <area shape="rect" coords="384,4,496,26" href="/privacy">
</map>

 

<!--Bottom Layer-->
      <LAYER SRC="http://ad.se.doubleclick.net/adl/mgon.com/;sz=468x60;ord=996802332?" bgcolor="#000000" width="468" height="60" visibility="hidden" onLoad="moveToAbsolute(layer1.pageX,layer1.pageY);clip.height=60;clip.width=468; visibility='show';"></LAYER><!--End Bottom Layer-->
</BODY>

</HTML>


