<!--
   This page has been created by Renaissance IT
   Renaissance Internet Technologies Copyright (c) 1999 All Rights Reserved.
   for more info on our products, please visit : http://www.renaissance.nl/
   This script has been written by Roy Boverhof <rboverhof@renaissance.nl>
 
   Pagename             : main.phtml
   Last Updated    		: 03-16-2001
-->

<HTML>
<HEAD>
	<TITLE>the Seekers of Lore : Main</TITLE>
</HEAD>
<BODY BGCOLOR="#000000" TEXT="#ffffff" LINK="#fff000" VLINK="#fff000" marginwidth="0" marginheight="0">
<DIV align=center>
<BR>
<!-- FGB Banner Code -->
<SCRIPT LANGUAGE="JavaScript">
<!-- Hide from old browsers
now = new Date();
random = now.getTime();

// Modify to reflect site specifics
site = "http://ds.cybereps.com";
target = "/SITE=FGN/AREA=EQLORE/AAMSZ=BANNER";

document.write('<IFRAME SRC="' + site + '/hserver/acc_random=' + random + target + '"');
document.write(' NORESIZE SCROLLING=NO HSPACE=0 VSPACE=0 FRAMEBORDER=0 MARGINHEIGHT=0 MARGINWIDTH=0 WIDTH=468 HEIGHT=60>');

document.write('<SCR');
document.write('IPT SRC="' + site + '/jnserver/acc_random=' + random + target + '">');
document.write('</SCR');
document.write('IPT>');

document.write('</IFRAME>');
// End Hide -->
</SCRIPT>

<NOSCRIPT><A HREF="http://ds.cybereps.com/accipiter/adclick/SITE=FGN/AREA=EQLORE/AAMSZ=BANNER"><IMG SRC="http://ds.cybereps.com/accipiter/nserver/SITE=FGN/AREA=EQLORE/AAMSZ=BANNER" border="0"></A></NOSCRIPT>
<!-- END FGB Banner Code --><table WIDTH="98%">
<tr>
	<td VALIGN="top">
	<TABLE cellPadding=3 cellSpacing=3 VALIGN="top">
    <TR>
      <TD VALIGN="top">
      <CENTER><B><FONT size=+1>Welcome to the "Seekers of Lore"</FONT></B></CENTER>
	  <font size="-1">
	  <P><FONT size=+1>W</FONT>e are an EverQuest guild devoted to the never ending quest for knowledge.
      <P><FONT size=+1>F</FONT>ounded by the glorious <A href="madwand.phtml">MadWand</A> and lead by the mighty <A href="http://www.loreSeekers.com/mem_detail.php3?search=2">Sorontar</A>, 
      the Seekers of Lore are devoted to collecting and cataloging all the EQ lore they can! Be it maps, quests, items or creative works by the players of EQ, we will have it here or link to where you can find it! So, please, 
	  take a moment and browse through our libraries. If you like what you see 
	  or have any comments to make, then feel free to sign our <A href="guestbook.php3">Guestbook</A>.<BR>
      <P><FONT size=+1>S</FONT>incerely,<BR>
	  <A href="mailto:webmaster@loreSeekers.com"><B>Sorontar D'Agora</B></A> 
      </P>
	  </font>
	  </TD>
	</TR>

	<tr><td><BR></td></tr>
	
	<TR>
		<TD VALIGN="top">
		<DIV ALIGN="left"><B>Site news :</B><BR><FONT FACE="Verdana, Arial" SIZE=+1 COLOR="#FFFF00"><A NAME="200175020"><B>Happy 2nd Birthday EQ!</B></A></FONT><BR><BR><TABLE><TR><TD><FONT FACE="Verdana, Arial" SIZE=2><FONT SIZE="2" FACE="arial">
Happy Birthday Eq'ers!<BR><BR>

Today, EQ turns TWO years old. It is hard to believe that the game is still going so strong and continues to increase in popularity daily. To mark this occassion, I have posted a special anniversery update to our site!<BR><BR>

Foremost in the update is a special <A HREF="stories/unique.phtml">article</A> I have written about EQ past and present. I hope I have captured how EverQuest has been a part of my life for well over 2 years now, and how, even though I don't play regularily anymore, I still interact in the community of EQ, and take great pleasure in helping keep this site running for all you players and fans.</FONT><BR><BR>


<A HREF="main.phtml"><B>Polls:</B></A><BR>
<FONT SIZE="2" FACE="arial">
Here are the results from the poll that has been up for the past month and a bit. The question was "<I>If there are no more add-ons to EQ, about how much longer will you play it?</I>". It's quite obvious most of you are still totally addicted to this game, hehe.
</FONT><BR><BR>

<TABLE BORDER=2>
<FONT FACE="verdana, arial" SIZE="1" COLOR="#FFFDCA">
<TR>
<TD><B>Answer</B></TD>
<TD><B>Votes</B></TD>
<TD><B>%</B></TD>
</TR>
<TR>
<TD>
1. Forever<BR>
2. At least a year<BR>
3. Less then 6 months<BR>
4. Not much longer<BR>
</TD>
<TD>
283<BR>
327<BR>
80<BR>
64<BR>
</TD>
<TD>
37.53%<BR>
43.37%<BR>
10.61%<BR>
8.49%<BR>
</TD>
</TR>
<TR>
<TD><B>Total Votes</B></TD>
<TD>754</TD>
<TD> </TD>
</TR>
</FONT>
</TABLE>

<P><FONT SIZE="2" FACE="arial">
With the second anniversery of EQ I thought a good poll to ask was just how many visitors here were playing on March 16th 1999, when the game was first released? So the new poll question will be "Where you playing EQ on the first day, 2 years ago?"
</FONT><BR><BR>

<A HREF="links.phtml"><B>Links:</B></A><BR>
<FONT SIZE="2" FACE="arial">
Updated all the link pages to reflect some new url's and other changes in graphics, etc. 
</FONT><BR><BR>

<A HREF="maps.php3"><B>Maps:</B></A><BR>
<FONT SIZE="2" FACE="arial">
A huge map update today to make up for the lack of ones this past month. I have added 20 new maps, including 2 for the brand new zone, the Warrens. That brings the total number of maps in our database to 389!
</FONT><BR><BR>

<FONT SIZE="2" FACE="arial">1. <A HREF="map_search.php3?action=zone&add_zone=Warrens">Warrens</A> - 2 maps of this new zone!</FONT><BR>
<FONT SIZE="2" FACE="arial">2. <A HREF="map_search.php3?action=zone&add_zone=Plane%20Of%20Sky">Plane of Sky</A> - By Medd Meddley</FONT><BR>
<FONT SIZE="2" FACE="arial">3. <A HREF="map_search.php3?action=zone&add_zone=Chardok">Chardok</A> - New set by Beepbeep</FONT><BR>
<FONT SIZE="2" FACE="arial">4. <A HREF="map_search.php3?action=zone&add_zone=Howling%20Stones">Howling Stones</A> - 1 new map</FONT><BR>
<FONT SIZE="2" FACE="arial">5. <A HREF="map_search.php3?action=zone&add_zone=Neriak%20Commons">Neriak - All areas</A> - By Zealott</FONT><BR>
<FONT SIZE="2" FACE="arial">6. <A HREF="map_search.php3?action=zone&add_zone=Siren's%20Grotto">Siren's Grotto</A> - New set by Draelon Stormsong</FONT><BR>
<FONT SIZE="2" FACE="arial">7. <A HREF="map_search.php3?action=zone&add_zone=Kael%20Drakken">Kael Drakken</A> - By Doccus Windstalker</FONT><BR>
<FONT SIZE="2" FACE="arial">8. <A HREF="map_search.php3?action=zone&add_zone=Skyshrine">Skyshrine</A> - New set by Illandra Azuryne</FONT><BR>
<FONT SIZE="2" FACE="arial">9. <A HREF="map_search.php3?action=zone&add_zone=Karnor's%20Castle">Karnor's Castle - Catacombs</A> - By EQ Atlas</FONT><BR><BR>

<B><I>MadWand</I></B></FONT></TD></TR></TABLE></DIV><BR><DIV ALIGN="left"><B>EQ news :</B><BR><FONT FACE="Verdana, Arial" SIZE=+1 COLOR="#FFFF00"><A NAME="200174200"><B>2 Year Birthday Patch</B></A></FONT><BR><BR><TABLE><TR><TD><FONT FACE="Verdana, Arial" SIZE=2><FONT SIZE="2" FACE="arial">
What changes are happening to EverQuest two years after it was released? Check out the patch message below from the big patch they did two days ago to see...
</FONT><BR>

<HR SIZE=2><BR>

<FONT FACE="verdana, arial" SIZE="1" COLOR="#FFFDCA">
March 14th, 3:00am<BR>
------------------------------<BR><BR>

<B>***EverQuest Turns Two***</B><BR><BR>

Two years ago this Friday, EverQuest was launched, forever changing the course of online gaming. Today EverQuest boasts nearly 360,000 active subscribers, and a two-year retention rate of 65%. Peak usage tops 89,000 simultaneous users with average peak usage at roughly 87,000. The EverQuest community continues to grow daily.<BR><BR>

We've put up a page on the EverQuest website to help celebrate EverQuest's achievement and to thank our loyal fans. Over the next couple of days we will be posting interesting content from EverQuest's humble beginnings, as well as a few surprises. Check it out! <A HREF="http://everquest.station.sony.com/2ndanniversary/index.jsp">[ link ]</A><BR><BR>

<B>*Ever Changing, Evolving, Expanding*</B><BR><BR>

<B>The Warrens:</B><BR><BR>

As part of our two-year celebration, we're pleased to announce the release of "The Warrens", a free expansion zone located on Odus. "The Warrens" is a low-to-mid level dungeon and the home of the Kobolds on Odus. You can patch the Warrens by running the "Optional Patch".<BR><BR>

In addition to filling-out the continent of Odus, "the Warrens" will also serve as a platform to try out some of the new ideas brought forth by members of the team and the public aimed at addressing some common gameplay issues. We would like to see what options might be open to and enjoyed by the players in the future.<BR><BR>

The first issue addressed in the Warrens is the problem of higher level characters competing with lower level characters for loot on lower level creatures. To address this issue, in the Warrens, a group that "outclasses" a particular foe will not receive any loot that is MAGIC, LORE, or NODROP. All other loot will drop. "Outclassing" a foe is defined as having a group makeup such that no one in your group receives experience from the kill. This can happen if, for instance, the foe is "green" to all group members, or if the group makeup is of such a wide level range that the system determines the fight was unbalanced using regular experience rules.<BR><BR>

Any time that an NPC would have dropped special loot and does not due to it being outclassed, a message indicating that the combat was "trivial" will be displayed to the group.<BR><BR>

As time goes on, we will be implementing new gameplay subsets and adjustements in the Warrens. Please be sure to let us know what you think!<BR><BR>

<B>The Planes:</B><BR><BR>

The Planes of Fear and Hate have been updated as part of our two-year celebration. Adventurers in the Plane of Fear will notice that some high-level foes are now available. Rewards for former "boss npcs" have been moved down to underlings that are roughly as powerful as the old bosses were.<BR><BR>

The Plane of Hate has also received a large update, but this one also includes the opening of a previously undiscovered part of the zone, now full high-level expansion-oriented content. Much as with Fear, rewards from bosses have been moved.<BR><BR>

<B>Epic Quests:</B><BR><BR>

As part of the Plane updates, we've made several adjustments to Epic quests for a number of classes. Previously, questers of many classes were put in direct competition with regular non-questing adventurers for a few coveted spawns. In these cases, a new step has been added to separate the "Epic Encounter" NPCs from the "Epic Quest" NPCs.<BR><BR>

For those who are mid-quest, all quest requirements have remained the same. In other words, if you turn the same items into the same NPC, the same reward applies. What has changed is that some components may be in a different location from where you expect them. It is recommended that you check with the last NPC in line or other adventurers to find where you need to go next.<BR><BR>

<B>***Patch Day***</B><BR><BR>

Along with the big announcements above, today was a patch day as well:<BR><BR>

- Fixed a bug that allowed exploitation of the period of time between character control being established and loading of character faction tables.<BR>
- Fixed the Dagger of Frost. Its special item flags were improperly removed in the last patch.<BR>
- The spell, Mark of Karn, has been enhanced to heal more per hit.<BR>
- The effect on the Celestial Elixir Breastplates has been changed to the enhanced Mark of Karn. The casting time on these items has also been changed to 9 seconds.<BR>
- NPCs in Thurgadin will no longer stop traveling when you /hail them.<BR>
- Fixed a problem present in Nagafen's Lair and the Plane of Hate that caused framerate to drop over time.<BR>
- Shift-clicking on a stack of items will cause you to pick up the whole stack. This is in addition to CTRL-clicking on a stack, which will cause you to pick up one. These both also work for coins now as well as items.<BR>
- In addition to the above, holding down the shift key while clicking the "Sell" button in the vendor screen will cause you to sell the entire stack of items if a stack is selected. For example, you can sell 20 peridots by selecting the stack, and shift-clicking "Sell". I'd recommend though that you give them to your neighborhood cleric first though :) The ability to buy stacks is on the list for implementation in the near future.<BR>
- There are a ton of new recipies for trade skill users out there. Check your books.<BR>
- There are a bunch of new quests as well.<BR>
- It appears that we fixed a bug with the Mend skill that caused it to be unavailable for a few seconds after it was supposed to be ready for use. Let us know if there are any further problems.<BR>
- Foraging items will now yield a message giving you some idea of what you've foraged.<BR><BR>

Please remember that the /movelog for the Rathe and E'ci is scheduled for this weekend. Please read the message below for details on the /movelog.<BR><BR>

<B>*A Message From Customer Service*</B><BR><BR>

We regularly receive requests from customers that want their characters moved from one server to another, or from one account to another. Unfortunately, due to the EverQuest EULA, the number of requests that we receive, the desire to maintain stable server communities and economies, and other problems associated with character moves, we can not move characters across servers or accounts.<BR><BR>

It is important for the integrity of the server that items from a server remain on that server. We also feel that it is important that characters that have built up a reputation, good or bad, have to live with the consequences of their decisions, and are not allowed to retreat from that reputation by changing servers.<BR><BR>

The only exception to this rule is when we open a Movelog for moving a large number of characters to new servers. At no other time will we move a character in such a fashion.<BR><BR>

- The EverQuest Team<BR><BR>
</FONT>

</FONT></TD></TR></TABLE></DIV>		</TD>
	</TR>
	</TABLE>
	<BR>
	</TD>
	<TD VALIGN="top">
	<TABLE CELLPADDING="3" CELLSPACING="3" WIDTH="250" VALIGN="top" BORDER="0">
	<TR>
		<TD VALIGN="top" bgcolor=#00001f>
			<P><CENTER><B>Images of Norrath</B></CENTER>
			<DIV ALIGN="center"><IMG SRC="http://www.loreseekers.com/screenshots/daily/tn_daily_image.jpg" BORDER=0 HSPACE=0><BR>
<FONT FACE="Verdana" COLOR="#00ffff" SIZE="-2">Some official EverQuest artwork<BR>
from 2 years ago.</FONT></DIV>
		</TD>
	</TR>
	
	<tr><td><BR></td></tr>
	
	<TR>
		<TD VALIGN="top" bgcolor=#00001f>
		<DIV ALIGN="center">
			<TABLE>
			<TR>
				<TD ROWSPAN="2"><IMG SRC="graphics/evervel.jpg" WIDTH=50 HEIGHT=60 ALT="" BORDER="0"></TD>
				<TD ALIGN="center"><FONT FACE="Verdana" SIZE="2"><B>Buy "the Scars of Velious" now!</B></FONT></TD>
			</TR>
			<TR>
				<TD ALIGN="center"><A HREF="http://www.dragon.ca/cgi-bin/affiliate.cgi?affid=LoreSeekersRB&id=EVERVEL" TARGET="_new"><IMG SRC="graphics/orderfrom.gif" ALIGN="Center" WIDTH ="120" HEIGHT ="26" ALT="Buy EverQuest Now!" BORDER="0"></A></TD>
			</TR>
			</TABLE>
		</DIV>
		</TD>
	</TR>
	
	<tr><td><BR></td></tr>
	
	<TR>
		<TD VALIGN="top" bgcolor=#00001f>
		<DIV ALIGN="center">
		<font size="-1"><b>Get an "@eqlore.com" address!</b><BR>
		<FONT COLOR="#ff0000" SIZE="-2"FACE="Verdana"> - New Feature!</FONT><BR>
		<BR>
		<table border="0" bordercolor="#000000" cellspacing="0" cellpadding="0" width="240">
		  <tr> 
		    <td valign="middle" align="center" nowrap height="25"> 
		      <table cellspacing="0" cellpadding="2" width="100%" border="0">
		        <form name="login_form" action="http://eqlore.mail.everyone.net/email/scripts/loginuser.pl" method="post">
		          <tr bgcolor="#00001F">
				  <td nowrap height="5"><font color="#FFFFFF" face="Verdana, Arial, Helvetica, sans-serif" size="2"><B>Email Login :</B></font></td><td><input type="text" name="loginName" size="12" maxlength="30"></td>
					</tr>
		          <tr bgcolor="#00001F"> 
		            <td height="2"><font color="#FFFFFF" face="Verdana, Arial, Helvetica, sans-serif" size="2"><B>Password :</B></font></td><td><input type="password" name="user_pwd" size="12" maxlength="30"></td>
		          </tr>
		          <tr bgcolor="#00001F">
				  	<td height="2" valign="bottom" align="right" COLSPAN="2"><input type="submit" name="login" value="Login">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
				  </tr>
				  <tr bgcolor="#00001F">
		            <td valign="middle" height="2" align="center" colspan="2"><font face="Verdana, Arial, Helvetica, sans-serif" color="#FFFFFF" size="2">New  users <a href="http://eqlore.mail.everyone.net/email/scripts/useragreement.pl"><b>sign up</a> now !</b></font></td>
		          </tr>
		        </form>
		      </table>
		    </td>
		  </tr>
		</table>
		<BR>
		</DIV>
		</TD>
	</TR>
	
	<tr><td><BR></td></tr>	
	
	<TR>
	<TD VALIGN="top" bgcolor=#00001f>
	<A NAME="1.0 Poll">
	<FONT SIZE="-1">
	<TABLE width=100%><TR><TD bgcolor=#00001f><div align="center"><B><font size="+1">V</font>ote :</B></div><BR><div align="center"><b><font size="-1">Were you playing EQ on the very first day, 2 years ago?</font></b></div><table><form action="http://www.loreseekers.com/vote.php3" method="post"><input type="hidden" name="poll_id" value="1"><input type="hidden" name="poll_forwarder" value="http://www.loreseekers.com/main.phtml"><tr><td><input type="radio" name="poll_voteNr" value="1"checked > <font size="-1"><b>Yes</b></font> </td></tr><tr><td><input type="radio" name="poll_voteNr" value="2"> <font size="-1"><b>No</b></font> </td></tr></table><div align="center"><input type="submit" value="Vote"></div></form></TD></TR></TABLE>	</FONT>
	</TD>
	</TR>

	<tr><td><BR></td></tr>
	
	<TR>
   		<TD bgcolor=#00001f>
		<CENTER><B>Featured Article</B> :<BR>
		<BR><FONT FACE="verdana, arial" COLOR="#FFFF00" SIZE=2><B>EverQuest: A Unique Phenomenon</B></FONT></CENTER>
<FONT FACE="verdana, arial" SIZE="2" COLOR="#FFFDCA">
<P><FONT SIZE="+1"><B>I</B></FONT>t was almost 2 and a half years ago that I was born again.<BR><BR>

Born again not in the religious sense, but in the sense that I became the incarnation of all my childhood fantasies. I became a Wizard!<BR><BR>

The date was November 19th, 1998 when I opened up an email to be greeted with the following...<BR><BR>

"<I>Greetings! You have been selected to be one of our testers in
our Phase III test of EverQuest.</I>"<BR><BR>
Read the rest of this article <A HREF="/stories/unique.phtml">Here.</A></FONT>		</TD>
	</TR>
	
<tr><td><BR></td></tr>
	
	<TR>
		<TD VALIGN="top" bgcolor=#00001f>
		<font size="-1"><b><font size="+1">D</font>o you want to share your lore ?<BR><font size="+1">C</font>heck our messageboards :</b><BR>
		<BR>
		<A HREF="http://www.loreseekers.com/phorum306/list.php3?num=4"><b>The Quest Forum</b></a><BR>
		<BR>
		<A HREF="http://www.loreseekers.com/phorum306/list.php3?num=3"><b>The Bazaar</b></a><BR>
		<BR>
		<A HREF="http://www.loreseekers.com/phorum306/list.php3?num=2"><b>The Roleplaying Forum</b></a><BR>
		<BR>
		<A HREF="http://www.loreseekers.com/phorum306/list.php3?num=1"><b>The Guild Forum</b></a><BR>
		<BR></font>	
		</TD>
	</TR>	
	
	</TABLE>
	</TD>
</TR>
	
	
</TABLE>

<HR WIDTH="98%">
<DIV ALIGN="center"><FONT SIZE="-2">
	<A HREF="http://www.renaissance.nl/copyright.html" TARGET="_new">Copyright</A> 1999 , 2000 <A HREF="http://www.renaissance.nl/english/" TARGET="_new">Renaissance IT</A>, All Rights Reserved.<BR>
</FONT></DIV>
<HR WIDTH="98%">

</FONT>
</DIV>
</BODY>
</HTML>
