



































<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
	<title>Create account</title>
	<link rel="stylesheet" type="text/css" href="./style/magelo.css">
</head>
<body onload="if(typeof(document.register.username)!='undefined') document.register.username.focus();">

<br>
<table align="center" width="96%" cellpadding="0" cellspacing="0">
<tr><td width="*" rowspan="2" colspan="2">
<table width="100%" align="center" border="1" bordercolor="#29455A" cellpadding="0" cellspacing="0">
<tr><td><table cellpadding="0" cellspacing="0" width="100%">
<tr>
	<td background="img/title_bg0.gif" height="15px" class="title">
		&nbsp;Register
	</td>
</tr>
<tr><td class="cadre-bg"><table width="100%">
<tr>
	<td class="text2">
	
		<form name="register" method="post" action="create_account.jsp;jsessionid=DOIPDFLMOLCN">
		<table width="98%" align="center" border="0">
		
		<tr>
			<td class="text">
				<br>
				Enter your desired username<br>
				<input class="input" type="text" name="username" size="20" maxlength="20" value="">
				
				<br><br>
				Enter your desired password <br>
				<input class="input" type="password" name="pass1" size="20" maxlength="20">
				
				<br>
				Confirm your password<br>
				<input class="input" type="password" name="pass2" size="20" maxlength="20"><br><br>
				
				Enter your email address. (Account activation procedure will be sent there)<br>
				<input class="input" type="text" name="email" size="30" maxlength="50" value="">
				
				<br>
				Enter your ICQ number (ICQ is an instant messenger like AIM/MSN, ignore this field if you dont use ICQ) <br>
				<input class="input" type="text" name="icq" size="12" maxlength="15" value="">
				
				<br><br>
				Pick your Timezone&nbsp;
				<select class='input' name='timezone'>
<option 
>Africa/Abidjan
<option 
>Africa/Accra
<option 
>Africa/Addis_Ababa
<option 
>Africa/Algiers
<option 
>Africa/Asmera
<option 
>Africa/Bamako
<option 
>Africa/Bangui
<option 
>Africa/Banjul
<option 
>Africa/Bissau
<option 
>Africa/Blantyre
<option 
>Africa/Brazzaville
<option 
>Africa/Bujumbura
<option 
>Africa/Cairo
<option 
>Africa/Casablanca
<option 
>Africa/Ceuta
<option 
>Africa/Conakry
<option 
>Africa/Dakar
<option 
>Africa/Dar_es_Salaam
<option 
>Africa/Djibouti
<option 
>Africa/Douala
<option 
>Africa/El_Aaiun
<option 
>Africa/Freetown
<option 
>Africa/Gaborone
<option 
>Africa/Harare
<option 
>Africa/Johannesburg
<option 
>Africa/Kampala
<option 
>Africa/Khartoum
<option 
>Africa/Kigali
<option 
>Africa/Kinshasa
<option 
>Africa/Lagos
<option 
>Africa/Libreville
<option 
>Africa/Lome
<option 
>Africa/Luanda
<option 
>Africa/Lubumbashi
<option 
>Africa/Lusaka
<option 
>Africa/Malabo
<option 
>Africa/Maputo
<option 
>Africa/Maseru
<option 
>Africa/Mbabane
<option 
>Africa/Mogadishu
<option 
>Africa/Monrovia
<option 
>Africa/Nairobi
<option 
>Africa/Ndjamena
<option 
>Africa/Niamey
<option 
>Africa/Nouakchott
<option 
>Africa/Ouagadougou
<option 
>Africa/Porto-Novo
<option 
>Africa/Sao_Tome
<option 
>Africa/Timbuktu
<option 
>Africa/Tripoli
<option 
>Africa/Tunis
<option 
>Africa/Windhoek
<option 
>America/Adak
<option 
>America/Anchorage
<option 
>America/Anguilla
<option 
>America/Antigua
<option 
>America/Araguaina
<option 
>America/Aruba
<option 
>America/Asuncion
<option 
>America/Atka
<option 
>America/Barbados
<option 
>America/Belem
<option 
>America/Belize
<option 
>America/Boa_Vista
<option 
>America/Bogota
<option 
>America/Boise
<option 
>America/Buenos_Aires
<option 
>America/Cambridge_Bay
<option 
>America/Cancun
<option 
>America/Caracas
<option 
>America/Catamarca
<option 
>America/Cayenne
<option 
>America/Cayman
<option 
>America/Chicago
<option 
>America/Chihuahua
<option 
>America/Cordoba
<option 
>America/Costa_Rica
<option 
>America/Cuiaba
<option 
>America/Curacao
<option 
>America/Danmarkshavn
<option 
>America/Dawson
<option 
>America/Dawson_Creek
<option 
>America/Denver
<option 
>America/Detroit
<option 
>America/Dominica
<option 
>America/Edmonton
<option 
>America/Eirunepe
<option 
>America/El_Salvador
<option 
>America/Ensenada
<option 
>America/Fort_Wayne
<option 
>America/Fortaleza
<option 
>America/Glace_Bay
<option 
>America/Godthab
<option 
>America/Goose_Bay
<option 
>America/Grand_Turk
<option 
>America/Grenada
<option 
>America/Guadeloupe
<option 
>America/Guatemala
<option 
>America/Guayaquil
<option 
>America/Guyana
<option 
>America/Halifax
<option 
>America/Havana
<option 
>America/Hermosillo
<option 
>America/Indiana/Indianapolis
<option 
>America/Indiana/Knox
<option 
>America/Indiana/Marengo
<option 
>America/Indiana/Vevay
<option 
>America/Indianapolis
<option 
>America/Inuvik
<option 
>America/Iqaluit
<option 
>America/Jamaica
<option 
>America/Jujuy
<option 
>America/Juneau
<option 
>America/Kentucky/Louisville
<option 
>America/Kentucky/Monticello
<option 
>America/Knox_IN
<option 
>America/La_Paz
<option 
>America/Lima
<option 
>America/Los_Angeles
<option 
>America/Louisville
<option 
>America/Maceio
<option 
>America/Managua
<option 
>America/Manaus
<option 
>America/Martinique
<option 
>America/Mazatlan
<option 
>America/Mendoza
<option 
>America/Menominee
<option 
>America/Merida
<option 
>America/Mexico_City
<option 
>America/Miquelon
<option 
>America/Monterrey
<option 
>America/Montevideo
<option 
>America/Montreal
<option 
>America/Montserrat
<option 
>America/Nassau
<option 
>America/New_York
<option 
>America/Nipigon
<option 
>America/Nome
<option 
>America/Noronha
<option 
>America/North_Dakota/Center
<option 
>America/Panama
<option 
>America/Pangnirtung
<option 
>America/Paramaribo
<option 
>America/Phoenix
<option 
>America/Port-au-Prince
<option 
>America/Port_of_Spain
<option 
>America/Porto_Acre
<option 
>America/Porto_Velho
<option 
>America/Puerto_Rico
<option 
>America/Rainy_River
<option 
>America/Rankin_Inlet
<option 
>America/Recife
<option 
>America/Regina
<option 
>America/Rio_Branco
<option 
>America/Rosario
<option 
>America/Santiago
<option 
>America/Santo_Domingo
<option 
>America/Sao_Paulo
<option 
>America/Scoresbysund
<option 
>America/Shiprock
<option 
>America/St_Johns
<option 
>America/St_Kitts
<option 
>America/St_Lucia
<option 
>America/St_Thomas
<option 
>America/St_Vincent
<option 
>America/Swift_Current
<option 
>America/Tegucigalpa
<option 
>America/Thule
<option 
>America/Thunder_Bay
<option 
>America/Tijuana
<option 
>America/Tortola
<option 
>America/Vancouver
<option 
>America/Virgin
<option 
>America/Whitehorse
<option 
>America/Winnipeg
<option 
>America/Yakutat
<option 
>America/Yellowknife
<option 
>Antarctica/Casey
<option 
>Antarctica/Davis
<option 
>Antarctica/DumontDUrville
<option 
>Antarctica/Mawson
<option 
>Antarctica/McMurdo
<option 
>Antarctica/Palmer
<option 
>Antarctica/South_Pole
<option 
>Antarctica/Syowa
<option 
>Antarctica/Vostok
<option 
>Arctic/Longyearbyen
<option 
>Asia/Aden
<option 
>Asia/Almaty
<option 
>Asia/Amman
<option 
>Asia/Anadyr
<option 
>Asia/Aqtau
<option 
>Asia/Aqtobe
<option 
>Asia/Ashgabat
<option 
>Asia/Ashkhabad
<option 
>Asia/Baghdad
<option 
>Asia/Bahrain
<option 
>Asia/Baku
<option 
>Asia/Bangkok
<option 
>Asia/Beirut
<option 
>Asia/Bishkek
<option 
>Asia/Brunei
<option 
>Asia/Calcutta
<option 
>Asia/Choibalsan
<option 
>Asia/Chongqing
<option 
>Asia/Chungking
<option 
>Asia/Colombo
<option 
>Asia/Dacca
<option 
>Asia/Damascus
<option 
>Asia/Dhaka
<option 
>Asia/Dili
<option 
>Asia/Dubai
<option 
>Asia/Dushanbe
<option 
>Asia/Gaza
<option 
>Asia/Harbin
<option 
>Asia/Hong_Kong
<option 
>Asia/Hovd
<option 
>Asia/Irkutsk
<option 
>Asia/Istanbul
<option 
>Asia/Jakarta
<option 
>Asia/Jayapura
<option 
>Asia/Jerusalem
<option 
>Asia/Kabul
<option 
>Asia/Kamchatka
<option 
>Asia/Karachi
<option 
>Asia/Kashgar
<option 
>Asia/Katmandu
<option 
>Asia/Krasnoyarsk
<option 
>Asia/Kuala_Lumpur
<option 
>Asia/Kuching
<option 
>Asia/Kuwait
<option 
>Asia/Macao
<option 
>Asia/Macau
<option 
>Asia/Magadan
<option 
>Asia/Makassar
<option 
>Asia/Manila
<option 
>Asia/Muscat
<option 
>Asia/Nicosia
<option 
>Asia/Novosibirsk
<option 
>Asia/Omsk
<option 
>Asia/Oral
<option 
>Asia/Phnom_Penh
<option 
>Asia/Pontianak
<option 
>Asia/Pyongyang
<option 
>Asia/Qatar
<option 
>Asia/Qyzylorda
<option 
>Asia/Rangoon
<option 
>Asia/Riyadh
<option 
>Asia/Riyadh87
<option 
>Asia/Riyadh88
<option 
>Asia/Riyadh89
<option 
>Asia/Saigon
<option 
>Asia/Sakhalin
<option 
>Asia/Samarkand
<option 
>Asia/Seoul
<option 
>Asia/Shanghai
<option 
>Asia/Singapore
<option 
>Asia/Taipei
<option 
>Asia/Tashkent
<option 
>Asia/Tbilisi
<option 
>Asia/Tehran
<option 
>Asia/Tel_Aviv
<option 
>Asia/Thimbu
<option 
>Asia/Thimphu
<option 
>Asia/Tokyo
<option 
>Asia/Ujung_Pandang
<option 
>Asia/Ulaanbaatar
<option 
>Asia/Ulan_Bator
<option 
>Asia/Urumqi
<option 
>Asia/Vientiane
<option 
>Asia/Vladivostok
<option 
>Asia/Yakutsk
<option 
>Asia/Yekaterinburg
<option 
>Asia/Yerevan
<option 
>Atlantic/Azores
<option 
>Atlantic/Bermuda
<option 
>Atlantic/Canary
<option 
>Atlantic/Cape_Verde
<option 
>Atlantic/Faeroe
<option 
>Atlantic/Jan_Mayen
<option 
>Atlantic/Madeira
<option 
>Atlantic/Reykjavik
<option 
>Atlantic/South_Georgia
<option 
>Atlantic/St_Helena
<option 
>Atlantic/Stanley
<option 
>Australia/ACT
<option 
>Australia/Adelaide
<option 
>Australia/Brisbane
<option 
>Australia/Broken_Hill
<option 
>Australia/Canberra
<option 
>Australia/Darwin
<option 
>Australia/Hobart
<option 
>Australia/LHI
<option 
>Australia/Lindeman
<option 
>Australia/Lord_Howe
<option 
>Australia/Melbourne
<option 
>Australia/NSW
<option 
>Australia/North
<option 
>Australia/Perth
<option 
>Australia/Queensland
<option 
>Australia/South
<option 
>Australia/Sydney
<option 
>Australia/Tasmania
<option 
>Australia/Victoria
<option 
>Australia/West
<option 
>Australia/Yancowinna
<option 
>Brazil/Acre
<option 
>Brazil/DeNoronha
<option 
>Brazil/East
<option 
>Brazil/West
<option 
>Canada/Atlantic
<option 
>Canada/Central
<option 
>Canada/East-Saskatchewan
<option 
>Canada/Eastern
<option 
>Canada/Mountain
<option 
>Canada/Newfoundland
<option 
>Canada/Pacific
<option 
>Canada/Saskatchewan
<option 
>Canada/Yukon
<option 
>Chile/Continental
<option 
>Chile/EasterIsland
<option 
>Cuba
<option 
>Egypt
<option 
>Eire
<option 
>Europe/Amsterdam
<option 
>Europe/Andorra
<option 
>Europe/Athens
<option 
>Europe/Belfast
<option 
>Europe/Belgrade
<option 
>Europe/Berlin
<option 
>Europe/Bratislava
<option 
>Europe/Brussels
<option 
>Europe/Bucharest
<option 
>Europe/Budapest
<option 
>Europe/Chisinau
<option 
>Europe/Copenhagen
<option 
>Europe/Dublin
<option 
>Europe/Gibraltar
<option 
>Europe/Helsinki
<option 
>Europe/Istanbul
<option 
>Europe/Kaliningrad
<option 
>Europe/Kiev
<option 
>Europe/Lisbon
<option 
>Europe/Ljubljana
<option 
>Europe/London
<option 
>Europe/Luxembourg
<option 
>Europe/Madrid
<option 
>Europe/Malta
<option 
>Europe/Minsk
<option 
>Europe/Monaco
<option 
>Europe/Moscow
<option 
>Europe/Nicosia
<option 
>Europe/Oslo
<option 
>Europe/Paris
<option 
>Europe/Prague
<option 
>Europe/Riga
<option 
>Europe/Rome
<option 
>Europe/Samara
<option 
>Europe/San_Marino
<option 
>Europe/Sarajevo
<option 
>Europe/Simferopol
<option 
>Europe/Skopje
<option 
>Europe/Sofia
<option 
>Europe/Stockholm
<option 
>Europe/Tallinn
<option 
>Europe/Tirane
<option 
>Europe/Tiraspol
<option 
>Europe/Uzhgorod
<option 
>Europe/Vaduz
<option 
>Europe/Vatican
<option 
>Europe/Vienna
<option 
>Europe/Vilnius
<option 
>Europe/Warsaw
<option 
>Europe/Zagreb
<option 
>Europe/Zaporozhye
<option 
>Europe/Zurich
<option 
>Greenwich
<option 
>Hongkong
<option 
>Iceland
<option 
>Indian/Antananarivo
<option 
>Indian/Chagos
<option 
>Indian/Christmas
<option 
>Indian/Cocos
<option 
>Indian/Comoro
<option 
>Indian/Kerguelen
<option 
>Indian/Mahe
<option 
>Indian/Maldives
<option 
>Indian/Mauritius
<option 
>Indian/Mayotte
<option 
>Indian/Reunion
<option 
>Iran
<option 
>Israel
<option 
>Jamaica
<option 
>Japan
<option 
>Kwajalein
<option 
>Libya
<option 
>Mexico/BajaNorte
<option 
>Mexico/BajaSur
<option 
>Mexico/General
<option 
>Mideast/Riyadh87
<option 
>Mideast/Riyadh88
<option 
>Mideast/Riyadh89
<option 
>Navajo
<option 
>Pacific/Apia
<option 
>Pacific/Auckland
<option 
>Pacific/Chatham
<option 
>Pacific/Easter
<option 
>Pacific/Efate
<option 
>Pacific/Enderbury
<option 
>Pacific/Fakaofo
<option 
>Pacific/Fiji
<option 
>Pacific/Funafuti
<option 
>Pacific/Galapagos
<option 
>Pacific/Gambier
<option 
>Pacific/Guadalcanal
<option 
>Pacific/Guam
<option 
>Pacific/Honolulu
<option 
>Pacific/Johnston
<option 
>Pacific/Kiritimati
<option 
>Pacific/Kosrae
<option 
>Pacific/Kwajalein
<option 
>Pacific/Majuro
<option 
>Pacific/Marquesas
<option 
>Pacific/Midway
<option 
>Pacific/Nauru
<option 
>Pacific/Niue
<option 
>Pacific/Norfolk
<option 
>Pacific/Noumea
<option 
>Pacific/Pago_Pago
<option 
>Pacific/Palau
<option 
>Pacific/Pitcairn
<option 
>Pacific/Ponape
<option 
>Pacific/Port_Moresby
<option 
>Pacific/Rarotonga
<option 
>Pacific/Saipan
<option 
>Pacific/Samoa
<option 
>Pacific/Tahiti
<option 
>Pacific/Tarawa
<option 
>Pacific/Tongatapu
<option 
>Pacific/Truk
<option 
>Pacific/Wake
<option 
>Pacific/Wallis
<option 
>Pacific/Yap
<option 
>Poland
<option 
>Portugal
<option 
>Singapore
<option 
>Turkey
<option 
>Universal
<option 
>Zulu
</select>
			
					<br><br>
					Clock System <select class="input" class="input" name="am_pm"><option value="true" >12 hours<option value="false" >24 hours</select><br><br>
				</td>
			</tr>
			<tr>
				<td align="center">
					<br>
					<input type="image" src="img/create_account_off.gif" border="0" alt="Create account" onmouseover="this.src='img/create_account_on.gif'" onmouseout="this.src='img/create_account_off.gif'">
					
				</td>
			</tr>
			
		</table>
		</form>
		
		
		
	</td>
</tr></table></td></tr></table></td></tr></table>
</td><td width="6" height="8" background="img/right_shadow.gif" valign="top"><img src="img/top_right_shadow.gif" width="6" height="8"></td></tr>
<tr><td width="6" height="100%" background="img/right_shadow.gif"></td></tr>
<tr>
	<td width="6" height="8" background="img/bottom_shadow.gif"><img src="img/bottom_left_shadow.gif" width="6" height="8"></td>
	<td width="*" height="8" background="img/bottom_shadow.gif"><img src="img/bottom_shadow.gif" width="6" height="8"></td>
	<td width="6" height="8" background="img/bottom_shadow.gif"><img src="img/bottom_right_shadow.gif" width="6" height="8"></td>
</tr>	
</table>

</body>
</html>