<!--
                 This page has been created by Renaissance IT
   Renaissance Internet Technologies Copyright (c) 1999 All Rights Reserved.

             for more info on our products, please visit :
                        http://www.renaissance.nl/

	This script has been written by Roy Boverhof <rboverhof@renaissance.nl>
	
        Pagename                : cazic.html
        Last Updated    		: 29-02-2000
-->

<HTML>
<HEAD>
	<TITLE>the Seekers of Lore : Battle at Cazic Thule</TITLE>
</HEAD>

<BODY BGCOLOR="#000000" TEXT="#000000" LINK="#000000" VLINK="#000000" ALINK="#000000">
<DIV ALIGN="CENTER">
<BR>
<!-- FGN Banner Code -->
<script language="JavaScript">
	<!-- Hide from old browsers
	var random = new Number(Math.floor(9999999 * Math.random())+1);

	// Modify to reflect site specifics
	page = "eqlore.com/";
	target = "@Top1,x02,x05,x08!Top1";

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript1.1" SRC="http://oascentral.cybereps.com/RealMedia/ads/adstream_jx.ads/' + page + 1 + random + target + '">');
	document.write('</SCR');
	document.write('IPT>');

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript">');
	document.write('_version=10; //-->');
	document.write('</SCR');
	document.write('IPT>');

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript1.1">');
	document.write('_version=11; //-->');
	document.write('</SCR');
	document.write('IPT>');

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript">');

	if (navigator.appVersion.indexOf('MSIE 3') != -1){
	document.write('<IFRAME MARGINWIDTH=0 MARGINHEIGHT=0 HSPACE=0 VSPACE=0 FRAMEBORDER=0 SCROLLING=no BORDERCOLOR="#000000" SRC="oascentral.cybereps.com/RealMedia/ads/adstream_sx.ads/' + page + random + target + '"></IFRAME>');
	  }
	else if (_version < 11) {
	document.write ('<A HREF="http://oascentral.cybereps.com/RealMedia/ads/click_nx.ads/' + page + random + target + '"><IMG SRC="http://oascentral.cybereps.com/RealMedia/ads/adstream_nx.ads/' + page + random + target + '"></a>');
	  }

	document.write('</SCR');
	document.write('IPT>');

	// End Hide -->
</script>
<!-- END FGN Banner Code --><BR>
<TABLE CELLSPACING = 0 CELLPADDING = 0 BORDER = 0>
<TR>
	<TD width="63"><IMG SRC = "../graphics/topc000.jpg" WIDTH = 63 HEIGHT = 87></TD>
	<TD width="473"><IMG SRC = "../graphics/topc001.jpg" WIDTH = 473 HEIGHT = 87></TD>
	<TD width="64"><IMG SRC = "../graphics/topc002.jpg" WIDTH = 64 HEIGHT = 87></TD>
</TR>
	<TD width="63"></TD>
	<TD BGCOLOR="#BEA279" width="460">
	<DIV ALIGN="CENTER">
	<TABLE>
	<TR>

	<TD BGCOLOR="#BEA279" width="400">

	<FONT FACE="Times New Roman" SIZE="+2">
	<P><BR><CENTER><B><I>Battle at Cazic~Thule </I></B></CENTER></FONT>

	<FONT SIZE="-1">
		
	<P><FONT SIZE="+1"><B>N</B></FONT>alfein wiped the sweat off his ink colored brow. It was hot, thought the dark elf Shadow Knight, even for the murky jungle of the Feerrott. At his side was the battle hardened dwarven cleric of Brell, Grundrikt. Together they stood before the vast Lost Temple of Cazic Thule. The two Seekers had journeyed here with the rumors of treasure and glory on their minds. Far had they come, across the vast Desert of Ro they had trekked, waded through the Innothule swamp, and cut and swam their way through the Feerrott.

	<P><FONT SIZE="+1"><B>G</B></FONT>rundrikt grunted and swore, as yet another jungle spider ran from out of the forest and startled them both. Giving each other a look, they walked up the large stone ramp and entered the tunnel. This twisted and turned, only to reveal a large set of doors, guarded by two bipedal lizards, Lizardmen, the Ogres of Oggok, called them. Men, Nalfein snorted in disgust. These beings would meet Innoruuk along with the rest they had left outside the temple. Grundrikt brandished his mace, and Nalfein drew Dark Reaver from the scabbard on his back. The black blade gleamed with the moisture upon it. Grundrikt cast a spell to stun the guards, and with a flash of a blade and the crunching sound of mace upon a skull, the guards had been dispatched.

	<P><FONT SIZE="+1"><B>C</B></FONT>arefully opening the doors, they came upon a vast courtyard, set into the temple complex, a pyramid off in the distance, and several doors off to the side. Two more lizards stood as guards above the yard, in front of the pyramid. Nalfein put his sword aside, and drew forth his bow and arrows. If he timed it right, he could fell both quickly.  Grundrikt called upon his god to aid Nalfein and himself in combat. Away went the first arrow, and then the second. The first went down with ease, but the second arrow stopped short, in mid air. <I>"Damn, a caster"</I>, Grundrikt said. Upon which lightning shot across the distance to strike them down.

	<P><FONT SIZE="+1"><B>N</B></FONT>alfein stood, picked up Dark Reaver, and called upon his dark god. Darkness flowed forth from his hands to engulf the lizardman caster. By the time the dazed lizard could recover, Nalfein was there to greet him personally.

	<P><I>"Now what?"</I> Grundrikt asked.

	<P><I>"We go in, and send the rest of these devil spawned beings to their maker."</I>

	<P><FONT SIZE="+1"><B>T</B></FONT>he entrance to the pyramid proved to be a fool's errand, as it only twisted and turned to come back out into the courtyard. Trying the door off to the right, Nalfein found a maze of passages. Three steps into the maze, Nalfein hissed, <I>"Fall back, trap."</I>

	<P><FONT SIZE="+1"><B>N</B></FONT>ot two seconds later, lizardmen poured out of the maze. <I>"To the tunnel, we cannot be outflanked!"</I> Grundrikt yelled. 

	<P><FONT SIZE="+1"><B>T</B></FONT>hey fell back to the entrance tunnel, and prepared to make a stand. The lizardmen charged with reckless abandon. Nalfein cut them down, one after the other, while Grundrikt sent waves of magical fear to chase off as many as possible. Alas, the lizardmen horde seemed endless. Nalfein was beginning to tire, and Grundrikt, exhausted from casting, had collapsed to the ground. Nalfein prepared to face his god for the final journey.

	<P><FONT SIZE="+1"><B>S</B></FONT>uddenly there was a loud clap, and the lizardmen just stood there.  Nalfein turned to see a gnome clad in robes, a paladin in shining armor, and a towering barbarian rogue behind them. Saved, Nalfein thought. An enchanter to mesmerize the enemy, and a warrior to dispatch the remaining enemies. How they too had come to this place, Nalfein cared not, but he reached down and helped Grundrikt to his feet. A quick rest, healing provided by Nalfein draining the lifeforce from a lizardman, and few quick words of introduction, and now they would work together. The barbarian had a map of the place.  To the left was the throne room, and beyond that stood the true riches of Cazic Thule.  What dangers lay between them, they would find out together, and gods willing, prove able to overcome.

	<P><FONT SIZE="+1"><I>Nalfein T'sarran, House Auvryndar</I></FONT><BR><FONT SIZE="2" FACE="ariel">Bertoxxulous Server</FONT><BR><BR>

	</FONT>

	</TD>
	</TR>
	</TABLE>
<TABLE>
<TR>
<TD><A HREF="http://www.loreseekers.com/tales.phtml"><IMG SRC="http://www.loreseekers.com/graphics/tales_return_link.jpg" WIDTH=200 HEIGHT=75 ALT="Read some other stories by our members!" BORDER="0"></A></TD>
</TR>
</TABLE>

	<TD width="64"></TD>
<TR>
	<TD><IMG SRC = "../graphics/botc000.jpg" WIDTH = 63 HEIGHT = 87></TD>
	<TD><IMG SRC = "../graphics/botc001.jpg" WIDTH = 473 HEIGHT = 87></TD>
	<TD><IMG SRC = "../graphics/botc002.jpg" WIDTH = 64 HEIGHT = 87></TD>
</TR>
</TABLE>
<BR>
<IMG SRC="http://service.bfast.com/bfast/serve?bfmid=1375281&siteid=40292692&bfpage=pc" BORDER="0" WIDTH="1" HEIGHT="1" NOSAVE ><A HREF="http://service.bfast.com/bfast/click?bfmid=1375281&siteid=40292692&bfpage=pc" TARGET="_new"><IMG SRC="http://affiliate.gamestop.com/affIMG/pc_120x60.gif" BORDER="0" WIDTH="120" HEIGHT="60" ALT="PC Games at GameStop.com"></A>
<BR>
<BR>
</DIV>
</BODY>
</HTML>