<!-- WARNING!  DO NOT EDIT THIS FILE BY HAND OR USING AN HTML EDITOR! -->
<HTML>
<HEAD>
<TITLE>Keyword Search</TITLE>
<SCRIPT LANGUAGE="JavaScript">
<!-- ;
function setStatus(msg) {
  window.status = msg;
  return true;
}
function initpage () {
  window.defaultStatus = "Keyword Search"
  if (document.userpass) {
    if (document.userpass.username) {
      if (document.userpass.username.value == "") {
        document.userpass.username.value = readcookie("user")
      }
    }
    if (document.userpass.passwd) {
      if (document.userpass.passwd.value == "") {
        document.userpass.passwd.value = readcookie("rpwd")
      }
    }
  }
}function readcookie(name) {
  var i = 0; var lookfor = name + "="
  while (i < document.cookie.length) {
    var j = i + lookfor.length
    if (document.cookie.substring(i,j) == lookfor) {
      var endstr = document.cookie.indexOf(";", j)
      if (endstr == -1) {
        endstr = document.cookie.length
      }
      return unescape(document.cookie.substring(j, endstr))
    }
    i = document.cookie.indexOf(" ", i) + 1
    if (i == 0) {
      break
    }
  }
  return ""
}
// end hide -->
</SCRIPT>
</HEAD>
<BODY BGCOLOR="#eeeeee" TEXT="#000000" LINK="#0000ff" VLINK="#800080" ALINK="#ff0000" BACKGROUND="http://www.eq-continuum.com/images/lebkgnd.jpg" onLoad="initpage()">
<BASEFONT SIZE="2"><FONT FACE="Verdana,Arial,Helvetica">
<A NAME="">
<a name=MT>
<FONT SIZE=+1><CENTER><B>Keyword Search</B></CENTER></FONT>
<HR>
<FORM ACTION="http://www.eq-continuum.com/cgi-bin/board-search.cgi" METHOD=POST>
<INPUT TYPE=HIDDEN NAME=charset_disp VALUE="">
To search the board, enter one or more words below.  Placing a <B>+</B> sign in front of a word <I>requires</I> the word.  Placing a <B>-</B> sign in front of a word <I>excludes</I> the word.  Placing a &quot;phrase in quotes&quot; matches the entire phrase.<P>
<TABLE>
<TR>
<TD><FONT FACE="Verdana,Arial,Helvetica" SIZE="2"><B>Search for:</B></FONT></TD>
<TD><INPUT SIZE=35 NAME=query TYPE=TEXT></TD>
</TR>
<TR>
<TD><FONT FACE="Verdana,Arial,Helvetica" SIZE="2"><B>Search topic:</B></FONT></TD>
<TD><SELECT NAME=searchwhere >
<OPTION VALUE=ALL>All topics on board
<OPTION VALUE="1">General Discussion
<OPTION VALUE="2">Guild Members Only
<OPTION VALUE="50">Archives
</SELECT></TD></TR>
<TR>
<TD><FONT FACE="Verdana,Arial,Helvetica" SIZE="2"><B>Look in:</B></FONT></TD>
<TD><SELECT SIZE=1 NAME=lookin>
<OPTION VALUE=1>Subject lines
<OPTION VALUE=2>Names of authors
<OPTION VALUE=3 SELECTED>Text of messages
</SELECT></TD>
</TR>
<TR>
<TD><FONT FACE="Verdana,Arial,Helvetica" SIZE="2"><B>Type of page:</B></FONT></TD>
<TD><SELECT SIZE=1 NAME=typepage>
<OPTION VALUE=1>Pages containing messages
<OPTION VALUE=3>Pages with or without messages
</SELECT></TD>
</TR>
</TABLE>
<P>
<INPUT TYPE=SUBMIT VALUE="Perform Search"></FORM>
<FONT SIZE=1><B></B></FONT>
</FONT>
<P>
<P>
</BODY>
</HTML>
