<!--
                 This page has been created by Renaissance IT
   Renaissance Internet Technologies Copyright (c) 1999 All Rights Reserved.

             for more info on our products, please visit :
                        http://www.renaissance.nl/

	This script has been written by Roy Boverhof <rboverhof@renaissance.nl>
	
        Pagename                : links3.html
        Last Updated    		: 03-16-2001
-->

<HTML>
<HEAD>
	<TITLE>the Seekers of Lore : Forums and Discussion Boards</TITLE>
</HEAD>

<BODY BGCOLOR="#000000" TEXT="#000000" LINK="#BEA279" VLINK="#BEA279">
<DIV ALIGN="CENTER">
<BR>
<script type="text/javascript"><!--
google_ad_client = "pub-0988179937943699";
google_ad_width = 468;
google_ad_height = 60;
google_ad_format = "468x60_as";
google_ad_channel ="7352298734";
google_page_url = document.location;
google_color_border = "FFFFFF";
google_color_bg = "00001F";
google_color_link = "FFFFFF";
google_color_url = "FFF000";
google_color_text = "0000FF";
//--></script>
<script type="text/javascript"
  src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
</script><BR>
<TABLE CELLSPACING = 0 CELLPADDING = 0 BORDER = 0>
<TR>
	<TD width="63"><IMG SRC = "graphics/topc000.jpg" WIDTH = 63 HEIGHT = 87></TD>
	<TD width="473"><IMG SRC = "graphics/topc001.jpg" WIDTH = 473 HEIGHT = 87></TD>
	<TD width="64"><IMG SRC = "graphics/topc002.jpg" WIDTH = 64 HEIGHT = 87></TD>
</TR>
	<TD width="63"></TD>
	<TD BGCOLOR="#BEA279" width="460">
	<DIV ALIGN="CENTER">
	<A HREF="links.phtml"><IMG SRC="graphics/linkheader.jpg" WIDTH ="200" HEIGHT ="75" ALT="Back to Links Index"></A>
	<TABLE WIDTH=440 ALIGN="center">
	<TR><TD></TD></TR>
	<TR>
		<TD>
		<A HREF="http://pub6.ezboard.com/bthemagicianstower.html" TARGET="_new"><IMG SRC="graphics/magicians_tower_link.jpg" WIDTH ="220" HEIGHT ="75"></A>
		</TD>
		<TD><FONT FACE="Verdana" SIZE="-2">An 'ezboard' forum for the magicians out there.</FONT></TD>
	</TR>
	<TR>
		<TD>
		<A HREF="http://boards.station.sony.com/cgi-bin/Ultimate.cgi?action=intro" TARGET="_new"><IMG SRC="graphics/everquest_link.jpg" WIDTH ="220" HEIGHT ="75"></A>
		</TD>
		<TD><FONT FACE="Verdana" SIZE="-2">The official Sony EQ message boards.</FONT></TD>
	</TR>
	<TR>
		<TD>
		<A HREF="http://vnboards.ign.com/default.asp?cat=5001" TARGET="_new"><IMG SRC="graphics/eqvault_link.jpg" WIDTH ="220" HEIGHT ="75"></A>
		</TD>
		<TD><FONT FACE="Verdana" SIZE="-2">EQVaults very popular discussion boards</FONT></TD>
	</TR>
	<TR>
		<TD>
		<A HREF="http://boards.stratics.com/cgi-bin/ubb/Ultimate.cgi?action=intro&BypassCookie=true" TARGET="_new"><IMG SRC="graphics/eqss_link.jpg" WIDTH ="220" HEIGHT ="75"></A>
		</TD>
		<TD><FONT FACE="Verdana" SIZE="-2">EQ Stratics' busy boards</FONT></TD>
	</TR>

<!--

Down...

	<TR>
		<TD>
		<A HREF="http://eqforge.com/cgi-bin/Ultimate.cgi?action=intro&BypassCookie=true" TARGET="_new"><IMG SRC="graphics/eq_forge_link.jpg" WIDTH ="220" HEIGHT ="75"></A>
		</TD>
		<TD><FONT FACE="Verdana" SIZE="-2">Forums hosted by the EQ Forge</FONT></TD>
	</TR>

-->

	<TR>
		<TD>
		<A HREF="http://pub13.ezboard.com/bthesafehouse" TARGET="_new"><IMG SRC="graphics/safehouse_link.jpg" WIDTH ="220" HEIGHT ="75"></A>
		</TD>
		<TD><FONT FACE="Verdana" SIZE="-2">The "All Things Rogue" Message Board.</FONT></TD>
	</TR>
	<TR>
		<TD>
		<A HREF="mailto:webmaster@loreseekers.com?subject=links"><IMG SRC="graphics/submit_link.jpg" WIDTH ="220" HEIGHT ="75"></A>
		</TD>
		<TD><I>Do you know of a good discussion board? Email us your link!</I></TD>
	</TR>
	</TABLE>
	<TD width="64"></TD>
<TR>
	<TD><IMG SRC = "graphics/botc000.jpg" WIDTH = 63 HEIGHT = 87></TD>
	<TD><IMG SRC = "graphics/botc001.jpg" WIDTH = 473 HEIGHT = 87></TD>
	<TD><IMG SRC = "graphics/botc002.jpg" WIDTH = 64 HEIGHT = 87></TD>
</TR>
</TABLE>
<BR>
<IMG SRC="http://service.bfast.com/bfast/serve?bfmid=1375281&siteid=40292692&bfpage=pc" BORDER="0" WIDTH="1" HEIGHT="1" NOSAVE ><A HREF="http://service.bfast.com/bfast/click?bfmid=1375281&siteid=40292692&bfpage=pc" TARGET="_new"><IMG SRC="http://affiliate.gamestop.com/affIMG/pc_120x60.gif" BORDER="0" WIDTH="120" HEIGHT="60" ALT="PC Games at GameStop.com"></A>
<BR>
<BR>
</DIV>
</BODY>
</HTML>



