<!--
                 This page has been created by Renaissance IT
   Renaissance Internet Technologies Copyright (c) 1999 All Rights Reserved.

             for more info on our products, please visit :
                        http://www.renaissance.nl/

	This script has been written by Roy Boverhof <rboverhof@renaissance.nl>
	
        Pagename                : faydwer_zones.html
        Last Updated    		: 05-02-2000
-->

<HTML>
<HEAD>
	<TITLE>the Seekers of Lore : Faydwer Map</TITLE>
</HEAD>

<BODY BGCOLOR="#000000" TEXT="#000000" LINK="#000000" VLINK="#000000" ALINK="#000000">
<DIV ALIGN="CENTER">
<BR>
<!-- FGB Banner Code -->
<SCRIPT LANGUAGE="JavaScript">
<!-- Hide from old browsers
now = new Date();
random = now.getTime();

// Modify to reflect site specifics
site = "http://ds.cybereps.com";
target = "/SITE=FGN/AREA=EQLORE/AAMSZ=BANNER";

document.write('<IFRAME SRC="' + site + '/hserver/acc_random=' + random + target + '"');
document.write(' NORESIZE SCROLLING=NO HSPACE=0 VSPACE=0 FRAMEBORDER=0 MARGINHEIGHT=0 MARGINWIDTH=0 WIDTH=468 HEIGHT=60>');

document.write('<SCR');
document.write('IPT SRC="' + site + '/jnserver/acc_random=' + random + target + '">');
document.write('</SCR');
document.write('IPT>');

document.write('</IFRAME>');
// End Hide -->
</SCRIPT>

<NOSCRIPT><A HREF="http://ds.cybereps.com/accipiter/adclick/SITE=FGN/AREA=EQLORE/AAMSZ=BANNER"><IMG SRC="http://ds.cybereps.com/accipiter/nserver/SITE=FGN/AREA=EQLORE/AAMSZ=BANNER" border="0"></A></NOSCRIPT>
<!-- END FGB Banner Code --><BR>
<TABLE CELLSPACING = 0 CELLPADDING = 0 BORDER = 0>
<TR>
	<TD width="63"><IMG SRC = "graphics/topc000.jpg" WIDTH = 63 HEIGHT = 87></TD>
	<TD width="473"><IMG SRC = "graphics/topc001.jpg" WIDTH = 473 HEIGHT = 87></TD>
	<TD width="64"><IMG SRC = "graphics/topc002.jpg" WIDTH = 64 HEIGHT = 87></TD>
</TR>
	<TD width="63"></TD>
	<TD BGCOLOR="#BEA279" width="460">
	<DIV ALIGN="CENTER">
	<A HREF="maps.php3"><IMG SRC="graphics/atlasheader.jpg" WIDTH ="150" HEIGHT ="75" BORDER="0"></A>
	<TABLE WIDTH="460">
	<TR><TD>
	<CENTER>
<TABLE BORDER="0">
<TR>
<TD><BR><FONT COLOR="#FFFF00" SIZE="4" FACE="Ariel"><CENTER>Now choose a region...</CENTER></FONT><BR></TD>
</TR>
<TR>
<TD>
<IMG SRC="graphics/faydwer_zones.jpg" WIDTH=400 HEIGHT=350 BORDER=0 USEMAP="#faydwer">
<MAP NAME="faydwer">
<AREA SHAPE=RECT COORDS="125,13,271,42" HREF="map_search.php3?action=zone&add_zone=Faydwer" ALT="Click to search for Faydwer continent maps">
<AREA SHAPE=RECT COORDS="5,54,198,329" HREF="west_faydwer_zones.phtml">
<AREA SHAPE=RECT COORDS="202,54,394,329" HREF="east_faydwer_zones.phtml">
</MAP>
</TD>
</TR>
</TABLE>
	</TD></TR>
	</TABLE>
	<TD width="64"></TD>
<TR>
	<TD><IMG SRC = "graphics/botc000.jpg" WIDTH = 63 HEIGHT = 87></TD>
	<TD><IMG SRC = "graphics/botc001.jpg" WIDTH = 473 HEIGHT = 87></TD>
	<TD><IMG SRC = "graphics/botc002.jpg" WIDTH = 64 HEIGHT = 87></TD>
</TR>
</TABLE>
<BR>
<SCRIPT LANGUAGE="JavaScript">
<!-- Hide from old browsers
now = new Date();
random = now.getTime();

// Modify to reflect site specifics
site = "http://ds.cybereps.com";
target = "/SITE=FGN/AREA=EQLORE/AAMSZ=BUTTON1";

document.write('<IFRAME SRC="' + site + '/hserver/acc_random=' + random + target + '"');
document.write(' NORESIZE SCROLLING=NO HSPACE=0 VSPACE=0 FRAMEBORDER=0 MARGINHEIGHT=0 MARGINWIDTH=0 WIDTH=120 HEIGHT=90>');

document.write('<SCR');
document.write('IPT SRC="' + site + '/jnserver/acc_random=' + random + target + '">');
document.write('</SCR');
document.write('IPT>');

document.write('</IFRAME>');
// End Hide -->
</SCRIPT>
<NOSCRIPT> <A HREF="http://ds.cybereps.com/accipiter/adclick/SITE=FGN/AREA=EQLORE/AAMSZ=BUTTON1">
<IMG SRC="http://ds.cybereps.com/accipiter/nserver/SITE=FGN/AREA=EQLORE/AAMSZ=BUTTON1" border="0"></A>
</NOSCRIPT>
<BR>
<BR>
</DIV>
</BODY>
</HTML>