<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">

<html>
<head>
	<title>..:: EQBard : le site de Jonili le petit barde ::..</title>

<SCRIPT LANGUAGE="Javascript">
<!--
function fenetre(intitule,params) { 
var fen = window.open(intitule,'zoom',params); 
}
//-->
</script>

<style>
a.lientexte {color:#0B5040;text-decoration:none;}
a.lientexte:hover {color:#0B5040;text-decoration:underline;}
</style>
</head>

<body bgcolor='#CFE6E3' text='#000000' link='#0B5040' vlink='#000000' alink='#000000'>
<table width='680' border='0' cellspacing='0' cellpadding='0'>
<tr><td>
<table width='680' border='0' cellspacing='0' cellpadding='0'>
<tr>
<td width='680' align='right' valign='top'>
<img src='./img/commun/c01/carre80.gif' width='10' height='10' border='0' alt=''>
<img src='./img/commun/c01/carre70.gif' width='10' height='10' border='0' alt=''>
<img src='./img/commun/c01/carre60.gif' width='10' height='10' border='0' alt=''>
<img src='./img/commun/c01/carre50.gif' width='10' height='10' border='0' alt=''>
</td></tr>
<tr><td height='2'><img src='./img/commun/transparent.gif' height='2' alt='' border='0'></td></tr>
<tr><td width='680' height='1'><img src='./img/commun/c01/carre50.gif' width='680' height='1' alt='' border='0'></td></tr>
</table>
</td></tr><tr><td>
<table width='680' border='0' cellspacing='0' cellpadding='0'>
<tr><td width='120' valign='top'><table width='100%' border='0' cellspacing='0' cellpadding='0'>
<tr><td>
<font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>&nbsp;<br>
<img src='./img/commun/c01/carre70.gif' width='10' height='10' border='0' alt=''>&nbsp;<a href=index.php?menu=1&data=1 class=lientexte><b>Accueil</b></a><br>&nbsp;<br>
<img src='./img/commun/c01/carre70.gif' width='10' height='10' border='0' alt=''>&nbsp;<a href=index.php?menu=2&data=2&order=1 class=lientexte><b>Chants</b></a><br>&nbsp;<br>
<img src='./img/commun/c01/carre70.gif' width='10' height='10' border='0' alt=''>&nbsp;<b>Equipement</b><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=31&data=31&inc=instruments class=lientexte>Instruments</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=32&data=31&inc=armures class=lientexte>Armures</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=33&data=31&inc=armes&order=1&sens=1&bard=1 class=lientexte>Armes</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=34&data=31&inc=resist class=lientexte>Resist gear</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=35&data=31&inc=slot class=lientexte>Par slot</a><br>&nbsp;<br>
<img src='./img/commun/c01/carre70.gif' width='10' height='10' border='0' alt=''>&nbsp;<b>Guides</b><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carreselect.gif' width='5' height='5' border='0' alt=''>&nbsp;Général<br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=42&data=42 class=lientexte>Tactiques</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=43&data=43 class=lientexte>Quêtes</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=44&data=44 class=lientexte>Zones</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=45&data=45 class=lientexte>Procs</a><br>&nbsp;<br>
<img src='./img/commun/c01/carre70.gif' width='10' height='10' border='0' alt=''>&nbsp;<b>Photos</b><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=51&data=51 class=lientexte>Atlas</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=52&data=52 class=lientexte>Bardes</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=54&data=54 class=lientexte>GM</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=55&data=55 class=lientexte>Divers</a><br>&nbsp;<br>
<img src='./img/commun/c01/carre70.gif' width='10' height='10' border='0' alt=''>&nbsp;<a href=index.php?menu=8&data=8 class=lientexte><b>Mode</b></a><br>&nbsp;<br>
<img src='./img/commun/c01/carre70.gif' width='10' height='10' border='0' alt=''>&nbsp;<a href=index.php?menu=6&data=6 class=lientexte><b>Liens</b></a><br>
<img src='./img/commun/c01/carre70.gif' width='10' height='10' border='0' alt=''>&nbsp;<a href=index.php?menu=7&data=7 class=lientexte><b>Download</b></a><br>
<img src='./img/commun/c01/carre70.gif' width='10' height='10' border='0' alt=''>&nbsp;<a href='http://forumsfr.ubi.com/messages/overview.asp?name=eq_themaeq_eqbardes' target='_blank' class=lientexte><b>Forum</b></a><br>
<img src='./img/commun/c01/carre70.gif' width='10' height='10' border='0' alt=''>&nbsp;<a href=mailto:jonili@eqbard.eqloft.com class=lientexte><b>M'écrire</b></a><br>&nbsp;<br>
<img src='./img/commun/c01/carre70.gif' width='10' height='10' border='0' alt=''>&nbsp;<a href=index.php?menu=9&data=9 class=lientexte><b>Backstage</b></a><br>&nbsp;<br></font></td></tr></table>
</td><td width='20' valign='top'><img src='./img/commun/c01/carre50.gif' width='10' height='10' border='0' alt=''>
<img src='./img/commun/c01/carre60.gif' width='10' height='10' border='0' alt=''>
<img src='./img/commun/c01/carre70.gif' width='10' height='10' border='0' alt=''>
<img src='./img/commun/c01/carre80.gif' width='10' height='10' border='0' alt=''>
</td><td width='540' align='left' valign='top'><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>&nbsp;<br><a href='index.php?menu=41&data=41 class=lientexte' class=lientexte><b>< Retour</b></a><br>&nbsp;<br><table width='100%' border='0' cellspacing='0' cellpadding='0'><tr><td colspan='2' bgcolor='#0B5040'><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2' color='white'><b>&nbsp;Créez votre canal de discussion...</b></font></td></tr><tr><td width ='10'>&nbsp;</td><td><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>&nbsp;<br>Je vais traduire et adapter ici le passage du manuel pour les Channel perso.
<br>&nbsp;<br>
Les joueurs peuvent desormais joindre jusqu'a 10 channels personalisés en plus des Channel normaux (auction, shout, say, guild, ooc..). Les commandes pour ces Channel ne s'appliquent pas aux /ooc et /shout. 
<br>&nbsp;<br>

Voici comment décrire les Channels : 
<ul>
<li>[] = parametres optionnels, &lt;&gt; = parametres obligatoires 
<li>&lt;channel&gt; = &lt;channel-name | 1..10&gt;[:&lt;character-name&gt;] 
<li>&lt;channel-list&gt; = &lt;channel&gt;[,...] 
</ul>

C'est assez compliqué a traduire, donc je vais tenter d'expliquer ce que j'ai compris : 
<ul>
<li>Par exemple pour rejoindre un channel, on fait : <br>
/chat set Voxraidleader:chefcode <br>
Cette commande vous fais rejoindre le channel VOXRAIDLEADER avec le mot de passe CHEFCODE. 
<li>Maintenant, pour rejoindre plusieurs channel a la fois : <br>
/chat set Voxraidleader:chefcode, Voxraidgroupleader:chefs, Voxraidgeneral <br>
Cette commande vous fais rejoindre 3 Chats : Voxraidleader (mot de passe : chefcode), Voxgroupleader (mot de passe : chefs) et Voxraidgeneral. 
</ul>
Quand il y a un mot de passe, ne pas oublier de mettre le ':' pour séparer code et channel. 
<br>&nbsp;<br>
Note : Les majuscules ne changent rien pour intégrer un channel en entrant le code (donc pas de password en PaSsWoRd ). Juste à la création du channel, le nom restera avec les majuscules indiquées. 
<br>&nbsp;<br>

</font>&nbsp;<br></td></tr><tr><td colspan='2' bgcolor='#0B5040'><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2' color='white'><b>&nbsp;Commandes générales</b></font></td></tr><tr><td width ='10'>&nbsp;</td><td><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>&nbsp;<br>
<b>/chat set &lt;channel-list&gt;</b> Cette commande vous fait REJOINDRE une liste de channels de Chat. Cette commande vous fera quiter automatiquement les Channel perso ou vous étiez pour vous mettre sur la liste indiquée. 
Utilisez plutot /join pour juste vous placer sur un autre Channel sans quitter les autres (voir ci dessous). 
<br>&nbsp;<br>
<b>/join &lt;channel-list&gt;</b> Vous rejoignez les channels listés dans le &lt;channel-list&gt;. Si le channel n'existe pas, vous créez un nouveau channel et vous en êtes modérateur. Donc attention à bien taper les paramêtres pour un channel déjà existant. Mettre des espaces dans le nom du channel ne sert à rien, ils seront supprimés...
<br>&nbsp;<br>
<b>/leave &lt;character-name&gt;</b> Vous permet de quitter le Channel spécifié. Vous devez entrer le numéro ou le nom du channel à quitter, sinon ça ne marche pas. 
<br>&nbsp;<br>
<b>/leaveall</b> Quitter tous les channels. 
<br>&nbsp;<br>
<b>/list</b> Vous donne la liste des channels où vous vous trouvez, les numéros attribués aux channels (1 a 10), et le nombre de personnes sur ces channels. Les numéros sont personels, vous pouvez ne pas avoir les mêmes qu'un autre joueur qui garde des Friends sur son Channel 1 par exemple. 
<br>&nbsp;<br>
<b>/list [channel]</b> Avec le nom du channel, cette comande vous fait un /who du channel (avec les noms des inscrits, donc).
<br>&nbsp;<br>
<b>/announce [on | off]</b> détermine si vous voulez voir un message vous prévenant de l'arrivée des gens sur les channels. Par défaut, c'est OFF. 
<br>&nbsp;<br>
<b>/chat #<channel-name> &lt;character-name&gt;</b> le # est obligatoire. Ca envoie un message à tout le channel en question. 
<br>&nbsp;<br>
<b>/<1..10> &lt;character-name&gt;</b> Envoie un message au channel. Ainsi, pour dire bonjour sur le channel 4 ce sera "/4 bonjour". 

<br>&nbsp;<br>
<b>/chat help</b> vous liste les commandes specifiques au chat. 


&nbsp;<br>

</font>&nbsp;<br></td></tr><tr><td colspan='2' bgcolor='#0B5040'><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2' color='white'><b>&nbsp;Les commandes pour modérateurs</b></font></td></tr><tr><td width ='10'>&nbsp;</td><td><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>&nbsp;<br>
<b>/chat invite &lt;character-name&gt; [channel]</b> Envoie une invitation à une personne pour joindre le channel. Si aucun nom de channel est spécifié, la personne sera invitée sur le channel numéroté 1. l'invitation arrive comme un message texte. Si il y a un code, La personne ne peut faire /join sans code que une fois (si elle quite, elle aura besoin d'un autre invite ou du code). 
<br>&nbsp;<br>
<b>/chat grant &lt;character-name&gt; [channel]</b> Donne les pouvoirs d'un modérateur au perso. Si aucun channel n'est spécifié, ca concernera le channel numéroté 1. 
<br>&nbsp;<br>
<b>/chat password &lt;character-name&gt; [channel]</b> Met ou change le code du channel. Ca concerne le channel 1 si aucun nom n'est spécifié. 
<br>&nbsp;<br>
<b>/chat kick &lt;character-name&gt; [channel]</b> L'essence du modérateur, ce qui fait sa force : Le Kick . Ca concerne le channel 1 si on ne précise pas le nom du channel. 
<br>&nbsp;<br>
<b>/chat moderate [channel]</b> Le rouleau de sparadrap des modérateurs : met le channel en mode 'Moderate' : seuls ceux qui sont autorisés peuvent parler. Retaper la commande repasse en 'normal mode'. Ca concerne le channel 1 si on ne précise pas le nom du channel (vive le copier-coller). 
<br>&nbsp;<br>
<b>/chat voice &lt;character-name&gt; [channel]</b> permet à un perso de parler sur un channel de type 'Moderate'. Ca concerne le channel 1 si on ne précise pas le nom du channel. 
<br>&nbsp;<br>

NOTE: Un chat protégé par un code est semi-permanent : il disparait si il est vide plus de 24h. Les chats sans code disparaissent dés qu'ils sont vides. 
<br>&nbsp;<br>

Remarque : /chat peut être remplacés par un point-virgule ';'. De plus vous pouvez entrer les commandes sans le /chat avant : ainsi, il est possible de faire /add, /join, /moderate... (je n'ai pas encore eu l'occasion de tester /kick , mais ça va venir  ...) 
&nbsp;<br>
 
</font>&nbsp;<br></td></tr><tr><td colspan='2' bgcolor='#0B5040'><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2' color='white'><b>&nbsp;Commandes associées</b></font></td></tr><tr><td width ='10'>&nbsp;</td><td><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>&nbsp;<br>
<b>/autojoin &lt;channel-list&gt;</b> sauvegarde les channels de la liste indiquée dans votre EQclient.ini . Vous loggerez dedans automatiquement en loggant (il est possible d'éditer eqclient pour changer ça offline donc). 
<br>&nbsp;<br>
<b>/usecolor</b> Pour changer la couleur du Chat ça fonctionne comme pour changer la couleur des Channel /ooc, /shout, /say... Voici les numéros des Channels personalisés : 
<ul>
<li>35 - Messages relatifs au Chat 
<li>36 - Chat Channel 1 
<li>37 - Chat Channel 2 
<li>38 - Chat Channel 3 
<li>39 - Chat Channel 4 
<li>40 - Chat Channel 5 
<li>41 - Chat Channel 6 
<li>42 - Chat Channel 7 
<li>43 - Chat Channel 8 
<li>44 - Chat Channel 9 
<li>45 - Chat Channel 10 
</ul>
<br>&nbsp;<br>
<b>Kaldanm</b>
</font>&nbsp;<br></td></tr></table>&nbsp;<br></font></td></tr></table>
</td></tr><tr><td>
<table width='680' border='0' cellspacing='0' cellpadding='0'>
<tr><td width='680' height='1'><img src='./img/commun/c01/carre50.gif' width='680' height='1' alt='' border='0'></td></tr>
<tr><td height='2'><img src='./img/commun/transparent.gif' height='2' alt='' border='0'></td></tr>
<tr>
<td width='680' align='left' valign='top'>
<img src='./img/commun/c01/carre50.gif' width='10' height='10' border='0' alt=''>
<img src='./img/commun/c01/carre60.gif' width='10' height='10' border='0' alt=''>
<img src='./img/commun/c01/carre70.gif' width='10' height='10' border='0' alt=''>
<img src='./img/commun/c01/carre80.gif' width='10' height='10' border='0' alt=''>
</td></tr>
</table>
</td></tr><tr><td align='center'>
<A target='_blank' href='http://www.eqloft.com/'><img src='./img/commun/hebergement.gif' width='122' height='31' border='0' alt=''></a></td></tr></table>

</body>
</html>
<html>
<!-- webbot bot="HTMLMarkup" startspan -->
<!-- BEGIN WEBSIDESTORY CODE -->
<!-- COPYRIGHT 1997-2001 WEBSIDESTORY, INC. ALL RIGHTS RESERVED. U.S.PATENT PENDING. Privacy notice at: http://websidestory.com/privacy -->
<script language="javascript">
var _pn="EQLoft";       //page name(s)
var _mlc="/SiteWeb";    //multi-level content category
var _cp="null";                 //campaign
var _acct="DM510830FOBR38FR3";  //account number(s)
var _pndef="title";             //default page name
var _ctdef="full";              //default content category
var _dlf="n";                   //download filter
var _elf="n";                   //exit link filter
var _epg="n";                   //event page identifier
var _hcv=65;                    //code version
var _mn="we44";                 //machine name
var _gn="ehg-ubisoft.hitbox.com";                       //gateway name
var _ptc="n"; // page type
function _wn(_nm){if((_nm.indexOf("NAME")>0&&_nm.indexOf("PUT")>=0)||
(_nm.indexOf("CONTENT")>=0&&_nm.indexOf("CATEGORY")>0))return true;return false;}
function _gd(_x,_w){_ed = (_x.lastIndexOf("/"));
_be = (_w!="full")?(_x.lastIndexOf("/",(_ed-2))):(_x.indexOf("/"));
_dn = (_be==_ed)?"/":(_x.substring(_be, _ed));return _dn;}
function _gf(_x){_ed = (_x.length);_be = ((_x.lastIndexOf("/"))+1);
_fn = (_x.substring(_be, _ed));return _fn;}
function _vc(_ml){_mll=_ml.length-1;if(_ml.lastIndexOf("/")==_mll){_ml=_ml.substring(0,_mll)}
if(_ml.indexOf("/")!=0){_ml="/"+_ml;}return _ml;}
function _ps(_ip,_pml){if(!_ip){_pml=(_wn(_pml))?_gd(location.pathname,_ctdef):_vc(_pml);}
else{if (_wn(_pml)){if (_pndef=="title"){_pt=document.title; if(_pt!=""){_pml=_pt};}
else{_pml=_gf(location.pathname);if (_pml==""){_pml=_pndef};}};}return _pml;}
function _pm(_ml,_fml,_ipn){if(_ml.indexOf(";")!=-1){_nml=_ml.substring(0,(_ml.indexOf(";")));
_rm=_ml.substring((_ml.indexOf(";")+1),_ml.length);_fml+=_ps(_ipn,_nml)+";";
_gp=_pm(_rm,_fml,_ipn);return _gp;}else {_fml+=_ps(_ipn,_ml);return _fml;}}
var _sv=10;var _bn=navigator.appName;if(_bn.substring(0,9)=="Microsoft"){_bn="MSIE";};
var _bv=(Math.round(parseFloat(navigator.appVersion)*100));if((_bn=="MSIE")&&(parseInt(_bv)==2))_bv=301;
var _rf=escape(document.referrer);_mlc=_pm(_mlc,"",false);_pn=_pm(_pn,"",true);
</script><script language="javascript1.1" id="_hbc">_sv=11;</script>
<script language="javascript1.1" defer src="http://a1604.g.akamai.net/f/1604/2007/1h/stats.hitbox.com/js/hbe.js"></script>
<script language="javascript">if (_sv==10){if
(document.cookie.indexOf("CP=")!=-1){_ce="y";}else{
document.cookie="CP=null*; path=/; expires=Wed, 1 Jan 2020 00:00:00 GMT";
_ce=(document.cookie.indexOf("CP=")!=-1)?"y":"n";};if((_rf=="undefined")||(_rf=="")){_rf="bookmark";};
_x2="<img src='http://"+_gn+"/HG?hc="+_mn+"&hb="+escape(_acct)+"&n="+escape(_pn);
_x3="&cd=1&hv=6' border=0 height=1 width=1>";
_ar="&bn="+escape(_bn)+"&bv="+_bv+"&ce="+_ce+"&ss=na&sc=na&dt=&sv="+_sv+"&con="+escape(_ct);
_ar+="&vcon="+escape(_mlc)+"&epg="+_epg+"&hp=u&cy=u&ja=na&ln=na&cp="+escape(_cp)+"&pl=&rf="+_rf;
document.write(_x2+_ar+_x3);}document.write("<\!--");</script>
<noscript><img src="http://ehg-ubisoft.hitbox.com/HG?hc=we44&cd=1&hv=6&ce=u&hb=DM510830FOBR38FR3&n=EQLoft&vcon=/SiteWeb" border='0' width='1' height='1'>
</noscript><!--//-->
<!-- END WEBSIDESTORY CODE  -->
<!-- webbot bot="HTMLMarkup" endspan -->
</html>
