<!--
                 This page has been created by Renaissance IT
   Renaissance Internet Technologies Copyright (c) 1999 All Rights Reserved.

             for more info on our products, please visit :
                        http://www.renaissance.nl/

	This script has been written by Roy Boverhof <rboverhof@renaissance.nl>
	
        Pagename                : rathe_screenshots.html
        Last Updated    		: 25-03-2000
-->

<HTML>
<HEAD>
	<TITLE>the Seekers of Lore : Rathe Server Screenshots</TITLE>
</HEAD>

<BODY BGCOLOR="#000000" TEXT="#000000" LINK="#000000" VLINK="#000000" ALINK="#000000">
<DIV ALIGN="CENTER">
<BR>
<!-- FGN Banner Code -->
<script language="JavaScript">
	<!-- Hide from old browsers
	var random = new Number(Math.floor(9999999 * Math.random())+1);

	// Modify to reflect site specifics
	page = "eqlore.com/";
	target = "@Top1,x02,x05,x08!Top1";

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript1.1" SRC="http://oascentral.cybereps.com/RealMedia/ads/adstream_jx.ads/' + page + 1 + random + target + '">');
	document.write('</SCR');
	document.write('IPT>');

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript">');
	document.write('_version=10; //-->');
	document.write('</SCR');
	document.write('IPT>');

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript1.1">');
	document.write('_version=11; //-->');
	document.write('</SCR');
	document.write('IPT>');

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript">');

	if (navigator.appVersion.indexOf('MSIE 3') != -1){
	document.write('<IFRAME MARGINWIDTH=0 MARGINHEIGHT=0 HSPACE=0 VSPACE=0 FRAMEBORDER=0 SCROLLING=no BORDERCOLOR="#000000" SRC="oascentral.cybereps.com/RealMedia/ads/adstream_sx.ads/' + page + random + target + '"></IFRAME>');
	  }
	else if (_version < 11) {
	document.write ('<A HREF="http://oascentral.cybereps.com/RealMedia/ads/click_nx.ads/' + page + random + target + '"><IMG SRC="http://oascentral.cybereps.com/RealMedia/ads/adstream_nx.ads/' + page + random + target + '"></a>');
	  }

	document.write('</SCR');
	document.write('IPT>');

	// End Hide -->
</script>
<!-- END FGN Banner Code --><BR>	
<TABLE CELLSPACING = 0 CELLPADDING = 0 BORDER = 0>
<TR>
	<TD width="63"><IMG SRC = "graphics/topc000.jpg" WIDTH = 63 HEIGHT = 87></TD>
	<TD width="473"><IMG SRC = "graphics/topc001.jpg" WIDTH = 473 HEIGHT = 87></TD>
	<TD width="64"><IMG SRC = "graphics/topc002.jpg" WIDTH = 64 HEIGHT = 87></TD>
</TR>
	<TD width="63"></TD>
	<TD BGCOLOR="#BEA279" width="460">
	<DIV ALIGN="CENTER">
	<A HREF="http://www.loreseekers.com/screenshots.phtml"><IMG SRC="graphics/screencap_header.gif" WIDTH ="200" HEIGHT ="75" BORDER="0"></A>
	<TABLE WIDTH="460">
	<TR><TD>
	<CENTER>
<TABLE BORDER="0">
<TR>
<TD><BR><FONT SIZE="4" FACE="Ariel"><CENTER>Screenshots from our Rathe members</CENTER></FONT><BR></TD>
</TR>
</TABLE>

<TABLE BORDER="0" WIDTH="440">
<TR> 
	<TD><A HREF="http://www.loreseekers.com/screenshots/rathe_1.jpg" TARGET="_new"><IMG SRC="http://www.loreseekers.com/screenshots/tn_rathe_1.jpg" WIDTH ="200" HEIGHT ="150" ALT="Click to view image full size"></A></TD>
	<TD><A HREF="http://www.loreseekers.com/screenshots/rathe_2.jpg" TARGET="_new"><IMG SRC="http://www.loreseekers.com/screenshots/tn_rathe_2.jpg" WIDTH ="200" HEIGHT ="150" ALT="Click to view image full size"></A></TD>
</TR>
<TR>
	<TD COLSPAN="2"><FONT SIZE="2" FACE="ARIEL"><CENTER><FONT COLOR="#FF00000">NEW</FONT> - Seekers ripping up Kithicor Forest with Paladin Tactix</CENTER></FONT></TD>
</TR>
<TR> 
	<TD><A HREF="http://www.loreseekers.com/screenshots/giant.jpg" TARGET="_new"><IMG SRC="http://www.loreseekers.com/screenshots/tn_giant.jpg" WIDTH ="200" HEIGHT ="150" ALT="Click to view image full size"></A></TD>
	<TD><A HREF="http://www.loreseekers.com/screenshots/specs.jpg" TARGET="_new"><IMG SRC="http://www.loreseekers.com/screenshots/tn_specs.jpg" WIDTH ="200" HEIGHT ="150" ALT="Click to view image full size"></A></TD>
</TR>
<TR> 
	<TD><A HREF="http://www.loreseekers.com/screenshots/me-specs.jpg" TARGET="_new"><IMG SRC="http://www.loreseekers.com/screenshots/tn_me-specs.jpg" WIDTH ="200" HEIGHT ="150" ALT="Click to view image full size"></A></TD>
	<TD><A HREF="http://www.loreseekers.com/screenshots/sven.jpg" TARGET="_new"><IMG SRC="http://www.loreseekers.com/screenshots/tn_sven.jpg" WIDTH ="200" HEIGHT ="150" ALT="Click to view image full size"></A></TD>
</TR>
<TR> 
	<TD><A HREF="http://www.loreseekers.com/screenshots/tarskuk.jpg" TARGET="_new"><IMG SRC="http://www.loreseekers.com/screenshots/tn_tarskuk.jpg" WIDTH ="200" HEIGHT ="150" ALT="Click to view image full size"></A></TD>
	<TD><A HREF="http://www.loreseekers.com/screenshots/falling.jpg" TARGET="_new"><IMG SRC="http://www.loreseekers.com/screenshots/tn_falling.jpg" WIDTH ="200" HEIGHT ="150" ALT="Click to view image full size"></A></TD>
</TR>
</TABLE>

	</CENTER>
	<P>
	<BR>
	<BR>
	</P>
	</TD></TR>
	</TABLE>
	<TD width="64"></TD>
<TR>
	<TD><IMG SRC = "graphics/botc000.jpg" WIDTH = 63 HEIGHT = 87></TD>
	<TD><IMG SRC = "graphics/botc001.jpg" WIDTH = 473 HEIGHT = 87></TD>
	<TD><IMG SRC = "graphics/botc002.jpg" WIDTH = 64 HEIGHT = 87></TD>
</TR>
</TABLE>
<BR>
<IMG SRC="http://service.bfast.com/bfast/serve?bfmid=1375281&siteid=40292692&bfpage=pc" BORDER="0" WIDTH="1" HEIGHT="1" NOSAVE ><A HREF="http://service.bfast.com/bfast/click?bfmid=1375281&siteid=40292692&bfpage=pc" TARGET="_new"><IMG SRC="http://affiliate.gamestop.com/affIMG/pc_120x60.gif" BORDER="0" WIDTH="120" HEIGHT="60" ALT="PC Games at GameStop.com"></A>
<BR>
<BR>
</DIV>
</BODY>
</HTML>