<!--
                 This page has been created by Renaissance IT
   Renaissance Internet Technologies Copyright (c) 1999 All Rights Reserved.
             for more info on our products, please visit :
                        http://www.renaissance.nl/

	This script has been written by Roy Boverhof <rboverhof@renaissance.nl>

        Pagename                : links1.html
        Last Updated    		: 03-16-2001
-->


<HTML>
<HEAD>
	<TITLE>the Seekers of Lore : General EQ Links</TITLE>
</HEAD>

<BODY BGCOLOR="#000000" TEXT="#000000" LINK="#000000" VLINK="#000000" ALINK="#000000">
<DIV ALIGN="CENTER">
<BR>
<!-- FGN Banner Code -->
<script language="JavaScript">
	<!-- Hide from old browsers
	var random = new Number(Math.floor(9999999 * Math.random())+1);

	// Modify to reflect site specifics
	page = "eqlore.com/";
	target = "@Top1,x02,x05,x08!Top1";

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript1.1" SRC="http://oascentral.cybereps.com/RealMedia/ads/adstream_jx.ads/' + page + 1 + random + target + '">');
	document.write('</SCR');
	document.write('IPT>');

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript">');
	document.write('_version=10; //-->');
	document.write('</SCR');
	document.write('IPT>');

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript1.1">');
	document.write('_version=11; //-->');
	document.write('</SCR');
	document.write('IPT>');

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript">');

	if (navigator.appVersion.indexOf('MSIE 3') != -1){
	document.write('<IFRAME MARGINWIDTH=0 MARGINHEIGHT=0 HSPACE=0 VSPACE=0 FRAMEBORDER=0 SCROLLING=no BORDERCOLOR="#000000" SRC="oascentral.cybereps.com/RealMedia/ads/adstream_sx.ads/' + page + random + target + '"></IFRAME>');
	  }
	else if (_version < 11) {
	document.write ('<A HREF="http://oascentral.cybereps.com/RealMedia/ads/click_nx.ads/' + page + random + target + '"><IMG SRC="http://oascentral.cybereps.com/RealMedia/ads/adstream_nx.ads/' + page + random + target + '"></a>');
	  }

	document.write('</SCR');
	document.write('IPT>');

	// End Hide -->
</script>
<!-- END FGN Banner Code -->
<BR>
<TABLE CELLSPACING = 0 CELLPADDING = 0 BORDER = 0>
<TR>
	<TD width="63"><IMG SRC = "graphics/topc000.jpg" WIDTH = 63 HEIGHT = 87></TD>
	<TD width="473"><IMG SRC = "graphics/topc001.jpg" WIDTH = 473 HEIGHT = 87></TD>
	<TD width="64"><IMG SRC = "graphics/topc002.jpg" WIDTH = 64 HEIGHT = 87></TD>
</TR>
<TR>
	<TD width="63"></TD>
	<TD BGCOLOR="#BEA279" width="460">
	<DIV ALIGN="CENTER">
	<A HREF="links.phtml"><IMG SRC="graphics/linkheader.jpg" WIDTH ="200" HEIGHT ="75" ALT="Back to Links Index" BORDER="0"></A>
	<TABLE WIDTH=440 ALIGN="center">
	<TR><TD></TD></TR>
	<TR>
		<TD>
		<A HREF="http://www.everquest.com/hht/index.jsp" TARGET="_new"><IMG SRC="graphics/harpys_link.jpg" WIDTH ="220" HEIGHT ="75" BORDER="0"></A>
		</TD>
		<TD><FONT FACE="Verdana" SIZE="-2">Harpy's Head Tavern. Come to this entertaining site to learn more about the lore, history, people and players of EQ. Hosted by Sony.</FONT></TD>
	</TR>
	<TR>
		<TD>
		<A HREF="https://www.station.sony.com/store/" TARGET="_new"><IMG SRC="graphics/sony_store_link.jpg" WIDTH ="220" HEIGHT ="75" BORDER="0"></A>
		</TD>
		<TD><FONT FACE="Verdana" SIZE="-2">Sony's Official Online Store. You may purchase the expansions here.</FONT></TD>
	</TR>
	<TR>
	<TR>
		<TD>
		<A HREF="http://station.sony.com/velious/" TARGET="_new"><IMG SRC="graphics/velious_link.jpg" WIDTH ="220" HEIGHT ="75" BORDER="0"></A>
		</TD>
		<TD><FONT FACE="Verdana" SIZE="-2">Sony's Official <I>Scars of Velious</I>™ website.</FONT></TD>
	</TR>
	<TR>
		<TD>
		<A HREF="http://www.everquest.com/" TARGET="_new"><IMG SRC="graphics/everquest_link.jpg" WIDTH ="220" HEIGHT ="75" BORDER="0"></A>
		</TD>
		<TD><FONT FACE="Verdana" SIZE="-2">Sony's Official <I>EverQuest</I>™ Homepage</FONT></TD>
	</TR>
	<TR>
		<TD>
		<A HREF="http://www.everquest.com/kunark/everquest_h.jsp" TARGET="_new"><IMG SRC="graphics/kunark_link.jpg" WIDTH ="220" HEIGHT ="75" BORDER="0"></A>
		</TD>
		<TD><FONT FACE="Verdana" SIZE="-2">Sony's official <I>Ruins of Kunark</I>™ website..</FONT></TD>
	</TR>
	<TR>
		<TD>
		<A HREF="http://www.verant.com/" TARGET="_new"><IMG SRC="graphics/verant_link.jpg" WIDTH ="220" HEIGHT ="75" BORDER="0"></A>
		</TD>
		<TD><FONT FACE="Verdana" SIZE="-2">Verant Interactive. Producers of EverQuest.</FONT></TD>
	</TR>
	<TR>
		<TD>
		<A HREF="http://eqvault.ign.com/" TARGET="_new"><IMG SRC="graphics/eqvault_link.jpg" WIDTH ="220" HEIGHT ="75" BORDER="0"></A>
		</TD>
		<TD><FONT FACE="Verdana" SIZE="-2">One of the oldest and most popular EQ sites on the net.</FONT></TD>
	</TR>
	<TR>
		<TD>
		<A HREF="http://everquest.allakhazam.com/" TARGET="_new"><IMG SRC="graphics/allakhazam_link.jpg" WIDTH ="220" HEIGHT ="75" BORDER="0"></A>
		</TD>
		<TD><FONT FACE="Verdana" SIZE="-2">The most complete and up to date information on EQ available! ***New URL***</FONT></TD>
	</TR>
	<TR>
		<TD>
		<A HREF="http://eq.stratics.com/" TARGET="_new"><IMG SRC="graphics/eqss_link.jpg" WIDTH ="220" HEIGHT ="75 BORDER="0"></A>
		</TD>
		<TD><FONT FACE="Verdana" SIZE="-2">EverQuest Stratics - another excellant site. Very well laid out and informative forums.</FONT></TD>
	</TR>
	<TR>
		<TD>
		<A HREF="http://www.gameznet.com/eq/index.shtml" TARGET="_new"><IMG SRC="graphics/eqlizer_link.jpg" WIDTH ="220" HEIGHT ="75" BORDER="0"></A>
		</TD>
		<TD><FONT FACE="Verdana" SIZE="-2">Quality information site with many higher level items and information.</FONT></TD>
	</TR>
	<TR>
		<TD>
		<A HREF="http://www.everlore.com/" TARGET="_new"><IMG SRC="graphics/everlore_link.jpg" WIDTH ="220" HEIGHT ="75" BORDER="0"></A>
		</TD>
		<TD><FONT FACE="Verdana" SIZE="-2">Another quality site with especially good spell information.</FONT></TD>
	</TR>
	<TR>
		<TD>
		<A HREF="http://members.home.net/casinobound/" TARGET="_new"><IMG SRC="graphics/sand_link.jpg" WIDTH ="220" HEIGHT ="75" BORDER="0"></A>
		</TD>
		<TD><FONT FACE="Verdana" SIZE="-2">Sanderson's Quest - A new source of EQ and RoK information.</FONT></TD>
	</TR>
	<TR>
		<TD>
		<A HREF="http://onlinegames.pagina.nl/" TARGET="_new"><IMG SRC="graphics/startpagina_link.jpg" WIDTH ="220" HEIGHT ="75" BORDER="0"></A>
		</TD>
		<TD><FONT FACE="Verdana" SIZE="-2">Online Games @ Startpagina - A great source of links to just about every good site on the net for our Dutch visitors. (Dutch Language Site)</FONT></TD>
	</TR>

	<TR>
		<TD>
		<B><DIV ALIGN="center"><A HREF="http://www.angelfire.com/games3/EverTry/index.html" TARGET="_new">Uber Quest</A></DIV></B>
		</TD>
		<TD><FONT FACE="Verdana" SIZE="-2"><FONT FACE="Verdana" SIZE="-2" COLOR="#FF0000">New! - </FONT>General site with quest and item info.</FONT></TD>
	</TR>	

	<TR>
		<TD></TD>
		<TD><BR></TD>
	</TR>
	
	<TR>
		<TD>
		<B><DIV ALIGN="center"><A HREF="http://www.jibantik.com/" TARGET="_new">Jibantik</A></DIV></B>
		</TD>
		<TD><FONT FACE="Verdana" SIZE="-2"><FONT FACE="Verdana" SIZE="-2" COLOR="#FF0000">New! - </FONT>This is a handy EverQuest search engine</FONT></TD>
	</TR>		
	
	<TR>
		<TD></TD>
		<TD><BR></TD>
	</TR>	
	
	<TR>
		<TD>
		<A HREF="mailto:webmaster@loreseekers.com?subject=links"><IMG SRC="graphics/submit_link.jpg" WIDTH ="220" HEIGHT ="75" BORDER="0"></A>
		</TD>
		<TD><I>Do you know a quality EverQuest site? Email us your link!</I></TD>
	</TR>
	</TABLE>
	<TD width="64"></TD>
<TR>
	<TD><IMG SRC = "graphics/botc000.jpg" WIDTH = 63 HEIGHT = 87></TD>
	<TD><IMG SRC = "graphics/botc001.jpg" WIDTH = 473 HEIGHT = 87></TD>
	<TD><IMG SRC = "graphics/botc002.jpg" WIDTH = 64 HEIGHT = 87></TD>
</TR>
</TABLE>
<BR>

<script language="JavaScript">
	<!-- Hide from old browsers
	var random = new Number(Math.floor(9999999 * Math.random())+1);

	// Modify to reflect site specifics
	page = "eqlore.com/";
	target = "@Top1,x02,x05,x08!x02";

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript1.1" SRC="http://oascentral.cybereps.com/RealMedia/ads/adstream_jx.ads/' + page + 1 + random + target + '">');
	document.write('</SCR');
	document.write('IPT>');

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript">');
	document.write('_version=10; //-->');
	document.write('</SCR');
	document.write('IPT>');

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript1.1">');
	document.write('_version=11; //-->');
	document.write('</SCR');
	document.write('IPT>');

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript">');

	if (navigator.appVersion.indexOf('MSIE 3') != -1){
	document.write('<IFRAME MARGINWIDTH=0 MARGINHEIGHT=0 HSPACE=0 VSPACE=0 FRAMEBORDER=0 SCROLLING=no BORDERCOLOR="#000000" SRC="oascentral.cybereps.com/RealMedia/ads/adstream_sx.ads/' + page + random + target + '"></IFRAME>');
	  }
	else if (_version < 11) {
	document.write ('<A HREF="http://oascentral.cybereps.com/RealMedia/ads/click_nx.ads/' + page + random + target + '"><IMG SRC="http://oascentral.cybereps.com/RealMedia/ads/adstream_nx.ads/' + page + random + target + '"></a>');
	  }

	document.write('</SCR');
	document.write('IPT>');

	// End Hide -->
</script><BR>
<BR>
</DIV>
</BODY>
</HTML>