<!--
                 This page has been created by Renaissance IT
   Renaissance Internet Technologies Copyright (c) 1999 All Rights Reserved.

             for more info on our products, please visit :
                        http://www.renaissance.nl/

	This script has been written by Roy Boverhof <rboverhof@renaissance.nl>
	
        Pagename                : fletching.phtml
        Last Updated    		: 19-09-2000
-->

<HTML>
<HEAD>
	<TITLE>the Seekers of Lore : guide to fletching</TITLE>
</HEAD>

<BODY BGCOLOR="#000000" TEXT="#000000" LINK="#FFF000">
<DIV ALIGN="CENTER">
<BR>
<!-- FGN Banner Code -->
<script language="JavaScript">
	<!-- Hide from old browsers
	var random = new Number(Math.floor(9999999 * Math.random())+1);

	// Modify to reflect site specifics
	page = "eqlore.com/";
	target = "@Top1,x02,x05,x08!Top1";

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript1.1" SRC="http://oascentral.cybereps.com/RealMedia/ads/adstream_jx.ads/' + page + 1 + random + target + '">');
	document.write('</SCR');
	document.write('IPT>');

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript">');
	document.write('_version=10; //-->');
	document.write('</SCR');
	document.write('IPT>');

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript1.1">');
	document.write('_version=11; //-->');
	document.write('</SCR');
	document.write('IPT>');

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript">');

	if (navigator.appVersion.indexOf('MSIE 3') != -1){
	document.write('<IFRAME MARGINWIDTH=0 MARGINHEIGHT=0 HSPACE=0 VSPACE=0 FRAMEBORDER=0 SCROLLING=no BORDERCOLOR="#000000" SRC="oascentral.cybereps.com/RealMedia/ads/adstream_sx.ads/' + page + random + target + '"></IFRAME>');
	  }
	else if (_version < 11) {
	document.write ('<A HREF="http://oascentral.cybereps.com/RealMedia/ads/click_nx.ads/' + page + random + target + '"><IMG SRC="http://oascentral.cybereps.com/RealMedia/ads/adstream_nx.ads/' + page + random + target + '"></a>');
	  }

	document.write('</SCR');
	document.write('IPT>');

	// End Hide -->
</script>
<!-- END FGN Banner Code --><BR>
<TABLE CELLSPACING = 0 CELLPADDING = 0 BORDER = 0>
<TR>
	<TD width="63"><IMG SRC = "../graphics/topc000.jpg" WIDTH = 63 HEIGHT = 87></TD>
	<TD width="473"><IMG SRC = "../graphics/topc001.jpg" WIDTH = 473 HEIGHT = 87></TD>
	<TD width="64"><IMG SRC = "../graphics/topc002.jpg" WIDTH = 64 HEIGHT = 87></TD>
</TR>
	<TD width="63"></TD>
	<TD BGCOLOR="#BEA279" width="460">

<TABLE ALIGN="center">
<TR>
<TD BGCOLOR="#BEA279" width=20></TD>
<TD GCOLOR="#BEA279" width=420>		

			<FONT SIZE=2><P> </P>
			</FONT><B><P>Jynon's Fletching Guide:</P>
			</B><FONT SIZE=2><P>By <A HREF="mailto:aspenkiddd@yahoo.com">Jynon Xantheothis</A>  - Paladin of Tarew Marr</P>
			
<P>The following is my guide to fletching. It gives a guide on the cheapest and fastest way to start mastery in Fletching. I hope you find it useful.
			
			
<P>Here are the recipes for the 13 arrows.</P>

<DIV ALIGN="center">

<P>
<TABLE BORDER=2 ALIGN="center">
<TR>
<TD BGCOLOR="#006600">&nbsp;</TD>
				<TD BGCOLOR="#006600"><FONT SIZE=2 COLOR="#ffff00">Requirements</FONT></TD>
				<TD BGCOLOR="#006600"><FONT SIZE=2 COLOR="#ffff00">Cost/5</FONT></TD>
				<TD BGCOLOR="#006600"><FONT SIZE=2 COLOR="#ffff00">Trivial</FONT></TD>
				<TD BGCOLOR="#006600"><FONT SIZE=2 COLOR="#ffff00">DMG</FONT></TD>
			</TR>			
			<TR>
				<TD BGCOLOR="#CCCC99"><FONT SIZE=2>#1</FONT></TD>
				<TD BGCOLOR="#CCCC99"><FONT SIZE=2>Field Point, Wooden Shaft, Round Fletch, Large Nock</FONT></TD>
				<TD BGCOLOR="#CCCC99"><FONT SIZE=2>24 cp</FONT></FONT></TD>
				<TD BGCOLOR="#CCCC99"><FONT SIZE=2>16</FONT></TD>
				<TD BGCOLOR="#CCCC99"><FONT SIZE=2>1</FONT></TD>
			</TR>
			<TR>
				<TD BGCOLOR="#CCCC99"><FONT SIZE=2>#2</FONT></TD>
				<TD BGCOLOR="#CCCC99"><FONT SIZE=2>Field Point, Wooden Shaft, Round Fletch, Medium Nock</FONT></TD>
				<TD BGCOLOR="#CCCC99"><FONT SIZE=2>37 cp</FONT></TD>
				<TD BGCOLOR="#CCCC99"><FONT SIZE=2>36</FONT></TD>
				<TD BGCOLOR="#CCCC99"><FONT SIZE=2>1</FONT></TD>
			</TR>
			<TR>
				<TD BGCOLOR="#CCCC99"><FONT SIZE=2>#3</FONT></TD>
				<TD BGCOLOR="#CCCC99"><FONT SIZE=2>Field Point, Wooden Shaft, Parabolic Fletch, Large Nock</FONT></TD>
				<TD BGCOLOR="#CCCC99"><FONT SIZE=2>49 cp</FONT></TD>
				<TD BGCOLOR="#CCCC99"><FONT SIZE=2>46</FONT></TD>
				<TD BGCOLOR="#CCCC99"><FONT SIZE=2>1</FONT></TD>
			</TR>
			<TR>
				<TD BGCOLOR="#CCCC99"><FONT SIZE=2>#4</FONT></TD>
				<TD BGCOLOR="#CCCC99"><FONT SIZE=2>Field Point, Wooden Shaft, Round Fletch, Small Nock</FONT></TD>
				<TD BGCOLOR="#CCCC99"><FONT SIZE=2>68 cp</FONT></TD>
				<TD BGCOLOR="#CCCC99"><FONT SIZE=2>??</FONT></TD>
				<TD BGCOLOR="#CCCC99"><FONT SIZE=2>1</FONT></TD>
			</TR>
			<TR>
				<TD BGCOLOR="#CCCC99"><FONT SIZE=2>#5</FONT></TD>
				<TD BGCOLOR="#CCCC99"><FONT SIZE=2>Field Point, Bone Shaft, Round Fletch, Large Nock</FONT></TD>
				<TD BGCOLOR="#CCCC99"><FONT SIZE=2>112 cp</FONT></TD>
				<TD BGCOLOR="#CCCC99"><FONT SIZE=2>??</FONT></TD>
				<TD BGCOLOR="#CCCC99"><FONT SIZE=2>2</FONT></TD>
			</TR>
			<TR>
				<TD BGCOLOR="#CCCC99"><FONT SIZE=2>#6</FONT></TD>
				<TD BGCOLOR="#CCCC99"><FONT SIZE=2>Field Point, Wooden Shaft, Shield Fletch, Large Nock</FONT></TD>
				<TD BGCOLOR="#CCCC99"><FONT SIZE=2>243 cp</FONT></TD>
				<TD BGCOLOR="#CCCC99"><FONT SIZE=2>??</FONT></TD>
				<TD BGCOLOR="#CCCC99"><FONT SIZE=2>2</FONT></TD>
			</TR>
			<TR>
				<TD BGCOLOR="#CCCC99"><FONT SIZE=2>#7</FONT></TD>
				<TD BGCOLOR="#CCCC99"><FONT SIZE=2>Hooked Point, Wooden Shaft, Round Fletch, Large Nock</FONT></TD>
				<TD BGCOLOR="#CCCC99"><FONT SIZE=2>393 cp</FONT></TD>
				<TD BGCOLOR="#CCCC99"><FONT SIZE=2>??</FONT></TD>
				<TD BGCOLOR="#CCCC99"><FONT SIZE=2>2</FONT></TD>
			</TR>
			<TR>
				<TD BGCOLOR="#CCCC99"><FONT SIZE=2>#8</FONT></TD>
				<TD BGCOLOR="#CCCC99"><FONT SIZE=2>Field Point, Wooden Shaft, Wooden Vane(fletch), Large Nock</FONT></TD>
				<TD BGCOLOR="#CCCC99"><FONT SIZE=2>831 cp</FONT></TD>
				<TD BGCOLOR="#CCCC99"><FONT SIZE=2>??</FONT></TD>
				<TD BGCOLOR="#CCCC99"><FONT SIZE=2>2</FONT></TD>
			</TR>
			<TR>
				<TD BGCOLOR="#CCCC99"><FONT SIZE=2>#9</FONT></TD>
				<TD BGCOLOR="#CCCC99"><FONT SIZE=2>Field Point, Ceramic Shaft, Round Fletch, Large Nock</FONT></TD>
				<TD BGCOLOR="#CCCC99"><FONT SIZE=2>1394 cp</FONT></TD>
				<TD BGCOLOR="#CCCC99"><FONT SIZE=2>??</FONT></TD>
				<TD BGCOLOR="#CCCC99"><FONT SIZE=2>3</FONT></TD>
			</TR>
			<TR>
				<TD BGCOLOR="#CCCC99"><FONT SIZE=2>#10</FONT></TD>
				<TD BGCOLOR="#CCCC99"><FONT SIZE=2>Field Point, Wooden Shaft, Bone Vane (Fletch), Large Nock</FONT></TD>
				<TD BGCOLOR="#CCCC99"><FONT SIZE=2>1644 cp</FONT></TD>
				<TD BGCOLOR="#CCCC99"><FONT SIZE=2>??</FONT></TD>
				<TD BGCOLOR="#CCCC99"><FONT SIZE=2>2</FONT></TD>
			</TR>
			<TR>
				<TD BGCOLOR="#CCCC99"><FONT SIZE=2>#11</FONT></TD>
				<TD BGCOLOR="#CCCC99"><FONT SIZE=2>Field Point, Wooden Shaft, Ceramic Vane (Fletch), Large Nock </FONT></TD>
				<TD BGCOLOR="#CCCC99"><FONT SIZE=2>3333 cp</FONT></TD>
				<TD BGCOLOR="#CCCC99"><FONT SIZE=2>??</FONT></TD>
				<TD BGCOLOR="#CCCC99"><FONT SIZE=2>3</FONT></TD>
			</TR>
			<TR>
				<TD BGCOLOR="#CCCC99"><FONT SIZE=2>#12</FONT></TD>
				<TD BGCOLOR="#CCCC99"><FONT SIZE=2>Field Point, Steel Shaft, Round Fletch, Large Nock</FONT></TD>
				<TD BGCOLOR="#CCCC99"><FONT SIZE=2>3396 cp</FONT></TD>
				<TD BGCOLOR="#CCCC99"><FONT SIZE=2>??</FONT></TD>
				<TD BGCOLOR="#CCCC99"><FONT SIZE=2>4</FONT></TD>
			</TR>
			<TR>
				<TD BGCOLOR="#CCCC99"><FONT SIZE=2>#13</FONT></TD>
				<TD BGCOLOR="#CCCC99"><FONT SIZE=2>Bladed Point, Wooden Shaft, Round Fletch, Large Nock</FONT></TD>
				<TD BGCOLOR="#CCCC99"><FONT SIZE=2>4772 cp</FONT></TD>
				<TD BGCOLOR="#CCCC99"><FONT SIZE=2>??</FONT></TD>
				<TD BGCOLOR="#CCCC99"><FONT SIZE=2>3</FONT></TD>
			</TR>
</TABLE>
</DIV>

<P>I will refer to these arrow types as #1 through #13 in the data below.
			
<P>Here is my actual level experience. I have not included the data for the 6 out of 8 bows I have made, although I am sure they also had an effect on my skill. I have seen my skill increase	while making a bow just once, at 36 making a Hickory/silk. 
			
<DIV ALIGN="center">

<P>
<TABLE BORDER=2 ALIGN="center">
<TR>
				<TD BGCOLOR="#006600"><FONT SIZE=2 COLOR="#ffff00">&nbsp;Level&nbsp;</FONT></TD>
				<TD BGCOLOR="#006600"><FONT SIZE=2 COLOR="#ffff00">&nbsp;Success&nbsp;/&nbsp;Tries&nbsp;</FONT></TD>
				<TD BGCOLOR="#006600"><FONT SIZE=2 COLOR="#ffff00">&nbsp;%&nbsp;Success&nbsp;</FONT></TD>
				<TD BGCOLOR="#006600"><FONT SIZE=2 COLOR="#ffff00">&nbsp;Buy&nbsp;/&nbsp;Resale&nbsp;</FONT></TD>
			</TR>
			<TR>
				<TD BGCOLOR="#CCCC99" ALIGN="center"><FONT SIZE=2>1-10</FONT></TD>
				<TD BGCOLOR="#CCCC99" ALIGN="center"><FONT SIZE=2>44/93</FONT></TD>
				<TD BGCOLOR="#CCCC99" ALIGN="center"><FONT SIZE=2>47.3%</FONT></TD>
				<TD BGCOLOR="#CCCC99" ALIGN="center"><FONT SIZE=2>2232/1572 cp</FONT></TD>
			</TR>
			<TR>
				<TD BGCOLOR="#CCCC99" ALIGN="center"><FONT SIZE=2>11-20</FONT></TD>
				<TD BGCOLOR="#CCCC99" ALIGN="center"><FONT SIZE=2>21/42</FONT></TD>
				<TD BGCOLOR="#CCCC99" ALIGN="center"><FONT SIZE=2>50.0%</FONT></TD>
				<TD BGCOLOR="#CCCC99" ALIGN="center"><FONT SIZE=2>1455/882 cp</FONT></TD>
			</TR>
			<TR>
				<TD BGCOLOR="#CCCC99" ALIGN="center"><FONT SIZE=2>21-30</FONT></TD>
				<TD BGCOLOR="#CCCC99" ALIGN="center"><FONT SIZE=2>45/80</FONT></TD>
				<TD BGCOLOR="#CCCC99" ALIGN="center"><FONT SIZE=2>56.3%</FONT></TD>
				<TD BGCOLOR="#CCCC99" ALIGN="center"><FONT SIZE=2>2960/1835 cp</FONT></TD>
			</TR>
			<TR>
				<TD BGCOLOR="#CCCC99" ALIGN="center"><FONT SIZE=2>31-40</FONT></TD>
				<TD BGCOLOR="#CCCC99" ALIGN="center"><FONT SIZE=2>22/52</FONT></TD>
				<TD BGCOLOR="#CCCC99" ALIGN="center"><FONT SIZE=2>42.3%</FONT></TD>
				<TD BGCOLOR="#CCCC99" ALIGN="center"><FONT SIZE=2>2380/1830 cp</FONT></TD>
			</TR>
			<TR>
				<TD BGCOLOR="#CCCC99" ALIGN="center"><FONT SIZE=2>41-50</FONT></TD>
				<TD BGCOLOR="#CCCC99" ALIGN="center"><FONT SIZE=2>30/51</FONT></TD>
				<TD BGCOLOR="#CCCC99" ALIGN="center"><FONT SIZE=2>58.8%</FONT></TD>
				<TD BGCOLOR="#CCCC99" ALIGN="center"><FONT SIZE=2>2993/2243 cp</FONT></TD>
			</TR>
			<TR>
				<TD BGCOLOR="#CCCC99" ALIGN="center"><FONT SIZE=2>51-51</FONT></TD>
				<TD BGCOLOR="#CCCC99" ALIGN="center"><FONT SIZE=2>15/28</FONT></TD>
				<TD BGCOLOR="#CCCC99" ALIGN="center"><FONT SIZE=2>53.6% </FONT></TD>
				<TD BGCOLOR="#CCCC99" ALIGN="center"><FONT SIZE=2>1904/1529 cp</FONT></TD>
			</TR>
			</TABLE>
			</DIV>
			
<P>So as I am currently at level 51 fletching, it has cost me 13924 cp, or 14 platinum to achieve. Also, add in the cost of the fletching kit, 1250 cp for a total cost of 15.1 platinum. Early, I sold the arrows back for a loss to offset costs. Now, as arrows are more expensive to make and the same buyback price, I just keep them for myself and to give away with sold bows. I am half way to Mastery for only 15 plat. Please keep in mind though that the arrow roughly double in cost each step from here on. This will severely increase the cost to gain levels of course.
			
<P>You can see that I have had a nearly 50% success ratio straight through. Things seem to get a lot worse as you triv out #2. You have to pay more for the arrows, but the resale to merchants stays the same! #2 cost 37 cp. #3 cost 49 that is a 32.4% increase in costs. The resale continues at the same level at least through #4, which suggests that you should just use the arrows that you make, rather than selling them back.
			
<P>Now, as for bows, I have had the following trials :

<P>	At skill 36 I made a trivial hickory/hemp, a trivial hickory/linen and made 2/3 on hickory/silk. At 37 I made 1/1 on hickory/silk. At 40 I made 0/1 on hickory/silk. At 48 I made 1/1 on Elm/hemp
			
<P>I was able to sell off the extra bows for an average of 5 gold apiece, regardless of which type they were. I suspect that the Hickory/Linen bow was first trivial at 36 and that if I try a hickory/silk after 46 it will be trivial. I will need to research this, but it seems that when the next arrow becomes trivial, so does the next bow.

<P>I used to think that having the various books was useless, but I now feel that holding the appropriate book in one of your main 8 inventory slots actually may help the skill increase faster, and possibly help with success %.

<P>There also seems to be a correlation between success and skill increase. While it is possible to become better at a skill while failing, only 9 of my 51 increases have happened on failed attempts. That means 82% of my skill increases happened on a successful attempt. While the cost factor is the main motivator here, this would seem to indicate that you should do the EASIEST non-trivial thing you can, so that you get more success. Fortunately, easiest also seems to be cheapest for fletchers.

<P>If you have any questions you can <A HREF="mailto:aspenkiddd@yahoo.com">e-mail</A> them to me at or give me a tell on the Tarew Marr my chars. name is Jynon.

<P>Good Luck,<BR><BR>

<B>Jynon Xantheothis</B><BR>
23rd Paladin<BR>
Tarew Marr Seekers of Lore<BR>

</TD>
<TD BGCOLOR="#BEA279" width=20></TD>
</TR>
</TABLE>	

	</TD>
	<TD width="64"></FONT></TD>
<TR>
	<TD><IMG SRC = "../graphics/botc000.jpg" WIDTH = 63 HEIGHT = 87></TD>
	<TD><IMG SRC = "../graphics/botc001.jpg" WIDTH = 473 HEIGHT = 87></TD>
	<TD><IMG SRC = "../graphics/botc002.jpg" WIDTH = 64 HEIGHT = 87></TD>
</TR>
</TABLE>
<BR>
<IMG SRC="http://service.bfast.com/bfast/serve?bfmid=1375281&siteid=40292692&bfpage=pc" BORDER="0" WIDTH="1" HEIGHT="1" NOSAVE ><A HREF="http://service.bfast.com/bfast/click?bfmid=1375281&siteid=40292692&bfpage=pc" TARGET="_new"><IMG SRC="http://affiliate.gamestop.com/affIMG/pc_120x60.gif" BORDER="0" WIDTH="120" HEIGHT="60" ALT="PC Games at GameStop.com"></A>
<BR>
<BR>
</DIV>
</BODY>
</HTML