<HTML>
<HEAD>
<TITLE>Welcome to Media and Games Online Network - MGON</TITLE>
<META name="description" content="MGON - The Gamer's Choice for gaming news. Get the hottest info from the gaming industry.
.">
<META name="keywords" content="MGON, MGO, Interviews, Game previews, Game downloads, Gaming Network, , Gaming News, News, Multiplayer, Games, PC Games, Console Games, Reviews, Forum, MGON International AB, Action, Strategy, Simulation, Roleplay, Racing">
<META name="robots" content="index,follow">
<!--
-->
<script language="JavaScript" type="text/javascript">
<!--
function go(where) {
  if(where != "void" && where!="") location.href = where;
}
wallPaperWindowsLength = 0;

function reply(tid,pid,cid,lang) {

  url = "/reply.phtml?tid=" + tid + "&pid=" + pid + "&id=" + cid + "&language=" + lang + '&ref=%2Fcorporate%2Findex.phtml';
  ipwindow = open("","prewindow","scrollbars=yes,toolbar=no,height=400,width=400");
  ipwindow.location.href = url;
        
}

function rateit(id,vote) {
    if(vote != "") {
		document.rate.content_id.value = id;
		document.rate.vote.value = vote;
		document.rate.submit();
	}
}

function screenshot(cid,pid) {

  url = "/screenshot.phtml?cid=" + cid + "&pid=" + pid;
  ipwindow = open("","prewindow","scrollbars=yes,toolbar=no,height=630,width=710");
  ipwindow.location.href = url;
        
}

function relatedmedia(url) {

  ipwindow = open("","prewindow","scrollbars=yes,toolbar=no,height=300,width=300");
  ipwindow.location.href = url;
        
}
function MM_preloadImages() { //v3.0
  var d=document; if(d.images){ if(!d.MM_p) d.MM_p=new Array();
    var i,j=d.MM_p.length,a=MM_preloadImages.arguments; for(i=0; i<a.length; i++)
    if (a[i].indexOf("#")!=0){ d.MM_p[j]=new Image; d.MM_p[j++].src=a[i];}}
}
function MM_findObj(n, d) { //v4.0
  var p,i,x;  if(!d) d=document; if((p=n.indexOf("?"))>0&&parent.frames.length) {
    d=parent.frames[n.substring(p+1)].document; n=n.substring(0,p);}
  if(!(x=d[n])&&d.all) x=d.all[n]; for (i=0;!x&&i<d.forms.length;i++) x=d.forms[i][n];
  for(i=0;!x&&d.layers&&i<d.layers.length;i++) x=MM_findObj(n,d.layers[i].document);
  if(!x && document.getElementById) x=document.getElementById(n); return x;
}
function MM_swapImgRestore() { //v3.0
  var i,x,a=document.MM_sr; for(i=0;a&&i<a.length&&(x=a[i])&&x.oSrc;i++) x.src=x.oSrc;
}
function MM_swapImage() { //v3.0
  var i,j=0,x,a=MM_swapImage.arguments; document.MM_sr=new Array; for(i=0;i<(a.length-2);i+=3)
   if ((x=MM_findObj(a[i]))!=null){document.MM_sr[j++]=x; if(!x.oSrc) x.oSrc=x.src; x.src=a[i+2];}
}

function getWall(id,name) {
  url = "/getwall.phtml?thisid=" + id + "&thisname=" + name;

	ipwindow = open("","prewindow_"+wallPaperWindowsLength,"fullscreen=no,resizable=yes,scrollbars=yes,toolbar=yes,height=600,width=800");        
        ipwindow.location.href = url;
	wallPaperWindowsLength++;

}

function getFile(id,name) {
  url = "/common/getfile.phtml?thisid=" + id + "&thisname=" + name;
  ipwindow = open("","prewindow","scrollbars=no,toolbar=no,height=200,width=495");
  ipwindow.location.href = url;
}
function localDate(dateStr) {
  now = new Date();
  var ar1 = now.toString().split(" ");
  var addH = -100;
  var addM = -100;
  var gmt = new Array(new Array());
  gmt["PST"] = -8;
  gmt["MST"] = -7;
  gmt["CST"] = -6;
  gmt["EST"] = -5;
  gmt["UTC"] = 0;
  if(ar1[4].indexOf("+") != -1) {
    var gm = ar1[4].split("+");
    gm[2] = 0-gm[1].substr(0,2);
    addH = Number(gm[2]);
    gm[2] = 0-gm[1].substr(2,2);
    addM = Number(gm[2]);
  }
  if(ar1[4].indexOf("-") != -1) {
    var gm = ar1[4].split("-");
    gm[2] = gm[1].substr(0,2);
    addH = Number(gm[2]);
    gm[2] = gm[1].substr(2,2);
    addM = Number(gm[2]);
  }
  if(addH == -100) {
    addH = gmt[ar1[4]];
    addM = 0;
  }
  there = new Date(dateStr);
  nowP = Date.parse(there);
  if(addH > 0) nowP -= 3600000;
  nowP += Number(addH)*3600000;
  nowP += Number(addM)*60000;
  realD = new Date(nowP);
  real = realD.toLocaleString();
  //  document.write(real[0] + " " + real[1] + " " + real[2] + " " +real[3]);
  document.write(real);
}
//-->
</script>

<script language="JavaScript">
<!--
function MM_reloadPage(init) {  //reloads the window if Nav4 resized
  if (init==true) with (navigator) {if ((appName=="Netscape")&&(parseInt(appVersion)==4)) {
    document.MM_pgW=innerWidth; document.MM_pgH=innerHeight; onresize=MM_reloadPage; }}
  else if (innerWidth!=document.MM_pgW || innerHeight!=document.MM_pgH) location.reload();
}
MM_reloadPage(true);
// -->
</script>
<link rel="stylesheet" href="/corporate/newstyle.css" type="text/css">



</HEAD>

<body bgcolor="#264B8A" text="#EEEEEE" link="#FFFFFF" vlink="#FFFFFF" alink="#FFFFFF" leftmargin="0" topmargin="0" marginwidth="0" marginheight="0">
 
<table width="750" border="0" cellspacing="0" cellpadding="0" align="center">
  <tr> 
    <td><img src="/corporate/images/top.jpg" width="750" height="105" usemap="#Map" border="0"></td>
  </tr>
</table>
<map name="Map"> 
  <area shape="rect" coords="105,21,274,45" href="/corporate/index.phtml" alt="MGON International AB" title="MGON International AB">
  <area shape="rect" coords="106,60,273,83" href="/corporate/services/index.phtml" alt="Services" title="Services">
  <area shape="rect" coords="477,22,644,45" href="/press/index.phtml" alt="Press Center" title="Press Center">
  <area shape="rect" coords="476,60,644,83" href="/corporate/mediakit/index.phtml" alt="Mediakit" title="Mediakit">
  <area shape="rect" coords="299,28,452,77" href="http://www.mgon.com" alt="MGON Home" title="MGON Home">
</map>
<table width="750" border="0" cellspacing="0" cellpadding="0" align="center">
  <tr>
    <td><img src="/corporate/images/mgon/mgonheadleft.jpg" width="536" height="52"></td>
    <td><img src="/corporate/images/mgon/mgonheadright.jpg" width="214" height="52"></td>
  </tr>
</table>
<table width="750" border="0" cellspacing="0" cellpadding="0" align="center" background="/newimages/misc/50x50pix.gif">
  <tr>
    <td width="41"><img src="/corporate/images/subleft.gif" width="41" height="21"></td>
    <td bgcolor="#000000" background="/newimages/misc/50x50black.gif" width="100%"><a href="/corporate/index.phtml" class="yellowlinks">MGON 
      International AB</a> <span class="Bolded">|</span> <a href="/corporate/mgon/contact.phtml" class="yellowlinks"></a><a href="/corporate/mgon/staff.phtml" class="yellowlinks">Staff</a> 
      <span class="Bolded">|</span> <a href="/corporate/mgon/contact.phtml" class="yellowlinks">Contacts</a> 
      <span class="Bolded">|</span> <span class="yellowlinks"><a href="/corporate/mgon/partners.phtml" class="yellowlinks">Partners</a> 
      <span class="Bolded">|</span> <span class="yellowlinks"><a href="/corporate/mgon/staff_bios.phtml" class="yellowlinks">Staff 
      Bios </a></span></span></td>
    <td align="right" width="239"><img src="/corporate/images/mgon/mgonsubright.jpg" width="239" height="21"></td>
  </tr>
</table>
<table width="750" border="0" cellspacing="0" cellpadding="0" align="center" background="/corporate/images/stretch.gif">
  <tr>
    <td>
      <table width="750" border="0" cellspacing="0" cellpadding="0" align="center" background="/newimages/misc/50x50pix.gif">
        <tr> 
          <td width="41" valign="top"><img src="/corporate/images/leftbg.gif" width="42" height="282"></td>
          <td valign="top" width="439"><br>
            <span class="blackbolded">MGON International &#150; a company introduction 
            </span> 
            <p>MGON International is a leading Internet games and entertainment 
              portal.<br>
              The business currently wholly owns and operates more than 40 high-quality<br>
              web sites devoted to a large variety of computer and console games. 
              MGON&#146;s<br>
              domains currently receive 2 million unique visitors and serve over 
              40 million page views per month, and its audience is growing at 
              a rate of over<br>
              20 per cent per month.</p>
            <p>MGON&#146;s ability to increase and retain its user base is founded 
              on two principles, obtaining strong word-of-mouth publicity, driving 
              up its audience numbers, and delivering high quality unique content, 
              aimed at retaining its audience.</p>
            <p>Unlike many other businesses in this sector MGON does not operate 
              an affiliate type model, MGON owns all of its domains and sites, 
              and therefore receives the full benefit of revenues generated. Nevertheless 
              the business is able to operate with a thin cost structure. MGON&#146;s 
              direct work force comprises 18 full-time employees involved in strategy, 
              technology, development and content control.</p>
          </td>
          <td align="right" width="270" valign="top"><img src="/corporate/images/mgon/middle.jpg" width="270" height="282"></td>
        </tr>
      </table>
    </td>
  </tr>
</table>
<table width="750" border="0" cellspacing="0" cellpadding="0" align="center" background="/corporate/images/stretch.gif">
  <tr>
    <td>
      <table width="750" border="0" cellspacing="0" cellpadding="0" align="center" background="/newimages/misc/50x50pix.gif">
        <tr> 
          <td width="41"> 
            <p><img src="/newimages/misc/1pix.gif" width="42" height="1"></p>
          </td>
          <td valign="top"> 
            <p><br>
              <span class="blackbolded">The Network</span><br>
              Content is provided to MGON through its Site Manager/Site Contributor 
              network, whereby members of each community are selected to provide 
              content, which is edited and controlled by a Site Manager via the 
              business&#146; proprietary Intranet software application, NetOffice. 
            </p>
            <p>With NetOffice, MGON is also able to homogenise the design of all 
              its sites, while the graphics resemble the atmosphere of the games 
              covered. By using homogenous design templates, MGON has established 
              a leading brand, renowned amongst gamers. </p>
            <p>MGON operates some of the world&#146;s largest games communities. 
              Its most popular site, the award winning &#147;The Sims Resources&#148; 
              handles over 3,000,000 downloads weekly, 450,000 unique users per 
              month and serves over 20 million page views per month. The web site 
              was, in addition, recently voted &#147;Best of Net&#148; by about.com, 
              and has been Maxis&#146; (the developer of the game) featured site 
              four times.</p>
          </td>
          <td width="41"><img src="/newimages/misc/1pix.gif" width="42" height="1"></td>
        </tr>
      </table>
    </td>
  </tr>
</table>
<table width="750" border="0" cellspacing="0" cellpadding="0" align="center">
  <tr>
    <td><img src="/corporate/images/bottom.gif" width="750" height="47"></td>
  </tr>
</table>
</BODY>

</HTML>


