<!--
                 This page has been created by Renaissance IT
   Renaissance Internet Technologies Copyright (c) 1999 All Rights Reserved.

             for more info on our products, please visit :
                        http://www.renaissance.nl/

	This script has been written by Roy Boverhof <rboverhof@renaissance.nl>
	
        Pagename                : members.html
        Last Updated    		: 13-6-1999
-->

<HTML>
<HEAD>
	<TITLE>the Seekers of Lore : Members</TITLE>
</HEAD>

<BODY BGCOLOR="#000000" TEXT="#FFFFFF" LINK="#FFF000">
<DIV ALIGN="center">
<BR>
<!-- FGB Banner Code -->
<SCRIPT LANGUAGE="JavaScript">
<!-- Hide from old browsers
now = new Date();
random = now.getTime();

// Modify to reflect site specifics
site = "http://ds.cybereps.com";
target = "/SITE=FGN/AREA=EQLORE/AAMSZ=BANNER";

document.write('<IFRAME SRC="' + site + '/hserver/acc_random=' + random + target + '"');
document.write(' NORESIZE SCROLLING=NO HSPACE=0 VSPACE=0 FRAMEBORDER=0 MARGINHEIGHT=0 MARGINWIDTH=0 WIDTH=468 HEIGHT=60>');

document.write('<SCR');
document.write('IPT SRC="' + site + '/jnserver/acc_random=' + random + target + '">');
document.write('</SCR');
document.write('IPT>');

document.write('</IFRAME>');
// End Hide -->
</SCRIPT>

<NOSCRIPT><A HREF="http://ds.cybereps.com/accipiter/adclick/SITE=FGN/AREA=EQLORE/AAMSZ=BANNER"><IMG SRC="http://ds.cybereps.com/accipiter/nserver/SITE=FGN/AREA=EQLORE/AAMSZ=BANNER" border="0"></A></NOSCRIPT>
<!-- END FGB Banner Code --><BR>	
<TABLE CELLSPACING = 0 CELLPADDING = 0 BORDER = 0>
<TR>
	<TD width="63"><IMG SRC = "graphics/topc000.jpg" WIDTH = 63 HEIGHT = 87></TD>
	<TD width="473"><IMG SRC = "graphics/topc001.jpg" WIDTH = 473 HEIGHT = 87></TD>
	<TD width="64"><IMG SRC = "graphics/topc002.jpg" WIDTH = 64 HEIGHT = 87></TD>
</TR>
	<TD width="63"></TD>
	<TD BGCOLOR="#BEA279" width="460">
	<DIV ALIGN="CENTER">
	<IMG SRC="graphics/members.jpg">
	<TABLE WIDTH="460">
	<TR>
		<TD>
		<DIV ALIGN="CENTER"><FONT COLOR="#000000">
		This is our guild's member section.<BR>
		<BR>
		Here you can search for one of our members, or view the complete list.
		If you are a member of the Seekers of Lore, you can enter the member only area, or edit your personal information by using the links below.
		<BR><BR>
		If you are not a member, but wish to become one, you can apply to our guild using the "Become a Seeker" link to the left.
		</FONT>
		<BR><BR>
		<A HREF="mem_list.php3">Member List</A><BR>
		<A HREF="members.php3">Member search</A><BR>
		<A HREF="apply.phtml">Become a Seeker of Lore</A><BR>
		<A HREF="restricted/mem_change.php3">Change Member Details</A><BR>
		<A HREF="restricted/">Members only !</A><BR>
		</DIV>
		</TD>
	</TR>
	</TABLE>
	<TD width="64"></TD>
<TR>
	<TD><IMG SRC = "graphics/botc000.jpg" WIDTH = 63 HEIGHT = 87></TD>
	<TD><IMG SRC = "graphics/botc001.jpg" WIDTH = 473 HEIGHT = 87></TD>
	<TD><IMG SRC = "graphics/botc002.jpg" WIDTH = 64 HEIGHT = 87></TD>
</TR>
</TABLE>
<BR>
<SCRIPT LANGUAGE="JavaScript">
<!-- Hide from old browsers
now = new Date();
random = now.getTime();

// Modify to reflect site specifics
site = "http://ds.cybereps.com";
target = "/SITE=FGN/AREA=EQLORE/AAMSZ=BUTTON1";

document.write('<IFRAME SRC="' + site + '/hserver/acc_random=' + random + target + '"');
document.write(' NORESIZE SCROLLING=NO HSPACE=0 VSPACE=0 FRAMEBORDER=0 MARGINHEIGHT=0 MARGINWIDTH=0 WIDTH=120 HEIGHT=90>');

document.write('<SCR');
document.write('IPT SRC="' + site + '/jnserver/acc_random=' + random + target + '">');
document.write('</SCR');
document.write('IPT>');

document.write('</IFRAME>');
// End Hide -->
</SCRIPT>
<NOSCRIPT> <A HREF="http://ds.cybereps.com/accipiter/adclick/SITE=FGN/AREA=EQLORE/AAMSZ=BUTTON1">
<IMG SRC="http://ds.cybereps.com/accipiter/nserver/SITE=FGN/AREA=EQLORE/AAMSZ=BUTTON1" border="0"></A>
</NOSCRIPT>
<BR>
<BR>
</DIV>
</BODY>
</HTML>
