<!--
                 This page has been created by Renaissance IT
   Renaissance Internet Technologies Copyright (c) 1999 All Rights Reserved.

             for more info on our products, please visit :
                        http://www.renaissance.nl/

	This script has been written by Roy Boverhof <rboverhof@renaissance.nl>
	
        Pagename                : charter.html
        Last Updated    		: 13-6-1999
-->

<HTML>
<HEAD>
	<TITLE>the Seekers of Lore : Charter</TITLE>
</HEAD>

<BODY BGCOLOR="#000000" TEXT="#FFFFFF" LINK="#FFFFFF">
<DIV ALIGN="CENTER">
<BR>
<!-- FGB Banner Code -->
<SCRIPT LANGUAGE="JavaScript">
<!-- Hide from old browsers
now = new Date();
random = now.getTime();

// Modify to reflect site specifics
site = "http://ds.cybereps.com";
target = "/SITE=FGN/AREA=EQLORE/AAMSZ=BANNER";

document.write('<IFRAME SRC="' + site + '/hserver/acc_random=' + random + target + '"');
document.write(' NORESIZE SCROLLING=NO HSPACE=0 VSPACE=0 FRAMEBORDER=0 MARGINHEIGHT=0 MARGINWIDTH=0 WIDTH=468 HEIGHT=60>');

document.write('<SCR');
document.write('IPT SRC="' + site + '/jnserver/acc_random=' + random + target + '">');
document.write('</SCR');
document.write('IPT>');

document.write('</IFRAME>');
// End Hide -->
</SCRIPT>

<NOSCRIPT><A HREF="http://ds.cybereps.com/accipiter/adclick/SITE=FGN/AREA=EQLORE/AAMSZ=BANNER"><IMG SRC="http://ds.cybereps.com/accipiter/nserver/SITE=FGN/AREA=EQLORE/AAMSZ=BANNER" border="0"></A></NOSCRIPT>
<!-- END FGB Banner Code --><BR>
<TABLE CELLSPACING = 0 CELLPADDING = 0 BORDER = 0>
<TR>
	<TD width="63"><IMG SRC = "graphics/topc000.jpg" WIDTH = 63 HEIGHT = 87></TD>
	<TD width="473"><IMG SRC = "graphics/topc001.jpg" WIDTH = 473 HEIGHT = 87></TD>
	<TD width="64"><IMG SRC = "graphics/topc002.jpg" WIDTH = 64 HEIGHT = 87></TD>
</TR>
	<TD width="63"></TD>
	<TD BGCOLOR="#BEA279" width="460">
	<DIV ALIGN="CENTER">
	<IMG SRC="graphics/charter.jpg" WIDTH=199 HEIGHT=43 BORDER=0 ALT="">
	<BR>
	<TABLE WIDTH="460">
	<TR>
		<TD><FONT COLOR="#000000">

		<FONT SIZE="+1">W</FONT>e, the Seekers of Lore, are dedicated to the never-ending quest
		of learning all there is to know about Norrath.<BR> We are not biased 
		towards any one faction, race, class, or religion.<BR> All who desire 
		knowledge above all else are welcome within our guild.<BR> We, the 
		Seekers, realize there are those who would seek to deter us from 
		the path of Lore, and we are willing and able to defend our purpose 
		against such beings.<BR><BR>
		<FONT SIZE="+1">A</FONT> Seeker will give his own life in defense of 
		another Seeker, and if another guild or faction seeks to abuse one of 
		our members while performing his duties, the whole of the guild will 
		rise up in defense against the aggressor.<BR> These words as written shall 
		be our charter, and all who come willingly unto the Seekers of Lore 
		shall treat them as law.<BR>
		<BR>
		<FONT SIZE="+1">A</FONT>s well, in order to maintain the integrity of the guild, a Seeker
		will follow a code of conduct as outlined below.<BR>
		<BR>
		<FONT SIZE="+1">A</FONT>bove all, a Seeker should role-play their character in public.<BR>
		By this I mean they should keep all public actions, shouts, etc.<BR>
		in character, and use ooc, private tells, and personal conversation
		for non role-playing discussions.<BR> When people see a member of
		our guild, they will know that that is a person they would want
		to play with.<BR>
		<BR>
		<FONT SIZE="+1">R</FONT>ole-player's of both good and evil factions are welcome amongst our
		members, but role-playing an "evil" character does not give a member
		license to be abusive or offensive to other players, or do anything that
		reflects badly on the guild.<BR> This includes ooc foul language,
		harassment, kill stealing, or failing to show proper consideration when
		fighting in a large group situation.<BR> "I am role-playing that way…" is no 
		excuse because there is really no provision in the game to defend against
		such behavior from another PC.<BR> If anyone wishes to be a truly evil and 
		disliked player, then there is the Rallos Zek PvP server for them.<BR> 
		<BR>
		<FONT SIZE="+1">A</FONT>ll new members from now on will be considered on probation for the
		first month. Any indication that they are not behaving in a manner that
		truly reflects the guild's code, will be let go.<BR>
		</FONT>
	</TR>
	</TABLE>	
	<BR>
	<IMG SRC="graphics/signature.jpg" WIDTH=286 HEIGHT=91 BORDER=0 ALT="" ALIGN="RIGHT">
	</DIV>
	</TD>
	<TD width="64"></TD>
<TR>
	<TD><IMG SRC = "graphics/botc000.jpg" WIDTH = 63 HEIGHT = 87></TD>
	<TD><IMG SRC = "graphics/botc001.jpg" WIDTH = 473 HEIGHT = 87></TD>
	<TD><IMG SRC = "graphics/botc002.jpg" WIDTH = 64 HEIGHT = 87></TD>
</TR>
</TABLE>
<BR>
<SCRIPT LANGUAGE="JavaScript">
<!-- Hide from old browsers
now = new Date();
random = now.getTime();

// Modify to reflect site specifics
site = "http://ds.cybereps.com";
target = "/SITE=FGN/AREA=EQLORE/AAMSZ=BUTTON1";

document.write('<IFRAME SRC="' + site + '/hserver/acc_random=' + random + target + '"');
document.write(' NORESIZE SCROLLING=NO HSPACE=0 VSPACE=0 FRAMEBORDER=0 MARGINHEIGHT=0 MARGINWIDTH=0 WIDTH=120 HEIGHT=90>');

document.write('<SCR');
document.write('IPT SRC="' + site + '/jnserver/acc_random=' + random + target + '">');
document.write('</SCR');
document.write('IPT>');

document.write('</IFRAME>');
// End Hide -->
</SCRIPT>
<NOSCRIPT> <A HREF="http://ds.cybereps.com/accipiter/adclick/SITE=FGN/AREA=EQLORE/AAMSZ=BUTTON1">
<IMG SRC="http://ds.cybereps.com/accipiter/nserver/SITE=FGN/AREA=EQLORE/AAMSZ=BUTTON1" border="0"></A>
</NOSCRIPT>
<BR>
<BR>
</DIV>
</BODY>
</HTML>
