<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">

<html>
<head>
	<title>..:: EQBard : le site de Jonili le petit barde ::..</title>

<SCRIPT LANGUAGE="Javascript">
<!--
function fenetre(intitule,params) { 
var fen = window.open(intitule,'zoom',params); 
}
//-->
</script>

<style>
a.lientexte {color:#0B5040;text-decoration:none;}
a.lientexte:hover {color:#0B5040;text-decoration:underline;}
</style>
</head>

<body bgcolor='#CFE6E3' text='#000000' link='#0B5040' vlink='#000000' alink='#000000'>
<table width='680' border='0' cellspacing='0' cellpadding='0'>
<tr><td>
<table width='680' border='0' cellspacing='0' cellpadding='0'>
<tr>
<td width='680' align='right' valign='top'>
<img src='./img/commun/c01/carre80.gif' width='10' height='10' border='0' alt=''>
<img src='./img/commun/c01/carre70.gif' width='10' height='10' border='0' alt=''>
<img src='./img/commun/c01/carre60.gif' width='10' height='10' border='0' alt=''>
<img src='./img/commun/c01/carre50.gif' width='10' height='10' border='0' alt=''>
</td></tr>
<tr><td height='2'><img src='./img/commun/transparent.gif' height='2' alt='' border='0'></td></tr>
<tr><td width='680' height='1'><img src='./img/commun/c01/carre50.gif' width='680' height='1' alt='' border='0'></td></tr>
</table>
</td></tr><tr><td>
<table width='680' border='0' cellspacing='0' cellpadding='0'>
<tr><td width='120' valign='top'><table width='100%' border='0' cellspacing='0' cellpadding='0'>
<tr><td>
<font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>&nbsp;<br>
<img src='./img/commun/c01/carre70.gif' width='10' height='10' border='0' alt=''>&nbsp;<a href=index.php?menu=1&data=1 class=lientexte><b>Accueil</b></a><br>&nbsp;<br>
<img src='./img/commun/c01/carre70.gif' width='10' height='10' border='0' alt=''>&nbsp;<b>Equipement</b><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=32&data=31&inc=armures class=lientexte>Armures</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=33&data=31&inc=armes&order=1&sens=1&bard=1 class=lientexte>Armes</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=35&data=31&inc=slot class=lientexte>Par slot</a><br>&nbsp;<br>
<img src='./img/commun/c01/carre70.gif' width='10' height='10' border='0' alt=''>&nbsp;<b>Guides</b><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carreselect.gif' width='5' height='5' border='0' alt=''>&nbsp;Général<br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=42&data=42 class=lientexte>Tactiques</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=43&data=43 class=lientexte>Quêtes</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=44&data=44 class=lientexte>Zones</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=45&data=45 class=lientexte>Procs</a><br>&nbsp;<br>
<img src='./img/commun/c01/carre70.gif' width='10' height='10' border='0' alt=''>&nbsp;<b>Photos</b><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=51&data=51 class=lientexte>Atlas</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=52&data=52 class=lientexte>Bardes</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=54&data=54 class=lientexte>GM</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=55&data=55 class=lientexte>Divers</a><br>&nbsp;<br>
<img src='./img/commun/c01/carre70.gif' width='10' height='10' border='0' alt=''>&nbsp;<a href=index.php?menu=8&data=8 class=lientexte><b>Mode</b></a><br>&nbsp;<br>
<img src='./img/commun/c01/carre70.gif' width='10' height='10' border='0' alt=''>&nbsp;<b>Spells Sebilis</b><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=1001&data=10 class=lientexte>Barde</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=1002&data=10 class=lientexte>Belluaire</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=1003&data=10 class=lientexte>Chaman</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=1004&data=10 class=lientexte>Clerc</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=1005&data=10 class=lientexte>Druide</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=1006&data=10 class=lientexte>Enchanteur</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=1007&data=10 class=lientexte>Fléau d'ombre</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=1009&data=10 class=lientexte>Magicien</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=1012&data=10 class=lientexte>Nécromancien</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=1013&data=10 class=lientexte>Paladin</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=1014&data=10 class=lientexte>Rôdeur</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=1015&data=10 class=lientexte>Sorcier</a><br>&nbsp;<br>
<img src='./img/commun/c01/carre70.gif' width='10' height='10' border='0' alt=''>&nbsp;<a href=index.php?menu=11&data=11 class=lientexte><b>Words</b></a><br>&nbsp;<br>
<img src='./img/commun/c01/carre70.gif' width='10' height='10' border='0' alt=''>&nbsp;<a href=index.php?menu=6&data=6 class=lientexte><b>Liens</b></a><br>
<img src='./img/commun/c01/carre70.gif' width='10' height='10' border='0' alt=''>&nbsp;<a href=index.php?menu=7&data=7 class=lientexte><b>Download</b></a><br>
<img src='./img/commun/c01/carre70.gif' width='10' height='10' border='0' alt=''>&nbsp;<a href='http://forumsfr.ubi.com/messages/overview.asp?name=eq_themaeq_eqbardes' target='_blank' class=lientexte><b>Forum</b></a><br>
<img src='./img/commun/c01/carre70.gif' width='10' height='10' border='0' alt=''>&nbsp;<a href=mailto:jonili@eqbard.eqloft.com class=lientexte><b>M'écrire</b></a><br>&nbsp;<br>
<img src='./img/commun/c01/carre70.gif' width='10' height='10' border='0' alt=''>&nbsp;<a href=index.php?menu=9&data=9 class=lientexte><b>Backstage</b></a><br>&nbsp;<br></font></td></tr></table>
</td><td width='20' valign='top'><img src='./img/commun/c01/carre50.gif' width='10' height='10' border='0' alt=''>
<img src='./img/commun/c01/carre60.gif' width='10' height='10' border='0' alt=''>
<img src='./img/commun/c01/carre70.gif' width='10' height='10' border='0' alt=''>
<img src='./img/commun/c01/carre80.gif' width='10' height='10' border='0' alt=''>
</td><td width='540' align='left' valign='top'><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>&nbsp;<br><a href='index.php?menu=41&data=41 class=lientexte' class=lientexte><b>< Retour</b></a><br>&nbsp;<br><table width='100%' border='0' cellspacing='0' cellpadding='0'><tr><td colspan='2' bgcolor='#0B5040'><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2' color='white'><b>&nbsp;/hitsmode</b></font></td></tr><tr><td width ='10'>&nbsp;</td><td><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>&nbsp;<br>Avant, vous aviez systematiquement les lignes de Fight qui spammaient le chat, rendant impossible ou presque la lecture des /tell, /gu et autres messages qui pouvaient être importants... Ces trucs pouvaient être supprimés, mais on perdait des infos, qui tape qui, quel mob tape le cleric, suis-je bien en autofight ou suis-je immobile devant le mob, etc... <br>&nbsp;<br>
La commande /hitsmode resoud ce probleme : elle crée des fenêtres spécifiques pour afficher les messages des coups que vous prenez, des coups que vous mettez, et des coups que les autres perso ou les mobs donnent autour de vous (en tout donc, 3 fenêtres différentes). <br>&nbsp;<br>
Etant donné la richesse de configuration, il est difficile au debut de comprendre comment l'utiliser de façon convenable. Voici donc un petit guide pour comprendre son utilisation. 
<br>&nbsp;<br>

Il y a 3 commande hitsmode : 
<ul>
<li>"/hitsmode my" : les coups que je donne à ma cible 
<li>"/hitsmode me" : les coups que l'on me donne 
<li>"/hitsmode other" : les coups qui sont donnés par d'autres sur d'autres cibles que moi. 
</ul>

Pour créer la fentre, îl suffit de taper : <br>&nbsp;<br>
/hitsmode my (ou me ou other) a X Y b c d e f (avec des espace entre chaque parametre) 
<br>&nbsp;<br>
PANIQUEZ PAS ! je vais expliquer à quoi correspondent les lettres. 
<ul>
<li>a : ce paramétre indique le détail de l'affichage. Vous avez 4 possibilités : m2, m3, m4 et m5 
	<ul>
	<li>m2 mettra "Kaldanm slash a snow bunny for 36" 
	<li>m3 mettra "slash a snow bunny for 36" 
	<li>m4 mettra "slash 36" 
	<li>m5 mettra "36" 
	</ul>
A noter que m5 ne peut être mis que pour le /hitsmode my. 

<li>X Y : C'est la position de la fenêtre sur l'écran. Par exemple, "0 0" c'est tout en haut à gauche. mettez plutot "5 100" pour que la fenetre soit légérement décalée à droite et assez basse pour pouvoir lire le texte. Gardez à l'esprit que vous entrez la position du coin inférieur gauche de la fenêtre. 

<li>b : Un chiffre compris entre 1 et 10. C'est le nombre de lignes qui s'afficheront au maximum. Notez que ca determine directement la taille (hauteur) de la fenêtre. Attention aussi aàpositioner la fenêtre assez bas pour lire toutes les lignes. 

<li>c : Un chiffre compris entre 1 et 5. C'est la taille de la police de caractéres, un peu comme /chatfontsize avec la fenêtre générale de chat. Vous pouvez avoir des fenêtres avec des tailles de police differentes. 

<li>d : Il faut mettre soit 1 soit 0. Si vous mettez 1 vous aurez un titre à la fenetre de type "My hits" ou "Attack on me". Avec 0 les hits apparaisent dans une fenêtre sans titre. 

<li>e : Il faut mettre soit 1 soit 0. Si vous mettez 1 il y aura un fond grisé sous la fenêtre. Si vous mettez 0, les Hits apparaitront sans fond, directement sur l'ecran. 

<li>f : La longueur de la fenêtre. Ce chiffre n'a aucune importance si vous mettez 0 à la commande précédente (car pas de fenêtre apparente), mais reste obligatoire. Vous mettez la longueur en pixel de votre feneêre. 200 est très long, sinon si vous êtes en m4 ou m5 (paramêtre a) mettez quelque chose plus proche de 50. 
</ul>
Voila ! tout compris ? <br>
Sachez que ces fenetres n'apparaisent que en fight ! Quand la commande est prise, vous n'avez aucun message de retour, sinon il vous met le message avec tout les paramêtres (en anglais). La meilleure façon de tester ce truc est de se mettre à Gfay sur orc hill, taper les commandes, et provoquer les orcs. Modifiez ensuite les parametres pendant le fight. 
<br>&nbsp;<br>
Comme commande utiles vous avez aussi : 
<ul>
<li>/hitsmode my on : remet les messages dans la fenêtre de chat. Fonctionne aussi avec "me" et "other". 
<li>/hitsmode my off : désactive totalement les messages (chat et fenêtre de hits). Fonctionne aussi avec "me" et "other". 
<li>/clearhits: vide les fenêtres de hitsmode sans les supprimer. Si vous avez mis des énormes fenêtres cette commande sera utile. 
</ul>
Conseils : 
<ul>
<li>Un papier et un crayon ! Pour noter les locs et paramêtres à garder, c'est le must de la technologie, surtout pendant votre "periode de test". 
<li>Faites une macro avec vos Hitsmode une fois ceux-ci bien placés ! C'est toujours embêtant à retaper, et après vous pouvez faire joujou avec. Surtout, si vous avez plusieurs persos, vous pouvez décider d'avoir plusieurs dispositions de Hitsmode. 
<li>mes parametres actuels sont, à titre d'exemple : 
<ul>
<li>/hitsmode my m3 5 65 5 0 0 1 180 
<li>/hitsmode me m2 260 400 8 1 0 0 150 
<li>/hitsmode other m2 5 163 8 0 0 1 180 
</ul>
avec cette config, j'ai les coups que je me prend au millieu de l'écran juste au dessus de la fenêtre de chat, à côté de mon énergie (sans fenêtre de fond). Les coups que je mets aux autres sont en haut à gauche juste sous la barre de lag. Les coups que les autres mettent (mobs et équipiers) sont tout à gauche en dessous de la fenêtre des coups que je mets, et il y a huit lignes d'affichées. 
<li>Pour les classes des faibles (niveau HP bien sur), il vaut mieux mettre le Hitsmode des coups que vous prenez au millieu de l'écran avec une police géante... enfin c'est mon avis perso
<li>Le meilleur endroit pour s'entrainer est orc hill : vous testez "/hitsmode my" en tapant les orcs, "/hitsmode other" en se mettant à côté des newbies, et pour "hitsmode me" vous vous asseyez devant un orc ! pendant que la fenêtre est la, vous bidouillez les parametres... 
</ul>
<br>&nbsp;<br>
<b>Kaldanm</b>

</font>&nbsp;<br></td></tr></table>&nbsp;<br></font></td></tr></table>
</td></tr><tr><td>
<table width='680' border='0' cellspacing='0' cellpadding='0'>
<tr><td width='680' height='1'><img src='./img/commun/c01/carre50.gif' width='680' height='1' alt='' border='0'></td></tr>
<tr><td height='2'><img src='./img/commun/transparent.gif' height='2' alt='' border='0'></td></tr>
<tr>
<td width='680' align='left' valign='top'>
<img src='./img/commun/c01/carre50.gif' width='10' height='10' border='0' alt=''>
<img src='./img/commun/c01/carre60.gif' width='10' height='10' border='0' alt=''>
<img src='./img/commun/c01/carre70.gif' width='10' height='10' border='0' alt=''>
<img src='./img/commun/c01/carre80.gif' width='10' height='10' border='0' alt=''>
</td></tr>
</table>
</td></tr><tr><td align='center'>
<A target='_blank' href='http://www.eqloft.com/'><img src='./img/commun/hebergement.gif' width='122' height='31' border='0' alt=''></a></td></tr></table>

</body>
</html>
