<HTML>
<HEAD>
<TITLE>Welcome to Media and Games Online Network - MGON</TITLE>
<META name="description" content="MGON - The Gamer's Choice for gaming news. Get the hottest info from the gaming industry.
.">
<META name="keywords" content="MGON, MGO, Interviews, Game previews, Game downloads, Gaming Network, , Gaming News, News, Multiplayer, Games, PC Games, Console Games, Reviews, Forum, MGON International AB, Action, Strategy, Simulation, Roleplay, Racing">
<META name="robots" content="index,follow">
<link rel="stylesheet" href="/newstyle.css" type="text/css">
<!--
-->

<script language="JavaScript" type="text/javascript">
<!--
function go(where) {
  if(where != "void" && where!="") location.href = where;
}

function reply(tid,pid,cid,lang) {

  url = "/reply.phtml?tid=" + tid + "&pid=" + pid + "&id=" + cid + "&language=" + lang + '&ref=%2Fmediakit%2Findex.phtml';
  ipwindow = open("","prewindow","scrollbars=yes,toolbar=no,height=400,width=400");
  ipwindow.location.href = url;
        
}

function rateit(id,vote) {
    if(vote != "") {
		document.rate.content_id.value = id;
		document.rate.vote.value = vote;
		document.rate.submit();
	}
}

function screenshot(cid,pid) {

  url = "/screenshot.phtml?cid=" + cid + "&pid=" + pid;
  ipwindow = open("","prewindow","scrollbars=yes,toolbar=no,height=630,width=710");
  ipwindow.location.href = url;
        
}

function relatedmedia(url) {

  ipwindow = open("","prewindow","scrollbars=yes,toolbar=no,height=300,width=300");
  ipwindow.location.href = url;
        
}
function MM_preloadImages() { //v3.0
  var d=document; if(d.images){ if(!d.MM_p) d.MM_p=new Array();
    var i,j=d.MM_p.length,a=MM_preloadImages.arguments; for(i=0; i<a.length; i++)
    if (a[i].indexOf("#")!=0){ d.MM_p[j]=new Image; d.MM_p[j++].src=a[i];}}
}
function MM_findObj(n, d) { //v4.0
  var p,i,x;  if(!d) d=document; if((p=n.indexOf("?"))>0&&parent.frames.length) {
    d=parent.frames[n.substring(p+1)].document; n=n.substring(0,p);}
  if(!(x=d[n])&&d.all) x=d.all[n]; for (i=0;!x&&i<d.forms.length;i++) x=d.forms[i][n];
  for(i=0;!x&&d.layers&&i<d.layers.length;i++) x=MM_findObj(n,d.layers[i].document);
  if(!x && document.getElementById) x=document.getElementById(n); return x;
}
function MM_swapImgRestore() { //v3.0
  var i,x,a=document.MM_sr; for(i=0;a&&i<a.length&&(x=a[i])&&x.oSrc;i++) x.src=x.oSrc;
}
function MM_swapImage() { //v3.0
  var i,j=0,x,a=MM_swapImage.arguments; document.MM_sr=new Array; for(i=0;i<(a.length-2);i+=3)
   if ((x=MM_findObj(a[i]))!=null){document.MM_sr[j++]=x; if(!x.oSrc) x.oSrc=x.src; x.src=a[i+2];}
}

function getWall(id,name) {
  url = "/getwall.phtml?thisid=" + id + "&thisname=" + name;
  ipwindow = open("","prewindow","fullscreen=no,resizable=yes,scrollbars=yes,toolbar=yes,height=600,width=800");
  ipwindow.location.href = url;
}

function getFile(id,name) {
  url = "/common/getfile.phtml?thisid=" + id + "&thisname=" + name;
  ipwindow = open("","prewindow","scrollbars=no,toolbar=no,height=200,width=495");
  ipwindow.location.href = url;
}
function localDate(dateStr) {
  now = new Date();
  var ar1 = now.toString().split(" ");
  var addH = -100;
  var addM = -100;
  var gmt = new Array(new Array());
  gmt["PST"] = -8;
  gmt["MST"] = -7;
  gmt["CST"] = -6;
  gmt["EST"] = -5;
  gmt["UTC"] = 0;
  if(ar1[4].indexOf("+") != -1) {
    var gm = ar1[4].split("+");
    gm[2] = 0-gm[1].substr(0,2);
    addH = Number(gm[2]);
    gm[2] = 0-gm[1].substr(2,2);
    addM = Number(gm[2]);
  }
  if(ar1[4].indexOf("-") != -1) {
    var gm = ar1[4].split("-");
    gm[2] = gm[1].substr(0,2);
    addH = Number(gm[2]);
    gm[2] = gm[1].substr(2,2);
    addM = Number(gm[2]);
  }
  if(addH == -100) {
    addH = gmt[ar1[4]];
    addM = 0;
  }
  there = new Date(dateStr);
  nowP = Date.parse(there);
  if(addH > 0) nowP -= 3600000;
  nowP += Number(addH)*3600000;
  nowP += Number(addM)*60000;
  realD = new Date(nowP);
  real = realD.toLocaleString();
  //  document.write(real[0] + " " + real[1] + " " + real[2] + " " +real[3]);
  document.write(real);
}
//-->
</script>
</HEAD>

<body bgcolor="#000000" text="#EEEEEE" link="#FFFFFF" vlink="#FFFFFF" alink="#FFFFFF" background="/newimages/backgrounds/bluelines.gif" leftmargin="0" topmargin="0" marginwidth="0" marginheight="0" onLoad="MM_preloadImages('/newimages/misc/arrow_on.gif')">
<table width="772" border="0" align="center" cellpadding="1" cellspacing="0" bgcolor="#000000">
  <tr>
    <td align="center"><!-- Webserver: w14 --><!-- loginUrl: http://everquest.mgon.com/common/loginNew.phtml?ref=www.mgon.com&page=/mediakit/index.phtml !--><!-- loginUrl: http://everquest.mgon.com/common/members.phtml?ref=www.mgon.com&page=/mediakit/index.phtml !--><script language="JavaScript">
<!--
function MM_openBrWindow(theURL,winName,features) { //v2.0
  window.open(theURL,winName,features);  
}
function login() {
  window.open('http://everquest.mgon.com/common/loginNew.phtml?ref=www.mgon.com&page=/mediakit/index.phtml', 'Login', 'width=250,height=250,scrollbars=yes'); 
}
function member() {
  window.open('http://everquest.mgon.com/common/members.phtml?ref=www.mgon.com&page=/mediakit/index.phtml', 'Member', 'width=500,height=600,scrollbars=yes'); 
}
//-->
</script>
<!-- Place the following code where you want an ad to appear -->
<SCRIPT LANGUAGE="JavaScript" SRC="http://ads.ad-flow.com/?DC=mgon-pop&JS=Y"></SCRIPT>
<NOSCRIPT>
<A HREF="http://ads.ad-flow.com/?SHT=mgon-pop"><IMG SRC="http://ads.ad-flow.com/?SIT=mgon-pop"></A>
</NOSCRIPT>
<table width="100%" border="0" cellspacing="0" cellpadding="0" background="/common/images/topplate/resize.gif">
  <tr> 
    <td> 
      <table width="488" border="0" cellspacing="0" cellpadding="0" background="/common/images/topplate/resize.gif">
				<tr> 
          <td><img src="/common/images/topplate/metalcorner.gif" width="5" height="20"></td>
				          <td><a href="javascript:login();"><img src="/common/images/topplate/memberlogin.gif" width="80" height="20" border="0"></a></td>					
			            <td><img src="/common/images/topplate/arrow.gif" width="10" height="20"></td>
          <td><img src="/common/images/topplate/metalcolumn.gif" width="3" height="20"></td>
          <td><a href="javascript:;" onClick="MM_openBrWindow('/common/sitemap.html','navigation','width=540,height=450')"><img src="/common/images/topplate/pc.gif" width="23" height="20" border="0"></a></td>
          <td><img src="/common/images/topplate/metalcolumn.gif" width="3" height="20"></td>
          <td><a href="javascript:;" onClick="MM_openBrWindow('/common/sitemap.html','navigation','width=540,height=450')"><img src="/common/images/topplate/action.gif" width="47" height="20" border="0"></a></td>
          <td><img src="/common/images/topplate/metalcolumn.gif" width="3" height="20"></td>
          <td><a href="javascript:;" onClick="MM_openBrWindow('/common/sitemap.html','navigation','width=540,height=450')"><img src="/common/images/topplate/roleplay.gif" width="62" height="20" border="0"></a></td>
          <td><img src="/common/images/topplate/metalcolumn.gif" width="3" height="20"></td>
          <td><a href="javascript:;" onClick="MM_openBrWindow('/common/sitemap.html','navigation','width=540,height=450')"><img src="/common/images/topplate/simulation.gif" width="70" height="20" border="0"></a></td>
          <td><img src="/common/images/topplate/metalcolumn.gif" width="3" height="20"></td>
          <td><a href="javascript:;" onClick="MM_openBrWindow('/common/sitemap.html','navigation','width=540,height=450')"><img src="/common/images/topplate/console.gif" width="56" height="20" border="0"></a></td>
          <td><img src="/common/images/topplate/metalcolumn.gif" width="3" height="20"></td>
          <td><a href="javascript:;" onClick="MM_openBrWindow('/common/sitemap.html','navigation','width=540,height=450')"><img src="/common/images/topplate/strategy.gif" width="64" height="20" border="0"></a></td>
          <td><img src="/common/images/topplate/metalcolumn.gif" width="3" height="20"></td>
          <td><a href="javascript:;" onClick="MM_openBrWindow('/common/sitemap.html','navigation','width=540,height=450')"><img src="/common/images/topplate/racing.gif" width="47" height="20" border="0"></a></td>
          <td><img src="/common/images/topplate/metalcolumn.gif" width="3" height="20"></td>
        </tr>
      </table>
    </td>
    <td background="/common/images/topplate/resize.gif" width="100%"><img src="/common/images/topplate/resize.gif" width="100%" height="20"></td>
    <td>
      <table width="88" border="0" cellspacing="0" cellpadding="0" background="/common/images/topplate/resize.gif">
        <tr>
          <td><img src="/common/images/topplate/metalcolumn.gif" width="3" height="20"></td>
          <td><a href="javascript:;" onClick="MM_openBrWindow('/common/sitemap.html','navigation','width=540,height=450')"><img src="/common/images/topplate/mgonetwork.gif" width="82" height="20" border="0"></a></td>
          <td><img src="/common/images/topplate/metalcorner.gif" width="5" height="20"></td>
        </tr>
      </table>
    </td>
  </tr>
</table>
<table width="100%" border="0" cellspacing="0" cellpadding="0" bgcolor="#000000">
  <tr> 
    <td><img src="http://193.45.143.23/1_1pix.gif?996715812" width="1" height="1" nosave></td>
  </tr>
</table>
</td>
  </tr>
</table>
<table width="772" border="0" cellspacing="0" cellpadding="0" align="center">
  <tr> 
    <td>

<TABLE width="772" border="0" cellspacing="0" cellpadding="0">

  <TR> 

    <TD><IMG src="/newimages/top/topleft.gif" width="592" height="81" border="0" usemap="#Map"><MAP name="Map"><AREA shape="rect" coords="13,36,138,76" href="http://www.mgon.com" alt="MGON Home" title="MGON Home"></MAP></TD>

    <TD width="100%" background="/newimages/top/resize.gif"><IMG src="/newimages/top/resize.gif" width="1" height="81"></TD>

    <TD><IMG src="/newimages/top/topright.gif" width="157" height="81"></TD>

  </TR>

</TABLE>


<TABLE width="772" border="0" cellspacing="0" cellpadding="0" bgcolor="#000000">
  <TR> 
		<TD align="center" width="130"> 
			<TABLE width="100%" border="0" cellspacing="0" cellpadding="0">
				<TR> 
					
          <TD align="center" background="/newimages/bannerarea/resize.gif"><OBJECT classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=4,0,2,0" width="120" height="60">
							<param name=movie value="http://www.mgon.com/flashmovies/mgochannel1.swf">
							<PARAM name=quality value=high>
							<PARAM name="menu" value="false">
							<embed src="http://www.mgon.com/flashmovies/mgochannel1.swf" quality=high pluginspage="http://www.macromedia.com/shockwave/download/index.cgi?P1_Prod_Version=ShockwaveFlash" 
type="application/x-shockwave-flash" menu="false" width="120" height="60">
							</EMBED> 
						</OBJECT></TD>
				</TR>
				<TR> 
					
          <TD><IMG src="/newimages/bannerarea/mgonchannel.gif" width="130" height="13"></TD>
				</TR>
			</TABLE>
		</TD>
		
    <TD align="center" width="490" valign="top"> 
      <!--Ad 468x60-->      <span class="smalltext"><NOLAYER><IFRAME SRC="http://ad.se.doubleclick.net/adi/mgon.com/;sz=468x60;ord=996715812?" bgcolor="#000000" width="468" height="60" frameborder="no" border="0" MARGINWIDTH="0" MARGINHEIGHT="0" SCROLLING="no"><A HREF="http://ad.se.doubleclick.net/jump/mgon.com/;abr=!ie;sz=468x60;ord=996715812?"><IMG SRC="http://ad.se.doubleclick.net/ad/mgon.com/;abr=!ie;sz=468x60;ord=996715812?" border="0" height="60" width="468"></A></IFRAME></NOLAYER><ILAYER id="layer1" visibility="hidden" width="468" height="60" align="center"></ILAYER></span><!--/Ad 468x60-->    </TD>
		
    <TD width="150" align="center" valign="top" background="/newimages/resizes/rightnav_black.gif"> 
      <!-- 120x60 code goes here -->
      
      <!-- 120x60 code goes here -->
    </TD>
	</TR>
</TABLE>
</td></tr></table>

<table width="772" border="0" cellspacing="0" cellpadding="0" align="center" background="/newimages/misc/50x50pix.gif">
  <tr>
    <td width="130" background="/newimages/resizes/leftnav.gif" valign="top"> 

<img src="/newimages/columns/sitecontent.gif" width="130" height="25"><br>
      <table width="130" border="0" cellspacing="0" cellpadding="0" bgcolor="#000000" background="/newimages/misc/50x50pix.gif">
        <tr> 
          <td> 
            <table width="130" border="0" cellspacing="1" cellpadding="0">
              <tr> 
                <td><img src="/newimages/misc/arrow_off.gif" width="12" height="19" name="a1"></td>
                <td bgcolor="#18355C" width="100%"> <a href="/"  class="bluelinks" onMouseOut="MM_swapImgRestore()" onMouseOver="MM_swapImage('a1','','/newimages/misc/arrow_on.gif',1)"> 
                  <div><img src="/newimages/misc/1pix.gif" width="5" height="1" border="0">Home</div>
                  </a>
                </td>
              </tr>
              <tr> 
                <td><img src="/newimages/misc/arrow_off.gif" width="12" height="19" name="a2"></td>
                <td bgcolor="#18355C" width="100%"><a href="/news.phtml"  class="bluelinks" onMouseOut="MM_swapImgRestore()" onMouseOver="MM_swapImage('a2','','/newimages/misc/arrow_on.gif',0)">
                  <div><img src="/newimages/misc/1pix.gif" width="5" height="1" border="0">News</div>
                  </a></td>
              </tr>
              <tr> 
                <td><img src="/newimages/misc/arrow_off.gif" width="12" height="19" name="a3"></td>
                <td bgcolor="#18355C" width="100%"><a href="/reviewindex.phtml"  class="bluelinks" onMouseOut="MM_swapImgRestore()" onMouseOver="MM_swapImage('a3','','/newimages/misc/arrow_on.gif',0)">
                  <div><img src="/newimages/misc/1pix.gif" width="5" height="1" border="0">Reviews</div>
                  </a></td>
              </tr>
              <tr> 
                <td><img src="/newimages/misc/arrow_off.gif" width="12" height="19" name="a4"></td>
                <td bgcolor="#18355C" width="100%"><a href="/previewindex.phtml"  class="bluelinks" onMouseOut="MM_swapImgRestore()" onMouseOver="MM_swapImage('a4','','/newimages/misc/arrow_on.gif',0)">
                  <div><img src="/newimages/misc/1pix.gif" width="5" height="1" border="0">Previews</div>
                  </a></td>
              </tr>
              <tr> 
                <td><img src="/newimages/misc/arrow_off.gif" width="12" height="19" name="a5"></td>
                <td bgcolor="#18355C" width="100%"><a href="/interviewindex.phtml"  class="bluelinks" onMouseOut="MM_swapImgRestore()" onMouseOver="MM_swapImage('a5','','/newimages/misc/arrow_on.gif',0)">
                  <div><img src="/newimages/misc/1pix.gif" width="5" height="1" border="0">Interviews</div>
                  </a></td>
              </tr>
              <tr> 
                <td><img src="/newimages/misc/arrow_off.gif" width="12" height="19" name="a6"></td>
                <td bgcolor="#18355C" width="100%"><a href="/articleindex.phtml"  class="bluelinks" onMouseOut="MM_swapImgRestore()" onMouseOver="MM_swapImage('a6','','/newimages/misc/arrow_on.gif',0)">
                  <div><img src="/newimages/misc/1pix.gif" width="5" height="1" border="0">Articles</div>
                  </a></td>
              </tr>
              <tr> 
                <td><img src="/newimages/misc/arrow_off.gif" width="12" height="19" name="a7"></td>
                <td bgcolor="#18355C" width="100%"><a href="/fileindex.phtml"  class="bluelinks" onMouseOut="MM_swapImgRestore()" onMouseOver="MM_swapImage('a7','','/newimages/misc/arrow_on.gif',0)">
                  <div><img src="/newimages/misc/1pix.gif" width="5" height="1" border="0">Downloads</div>
                  </a></td>
              </tr>
              <tr> 
                <td><img src="/newimages/misc/arrow_off.gif" width="12" height="19" name="a8"></td>
                <td bgcolor="#18355C" width="100%"><a href="http://www.mgoforum.com"  class="bluelinks" onMouseOut="MM_swapImgRestore()" onMouseOver="MM_swapImage('a8','','/newimages/misc/arrow_on.gif',0)">
                  <div><img src="/newimages/misc/1pix.gif" width="5" height="1" border="0">MGOforums</div>
                  </a></td>
              </tr>
            </table>
          </td>
        </tr>
      </table>  <table width="130" border="0" cellspacing="0" cellpadding="1" bgcolor="#000000">
        <tr>
          <td><img src="/newimages/misc/searchdummy.gif" width="128" height="136"></td>
        </tr>
      </table>
      <table width="130" border="0" cellspacing="0" cellpadding="0" bgcolor="#000000" background="/newimages/misc/50x50pix.gif">
        <tr> 
          <td> 
            <table width="130" border="0" cellspacing="1" cellpadding="0">
              <tr> 
                <td><img src="/newimages/misc/arrow_off.gif" width="12" height="19" name="a9"></td>
                <td bgcolor="#18355C" width="100%">
                  <a href="/company/"  class="bluelinks" onMouseOut="MM_swapImgRestore()" onMouseOver="MM_swapImage('a9','','/newimages/misc/arrow_on.gif',0)">
                  <div><img src="/newimages/misc/1pix.gif" width="5" height="1" border="0">The 
                    Company</div>
                  </a>
                </td>
              </tr>
              <tr> 
                <td><img src="/newimages/misc/arrow_off.gif" width="12" height="19" name="a10"></td>
                <td bgcolor="#18355C" width="100%">
                  <a href="/mediakit/"  class="bluelinks" onMouseOut="MM_swapImgRestore()" onMouseOver="MM_swapImage('a10','','/newimages/misc/arrow_on.gif',0)">
                  <div><img src="/newimages/misc/1pix.gif" width="5" height="1" border="0">Our 
                    Mediakit</div>
                  </a>
                </td>
              </tr>
              <tr> 
                <td><img src="/newimages/misc/arrow_off.gif" width="12" height="19" name="a11"></td>
                <td bgcolor="#18355C" width="100%">
                  <a href="/press.phtml"  class="bluelinks" onMouseOut="MM_swapImgRestore()" onMouseOver="MM_swapImage('a11','','/newimages/misc/arrow_on.gif',0)">
                  <div><img src="/newimages/misc/1pix.gif" width="5" height="1" border="0">Press 
                    Material</div>
                  </a>
                </td>
              </tr>
              <tr> 
                <td><img src="/newimages/misc/arrow_off.gif" width="12" height="19" name="a12"></td>
                <td bgcolor="#18355C" width="100%">
                  <a href="/contactus/"  class="bluelinks" onMouseOut="MM_swapImgRestore()" onMouseOver="MM_swapImage('a12','','/newimages/misc/arrow_on.gif',0)">
                  <div><img src="/newimages/misc/1pix.gif" width="5" height="1" border="0">Contact 
                    Us</div>
                  </a>
                </td>
              </tr>
            </table>
          </td>
        </tr>
      </table>
    </td>
    <TD width="642" valign="top" background="/newimages/backgrounds/middlecolumn_black_wide.gif"> 
      <table width="100%" border="0" cellspacing="0" cellpadding="0" background="/newimages/sections/resize.gif">
        <tr> 
          <td width="100%" valign="bottom">&nbsp; </td>
          <td align="right"><img src="/newimages/sections/mediakit.gif"></td>
        </tr>
      </table>
      <table width="642" border="0" cellspacing="0" cellpadding="0">
        <tr>
          <td><img src="/newimages/misc/1pixblack.gif" width="642" height="1"></td>
        </tr>
      </table>
      <table width="100%" border="0" cellspacing="0" cellpadding="12">
        <tr> 
          <td valign="top" width="100%"> 
            <p class="Headline"><a name="demographics"></a>Demographics</p>
            <p>What started out as the hobby of a handful of game enthusiasts 
              2 years ago has grown into a large multinational corporation employing 
              over 400 professionals across the globe. Media and Games Online 
              Network, the Gamers' Choice, is quickly becoming the premier portal 
              for avid gamers on the web. Built to be the ultimate games community 
              resource, by the people who play the games, MGON's fan sites provide 
              a huge spectrum of gaming information and resources for the web 
              generation audience. Today, the MGONetwork consists of over 40 top 
              quality websites. </p>
            <p>The MGONetwork currently serves an average of 40 million impressions 
              per month, to approximately 1,3 million monthly unique visitors. 
              Current trends indicate a 20% growth rate in monthly impressions. 
              MGON's increasing member database comprises at present of over 20,000 
              registered community members.</p>
            <p><b>Audience Profile</b></p>
            <p>The MGONetwork serves a mostly male audience that is very advanced 
              technically. They are devoted gamers who feel at home on the Internet. 
            </p>
            <p><i>Highly Desirable Demographic </i></p>
            <ul>
              <li>82% are male</li>
              <li>46% under 18</li>
              <li>27% 18-24 years</li>
              <li>18% 25-34 years </li>
            </ul>
            <p>Websites related to games popular with the female audience, such 
              as <a href="http://www.homecreatures.com/">HomeCreatures</a> and 
              the award winning <a href="http://www.thesimsresource.com/">The 
              Sims Resource</a> have increased the number of female visitors to 
              the MGONetwork. </p>
            <p><span class="Bolded"><b>Online Behaviour</b></span></p>
            <p>MGON visitors spend, on average, 30 hours a week online and each 
              visit to MGON lasts for nearly 25 minutes:</p>
            <ul>
              <li> 75% go online for downloading/purchasing software </li>
              <li>81% go online for game information </li>
              <li>90% go online for entertainment </li>
              <li>69% go online for game playing </li>
              <li>67% go online for technology news </li>
              <li>68% plan to purchase a product online</li>
            </ul>
            <p><i>MGON visitors are gaming experts </i></p>
            <p>78% of MGON visitors rate their level of gaming expertise as "advanced.&quot; 
              They have spent on average, 8 years playing PC games and 9 years 
              playing console games. The typical MGON visitor spends 16 hours 
              a week playing PC games and 5 hours a week playing console games.</p>
            <p> MGON users have recommended the network to an average of 7 people, 
              and 67% of visitors said MGON was their first choice for game information. 
            </p>
            <p><i>MGON visitors plan to invest in high-end products </i></p>
            <ul>
              <li> 72% Computer Hardware </li>
              <li>45% High Speed Internet Connection </li>
              <li>37% DVD Player </li>
              <li>32% Large Screen Display (19" +) </li>
              <li>28% Home Audio/Visual Equipment </li>
              <li>26% Digital Camera </li>
              <li>23% Desktop Computer </li>
              <li>19% LaserJet or Inkjet Printer </li>
            </ul>
            <p><i>Plan to spend on games next 12 months: </i></p>
            <ul>
              <li> 57% plan to spend $100-$500 on PC games </li>
              <li>33% plan to spend $100-$500 on Console games </li>
              <li>Average is $350 per person </li>
            </ul>
            <p> <i>Types of games planned for purchase next 12 months: </i></p>
            <p> PC Games:</p>
            <ul>
              <li>80% Action </li>
              <li>66% Adventure Role Play</li>
              <li>65% Strategy </li>
              <li>65% Simulation</li>
              <li>26% Sports</li>
            </ul>
            <p>Console Games:</p>
            <ul>
              <li>75% Action </li>
              <li>62% Adventure Role Play</li>
              <li>42% Sports </li>
              <li>34% Simulation </li>
              <li>30% Strategy</li>
            </ul>
            <p><i>Plan to buy gaming related products in the next 12 months: </i></p>
            <ul>
              <li> 80% PC Game Software </li>
              <li> 62% 3D Accelerator Card </li>
              <li>37% Console Games </li>
              <li>30% Simulator Accessories </li>
              <li>28% Controller </li>
              <li>28% Memory Card </li>
              <li>27% Gaming Console System </li>
              <li>14% Game Storage Device </li>
            </ul>
            <p>MGON visitors invest large amounts of time and money on their hobby, 
              they are keen to keep up with the latest technology, and play the 
              latest games. </p>
            <p>Further insight into the MGON visitor profile can be found in the 
              statistics from Cyber Dialogue, an Internet consumer trend research 
              organization; and from Interactive Digital Software Association</p>
            <p><i>Data, Insight and Analysis: </i></p>
            <ul>
              <li>30% of Internet users go online for games </li>
              <li>50% of game content users reported 10 or more visits to gaming 
                sites</li>
              <li> From year end 1998 to Q3 1999, there was a 55% growth in the 
                number of online gamers</li>
              <li> 40% of adult Internet users have changed their views of specific 
                brands due to information they received online! </li>
            </ul>
            <p><i>Interests of Net Enthusiasts:</i></p>
            <ul>
              <li> Movie & TV Fans also visit: n Game Sites 30% </li>
              <li>Sport Enthusiasts also visit: n Game Sites 32% </li>
              <li>Music Aficionados also visit: n Game Sites 35% </li>
            </ul>
            <p><i>Online Gamers also visit: </i></p>
            <ul>
              <li>Music Sites 53% </li>
              <li>Movie & TV Sites 49% </li>
              <li>Sports Sites 48% </li>
            </ul>
            <p><i>Who plays computer and video games? </i></p>
            <ul>
              <li>43% of people who play interactive games are women </li>
              <li>The average age of an interactive game player is 28 years old 
              </li>
            </ul>
            <ul>
              <li>For Computer Gamers... 
                <ul>
                  <li>28% under 18 </li>
                  <li>30% 18 - 35 </li>
                  <li>42% over 35 </li>
                </ul>
              </li>
              <li>For Console Gamers... 
                <ul>
                  <li> 42% under 18 </li>
                  <li>37% 18 - 35 </li>
                  <li>21% over 35 </li>
                </ul>
              </li>
            </ul>
            <p><i>Why do people play games?</i></p>
            <p> In 2000, 35% of all Americans rated playing computer and video 
              games as the most fun entertainment activity for the third consecutive 
              year. </p>
            <ul>
              <li>78% Games are challenging </li>
              <li>55% Games are a great stress reliever </li>
              <li>49% Games provide a lot of entertainment value for the money 
              </li>
              <li>39% Games are engrossing</li>
              <li> 37% Games are a interactive social experience that can be shared 
                with friends and family 
                <ul>
                  <li>59% play with friends. </li>
                  <li>33% play with brothers and/or sisters. </li>
                  <li>27% with spouse. </li>
                  <li>25% play with parents. </li>
                  <li>43% play with other family members. </li>
                </ul>
              </li>
            </ul>
            <p><i>Who purchases computer and video games? </i></p>
            <ul>
              <li>97% of people who purchase computer games and 87% of people 
                who purchase video games are 18 years or older. </li>
              <li>Of those under 18 years old who purchase games, 84% get their 
                parents permission. </li>
              <li>50% of people who purchase computer games are men and 50% are 
                women.</li>
              <li>52% of people who purchase console games are men and 48% are 
                women. </li>
            </ul>
            <p><span class="Bolded">Source:</span> Cyber Dialogue, Jan. 2000 and 
              IDSA </p>
            <p class="Headline"><a name="statistics"></a>Statistics</p>
            <p>Pageviews<br>
              During the month of March, the MGONetwork delivered 35 million impressions. 
              Current trends indicate an approximately 20% growth rate in monthly 
              impressions. </p>
            <p>Our Audience<br>
              The MGONetwork currently has over 1,3 million unique visitors each 
              month. Q1 2001 saw over 3,1 million unique visitors to the network.</p>
            <p><span class="Bolded">Source:</span> DART logs, March 2001 </p>
            <p><a name="bannerinfo"></a><span class="Headline">Banner Info</span></p>
            <p>Advertising is currently available in the following formats:</p>
            <ul>
              <li>468x60 banners: maximum size 12kb</li>
              <li>120x600 skyscrapers: maximum size 15 kb</li>
              <li>160x600 skyscrapers: maxiumu size 18kb</li>
              <li>120x90 buttons: maximum size 10kb</li>
              <li>120x60 buttons: maximum size 8kb</li>
              <li>125x125 buttons: maximum size 10kb<br>
              </li>
            </ul>
            <p>Each banner and button ad is located in the upper third of each 
              webpage within the MGONetwork. The image below illustrates the placement 
              of banner and button ads in our design.</p>
            <p><img src="/images/mediakit/bannerplacement2.jpg" width="400" height="187" border="1"></p>
            <p>MGON also offers targeted marketing campaigns that can be customized 
              to fit each clients specific needs.</p>
            <p><a name="contactinfo"></a><span class="Headline">Contact Info</span> 
            </p>
            <p>Please contact us directly for more information on targeted marketing 
              campaigns, advertising rates and any queries you may have.</p>
            <p><span class="Bolded">E-mail:</span> <a href="mailto:advertise@mgon.com">advertise@mgon.com</a>. 
              <br>
              <span class="Bolded">Phone: +46 270 735 30</span></p>
            </td>
        </tr>
      </table>
    </TD>
  </TR>
</TABLE>
 
<table width="772" border="0" cellspacing="0" cellpadding="0" align="center">
  <tr>
    <td><img src="/newimages/bottom/copyright.gif" width="621" height="30" border="0" usemap="#Map2"></td>
    <td><a href="/"><img src="/newimages/bottom/home.gif" width="75" height="30" border="0"></a></td>
    <td><a href="#top"><img src="/newimages/bottom/top.gif" width="76" height="30" border="0"></a></td>
  </tr>
</table>
<TABLE width="772" border="0" cellspacing="0" cellpadding="0" height="90" background="/images2/misc/50x50pix.gif" align="center">
  <TR bgcolor="#000000" align="center"> 
    <TD class="smalltext"><SCRIPT language="JavaScript"
src="http://adtegrity.spinbox.net/?DC=Mgon+Bottom&JS=Y&TARGET=_new">
</SCRIPT><NOSCRIPT><A href="http://adtegrity.spinbox.net/?SHT=Mgon+Bottom" target="_new"
height="468" width="60"><IMG src="http://adtegrity.spinbox.net/?SIT=Mgon+Bottom" border="0"></A></NOSCRIPT></TD>
  </TR>
</TABLE>
<map name="Map">
  <area shape="rect" coords="387,7,495,25" href="/privacy.phtml">
</map>
<map name="Map2">
  <area shape="rect" coords="384,4,496,26" href="/privacy">
</map>
  
<!--Bottom Layer-->
      <LAYER SRC="http://ad.se.doubleclick.net/adl/mgon.com/;sz=468x60;ord=996715812?" bgcolor="#000000" width="468" height="60" visibility="hidden" onLoad="moveToAbsolute(layer1.pageX,layer1.pageY);clip.height=60;clip.width=468; visibility='show';"></LAYER><!--End Bottom Layer--></BODY>

</HTML>


