<!--
   This page has been created by Renaissance IT
   Renaissance Internet Technologies Copyright (c) 1999 All Rights Reserved.
   for more info on our products, please visit : http://www.renaissance.nl/
   This script has been written by Roy Boverhof <rboverhof@renaissance.nl>
 
   Pagename             : main.phtml
   Last Updated    		: 03-16-2001
-->

<HTML>
<HEAD>
	<TITLE>the Seekers of Lore : Main</TITLE>
</HEAD>
<BODY BGCOLOR="#000000" TEXT="#ffffff" LINK="#fff000" VLINK="#fff000" marginwidth="0" marginheight="0">
<DIV align=center>
<BR>
<!-- FGB Banner Code -->
<SCRIPT LANGUAGE="JavaScript">
   <!-- Hide from old browsers
   now = new Date();
   random = now.getTime();
     
   // Modify to reflect site specifics
   site = "http://ds.cybereps.com";
   target = "/SITE=FGN/AREA=EQLORE/AAMSZ=BANNER";
   
   document.write('<IFRAME SRC="' + site + '/hserver/acc_random=' + random + target + '"');
   document.write(' NORESIZE SCROLLING=NO HSPACE=0 VSPACE=0 FRAMEBORDER=0 MARGINHEIGHT=0 MARGINWIDTH=0 WIDTH=468 HEIGHT=60>');
   
   document.write('<SCR');
   document.write('IPT SRC="' + site + '/jnserver/acc_random=' + random + target + '">');
   document.write('</SCR');
   document.write('IPT>');
   
   document.write('</IFRAME>');
   // End Hide -->
 </SCRIPT>
 <NOSCRIPT> 
   <A HREF="http://ds.cybereps.com/accipiter/adclick/SITE=FGN/AREA=EQLORE/AAMSZ=BANNER">
   <IMG SRC="http://ds.cybereps.com/accipiter/nserver/SITE=FGN/AREA=EQLORE/AAMSZ=BANNER" border="0"></A>
 </NOSCRIPT>
<!-- END FGB Banner Code --><table WIDTH="98%">
<tr>
	<td VALIGN="top">
	<TABLE cellPadding=3 cellSpacing=3 VALIGN="top">
    <TR>
      <TD VALIGN="top">
      <CENTER><B><FONT size=+1>Welcome to the "Seekers of Lore"</FONT></B></CENTER>
	  <font size="-1">
	  <P><FONT size=+1>W</FONT>e are an EverQuest guild devoted to the never ending quest for knowledge.
      <P><FONT size=+1>F</FONT>ounded by the glorious <A href="madwand.phtml">MadWand</A> and lead by the mighty <A href="http://www.loreSeekers.com/mem_detail.php3?search=2">Sorontar</A>, 
      the Seekers of Lore are devoted to collecting and cataloging all the EQ lore they can! Be it maps, quests, items or creative works by the players of EQ, we will have it here or link to where you can find it! So, please, 
	  take a moment and browse through our libraries. If you like what you see 
	  or have any comments to make, then feel free to sign our <A href="guestbook.php3">Guestbook</A>.<BR>
      <P><FONT size=+1>S</FONT>incerely,<BR>
	  <A href="mailto:webmaster@loreSeekers.com"><B>Sorontar D'Agora</B></A> 
      </P>
	  </font>
	  </TD>
	</TR>

	<tr><td><BR></td></tr>
	
	<TR>
		<TD VALIGN="top">
		<DIV ALIGN="left"><B>Site news :</B><BR><FONT FACE="Verdana, Arial" SIZE=+1 COLOR="#FFFF00"><A NAME="2001177151"><B>Long awaited updates</B></A></FONT><BR><BR><TABLE><TR><TD><FONT FACE="Verdana, Arial" SIZE=2>Hail all,
<P>
I have just added a new guide : <A HREF="guides/disciplines.phtml">Treatise on Disciplines</A> by Gorthag Bashinfletcher.
<P>
If you are interested in reading a nice story by Galun Stormfury, check out : <A HREF="stories/fishing.phtml">Fishing for Trouble</A> !
<P>
I hope I have time to digitize some footage of Luclin I made at E3 soon, don't worry... I won't forget to do that...hehe....
<P>
I also added some new links in our <A HREF="links.phtml">links</A> section
<P>
At the moment I am working on software that will allow everyone to submit news, quests, items, etc... The site has become too much for me to handle by myself... I know there hasn't been a lot of activity here lately, but I promise to make that up to you. In about 3 weeks I will finally have some time to install new messageboards, and maybe even a couple of new features !
<P>
Sincerely,
<P>
Sorontar D'Agora<BR>
Seekers of Lore</FONT></TD></TR></TABLE></DIV><BR><DIV ALIGN="left"><B>EQ news :</B><BR><FONT FACE="Verdana, Arial" SIZE=+1 COLOR="#FFFF00"><A NAME="2001138031"><B>Shadows of Luclin</B></A></FONT><BR><BR><TABLE><TR><TD><FONT FACE="Verdana, Arial" SIZE=2>Hail all,
<P>
I have made some great shots of Luclin, I must say... It looks really good. The whole world has a lot of detail, you can actually see the grass :)
<P>
I will get back home somewhere next wednesday, so I'll be able to digitize the video I made by then.
<P>
One of the developers of Verant told me that the facial expression in Luclin are going to be a really cool feature... I didn't manage to get them on tape but... I have a nice view of Norrath...hehe....
<P>
Greetings from sunny LA,
<P>
Sorontar D'Agora</FONT></TD></TR></TABLE></DIV>		</TD>
	</TR>
	</TABLE>
	<BR>
	</TD>
	<TD VALIGN="top">
	<TABLE CELLPADDING="3" CELLSPACING="3" WIDTH="250" VALIGN="top" BORDER="0">
	<TR>
		<TD VALIGN="top" bgcolor=#00001f>
			<P><CENTER><B>Images of Norrath</B></CENTER>
			<DIV ALIGN="center"><A HREF="http://www.loreseekers.com/screenshots/daily/daily_image.jpg"><IMG SRC="http://www.loreseekers.com/screenshots/daily/tn_daily_image.jpg" BORDER=0 HSPACE=0></A><BR>
<FONT FACE="Verdana" COLOR="#00ffff" SIZE="-2">
Levitating over the Dreadlands.<BR>
By Avonlia, Ranger of Tunare
</FONT></DIV>
		</TD>
	</TR>
	
	<tr><td><BR></td></tr>
	
	<TR>
		<TD VALIGN="top" bgcolor=#00001f>
		<DIV ALIGN="center">
			<TABLE>
			<TR>
				<TD ROWSPAN="2"><IMG SRC="graphics/evervel.jpg" WIDTH=50 HEIGHT=60 ALT="" BORDER="0"></TD>
				<TD ALIGN="center"><FONT FACE="Verdana" SIZE="2"><B>Buy "the Scars of Velious" now!</B></FONT></TD>
			</TR>
			<TR>
				<TD ALIGN="center"><A HREF="http://www.dragon.ca/cgi-bin/affiliate.cgi?affid=LoreSeekersRB&id=EVERVEL" TARGET="_new"><IMG SRC="graphics/orderfrom.gif" ALIGN="Center" WIDTH ="120" HEIGHT ="26" ALT="Buy EverQuest Now!" BORDER="0"></A></TD>
			</TR>
			</TABLE>
		</DIV>
		</TD>
	</TR>
	
	<tr><td><BR></td></tr>
	
	<TR>
		<TD VALIGN="top" bgcolor=#00001f>
		<DIV ALIGN="center">
		<font size="-1"><b>Get an "@eqlore.com" address!</b><BR>
		<FONT COLOR="#ff0000" SIZE="-2"FACE="Verdana"> - New Feature!</FONT><BR>
		<BR>
		<table border="0" bordercolor="#000000" cellspacing="0" cellpadding="0" width="240">
		  <tr> 
		    <td valign="middle" align="center" nowrap height="25"> 
		      <table cellspacing="0" cellpadding="2" width="100%" border="0">
		        <form name="login_form" action="http://eqlore.mail.everyone.net/email/scripts/loginuser.pl" method="post">
		          <tr bgcolor="#00001F">
				  <td nowrap height="5"><font color="#FFFFFF" face="Verdana, Arial, Helvetica, sans-serif" size="2"><B>Email Login :</B></font></td><td><input type="text" name="loginName" size="12" maxlength="30"></td>
					</tr>
		          <tr bgcolor="#00001F"> 
		            <td height="2"><font color="#FFFFFF" face="Verdana, Arial, Helvetica, sans-serif" size="2"><B>Password :</B></font></td><td><input type="password" name="user_pwd" size="12" maxlength="30"></td>
		          </tr>
		          <tr bgcolor="#00001F">
				  	<td height="2" valign="bottom" align="right" COLSPAN="2"><input type="submit" name="login" value="Login">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
				  </tr>
				  <tr bgcolor="#00001F">
		            <td valign="middle" height="2" align="center" colspan="2"><font face="Verdana, Arial, Helvetica, sans-serif" color="#FFFFFF" size="2">New  users <a href="http://eqlore.mail.everyone.net/email/scripts/useragreement.pl"><b>sign up</a> now !</b></font></td>
		          </tr>
		        </form>
		      </table>
		    </td>
		  </tr>
		</table>
		<BR>
		</DIV>
		</TD>
	</TR>
	
	<tr><td><BR></td></tr>	
	
	<TR>
	<TD VALIGN="top" bgcolor=#00001f>
	<A NAME="1.0 Poll">
	<FONT SIZE="-1">
	<TABLE width=100%><TR><TD bgcolor=#00001f><div align="center"><B><font size="+1">V</font>ote :</B></div><BR><div align="center"><b><font size="-1">Which of the three chapters of EverQuest have you enjoyed the most?</font></b></div><table><form action="http://www.loreseekers.com/vote.php3" method="post"><input type="hidden" name="poll_id" value="1"><input type="hidden" name="poll_forwarder" value="http://www.loreseekers.com/main.phtml"><tr><td><input type="radio" name="poll_voteNr" value="1"checked > <font size="-1"><b>Original EverQuest</b></font> </td></tr><tr><td><input type="radio" name="poll_voteNr" value="2"> <font size="-1"><b>Ruins of Kunark</b></font> </td></tr><tr><td><input type="radio" name="poll_voteNr" value="3"> <font size="-1"><b>Scars of Velious</b></font> </td></tr></table><div align="center"><input type="submit" value="Vote"></div></form></TD></TR></TABLE>	</FONT>
	</TD>
	</TR>

	<tr><td><BR></td></tr>
	
	<TR>
   		<TD bgcolor=#00001f>
		<CENTER><B>Featured Article</B> :<BR>
		<BR><FONT FACE="verdana, arial" COLOR="#FFFF00" SIZE=2><B>EverQuest: A Unique Phenomenon</B></FONT></CENTER>
<FONT FACE="verdana, arial" SIZE="2" COLOR="#FFFDCA">
<P><FONT SIZE="+1"><B>I</B></FONT>t was almost 2 and a half years ago that I was born again.<BR><BR>

Born again not in the religious sense, but in the sense that I became the incarnation of all my childhood fantasies. I became a Wizard!<BR><BR>

The date was November 19th, 1998 when I opened up an email to be greeted with the following...<BR><BR>

"<I>Greetings! You have been selected to be one of our testers in
our Phase III test of EverQuest.</I>"<BR><BR>
Read the rest of this article <A HREF="/stories/unique.phtml">Here.</A></FONT>		</TD>
	</TR>
	
<tr><td><BR></td></tr>
	
	<TR>
		<TD VALIGN="top" bgcolor=#00001f>
		<font size="-1"><b><font size="+1">D</font>o you want to share your lore ?<BR><font size="+1">C</font>heck our messageboards :</b><BR>
		<BR>
		<A HREF="http://www.loreseekers.com/phorum306/list.php3?num=4"><b>The Quest Forum</b></a><BR>
		<BR>
		<A HREF="http://www.loreseekers.com/phorum306/list.php3?num=3"><b>The Bazaar</b></a><BR>
		<BR>
		<A HREF="http://www.loreseekers.com/phorum306/list.php3?num=2"><b>The Roleplaying Forum</b></a><BR>
		<BR>
		<A HREF="http://www.loreseekers.com/phorum306/list.php3?num=1"><b>The Guild Forum</b></a><BR>
		<BR></font>	
		</TD>
	</TR>	
	
	<tr><td><BR></td></tr>
	
	</TABLE>
	</TD>
</TR>
</TABLE>

<HR WIDTH="98%">
<DIV ALIGN="center"><FONT SIZE="-2">
	<A HREF="http://www.renaissance.nl/copyright.html" TARGET="_new">Copyright</A> 1999 , 2000 <A HREF="http://www.renaissance.nl/english/" TARGET="_new">Renaissance IT</A>, All Rights Reserved.<BR>
</FONT></DIV>
<HR WIDTH="98%">

</FONT>
</DIV>
</BODY>
</HTML>
