<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">

<html>
<head>
	<title>..:: EQBard : le site de Jonili le petit barde ::..</title>

<SCRIPT LANGUAGE="Javascript">
<!--
function fenetre(intitule,params) { 
var fen = window.open(intitule,'zoom',params); 
}
//-->
</script>

<style>
a.lientexte {color:#0B5040;text-decoration:none;}
a.lientexte:hover {color:#0B5040;text-decoration:underline;}
</style>
</head>

<body bgcolor='#CFE6E3' text='#000000' link='#0B5040' vlink='#000000' alink='#000000'>
<table width='680' border='0' cellspacing='0' cellpadding='0'>
<tr><td>
<table width='680' border='0' cellspacing='0' cellpadding='0'>
<tr>
<td width='680' align='right' valign='top'>
<img src='./img/commun/c01/carre80.gif' width='10' height='10' border='0' alt=''>
<img src='./img/commun/c01/carre70.gif' width='10' height='10' border='0' alt=''>
<img src='./img/commun/c01/carre60.gif' width='10' height='10' border='0' alt=''>
<img src='./img/commun/c01/carre50.gif' width='10' height='10' border='0' alt=''>
</td></tr>
<tr><td height='2'><img src='./img/commun/transparent.gif' height='2' alt='' border='0'></td></tr>
<tr><td width='680' height='1'><img src='./img/commun/c01/carre50.gif' width='680' height='1' alt='' border='0'></td></tr>
</table>
</td></tr><tr><td>
<table width='680' border='0' cellspacing='0' cellpadding='0'>
<tr><td width='120' valign='top'><table width='100%' border='0' cellspacing='0' cellpadding='0'>
<tr><td>
<font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>&nbsp;<br>
<img src='./img/commun/c01/carre70.gif' width='10' height='10' border='0' alt=''>&nbsp;<a href=index.php?menu=1&data=1 class=lientexte><b>Accueil</b></a><br>&nbsp;<br>
<img src='./img/commun/c01/carre70.gif' width='10' height='10' border='0' alt=''>&nbsp;<a href=index.php?menu=2&data=2&order=1 class=lientexte><b>Chants</b></a><br>&nbsp;<br>
<img src='./img/commun/c01/carre70.gif' width='10' height='10' border='0' alt=''>&nbsp;<b>Equipement</b><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=31&data=31&inc=instruments class=lientexte>Instruments</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=32&data=31&inc=armures class=lientexte>Armures</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=33&data=31&inc=armes&order=1&sens=1&bard=1 class=lientexte>Armes</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=34&data=31&inc=resist class=lientexte>Resist gear</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=35&data=31&inc=slot class=lientexte>Par slot</a><br>&nbsp;<br>
<img src='./img/commun/c01/carre70.gif' width='10' height='10' border='0' alt=''>&nbsp;<b>Guides</b><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=41&data=41 class=lientexte>Général</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=42&data=42 class=lientexte>Tactiques</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carreselect.gif' width='5' height='5' border='0' alt=''>&nbsp;Quêtes<br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=44&data=44 class=lientexte>Zones</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=45&data=45 class=lientexte>Procs</a><br>&nbsp;<br>
<img src='./img/commun/c01/carre70.gif' width='10' height='10' border='0' alt=''>&nbsp;<b>Photos</b><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=51&data=51 class=lientexte>Atlas</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=52&data=52 class=lientexte>Bardes</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=54&data=54 class=lientexte>GM</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=55&data=55 class=lientexte>Divers</a><br>&nbsp;<br>
<img src='./img/commun/c01/carre70.gif' width='10' height='10' border='0' alt=''>&nbsp;<a href=index.php?menu=8&data=8 class=lientexte><b>Mode</b></a><br>&nbsp;<br>
<img src='./img/commun/c01/carre70.gif' width='10' height='10' border='0' alt=''>&nbsp;<a href=index.php?menu=6&data=6 class=lientexte><b>Liens</b></a><br>
<img src='./img/commun/c01/carre70.gif' width='10' height='10' border='0' alt=''>&nbsp;<a href=index.php?menu=7&data=7 class=lientexte><b>Download</b></a><br>
<img src='./img/commun/c01/carre70.gif' width='10' height='10' border='0' alt=''>&nbsp;<a href='http://forumsfr.ubi.com/messages/overview.asp?name=eq_themaeq_eqbardes' target='_blank' class=lientexte><b>Forum</b></a><br>
<img src='./img/commun/c01/carre70.gif' width='10' height='10' border='0' alt=''>&nbsp;<a href=mailto:jonili@eqbard.eqloft.com class=lientexte><b>M'écrire</b></a><br>&nbsp;<br>
<img src='./img/commun/c01/carre70.gif' width='10' height='10' border='0' alt=''>&nbsp;<a href=index.php?menu=9&data=9 class=lientexte><b>Backstage</b></a><br>&nbsp;<br></font></td></tr></table>
</td><td width='20' valign='top'><img src='./img/commun/c01/carre50.gif' width='10' height='10' border='0' alt=''>
<img src='./img/commun/c01/carre60.gif' width='10' height='10' border='0' alt=''>
<img src='./img/commun/c01/carre70.gif' width='10' height='10' border='0' alt=''>
<img src='./img/commun/c01/carre80.gif' width='10' height='10' border='0' alt=''>
</td><td width='540' align='left' valign='top'><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>&nbsp;<br><a href='index.php?menu=43&data=43 class=lientexte' class=lientexte><b>< Retour</b></a><br>&nbsp;<br><table width='100%' border='0' cellspacing='0' cellpadding='0'><tr><td colspan='2' bgcolor='#0B5040'><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2' color='white'><b>&nbsp;Singing Short Sword</b></font></td></tr><tr><td width ='10'>&nbsp;</td><td><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>&nbsp;<br>
Singing Short Sword : l'epic des bardes ! woooot ! Cette épée, en plus de ses statistiques déjà intéressantes, procure, quand elle proc, un buff de groupe qui donne 55% de haste, 30 str, 30 atk, qui dure 2 mn 30 et qui a un rayon d'action de 150 pieds. Elle donne un bonus aux chants basés sur un skill d'instrument. Et 80% de bonus à certains chants basés sur le skill singing. Et en plus, il y a plein de jolies notes de musique autour….
<br>&nbsp;<br>
Allez ! Au boulot !
<br>&nbsp;<br>
</font>&nbsp;<br></td></tr><tr><td colspan='2' bgcolor='#0B5040'><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2' color='white'><b>&nbsp;L'histoire</b></font></td></tr><tr><td width ='10'>&nbsp;</td><td><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>&nbsp;<br>
Baldric Slezaf, un barde vivant dans les dreadlands, rêve d'y faire jouer une symphonie. Pas n'importe quelle symphonie. Une superbe symphonie dont il a acheté la partition auprès d'un marchand ambulant. L'auteur en est inconnu, la partition étant simplement signée 'le maestro'.
<br>&nbsp;<br>
Il a commencé à déchiffrer la partition, mais, malheureusement, il manque les pages 24 et 25. Et aussi un luth pour la jouer. Seul Forpar Fizfla est capable de réaliser ce luth.
<br>&nbsp;<br>
Forpar Fizfla est un facteur d'instrument un peu excentrique d'Ak'Anon. Il réalise des instruments enchantés qui produisent des sons sublimes.
<br>&nbsp;<br>
Votre mission, si vous, l'acceptez, consiste à ramener à Baldric Slezaf les deux pages manquantes et le luth.
<br>&nbsp;<br>

</font>&nbsp;<br></td></tr><tr><td colspan='2' bgcolor='#0B5040'><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2' color='white'><b>&nbsp;La quête</b></font></td></tr><tr><td width ='10'>&nbsp;</td><td><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>&nbsp;<br>
De nombreuses parties de la quête sont relativement faciles à faire pour un barde niveau 45 à 55 et peuvent se faire en solo. Vous aurez besoin d'un ou 2 groupes pour certaines parties. Par contre, certaines parties vont demander la participation de nombreux joueurs. Il est préférable d'avoir l'appui d'une bonne guilde pour y parvenir.
<br>&nbsp;<br>
Cette quête est très longue et, comme la plupart des epics, assez difficile. Heureusement, certaines parties peuvent se chaîner.
<br>&nbsp;<br>
Les dialogues sont relatés ici, mais ne sont pas forcément indispensables.
<br>&nbsp;<br>
<b>Vous avez intérêt à garder une bonne faction avec les gnomes pour faire la quête tranquillement. Si vous êtres Kos avec les gnomes, ça sera très difficile.</b>
<br>&nbsp;<br>
Le véritable départ de la quête se situe dans DL (les Dreadlands). Il faut aller voir un NPC nommé Baldric Sleza. Il est dans la petite zone où sont situés les portails de téléportation des druides et des wizards, dans une des pyramides des anciennes ruines. Sa location est +773, +9666.
<br>&nbsp;<br>
Attention, il y a des squelettes qui rôdent dans les ruines. Ils ne sont pas nombreux, mais assez forts pour vous poser de sérieux problèmes si vous êtes d'un niveau inférieur à 50.
<br>&nbsp;<br>
Si vous lui parlez, il vous racontera une histoire à propos de 2 pages manquantes pour sa symphonie et d'un instrument magique pour la jouer. Si vous lui ramenez les items dont il parle, il vous donnera la SSS (singing short sword) en récompense.
<br>&nbsp;<br>
You say, <i>'hail Baldric Slezaf'</i><br>
Baldric Slezaf says <i>'Hello [votre nom]. Don't you think this would be a wonderful place to perform a symphony?'</i><br>
You say, <i>'What symphony ?'</i><br>
Baldric Slezaf says <i>'It has been my dream for years to perform a symphony that would be remembered for ages to come. I have run into a few minor snags, however.'</i><br>
You say, <i>'What snags ?'</i><br>
Baldric Slezaf says <i>'Several years ago I bought sheets of the most beautiful sounding music from a traveling merchant. He did not know the author of the work as it was simply signed 'the Maestro'. The melody I played from them was wondrous and invoked feelings in me I have never felt before. However, as I reached the middle of the music, I discovered it was missing two pages !'</i><br>
You say, <i>'What pages?'</i><br>
Baldric Slezaf says <i>'The pages that were missing were pages 24 and 25. I have been searching the world for a spot to hold my symphony and I have finally found it. Without the music and a new lute crafted by the famous instrument maker Forpar Fizfla, I do not think I can pull it off.'</i><br>
You say, <i>'Who is Forpar Fizfla?'</i><br>
Baldric Slezaf says <i>'Forpar Fizfla is an eccentric instrument maker from Ak'Anon. He makes enchanted instruments that enhance the sound of the music. If I am to perform the concert of all concerts, I must have one of his instruments. I went to Ak'Anon, seeking to purchase an instrument from him but he wouldn't even speak to me.'</i><br>
You say, <i>'What music?'</i><br>
Baldric Slezaf says <i>'It makes me sad to know that the pages of this music may be spread across the world or destroyed. If you find and bring me the two missing sheets as well as a new lute, I would be happy to repay you in some way.'</i><br>
You say, <i>'How will you repay me?'</i><br>
Baldric Slezaf pulls a fantastic looking sword from its scabbard and says, <i>'I might be willing to part with this wonderful sword if I were able to perform this symphony. You would also gain recognition at the opening of the symphony.'</i><br>
Baldric sheathes his sword and begins to hum a haunting melody.

<br>&nbsp;<br>
</font>&nbsp;<br></td></tr><tr><td colspan='2' bgcolor='#0B5040'><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2' color='white'><b>&nbsp;Page 24 : le haut</b></font></td></tr><tr><td width ='10'>&nbsp;</td><td><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>&nbsp;<br>
La première partie de la quête est facile à faire en solo, car cela demande simplement un peu de course à pied (tout le tour d'Antonica tout de même !). Mais avec le Selo, c'est pas compliqué, surtout au niveau 51 (selo's song of travel).
<br>&nbsp;<br>
Le départ est dans West karana. Vous allez voir la barde <b>Konia Swiftfoot</b> qui est dans la tour de garde 1 (celle qui est tout près de la zone de Qeynos Hills). Sa location est -516, -2434. Elle va vous envoyer dans une course de relais en portant une torche à divers NPC situés sur le continent Antonica.
<br>&nbsp;<br>
You say: <i>'Hail Konia Swiftfoot'</i><br>
Konia Swiftfoot says: <i>'Hello there [votre nom]. I am hosting a relay running contest. Would you like to participate?'</i><br>
You say: <i>'Yes I would like to participate.'</i><br>
Konia Swiftfoot says: <i>'Great! The prize will be this silly old music sheet. Let me know when you are ready and I will pass you the torch and tell you where the first stop is.'</i><br>
You say: <i>'I am ready.'</i><br>
Konia Swiftfoot says: <i>'Here you go. Run with this torch as fast as you can to the misty thicket and hand this torch off to Fajio Knejo. He will tell you where to go from there. Hurry! You do not have much time!'</i>
<br>&nbsp;<br>
Vous recevez une torche (elle peut se mettre dans un sac, pas besoin de slot libre dans votre inventaire).
<br>&nbsp;<br>

Allez à Misty Thicket près de l'entrée de Runneyeye Citadel. Vous trouverez Fajio Knejo à la location -120, -54). Le plus court chemin est de mettre votre Selo en route et de traverser : West Karana, North Karana, East Karana, Gorge of King Xxorb, Runnyeye Citadel, Misty Thicket (à moins que vous soyez avec un druide qui vous téléporte à Misty Thicket directement).
<br>&nbsp;<br>
You say: <i>'Hail Fajio Knejo.'</i><br>
Fajio Knejo says: <i>'Greetings, [votre nom]. I hope you are having a fine day.'</i><br>
Donnez la torche à Fajio<br>
Fajio Knejo says: <i>'Run onward, my friend, to the far off Desert of Ro and give this torch to Andad Filla.'</i>
<br>&nbsp;<br>
Vous recevez une autre torche
<br>&nbsp;<br>
Allez dans la zone Southern Desert of Ro près de l'entrée d'Innothule Swamp. Andad Filla est à la location -3032, +1216. Le plus rapide est de traverser Misty Thicket, Rivervale, Kithicor Forest, West Commonlands, East Commonlands, North Desert of Ro (par le tunnel), Oasis, enfin South Desert of Ro. Les druides et les wizards peuvent téléporter à South Desert of Ro.
<br>&nbsp;<br>
You say: <i>'hail Andad Filla'</i><br>
Andad Filla says: <i>'Hello traveler, please do not bother me right now I am waiting for someone.'</i><br>
Donnez la torche à Andad<br>
Andad Filla says: <i>'You still have a ways to go! Seek out Misty Tekcihta near the arena at Lake Rathe. Run like the wind!'</i>
<br>&nbsp;<br>
Vous recevez une autre torche
<br>&nbsp;<br>
Allez dans Lake Rathe à l'entrée de Arena. Misty Tekcihta est à la location +2419, +2583. Le plus rapide est de traverser Innothule swamps, Freerrott, Rathe Mountains et Lake Rathe. Il n'y a pas de tp tout près, vous irez plus vite en courant. Attention aux gardes ogres dans Feerrott.
<br>&nbsp;<br>
You say: <i>'Hail Misty Tekcihta'</i><br>
Misty Tekcihta smiles and taps her foot.<br>
Donnez la torche à Misty.<br>
Misty Tekcihta hands you a small ring.
<br>&nbsp;<br>
Vous recevez un anneau.
<br>&nbsp;<br>
Retournez dans West Karana pour revoir Konia. Le plus court est par Lake Rathe, South Karana, North Karana puis West Karana. Le téléport le plus près est North Karana pour les druides ou West Karana pour les wizards.
<br>&nbsp;<br>
Donnez l'anneau à Konia.<br>
Konia Swiftfoot says: <i>'Excellent! You are quite a runner. Here is half of the sheet music. I decided to keep the other half because it has this wonderful signature. I think it might be quite valuable. It is probably worth as much as an instrument the great Mahlin used.'</i>
<br>&nbsp;<br>
<b>Vous recevez Maestro's Symphony Page 24 Top.</b>
<br>&nbsp;<br>
Voilà, la première partie est finie. C'est long, mais très facile.

<br>&nbsp;<br>
</font>&nbsp;<br></td></tr><tr><td colspan='2' bgcolor='#0B5040'><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2' color='white'><b>&nbsp;Page 24 : le bas</b></font></td></tr><tr><td width ='10'>&nbsp;</td><td><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>&nbsp;<br>
Pour obtenir le bas de la page 24, vous devez donner à <b>Konia Swiftfoot</b> (voir page 24 up) les Mahlin's Bongos. Pour obtenir ces bongos, voici la marche à suivre.
<br>&nbsp;<br>
Parlez à <b>Braenar Swiftsong</b>. Il est dans South Karana près du puits (well) à la location -21, +88.
<br>&nbsp;<br>
You say, <i>'Hail Baenar Swiftsong'</i><br>
Baenar Swiftsong says <i>'Please, I am trying to work here. If you bother me I will write a horrible song about you and sing it from the mountain tops!'</i><br>
You say, <i>'what doll?'</i><br>
Baenar Swiftsong says <i>'What's that you say? You wish to have the doll I was to give her? Whatever for? Bah! Nevermind me. I rant like an old woman sometimes. I should let her memory go but I would stop my heart from beating before I forget that child. Here, take this invoice. I have no further use for it. Give it to Marfen Binkdirple.'</i><br>
Vous recevez une facture (Invoice).
<br>&nbsp;<br>
Allez à Solusek A remettre la facture au marchand gnome <b>Marfen</b>. Vous recevrez une poupée (doll). Le marchand est celui qui vend le Tinkerer's bags et les Traveller's Boots. Il est à la location -304, -1083).
<br>&nbsp;<br>
Le plus simple est de rentrer dans Sol A à partir de Sol B (en passant par la zone derrière la pool room de Sol B). Vous pourrez passer les gobelins invisible (attention, les shamans et peut-être les wizards voient l'invisible). Par contre, pas besoin d'invisibilité avec le gnome ou les robots. Ne vous mettez pas en illusion dark elf, les robots n'aiment pas ça du tout !
<br>&nbsp;<br>
Marfen Binkdirple says <i>'Ah! 'Bout time ye got yer lazy bones down here! I was beginnin' ta worry bout ya. Thought ye'd never pick the doll up. Me kin worked and toiled over this thing fer days. That Baenar was sure exact in every detail. For a special child, he said. Must be some child. He spent all he had and some he didn't. Still owes us a show! Anyway, I heard she passed away some time ago. Give the lad muh regards.'</i><br>
Vous recevez une doll (poupée)
<br>&nbsp;<br>
Allez à Unrest pour donner la poupée à <b>Serra</b>. Serra est à côté du gnomish speulunker.
<br>&nbsp;<br>
Dans Unrest, longez le mur de droite jusqu'au bassin. Plongez dans le bassin. Au fond du bassin il y a un tunnel qui amène à une chambre souterraine (qui est hors eau). Serra est là avec l'autre mob. Ils n'attaquent pas. Si vous avez les singing steel gauntlets, c'est facile (enduring breath).
<br>&nbsp;<br>
Donnez la poupée à Serra. <br>
Serra says <i>'Oh! You have the dolly! Thank you! Thank you! Thank you! I can go home now. Please give this to my father, Baenar. He will understand when he gets it.' Serra begins to fade away. 'Bye bye!'</i><br>
Vous revevez une note.
<br>&nbsp;<br>
Ramenez la note de Serra à Braenar, qui vous donnera une nouvelle note pour Maligar.
<br>&nbsp;<br>
Baenar Swiftsong says <i>'A note from the child? How can that be! How could she know I was her father? Unless? Cyrah told her. Forgive me. Cyrah was the name of the woman to whom I was betrothed. Unfortunately her parents forbade her from marrying a lowly bard such as myself. Her father married her off to a young merchant in Qeynos named Maligar. She married him only out of respect to her father. Her heart was truly mine, at least, so she always said. When Serra was born, I visited them both often. She was like no other, so innocent and sweet. In those few years I watched her grow up to be more and more like her mother and I saw none of the father in her appearance. I do not like Maligar, but the least we can do is inform him of his child's death. I saw his caravan pass by not more than a day ago headed to Qeynos.'</i><br>
Vous recevez une note
<br>&nbsp;<br>
Apportez la note de Braenar à <b>Maligar</b>. Maligar est dans West Karana, location +1179, -10878. Il spawne environ toutes les demi-heures.
<br>&nbsp;<br>
Dès que vous lui donnez la note, un enraged Doppelganger spawne. En fait, c'est une copie de Maligar. Vous devez tuer le doppelganger et looter sa tête (no drop).
<br>&nbsp;<br>
Maligar says <i>'Hmmm. What's this? A note from that silly bard Baenar? I wasn't aware that those of his kind could write, much less read.' Maligar lets out a deep laugh. 'I see you do not share my sense of humor. Let's read it, shall we? Oh, no! She's dead? I knew that already, you fool. It was by my hand she died! Ooops! Did I let that slip out? Silly me. I guess I will have to kill you now!' </i>
<br>&nbsp;<br>
Attention : Maligar n'est pas tout seul et ils sont tous Kos (ils attaquent à vue). Allez-y avec un bon groupe (niveaux 45-55). Il serait possible d'avoir une bonne faction avec Maligar et son gang avec le chant 11, Cinda's Charismatic Carillon, surtout en illusion dark elf. Je ne sais pas, je n'ai pas essayé car ça ne changeait rien pour les autres memebres du groupe.
<br>&nbsp;<br>
D'abord commencez par puller et tuer les autres mobs. Pas de problème de faction, ils sont de la faction brigands.
<br>&nbsp;<br>
Quand j'y suis allé, le groupe était constitué de 2 bardes (Tranule et Jonili), un prêtre, un guerrier, un druide. Une fois les autres tués, j'ai charmé Maligar et je lui ai donné la note. Le Doppelganger a spawné.
<br>&nbsp;<br>
C'est un combat délicat. Ce n'est pas qu'il est très fort, mais il aveugle (blind) et, en fait, je n'ai rien vu du combat. Je n'ai fait que twister des chants de resistance. Apparemment, il n'aveuglerait plus depuis septembre 2001, mais je n'ai pas vérifié.
<br>&nbsp;<br>
On a pu le faire 2 fois, pour les 2 bardes du groupe. Une fois le premier Doppelganger mort, il suffit de recharmer Maligar et de lui redonner la note et le Doppelganger respawne. Une fois le deuxième mort, on a tué Maligar. Mais ce n'est pas obligatoire, l'important est de looter la tête du Doppelganger.
<br>&nbsp;<br>
Ramenez la tête du Doppelganger à Braenar et vous recevrez "Mahlin's Bongo's".
<br>&nbsp;<br>
Baenar Swiftsong says <i>'That vile dog! I knew there was something not right with him, the way he stared at everyone with contempt! Even his own wife! I curse him! I curse him to stay upon the realm and deny him what he most desires! This is too much! I cannot play or write this day. The sadness overwhelms me. In honor of Serra, the daughter that was denied to me in spirit, I vow never to play this instrument again! It was her favorite and she listened to me play for hours on end. Here take it! Take it out of my sight! Leave me be with my grief and my loss.'</i><br>
Vous recevez Mahlin's Bongo's
<br>&nbsp;<br>
Ramenez les Bongos à <b>Konia Swiftfoot</b> dans West Karana pour obtenir le bas de la Page 24.
<br>&nbsp;<br>
Konia Swiftfoot says <i>'Mahlin's bongos! Here, take the other half of the sheet music. I can not really make out what the signature was anyway.'</i>
<br>&nbsp;<br>
<b>Vous recevez Maestro's Symphony Page 24 Bottom</b>
<br>&nbsp;<br>
A part Maligar, c'est à peine plus difficile à faire que le haut de la page 24.
<br>&nbsp;<br>
</font>&nbsp;<br></td></tr><tr><td colspan='2' bgcolor='#0B5040'><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2' color='white'><b>&nbsp;Page 25</b></font></td></tr><tr><td width ='10'>&nbsp;</td><td><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>&nbsp;<br>
Pour la Page 25, allez à South Karana et parlez à la barde elfe nommée <b>Kelkim Menkia</b>. Elle est entre la ville des Centaures et les Treants, le long de la zone (avec le track, on la trouve très facilement).
<br>&nbsp;<br>
You say: <i>'Hail, Kelkim Menkia'</i><br>
Kelkim Menkia sighs as she looks over her lute. <i>'My lute was mangled by those damnable gnolls. I have no idea how I'm going to get a new set of strings for it. They were so rare.'</i><br>
You say: <i>'What rare Strings?'</i><br>
Kelkim Menkia says <i>'I only use the finest lute strings on my lute. My uncle got them for me from across the world. His name was Zendrik the Wurmslayer. As his name implies, he killed many wurms and drakes. The strings for my lute were all made from the guts of the wurms and drakes he slew.'</i><br>
You say: <i>'What wurms and drakes?'</i><br>
Kelkim Menkia says <i>'The strings were from a chromodrac, a red wurm, and a huge onyx drake. It always sounded so wonderful.'</i></br>
Kelkim sighs, looking off into the horizon. As she shakes her lute angrily, she says, <i>'I'll kill all of you dirty gnolls!.'</i>
<br>&nbsp;<br>

Voici les items qu'elle demande pour refaire les cordes de son luth :
<ul>
<li>Guts d'un named chromatic drake dans Skyfire Mountains (Eldrig the Old). Il est niveau 51, il  summone et il gate.
<li>Guts d'une named red wurm dans Burning Woods (Nezekezena). Elle est niveau 45-51.
<li>Guts d'un Oynx Drake dans Rathe Mountains (Blackwing). Il est niveau 40.
</ul>
<b>Eldrig the Old</b>
<br>&nbsp;<br>
Il spawne dans les Skyfire Mountains, location +500, -4000). Eldrig est un named Chromodrac, niveau 51. Il summone, dispelle et lance Boiling Blood (DoT), mais comme il dispelle, il dispelle son propre dot !
<br>&nbsp;<br>
Cette location est un peu au nord de l'entrée de la zone depuis OT (Overthere). Il y a un spawn toutes les 13 minutes. Le mob qui spawne va aller se promener le long de la zone vers le sud puis l'ouest jusqu'au bord de la zone vers Burning Woods. Il y a des PH (placeholder). Les placeholders peuvent être n'importe quel mob de la zone : bottomless feasters, skyash/skycinder drakes, wurms, mature wurms, wyverns, and chromodracs.
<br>&nbsp;<br>
On peut aussi des fois trouver Eldrig the Old près de la zone de Burning Woods (puisqu'il se promène jusque là-bas).
<br>&nbsp;<br>
Je vous conseille de former un bon groupe (niveaux 52-55 minimum) et de camper au spawn point. Vous pouvez tracker et puller les mobs environnants et les tuer en attendant le spawn d'Eldrig ou du PH. La bonne technique de combat dans cette zone est le snare/fear. Les mobs vont fuir le long de la zone et il n'y a pas d'add.
<br>&nbsp;<br>
Je l'ai tué avec un groupe comprenant un druide 60, un paladin 55, un rogue 56 et moi barde 54. On tuait une mature wyvern en fear/snare quand il a spawné juste au milieu du combat ! C'est bien une des rares fois où je me suis félicitée que notre fear soit un chant de zone !
<br>&nbsp;<br>
Le combat est assez facile.
<br>&nbsp;<br>
Lootez les guts

<br>&nbsp;<br>
<b>Nezekezena</b>
<br>&nbsp;<br>
Elle spawne dans Burning Woods. Elle est niveau 45-51, donc au niveau 51 elle summone et gate. Elle spawne location -470, -2550. Elle a également des PH, dont une autre named wurm, Phurzikon, qui droppe un item pour l'epic des magiciens.
<br>&nbsp;<br>
Allez-y avec un bon groupe, car le spawn est rapide et il y a beaucoup de monstres errants dans le coin. Il est très courant de se retrouver avec 4 ou 5 adversaires sur le dos en même temps. Ne pratiquez pas le fear/snare, ni le kittiong, c'est trop dangereux (compte tenu du nombre de monstres dans le coin). Prenez un groupe avec un prêtre et au moins un bon tank (niveaux 54 ou au-dessus). Un enchanteur vous simplifiera la vie, sinon vous serez chargé du crowd control. Par contre, vous pourrez faire pas mal d'exp.
<br>&nbsp;<br>
Les guts droppent très souvent de Nezekezena.
<br>&nbsp;<br>
Lootez les guts
<br>&nbsp;<br>

<b>Blackwing</b>
<br>&nbsp;<br>
Il spawne dans Rathe Mountains, au sud-ouest de la zone, location -1700, -15. Il y a des PH aussi. Il suffit de tuer tous les drakes qui spawnent à cette loc pour voir arriver Blackwing. Les PH sont des drakes et des basilics. En une heure environ, vous devez trouver Blackwing
<br>&nbsp;<br>
Il est assez facile à tuer, vous pouvez le faire en solo en kitting, ou même en mélée (ça dépend de votre équipement). Je l'ai tué en kitting, on était 2 bardes niveau 51.
<br>&nbsp;<br>
Par contre, faites très attention. Dans cette zone, pas loin il y a le sphinx Zazamouhk (enchanteur avec un pet). Si vous n'allez pas trop près de lui, pas de problème. Le pire est Rharzar, un drake vert niveau 55. C'est un wizard (DD de plus de 600 points) qui vole plus vite que le Selo. Il sert à l'epic des SK. Donc, avant d'entrer dans le coin du spawn de Blackwing (quand vous êtes dans le coin des Hill Giants) utilisez le track pour voir si Rharzar est là. Si il est là, n'y allez pas, il vous tuera. Ou alors, allez-y avec 3 ou 4 groupes pour le tuer.
<br>&nbsp;<br>
Lootez les guts
<br>&nbsp;<br>

Une fois que vous avez les 3 guts, apportez-les à <b>Kelkim Menkia</b> dans South Karana et vous aurez la page 25. Cette quête peut se chaîner si vous avez au moins un des guts et un de vos amis les autres.
<br>&nbsp;<br>
Kelkim Menkia snatches the gut strings from your hand and immediately begins to string her lute. <i>'This is wonderful, I will be able to play my lute again soon! Take this old sheet of music I found - I don't think I will have much use for it. My new desire is to bash gnoll heads in with my lute. Safe travels to you, [votre nom].'</i>
<br>&nbsp;<br>
<b>Vous recevez Maestro's Symphony Page 25</b>
<br>&nbsp;<br>


</font>&nbsp;<br></td></tr><tr><td colspan='2' bgcolor='#0B5040'><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2' color='white'><b>&nbsp;Mystical Lute : la tête</b></font></td></tr><tr><td width ='10'>&nbsp;</td><td><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>&nbsp;<br>
Baldric Slezaf vous dit que Forpar Fizla a son luth mais qu'il ne veut pas lui parler. Vous devez récupérer ce luth comme dernier item à donner à Baldric. Ce luth se compose d'une tête (head), d'un corps (body) et des cordes (strings).
<br>&nbsp;<br>

<b>Parler à Forpar</b>
<br>&nbsp;<br>
Forpar Fizla ne veut pas vous parler, mais il ne veut pas non plus parler aux autres gnomes. Pour arriver à converser avec lui, vous devez aider son amie, une jeune femme barde elfe appelée Vedico.
<br>&nbsp;<br>
<b>Vedico Windwisper</b> est aux docks de Butcherblock, à l'intérieur d'un des magasin, location +1010, +3010. Elle s'est fait voler son cor par un cyclope dénommé Quag Maelstrome dans Ocean of Tears. Si vous tuez ce cyclope, vous pourrez looter l'Alluring Horn que vous allez rendre à Vedico dans Butcherblock.
<br>&nbsp;<br>
You say, <i>'hail Vedico Windwisper'</i><br>
Vedico Windwisper says <i>'Hello [Votre Nom] . Have you seen the port master? I am here to complain about the shoddy service.'</i><br>
You say, <i>'What shoddy service?'</i><br>
Vedico Windwisper says <i>'I was sailing from Freeport on one of the boats when a giant cyclops attacked the boat! No one lifted a finger as he stole the horn I was playing and ran off. Someone here has to answer for the loss of my horn.'</i><br>
You say, <i>'what giant cyclops?'</i><br>
Vedico Windwisper says <i>'He was a huge cyclops! He came rushing up out of the water and stared at me with his big eye and said, 'Me like horn me take and play pretty music!' before he snatched my horn and disappeared back under the waves.'</i>
<br>&nbsp;<br>
<b>Quag Maelstrom</b> est dans Ocean of Tears sur l'île des Seafury Cyclops. La location est à peu près +2000, -6000. Il est possible de le tuer en groupe ou en solo. Si vous voulez le faire en solo (soyez au moins niveau 51), il suffit de le puller sur l'île voisine de l'Ancient Cyclops. Puis vous le tuez en kiting le long de la plage (n'allez pas près du spawn de l'Ancient Cyclops). Sinon, allez-y avec un groupe.
<br>&nbsp;<br>
Je l'ai tué de nombreuses fois car on campait l'Ancient Cyclops pour la quête des Jboots. Entre 2 spawns, on pullait des Seafurys, dont Quag Maelstrom. Il spawne très souvent et droppe toujours I'alluring horn. Les singing steel boots sont un plus pour cette partie (lévitation de groupe pour 5 minutes).
<br>&nbsp;<br>
Apportez l'Alluring Horn à Vedico dans Butcherblock et elle vous donnera une note pour Forpar.
<br>&nbsp;<br>
Vedico Windwisper says <i>'Where did you find this? I thought the cyclops took it. I am in your debt [Votre Nom]. This horn has always been special to me.'</i><br>
Vedico reaches into her pack and pulls out a note. <i>'Do you think you could deliver this to my gnome friend Forpar. I have not spoken to him in a while and unfortunatly I will be unable to make the trip to visit him. If you are looking to have an instrument made he is the man to ask.'</i><br>
<b>Recevez une note.</b>
<br>&nbsp;<br>
Allez dans Steamfont Mountains et trouvez Forpar Fizfla. Il est dans le deuxième moulin à vent, à la location +128, -600. Si votre faction avec lui n'est pas excellente, utilisez le chant Cinda's Charismatic Carillion (avec ça il est amiable pour moi). Donnez-lui la note de Vedico et il parle d'un luth mystique qu'il peut fabriquer.
<br>&nbsp;<br>
You say, <i>'hail Forpar Fizfla'</i><br>	
Forpar Fizfla says <i>'Get out you pesky [Votre race]! I don't need any Half Elf germs! Out, ye filthy beast.'</i><br>
<b>Donnez-lui la note de Vedico</b><br>
Forpar Fizfla says <i>'So you know Vedico! How is the lass? If Vedico would give you the time of day, you must be something special. What can I do for you? I hope you have not come to have me make another [mystical instrument].'</i><br>
You say, <i>'what mystical instrument?'</i><br>
Forpar Fizfla says <i>'I have made many mystical instruments in the past. Each one seemed to be better then the last. I have always had a dream of building the world's best lute, but I have yet to find someone brave enough to gather the components needed to make the instrument.'</i><br>
You say, <i>'I can gather components'</i><br>
Forpar Fizfla says <i>'To make a mystical lute I will first need to make several pieces. If you bring me the backbone of an ancient fishman, a strong tentacle from one of the long lost amalgyms, and a petrified skull of a lycanthrope I may be able to create the head and neck of the instrument. If you go out and gather these things, make sure to bring me the note I gave you or I might forget who you are. I am getting quite old, you know.'</i><br>
<b>Recevez une note de Forpar pour lui-même.</b>
<br>&nbsp;<br>
C'est là que cette quête devient vraiment difficile. Vous allez avoir besoin d'une bonne assistance pour y parvenir. Forpar vous dit qu'il est prêt à vous faire un instrument, mais il ne vous parle d'abord que de la tête. Les objets nécessaires sont les suivants (ils sont tous no drop, mais ils peuvent se chaîner) :
<ul>
<li><b>Backbone of an Ancient Fishman</b> - C'est le backbone de Phinigel Autropos, le boss de Kedge Keep 
<li><b>Amalgym Tentacle</b> - c'est un Amygdalan Tendril qui se loote sur les amygdalan warriors sur le Plane of Fear 
<li><b>Petrified skull of a Lycanthrope</b> - C'est le crâne du Drolvarg Warlord de Karnor's Castle
</ul>

<b>Backbone of an Ancient Fishman</b>
<br>&nbsp;<br>
Phinigel Autropos ne se tue pas comme ça. Cela nécessite un raid organisé et au moins 2 groupes complets pour y arriver (niveaux 53-60). En outre, le pull est assez délicat à effectuer. Phinigel est entouré de Swirlspine Seahorses et de Swirlspine Guardians. En plus, ce sont tous des healers. Vous pouvez les mezzer, mais seulement avec le chant du niveau 53. Les singing steel gauntlets, avec leur enduring breath permanent, vous permettront d'aller dans Kedge Keep tranquillement.
<br>&nbsp;<br>
Il existe des guides très bien faits sur cette zone.
<br>&nbsp;<br>
Il faut looter le Kedge Backbone sur Phinigel. Mais il ne le droppe pas à chaque fois.
<br>&nbsp;<br>
<b>Petrified Werewolf Skull</b>
<br>&nbsp;<br>
Le Drolvarg Warlord spawne dans Karnor's Castle juste en dessous de la Hand Room. Il est niveau 51 à 54, et donc peut summoner. (Il droppe aussi en rare l'Harmonic Dagger). Il a des PH qui sont des Drolvarg Bodyguards.
<br>&nbsp;<br>
Un bon groupe niveaux 51 et plus peut tenir la pièce, voire même faire la Hand Room en même temps.
<br>&nbsp;<br>
<b>Amygdalan Tendril</b>
<br>&nbsp;<br>
Les Amygdalan Tendrils droppent des Amygdalan Warriors dans Plane of Fear. Participez à un raid organisé et demandez à looter. Attention, prévenez les organisateurs du raid que vous en avez besoin pour votre epic, car c'est en fait un fouet (arme 1HS) warrior only. Ne laissez pas les guerriers le looter (de toute façon, comme arme, elle n'est pas intéressante).
<br>&nbsp;<br>
Prenez ces 3 objets et allez les donner à Forpar, ainsi que sa note et il vous donnera en retour la Mystical Lute Head.
<br>&nbsp;<br>
Donnez à Forpar sa Note, le Backbone, le Petrified Skull, et le Tendril<br>
Forpar Fizfla says <i>'Wow! I didn't think a Half Elf like you would be able to gather all of those things.' Forpar rambles around and works with small tools for a good ten minutes before handing you a very fine looking lute head. 'Now, do you want to gather the next pieces for me?'</i><br>
<b>Recevez Mystical Lute Head.</b><br>
You say, <i>'What next pieces?'</i><br>
Forpar Fizfla says <i>'The next pieces are a little harder to come by than those. To make the body of an instrument that will last for ages to come, I need something very special. The scales of a big red dragon and the scales of a big white dragon will make it unbreakable, as well as giving it a unique look. Some metal bits will allow me to hold the body together. Please, if you gather up these things, bring them to me as soon as possible. I have not felt this good in years!</i>
<br>&nbsp;<br>

</font>&nbsp;<br></td></tr><tr><td colspan='2' bgcolor='#0B5040'><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2' color='white'><b>&nbsp;Mystical Lute : le coprs</b></font></td></tr><tr><td width ='10'>&nbsp;</td><td><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>&nbsp;<br>
Quand vous recevez la tête du luth, Forpar vous indique les objets nécessaires pour le corps. Les voici (ils ne sont pas no drop) :
<ul>
<li><b>Large red Dragon Scale</b> - Une écaille de dragon rouge. On en trouve sur Talendor dans Skyfire, Lord Nagafen ou Ragefire dans Sol B, ou Nortlav Scalekeeper dans The Hole.
<li><b>Large white Dragon Scale</b> - Une écaille de dragon blanc. On en trouve sur Gorenaire dans Dreadlands ou Lady Vox dans Permafrost 
<li>Metal bit - 1 metal bit fait à la forge, avec le trade skill smithing, trivial à 21.
</ul>
A part le metal bit qui est très facile à avoir (vous pouvez le forger vous-même ou demander à un ami de le faire, ça ne coûte presque rien), les écailles de dragon sont très dures à trouver. J'ai parfois vu des écailles rouges à vendre (2 fois) entre 35 et 50 kpp. Par contre, les écailles blanches sont très recherchées car on peut avoir un manteau avec (une quête dans Rathe Mountains).
<br>&nbsp;<br>
Je ne sais pas comment cela se passe sur votre serveur, mais sur le mien (Erolisi Marr), Naggy et Vox ne sont pas tués par les guildes. Ce sont des joueurs de petites guildes qui font appel aux volontaires. Cela veut dire à peu près 2 heures d'attente pour avoir suffisamment de monde et des querelles continuelles sur qui peur roller sur le loot. De toute façon, il ne faut pas être plus que niveau 52 pour les tuer (et on ne vous prend pas si vous n'êtes pas 51).
<br>&nbsp;<br>
Les autres dragons sont tués par les grosses guildes (souvent moins d'une heure une fois qu'ils ont spawné). Ce qui veut dire que, si vous n'appartenez pas à une grosse guilde, il vous faut faire Naggy et Vox.
<br>&nbsp;<br>
Les écailles ne droppent que rarement de Naggy et Vox. Entre ceux que j'ai tués et ceux de Jonili, Vox a droppé une fois sur les 12 morts, et Naggy 2 fois sur 15. Pour Naggy, les guerriers et les bardes participaient au roll. Pour Vox, seuls les bardes participaient. Les écailles sont réputées dropper plus souvent des autres dragons.
<br>&nbsp;<br>
Une fois que vous avez ces 3 objets, allez revoir Forpar dans Steamfont. 
<br>&nbsp;<br>
Donnez à Forpar red dragonscale, white dragonscale, et 1 metal bit.<br>
Forpar Fizfla says <i>'Wooooooo! You are doing a wonderful job, [Votre Nom]. I wish I could go out and gather these things myself.' Forpar sits back down at his desk and pulls several very strange looking tools out. Eventually he looks up at you and says, 'The body is done! Only one more piece to go!' </i>
<b>Recevez Mystical Lute Body</b>
<br>&nbsp;<br>

</font>&nbsp;<br></td></tr><tr><td colspan='2' bgcolor='#0B5040'><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2' color='white'><b>&nbsp;Mystical Lute : les cordes</b></font></td></tr><tr><td width ='10'>&nbsp;</td><td><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>&nbsp;<br>
Pour terminer, il faut trouver les cordes du luth - Trakanon Gut Strings. Elles droppent sur Trakanon lui-même (c'est un petit dragon niveau 65 au fond d'Old Sebilis). Attention : les guts ne droppent pas du Trakanon normal, mais d'un spawn spécial.
<br>&nbsp;<br>
Vous faites spawner le Trakanon spécial en parlant  à l'Undead Bard. L'undead bard spawne à peu près 18 +/- 4 heures après que le Trakanon normal a été tué. La location de l'Undead Bard est -2100, -700. Un ranger peut le tracker depuis le château (où sont les Juggernauts) et un bardes depuis le pont uniquement, c'est-à-dire pas très loin.
<br>&nbsp;<br>
Par contre, il paraîtrait qu'une fois que le Undead Bard spawne, il reste jusqu'à ce que le Trakanon normal respawne (aucun mob ne l'attaque, à part Trakanon).
<br>&nbsp;<br>
Vous donnez le Body du Mystical Lute à l'Undead Bard. Il vous le rend , devient enragé et vous attaque. Il faut le tuer. Il est niveau 55-56. Donc ayez un bon prêtre dans votre groupe ou demandez à un enchanteur de vous mettre une bonne rune (4 ou 5) pour ne pas mourir. Le mieux est que les tanks du raid soient juste autour à ce moment là et attaquent le plus vite possible. Utilisez votre chant Song of Dawn du niveau 53 pour ne plus être aggro.
<br>&nbsp;<br>
Quand l'Undead Bard est mort (cela va assez vite), Trakanon spawne immédiatement. Il est un peu moins fort que le normal, puisqu'il n'est pas buffé, mais il est 65 quand même. Il droppe les guts à chaque fois, ainsi qu'une BP, mais pas de dent.
<br>&nbsp;<br>
<b>Lootez les guts.</b>
<br>&nbsp;<br>
Voici la conversation avec with your Undead Bard :<br>
You say, <i>'Hail, An Undead Bard'</i><br>
An Undead Bard says <i>'Hail, [Votre Nom] . Are you perchance a minstrel?'</i><br>
You say, <i>'I am a minstrel' </i><br>
An Undead Bard says <i>'I, too, am a bard, or was rather. I have been cursed by that blasted pile of bones who calls itself, Trakanon' </i><br>
You say, <i>'Who is Trakanon ?' </i><br>
An Undead Bard says <i>'He is the undead dragon who rules this realm. I came on a quest seeking strings for my new instrument.' </i><br>
You say, <i>'What new instrument ?' </i><br>
An Undead Bard says <i>'I sought to create a Magical Lute.'</i><br>
You say, <i>'What Magical Lute ?' </i><br>
An Undead Bard says <i>'One that would make me the greatest bard in all the lands! Are you on a similar quest?' </i><br>
You say, <i>'I am on a similar quest'</i><br>
An Undead Bard says <i>'Well then, I would ask you a favor for one in return. If I bring that cursed dragon here, will you kill it for me?'</i><br>
You say, <i>'I will kill it for you' </i><br>
An Undead Bard says <i>'Excellent. I have stayed here far too long and I wish to go to my eternal slumber. But before I do so, I ask for one last request' </i><br>
You say, <i>'What is your one last request ?' </i><br>
An Undead Bard says <i>'Give me the Mystical Lute Body you have. I will return it, don't worry. I only wish to hold an instrument one last time before I leave.' </i><br>
&nbsp;<br>

</font>&nbsp;<br></td></tr><tr><td colspan='2' bgcolor='#0B5040'><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2' color='white'><b>&nbsp;La récompesne : Singing Short Sword</b></font></td></tr><tr><td width ='10'>&nbsp;</td><td><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>&nbsp;<br>
Allez à Steamfont retrouver <b>Forpar</b>. Donnez-lui les différentes parties pour obtenir le Mystical Lute : la tête, le corps et les guts.
<br>&nbsp;<br>
<b>Recevez le Mystical Lute de Forpar.</b>
<br>&nbsp;<br>

C'est presque fini.
<br>&nbsp;<br>
Allez dans Dreadlands voir <b>Baldric Slezaf</b> et donnez-lui : page 24 top, page 24 botom, page 25 et Mystical lute from Foplar.
<br>&nbsp;<br>
<b>Recevez Singing Short Sword!</b>
<br>&nbsp;<br>
Tranule, Barde sur EM.
</font>&nbsp;<br></td></tr></table>&nbsp;<br></font></td></tr></table>
</td></tr><tr><td>
<table width='680' border='0' cellspacing='0' cellpadding='0'>
<tr><td width='680' height='1'><img src='./img/commun/c01/carre50.gif' width='680' height='1' alt='' border='0'></td></tr>
<tr><td height='2'><img src='./img/commun/transparent.gif' height='2' alt='' border='0'></td></tr>
<tr>
<td width='680' align='left' valign='top'>
<img src='./img/commun/c01/carre50.gif' width='10' height='10' border='0' alt=''>
<img src='./img/commun/c01/carre60.gif' width='10' height='10' border='0' alt=''>
<img src='./img/commun/c01/carre70.gif' width='10' height='10' border='0' alt=''>
<img src='./img/commun/c01/carre80.gif' width='10' height='10' border='0' alt=''>
</td></tr>
</table>
</td></tr><tr><td align='center'>
<A target='_blank' href='http://www.eqloft.com/'><img src='./img/commun/hebergement.gif' width='122' height='31' border='0' alt=''></a></td></tr></table>

</body>
</html>
<html>
<!-- webbot bot="HTMLMarkup" startspan -->
<!-- BEGIN WEBSIDESTORY CODE -->
<!-- COPYRIGHT 1997-2001 WEBSIDESTORY, INC. ALL RIGHTS RESERVED. U.S.PATENT PENDING. Privacy notice at: http://websidestory.com/privacy -->
<script language="javascript">
var _pn="EQLoft";       //page name(s)
var _mlc="/SiteWeb";    //multi-level content category
var _cp="null";                 //campaign
var _acct="DM510830FOBR38FR3";  //account number(s)
var _pndef="title";             //default page name
var _ctdef="full";              //default content category
var _dlf="n";                   //download filter
var _elf="n";                   //exit link filter
var _epg="n";                   //event page identifier
var _hcv=65;                    //code version
var _mn="we44";                 //machine name
var _gn="ehg-ubisoft.hitbox.com";                       //gateway name
var _ptc="n"; // page type
function _wn(_nm){if((_nm.indexOf("NAME")>0&&_nm.indexOf("PUT")>=0)||
(_nm.indexOf("CONTENT")>=0&&_nm.indexOf("CATEGORY")>0))return true;return false;}
function _gd(_x,_w){_ed = (_x.lastIndexOf("/"));
_be = (_w!="full")?(_x.lastIndexOf("/",(_ed-2))):(_x.indexOf("/"));
_dn = (_be==_ed)?"/":(_x.substring(_be, _ed));return _dn;}
function _gf(_x){_ed = (_x.length);_be = ((_x.lastIndexOf("/"))+1);
_fn = (_x.substring(_be, _ed));return _fn;}
function _vc(_ml){_mll=_ml.length-1;if(_ml.lastIndexOf("/")==_mll){_ml=_ml.substring(0,_mll)}
if(_ml.indexOf("/")!=0){_ml="/"+_ml;}return _ml;}
function _ps(_ip,_pml){if(!_ip){_pml=(_wn(_pml))?_gd(location.pathname,_ctdef):_vc(_pml);}
else{if (_wn(_pml)){if (_pndef=="title"){_pt=document.title; if(_pt!=""){_pml=_pt};}
else{_pml=_gf(location.pathname);if (_pml==""){_pml=_pndef};}};}return _pml;}
function _pm(_ml,_fml,_ipn){if(_ml.indexOf(";")!=-1){_nml=_ml.substring(0,(_ml.indexOf(";")));
_rm=_ml.substring((_ml.indexOf(";")+1),_ml.length);_fml+=_ps(_ipn,_nml)+";";
_gp=_pm(_rm,_fml,_ipn);return _gp;}else {_fml+=_ps(_ipn,_ml);return _fml;}}
var _sv=10;var _bn=navigator.appName;if(_bn.substring(0,9)=="Microsoft"){_bn="MSIE";};
var _bv=(Math.round(parseFloat(navigator.appVersion)*100));if((_bn=="MSIE")&&(parseInt(_bv)==2))_bv=301;
var _rf=escape(document.referrer);_mlc=_pm(_mlc,"",false);_pn=_pm(_pn,"",true);
</script><script language="javascript1.1" id="_hbc">_sv=11;</script>
<script language="javascript1.1" defer src="http://a1604.g.akamai.net/f/1604/2007/1h/stats.hitbox.com/js/hbe.js"></script>
<script language="javascript">if (_sv==10){if
(document.cookie.indexOf("CP=")!=-1){_ce="y";}else{
document.cookie="CP=null*; path=/; expires=Wed, 1 Jan 2020 00:00:00 GMT";
_ce=(document.cookie.indexOf("CP=")!=-1)?"y":"n";};if((_rf=="undefined")||(_rf=="")){_rf="bookmark";};
_x2="<img src='http://"+_gn+"/HG?hc="+_mn+"&hb="+escape(_acct)+"&n="+escape(_pn);
_x3="&cd=1&hv=6' border=0 height=1 width=1>";
_ar="&bn="+escape(_bn)+"&bv="+_bv+"&ce="+_ce+"&ss=na&sc=na&dt=&sv="+_sv+"&con="+escape(_ct);
_ar+="&vcon="+escape(_mlc)+"&epg="+_epg+"&hp=u&cy=u&ja=na&ln=na&cp="+escape(_cp)+"&pl=&rf="+_rf;
document.write(_x2+_ar+_x3);}document.write("<\!--");</script>
<noscript><img src="http://ehg-ubisoft.hitbox.com/HG?hc=we44&cd=1&hv=6&ce=u&hb=DM510830FOBR38FR3&n=EQLoft&vcon=/SiteWeb" border='0' width='1' height='1'>
</noscript><!--//-->
<!-- END WEBSIDESTORY CODE  -->
<!-- webbot bot="HTMLMarkup" endspan -->
</html>
