<!--
                 This page has been created by Renaissance IT
   Renaissance Internet Technologies Copyright (c) 1999 All Rights Reserved.

             for more info on our products, please visit :
                        http://www.renaissance.nl/

	This script has been written by Roy Boverhof <rboverhof@renaissance.nl>
	
        Pagename                : members.html
        Last Updated    		: 13-6-1999
-->

<HTML>
<HEAD>
	<TITLE>the Seekers of Lore : Members</TITLE>
</HEAD>

<BODY BGCOLOR="#000000" TEXT="#FFFFFF" LINK="#FFF000">
<DIV ALIGN="center">
<BR>
<!-- FGN Banner Code -->
<script language="JavaScript">
	<!-- Hide from old browsers
	var random = new Number(Math.floor(9999999 * Math.random())+1);

	// Modify to reflect site specifics
	page = "eqlore.com/";
	target = "@Top1,x02,x05,x08!Top1";

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript1.1" SRC="http://oascentral.cybereps.com/RealMedia/ads/adstream_jx.ads/' + page + 1 + random + target + '">');
	document.write('</SCR');
	document.write('IPT>');

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript">');
	document.write('_version=10; //-->');
	document.write('</SCR');
	document.write('IPT>');

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript1.1">');
	document.write('_version=11; //-->');
	document.write('</SCR');
	document.write('IPT>');

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript">');

	if (navigator.appVersion.indexOf('MSIE 3') != -1){
	document.write('<IFRAME MARGINWIDTH=0 MARGINHEIGHT=0 HSPACE=0 VSPACE=0 FRAMEBORDER=0 SCROLLING=no BORDERCOLOR="#000000" SRC="oascentral.cybereps.com/RealMedia/ads/adstream_sx.ads/' + page + random + target + '"></IFRAME>');
	  }
	else if (_version < 11) {
	document.write ('<A HREF="http://oascentral.cybereps.com/RealMedia/ads/click_nx.ads/' + page + random + target + '"><IMG SRC="http://oascentral.cybereps.com/RealMedia/ads/adstream_nx.ads/' + page + random + target + '"></a>');
	  }

	document.write('</SCR');
	document.write('IPT>');

	// End Hide -->
</script>
<!-- END FGN Banner Code --><BR>	
<TABLE CELLSPACING = 0 CELLPADDING = 0 BORDER = 0>
<TR>
	<TD width="63"><IMG SRC = "graphics/topc000.jpg" WIDTH = 63 HEIGHT = 87></TD>
	<TD width="473"><IMG SRC = "graphics/topc001.jpg" WIDTH = 473 HEIGHT = 87></TD>
	<TD width="64"><IMG SRC = "graphics/topc002.jpg" WIDTH = 64 HEIGHT = 87></TD>
</TR>
	<TD width="63"></TD>
	<TD BGCOLOR="#BEA279" width="460">
	<DIV ALIGN="CENTER">
	<IMG SRC="graphics/members.jpg">
	<TABLE WIDTH="460">
	<TR>
		<TD>
		<DIV ALIGN="CENTER"><FONT COLOR="#000000">
		This is our guild's member section.<BR>
		<BR>
		Here you can search for one of our members, or view the complete list.
		If you are a member of the Seekers of Lore, you can enter the member only area, or edit your personal information by using the links below.
		<BR><BR>
		If you are not a member, but wish to become one, you can apply to our guild using the "Become a Seeker" link to the left.
		</FONT>
		<BR><BR>
		<A HREF="mem_list.php3">Member List</A><BR>
		<A HREF="members.php3">Member search</A><BR>
		<A HREF="apply.phtml">Become a Seeker of Lore</A><BR>
		<A HREF="restricted/mem_change.php3">Change Member Details</A><BR>
		<A HREF="restricted/">Members only !</A><BR>
		</DIV>
		</TD>
	</TR>
	</TABLE>
	<TD width="64"></TD>
<TR>
	<TD><IMG SRC = "graphics/botc000.jpg" WIDTH = 63 HEIGHT = 87></TD>
	<TD><IMG SRC = "graphics/botc001.jpg" WIDTH = 473 HEIGHT = 87></TD>
	<TD><IMG SRC = "graphics/botc002.jpg" WIDTH = 64 HEIGHT = 87></TD>
</TR>
</TABLE>
<BR>
<IMG SRC="http://service.bfast.com/bfast/serve?bfmid=1375281&siteid=40292692&bfpage=pc" BORDER="0" WIDTH="1" HEIGHT="1" NOSAVE ><A HREF="http://service.bfast.com/bfast/click?bfmid=1375281&siteid=40292692&bfpage=pc" TARGET="_new"><IMG SRC="http://affiliate.gamestop.com/affIMG/pc_120x60.gif" BORDER="0" WIDTH="120" HEIGHT="60" ALT="PC Games at GameStop.com"></A>
<BR>
<BR>
</DIV>
</BODY>
</HTML>
