<!--
   This page has been created by Renaissance IT
   Renaissance Internet Technologies Copyright (c) 1999 All Rights Reserved.
   for more info on our products, please visit : http://www.renaissance.nl/
   This script has been written by Roy Boverhof <rboverhof@renaissance.nl>
 
   Pagename             : main.phtml
   Last Updated    		: 06-11-2000
-->

<HTML>
<HEAD>
	<TITLE>the Seekers of Lore : Main</TITLE>
</HEAD>
<BODY BGCOLOR="#000000" TEXT="#ffffff" LINK="#fff000" VLINK="#fff000" marginwidth="0" marginheight="0">
<DIV align=center>
<BR>
<!-- FGB Banner Code -->
<SCRIPT LANGUAGE="JavaScript">
<!-- Hide from old browsers
now = new Date();
random = now.getTime();

// Modify to reflect site specifics
site = "http://ds.cybereps.com";
target = "/SITE=FGN/AREA=EQLORE/AAMSZ=BANNER";

document.write('<IFRAME SRC="' + site + '/hserver/acc_random=' + random + target + '"');
document.write(' NORESIZE SCROLLING=NO HSPACE=0 VSPACE=0 FRAMEBORDER=0 MARGINHEIGHT=0 MARGINWIDTH=0 WIDTH=468 HEIGHT=60>');

document.write('<SCR');
document.write('IPT SRC="' + site + '/jnserver/acc_random=' + random + target + '">');
document.write('</SCR');
document.write('IPT>');

document.write('</IFRAME>');
// End Hide -->
</SCRIPT>

<NOSCRIPT><A HREF="http://ds.cybereps.com/accipiter/adclick/SITE=FGN/AREA=EQLORE/AAMSZ=BANNER"><IMG SRC="http://ds.cybereps.com/accipiter/nserver/SITE=FGN/AREA=EQLORE/AAMSZ=BANNER" border="0"></A></NOSCRIPT>
<!-- END FGB Banner Code --><table WIDTH="98%">
<tr>
	<td VALIGN="top">
	<TABLE cellPadding=3 cellSpacing=3 VALIGN="top">
    <TR>
      <TD VALIGN="top">
      <CENTER><B><FONT size=+1>Welcome to the "Seekers of Lore"</FONT></B></CENTER>
	  <font size="-1">
	  <P><FONT size=+1>W</FONT>e are an EverQuest guild devoted to the never ending quest for knowledge.
      <P><FONT size=+1>F</FONT>ounded by the glorious <A href="madwand.phtml">MadWand</A> and lead by the mighty <A href="http://www.loreSeekers.com/mem_detail.php3?search=2">Sorontar</A>, 
      the Seekers of Lore are devoted to collecting and cataloging all the EQ lore they can! Be it maps, quests, items or creative works by the players of EQ, we will have it here or link to where you can find it! So, please, 
	  take a moment and browse through our libraries. If you like what you see 
	  or have any comments to make, then feel free to sign our <A href="guestbook.php3">Guestbook</A>.<BR>
      <P><FONT size=+1>S</FONT>incerely,<BR>
	  <A href="mailto:webmaster@loreSeekers.com"><B>Sorontar D'Agora</B></A> 
      </P>
	  </font>
	  </TD>
	</TR>

	<tr><td><BR></td></tr>
	
	<TR>
		<TD VALIGN="top">
		<DIV ALIGN="left"><TABLE><TR><TD><B>Site news :</B></TD><TD><FONT FACE="Verdana, Arial" SIZE=+1><A NAME="200031722I"><B>Large Map Update</B></A></FONT></TD></TR></TABLE><BR><TABLE><TR><TD><FONT FACE="Verdana, Arial" SIZE=2><FONT SIZE="2" FACE="arial">
Updates to the site Monday November 13th...<BR><BR>

A large map update today, as I am posting 5 new maps, 1 updated one, and 7 edited ones. The edited maps are all ones done by the famous mapmaker 'Maps' and have been changed to include legends for the markers on her original maps, which makes them easier to follow. Many thanks to Gamgan of Xegony for the submissions!</FONT><BR><BR>

<A HREF="maps.php3"><B>Maps:</B></A><BR><BR>

<FONT SIZE="2" FACE="arial">1. <A HREF="map_search.php3?action=zone&add_zone=Old%20Sebilis">Old Sebilis</A> - By EQ Atlas (new!)</FONT><BR>
<FONT SIZE="2" FACE="arial">2. <A HREF="map_search.php3?action=zone&add_zone=Kelethin">Kelethin</A> - By unknown (new!)</FONT><BR>
<FONT SIZE="2" FACE="arial">3. <A HREF="map_search.php3?action=zone&add_zone=Kelethin">Kelethin</A> - By Kenshiro (updated)</FONT><BR>
<FONT SIZE="2" FACE="arial">4. <A HREF="map_search.php3?action=zone&add_zone=Greater%20Faydark">Greater Faydark</A> - By Maps (edited)</FONT><BR>
<FONT SIZE="2" FACE="arial">5. <A HREF="map_search.php3?action=zone&add_zone=Ak'Anon">Ak'Anon</A> - By unknown (new!)</FONT><BR>
<FONT SIZE="2" FACE="arial">6. <A HREF="map_search.php3?action=zone&add_zone=Butcherblock%20Mountains">Butcherblock Mountains</A> - By Maps (edited)</FONT><BR>
<FONT SIZE="2" FACE="arial">7. <A HREF="map_search.php3?action=zone&add_zone=Crushbone">Crushbone</A> - By Maps (edited)</FONT><BR>
<FONT SIZE="2" FACE="arial">8. <A HREF="map_search.php3?action=zone&add_zone=Kedge%20Keep">Kedge Keep</A> - By Kuan (new!)</FONT><BR>
<FONT SIZE="2" FACE="arial">9. <A HREF="map_search.php3?action=zone&add_zone=Lesser%20Faydark">Lesser Faydark</A> - By Maps (edited)</FONT><BR>
<FONT SIZE="2" FACE="arial">10. <A HREF="map_search.php3?action=zone&add_zone=Solusek's%20Eye%20B">Sol B</A> - By Maps (edited)</FONT><BR>
<FONT SIZE="2" FACE="arial">11. <A HREF="map_search.php3?action=zone&add_zone=Toxxulia%20Forrest">Toxxulia Forest</A> - By Maps (edited)</FONT><BR>
<FONT SIZE="2" FACE="arial">12. <A HREF="map_search.php3?action=zone&add_zone=Steamfont%20Mountains">Steamfont Mountains</A> - By Maps (edited)</FONT><BR>
<FONT SIZE="2" FACE="arial">13. <A HREF="map_search.php3?action=zone&add_zone=Estate%20of%20Unrest">Estate of Unrest</A> - By Maps (edited)</FONT><BR><BR>

<FONT SIZE="2" FACE="arial">
You might also want to check a nice poem made by Hyppy : <A HREF="/stories/hyppy_poem.phtml">A Winter's Afternoon</A></FONT><BR><BR></FONT></TD></TR></TABLE></DIV><BR><DIV ALIGN="left"><TABLE><TR><TD><B>EQ news :</B></TD><TD><FONT FACE="Verdana, Arial" SIZE=+1><A NAME="200033314I"><B>Patch Message (Nov 29)</B></A></FONT></TD></TR></TABLE><BR><TABLE><TR><TD><FONT FACE="Verdana, Arial" SIZE=2><FONT SIZE="2" FACE="arial">
The servers are down for the scheduled patch. They are scheduled to be back up by 11:00am PST (02:00pm EST). Here is the patch message already on the patch server...<BR><BR>
</FONT>

<HR SIZE=2>

<FONT FACE="verdana, arial" SIZE="1" COLOR="#FFFDCA">
November 29th, 3:00am<BR>
------------------------------<BR><BR>

*Patch Day*<BR><BR>

Today's patch includes updates to the client to address some problems reported by people in regards to the DX7 update, as well as other gameplay issues:<BR><BR>

- Corrected an older bug that would cause people to stop gaining or losing faction with associates when the primary faction was at its maximum or minimum.  Players will now be able to further modify associate factions in the appropriate direction.<BR><BR>

- Random-effects on weapons carried by pets will now behave as if the pet is a player character rather than an NPC.  The change last patch reduced them to a rate below player characters.  As part of this patch, target-specific random effects will only work if the target is the intended type.  For instance, a weapon that processes "Dismiss Summoned" will only "go off" on a summoned NPC instead of everything.<BR><BR>

- Added some code that should address if not eliminate a problem reported by people whereas the client would "freeze" for a second or two every few minutes.  For those who do not have IRQ sharing and/or driver problems, this should address the issue.<BR><BR>

- Made final positive modifications to several Epic Quest rewards.  Included in these changes: the SK weapon will now allow you to bash while carrying it.<BR><BR>

- Fixed a problem that gave people problems when exiting the game and attempting to get back in.<BR><BR>

- Added some code to address reports from people who find exiting from the character-select screen back to the server-select screen rather slow when mip-mapping is enabled.  Most of this problem is due to routines in DX required to release resources consumed by mip-mapping and may not be addressable until the next version of DirectX is adopted.<BR><BR>

- Changed customizable key mappings so that the ESC key will clear the "NOKEY" setting instead of the "Backspace".  This means that you can now assign "Backspace" to a function in game.<BR><BR>

- Corrected a sound problem that would cause certain sounds to be played "rapid-fire" under some circumstances.  There is still a potential for this to happen with some other sounds that will be addressed in a patch in the near future.<BR><BR>

- Corrected a problem in Kedge Keep that made the top encounter more difficult than intended after the server had been up for a while.<BR><BR>

- Higher level Magician, Necromancer, and Shadowknight pets now have the ability to dual-wield without being handed weapons.  The calculation used to determine whether or not this ability exists takes several things into account, but for the most part 39th level and above summons (higher for the Shadowknight) will have this ability.  It is possible that you could get a "good" 34th level pet that will, or a "bad" 39th level pet that will not have this ability.<BR><BR>

- Bards of the land, hark unto me: The notes have been scribed on tattered parchment, two score and nine, for you they are meant.  Abandon your mates, though they may fume, and follow the call of the seafarer's tune.<BR><BR>

- The Monk's hand-to-hand skill cap has been raised to a level equal to their one-handed blunt skill.<BR><BR>

Remember! Only a few days left until the launch of EverQuest: The Scars of Velious.  Reserve your copy at your local retailer today!<BR><BR>


- The EverQuest Team<BR><BR>
</FONT></FONT></TD></TR></TABLE></DIV>		</TD>
	</TR>
	</TABLE>
	<BR>
	</TD>
	<TD VALIGN="top">
	<TABLE CELLPADDING="3" CELLSPACING="3" WIDTH="250" VALIGN="top" BORDER="0">
	<TR>
		<TD VALIGN="top" bgcolor=#00001f>
			<P><CENTER><B>Images of Norrath<BR><FONT COLOR="#ff0000" SIZE="-2"> - New Feature!</FONT></FONT></B></CENTER>
			<DIV ALIGN="center"><A HREF="http://www.loreseekers.com/screenshots/daily/daily_image.jpg" TARGET="_new"><IMG SRC="http://www.loreseekers.com/screenshots/daily/tn_daily_image.jpg" WIDTH=240 HEIGHT=180 BORDER=0 HSPACE=0 ALT="Click to view full size"></A><BR>
<FONT FACE="Verdana" COLOR="#00ffff" SIZE="-2">Ever wonder where all the GM's hang?</FONT><BR><FONT FACE="Verdana" COLOR="#FFFFFF" SIZE="-2">by the Bertox Seekers.</FONT></DIV>
		</TD>
	</TR>
	
	<tr><td><BR></td></tr>
	
	<TR>
		<TD VALIGN="top" bgcolor=#00001f>
		<DIV ALIGN="center">
		<font size="-1"><b>Get an "@eqlore.com" address!</b><BR>
		<FONT COLOR="#ff0000" SIZE="-2"FACE="Verdana"> - New Feature!</FONT><BR>
		<BR>
		<table border="0" bordercolor="#000000" cellspacing="0" cellpadding="0" width="240">
		  <tr> 
		    <td valign="middle" align="center" nowrap height="25"> 
		      <table cellspacing="0" cellpadding="2" width="100%" border="0">
		        <form name="login_form" action="http://eqlore.mail.everyone.net/email/scripts/loginuser.pl" method="post">
		          <tr bgcolor="#00001F">
				  <td nowrap height="5"><font color="#FFFFFF" face="Verdana, Arial, Helvetica, sans-serif" size="2"><B>Email Login :</B></font></td><td><input type="text" name="loginName" size="12" maxlength="30"></td>
					</tr>
		          <tr bgcolor="#00001F"> 
		            <td height="2"><font color="#FFFFFF" face="Verdana, Arial, Helvetica, sans-serif" size="2"><B>Password :</B></font></td><td><input type="password" name="user_pwd" size="12" maxlength="30"></td>
		          </tr>
		          <tr bgcolor="#00001F">
				  	<td height="2" valign="bottom" align="right" COLSPAN="2"><input type="submit" name="login" value="Login">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
				  </tr>
				  <tr bgcolor="#00001F">
		            <td valign="middle" height="2" align="center" colspan="2"><font face="Verdana, Arial, Helvetica, sans-serif" color="#FFFFFF" size="2">New  users <a href="http://eqlore.mail.everyone.net/email/scripts/useragreement.pl"><b>sign up</a> now !</b></font></td>
		          </tr>
		        </form>
		      </table>
		    </td>
		  </tr>
		</table>
		<BR>
		</DIV>
		</TD>
	</TR>
	
	<tr><td><BR></td></tr>	
	
	<TR>
	<TD VALIGN="top" bgcolor=#00001f>
	<A NAME="1.0 Poll">
	<FONT SIZE="-1">
	<TABLE width=100%><TR><TD bgcolor=#00001f><div align="center"><B><font size="+1">V</font>ote :</B></div><BR><div align="center"><b><font size="-1">Will you be buying the Scars of Velious expansion pack next month?</font></b></div><table><form action="http://www.loreseekers.com/vote.php3" method="post"><input type="hidden" name="poll_id" value="1"><input type="hidden" name="poll_forwarder" value="http://www.loreseekers.com/main.phtml"><tr><td><input type="radio" name="poll_voteNr" value="1"checked > <font size="-1"><b>Yes</b></font> </td></tr><tr><td><input type="radio" name="poll_voteNr" value="2"> <font size="-1"><b>No</b></font> </td></tr><tr><td><input type="radio" name="poll_voteNr" value="3"> <font size="-1"><b>Undecided</b></font> </td></tr></table><div align="center"><input type="submit" value="Vote"></div></form></TD></TR></TABLE>	</FONT>
	</TD>
	</TR>

	<tr><td><BR></td></tr>
	
	<TR>
   		<TD bgcolor=#00001f>
		<CENTER><B>Featured Article</B> :<BR>
		<font size="-1"><FONT COLOR="#ff0000"><B>A Winter's Afternoon</B></FONT></CENTER></fONT>
<FONT FACE="Verdana" SIZE="-2">
<P><FONT SIZE="+1"><B>M</B></FONT>y weary feet before me,<BR>
And with many miles to go<BR>
I settled in on my pace<BR>
To drive me through the snow<BR>
<BR><BR>
Read the rest of this poem <A HREF="/stories/hyppy_poem.phtml">Here.</A></FONT>		</TD>
	</TR>
	
	<tr><td><BR></td></tr>
	
	<TR>
		<TD VALIGN="top" bgcolor=#00001f>
		<DIV ALIGN="center">
		<font size="-1"><b><font size="+1">N</font>orrathian History !</b><BR>
		</DIV>
		<FONT FACE="Verdana" SIZE="-2">
		<FONT SIZE="+1">T</FONT>he Reapers of Fate on Tarew Marr server recently undertook a huge project 
		to research and compile the Norrathian History.  Anyone that has any 
		information is welcome to post on our message board at: 
		<A HREF="http://www.fdsoftware.com/eq/forums/" TARGET="new">http://www.fdsoftware.com/eq/forums/</A>
		<P>
		<FONT SIZE="+1">A</FONT>ll help is welcome - we would like to gather as much information as 
		possible so that we can eventually create a complete (or as close to 
		complete) history of Norrath for all to read.
		<P>
		<FONT SIZE="+1">T</FONT>he Seekers of Lore will also aid the Reapers of Fate in this project,
		as soon as we have some results we will post them on a new section called
		"history" on this site.
		</FONT>
		</TD>
	</TR>
	
	<tr><td><BR></td></tr>
		
	<TR>
		<TD VALIGN="top" bgcolor=#00001f>
		<font size="-1"><b><font size="+1">D</font>o you want to share your lore ?<BR><font size="+1">C</font>heck our messageboards :</b><BR>
		<BR>
		<A HREF="http://www.loreseekers.com/phorum306/list.php3?num=4"><b>The Quest Forum</b></a><BR>
		<BR>
		<A HREF="http://www.loreseekers.com/phorum306/list.php3?num=3"><b>The Bazaar</b></a><BR>
		<BR>
		<A HREF="http://www.loreseekers.com/phorum306/list.php3?num=2"><b>The Roleplaying Forum</b></a><BR>
		<BR>
		<A HREF="http://www.loreseekers.com/phorum306/list.php3?num=1"><b>The Guild Forum</b></a><BR>
		<BR></font>	
		</TD>
	</TR>	
	
	</TABLE>
	</TD>
</TR>
	
	
</TABLE>

<HR WIDTH="98%">
<DIV ALIGN="center"><FONT SIZE="-2">
	<A HREF="http://www.renaissance.nl/copyright.html" TARGET="_new">Copyright</A> 1999 , 2000 <A HREF="http://www.renaissance.nl/english/" TARGET="_new">Renaissance IT</A>, All Rights Reserved.<BR>
</FONT></DIV>
<HR WIDTH="98%">

</FONT>
</DIV>
</BODY>
</HTML>
