<!--
                 This page has been created by Renaissance IT
   Renaissance Internet Technologies Copyright (c) 1999 All Rights Reserved.

             for more info on our products, please visit :
                        http://www.renaissance.nl/

	This script has been written by Roy Boverhof <rboverhof@renaissance.nl>
	
        Pagename                : library.html
        Last Updated    		: 13-6-1999
-->

<HTML>
<HEAD>
	<TITLE>the Seekers of Lore : Library</TITLE>
</HEAD>

<BODY BGCOLOR="#000000" TEXT="#000000" LINK="#FFF000">
<DIV ALIGN="CENTER">
<BR>
<script type="text/javascript"><!--
google_ad_client = "pub-0988179937943699";
google_ad_width = 468;
google_ad_height = 60;
google_ad_format = "468x60_as";
google_ad_channel ="7352298734";
google_page_url = document.location;
google_color_border = "FFFFFF";
google_color_bg = "00001F";
google_color_link = "FFFFFF";
google_color_url = "FFF000";
google_color_text = "0000FF";
//--></script>
<script type="text/javascript"
  src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
</script><BR>
<TABLE CELLSPACING = 0 CELLPADDING = 0 BORDER = 0>
<TR>
	<TD width="63"><IMG SRC = "graphics/topc000.jpg" WIDTH = 63 HEIGHT = 87></TD>
	<TD width="473"><IMG SRC = "graphics/topc001.jpg" WIDTH = 473 HEIGHT = 87></TD>
	<TD width="64"><IMG SRC = "graphics/topc002.jpg" WIDTH = 64 HEIGHT = 87></TD>
</TR>
	<TD width="63"></TD>
	<TD BGCOLOR="#BEA279" width="460">
	<DIV ALIGN="CENTER">
	<IMG SRC="graphics/library.jpg">
	<TABLE WIDTH="460">
	<TR>
		<TD>
		<DIV ALIGN="CENTER">
		Welcome to the Seekers of Lore library.<BR>
		<BR>
		Within these pages you will find all the accumulated knowledge of our guild.
		It is here that we showcase what we have discovered, and present it to all, so that they may know more about the great land called Norrath. From detailed maps of it's varied landscape made by intrepid explorers such as yourself, to the secret words of power, known only to reclusive elderly mages; you will find it here.
		And if by chance you should come upon some previously unknown piece of Lore, then feel free to submit it to our guild, so that we may add it to the library.
		<BR>
		<BR>
		<TABLE>
		<TR>
			<TD>
			<A HREF="maps.php3">Atlas of Norrath</A><BR>
			<A HREF="arcane.php3">the Arcane</A><BR>
			<A HREF="quests.php3">Quests</A><BR>
			<A HREF="guides.php3">Guides</A><BR>
			<A HREF="beast_search.php3">Bestiary</A><BR>
			<A HREF="npc.phtml">Non Player Characters</A><BR>
			<A HREF="items.phtml">Items</A><BR>
			<A HREF="books.php3">Books</A><BR>
			</TD>
		</TR>
		</TABLE>
		</DIV>
		</TD>
	</TR>
	</TABLE>	
	</DIV>
	</TD>
	<TD width="64"></TD>
<TR>
	<TD><IMG SRC = "graphics/botc000.jpg" WIDTH = 63 HEIGHT = 87></TD>
	<TD><IMG SRC = "graphics/botc001.jpg" WIDTH = 473 HEIGHT = 87></TD>
	<TD><IMG SRC = "graphics/botc002.jpg" WIDTH = 64 HEIGHT = 87></TD>
</TR>
</TABLE>
<script type="text/javascript"><!--
google_ad_client = "pub-0988179937943699";
google_ad_width = 180;
google_ad_height = 60;
google_ad_format = "180x60_as_rimg";
google_cpa_choice = "CAAQ56j8zwEaCHvU9tBAqJJaKMu293M";
//--></script>
<script type="text/javascript" src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
</script>
<BR>
<BR>
<BR>
</DIV>
</BODY>
</HTML>
