<!--
                 This page has been created by Renaissance IT
   Renaissance Internet Technologies Copyright (c) 1999 All Rights Reserved.

             for more info on our products, please visit :
                        http://www.renaissance.nl/

	This script has been written by Roy Boverhof <rboverhof@renaissance.nl>
	
        Pagename                : screenshots.html
        Last Updated    		: 08-07-2000
-->

<HTML>
<HEAD>
	<TITLE>the Seekers of Lore : screenshots</TITLE>
</HEAD>

<BODY BGCOLOR="#000000" TEXT="#000000" LINK="#000000" VLINK="#000000" ALINK="#000000">
<DIV ALIGN="CENTER">
<BR>
<!-- FGN Banner Code -->
<script language="JavaScript">
	<!-- Hide from old browsers
	var random = new Number(Math.floor(9999999 * Math.random())+1);

	// Modify to reflect site specifics
	page = "eqlore.com/";
	target = "@Top1,x02,x05,x08!Top1";

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript1.1" SRC="http://oascentral.cybereps.com/RealMedia/ads/adstream_jx.ads/' + page + 1 + random + target + '">');
	document.write('</SCR');
	document.write('IPT>');

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript">');
	document.write('_version=10; //-->');
	document.write('</SCR');
	document.write('IPT>');

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript1.1">');
	document.write('_version=11; //-->');
	document.write('</SCR');
	document.write('IPT>');

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript">');

	if (navigator.appVersion.indexOf('MSIE 3') != -1){
	document.write('<IFRAME MARGINWIDTH=0 MARGINHEIGHT=0 HSPACE=0 VSPACE=0 FRAMEBORDER=0 SCROLLING=no BORDERCOLOR="#000000" SRC="oascentral.cybereps.com/RealMedia/ads/adstream_sx.ads/' + page + random + target + '"></IFRAME>');
	  }
	else if (_version < 11) {
	document.write ('<A HREF="http://oascentral.cybereps.com/RealMedia/ads/click_nx.ads/' + page + random + target + '"><IMG SRC="http://oascentral.cybereps.com/RealMedia/ads/adstream_nx.ads/' + page + random + target + '"></a>');
	  }

	document.write('</SCR');
	document.write('IPT>');

	// End Hide -->
</script>
<!-- END FGN Banner Code --><BR>	
<TABLE CELLSPACING = 0 CELLPADDING = 0 BORDER = 0>
<TR>
	<TD WIDTH="63"><IMG SRC = "graphics/topc000.jpg" WIDTH = 63 HEIGHT = 87></TD>
	<TD WIDTH="473"><IMG SRC = "graphics/topc001.jpg" WIDTH = 473 HEIGHT = 87></TD>
	<TD WIDTH="64"><IMG SRC = "graphics/topc002.jpg" WIDTH = 64 HEIGHT = 87></TD>
</TR>
	<TD WIDTH="63"></TD>
	<TD BGCOLOR="#BEA279" WIDTH="460">
	<DIV ALIGN="CENTER">
	<IMG SRC="graphics/screencap_header.gif">
	<TABLE WIDTH="460">
	<TR><TD>

<TABLE BGCOLOR="#BEA279" WIDTH=420 CELLPADDING=5 CELLSPACING=5 ALIGN="center">
<TR>
<TD BGCOLOR="#BEA279" WIDTH=20></TD>
<TD GCOLOR="#BEA279" WIDTH=380>
<FONT FACE="Verdana" SIZE="2">
<HR>

<B>1. <A HREF="velious_shots.phtml">Scars of Velious</A><FONT COLOR="#FF0000"> - New!!</FONT></B><BR>&nbsp;&nbsp;&nbsp; - <FONT SIZE="-2">Images from the frigid continent of Velious.</FONT><BR><BR>

<B>2. <A HREF="screenshots/daily/daily_image.jpg" TARGET="_new">Daily Image</A></B><BR>&nbsp;&nbsp;&nbsp; - <FONT SIZE="-2">Daily images of Norrath.</FONT><BR><BR>

<B>3. <A HREF="xegony_shots.phtml">Xegony Server</A></B><BR>&nbsp;&nbsp;&nbsp; - <FONT SIZE="-2">Pictures from our Xegony branch.</FONT><BR><BR>

<B>4. <A HREF="bertox_shots.phtml">Bertoxxulous Server</A></B><BR>&nbsp;&nbsp;&nbsp; - <FONT SIZE="-2">Pictures from our Bertoxxulous chapter</FONT><BR><BR>

<B>5. <A HREF="dragon_shots.phtml">Veeshan Event</A></B><BR>&nbsp;&nbsp;&nbsp;- <FONT SIZE="-2">Shots of some impressive dragons during GM<BR>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;event on Veeshan</FONT><BR><BR>

<B>6. <A HREF="rok_screenshots.phtml">Ruins of Kunark™</A></B><BR>&nbsp;&nbsp;&nbsp; - <FONT SIZE="-2">Screenshots from the expansion</FONT><BR><BR>

<B>7. <A HREF="rathe_screenshots.phtml">Rathe Server</A></B><BR>&nbsp;&nbsp;&nbsp; - <FONT SIZE="-2">Pictures from our Rathe chapter</FONT><BR><BR>

<B>8. <A HREF="bristlebane_shots.phtml">Bristlebane Server</A></B><BR>&nbsp;&nbsp;&nbsp; - <FONT SIZE="-2">Pictures from our Bristlebane chapter</FONT><BR><BR>

<B>9. <A HREF="http://www.netset.com/~hans/seekers/" TARGET="_new">Cazic-Thule Server</A></B><BR>&nbsp;&nbsp;&nbsp; - <FONT SIZE="-2">Pictures from our Cazic-Thule chapter</FONT><BR><BR>

<B>10. <A HREF="http://www.rit.edu/~jco2641/eqwedding.html" TARGET="_new">Wedding</A></B><BR>&nbsp;&nbsp;&nbsp; - <FONT SIZE="-2">Pictures from a wedding on Bristlebane</FONT><BR><BR>
<HR>
</FONT>

</TD>
<TD BGCOLOR="#BEA279" WIDTH=20></TD>
</TR>
</TABLE>

	</TD></TR>
	</TABLE>
	<TD WIDTH="64"></TD>
<TR>
	<TD><IMG SRC = "graphics/botc000.jpg" WIDTH = 63 HEIGHT = 87></TD>
	<TD><IMG SRC = "graphics/botc001.jpg" WIDTH = 473 HEIGHT = 87></TD>
	<TD><IMG SRC = "graphics/botc002.jpg" WIDTH = 64 HEIGHT = 87></TD>
</TR>
</TABLE>
<BR>

<script language="JavaScript">
	<!-- Hide from old browsers
	var random = new Number(Math.floor(9999999 * Math.random())+1);

	// Modify to reflect site specifics
	page = "eqlore.com/";
	target = "@Top1,x02,x05,x08!x02";

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript1.1" SRC="http://oascentral.cybereps.com/RealMedia/ads/adstream_jx.ads/' + page + 1 + random + target + '">');
	document.write('</SCR');
	document.write('IPT>');

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript">');
	document.write('_version=10; //-->');
	document.write('</SCR');
	document.write('IPT>');

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript1.1">');
	document.write('_version=11; //-->');
	document.write('</SCR');
	document.write('IPT>');

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript">');

	if (navigator.appVersion.indexOf('MSIE 3') != -1){
	document.write('<IFRAME MARGINWIDTH=0 MARGINHEIGHT=0 HSPACE=0 VSPACE=0 FRAMEBORDER=0 SCROLLING=no BORDERCOLOR="#000000" SRC="oascentral.cybereps.com/RealMedia/ads/adstream_sx.ads/' + page + random + target + '"></IFRAME>');
	  }
	else if (_version < 11) {
	document.write ('<A HREF="http://oascentral.cybereps.com/RealMedia/ads/click_nx.ads/' + page + random + target + '"><IMG SRC="http://oascentral.cybereps.com/RealMedia/ads/adstream_nx.ads/' + page + random + target + '"></a>');
	  }

	document.write('</SCR');
	document.write('IPT>');

	// End Hide -->
</script><BR>
<BR>
</DIV>
</BODY>
</HTML>

