<!--
                 This page has been created by Renaissance IT
   Renaissance Internet Technologies Copyright (c) 1999 All Rights Reserved.

             for more info on our products, please visit :
                        http://www.renaissance.nl/

	This script has been written by Roy Boverhof <rboverhof@renaissance.nl>
	
        Pagename                : base_prices.html
        Last Updated    		: 31-01-2000
-->

<HTML>
<HEAD>
	<TITLE>the Seekers of Lore : Base Prices Chart</TITLE>
</HEAD>

<BODY BGCOLOR="#000000" TEXT="#000000" LINK="#000000" VLINK="#000000" ALINK="#000000">
<DIV ALIGN="CENTER">
<BR>
<!-- FGB Banner Code -->
<SCRIPT LANGUAGE="JavaScript">
   <!-- Hide from old browsers
   now = new Date();
   random = now.getTime();
     
   // Modify to reflect site specifics
   site = "http://ds.cybereps.com";
   target = "/SITE=FGN/AREA=EQLORE/AAMSZ=BANNER";
   
   document.write('<IFRAME SRC="' + site + '/hserver/acc_random=' + random + target + '"');
   document.write(' NORESIZE SCROLLING=NO HSPACE=0 VSPACE=0 FRAMEBORDER=0 MARGINHEIGHT=0 MARGINWIDTH=0 WIDTH=468 HEIGHT=60>');
   
   document.write('<SCR');
   document.write('IPT SRC="' + site + '/jnserver/acc_random=' + random + target + '">');
   document.write('</SCR');
   document.write('IPT>');
   
   document.write('</IFRAME>');
   // End Hide -->
 </SCRIPT>
 <NOSCRIPT> 
   <A HREF="http://ds.cybereps.com/accipiter/adclick/SITE=FGN/AREA=EQLORE/AAMSZ=BANNER">
   <IMG SRC="http://ds.cybereps.com/accipiter/nserver/SITE=FGN/AREA=EQLORE/AAMSZ=BANNER" border="0"></A>
 </NOSCRIPT>
<!-- END FGB Banner Code --><BR>
<TABLE CELLSPACING = 0 CELLPADDING = 0 BORDER = 0>
<TR>
	<TD width="63"><IMG SRC = "http://www.loreseekers.com/graphics/topc000.jpg" WIDTH = 63 HEIGHT = 87></TD>
	<TD width="473"><IMG SRC = "http://www.loreseekers.com/graphics/topc001.jpg" WIDTH = 473 HEIGHT = 87></TD>
	<TD width="64"><IMG SRC = "http://www.loreseekers.com/graphics/topc002.jpg" WIDTH = 64 HEIGHT = 87></TD>
</TR>
	<TD width="63"></TD>
	<TD BGCOLOR="#BEA279" width="460">
	<DIV ALIGN="CENTER">
	<TABLE>
	<TR>
	<TD BGCOLOR="#BEA279" width="450">

<P ALIGN="left"><FONT SIZE="4" face="helvetica"><STRONG>B. Base Prices</STRONG></FONT></A></P>

<!-- START OF CONVERTED OUTPUT -->
<!-- ------------------------- -->
<Table border BGCOLOR="#BEA279">
<TR VALIGN="bottom">
<TD ALIGN="right" VALIGN="bottom"><FONT FACE="Verdana" SIZE="1">
&nbsp;</FONT></TD>
<TD ALIGN="right" VALIGN="bottom"><FONT FACE="Verdana" SIZE="1">
&nbsp;</FONT></TD>
<TD BGCOLOR=#800000  ALIGN="center" VALIGN="middle"><FONT FACE="Verdana" SIZE="1" COLOR=#FFFFFF><B>
Gem</B></FONT></TD>
<TD BGCOLOR=#800000  ALIGN="center" VALIGN="middle"><FONT FACE="Verdana" SIZE="1" COLOR=#FFFFFF><B>
Silver</B></FONT></TD>
<TD BGCOLOR=#800000  ALIGN="center" VALIGN="middle"><FONT FACE="Verdana" SIZE="1" COLOR=#FFFFFF><B>
Electrum</B></FONT></TD>
<TD BGCOLOR=#800000  ALIGN="center" VALIGN="middle"><FONT FACE="Verdana" SIZE="1" COLOR=#FFFFFF><B>
Gold</B></FONT></TD>
<TD BGCOLOR=#800000  ALIGN="center" VALIGN="middle"><FONT FACE="Verdana" SIZE="1" COLOR=#FFFFFF><B>
Platinum</B></FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD BGCOLOR=#800000 ALIGN="center"><FONT FACE="Verdana" SIZE="1" COLOR=#FFFFFF><B>
Stone</B></FONT></TD>
<TD BGCOLOR=#800000 ALIGN="center"><FONT FACE="Verdana" SIZE="1" COLOR=#FFFFFF><B>
Property</B></FONT></TD>
<TD BGCOLOR=#800000 ALIGN="center"><FONT FACE="Verdana" SIZE="1" COLOR=#FFFFFF><B>
P.G.S.C</B></FONT></TD>
<TD BGCOLOR=#800000 ALIGN="center"><FONT FACE="Verdana" SIZE="1" COLOR=#FFFFFF><B>
P.G.S.C</B></FONT></TD>
<TD BGCOLOR=#800000 ALIGN="center"><FONT FACE="Verdana" SIZE="1" COLOR=#FFFFFF><B>
P.G.S.C</B></FONT></TD>
<TD BGCOLOR=#800000 ALIGN="center"><FONT FACE="Verdana" SIZE="1" COLOR=#FFFFFF><B>
P.G.S.C</B></FONT></TD>
<TD BGCOLOR=#800000 ALIGN="center"><FONT FACE="Verdana" SIZE="1" COLOR=#FFFFFF><B>
P.G.S.C</B></FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD BGCOLOR=#FFFFCC ALIGN="left"><FONT FACE="Verdana" SIZE="1">
Malachite</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
Vs Pois</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
0.0.5.2</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
0.5.7.7</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
2.6.7.7</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
10.5.5.2</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
105.0.5.2</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD BGCOLOR=#FFFFCC ALIGN="left"><FONT FACE="Verdana" SIZE="1">
Lapis Lazuli</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
Vs Dis</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
0.0.9.4</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
0.6.1.9</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
2.7.1.9</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
10.5.9.4</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
105.0.9.4</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD BGCOLOR=#FFFFCC ALIGN="left"><FONT FACE="Verdana" SIZE="1">
Turquiose</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
Vs Cold</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
0.1.1.5</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
0.6.4.0</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
2.7.4.0</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
10.6.1.5</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
105.1.1.5</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD BGCOLOR=#FFFFCC ALIGN="left"><FONT FACE="Verdana" SIZE="1">
Hematite</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
Vs Fire</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
0.1.5.7</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
0.6.8.2</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
2.7.8.2</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
10.6.5.7</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
105.1.5.7</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD BGCOLOR=#FF9900 ALIGN="left"><FONT FACE="Verdana" SIZE="1">
Wolf's Eye Agate</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
Vs Magic</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
0.1.6.0</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
0.6.8.5</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
2.7.8.5</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
10.6.6.0</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
105.1.6.0</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD BGCOLOR=#FFFFCC ALIGN="left"><FONT FACE="Verdana" SIZE="1">
Cat's Eye Agate</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
CHR</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
0.2.1.0</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
0.7.3.5</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
2.8.3.5</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
10.7.1.0</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
105.2.1.0</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD BGCOLOR=#FFFFCC ALIGN="left"><FONT FACE="Verdana" SIZE="1">
Bloodstone</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
STA</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
0.5.2.5</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
1.0.5.0</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
3.1.5.0</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
11.0.2.5</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
105.5.2.5</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD BGCOLOR=#FFFFCC ALIGN="left"><FONT FACE="Verdana" SIZE="1">
Onyx</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
DEX</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
0.6.5.2</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
1.1.7.7</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
3.2.7.7</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
11.1.5.2</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
105.6.5.2</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD BGCOLOR=#FFFFCC ALIGN="left"><FONT FACE="Verdana" SIZE="1">
Jasper</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
WIS</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
0.7.8.7</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
1.3.1.2</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
3.4.1.2</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
11.2.8.7</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
105.7.8.7</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD BGCOLOR=#FFFFCC ALIGN="left"><FONT FACE="Verdana" SIZE="1">
Carnelian</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
AGI</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
0.8.9.2</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
1.4.1.7</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
3.5.1.7</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
11.3.9.2</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
105.8.9.2</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD BGCOLOR=#FFFFCC ALIGN="left"><FONT FACE="Verdana" SIZE="1">
Star Rose Quartz</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
INT</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
1.0.5.0</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
1.5.7.5</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
3.6.7.5</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
11.5.5.0</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
106.0.5.0</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD BGCOLOR=#FFFFCC ALIGN="left"><FONT FACE="Verdana" SIZE="1">
Amber</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
STR</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
2.6.2.5</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
3.1.5.0</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
5.2.5.0</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
13.1.2.5</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
107.6.2.5</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD BGCOLOR=#FFFFCC ALIGN="left"><FONT FACE="Verdana" SIZE="1">
Jade</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
Mana / HP / AC</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
3.6.7.5</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
4.2.0.0</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
6.3.0.0</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
14.1.7.5</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
108.6.7.5</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD BGCOLOR=#FFFFCC ALIGN="left"><FONT FACE="Verdana" SIZE="1">
Pearl</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
Vs Pois / AC</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
4.7.2.5</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
5.2.5.0</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
7.3.5.0</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
15.2.2.5</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
109.7.2.5</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD BGCOLOR=#FFFFCC ALIGN="left"><FONT FACE="Verdana" SIZE="1">
Topaz</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
Vs   Dis / AC</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
5.2.5.0</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
5.7.7.5</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
7.8.7.5</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
15.7.5.0</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
110.2.5.0</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD BGCOLOR=#FFFFCC ALIGN="left"><FONT FACE="Verdana" SIZE="1">
Peridot</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
Vs Cold / AC</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
10.5.0.0</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
11.0.2.5</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
13.1.2.5</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
21.0.0.0</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
115.5.0.0</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD BGCOLOR=#FFFFCC ALIGN="left"><FONT FACE="Verdana" SIZE="1">
Emerald</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
Vs   Fire / AC</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
13.6.5.0</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
14.1.7.5</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
16.2.7.5</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
24.1.5.0</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
118.6.5.0</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD BGCOLOR=#FF9900 ALIGN="left"><FONT FACE="Verdana" SIZE="1">
Jacinth</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
Vs Magic / AC</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
13.6.5.5</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
14.1.8.0</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
16.2.8.0</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
24.1.5.5</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
118.6.5.5</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD BGCOLOR=#FFFFCC ALIGN="left"><FONT FACE="Verdana" SIZE="1">
Opal</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
Sta / Agi</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
17.8.5.0</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
18.3.7.5</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
20.4.7.5</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
28.3.5.0</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
122..8.5.0</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD BGCOLOR=#FF9900 ALIGN="left"><FONT FACE="Verdana" SIZE="1">
Black Pearl</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
Dex / Agi</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
21.0.0.0</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
21.5.2.5</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
23.6.2.5</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
31.5.0.0</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
126.0.0.0</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD BGCOLOR=#FFFFCC ALIGN="left"><FONT FACE="Verdana" SIZE="1">
Star Ruby</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
Dex / Chr</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
68.2.5.0</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
68.7.7.5</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
70.8.7.5</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
78.7.5.0</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
173.2.5.0</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD BGCOLOR=#FFFFCC ALIGN="left"><FONT FACE="Verdana" SIZE="1">
Fire Emerald</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
Str / Dex</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
89.2.5.0</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
89.7.7.5</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
91.8.7.5</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
99.7.5.0</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
194.2.5.0</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD BGCOLOR=#FFFFCC ALIGN="left"><FONT FACE="Verdana" SIZE="1">
Sapphire</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
Str / Int</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
105.0.0.0</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
105.5.2.5</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
107.6.2.5</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
115.5.0.0</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
210.0.0.0</FONT></TD>
</TR>
<TR VALIGN="bottom">
<TD BGCOLOR=#FFFFCC ALIGN="left"><FONT FACE="Verdana" SIZE="1">
Ruby</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
Str / Wis</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
131.0.0.0</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
131.5.2.5</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
133.6.2.5</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
141.5.0.0</FONT></TD>
<TD ALIGN="center"><FONT FACE="Verdana" SIZE="1">
236.0.0.0</FONT></TD>
</TR>
</TABLE>
<!-- ------------------------- -->
<!-- END OF CONVERTED OUTPUT -->
<!-- ------------------------- -->


<BR><BR><DIV ALIGN="center"><A HREF="new_jewelry_guide.phtml" TARGET="_self"><IMG SRC="back_button.jpg" WIDTH=200 HEIGHT=50 BORDER=0 ALIGN="MIDDLE" ALT="Back to the Guide"></A></DIV><BR><BR>


</TR>
</TABLE>
	<TD width="64"></TD>
<TR>
	<TD><IMG SRC = "http://www.loreseekers.com/graphics/botc000.jpg" WIDTH = 63 HEIGHT = 87></TD>
	<TD><IMG SRC = "http://www.loreseekers.com/graphics/botc001.jpg" WIDTH = 473 HEIGHT = 87></TD>
	<TD><IMG SRC = "http://www.loreseekers.com/graphics/botc002.jpg" WIDTH = 64 HEIGHT = 87></TD>
</TR>
</TABLE>
<BR>
 <SCRIPT LANGUAGE="JavaScript">
   <!-- Hide from old browsers
   now = new Date();
   random = now.getTime();
   
   // Modify to reflect site specifics
   site = "http://ds.cybereps.com";
   target = "/SITE=FGN/AREA=EQLORE/AAMSZ=BOX";
   
   document.write('<IFRAME SRC="' + site + '/hserver/acc_random=' + random + target + '"');
   document.write(' NORESIZE SCROLLING=NO HSPACE=0 VSPACE=0 FRAMEBORDER=0 MARGINHEIGHT=0 MARGINWIDTH=0 WIDTH=125 HEIGHT=125>');
      
   document.write('<SCR');
   document.write('IPT SRC="' + site + '/jnserver/acc_random=' + random + target + '">');
   document.write('</SCR');
   document.write('IPT>');
   
   document.write('</IFRAME>');
   // End Hide -->
 </SCRIPT>
 <NOSCRIPT> 
   <A HREF="http://ds.cybereps.com/accipiter/adclick/SITE=FGN/AREA=EQLORE/AAMSZ=BOX">
   <IMG SRC="http://ds.cybereps.com/accipiter/nserver/SITE=FGN/AREA=EQLORE/AAMSZ=BOX" border="0"></A>
 </NOSCRIPT>
<BR>
<BR>
</DIV>
</BODY>
</HTML>



