<!--
                 This page has been created by Renaissance IT
   Renaissance Internet Technologies Copyright (c) 1999 All Rights Reserved.

             for more info on our products, please visit :
                        http://www.renaissance.nl/

	This script has been written by Roy Boverhof <rboverhof@renaissance.nl>
	
        Pagename                : links5.phtml
        Last Updated    		: 27-6-2001
-->

<HTML>
<HEAD>
	<TITLE>the Seekers of Lore : Specialized EQ Links</TITLE>
</HEAD>

<BODY BGCOLOR="#000000" TEXT="#000000" LINK="#000000" VLINK="#000000" ALINK="#000000">
<DIV ALIGN="CENTER">
<BR>
<script type="text/javascript"><!--
google_ad_client = "pub-0988179937943699";
google_ad_width = 468;
google_ad_height = 60;
google_ad_format = "468x60_as";
google_ad_channel ="";
google_page_url = document.location;
google_color_border = "FFFFFF";
google_color_bg = "00001F";
google_color_link = "FFFFFF";
google_color_url = "FFF000";
google_color_text = "0000FF";
//--></script>
<script type="text/javascript"
  src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
</script><BR>
<TABLE CELLSPACING = 0 CELLPADDING = 0 BORDER = 0>
<TR>
	<TD width="63"><IMG SRC = "graphics/topc000.jpg" WIDTH = 63 HEIGHT = 87></TD>
	<TD width="473"><IMG SRC = "graphics/topc001.jpg" WIDTH = 473 HEIGHT = 87></TD>
	<TD width="64"><IMG SRC = "graphics/topc002.jpg" WIDTH = 64 HEIGHT = 87></TD>
</TR>
	<TD width="63"></TD>
	<TD BGCOLOR="#BEA279" width="460">
	<DIV ALIGN="CENTER">
	<A HREF="links.phtml"><IMG SRC="graphics/linkheader.jpg" WIDTH ="200" HEIGHT ="75" ALT="Back to Links Index" BORDER="0"></A>
	<TABLE WIDTH=440 ALIGN="center">
	<TR><TD></TD></TR>
	<TR>
		<TD>
		<DIV ALIGN="center"><B><A HREF="http://graffe.com/darkmoon/" TARGET="_new">Darkmoon</A></B></DIV>
		</TD>
		<TD><FONT FACE="Verdana" SIZE="-2">Darkmoon is a evil roleplaying guild made up of Dark Elves, Trolls and Orgres</FONT></TD>
	</TR>
	
	<TR>
		<TD>
		<B><DIV ALIGN="center"><A HREF="http://www.eqalliance.com/eq/eqindex.htm" TARGET="_new">Alliance of the Griffin</A></DIV></B>
		</TD>
		<TD><FONT FACE="Verdana" SIZE="-2">Alliance of the Griffin</FONT></TD>
	</TR>	
	
	<TR>
		<TD>
		<B><DIV ALIGN="center"><A HREF="http://www.notacult.com" TARGET="_new">Flowers of Happiness</A></DIV></B>
		</TD>
		<TD><FONT FACE="Verdana" SIZE="-2"><FONT FACE="Verdana" SIZE="-2" COLOR="#FF0000">New! - </FONT>Flowers of Happiness, a guild on the PvP server Rallos Zek.</FONT></TD>
	</TR>	
	
	<TR>
		<TD></TD>
		<TD><BR><BR><BR></TD>
	</TR>	
	
	
	<TR>
		<TD>
		<A HREF="mailto:webmaster@loreseekers.com?subject=links"><IMG SRC="graphics/submit_link.jpg" WIDTH ="220" HEIGHT ="75" BORDER="0"></A>
		</TD>
		<TD><I>Do you know a quality EverQuest site? Email us your link!</I></TD>
	</TR>
	</TABLE>
	<TD width="64"></TD>
<TR>
	<TD><IMG SRC = "graphics/botc000.jpg" WIDTH = 63 HEIGHT = 87></TD>
	<TD><IMG SRC = "graphics/botc001.jpg" WIDTH = 473 HEIGHT = 87></TD>
	<TD><IMG SRC = "graphics/botc002.jpg" WIDTH = 64 HEIGHT = 87></TD>
</TR>
</TABLE>
<BR>
<IMG SRC="http://service.bfast.com/bfast/serve?bfmid=1375281&siteid=40292692&bfpage=pc" BORDER="0" WIDTH="1" HEIGHT="1" NOSAVE ><A HREF="http://service.bfast.com/bfast/click?bfmid=1375281&siteid=40292692&bfpage=pc" TARGET="_new"><IMG SRC="http://affiliate.gamestop.com/affIMG/pc_120x60.gif" BORDER="0" WIDTH="120" HEIGHT="60" ALT="PC Games at GameStop.com"></A>
<BR>
<BR>
</DIV>
</BODY>
</HTML>

