<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">

<html>
<head>
	<title>..:: EQBard : le site de Jonili le petit barde ::..</title>

<SCRIPT LANGUAGE="Javascript">
<!--
function fenetre(intitule,params) { 
var fen = window.open(intitule,'zoom',params); 
}
//-->
</script>

<style>
a.lientexte {color:#0B5040;text-decoration:none;}
a.lientexte:hover {color:#0B5040;text-decoration:underline;}
</style>
</head>

<body bgcolor='#CFE6E3' text='#000000' link='#0B5040' vlink='#000000' alink='#000000'>
<table width='680' border='0' cellspacing='0' cellpadding='0'>
<tr><td>
<table width='680' border='0' cellspacing='0' cellpadding='0'>
<tr>
<td width='680' align='right' valign='top'>
<img src='./img/commun/c01/carre80.gif' width='10' height='10' border='0' alt=''>
<img src='./img/commun/c01/carre70.gif' width='10' height='10' border='0' alt=''>
<img src='./img/commun/c01/carre60.gif' width='10' height='10' border='0' alt=''>
<img src='./img/commun/c01/carre50.gif' width='10' height='10' border='0' alt=''>
</td></tr>
<tr><td height='2'><img src='./img/commun/transparent.gif' height='2' alt='' border='0'></td></tr>
<tr><td width='680' height='1'><img src='./img/commun/c01/carre50.gif' width='680' height='1' alt='' border='0'></td></tr>
</table>
</td></tr><tr><td>
<table width='680' border='0' cellspacing='0' cellpadding='0'>
<tr><td width='120' valign='top'><table width='100%' border='0' cellspacing='0' cellpadding='0'>
<tr><td>
<font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>&nbsp;<br>
<img src='./img/commun/c01/carre70.gif' width='10' height='10' border='0' alt=''>&nbsp;<a href=index.php?menu=1&data=1 class=lientexte><b>Accueil</b></a><br>&nbsp;<br>
<img src='./img/commun/c01/carre70.gif' width='10' height='10' border='0' alt=''>&nbsp;<b>Equipement</b><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=32&data=31&inc=armures class=lientexte>Armures</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=33&data=31&inc=armes&order=1&sens=1&bard=1 class=lientexte>Armes</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=35&data=31&inc=slot class=lientexte>Par slot</a><br>&nbsp;<br>
<img src='./img/commun/c01/carre70.gif' width='10' height='10' border='0' alt=''>&nbsp;<b>Guides</b><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=41&data=41 class=lientexte>Général</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=42&data=42 class=lientexte>Tactiques</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carreselect.gif' width='5' height='5' border='0' alt=''>&nbsp;Quêtes<br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=44&data=44 class=lientexte>Zones</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=45&data=45 class=lientexte>Procs</a><br>&nbsp;<br>
<img src='./img/commun/c01/carre70.gif' width='10' height='10' border='0' alt=''>&nbsp;<b>Photos</b><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=51&data=51 class=lientexte>Atlas</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=52&data=52 class=lientexte>Bardes</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=54&data=54 class=lientexte>GM</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=55&data=55 class=lientexte>Divers</a><br>&nbsp;<br>
<img src='./img/commun/c01/carre70.gif' width='10' height='10' border='0' alt=''>&nbsp;<a href=index.php?menu=8&data=8 class=lientexte><b>Mode</b></a><br>&nbsp;<br>
<img src='./img/commun/c01/carre70.gif' width='10' height='10' border='0' alt=''>&nbsp;<b>Spells Sebilis</b><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=1001&data=10 class=lientexte>Barde</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=1002&data=10 class=lientexte>Belluaire</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=1003&data=10 class=lientexte>Chaman</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=1004&data=10 class=lientexte>Clerc</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=1005&data=10 class=lientexte>Druide</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=1006&data=10 class=lientexte>Enchanteur</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=1007&data=10 class=lientexte>Fléau d'ombre</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=1009&data=10 class=lientexte>Magicien</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=1012&data=10 class=lientexte>Nécromancien</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=1013&data=10 class=lientexte>Paladin</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=1014&data=10 class=lientexte>Rôdeur</a><br>
&nbsp;&nbsp;&nbsp;<img src='./img/commun/c01/carre60.gif' width='5' height='5' border='0' alt=''>&nbsp;<a href=index.php?menu=1015&data=10 class=lientexte>Sorcier</a><br>&nbsp;<br>
<img src='./img/commun/c01/carre70.gif' width='10' height='10' border='0' alt=''>&nbsp;<a href=index.php?menu=6&data=6 class=lientexte><b>Liens</b></a><br>
<img src='./img/commun/c01/carre70.gif' width='10' height='10' border='0' alt=''>&nbsp;<a href=index.php?menu=7&data=7 class=lientexte><b>Download</b></a><br>
<img src='./img/commun/c01/carre70.gif' width='10' height='10' border='0' alt=''>&nbsp;<a href='http://forumsfr.ubi.com/messages/overview.asp?name=eq_themaeq_eqbardes' target='_blank' class=lientexte><b>Forum</b></a><br>
<img src='./img/commun/c01/carre70.gif' width='10' height='10' border='0' alt=''>&nbsp;<a href=mailto:jonili@eqbard.eqloft.com class=lientexte><b>M'écrire</b></a><br>&nbsp;<br>
<img src='./img/commun/c01/carre70.gif' width='10' height='10' border='0' alt=''>&nbsp;<a href=index.php?menu=9&data=9 class=lientexte><b>Backstage</b></a><br>&nbsp;<br></font></td></tr></table>
</td><td width='20' valign='top'><img src='./img/commun/c01/carre50.gif' width='10' height='10' border='0' alt=''>
<img src='./img/commun/c01/carre60.gif' width='10' height='10' border='0' alt=''>
<img src='./img/commun/c01/carre70.gif' width='10' height='10' border='0' alt=''>
<img src='./img/commun/c01/carre80.gif' width='10' height='10' border='0' alt=''>
</td><td width='540' align='left' valign='top'><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>&nbsp;<br><a href='index.php?menu=43&data=43 class=lientexte' class=lientexte><b>< Retour</b></a><br>&nbsp;<br><table width='100%' border='0' cellspacing='0' cellpadding='0'><tr><td colspan='2' bgcolor='#0B5040'><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2' color='white'><b>&nbsp;La clé de Veeshan's Peak : The Rune of Scale</b></font></td></tr><tr><td width ='10'>&nbsp;</td><td><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>&nbsp;<br>
Veeshan's Peak est l'un des plus gros donjons du jeu. Pour pouvoir y entrer, vous devez posséder une clé obtenue par une quête.
<br>&nbsp;<br>
Vous devez rassembler 4 objets :
<ul>
<li>Trakanon's tooth
<li>Medallion of the Jarsath
<li>Medallion of the Obulus
<li>Medallion of the Kylong
</ul>

</font>&nbsp;<br></td></tr><tr><td colspan='2' bgcolor='#0B5040'><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2' color='white'><b>&nbsp;1. Trakanon's tooth</b></font></td></tr><tr><td width ='10'>&nbsp;</td><td><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>&nbsp;<br>
Cette dent se trouve sur Trakanon, le dragon qui hante le fond de Odl Sebilis. Vous devez rassembler plusieurs groupes pour abattre ce dragon. Il lance un dot de poison AoE qui fait d'énormes dégats.
<br>&nbsp;<br>
</font>&nbsp;<br></td></tr><tr><td colspan='2' bgcolor='#0B5040'><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2' color='white'><b>&nbsp;2. Medallion of the Jarsath</b></font></td></tr><tr><td width ='10'>&nbsp;</td><td><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>&nbsp;<br>
Ce médaillon est en 3 morceaux.
<br>&nbsp;<br>
Le morceau du haut se trouve par terre dans Swamp of no Hope, loc +52,+2935.
<br>&nbsp;<br>
Le morceau du milieu se trouve sur <b>an ancien Jarsath</b>, un undead qui traine dans Firiona Vie. C'est à priori le seul undead de la zone, donc pas très dur à trouver avec sens undead. Il spawne toutes les 24H et se promène dans la zone. Il est bleu au lvl 56 et je l'ai tué en solo très facilement.
<br>&nbsp;<br>
Le morceau du bas se trouve sur le <b>Bloogill Marauder</b> qui se trouve dans le lac de Lake of Ill Omen, loc -375,-40.
<br>&nbsp;<br>
Apporter les 3 morceaux à <b>Xiblin Fizzlebik</b> qui est sur l'ile avec l'echiquier dans Timorous Deep (-6200,+2800).
<ul>
<li>You say, 'Hail, Xiblin Fizzlebik'
<li>Xiblin Fizzlebik says 'Hello, Jonili!  I am Xiblin Fizzlebik, renowned archeologist and historian of Ak'Anon.  I'm currently in search of artifacts and relics on the Iksar [Jarsath tribe].  If you stumble upon anything, please bring it to me.'
<li>You say, 'what Jarsath tribe ?'
<li>Xiblin Fizzlebik says 'About two thousand years ago, there were five different tribes of Iksar who dwelled on the continent of Kunark.  One of these tribes was the Jarsath.  They were a very primitive sort, proud and tribal, but also cannibalistic.  Often, they went to war with the other tribes that co-existed with them, back then.  The ruins found on this island were of structures created by the Jarsath.  I've been excavating for quite some time now, but haven't been able to find anything of significance.'
<li>You say, 'What are you looking for ?'
<li>Xiblin Fizzlebik says 'In my studies, I have learned that the Jarsath believed they could draw power from a holy symbol, specifically, a medallion that represented their tribe.  When Salthir became king of the Iksar empire, Sebilis, he had the medallion broken into three pieces and hid them on the Kunark continent so that they would never be found.  I'm searching for the pieces so that I can put it back together and learn more about this tribe.  Perhaps you wish to help?'
<li>You say, 'I will help you'
<li>Xiblin Fizzlebik says 'All I know is that the pieces were most likely hidden in watery regions.  If you manage to find them, bring them to me and I will be able to put the medallion of the Jarsath back together.  I am sure there is much to be learned from it.'
<li>Donnez les 3 morceaux du médaillon
<li>Xiblin Fizzlebik tinkers with the three pieces and snaps the pieces together.  'Wow..  You've done it.. but I suddenly feel very.. strange..  This medallion is cursed!  Here, you take it!'
</ul>

</font>&nbsp;<br></td></tr><tr><td colspan='2' bgcolor='#0B5040'><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2' color='white'><b>&nbsp;3. Medallion of the Obulus</b></font></td></tr><tr><td width ='10'>&nbsp;</td><td><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>&nbsp;<br>
Ce médaillon est en 3 morceaux.
<br>&nbsp;<br>
Le morceau du haut se trouve sur <b>Sselot Dnaas</b> qui spawn sur l'ile de Warslik's Woods. On peut aussi l'obtenir en lui donnant un burnished wooden staff looté à Chardok (en prenant soin de le charmer avant...). Ce mob ne quitte jamais son ile, même si il aggro. Donc on peuty le combattre en melee, se sauver pour se soigner avec des bandages, et revenir le combattre... 
<br>&nbsp;<br>
Le morceau du milieu se loot sur un <b>rotting skeleton</b> dans les Dreadlands, loc +2100,-5100. Il a des place holders. Il respawn toutes les 6 mn.
<br>&nbsp;<br>
Le morceau du bas se loot sur the <b>Pained Soul</b> dans Trakanon's Teeth, près de l'entrée de Sebilis. Il a des place holders et respawne toutes les 8mn30. Il spawne en -1835,-4368 près de l'entrée de Sebilis.
<br>&nbsp;<br>
Rapporter ces 3 morceaux à <b>Slixin Klex</b>, un skeleton dans Burning Woods, loc -680,-1120.

<br>&nbsp;<br>
</font>&nbsp;<br></td></tr><tr><td colspan='2' bgcolor='#0B5040'><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2' color='white'><b>&nbsp;4. Medallion of the Kylong</b></font></td></tr><tr><td width ='10'>&nbsp;</td><td><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>&nbsp;<br>
Ce médaillon est en 3 morceaux.
<br>&nbsp;<br>
Le morceau du haut s'obtient en allant voir <b>Niblek</b>, un named ratman vivant au fond de Chardok. Il suffit de lui remettre un black sapphire et un ruby. Pour l'atteindre, il suffit de prendre le tunnel à gaiche de l'entrée du chateau (levitation nécessaire). Suivre le tunnel et prendre à droite à la première fourche. Au carrefour suivant, prendre à gauche. Puis à droite au carrefour d'après. Et longer toujour le mur de droite à partir de là. Niblek se trouve par là.
<br>&nbsp;<br>
Le morceau du mileu se loote sur <b>Verix Kylox's Remains</b> (+50,-600) dans Karnor's Castle.Il faut emprunter le tunnel dans le moat pour accéder à la salle. Le place holder est un "decayed Kylong" qui spawne toutes les 25 mn environ.
<br>&nbsp;<br>
Le morceau du bas se rammase par terre dans <b>Kaesora</b>, au premier étage de la library. Il respawne toutes les 2h10.
<br>&nbsp;<br>
Ramener ces trois morceaux au <b>Proffesor Akabao</b> dans le moulin de Make of Ill Omen.
<br>&nbsp;<br>
</font>&nbsp;<br></td></tr><tr><td colspan='2' bgcolor='#0B5040'><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2' color='white'><b>&nbsp;The Rune of Scale</b></font></td></tr><tr><td width ='10'>&nbsp;</td><td><font face='Verdana,Geneva,Arial,Helvetica,sans-serif' size='2'>&nbsp;<br>
Une fois les 4 objets récupéreés, les apporter à Emporer Ganak dans Trakanon's Teeth, et recevez la clé de Veeshan's Peak.
<br>&nbsp;<br>
</font>&nbsp;<br></td></tr></table>&nbsp;<br></font></td></tr></table>
</td></tr><tr><td>
<table width='680' border='0' cellspacing='0' cellpadding='0'>
<tr><td width='680' height='1'><img src='./img/commun/c01/carre50.gif' width='680' height='1' alt='' border='0'></td></tr>
<tr><td height='2'><img src='./img/commun/transparent.gif' height='2' alt='' border='0'></td></tr>
<tr>
<td width='680' align='left' valign='top'>
<img src='./img/commun/c01/carre50.gif' width='10' height='10' border='0' alt=''>
<img src='./img/commun/c01/carre60.gif' width='10' height='10' border='0' alt=''>
<img src='./img/commun/c01/carre70.gif' width='10' height='10' border='0' alt=''>
<img src='./img/commun/c01/carre80.gif' width='10' height='10' border='0' alt=''>
</td></tr>
</table>
</td></tr><tr><td align='center'>
<A target='_blank' href='http://www.eqloft.com/'><img src='./img/commun/hebergement.gif' width='122' height='31' border='0' alt=''></a></td></tr></table>

</body>
</html>
