<!--
                 This page has been created by Renaissance IT
   Renaissance Internet Technologies Copyright (c) 1999 All Rights Reserved.

             for more info on our products, please visit :
                        http://www.renaissance.nl/

	This script has been written by Roy Boverhof <rboverhof@renaissance.nl>
	
        Pagename                : credits.html
        Last Updated    		: 04-08-2000
-->

<HTML>
<HEAD>
	<TITLE>the Seekers of Lore : Credits</TITLE>
</HEAD>

<BODY BGCOLOR="#000000" TEXT="#000000" LINK="#000000" VLINK="#000000" ALINK="#000000">
<DIV ALIGN="CENTER">
<BR>
<!-- FGN Banner Code -->
<script language="JavaScript">
	<!-- Hide from old browsers
	var random = new Number(Math.floor(9999999 * Math.random())+1);

	// Modify to reflect site specifics
	page = "eqlore.com/";
	target = "@Top1,x02,x05,x08!Top1";

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript1.1" SRC="http://oascentral.cybereps.com/RealMedia/ads/adstream_jx.ads/' + page + 1 + random + target + '">');
	document.write('</SCR');
	document.write('IPT>');

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript">');
	document.write('_version=10; //-->');
	document.write('</SCR');
	document.write('IPT>');

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript1.1">');
	document.write('_version=11; //-->');
	document.write('</SCR');
	document.write('IPT>');

	document.write('<SCR');
	document.write('IPT LANGUAGE="JavaScript">');

	if (navigator.appVersion.indexOf('MSIE 3') != -1){
	document.write('<IFRAME MARGINWIDTH=0 MARGINHEIGHT=0 HSPACE=0 VSPACE=0 FRAMEBORDER=0 SCROLLING=no BORDERCOLOR="#000000" SRC="oascentral.cybereps.com/RealMedia/ads/adstream_sx.ads/' + page + random + target + '"></IFRAME>');
	  }
	else if (_version < 11) {
	document.write ('<A HREF="http://oascentral.cybereps.com/RealMedia/ads/click_nx.ads/' + page + random + target + '"><IMG SRC="http://oascentral.cybereps.com/RealMedia/ads/adstream_nx.ads/' + page + random + target + '"></a>');
	  }

	document.write('</SCR');
	document.write('IPT>');

	// End Hide -->
</script>
<!-- END FGN Banner Code --><BR>
<TABLE CELLSPACING = 0 CELLPADDING = 0 BORDER = 0>
<TR>
	<TD width="63"><IMG SRC = "graphics/topc000.jpg" WIDTH = 63 HEIGHT = 87></TD>
	<TD width="473"><IMG SRC = "graphics/topc001.jpg" WIDTH = 473 HEIGHT = 87></TD>
	<TD width="64"><IMG SRC = "graphics/topc002.jpg" WIDTH = 64 HEIGHT = 87></TD>
</TR>
	<TD width="63"></TD>
	<TD BGCOLOR="#BEA279" width="460">
	<DIV ALIGN="CENTER">
	<IMG SRC="graphics/credits_header.jpg" WIDTH ="200" HEIGHT ="50">
	<TABLE WIDTH="460">
	<TR><TD>

<TABLE BGCOLOR="#BEA279" width="430" CELLPADDING="5" CELLSPACING="5" ALIGN="center">
<TR>
<TD BGCOLOR="#BEA279" width="10"></TD>
<TD GCOLOR="#BEA279" width="410">
<FONT FACE="Verdana" SIZE="2">
<HR>

<B><A HREF="mailto:madwand@home.com">MadWand</A></B><BR>&nbsp;&nbsp; - <FONT SIZE="-1">Founder, Content, Graphics, Maps</FONT><BR><BR>

<B><A HREF="mailto:webmaster@loreseekers.com">Sorontar</A></B><BR>&nbsp;&nbsp; - <FONT SIZE="-1">Site Design, PHP3, MySQL, Site Hosting</FONT><BR><BR>

<B><A HREF="http://www.loreseekers.com/mem_detail.php3?search=58">Alchemys</A></B><BR>&nbsp;&nbsp; - <FONT SIZE="-1">PHP & Database Guru</FONT><BR><BR>

<B><A HREF="http://www.loreseekers.com/mem_detail.php3?search=46">Sora</A></B><BR>&nbsp;&nbsp; - <FONT SIZE="-1">and <A HREF="http://arctic.net" TARGET="_new">Arctic.Net</A> for their hosting of the mailing list</FONT><BR><BR>

<B>Frashii</B><BR>&nbsp;&nbsp; - <FONT SIZE="-1">Donation of webspace for our growing Lore!</FONT><BR><BR>

<B><A HREF="http://www.loreseekers.com/mem_detail.php3?search=924">Hyppy</A></B><BR>&nbsp;&nbsp; - <FONT SIZE="-1">Head Zookeeper</FONT><BR><BR>

<B>Zealott</B><BR>&nbsp;&nbsp; - <FONT SIZE="-1">Head Cartographer</FONT><BR><BR>

<B>Many Others!</B><BR>&nbsp;&nbsp; - <FONT SIZE="-1">Thanks to all who contibuted over the past year!</FONT><BR><BR>

<HR>
</FONT>
</TD>
<TD BGCOLOR="#BEA279" width="10"></TD>
</TR>
</TABLE>

	</TD></TR>
	</TABLE>
	<TD width="64"></TD>
<TR>
	<TD><IMG SRC = "graphics/botc000.jpg" WIDTH = 63 HEIGHT = 87></TD>
	<TD><IMG SRC = "graphics/botc001.jpg" WIDTH = 473 HEIGHT = 87></TD>
	<TD><IMG SRC = "graphics/botc002.jpg" WIDTH = 64 HEIGHT = 87></TD>
</TR>
</TABLE>
<BR>
<IMG SRC="http://service.bfast.com/bfast/serve?bfmid=1375281&siteid=40292692&bfpage=pc" BORDER="0" WIDTH="1" HEIGHT="1" NOSAVE ><A HREF="http://service.bfast.com/bfast/click?bfmid=1375281&siteid=40292692&bfpage=pc" TARGET="_new"><IMG SRC="http://affiliate.gamestop.com/affIMG/pc_120x60.gif" BORDER="0" WIDTH="120" HEIGHT="60" ALT="PC Games at GameStop.com"></A>
<BR>
<BR>
</DIV>
</BODY>
</HTML>
