<HTML>
<HEAD>
<TITLE>Welcome to Media and Games Online Network - MGON</TITLE>
<META name="description" content="MGON - The Gamer's Choice for gaming news. Get the hottest info from the gaming industry.
.">
<META name="keywords" content="MGON, MGO, Interviews, Game previews, Game downloads, Gaming Network, Articles, Gaming News, News, Multiplayer, Games, PC Games, Console Games, Reviews, Forum, MGON International AB, Action, Strategy, Simulation, Roleplay, Racing">
<META name="robots" content="index,follow">
<LINK rel="stylesheet" href="/pagestyle2.css">
<STYLE type="text/css">
<!--
-->
</STYLE>
<script language="JavaScript" type="text/javascript">
<!--
function go(where) {
  if(where != "void" && where!="") location.href = where;
}

function reply(tid,pid,cid,lang) {

  url = "/reply.phtml?tid=" + tid + "&pid=" + pid + "&id=" + cid + "&language=" + lang + '&ref=%2Farticleindex.phtml';
  ipwindow = open("","prewindow","scrollbars=yes,toolbar=no,height=400,width=400");
  ipwindow.location.href = url;
        
}

function rateit(id,vote) {
    if(vote != "") {
		document.rate.content_id.value = id;
		document.rate.vote.value = vote;
		document.rate.submit();
	}
}

function screenshot(cid,pid) {

  url = "/screenshot.phtml?cid=" + cid + "&pid=" + pid;
  ipwindow = open("","prewindow","scrollbars=yes,toolbar=no,height=630,width=710");
  ipwindow.location.href = url;
        
}

function relatedmedia(url) {

  ipwindow = open("","prewindow","scrollbars=yes,toolbar=no,height=300,width=300");
  ipwindow.location.href = url;
        
}
//-->
</script></HEAD>

<BODY bgcolor="#FFFFFF" text="#000000" link="#000000" vlink="#000000" alink="#000000" leftmargin="0" topmargin="0" marginwidth="0" marginheight="0" background="/images2/backgrounds/resize.gif">
<TABLE width="750" border="0" cellspacing="0" cellpadding="0"><TR><TD><!-- hostname =  -->


<SCRIPT language="JavaScript" type="text/javascript">
<!--
if (window != top) top.location.href = location.href;

     NS4 = (document.layers);
     IE4 = (document.all);
    ver4 = (NS4 || IE4);
     IE5 = (IE4 && navigator.appVersion.indexOf("5.")!=-1);
   isMac = (navigator.appVersion.indexOf("Mac") != -1);
  isMenu = (NS4 || (IE4 && !isMac) || (IE5 && isMac));

function popUp(){return};
function popDown(){return};

if (!ver4) event = null;

//-->
</SCRIPT>
<script language="JavaScript1.2" type="text/javascript">
<!--

if (isMenu) {
    menuVersion = 3;
    
    menuWidth = 100;
    childOverlap = 1;
    childOffset = -109;
    perCentOver = null;
    secondsVisible = .5;
    
    fntCol = "blue";
    fntSiz = "7";
    fntBold = true;
    fntItal = false;
    fntFam = "arial, helvetica";
    
    backCol = "#DDDDDD";
    overCol = "#FFCCCC";
    overFnt = "purple";
    
    borWid = 1;
    borCol = "black";
    borSty = "solid";
    itemPad = 3;
    
    imgSrc = "http://www.mgon.com/images/misc/menuarrow.gif";
    imgSiz = 10;
    
    separator = 1;
    separatorCol = "red";
    
    isFrames = false;      // <-- IMPORTANT for full window
    navFrLoc = "left";     // <-- display. see below
    
    keepHilite = true; 
    NSfontOver = true;
    clickStart = false;
    clickKill = false;
}

//-->
</script>
<SCRIPT language="JavaScript1.2" type="text/javascript">
<!--
if (isMenu) {

  //document.write("<SCRIPT LANGUAGE='JavaScript1.2' SRC='http://www.mgon.com/shared/js/hierArrays.js'><\/SCRIPT>");

arMenu1 = new Array(
105,184,"19",
"white","white",
"#813E09","#FF9216",
"black","black",
"&nbsp;Deus Ex","http://www.deusexcenter.com/common/quickLoginAndRedirect?id=&pw=&ref=/",0,
"&nbsp;Duke Nukem","http://www.dukenukemcenter.com/common/quickLoginAndRedirect?id=&pw=&ref=/",0,
"&nbsp;Elite Force","http://www.eliteforcecenter.com/common/quickLoginAndRedirect?id=&pw=&ref=/",0,
"&nbsp;Half Life","http://www.hlcenter.com/common/quickLoginAndRedirect?id=&pw=&ref=/",0,
"&nbsp;Halo","http://www.halocenter.com/common/quickLoginAndRedirect?id=&pw=&ref=/",0,
"&nbsp;Quake 3","http://www.q3center.com/common/quickLoginAndRedirect?id=&pw=&ref=/",0,
"&nbsp;<i>More Action Sites</i>","#",1
)

arMenu1_7 = new Array(

"&nbsp;Rainbow Six","http://www.rainbowsixcenter.com/common/quickLoginAndRedirect?id=&pw=&ref=/",0,
"&nbsp;Rune","http://www.runecenter.com/common/quickLoginAndRedirect?id=&pw=&ref=/",0,
"&nbsp;Soldier of Fortune","http://www.sofcenter.com/common/quickLoginAndRedirect?id=&pw=&ref=/",0,
"&nbsp;Team Fortress","http://www.fortresscenter.com/common/quickLoginAndRedirect?id=&pw=&ref=/",0,
"&nbsp;StrikeForce","http://www.strikeforcecenter.com/common/quickLoginAndRedirect?id=&pw=&ref=/",0,
"&nbsp;Tribes","http://www.tribescenter.com/common/quickLoginAndRedirect?id=&pw=&ref=/",0,
"&nbsp;<i>More Action Sites</i>","#",1
)

arMenu1_7_7 = new Array(

"&nbsp;Unreal","http://www.unrealcenter.com/common/quickLoginAndRedirect?id=&pw=&ref=/",0,
"&nbsp;Wheel of Time","http://www.wotgame.com/common/quickLoginAndRedirect?id=&pw=&ref=/",0,
"&nbsp;&nbsp;","#",0,
"&nbsp;&nbsp;","#",0,
"&nbsp;&nbsp;","#",0,
"&nbsp;&nbsp;","#",0,
"&nbsp;&nbsp;","#",0
)

arMenu2 = new Array(
105,268,"19",
"white","white",
"#003355","#0078C8",
"black","black",
"&nbsp;Black & White","http://www.bwcenter.com/common/quickLoginAndRedirect?id=&pw=&ref=/",0,
"&nbsp;Dark Reign","http://www.darkreigncenter.com/common/quickLoginAndRedirect?id=&pw=&ref=/",0,
"&nbsp;Ground Control","http://www.gccenter.com/common/quickLoginAndRedirect?id=&pw=&ref=/",0,
"&nbsp;Sacrifice","http://www.sacrificecenter.com/common/quickLoginAndRedirect?id=&pw=&ref=/",0,
"&nbsp;Worms","http://www.wormscenter.com/common/quickLoginAndRedirect?id=&pw=&ref=/",0
)

arMenu3 = new Array(
115,352,"19",
"white","white",
"#A40307","#E80005",
"black","black",
"&nbsp;Baldurs Gate","http://www.baldursgatehaven.com/common/quickLoginAndRedirect?id=&pw=&ref=/",0,
"&nbsp;Diablo","http://www.diablohaven.com/common/quickLoginAndRedirect?id=&pw=&ref=/",0,
"&nbsp;Horizons","http://www.horizonshaven.com/common/quickLoginAndRedirect?id=&pw=&ref=/",0,
"&nbsp;MUD's","http://www.mudcenter.com/common/quickLoginAndRedirect?id=&pw=&ref=/",0,
"&nbsp;Neocron","http://www.neocroncenter.com/common/quickLoginAndRedirect?id=&pw=&ref=/",0,
"&nbsp;Neverwinter &nbsp;Nights","http://www.neverwinterhaven.com/common/quickLoginAndRedirect?id=&pw=&ref=/",0,
"&nbsp;<i>More Roleplay Sites</i>","#",1
)

arMenu3_7 = new Array(

"&nbsp;Throne of Darkness","http://www.todhaven.com/common/quickLoginAndRedirect?id=&pw=&ref=/",0,
"&nbsp;Ultima","http://www.ultimahaven.com/common/quickLoginAndRedirect?id=&pw=&ref=/",0,
"&nbsp;Vampire","http://www.vampirehaven.com/common/quickLoginAndRedirect?id=&pw=&ref=/",0,
"&nbsp;&nbsp;","#",0,
"&nbsp;&nbsp;","#",0,
"&nbsp;&nbsp;","#",0,
"&nbsp;&nbsp;","#",0
)

arMenu4 = new Array(
105,436,"19",
"white","white",
"#004612","#009526",
"black","black",
"&nbsp;CManager","http://www.cmanagercenter.com/common/quickLoginAndRedirect?id=&pw=&ref=/",0,
"&nbsp;Creatures","http://www.homecreatures.com/common/quickLoginAndRedirect?id=&pw=&ref=/",0,
"&nbsp;Pokémon","http://www.pokeball.net/common/quickLoginAndRedirect?id=&pw=&ref=/",0,
"&nbsp;The Sims","http://www.thesimsresource.com/common/quickLoginAndRedirect?id=&pw=&ref=/",0,
"&nbsp;Tycoon","http://www.tycoonresource.com/common/quickLoginAndRedirect?id=&pw=&ref=/",0
)

arMenu5 = new Array(
105,520,"19",
"white","white",
"#383838","#8A8A8A",
"black","black",
"&nbsp;Racing Source","http://www.racingsource.com/common/quickLoginAndRedirect?id=&pw=&ref=/",0,
"&nbsp;Driver","http://www.driverhq.com/common/quickLoginAndRedirect?id=&pw=&ref=/",0
)

arMenu6 = new Array(
105,100,"19",
"white","white",
"#48003F","#B2009C",
"black","black",
"&nbsp;MGON","http://www.mgon.com/common/quickLoginAndRedirect?id=&pw=&ref=/",0,
"&nbsp;MGON - SE","http://se.mgon.com/common/quickLoginAndRedirect?id=&pw=&ref=/",0,
"&nbsp;ESports - Live","http://www.esports-live.com/common/quickLoginAndRedirect?id=&pw=&ref=/",0,
"&nbsp;Nintendo","http://www.nintendocenter.com/common/quickLoginAndRedirect?id=&pw=&ref=/",0,
"&nbsp;Playstation","http://www.playstationcenter.com/common/quickLoginAndRedirect?id=&pw=&ref=/",0,
"&nbsp;Playstation - SE","http://se.playstationcenter.com/common/quickLoginAndRedirect?id=&pw=&ref=/",0
)

arMenu7 = new Array(
105,1,"19",
"white","white",
"#101040","#101090",
"black","black",
"&nbsp;Edit Profile", "javascript:member()",0,
"&nbsp;Logout", "http://everquest.mgon.com/common/logout.phtml?ref=/articleindex.phtml",0
)

arMenu8 = new Array(
105,1,"19",
"white","white",
"#101040","#101090",
"black","black",
"&nbsp;Login","javascript:login()",0,
"&nbsp;New member","javascript:member()",0,
"&nbsp;Forgot it?","javascript:forgotit()",0)

}

//-->
</SCRIPT>
<SCRIPT language="JavaScript1.2" type="text/javascript">
<!--
if (isMenu) {
document.write("<SCRIPT LANGUAGE='JavaScript1.2' SRC='http://www.mgon.com/shared/js/hierMenus.js'><\/SCRIPT>");
}
function logout() {
  location.href = "http://everquest.mgon.com/common/logout.phtml?ref=/articleindex.phtml";
}
function login() {
  ipwindow = open("","Login","scrollbars=no,toolbar=no,height=200,width=240");
  ipwindow.location.href = "http://everquest.mgon.com/common/login.phtml?ref=www.mgon.com&page=/articleindex.phtml";        
}
function forgotit() {
  ipwindow = open("","Login","scrollbars=no,toolbar=no,height=250,width=400");
  ipwindow.location.href = "/common/forgotit.phtml";        
}
function member() {
  ipwindow = open("","Members","scrollbars=yes,toolbar=no,height=600,width=500");
  ipwindow.location.href = "http://everquest.mgon.com/common/members.phtml?ref=www.mgon.com&page=/articleindex.phtml";        
}
//-->
</SCRIPT>
<table width="100%" border="0" cellspacing="0" cellpadding="0" background="/images/network_nav/resize.gif">
  <tr> 
    <td><img src="/images/network_nav/left.gif" width="2" height="20"></td>
    <td><a href="#" onClick="javascript:login()" onMouseOver="popUp('elMenu8',event)" onMouseOut="popDown('elMenu8')"><img src="/images/network_nav/member_login.gif" width="97" height="20" border="0"></a></td>
    <td><a href="#" onMouseOver="popUp('elMenu6',event)" onMouseOut="popDown('elMenu6')"><img src="/images/network_nav/console_new.gif" width="84" height="20" border="0"></a></td>
    <td><a href="#" onMouseOver="popUp('elMenu1',event)" onMouseOut="popDown('elMenu1')"><img src="/images/network_nav/action.gif" width="84" height="20" border="0"></a></td>
    <td><a href="#" onMouseOver="popUp('elMenu2',event)" onMouseOut="popDown('elMenu2')"><img src="/images/network_nav/strategy.gif" width="84" height="20" border="0"></a></td>
    <td><a href="#" onMouseOver="popUp('elMenu3',event)" onMouseOut="popDown('elMenu3')"><img src="/images/network_nav/roleplay.gif" width="84" height="20" border="0"></a></td>
    <td><a href="#" onMouseOver="popUp('elMenu4',event)" onMouseOut="popDown('elMenu4')"><img src="/images/network_nav/simulation.gif" width="84" height="20" border="0"></a></td>
    <td><a href="#" onMouseOver="popUp('elMenu5',event)" onMouseOut="popDown('elMenu5')"><img src="/images/network_nav/racing.gif" width="85" height="20" border="0"></a></td><td width="100%">&nbsp;</td><td><A href="http://www.mgon.com/common/quickLoginAndRedirect?id=&pw=&ref=/"><img src="/images/network_nav/network.gif" width="144" height="20" border="0"></A></td>
  </tr>
</table>
<script language="javascript">
var compname='Ad/mgon';
</script>
<script language="javascript" src="http://www.rankyou.com/cpt_transfers/single_month_enter.js">
</script></TD></TR></TABLE>

<TABLE width="750" border="0" cellspacing="0" cellpadding="0">

  <TR> 

    <TD><IMG src="/images2/top/topleft.jpg" width="152" height="136" border="0" usemap="#Map"><MAP name="Map"><AREA shape="rect" coords="13,36,138,76" href="http://www.mgon.com" alt="MGON Home" title="MGON Home"></MAP></TD>

    <TD width="100%" background="/images2/top/resize.jpg"><IMG src="/images2/top/logo.jpg" width="455" height="136"></TD>

    <TD align="center"><IMG src="/images2/top/topright.jpg" width="142" height="136"></TD>

  </TR>

</TABLE>


<TABLE width="750" border="0" cellspacing="0" cellpadding="0" bgcolor="#000000">
	<TR> 
		<TD align="center" width="130"> 
			<TABLE width="100%" border="0" cellspacing="0" cellpadding="0">
				<TR> 
					<TD align="center" background="/images2/top/channelresize.gif"><OBJECT classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=4,0,2,0" width="120" height="60">
							<PARAM name=movie value="http://www.mgon.com/flashmovies/mgochannel2.swf">
							<PARAM name=quality value=high>
							<PARAM name="menu" value="false">
							<EMBED src="http://www.mgon.com/flashmovies/mgochannel2.swf" quality=high pluginspage="http://www.macromedia.com/shockwave/download/index.cgi?P1_Prod_Version=ShockwaveFlash" 
type="application/x-shockwave-flash" menu="false" width="120" height="60">
							</EMBED> 
						</OBJECT></TD>
				</TR>
				<TR> 
					<TD><IMG src="/images/top/channelbottom.gif" width="130" height="13"></TD>
				</TR>
			</TABLE>
		</TD>
		
    <TD align="center" width="490" valign="top"> 
      <span class="smalltext"><NOLAYER><IFRAME SRC="http://ad.se.doubleclick.net/adi/mgon.com/;sz=468x60;ord=981121760?" bgcolor="#000000" width="468" height="60" frameborder="no" border="0" MARGINWIDTH="0" MARGINHEIGHT="0" SCROLLING="no"><A HREF="http://ad.se.doubleclick.net/jump/mgon.com/;abr=!ie;sz=468x60;ord=981121760?"><IMG SRC="http://ad.se.doubleclick.net/ad/mgon.com/;abr=!ie;sz=468x60;ord=981121760?" border="0" height="60" width="468"></A></IFRAME></NOLAYER><ILAYER id="layer1" visibility="hidden" width="468" height="60" align="center"></ILAYER></span>    </TD>
		
    <TD width="130" align="center" valign="top"><IMG
SRC="http://service.bfast.com/bfast/serve?bfmid=1375281&siteid=34593362&bfpa
ge=pc" BORDER="0" WIDTH="1" HEIGHT="1" NOSAVE > <A
HREF="http://service.bfast.com/bfast/click?bfmid=1375281&siteid=34593362&bfp
age=pc" TARGET="_top"><IMG
SRC="http://affiliate.gamestop.com/affimg/120_pc3_gs.gif" BORDER="0"
WIDTH="120" HEIGHT="60" ALT="PC titles from Gamestop.com"></A></TD>
	</TR>
</TABLE>
 
<TABLE width="750" border="0" cellspacing="0" cellpadding="0">
  <TR> 
    <TD valign="top" width="130" align="center"> 
       
<TABLE width="130" border="0" cellspacing="0" cellpadding="0">
  <TR> 
    <TD><IMG src="/images2/buttons/sitecontent.gif" width="130" height="25"></TD>
  </TR>
</TABLE>
<table width="130" border="0" cellspacing="0" cellpadding="0">
  <tr bgcolor="#000E24"> 
    <td> 
      <table width="100%" border=0 cellpadding=0 cellspacing=1>
        <tr bgcolor="#000E24"> 
          <td style="border='1 solid #809ECB'" onMouseOver="style.backgroundColor='#809ECB'; style.cursor='hand'; style.border='1 solid #809ECB'" onMouseOut="style.backgroundColor='#000E24'; style.border='1 solid #809ECB';" height="21"> 
            <table width="100%" border="0" cellspacing="0" cellpadding="2">
              <tr> 
                <td bgcolor="#000E24" height="21" width="100%"><a href="/" class="navlinks" style="margin:0;"> 
                  <div><img src="/images2/misc/1pix.gif" width="1" height="1" border="0">&nbsp;<span class="navlinks">Home</span></div>
                  </a></td>
                <td class="Bolded"><font size="2" face="Verdana, Arial, Helvetica, sans-serif" color="#000E24">&laquo;</font></td>
              </tr>
            </table>
          </td>
        </tr>
        <tr bgcolor="#000E24"> 
          <td style="border='1 solid #809ECB'" onMouseOver="style.backgroundColor='#809ECB'; style.cursor='hand'; style.border='1 solid #809ECB'" onMouseOut="style.backgroundColor='#000E24'; style.border='1 solid #809ECB';" height="21"> 
            <table width="100%" border="0" cellspacing="0" cellpadding="2">
              <tr> 
                <td bgcolor="#000E24" height="21" width="100%"><a href="/news.phtml" class="navlinks" style="margin:0;"> 
                  <div><img src="/images2/misc/1pix.gif" width="1" height="1" border="0">&nbsp;<span class="navlinks">News</span></div>
                  </a></td>
                <td class="Bolded"><font size="2" face="Verdana, Arial, Helvetica, sans-serif" color="#000E24">&laquo;</font></td>
              </tr>
            </table>
          </td>
        </tr>
        <tr bgcolor="#000E24"> 
          <td style="border='1 solid #809ECB'" onMouseOver="style.backgroundColor='#809ECB'; style.cursor='hand'; style.border='1 solid #809ECB'" onMouseOut="style.backgroundColor='#000E24'; style.border='1 solid #809ECB';" height="21"> 
            <table width="100%" border="0" cellspacing="0" cellpadding="2">
              <tr> 
                <td bgcolor="#000E24" height="21" width="100%"><a href="/reviewindex.phtml" class="navlinks" style="margin:0;"> 
                  <div><img src="/images2/misc/1pix.gif" width="1" height="1" border="0">&nbsp;<span class="navlinks">Reviews</span></div>
                  </a></td>
                <td class="Bolded"><font size="2" face="Verdana, Arial, Helvetica, sans-serif" color="#000E24">&laquo;</font></td>
              </tr>
            </table>
          </td>
        </tr>
        <tr bgcolor="#000E24"> 
          <td style="border='1 solid #809ECB'" onMouseOver="style.backgroundColor='#809ECB'; style.cursor='hand'; style.border='1 solid #809ECB'" onMouseOut="style.backgroundColor='#000E24'; style.border='1 solid #809ECB';" height="21"> 
            <table width="100%" border="0" cellspacing="0" cellpadding="2">
              <tr> 
                <td bgcolor="#000E24" height="21" width="100%"><a href="/previewindex.phtml" class="navlinks" style="margin:0;"> 
                  <div><img src="/images2/misc/1pix.gif" width="1" height="1" border="0">&nbsp;<span class="navlinks">Previews</span></div>
                  </a></td>
                <td class="Bolded"><font size="2" face="Verdana, Arial, Helvetica, sans-serif" color="#000E24">&laquo;</font></td>
              </tr>
            </table>
          </td>
        </tr>
        <tr bgcolor="#000E24"> 
          <td style="border='1 solid #809ECB'" onMouseOver="style.backgroundColor='#809ECB'; style.cursor='hand'; style.border='1 solid #809ECB'" onMouseOut="style.backgroundColor='#000E24'; style.border='1 solid #809ECB';" height="21"> 
            <table width="100%" border="0" cellspacing="0" cellpadding="2">
              <tr> 
                <td bgcolor="#000E24" height="21" width="100%"><a href="/interviewindex.phtml" class="navlinks" style="margin:0;"> 
                  <div><img src="/images2/misc/1pix.gif" width="1" height="1" border="0">&nbsp;<span class="navlinks">Interviews</span></div>
                  </a></td>
                <td class="Bolded"><font size="2" face="Verdana, Arial, Helvetica, sans-serif" color="#000E24">&laquo;</font></td>
              </tr>
            </table>
          </td>
        </tr>

        <tr bgcolor="#000E24"> 
          <td style="border='1 solid #809ECB'" onMouseOver="style.backgroundColor='#809ECB'; style.cursor='hand'; style.border='1 solid #809ECB'" onMouseOut="style.backgroundColor='#000E24'; style.border='1 solid #809ECB';" height="21"> 
            <table width="100%" border="0" cellspacing="0" cellpadding="2">
              <tr> 
                <td bgcolor="#000E24" height="21" width="100%"><a href="/articleindex.phtml" class="navlinks" style="margin:0;"> 
                  <div><img src="/images2/misc/1pix.gif" width="1" height="1" border="0">&nbsp;<span class="navlinks">Articles</span></div>
                  </a></td>
                <td class="Bolded"><font size="2" face="Verdana, Arial, Helvetica, sans-serif" color="#000E24">&laquo;</font></td>
              </tr>
            </table>
          </td>
        </tr>
        <tr bgcolor="#000E24"> 
          <td style="border='1 solid #809ECB'" onMouseOver="style.backgroundColor='#809ECB'; style.cursor='hand'; style.border='1 solid #809ECB'" onMouseOut="style.backgroundColor='#000E24'; style.border='1 solid #809ECB';" height="21"> 
            <table width="100%" border="0" cellspacing="0" cellpadding="2">
              <tr> 
                <td bgcolor="#000E24" height="21" width="100%"><a href="/fileindex.phtml" class="navlinks" style="margin:0;"> 
                  <div><img src="/images2/misc/1pix.gif" width="1" height="1" border="0">&nbsp;<span class="navlinks">Downloads</span></div>
                  </a></td>
                <td class="Bolded"><font size="2" face="Verdana, Arial, Helvetica, sans-serif" color="#000E24">&laquo;</font></td>
              </tr>
            </table>
          </td>
        </tr>
        <tr bgcolor="#000E24"> 
          <td style="border='1 solid #809ECB'" onMouseOver="style.backgroundColor='#809ECB'; style.cursor='hand'; style.border='1 solid #809ECB'" onMouseOut="style.backgroundColor='#000E24'; style.border='1 solid #809ECB';" height="21"> 
            <table width="100%" border="0" cellspacing="0" cellpadding="2">
              <tr> 
                <td bgcolor="#000E24" height="21" width="100%"><a href="http://www.mgoforum.com/" class="navlinks" style="margin:0;"> 
                  <div><img src="/images2/misc/1pix.gif" width="1" height="1" border="0">&nbsp;<span class="navlinks">MGON 
                    Forum</span></div>
                  </a></td>
                <td class="Bolded"><font size="2" face="Verdana, Arial, Helvetica, sans-serif" color="#000E24">&laquo;</font></td>
              </tr>
            </table>
          </td>
        </tr>
      </table>
    </td>
  </tr>
</table>
<TABLE width="130" border="0" cellspacing="0" cellpadding="0">
  <TR> 
    <TD><IMG src="/images2/buttons/siteinfo.gif" width="130" height="25"></TD>
  </TR>
</TABLE>
<table width="130" border="0" cellspacing="0" cellpadding="0">
  <tr bgcolor="#000E24"> 
    <td> 
      <table width="100%" border=0 cellpadding=0 cellspacing=1>
        <tr bgcolor="#000E24"> 
          <td style="border='1 solid #809ECB'" onMouseOver="style.backgroundColor='#809ECB'; style.cursor='hand'; style.border='1 solid #809ECB'" onMouseOut="style.backgroundColor='#000E24'; style.border='1 solid #809ECB';" height="21"> 
            <table width="100%" border="0" cellspacing="0" cellpadding="2">
              <tr> 
                <td bgcolor="#000E24" height="21" width="100%"><a href="/company/" class="navlinks" style="margin:0;"> 
                  <div><img src="/images2/misc/1pix.gif" width="1" height="1" border="0">&nbsp;<span class="navlinks">The 
                    Company</span></div>
                  </a></td>
                <td class="Bolded"><font size="2" face="Verdana, Arial, Helvetica, sans-serif" color="#000E24">&laquo;</font></td>
              </tr>
            </table>
          </td>
        </tr>
        <tr bgcolor="#000E24"> 
          <td style="border='1 solid #809ECB'" onMouseOver="style.backgroundColor='#809ECB'; style.cursor='hand'; style.border='1 solid #809ECB'" onMouseOut="style.backgroundColor='#000E24'; style.border='1 solid #809ECB';" height="21"> 
            <table width="100%" border="0" cellspacing="0" cellpadding="2">
              <tr> 
                <td bgcolor="#000E24" height="21" width="100%"><a href="/mediakit/" class="navlinks" style="margin:0;"> 
                  <div><img src="/images2/misc/1pix.gif" width="1" height="1" border="0">&nbsp;<span class="navlinks">Our 
                    Mediakit</span></div>
                  </a></td>
                <td class="Bolded"><font size="2" face="Verdana, Arial, Helvetica, sans-serif" color="#000E24">&laquo;</font></td>
              </tr>
            </table>
          </td>
        </tr>
        <tr bgcolor="#000E24"> 
          <td style="border='1 solid #809ECB'" onMouseOver="style.backgroundColor='#809ECB'; style.cursor='hand'; style.border='1 solid #809ECB'" onMouseOut="style.backgroundColor='#000E24'; style.border='1 solid #809ECB';" height="21"> 
            <table width="100%" border="0" cellspacing="0" cellpadding="2">
              <tr> 
                <td bgcolor="#000E24" height="21" width="100%"><a href="/press.phtml" class="navlinks" style="margin:0;"> 
                  <div><img src="/images2/misc/1pix.gif" width="1" height="1" border="0">&nbsp;<span class="navlinks">Press 
                    Material</span></div>
                  </a></td>
                <td class="Bolded"><font size="2" face="Verdana, Arial, Helvetica, sans-serif" color="#000E24">&laquo;</font></td>
              </tr>
            </table>
          </td>
        </tr>
        <tr bgcolor="#000E24"> 
          <td style="border='1 solid #809ECB'" onMouseOver="style.backgroundColor='#809ECB'; style.cursor='hand'; style.border='1 solid #809ECB'" onMouseOut="style.backgroundColor='#000E24'; style.border='1 solid #809ECB';" height="21"> 
            <table width="100%" border="0" cellspacing="0" cellpadding="2">
              <tr> 
                <td bgcolor="#000E24" height="21" width="100%"><a href="/contactus/" class="navlinks" style="margin:0;"> 
                  <div><img src="/images2/misc/1pix.gif" width="1" height="1" border="0">&nbsp;<span class="navlinks">Contact 
                    Us</span></div>
                  </a></td>
                <td class="Bolded"><font size="2" face="Verdana, Arial, Helvetica, sans-serif" color="#000E24">&laquo;</font></td>
              </tr>
            </table>
          </td>
        </tr>
      </table>
    </td>
  </tr>
</table>    
<TABLE width="122" border="0" cellspacing="0" cellpadding="1" bgcolor="#000000" background="/images/misc/50x50pix.gif">
  <TR align="center"> 
          <TD><IMG SRC="http://service.bfast.com/bfast/serve?bfmid=1307357&siteid=36766142&bfpage=1" BORDER="0" WIDTH="1" HEIGHT="1" NOSAVE ><BR>
<A HREF="http://service.bfast.com/bfast/click?bfmid=1307357&siteid=36766142&bfpage=1" TARGET="_top">
<IMG SRC="http://www.gator.com/images/banners/gator_tired_120x90.gif" BORDER="0" WIDTH="120" HEIGHT="90" ALT="Gator fills out forms and remembers passwords!"></A><!--index: 1 num: 5 --></TD>
        </TR>
      </TABLE>
    </TD>
    <TD width="620" valign="top"> 
      <TABLE width="100%" border="0" cellspacing="0" cellpadding="0" background="/images2/sections/resize.gif">
        <TR> 
          <TD><IMG src="/images2/misc/1pixblack.gif" width="1" height="63"></TD>
          <TD width="100%" valign="bottom"> 
            <TABLE width="100%" border="0" cellspacing="0" cellpadding="0" background="/images2/misc/50x50pix.gif">
              <TR> 
                <TD height="28"><SPAN class="Bolded"><IMG src="/images2/misc/1pix.gif" width="11" height="1"></SPAN></TD>
              </TR>
            </TABLE>
          </TD>
          <TD align="right"><IMG src="/images2/sections/articles.gif" width="275" height="63"></TD>
        </TR>
      </TABLE>
      <TABLE width="100%" border="0" cellspacing="0" cellpadding="0">
        <TR> 
          <TD width="490"> 
            <TABLE width="100%" border="0" cellspacing="0" cellpadding="0">
              <TR> 
                <TD valign="top" width="100%" align="center"> 
                  <TABLE width="100%" border="0" cellspacing="0" cellpadding="0">
                    <TR>                 <TD valign="top" width="33%">
                  <TABLE width="100%" border="0" cellspacing="0" cellpadding="0">
                    <TR> 
                      <TD><IMG src="/images/category/article.gif" width="110" height="25"></TD>
                      <TD background="/images2/buttons/resize.gif" width="100%" class="bluebolded">31/01</TD>
                    </TR>
                  </TABLE>
            <TABLE width="100%" border="0" cellspacing="0" cellpadding="0">
<tr bgcolor="#000000">
                <TD background="/images2/articles/resize.gif"><A href="/articles.phtml?id=52352&language=en"><IMG src="/php-bin/getimage.inc?id=50136" width="137" height="85" border="0"></a></TD>
</tr>
<tr bgcolor="#000000">
                <TD height="25" bgcolor="#000000" class="smalltext">&nbsp;&nbsp;&nbsp;&nbsp;<A href="/articles.phtml?id=52352&language=en" class="yellowlinks">• Life in a Funhouse Mirror</A></TD>
</tr>
</table>
                  <TABLE width="100%" border="0" cellspacing="0" cellpadding="12">
                    <TR> 
                      <TD class="smalltext">Mike looks at society's obsession with reality-based entertainment, from reality-based TV shows like Big Brother to reality-based computer games like The Sims.</TD>
                    </TR>
                  </TABLE>
                </TD>                <TD valign="top" width="33%">
                  <TABLE width="100%" border="0" cellspacing="0" cellpadding="0">
                    <TR> 
                      <TD><IMG src="/images/category/article.gif" width="110" height="25"></TD>
                      <TD background="/images2/buttons/resize.gif" width="100%" class="bluebolded">24/01</TD>
                    </TR>
                  </TABLE>
            <TABLE width="100%" border="0" cellspacing="0" cellpadding="0">
<tr bgcolor="#000000">
                <TD background="/images2/articles/resize.gif"><A href="/articles.phtml?id=48484&language=en"><IMG src="/php-bin/getimage.inc?id=47625" width="137" height="85" border="0"></a></TD>
</tr>
<tr bgcolor="#000000">
                <TD height="25" bgcolor="#000000" class="smalltext">&nbsp;&nbsp;&nbsp;&nbsp;<A href="/articles.phtml?id=48484&language=en" class="yellowlinks">• Gaming Legends: Sonic</A></TD>
</tr>
</table>
                  <TABLE width="100%" border="0" cellspacing="0" cellpadding="12">
                    <TR> 
                      <TD class="smalltext">Sonic The Hedgehog has starred in over 20 games in the past 10 years, spawned comics, television shows, clothes, music and various fan clubs. Arguably Sega&#8217;s greatest success, Sonic began life as Sega&#8217;s answer to Mario. </TD>
                    </TR>
                  </TABLE>
                </TD>                <TD valign="top" width="33%">
                  <TABLE width="100%" border="0" cellspacing="0" cellpadding="0">
                    <TR> 
                      <TD><IMG src="/images/category/article.gif" width="110" height="25"></TD>
                      <TD background="/images2/buttons/resize.gif" width="100%" class="bluebolded">16/01</TD>
                    </TR>
                  </TABLE>
            <TABLE width="100%" border="0" cellspacing="0" cellpadding="0">
<tr bgcolor="#000000">
                <TD background="/images2/articles/resize.gif"><A href="/articles.phtml?id=47998&language=en"><IMG src="/php-bin/getimage.inc?id=45356" width="137" height="85" border="0"></a></TD>
</tr>
<tr bgcolor="#000000">
                <TD height="25" bgcolor="#000000" class="smalltext">&nbsp;&nbsp;&nbsp;&nbsp;<A href="/articles.phtml?id=47998&language=en" class="yellowlinks">• Covert Ops Essentials</A></TD>
</tr>
</table>
                  <TABLE width="100%" border="0" cellspacing="0" cellpadding="12">
                    <TR> 
                      <TD class="smalltext">When is a game review not quite a game review? Well this is a question that doesn&#8217;t come around too often. It is not that regular that we see products that we are really not sure how to categorise. Just recently Red Storms Covert Ops Essentials arrived on my doorstep for review. Now you may wonder why this is the case after it has been on shelves in the US for around 6 months. Well for some reason it has only just been decided that this title should be available to gamers in Sunny Australia. This for a start I am not too impressed with, having played each game quite avidly in the Rainbow 6 franchise.</TD>
                    </TR>
                  </TABLE>
                </TD> </TR>
                  </TABLE>
                  <TABLE width="100%" border="0" cellspacing="0" cellpadding="0" background="/images2/buttons/resize.gif">
                    <TR> 
                      <TD><IMG src="/images2/buttons/archive.gif" width="130" height="25"></TD>
                    </TR>
                  </TABLE>
                  <TABLE width="100%" border="0" cellspacing="1" cellpadding="0">
                    <FORM method="post" action="/articles.phtml">
                      <TR> 
                        <TD height="40"><IMG src="/images2/misc/1pix.gif" width="10" height="8"></TD>
                        <TD height="40" width="100%" nowrap class="smalltext"><SPAN class="Bolded"><SPAN class="bluebolded">Search 
                          Articles:&nbsp;</SPAN></SPAN>&nbsp; 
                          <INPUT type="text" name="search" class="formbody" size="14" maxlength="50" value="">
                          &nbsp; 
                          <SELECT name="rel_category" class="formbody">
                            <option  value="0">All</option>
<option  value="1">Action</option>
<option  value="15">Adventure</option>
<option  value="3">Hardware</option>
<option  value="16">Other</option>
<option  value="14">Peripherals</option>
<option  value="12">Racing</option>
<option  value="11">RPG</option>
<option  value="2">Simulation</option>
<option  value="4">Software</option>
<option  value="8">Sport</option>
<option  value="9">Strategy</option>
 
                          </SELECT>
                          &nbsp; &nbsp; 
                          <INPUT type="image" border="0" name="imageField2" src="/images2/buttons/search_go.gif" width="24" height="22" align="top">
                        </TD>
                        <TD height="40" class="Bolded" align="right"><IMG src="/images2/misc/1pix.gif" width="10" height="1"></TD>
                      </TR>
                    </FORM>
                  </TABLE>
                  <TABLE width="466" border="0" cellspacing="0" cellpadding="0">
                    <TR> 
                      <TD><IMG src="/images2/misc/coloredpix.gif" width="466" height="1"></TD>
                    </TR>
                    <TR> 
                      <TD height="30" class="smalltext">  Now displaying the 15 
                        latest Articles.  </TD>
                    </TR>
                  </TABLE>
                  <TABLE width="100%" border="0" cellspacing="0" cellpadding="0">
                    <TR> 
                      <TD class="smalltext" valign="top">&nbsp;</TD>
                      <TD width="50%" class="smalltext" valign="top">&nbsp;</TD>
                      <TD class="smalltext" valign="top" width="13%">&nbsp;</TD>
                      <TD class="smalltext" valign="top" width="20%">&nbsp;</TD>
                      <TD class="smalltext" valign="top" width="17%">&nbsp;</TD>
                      <TD class="smalltext" valign="top">&nbsp;</TD>
                    </TR>
                    <TR> 
                      <TD class="smalltext" valign="top"><IMG src="/images2/misc/1pix.gif" width="12" height="1"></TD>
                      <TD height="30" class="Bolded" valign="top" nowrap>Title<BR>
                      </TD>
                      <TD class="Bolded" valign="top" nowrap>Added</TD>
                      <TD class="Bolded" valign="top" nowrap>Author</TD>
                      <TD class="Bolded" valign="top" nowrap>Category</TD>
                      <TD class="smalltext" valign="top"><IMG src="/images2/misc/1pix.gif" width="12" height="8"></TD>
                    </TR>
                                  <TR> 
                <TD class="smalltext" valign="top">&nbsp;</TD>
                <TD height="25" nowrap><A href="/articles.phtml?id=52352&language=en">• Life in a Funhouse Mirror</A><SPAN class="yellowbolded"> - New!</SPAN></TD>
                <TD>31/01</TD>
                <TD>Mike</TD>
                <TD>Other</TD>
                <TD class="smalltext">&nbsp;</TD>
              </TR>              <TR> 
                <TD class="smalltext" valign="top">&nbsp;</TD>
                <TD height="25" nowrap><A href="/articles.phtml?id=48484&language=en">• Gaming Legends: Sonic</A><SPAN class="yellowbolded"> - New!</SPAN></TD>
                <TD>24/01</TD>
                <TD>Miff</TD>
                <TD>Other</TD>
                <TD class="smalltext">&nbsp;</TD>
              </TR>              <TR> 
                <TD class="smalltext" valign="top">&nbsp;</TD>
                <TD height="25" nowrap><A href="/articles.phtml?id=47998&language=en">• Covert Ops Essentials</A><SPAN class="yellowbolded"> - New!</SPAN></TD>
                <TD>16/01</TD>
                <TD>dale</TD>
                <TD>Action</TD>
                <TD class="smalltext">&nbsp;</TD>
              </TR>              <TR> 
                <TD class="smalltext" valign="top">&nbsp;</TD>
                <TD height="25" nowrap><A href="/articles.phtml?id=45467&language=en">• A MGON Carol</A></TD>
                <TD>27/12</TD>
                <TD>Jeff, Dem, Oscar, Mike, Morten & Miff - what a crew!</TD>
                <TD>Other</TD>
                <TD class="smalltext">&nbsp;</TD>
              </TR>              <TR> 
                <TD class="smalltext" valign="top">&nbsp;</TD>
                <TD height="25" nowrap><A href="/articles.phtml?id=43786&language=en">• Employee X: Part 3</A></TD>
                <TD>15/12</TD>
                <TD>Mike</TD>
                <TD>Action</TD>
                <TD class="smalltext">&nbsp;</TD>
              </TR>              <TR> 
                <TD class="smalltext" valign="top">&nbsp;</TD>
                <TD height="25" nowrap><A href="/articles.phtml?id=43433&language=en">• SMOCK! FRUNK! BOOM!</A></TD>
                <TD>13/12</TD>
                <TD>Mike</TD>
                <TD></TD>
                <TD class="smalltext">&nbsp;</TD>
              </TR>              <TR> 
                <TD class="smalltext" valign="top">&nbsp;</TD>
                <TD height="25" nowrap><A href="/articles.phtml?id=40368&language=en">• Employee X: Part 2</A></TD>
                <TD>29/11</TD>
                <TD>Mike</TD>
                <TD>Action</TD>
                <TD class="smalltext">&nbsp;</TD>
              </TR>              <TR> 
                <TD class="smalltext" valign="top">&nbsp;</TD>
                <TD height="25" nowrap><A href="/articles.phtml?id=41003&language=en">• Q3 Team Arena</A></TD>
                <TD>28/11</TD>
                <TD>Corven</TD>
                <TD></TD>
                <TD class="smalltext">&nbsp;</TD>
              </TR>              <TR> 
                <TD class="smalltext" valign="top">&nbsp;</TD>
                <TD height="25" nowrap><A href="/articles.phtml?id=40175&language=en">• Employee X</A></TD>
                <TD>22/11</TD>
                <TD>Mike</TD>
                <TD>Action</TD>
                <TD class="smalltext">&nbsp;</TD>
              </TR>              <TR> 
                <TD class="smalltext" valign="top">&nbsp;</TD>
                <TD height="25" nowrap><A href="/articles.phtml?id=39376&language=en">• Black & White</A></TD>
                <TD>15/11</TD>
                <TD>Mike</TD>
                <TD></TD>
                <TD class="smalltext">&nbsp;</TD>
              </TR>              <TR> 
                <TD class="smalltext" valign="top">&nbsp;</TD>
                <TD height="25" nowrap><A href="/articles.phtml?id=36400&language=en">• Devoted Fans</A></TD>
                <TD>18/10</TD>
                <TD>Morten</TD>
                <TD></TD>
                <TD class="smalltext">&nbsp;</TD>
              </TR>              <TR> 
                <TD class="smalltext" valign="top">&nbsp;</TD>
                <TD height="25" nowrap><A href="/articles.phtml?id=36290&language=en">• Microsoft Game-On Launch</A></TD>
                <TD>18/10</TD>
                <TD>Dale</TD>
                <TD></TD>
                <TD class="smalltext">&nbsp;</TD>
              </TR>              <TR> 
                <TD class="smalltext" valign="top">&nbsp;</TD>
                <TD height="25" nowrap><A href="/articles.phtml?id=35231&language=en">• Cyber Life</A></TD>
                <TD>17/10</TD>
                <TD>Miff</TD>
                <TD></TD>
                <TD class="smalltext">&nbsp;</TD>
              </TR>              <TR> 
                <TD class="smalltext" valign="top">&nbsp;</TD>
                <TD height="25" nowrap><A href="/articles.phtml?id=35178&language=en">• WAP Games</A></TD>
                <TD>06/10</TD>
                <TD>Miff</TD>
                <TD></TD>
                <TD class="smalltext">&nbsp;</TD>
              </TR>              <TR> 
                <TD class="smalltext" valign="top">&nbsp;</TD>
                <TD height="25" nowrap><A href="/articles.phtml?id=32566&language=en">• AO Cocktail Party</A></TD>
                <TD>02/10</TD>
                <TD>Ben Lewis</TD>
                <TD></TD>
                <TD class="smalltext">&nbsp;</TD>
              </TR> 
                  </TABLE>
                  <TABLE cellspacing="0" cellpadding="12" border="0" width="100%">
                    <TR> 
                      <TD>  For more articles and 
                        sort options, visit the <A href="/articles.phtml">archive &raquo;</A>  </TD>
                    </TR>
                  </TABLE>
                </TD>
              </TR>
            </TABLE>
          </TD>
          <TD valign="top" width="130" align="right" background="/images2/backgrounds/rightnav.gif"> 
            <TABLE width="100%" border="0" cellspacing="0" cellpadding="0">
              <TR> 
                <TD><IMG src="images2/buttons/feedback.gif" width="130" height="25"></TD>
              </TR>
              <TR> 
                <TD height="25" class="smalltext">&nbsp;&nbsp;&nbsp;<IMG src="/images2/misc/yellowarrow.gif" width="12" height="11"><A href="mailto:feedback@mgon.com">Submit Feedback!</A></TD>
              </TR>
              <TR> 
                <TD height="25" class="smalltext">&nbsp;&nbsp;&nbsp;<IMG src="/images2/misc/yellowarrow.gif" width="12" height="11"><A href="mailto:articles@mgon.com">Suggest Articles</A></TD>
              </TR>
              <TR> 
                <TD height="25" class="smalltext">&nbsp;&nbsp;&nbsp;<IMG src="/images2/misc/yellowarrow.gif" width="12" height="11"><A href="http://gimli.mgon.com/">Discuss This!</A></TD>
              </TR>
            </TABLE>
          </TD>
        </TR>
      </TABLE>
    </TD>
  </TR>
</TABLE>
 
<TABLE width="750" border="0" cellspacing="0" cellpadding="0">
  <TR> 
    <TD><IMG src="/images2/bottom/copyright.gif" width="340" height="30" border="0"><A href="/privacy.phtml"><IMG src="/images2/bottom/privacy.gif" width="101" height="30" border="0"></A></TD>
    <TD><IMG src="/images2/bottom/bottomplate.gif" width="177" height="30"></TD>
    <TD><A href="#top"><IMG src="/images2/bottom/top.gif" width="68" height="30" border="0"></A></TD>
    <TD><A href="/index.phtml"><IMG src="/images2/bottom/home.gif" width="64" height="30" border="0"></A></TD>
  </TR>
</TABLE>
<TABLE width="750" border="0" cellspacing="0" cellpadding="0" height="90" background="/images2/misc/50x50pix.gif">
  <TR bgcolor="#000000" align="center"> 
    <TD class="smalltext">
      <SCRIPT language="JavaScript"
src="http://adtegrity.spinbox.net/?DC=Mgon+Bottom&JS=Y&TARGET=_new">
</SCRIPT>
      <NOSCRIPT><A href="http://adtegrity.spinbox.net/?SHT=Mgon+Bottom" target="_new"
height="468" width="60"><IMG src="http://adtegrity.spinbox.net/?SIT=Mgon+Bottom" border="0"></A></NOSCRIPT></TD>
  </TR>
</TABLE>
<SCRIPT LANGUAGE="JavaScript">
/*

//<!--
Debug info
--------------------------------------
//Error 0:
Parsed part <!--part_IntroScreen-->
No sql info
No more details

//Error 1:
Parsed part <!--part_IntroText-->
No sql info
No more details

//Error 2:
Time spent in regexp: 0
No sql info
No more details

//Error 3:
Time spent in regexp: 0
No sql info
No more details

//Error 4:
Time spent in regexp: 0
No sql info
No more details

//Error 5:
Time elapsed in listContent: 0.045403957366943
No sql info
No more details

//Error 6:
Time spent in regexp: 0
No sql info
No more details

//Error 7:
Time spent in regexp: 0
No sql info
No more details

//Error 8:
Time spent in regexp: 0
No sql info
No more details

//Error 9:
Time spent in regexp: 0
No sql info
No more details

//Error 10:
Time spent in regexp: 0
No sql info
No more details

//Error 11:
Time spent in regexp: 0
No sql info
No more details

//Error 12:
Time spent in regexp: 0
No sql info
No more details

//Error 13:
Time spent in regexp: 0
No sql info
No more details

//Error 14:
Time spent in regexp: 0
No sql info
No more details

//Error 15:
Time spent in regexp: 0
No sql info
No more details

//Error 16:
Time spent in regexp: 0
No sql info
No more details

//Error 17:
Time spent in regexp: 0
No sql info
No more details

//Error 18:
Time spent in regexp: 0
No sql info
No more details

//Error 19:
Time spent in regexp: 0
No sql info
No more details

//Error 20:
Time spent in regexp: 0
No sql info
No more details

//Error 21:
Time elapsed in listContent: 0.03643798828125
No sql info
No more details

22 errors.


Queries
--------------------------------------
Query 0:
Query: SELECT co.ID AS ID,co.icon AS icon,co.section AS section,co.header AS header,UNIX_TIMESTAMP(co.created) AS created,co.creatorname as nick,co.creatoremail as email,s.name as section_name,s.location as url,co.language AS language, `tIntroScreen`.value AS `part_IntroScreen`, `tIntroText`.value AS `part_IntroText`,s.image1 AS sectionImage1,s.image2 AS sectionImage2 FROM content AS co INNER JOIN content_sections AS s ON(co.section = s.ID) LEFT JOIN content_parts AS `tIntroScreen` ON(`tIntroScreen`.name = 'IntroScreen' AND `tIntroScreen`.parent = co.ID AND `tIntroScreen`.language = co.language) LEFT JOIN content_parts AS `tIntroText` ON(`tIntroText`.name = 'IntroText' AND `tIntroText`.parent = co.ID AND `tIntroText`.language = co.language) WHERE co.published=1  AND co.section=476 AND co.language='en'  ORDER BY co.created DESC LIMIT 0, 3
Result: OK
User: php
Database server: localhost()
Time: 0.032071948051453 seconds

Query 1:
Query: SELECT COUNT(DISTINCT co.ID) FROM content AS co INNER JOIN content_sections AS s ON(co.section = s.ID) LEFT JOIN content_parts AS `tIntroScreen` ON(`tIntroScreen`.name = 'IntroScreen' AND `tIntroScreen`.parent = co.ID AND `tIntroScreen`.language = co.language) LEFT JOIN content_parts AS `tIntroText` ON(`tIntroText`.name = 'IntroText' AND `tIntroText`.parent = co.ID AND `tIntroText`.language = co.language) WHERE co.published=1  AND co.section=476 AND co.language='en' 
Result: OK
User: php
Database server: localhost()
Time: 0.0068550109863281 seconds

Query 2:
Query: SELECT rel_category FROM content_sections WHERE ID=476
Result: OK
User: php
Database server: localhost()
Time: 0.00055098533630371 seconds

Query 3:
Query: SELECT ID,name FROM relations_category  ORDER BY name ASC
Result: OK
User: php
Database server: localhost()
Time: 0.00057792663574219 seconds

Query 4:
Query: SELECT DISTINCT co.ID AS ID,co.icon AS icon,co.section AS section,co.header AS header,UNIX_TIMESTAMP(co.created) AS created,co.creatorname as nick,co.creatoremail as email,s.name as section_name,s.location as url,co.language AS language, UNIX_TIMESTAMP(co.created) - UNIX_TIMESTAMP() AS new, rcategory.name AS rel_category FROM content AS co INNER JOIN content_sections AS s ON(co.section = s.ID) LEFT JOIN content_relations AS rel ON(rel.parent = co.ID) LEFT JOIN relations_category AS rcategory ON (rcategory.ID = rel.category) WHERE co.published=1  AND co.section=476 AND co.language='en'  ORDER BY co.created DESC LIMIT 0, 15
Result: OK
User: php
Database server: localhost()
Time: 0.010313987731934 seconds

Query 5:
Query: SELECT COUNT(DISTINCT co.ID) FROM content AS co INNER JOIN content_sections AS s ON(co.section = s.ID) LEFT JOIN content_relations AS rel ON(rel.parent = co.ID) LEFT JOIN relations_category AS rcategory ON (rcategory.ID = rel.category) WHERE co.published=1  AND co.section=476 AND co.language='en' 
Result: OK
User: php
Database server: localhost()
Time: 0.0025070905685425 seconds

6 queries.
-->
*/

</SCRIPT>
<!--Bottom Layer-->
<LAYER SRC="http://ad.se.doubleclick.net/adl/mgon.com/;sz=468x60;ord=981121760?" bgcolor="#000000" width="468" height="60" visibility="hidden" onLoad="moveToAbsolute(layer1.pageX,layer1.pageY);clip.height=60;clip.width=468; visibility='show';"></LAYER><!--End Bottom Layer--></BODY>

</HTML>


